### ISSUE TITLE
Energy Storage multiblock detection

### ISSUE THREAD

**Issue by pennywis3** [brandon3055/Draconic-Evolution#10]
Currently the Energy Core will only check for 6 specific Draconium blocks to see if the multiblock is valid but returns the full structure on deconstruction.
![2015-02-12_02 15 51](https://cloud.githubusercontent.com/assets/4288061/6160014/b0a2b5ec-b25d-11e4-8f9b-aac06a6372ba.png)
![2015-02-12_02 15 57](https://cloud.githubusercontent.com/assets/4288061/6160015/b2dc9d8c-b25d-11e4-8417-2d365914a075.png)
![2015-02-12_02 16 01](https://cloud.githubusercontent.com/assets/4288061/6160017/b45e4a0c-b25d-11e4-9a1d-32ec4bedf8ca.png)

**Comment by brandon3055** [comment]
That is not a bug. It is a feature that allows you quickly build a core in creative mode. It does not work in survival mode.
