### ISSUE TITLE
Sounds.json issue.

### ISSUE THREAD

**Issue by jjoonn56** [brandon3055/Draconic-Evolution#100]
So idk what is causing this, I was able to play perfectly fine one second, then I was disconnected and when I try to log in I get kicked with a terminal error. I don't crash, I just get disconnected from the server. The server does not crash, nor is it affected in any way. No output to console other than me getting disconnected. Here is whats in the log: 

http://pastebin.com/KeNPW9Vj

And no I do not have a resource pack. This is a fresh install.

**Comment by brandon3055** [comment]
Thats rather odd... Have you tried re downloading the mod? Also can you please post the entire log.

**Comment by jjoonn56** [comment]
Here you go: http://pastebin.com/VBLXcr8y

And I have done fresh installs of the pack. I have also not changed Draconic Evolution at all. Just yesterday I was able to play fine, then all of a sudden I cant.

**Comment by brandon3055** [comment]
Hmm... Is it possible something changed on the server side? Unfortunately JSON errors are a pain to figure out because there is nothing in the problem indicating the cause of the problem. But sound is mostly handled client side so thats probably not the reason you are betting kicked from the server.

**Comment by brandon3055** [comment]
Did you ever manage to get this sorted out?

**Comment by GreatOrator** [comment]
Logs provided don't show the connection error and does not show anything in particular that would cause a disconnect or crash
