### ISSUE TITLE
Glowing Outlines of Blocks

### ISSUE THREAD

**Issue by wolfbane1021** [brandon3055/Draconic-Evolution#1001]
## Base information
* Minecraft version: 1.10.2
* Mod version: 1.10.2-2.1.6.263
* Minecraft Forge version: 12.18.3.2477
* Mod Pack: SkyFactory 3

## Description
  I'm seeing these glowing green/purple outlines of some energy relays and energy I/O crystals and they wont go away. I can see most of them through blocks but there's one that I can constantly see and one that only shows up if I get close to it. I've tried severing all links, breaking and replacing blocks, placing other blocks in their place, rebooting, all end with nothing. I've also tried looking online for any fixes and asked around on the server I'm playing on and still no luck. These outlines also shape themselves to whatever block is place in that spot. Draconic Evolution or not.

Images Below:

![outline1](https://user-images.githubusercontent.com/34698934/34198098-25fd92a8-e537-11e7-9b6d-d98ec80a3dd5.png)

![image](https://user-images.githubusercontent.com/34698934/34198165-5e2bde64-e537-11e7-8e5b-0c99259cea8e.png)

  I'm not holding the crystal binder or anything and I don't believe I did anything special. Just the normal crouch+right click to start link and then right click to link. Is there anything I can do to fix this? Am I just missing something? These outlines are very annoying lol.

Edit*
  I've noticed I only see the outlines through blocks when I'm hovering over a block with my cursor. When I'm just looking at air they aren't visible. However the one outline that's in the air I still see all the time and I believe I should only be seeing the outlines of things if I'm looking at say an energy I/O crystal and it's showing me what it's connected to.

**Comment by brandon3055** [comment]
I am very confused rite now... No matter how bad anything breaks there is not code in DE that would do this. Even the binder would not do this because it does not specifically render on crystals. It renders on whatever "single" block its bound to.
The only possible conclusion i can think of is some mod in your pack is rendering selection bounding boxes on my crystals. But i have absolutely no idea why...

**Comment by wolfbane1021** [comment]
Huh, well hearing confirmation that it's not a DE thing made it much easier to find a solution. Apparently it's caused by the Ring of Loki from the Botania mod. Kind of feel dumb I didn't just google "SkyFactory 3 glowing box" rather than "Draconic Evolution going box". Thanks for the reply though, still helped lol.
