### ISSUE TITLE
Have a question?

### ISSUE THREAD

**Issue by joshuasuperboy** [brandon3055/Draconic-Evolution#1006]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic Evolution 1.12-2.3.5.269-universal
* Minecraft Forge version: 1.12.2-forge1.12.2-14.23.1.2566
* Mod Pack: My own modpack

There is no crash report

I wanted to ask if there is a way to disable the war of the enderman after killing the ender dragon and taking the egg. I do not want to have my world completely destroyed by enderman. Can i disable that from happening by disabling modgriefing via commands.

**Comment by brandon3055** [comment]
No. They will stop spawning when the ritual finishes. It should not spawn enough of them to cause issues. unless your server is already close to its performance limit.

**Comment by joshuasuperboy** [comment]
Oh k thanks
