### ISSUE TITLE
Suggestion - Reactor Shield (cosmetic)

### ISSUE THREAD

**Issue by AJSarley223** [brandon3055/Draconic-Evolution#1007]
This isn't really crucial to the mod in general, but I noticed something weird about the texture on the Reactor Shield (the blue containment field that surrounds the draconic reactor). In the image below, the Cyan parts of the shield are transparent while the darker Blue is opaque, resulting in a weird "tie-dye" effect.

![reactor_videocapture](https://user-images.githubusercontent.com/30648583/34450532-0b510b64-ecd1-11e7-8dbf-8209c3fdad95.PNG)

For visual aid, below is a quick and dirty mockup I made in Blender with the opacity swapped, which appears to "glow" more. Can you do something like this in the next version?

 ![reactormockup](https://user-images.githubusercontent.com/30648583/34450453-92804846-ecce-11e7-8797-65af4f1076b4.gif)

**Comment by brandon3055** [comment]
I may look into this but a simple inversion would probably brake at different shield strengths.
