### ISSUE TITLE
Advanced Dislocator Baubles Slot?

### ISSUE THREAD

**Issue by SgtSnipey** [brandon3055/Draconic-Evolution#1009]
Great Mod For Starters Love It! Keep Up Your Amazing Work!  Great Job on the graphics ands renders for things like the Armors, Armor Shield, And the Reactor itself are just Amazing! Now for the part where I ask for something.

I was wondering if you would be willing to let us put and use the Advanced Dislocator in a baubles slot. With a key to get it open and then be used? I was thinking the chest slot because of how powerful it is . I'll understand if the answer is no. Just figured I'd ask. :D

**Comment by joshuasuperboy** [comment]
Thats a pretty good idea and make the draconic capacitor go in the baubles slot to, instead it filling up a inventory slot.
