### ISSUE TITLE
Xp Not realy working

### ISSUE THREAD

**Issue by Goten87** [brandon3055/Draconic-Evolution#101]
hello Brandon
i just tested a newer version of your mod
i see that the vanilla items are good and get the XP right into the XP bar now im doing Certus quarts ore
and the XP drops on the ground again
so i think this is a bug

**Comment by brandon3055** [comment]
I add the xp to your bar by calculating the amount of xp the ore drops using the vanilla xp system which all mods should use. If certus quartz still drops xp orbs that means it dose not use the vanilla system and there is not much i can do about that.

**Comment by Goten87** [comment]
Ok so I need to complain at ae2 about it then sins it's from that mod

**Comment by brandon3055** [comment]
pretty much but i dont think its a big deal. Your probably never going to mine enough quartz ore for it to be a problem.
