### ISSUE TITLE
Creative Flight Toggle

### ISSUE THREAD

**Issue by JimJoyy** [brandon3055/Draconic-Evolution#1010]
## Base information
* Minecraft version: 1.10.2
* Mod version: 1.10.2-2.1.7.266
* Minecraft Forge version: 12.18.3.2511
* Mod Pack: Ozone Lite

More than an issue, its more of an question/request

Back in 1.7 version of the mod there was a bind that essentially pressed your space twice. As someone used to jetpacks hover toggle a lot, i find myself missing the ability to start falling with a press of a button. Is this bind coming back in 1.10 release? is it there and im just unable to find it?

**Comment by brandon3055** [comment]
Somehow that got missed in the 1.10 update.
I will probably re add it but probably only in 1.12+

**Comment by JimJoyy** [comment]
Well then, AHK TO THE RESCUE!
Thanks for answer :D

**Comment by brandon3055** [comment]
ok will be in the next release.
As it was basically a strait copy paste it will also be in the next 1.10 release.
