### ISSUE TITLE
Crash with EnderIO Capacitor Bank

### ISSUE THREAD

**Issue by BrisingrAerowing** [brandon3055/Draconic-Evolution#1011]
## Base information
* Minecraft version: 1.10.2
* Mod version: 2.1.8.273
* Minecraft Forge version: 2511
* Mod Pack: (if applicable) N/A

## Crash report
[Crash Report](https://gist.github.com/BrisingrAerowing/fff0ea60118015968181e4aaaaf8f180)

This happened when placing an Ender IO Creative Capacitor into my inventory with an active Creative Flux Capacitor set to charge Armor and Held Items.

**Comment by covers1624** [comment]
EnderIO issue, this has been reported before. Their item states that it has a capability then gives us null when we actually ask it for the capability.
