### ISSUE TITLE
Llama soul named "Pig Soul"

### ISSUE THREAD

**Issue by ouroborus** [brandon3055/Draconic-Evolution#1013]
Llama souls generate with the name "Pig Soul".

![2018-01-03_21 21 16](https://user-images.githubusercontent.com/392047/34551269-fd1a81d8-f0cc-11e7-9456-b524ed18be2f.png)

## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.5.269
* Minecraft Forge version: 14.23.1.2570
* Mod Pack: ATM3 v5.5

**Comment by brandon3055** [comment]
This will be fixed in the next release.
