### ISSUE TITLE
Editing fusion crafting wont work

### ISSUE THREAD

**Issue by loverguy** [brandon3055/Draconic-Evolution#1016]
i'm trying to balance my modpack by editing every recipe i've tried to edit the fusion crafting but didn't worked this is the file: http://textuploader.com/dcepf

**Comment by covers1624** [comment]
Can we get a full log for this one. Also i recommend using https://jsonlint.com/ if you are editing jsons without a smart editor.

**Comment by loverguy** [comment]
[latest.log](https://github.com/brandon3055/Draconic-Evolution/files/1609688/latest.log) this is the log file and what the best smart editor please ?

**Comment by covers1624** [comment]
I would recommend https://www.sublimetext.com/ otheriwse any jetbains product such as Intellij IDEA. The actual issue here is in your json, it is not formatted properly.
