### ISSUE TITLE
Mob Soul Issue

### ISSUE THREAD

**Issue by CallMehHypnos** [brandon3055/Draconic-Evolution#1017]
## Base information
* Minecraft version: 1.10.2
* Mod version: _probably 1.10.2, sorry I'm a noob_
* Minecraft Forge version: _forge-12.18.3.2477, hope this helps_
* Mod Pack: (if applicable) SkyFactory 3

## Crash report
```
"CRASH REPORT HERE"
```
It's not really a crash so I decided to delete that and write my own text here.

I've been trying to get a Mob Soul from a Villager using the Reaper enchantment but I have not had any success doing so, so I wanted to give it to me by using this command:
/give @p draconicevolution:mobSoul 1 0 {EntityName:Villager]
.

I've been trying it with other Entities as well but I always get the message:
"There is no such item with name draconicevolution:mobSoul."

So, what do I do? I'm kind of clueless. I wanted to set up a Villager Spawner for my Blood Altar (Blood Magic) but I cannot seem to get the soul for it :/.

I hope to get some tips soon as I cannot really progress further at the moment. If needed, I can provide screenshots taken in my Singleplayer world!

CallMehHypnos

**Comment by brandon3055** [comment]
Due to a change in minecrafts naming requirements the names of all items now use snake_case meaning the command you need is
`/give @p draconicevolution:mob_soul 1 0 {EntityName:Villager}`

**Comment by CallMehHypnos** [comment]
It worked! Thanks a lot! I'll close this now :)
