### ISSUE TITLE
Recipes that are shift-clicked into the crafting component of a Draconium Chest are not added properly.

### ISSUE THREAD

**Issue by Xyphin** [brandon3055/Draconic-Evolution#1018]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12 - 2.3.5.269 (2.3.5)
* Minecraft Forge version: 14.23.1.2566
* Mod Pack: Direwolf20 1.12

## Description 
You'll have to forgive me if any of the information in this report is a bit confusing - I'm somewhat new to Minecraft, and I wasn't the one who setup the server. :( I turned debug information on for my screenshots, so hopefully that clarifies any versioning issues.

I recently built the Draconium Chest, and I noticed that when shift clicking a recipe into the crafting area, the pattern is misaligned and often doesn't add all the items in properly. I have added screenshots below. There was a [similar issue](https://github.com/brandon3055/Draconic-Evolution/issues/37) raised by another user when attempting to use this chest as part of an automated system, but it has since been closed.

The target pattern:
![recipe_issue_target](https://user-images.githubusercontent.com/35203109/34654830-a82017ce-f3b5-11e7-885c-ee3a68dfeefd.png)

After shift+clicking:
![recipe_issue_post_click](https://user-images.githubusercontent.com/35203109/34654829-a807ffd6-f3b5-11e7-8b40-92d583741047.png)

**Comment by brandon3055** [comment]
Thanks for letting me know about this. It will be fixed in the next update.
