### ISSUE TITLE
Fusion Controller

### ISSUE THREAD

**Issue by MelanX** [brandon3055/Draconic-Evolution#1019]
I have a suggestion:
What's about a block which is better for Fusion Crafting. So, you wanna automate all your recipes by AE2 or RS. But now there is no perfect solution which works everytime. A block which controls everything would be nice.

**Comment by brandon3055** [comment]
Fusion crafting isnt meant to be dead simple. Its supposed to take some effort and ingenuity to automate. Its more fun that way anyway. That said DE does have an api that would make it possible for someone to create an addon that could do this but i dont think i will be adding it to the base game.
