### ISSUE TITLE
Draconic Mob grinder.. Not grinding enemies? 

### ISSUE THREAD

**Issue by Gilgreth** [brandon3055/Draconic-Evolution#102]
Simply put, I have the DE-Grinder set up in my kill room connected to Ender IO Ender Cable from my Reactor so it has PLENTY of power. But it just simply isn't killing mobs. It doesn't to anything but spin the fan it has. Is there something I missed?

**Comment by GreatOrator** [comment]
Version of DE and pics showing the Grinder GUI to verify it has power?

**Comment by Gilgreth** [comment]
1.0.1c
I've powered it via Coal, Coal Coke, and RF. Bar is climbing and fully red. But doesn't kill anything. Do you have to have it in a specific position?

**Comment by Gilgreth** [comment]
Rotated for the fan to be in the back. Mobs are getting 
pushed into it and still not being ground up.

**Comment by Gilgreth** [comment]
http://puu.sh/i4asS/2176633cb9.jpg

**Comment by GreatOrator** [comment]
What other mods are you using and can you look at the console to see if there are any messages output?

Can not duplicate in other modpacks or on it's own, though coal does make it run significantly slower.

**Comment by primetoxinz** [comment]
is it getting a redstone signal from something? that can turn it off

**Comment by Gilgreth** [comment]
I'm running the Mech&Magic pack. and there aren't any messages regarding the item or Draconic Evolution except for me accessing the GUI. There is no redstone signals near it at all. and to power it i've used Coal and it fills completely then drops to 0 when the first mob gets to it. 

Using RF it stays full constantly and never drops. so I'm not sure.

**Comment by brandon3055** [comment]
The fact that the RF buffer is dropping when running on coal means that it is trying to kill the mobs but something is stopping it. Are you by any chance on a bukkit/cauldron server? Or are there any other mods installed that may prevent a fake player from killing mobs? 

Can you also check if autonomous activator can kill mobs. That will tell me if it is just a problem with DE or a problem with fake players in general in your pack.

**Comment by Gilgreth** [comment]
Test with Autonomus Activator Complete. item does not kill mobs either. Server is also a Bukkit based server. Not sure how to fix it from there by enabling it. if I can that is.

**Comment by GreatOrator** [comment]
Check with your server admin, but does your server use a plugin like towny or mytown?

**Comment by Gilgreth** [comment]
We do not use the Towny or Mytown plugins.

**Comment by Gilgreth** [comment]
How would I be able to find the specific config file for the "fake players?"

**Comment by Gilgreth** [comment]
PlayerAPI was added to server. Fixed some automated issues with fake players but Autonomous Activator's left click function is inoperable. Draconic Evolution Mob Grinder still ceases to function as intended.

**Comment by brandon3055** [comment]
That depends on what plugin is stopping it. We had the same problem ion a server that i play on and it was todo with a plugin that allows unpayed (hacked) clients to connect to the server. Dose your server run anything like that?

**Comment by Prophious** [comment]
griefing protection plugin may be causing some issues there, because its a "fake player" so in a sense you have to allow it to grief your blocks/mobs, maybe by adding in player "Draconic-Evolution" to your claim

**Comment by GreatOrator** [comment]
Since there has been no further information and it seems to be a plugin issue, closing.
