### ISSUE TITLE
What About adding a New Armor Set?

### ISSUE THREAD

**Issue by InterPlay02** [brandon3055/Draconic-Evolution#1021]
Hello!

Today I am asking myself: What if Draconic Evolution Have a New Armor Set?
The Chaos Armor! Or Chaotic Armor... Whatever...

This would be REEEEEAAALLYY cool! So, the modpack creators use it as their final goal in to their modpacks! And, also: What if you make it's recipe not available on JEI? Suuuper cool!
Any wishes on adding this kind of things?

**Comment by InterPlay02** [comment]
PS.: Check out my Pull Request! I updated the pt-BR lang file!

**Comment by brandon3055** [comment]
This is planned for the next big DE re write (which i have not actually started yet)
