### ISSUE TITLE
Freeze when cactus or similar depletes the shield of Wyvern Armor

### ISSUE THREAD

**Issue by Maxwell-lt** [brandon3055/Draconic-Evolution#1022]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.8.279-universal
* Minecraft Forge version: 14.23.1.2577
* Mod List: https://gist.github.com/Maxwell-lt/928f48a79c6c98409474e59bbacd30c2

## Description
When walking into a cactus, normally entropy rises, shields fall, and eventually the player starts taking damage. Occasionally, when the shield meter reaches zero, the game freezes. I was able to reproduce this error twice, once with a cactus and once with the Ender Lilly from Extra Utilities 2. Both the client and the server experience the freeze, the server dropping to a tick rate of zero for between 1 and 5 minutes.

## Steps to reproduce:
* Equip a set of charged Wyvern Armor (I had Protection IV on every piece)
* Walk into a cactus
* Wait for the shield meter to reach zero

Note that this bug is not reproducible 100% of the time. I only was able to trigger it twice, though I tried around a dozen times.

## Crash report
The mod didn't quite crash as much as freeze both the client and server while generating about 2 million lines of stacktraces (I only have access to client-side logs). I've cut the first and last 10,000 lines of stacktraces, but you can also check out the full fml-client-latest.log if necessary.
* First 10,000: https://gist.github.com/Maxwell-lt/8bf9dfe68807f47a6e9d9423bd27871c
* Last 10,000: https://gist.github.com/Maxwell-lt/3f66eccd10bc97b6d5809c9f20541b74
* Full session log (300MB file, relevant content starts after about 27,500 lines): https://drive.google.com/open?id=1yC4K5LPBsu9oF-VcVjDB99_Y0euLu8h7

**Comment by MrLightningBlaze** [comment]
I happen to get the same log errors when I fall into lava with my Wyvern chestplate on, when I touch the lava, my entire game locks up for about 30 seconds until it unfreezes to the respawn screen, and it happens to me 100% of the time there
