### ISSUE TITLE
Custom Fusion Recipe not Working

### ISSUE THREAD

**Issue by loverguy** [brandon3055/Draconic-Evolution#1024]
I have problem with make custom fusion recipe i've did everything right but it's like don't read the file at all 
http://textuploader.com/dmmig

**Comment by covers1624** [comment]
http://ss.covers1624.net/rbk8rkp.png Your json isnt formatted properly, please use a service such as https://jsonlint.com/ or a smart editor such as sublime.

**Comment by loverguy** [comment]
Thx !
