### ISSUE TITLE
[Feature request] Invisible armor?

### ISSUE THREAD

**Issue by micmou** [brandon3055/Draconic-Evolution#1027]
I am probably so far from the right place on this it ain't funny so delete if these don't go here. Something I wish for in a lot of mods is a ability to either camouflage or make transparent armor. 

Alot of people go around armorless for this reason. 

So my suggestion is to add an upgrade that allows you to colour your armor or make it transparent.

If the issue arises with the argument of not knowing what someone is wearing have it if you take damage it kinda fades in. If I was some sort of magical transparency system I wouldnt like being banged on either xD

**Comment by Mitchel75814** [comment]
In the armor config menu, where you set flight speed and all that there is the option to make the armor invisible.

**Comment by micmou** [comment]
@Mitchel75814 I feel very very unbelievably dumb rn..........

**Comment by CTH999** [comment]
It's there from another suggestion.

Also, don't feel dumb @micmou.

That happens to us all. It happens to me more than I want to admit, that's for sure!
