### ISSUE TITLE
Draconic Reactor Issue

### ISSUE THREAD

**Issue by jmac460** [brandon3055/Draconic-Evolution#1028]
## Base information
* Minecraft version: 1.10.2
* Mod version: most Recent
* Minecraft Forge version:
* Mod Pack: (if applicable) Project Ozone Lite

## Crash report
Basically, the Draconic reactor does not work correctly. I am not sure what is wrong, but every single 1.10.2 tutorial on the most recent version does not work on this modpack. I have tried everything to get the reactor to work correctly (even computercraft) and all of them cannot get the reactor to function correctly. I have copied everything in the tutorials, including the one that was made by the creator, and all of them seem to not function. I am not sure why this is happening, but it is VERY frustrating to keep having to backup my server over and over because the mod doesn't want to work.

**Comment by InterPlay02** [comment]
But you didn't say what is happening...

**Comment by jmac460** [comment]
I said it does not work. It blows up. No matter what value you put into the flux gates, it shoots straight to 99% saturation and then blows up.

**Comment by InterPlay02** [comment]
Can you, please, send some screenshots, so I can try to help you?

**Comment by jmac460** [comment]
![image](https://user-images.githubusercontent.com/34420502/35660250-924f7d8a-06d0-11e8-8279-d1a7cffec0ef.png)
![image](https://user-images.githubusercontent.com/34420502/35660262-a3ed416c-06d0-11e8-8426-d87e682b9c33.png)
![image](https://user-images.githubusercontent.com/34420502/35660267-b0440c7a-06d0-11e8-9304-faff567b231f.png)

These numbers show a stable reactor, however, these numbers are ridiculously high for some reason. If i were to put ANY other numbers below this, it shoots to 99% saturation and my shield plummets instantly and the reactor explodes. I am not sure why this is the case, but I cannot even supply this much power in Survival unless i use a creative energy supply

**Comment by jmac460** [comment]
Also, I have to adjust the numbers on this stable one every few minutes or it gets dangerously low shield or high saturation. It is unplayable to have to adjust these so often

**Comment by Tahakk** [comment]
have you tried to star maybe with lover numbers before going straight to extremes? Not even sure that this is quite right ratio that you can take/give energy. You are simply taking to much energy from it.

**Comment by InterPlay02** [comment]
Yeah, man! What are you trying to do? These values are ridiculous!
You **only need to put one value in the Signal Low**.

Let's build one from the beginnig.
First:
Build your reactor. Is the setup corrrect? If it is, go to the next step.

Second:
In the exit of energy (The flux gate you put right behind the Stabilizer), place 530,000...
And, in the entrance of energy (The flux gate you put attatched to the energy injector), place 126,000...
(Remember: You **only need to put these values in the Signal Low**). **Don't place any values in the Signal High yet!**

Third:
Charge your reactor. Wait until the Containment Field reaches 50%, the saturation also reaches 50% and the temperature reaches 2,000. When these three things are this way, turn on the reactor.

Fourth:
 This setup will make the temperature reaches over 8,000 degrees, but don't worry... This **was** meant to be like this. And this will make the Containment field drops all the way down to 4%... But don't worry, this **will** happens. But then, when the reactor begins to generate 530,000+ RF/t, the temperature will start to drop down, the containment field will start to rise up and the saturation will start to rise, as well.

This config should last a lot of time! When the containment field reaches over 30~40% you can increase the generation. How? Increasing the exit of energy (The flux gate you put right behind the Stabilizer). You can change it to something like 560,000. This will make the temperature rise up again, and will make the contaiment field drop again. But only until the reator starts to generate 560,000. When it gets there, the temperature will drop again and the containment field will rise again. Did you understand?

**Comment by InterPlay02** [comment]
Now I will try to teach you how this reactor works:

When you set a value to the exit of energy, the reactor then needs to work harder to generate that value. This is why it gets hotter and hotter. **BUT** when it gets there, it starts to rest, because now it **is** generating that value. You only need to keep in mind that you need to set up a good value **in the energy entrance** so, when the reactor starts to works harder, the containment field don't fall to zero.

Note: In these cases, the reactor will only explode if the containment field reaches zero. if there is still some energy entering the force field, the reactor won't explode. I mean: Even if there is only 0,5% in the containment field, it won't explode. Only when it drops to zero, it will...

So... This is how it works: You put a value in the energy exit, it will work harder to make it happens, but when it get there, it rests... Then the temperature drops down, and the containment field rises up. When you change the values, it will do it again. When you change it again, it will do it again... And so on.

I hope this explanation helps not only you, but also those who are reading.

**Comment by jmac460** [comment]
I tried every number under the sun, and only putting in on the low/ or only high. I troubleshooted this for so long... and those numbers i sent are the only ones that work and i have NO clue as to why. I have done EXACTLY as stated in your explanation, and the saturation still shoots to 99% and the shield drops to 0% and it blows up. Literally step by step, and it is doing this... idk man. I can send screenshots of the reactor before i turn it on (with pics of the flux gates, and the actual reactor when its charged) but i will not be able to capture a picture of the reactor shooting to those 99%/0% values... it happens instantly.

**Comment by jmac460** [comment]
In the actual Draconic Evolution /brandon3055 config file, what is the power generation scale? Mine is set to 60.0... is this normal?

**Comment by InterPlay02** [comment]
Ah, man... Don't tell me that...
In my config file:
D:reactorOutputMultiplier=1.0

Is this line that you are talking about?

**Comment by jmac460** [comment]
yes. why is mine 60

**Comment by jmac460** [comment]
omg if this is really the issue

**Comment by InterPlay02** [comment]
Turn it down to 1.0 or delete the file. It will be regenerated with the defalt configs.

**Comment by jmac460** [comment]
Ok. will do. not sure how it ever got to 60

**Comment by jmac460** [comment]
So i did exactly as you described and when I went to activate the reactor, it initially started fine, but the shield went all the way down. It never stopped at 4%, it completely went to 0 and blew up

**Comment by InterPlay02** [comment]
Well... So, increase the amount of RF entering **before it explodes** next time...

**Comment by jmac460** [comment]
Yes i am sending it to the Energy Core.

**Comment by ljside4672-boop** [comment]
Load 8 Awakened Draconium Blocks, set the Input Flux Gate to 20,000 ~ 25,000, and set the Output Flux Gate to 200,000 ~ 250,000.

**Comment by FoxMcloud5655** [comment]
Please do not necro closed issues.
