### ISSUE TITLE
[1.12.2] Swapping Wand from Not Enough Wands Causes Issues

### ISSUE THREAD

**Issue by SnowShock35** [brandon3055/Draconic-Evolution#1029]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2583
- NotEnoughWands 1.12-1.6.0
- Other:
  - Draconic Evolution 1.12-2.3.7.278
  - Brandon's Core 1.12-2.3.7-140

#### Issue Description

When using the swapping wand on end or nether Draconium Ore it returns the overworld variant for some odd reason. I've tried to figure out why but don't see how or why it would occur. all three variants have separate metadata so should be able to distinguish between them.

@brandon3055 Please could you take a look at romelo333/notenoughwands#71. Specifically, the comment section as McJty has asked you something there. :smile:

**Comment by brandon3055** [comment]
Found the problem. Will be fixed in the next release.
https://github.com/MinecraftForge/MinecraftForge/pull/4602
