### ISSUE TITLE
Staff of Power in AOE Safe Mode duplicates Broken Spawners

### ISSUE THREAD

**Issue by kim-yannick** [brandon3055/Draconic-Evolution#103]
If AOE Safe Mode is blocking the mining of a regular mob spawner, a Broken Spawner drops without breaking the spawner. This can be used to drop unlimited Broken Spawners from a single mob spawner. I am playing FTB Infinity 1.5.1 and discovered this issue while griefing through a Deep Dark Temple.

**Comment by brandon3055** [comment]
This is a bug in EIO which i believe has been fixed in the latest version of EIO.
