### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by arqueiro108** [brandon3055/Draconic-Evolution#1030]
## Base information
* Minecraft version:
* Mod version:
* Minecraft Forge version:
* Mod Pack: (if applicable)

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by covers1624** [comment]
You have only posted the template.
