### ISSUE TITLE
A function change

### ISSUE THREAD

**Issue by zetosuru** [brandon3055/Draconic-Evolution#1031]
With the basic displacer, it's possible to bypass things like GriefProtection on sponge servers with it's linking method being just clicking in the air. I'm suggesting a slight change there you have to click on a block to set rather than the air.

**Comment by brandon3055** [comment]
What are you referring to? There is no "basic displacer" in DE

**Comment by zetosuru** [comment]
I meant the dislocator. No idea where displacer came from in my mind.

**Comment by covers1624** [comment]
So the thing is, while you can set a dislocator to teleport in to a protected area, the area is.. protected, so you will either be booted from the area, or wont be able to do stuff in there, so the point is moot. I don't understand how teleporting in to some ones house that is protected with grief prevention bypasses grief prevention, even if its behind a closed door, its still protected..

**Comment by zetosuru** [comment]
Actually the reason I suggested it was due to mobs. We just had to deal with someone spawning a mess load of mobs, and dropping them through the portal created with the displacer.

**Comment by gigabit101** [comment]
Not alot that can been done about this unfortunately
