### ISSUE TITLE
Suggestion disable item dislocator pinging sound

### ISSUE THREAD

**Issue by wolfrunner86** [brandon3055/Draconic-Evolution#1035]
i would really like a way to disable the annoying pinging every time the magnet sucks something in. if there is already a way to disable this i cant find it.

**Comment by brandon3055** [comment]
This will be in the next release.

**Comment by bbf** [comment]
I think with you commit 4570abbc71c720940493dd0cfdcc20e59b24fb5a, the magnet ping plays constantly, even when nothing is being picked up.

This is your new code:
`if (flag || !DEConfig.disableDislocatorSound) {`
I think it should be:
`if (flag && !DEConfig.disableDislocatorSound) {`

**Comment by kkjdroid** [comment]
I can confirm that my dislocator now plays the ping constantly.

**Comment by covers1624** [comment]
Brandon figured it out in smp yesterday.. https://github.com/brandon3055/Draconic-Evolution/commit/76dff8b55b221769b0e318b9a0e9de06143b35d6 Fix is live on curse also.

**Comment by Bunny83** [comment]
Funny the bugged version made it into the latest Direwolf20 pack... However great to know this so we can at least "disable" the constant pinging and get back the usual behaviour. I never found the pickup sound annoying, but it's very annoying when it plays constantly :)
