### ISSUE TITLE
Crash to desktop when a Mob Grinder is viewed inside a Compact Machine, when in contact with a Flux Networks Flux Point.

### ISSUE THREAD

**Issue by Maxwell-lt** [brandon3055/Draconic-Evolution#1039]
https://github.com/thraaawn/CompactMachines/issues/298

## Base information
* Minecraft version: 1.12.2
* Mod version: 3.0.6-b192
* Minecraft Forge version: 14.23.1.2604

### Mod List
| Mod | Version |
|--|--|
| BrandonsCore | 2.3.7.140 |
| CodeChickenLib | 3.1.5.331 |
| compactmachines | 3.0.6-b192 |
| Draconic-Evolution | 2.3.8.279 |
| flux-networks | 3.0.3 |
| RedstoneFlux | 2.0.1.2 |
| sonarcore | 5.0.5 |

## Crash report

https://paste.ee/p/0lOuj

Might not be on your end, but Draconic Evolution seems to be involved in a rendering-related crash to desktop. When a Flux Point from Flux Networks is placed against a Mob Grinder (both inside a Compact Machine), it causes a client crash when the Compact Machine is right-clicked from the outside (expected behavior is that the interior of the Compact Machine can be viewed).

**Comment by thraaawn** [comment]
Hey, this isn't related to DE at all. Sorry about that, I need to mention somewhere on my readme not to report rendering bugs in the machine view to any mod author than me.

Please close.
