### ISSUE TITLE
Enchanting either the Draconic Pickaxe or Staff.

### ISSUE THREAD

**Issue by Ki-Tarn** [brandon3055/Draconic-Evolution#104]
Was trying to enchant the pickaxe and staff with either Fortune 3 or Silk Touch. The GUI accepts them in the top enchanting slot and the pick glows when going back to base menu, but when closed the enchantment does not stay and the book is gone from the slot when reopened.

Using the version on Mod Pack Infinity 1.5.1

**Comment by brandon3055** [comment]
Hmm... Are you by any chance on a bucket/cauldron server?

**Comment by Ki-Tarn** [comment]
You'd know better than I would if it's a bucket/cauldron server as it's the Lolnet server. :3

Which is now using DE 1.0.1c, which seems to have fixed the pick at least. A friend has the staff so we'll check that later. It worked correctly though with the GUI inventory letting me install and remove the enchantment book.

**Comment by brandon3055** [comment]
oh yes... Lolnet... That bug has been plaguing me for months! But im glad to hear my last attempt at fixing it was successful! If that did not work there is really not much else i could try.

If it works for the pick it should work for everything because they all use the same code.
