### ISSUE TITLE
Celestial Manipulator don't work in RFTools Dimensions

### ISSUE THREAD

**Issue by Morslord** [brandon3055/Draconic-Evolution#1040]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.8.279
* Minecraft Forge version: 14.23.1.2587
* Mod Pack: FTB Presents Direwolf20 1.12

## Description
The Celestial Manipulator can neither change the weather nor the time in RFTools Dimensions.
When I try to change the time, the sun/moon get moved and instantly warped back to the original position.
Because there is noch crash-report I made a video of the bug:
https://www.youtube.com/watch?v=Xr1On5AGzvM
Hopefully it helps.

I also create an issue for RFTools, because I don't know, if it is a bug from Draconic Evolution or RFTools.
Link to the issue: https://github.com/McJty/RFTools/issues/1603

**Comment by brandon3055** [comment]
As McJty said in his issue this isnt really a bug in ether mod its just hard to support every other mod with their custom dimensions because everyone handles things slightly differently.
