### ISSUE TITLE
[Feature Request] Chaos Dragon Heavily Over-Powered

### ISSUE THREAD

**Issue by IAmVensey** [brandon3055/Draconic-Evolution#1042]
Regarding the 1.10.2-2.1.6.263 version of Draconic Evolution for the Sky Factory 3 pack:

Nerf the Chaos Dragon. 

I get it. You want it to be challenging and hard; it IS a Chaos Dragon, after all. But there is a fine line to be drawn between having an enjoyable yet challenging experience, and a horrifically, frustratingly impossible one. Currently, the Chaos Dragon fits squarely into the latter category. Regardless of how powerful the Draconic items are, this dragon is so heavily unbalanced that all of the other Draconic items (such as armor and weapons) are basically useless. 

It isn't enjoyable in any way. 

I'd love to be able to use the extent of the mod that you've developed, as I know it takes time and dedication, but the reward for all the difficulty is simply not worth it. It takes a whole chaotic shard to make ONE core to make ONE chaotic-tier fusion crafter (of which you usually need 10 for crafting), and then the draconic energy core on top of that. In order to even make it worth it, you'd have to fight at least two or three Chaos Dragons, and it's just not worth the time and frustration; I'd rather just pull it from creative at that rate.

If you want to keep all the elements of the Chaos dragon that you do now, then you need to seriously nerf some of those abilities. If not, you'll have to remove some things to make it playable and possible.

Try giving the player some breathing room, or having the Chaos dragon actually come down and sit in one place for a few moments the way that the Ender dragon does. **And most certainly nerf the bullets**. At least have them time out or something instead of following you forever.

It's been an hour, and I have done everything in my power to become as powerful as possible to defeat the thing and I can't. (I have fully upgraded Draconic EVERYTHING: armor, bow, Staff of Power, FIVE draconic capacitors with max RF, and additional enchantmentss on top of all of those.)

The dragon is overpowered, and becomes a pointless endeavor for the Chaos Crystal and makes the Draconic Evolution mod basically unplayable past a certain point. (This is especially true in single player; after an hour, I got fed up with the BS and decided to switch to creative, and even then it took me another 15 minutes to beat the dragon!)

So again, consider either removing some powers of the Chaos Dragon or nerfing them so that it's playable again.

**Comment by Tahakk** [comment]
I have no idea what are your problems, not talking that 1.10.2 of most of the mods is not supported, and this is not even bug.
Killing a chaos dragon after 1.7.10 version was challenging, cannot deny that, but I have played od server with many players and no one had problem with that.

First part is just you basically running every time dragon get on your ass and destroying his crystals.
Second part is dragon running away from you because he is getting his ass kicked. 

It is wise to have fully upgraded Draconic armor, Draconic bow (it is like minigun on it's peak) and maybe more than one Draconic Flux Capacitor.

The problem of your issue is that author of the mod won't be able to get some modpack easier just because you want to. You would have to tell that to pack creator if the mod even support those features.

**Comment by IAmVensey** [comment]
I was under the impression this was the place to present ideas to the mod. If it's not even being supported any longer, then I'll be closing the issue.

**Comment by covers1624** [comment]
Clarification, DE is supported, he said most mods dont support 1.10 anymore. Honestly the fight isnt that hard, you are just going about it the wrong way. @brandon3055 please clear things up here.

**Comment by brandon3055** [comment]
Its meant to be hard. So hard that sure it may not be for everyone. That said people have complained that its too easy which once you figure out how to fight it it really is easy so no i will not be reducing its difficulty.

**Comment by brandon3055** [comment]
https://www.youtube.com/watch?v=xGqnJ0P4z7o&ab_channel=Brandon3055
