### ISSUE TITLE
Crash report from breaking chaos shard

### ISSUE THREAD

**Issue by JoeSGT** [brandon3055/Draconic-Evolution#1043]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.8.279
* Minecraft Forge version:  1.12.2-14.23.1.2604
* Mod Pack: (if applicable)

## Crash report 
``` 
https://pastebin.com/CipLPfhP
```
Please note assuming the issue is a crash something like this

```java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException```
 it seem the server crash whenever someone break Chaos shard

**Comment by brandon3055** [comment]
Sponge is making it tricky to track down the issue. Please try to reproduce this issue without sponge and give me the crash report without sponge installed. If the issue goes away when you remove sponge then this is a sponge issue.

**Comment by JoeSGT** [comment]
it seem to be a sponge issue going to go even deeper in testing before reporting.
Thanks

**Comment by JoeSGT** [comment]
@brandon3055  can you possibly add a config option to disable chaos shard from explosive ?
