### ISSUE TITLE
Mob souls

### ISSUE THREAD

**Issue by amigo127** [brandon3055/Draconic-Evolution#1044]
## Base information
* Minecraft version: 1.10.2
* Mod version: 2.1.7.266
* Minecraft Forge version: 1.10.2-12.18.3.2511

Is NOT a crash report!</br>

I want to give myself a wither skeleton soul mob just I can not do it

**Comment by JoeSGT** [comment]
you can try this command
```
/give @p draconicevolution:mob_soul 1 0 {EntityName:Skeleton, EntityTypeID:1}
```

**Comment by amigo127** [comment]
i have already try this command and same give a soul of skeleton basic

**Comment by brandon3055** [comment]
Minecraft changed their entity registration. Its now this.
`/give @p draconicevolution:mob_soul 1 0 {EntityName:"minecraft:wither_skeleton"}`
