### ISSUE TITLE
[Item Duplication] Gendustry input cover taking clones of items

### ISSUE THREAD

**Issue by PG-Fuury** [brandon3055/Draconic-Evolution#1047]
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.8.279
* Minecraft Forge version:14.23.1.2601
* Mod Pack: FTB Revelation

No crash, but Item duplication bug, probably due to placed items in the world not getting items removed when they get piped out.
Situation:
Gendustry Industrial Apiary with item input cover, Bees placed as item on that side
Apiary takes bees in, they are still in the "placed item" block, they get pulled in again

Easily abused to duplicate pristine princesses

**Comment by brandon3055** [comment]
This is partially a bug with Gendustry not using the correct method to remove items from the inventory but regardless this will be fixed in the next release.
