### ISSUE TITLE
[Suggestion] Cross-mod fusion crafting upgrades for Draconic armor

### ISSUE THREAD

**Issue by Saklad5** [brandon3055/Draconic-Evolution#1050]
As endgame armor, it would be cool to be able to add armor effects from other mods onto Draconic gear by infusing those mod’s armor sets into them. This should be expensive, using up endgame armor pieces from said mods and the materials normally used for Draconic-tier upgrades, but add the unique abilities as configurable options.

- Fusing Draconic armor with Terrasteel armor from Botania, for instance, could grant the “Will of the Ancients” buffs that armor provides. Infusing a full set of Draconic armor with them would grant passive health regeneration, 20% mana savings, and passive mana generation, accompanied by the Ancient Will effects if you added those to the helmet.

- Fusing Draconic armor with Apiarist’s gear would grant immunity to negative bee effects.

- Fusing Draconic armor with a Radiation Suit from Deep Resonance would grant partial immunity to radiation, to the same degree wearing the Radiation Suit pieces would. (I know Draconic armor already negates negative potion effects, but quite frankly that bit feels overpowered and should probably be exempted for radiation effects anyway)

I’m sure you can think of plenty of other mods with unique mechanics that could be merged with Draconic gear.

**Comment by CTH999** [comment]
Don't forget Redstone arsenal, and [PSI](https://minecraft.curseforge.com/projects/psi?gameCategorySlug=mc-mods&projectID=241665). Also, as a end-tier, averiata!

**Comment by Saklad5** [comment]
Does Redstone Arsenal introduce any unique armor mechanics? PSI does, but that seems like a UI nightmare to coordinate.

**Comment by CTH999** [comment]
RA doesn't. However, you are right. PSI would be a night mare to integrate, but It would be awesome. Or, it could be where you have to select the spell from the Config-UI, and add them in else where. Also, if you can only integrate the PSI helmet later, then it would be nice if you could put all the sensors in the recipe. Then, you can alter what sensor is being used.

Also, [Advanced Rocketry's](https://minecraft.curseforge.com/projects/advanced-rocketry?gameCategorySlug=mc-mods&projectID=236542) Space Suits would be nice.

**Comment by Saklad5** [comment]
OK, Flux-Infused Armor’s only unique mechanic is absorbing Flux damage as energy. I suppose that mechanic could be added to Draconic armor.

I’m mostly thinking about the sort of mechanic that has API hooks. Countless mods add damage types and mechanics that can theoretically be used by other mods, but never are. And by the time you can get Draconic armor, all those mechanics aren’t enough to justify switching gear, even though you invested in getting it. Rather than putting on an IC2 hazmat suit, people will just grab uranium and tank the radiation damage with the draconic shield because it is more convenient.

**Comment by CTH999** [comment]
Yes, but it costs power. Hence, add it to the DE Armor. Especially AR's Space suits. Just because that would be awesome to use it in space! I agree, I don't change armors, however, I would like to use less power, therefor the feature being in DE Would be awesome. I do see your point though.

**Comment by Saklad5** [comment]
Advanced Rocketry spacesuits are an excellent example of where this would be helpful. Also Thaumcraft’s Thaumic Goggles, if that is still a thing when that mod reappears. For some reason many mods actually do implement support for that particular piece of equipment.

**Comment by CTH999** [comment]
It is, and those are great pieces. However, I get the feeling that for some, both mods would need some support. Also, it would be nice it would work with the googles from a little know mod called [Crossroads MC](https://minecraft.curseforge.com/projects/crossroads-mc?gameCategorySlug=mc-mods&projectID=250231). It's more realistic than DE, but it's quite well done, and it would be nice. Also, with the botania one, the phantom ink would make the armor clear, so setting the hid armor would make you invisible if all where toggled. However, just a neat little addition.

**Comment by Saklad5** [comment]
Phantom Ink’s functionality is already completely replicated in Draconic Evolution.

**Comment by CTH999** [comment]
Good point, however, what I mean is if the amour  is invisible and has phantom ink, then It makes you invisible. However, it would be nice if, at least, it made the partials disappear. Then, you are invisible. So, forget the phantom ink idea. It would be a "bit" complicated.

**Comment by Saklad5** [comment]
You realize there is a Botania cape that will make you invisible, right?

**Comment by CTH999** [comment]
Yes, I do. And since it's in the same mod, it's a Duh moment!

Thanks :)

**Comment by gigabit101** [comment]
This might be added in DE3, There is no plans on adding this in current versions.
