### ISSUE TITLE
Suggestion- Bags

### ISSUE THREAD

**Issue by CTH999** [brandon3055/Draconic-Evolution#1051]
This mod adds lots. Chests, new crafting mechanics, Armor, Tools, Weapons, Ores, New Mechanics, Bosses, Power Gen, Power Storage, Power Transfer...

But, where's my bags?

Bags give more inventory, and this mod, be DE, would do it differently. First off, arrows would be drawn from it as well as the inventory. Everything stays out, except for stuff in the white-list/ not in the black list. Also, it will smelt ores.

However, it would also be up-gradable, with power storage, and a storage increase. Also, it would have a basic, wyvern, and draconic tier.

Also, a great feature. Items can extract power from any power containing items, and it acts like a power cell with its own+ other items storage. Meaning, throw in you useless wyvern pick you thought you lost. Use it as storage. Also, it auto- puts the best tool for the job in your hands. If that feature is enabled,

However, this is just a suggestion. It's you mod after all.

**Comment by Saklad5** [comment]
So… a Draconic Chest, but portable?

Keep in mind that Draconic Evolution doesn’t need to do everything, and certainly doesn’t need more power storage. All DE items pool their energy, so every single bit of gear is effectively a storage boost to every other piece of gear.

Also, you were supposed to use your Wyvern Pick to make a Draconic one. I don’t think there’s any need to find another use for it.

**Comment by Saklad5** [comment]
And if you want a bag with automatic input/output based on whitelists and blacklists, Thermal Expansion’s Satchels have you covered already.

If you want automatic ore processing, just use a Refined Storage Addons Network Bag (especially once whitelists are added). Frankly, the Draconic Chest’s ore processing is already a bit much.

**Comment by CTH999** [comment]
True, but they aren't power storage, auto smelting, DE bags. Also, if you look at it, you died, and landed on a hopper. You couldn't find your friends base, so you made a new pick. Later, you found the old one, and now can use it as a battery. However, I see you point. I completely agree about the chest! Also, I didn't know about RSA Network bag. Have to check it out. Thanks!

**Comment by Saklad5** [comment]
Just a warning about the Network Bag: it’s not fully implemented yet, so right now it automatically dumps literally everything you pick up directly into your Refined Storage network. There’s no filter, but even the tooltip says that is coming soon. It is not an actual bag, but you probably don’t want to hang onto ores while mining anyway.

Oh, and it does run out of power relatively fast when using tools like Terra Shatterers or Draconic Evolution gear. It isn’t armor or a held item during normal use, of course, so you just have to switch to it occasionally to top it off. It’s a shame most batteries don’t charge items throughout the inventory.

**Comment by CTH999** [comment]
Ah, thanks. Exactly. And, since I play with RS mostly, I'll be fine. (I prefer AE, but just RS is much more stable at times. And it is a sham. I know what my next suggestion is!
