### ISSUE TITLE
Suggestion: DE Capacitors should have more options.

### ISSUE THREAD

**Issue by CTH999** [brandon3055/Draconic-Evolution#1052]
The Draconic Evolution Capacitors should have more options. Such as charging all items in the inventory, or "All Items Excluding Hot-bar/armor".

This would be great for items that go in the inventory, stay there, but need power. (IE Refined Storage Add-ons "Network Bag" Which uses a lot of power, and to charge it you need to hold it.)

That's all for this suggestion!

**Comment by Saklad5** [comment]
You misspelled Capacitor.

**Comment by CTH999** [comment]
Thanks!

**Comment by gigabit101** [comment]
There is no plans on adding this in current versions, This might be added in DE3
