### ISSUE TITLE
Drac evo erroring and causing crash during loading

### ISSUE THREAD

**Issue by Cewkaurai** [brandon3055/Draconic-Evolution#1054]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12-2.3.9.283
* Minecraft Forge version: latest build; 14.23.2.2617
* Mod Pack: Custom pack; being built for a server

## Crash report

https://pastebin.com/QuFZEibi

**Comment by covers1624** [comment]
You have the deobf jar installed, you want the universal jar. The deobf jar is for mod developers.

**Comment by Cewkaurai** [comment]
ok, somehow the download link I used gave me the wrong version of the jar file xD I got the right one from curseforge I think though,
