### ISSUE TITLE
[Bug] Portals can be broken and placed in survival mode

### ISSUE THREAD

**Issue by Philosyang** [brandon3055/Draconic-Evolution#1056]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.8.279 (2.3.8)
* Minecraft Forge version: 14.23.1.2586
* Mod Pack: N/A

## Bug report
**Portal** (draconicevolution:portal) can be broken with any pickaxe and placed in the world (though not working). Is this a bug or this is intended?

**Comment by CTH999** [comment]
I honestly thought that was a feature...

Thought, now I thing, "Why would there be a feature for that?"

**Comment by brandon3055** [comment]
Yes this is a bug.
