### ISSUE TITLE
Suggestion: Support CoFH IQuiverItem

### ISSUE THREAD

**Issue by Alex-hawks** [brandon3055/Draconic-Evolution#1059]
I tried to use the [Flux Infused Quiver](https://teamcofh.com/docs/flux-infused-quiver/) [(Github)](https://github.com/CoFH/RedstoneArsenal/blob/1.12/src/main/java/cofh/redstonearsenal/item/util/ItemQuiverFlux.java) with the Draconic Bow, and was very disappointed to find that it didn't work. I noticed that there is already a soft dependency on Thermal Foundation, which means you don't need to add any other dependencies to Draconic Evolution to add this support. The interface required for support is [here](https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/util/core/IQuiverItem.java), and an example of an item that supports the Quivers is the [Flux Infused Bow](https://github.com/CoFH/RedstoneArsenal/blob/1.12/src/main/java/cofh/redstonearsenal/item/tool/ItemBowFlux.java)

**Comment by dash16** [comment]
This would be nice!  As a workaround until then, give yourself an infinity enchantment on the Draconic bow.

**Comment by gigabit101** [comment]
This might happen In DE3, No plans on adding this to current versions.
