### ISSUE TITLE
Random "Ticking player" error

### ISSUE THREAD

**Issue by accessdenied0** [brandon3055/Draconic-Evolution#106]
Dear @brandon3055,

I can't really enplane why this happened or if this is the fault of this mod, but I can describe the circumstances: It was just at the start from my SSP World I tried to search something in NEI it crashed and throw this error: http://pastebin.com/7DW0Sddn. Strangely: It doesn't appeared before or every time. Just sometimes.

I hope I could help,

access_denied

**Comment by brandon3055** [comment]
Hmm that is rather odd... Its not a problem with nei its my update checker that runs about 20 seconds after you login to a world for the first time after starting the game. But the crash itself dose not make a lot of sense. I will look into it when i can.

**Comment by brandon3055** [comment]
Is this still an issue?

**Comment by accessdenied0** [comment]
Dear @brandon3055,

So far I never experienced this issue again. It seem to be fixed or was maybe (like in the op mentioned) not even your fault.

access_denied
