### ISSUE TITLE
Feature Request - 1.7.10

### ISSUE THREAD

**Issue by Kagenokami** [brandon3055/Draconic-Evolution#1062]
## Base information
* Minecraft version: 1.7.10

I think it would be cool to allow the Awakened Draconic gear to accept "composite" enchants. IE Enchantment books that have been combined into 1 enchantment. With the addition of enchantments from mods like Thaumcraft, not being able to make use of the ability to combine enchantments severely limits the potential of the staff of power and armors. While it IS possible to exchange enchants at a moment's notice, it is extremely frustrating to waste the inventory space and the time.

So...in short. It would be really cool to see composite enchantment support in 1.7.10 for use with enchantment adding mods. :D Thanks for the awesome mod and I hope to see new content~ <3

**Comment by Tahakk** [comment]
Move on to 1.12 mate, best answer you can get

**Comment by Kagenokami** [comment]
Not everyone can move due to the mod fracture. I am thus stuck on 1.7.10

**Comment by covers1624** [comment]
Mod Fracture, lol. Anyway, DE for 1.7 is un supported and un maintained. Ill add this to brandon's "Maybe if i can be bothered with a 1.7 final release" list.
