### ISSUE TITLE
Crash when logging in.

### ISSUE THREAD

**Issue by Diamond45123** [brandon3055/Draconic-Evolution#1064]
## Base information
* Minecraft version: 1.11.2
* Mod version: 2.2.5.271
* Minecraft Forge version: 2563
* Mod Pack: (if applicable) custom

## Crash report
https://pastebin.com/0P2cTVzH

I was trying to extract energy from my tier 4 energy core. So, I placed a glass block above the pylon and it resulted into this weird circle above the pylon. I tried right-clicking it. It resulted in this crash.
Now, Whenever i try to login, it does the same crash. Help.

**Comment by Diamond45123** [comment]
Tried restoring a backup to fix it but still resulted to the same thing, although the circle thing isn't there yet.
https://pastebin.com/0uTnpCQd

**Comment by covers1624** [comment]
Remove Flux Points or whatever it's called, it has serious issues.

**Comment by Diamond45123** [comment]
Doesn't work, need help. Even if i remove it. It causes crashes somehow.how do i fix this? i don't want to lose the world.

**Comment by Diamond45123** [comment]
For some reason, it crashes when i connect a flux sender to a pylon.. I'll try using a cable then a flux sender..

**Comment by covers1624** [comment]
Without screenshots and/or a crash log, i can do nothing.

**Comment by Diamond45123** [comment]
Here : https://pastebin.com/puFuG2rq
It is essentially the same crash.
I don't know why but it crashes for some reason

**Comment by Diamond45123** [comment]
It even crashes when there's nothing charging the energy core. wat.

**Comment by covers1624** [comment]
Remove SonarCore and FluxexPoints, they are broken in more ways than i can count and is basically unmaintained by the state and severity of the bugs.

**Comment by TNTUP** [comment]
I don't have such crashes using those mods, this cannot be related to them? Try updating SonarCore/FluxNetworks to the latest version?

**Comment by brandon3055** [comment]
Yes this IS a SonarCore/FluxexPoints issue. The fact that you a single user are not getting these crashes does not mean nothing is wrong. It just means you have so far not encountered one of the countless situations where these mods break. I dont want to hear any more complaints related to these mods until these mods actually try to fix their shit. Any future issues involving these mods will be locked.
