### ISSUE TITLE
Crashes cubic chunk's custom ore gen

### ISSUE THREAD

**Issue by N0819** [brandon3055/Draconic-Evolution#1065]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.822.0-SNAPSHOT-all.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.2 (1).jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 2/24/18 4:24 PM
Description: Updating screen events

java.lang.ExceptionInInitializerError
	at cubicchunks.worldgen.gui.OreSettingsTab$UIStandardOreOptions.lambda$new$1(OreSettingsTab.java:190)
	at cubicchunks.worldgen.gui.OreSettingsTab$UIStandardOreOptions$$Lambda$1274/1850540328.accept(Unknown Source)
	at cubicchunks.worldgen.gui.component.UIBlockStateButton.lambda$onClick$0(UIBlockStateButton.java:100)
	at cubicchunks.worldgen.gui.component.UIBlockStateButton$$Lambda$1542/1026061231.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at cubicchunks.worldgen.gui.component.UIBlockStateButton.onClick(UIBlockStateButton.java:100)
	at net.malisis.core.client.gui.MalisisGui.func_146286_b(MalisisGui.java:501)
	at net.malisis.core.client.gui.MalisisGui.func_146274_d(MalisisGui.java:353)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at com.brandon3055.draconicevolution.blocks.Portal.func_149915_a(Portal.java:89)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at cubicchunks.worldgen.gui.component.UIBlockStateSelect.<clinit>(UIBlockStateSelect.java:86)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cubicchunks.worldgen.gui.OreSettingsTab$UIStandardOreOptions.lambda$new$1(OreSettingsTab.java:190)
	at cubicchunks.worldgen.gui.OreSettingsTab$UIStandardOreOptions$$Lambda$1274/1850540328.accept(Unknown Source)
	at cubicchunks.worldgen.gui.component.UIBlockStateButton.lambda$onClick$0(UIBlockStateButton.java:100)
	at cubicchunks.worldgen.gui.component.UIBlockStateButton$$Lambda$1542/1026061231.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at cubicchunks.worldgen.gui.component.UIBlockStateButton.onClick(UIBlockStateButton.java:100)
	at net.malisis.core.client.gui.MalisisGui.func_146286_b(MalisisGui.java:501)
	at net.malisis.core.client.gui.MalisisGui.func_146274_d(MalisisGui.java:353)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: cubicchunks.worldgen.gui.CustomCubicGui
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1369958768 bytes (1306 MB) / 2852126720 bytes (2720 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.42 Powered by Forge 14.23.2.2619 45 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State       | ID                                  | Version                   | Source                                                   | Signature                                |
	|:----------- |:----------------------------------- |:------------------------- |:-------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAA | minecraft                           | 1.12.2                    | minecraft.jar                                            | None                                     |
	| UCHIJAAAAAA | mcp                                 | 9.42                      | minecraft.jar                                            | None                                     |
	| UCHIJAAAAAA | FML                                 | 8.0.99.99                 | forge-1.12.2-14.23.2.2619.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | forge                               | 14.23.2.2619              | forge-1.12.2-14.23.2.2619.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | foamfixcore                         | 7.7.4                     | minecraft.jar                                            | None                                     |
	| UCHIJAAAAAA | mercurius_updater                   | 1.0                       | MercuriusUpdater-1.12.2.jar                              | None                                     |
	| UCHIJAAAAAA | malisiscore                         | 1.12.2-6.3.2              | malisiscore-1.12.2-6.3.2 (1).jar                         | None                                     |
	| UCHIJAAAAAA | cubicchunks                         | 1.12.2-0.0.822.0-SNAPSHOT | CubicChunks-1.12.2-0.0.822.0-SNAPSHOT-all.jar            | None                                     |
	| UCHIJAAAAAA | aether_legacy                       | v1.0                      | aether_legacy-1.12.2-1.0.jar                             | None                                     |
	| UCHIJAAAAAA | appliedenergistics2                 | rv5-alpha-8               | Applied-Energistics-2-Mod-1.12.2.jar                     | None                                     |
	| UCHIJAAAAAA | bibliocraft                         | 2.4.3                     | BiblioCraft-Mod-1.12 (1).jar                             | None                                     |
	| UCHIJAAAAAA | biomesoplenty                       | 7.0.1.2302                | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar            | None                                     |
	| UCHIJAAAAAA | codechickenlib                      | 3.1.5.331                 | CodeChickenLib-1.12.2-3.1.5.331-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | redstoneflux                        | 2.0.1                     | RedstoneFlux-1.12-2.0.1.2-universal.jar                  | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAAAA | brandonscore                        | 2.4.0                     | BrandonsCore-1.12-2.4.0.152-universal.jar                | None                                     |
	| UCHIJAAAAAA | buildcraftlib                       | 7.99.14                   | BuildCraft-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAAAAAA | buildcraftcore                      | 7.99.14                   | BuildCraft-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAAAAAA | buildcraftbuilders                  | 7.99.14                   | BuildCraft-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAAAAAA | buildcraftenergy                    | 7.99.14                   | BuildCraft-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAAAAAA | buildcraftfactory                   | 7.99.14                   | BuildCraft-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAAAAAA | buildcraftrobotics                  | 7.99.14                   | BuildCraft-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAAAAAA | buildcraftsilicon                   | 7.99.14                   | BuildCraft-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAAAAAA | buildcrafttransport                 | 7.99.14                   | BuildCraft-Mod-1.12.2.jar                                | None                                     |
	| UCHIJAAAAAA | chickenchunks                       | 2.4.1.71                  | ChickenChunks-1.12.2-2.4.1.71-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | chiselsandbits                      | 14.11                     | chiselsandbits-14.11.jar                                 | None                                     |
	| UCHIJAAAAAA | cofhcore                            | 4.3.10                    | CoFHCore-1.12.2-4.3.10.5-universal.jar                   | None                                     |
	| UCHIJAAAAAA | cofhworld                           | 1.1.1                     | CoFHWorld-1.12.2-1.1.1.12-universal.jar                  | None                                     |
	| UCHIJAAAAAA | coloredwatermod                     | 1.0.0                     | Colored+Water+Mod.jar                                    | None                                     |
	| UCHIJAAAAAA | thermalfoundation                   | 2.3.10                    | ThermalFoundation-1.12.2-2.3.10.6-universal.jar          | None                                     |
	| UCHIJAAAAAA | draconicevolution                   | 2.3.9                     | Draconic-Evolution-1.12-2.3.9.283-universal.jar          | None                                     |
	| UCHIJAAAAAA | enderstorage                        | 2.4.2.126                 | EnderStorage-1.12.2-2.4.2.126-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAA | foamfix                             | 0.9.4-1.12.2              | FoamFix-1.12.2-0.9.4-Anarchy.jar                         | None                                     |
	| UCHIJAAAAAA | ichunutil                           | 7.1.4                     | iChunUtil-1.12.2-7.1.4 (1).jar                           | None                                     |
	| UCHIJAAAAAA | generallaymansaestheticspyingscreen | 7.0.0                     | GeneralLaymansAestheticSpyingScreen-1.12.2-7.0.0 (1).jar | None                                     |
	| UCHIJAAAAAA | ironchest                           | 1.12.2-7.0.34.820         | Iron-Chests-Mod-1.12.2.jar                               | None                                     |
	| UCHIJAAAAAA | ironbackpacks                       | 1.12.2-3.0.5-6            | IronBackpacks-1.12.2-3.0.5-6.jar                         | None                                     |
	| UCHIJAAAAAA | mantle                              | 1.12-1.3.1.21             | Mantle-1.12-1.3.1.21.jar                                 | None                                     |
	| UCHIJAAAAAA | radixcore                           | 1.12.x-2.2.1              | RadixCore-1.12.x-2.2.1-universal.jar                     | None                                     |
	| UCHIJAAAAAA | mca                                 | 1.12.2-5.3.1              | MCA-1.12.x-5.3.1-universal.jar                           | None                                     |
	| UCHIJAAAAAA | thermaldynamics                     | 2.3.10                    | ThermalDynamics-1.12.2-2.3.10.4-universal.jar            | None                                     |
	| UCHIJAAAAAA | thermalexpansion                    | 5.3.10                    | ThermalExpansion-1.12.2-5.3.10.15-universal.jar          | None                                     |
	| UCHIJAAAAAA | tconstruct                          | 1.12-2.8.1.49             | Tinkers-Construct-Mod-1.12.1.jar                         | None                                     |
	| UCHIJAAAAAA | tinkertoolleveling                  | 1.12-1.0.3.DEV.56fac4f    | TinkerToolLeveling-1.12-1.0.3.jar                        | None                                     |
	| UCHIJAAAAAA | twilightforest                      | 3.0.0                     | Twilight-Forest-Mod-1.12.2.jar                           | None                                     |
	| UD          | cubicchunkscore                     | @@VERSION@@               | minecraft.jar                                            | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.822.0-SNAPSHOT-all.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.3.2 (1).jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.31' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	AE2 Version: alpha rv5-alpha-8 for Forge 14.23.0.2491
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2619
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7

**Comment by brandon3055** [comment]
This is a bug in cubic chunk's Tile entity creation requires a world object and they are giving null.

**Comment by N0819** [comment]
It's a UI related crash. This is before world gen.
