### ISSUE TITLE
Pig Soul causing mipmap flicker.

### ISSUE THREAD

**Issue by MastrPancake** [brandon3055/Draconic-Evolution#1066]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.8.279
* Minecraft Forge version: 14.23.2.2611
* Mod Pack: OptiFine HD U C9

When i look in the creative tab of the mod i noticed my mipmap would flicker in the world. I narrowed it down to the pig soul by just placing the item in my inventory and restarting the game then opening my inventory. I turned off shaders in the config and every thing i could change client side and nothing fixed it.

**Comment by brandon3055** [comment]
Please test this without optifine installed. I suspect optifines rendering is not compatible with DE's items.

**Comment by MastrPancake** [comment]
Turns out its being caused by conflicts with the Between Lands mod. Looking at config settings to see if that can fix it.

**Comment by MastrPancake** [comment]
Turned off shaders for both mods and sadly this cant be fixed with config options.
