### ISSUE TITLE
Item Dislocator constant pickup sound

### ISSUE THREAD

**Issue by Garubis** [brandon3055/Draconic-Evolution#1069]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.9.283
* Minecraft Forge version: 14.23.2.2619
* Mod Pack: [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) Version: 1.25

## Description
When using an activated item dislocator, a constant ding can be heard as if an item was being picked up.
There is room in the players inventory, there is no item entity near them, there is no exp gain.
It can be heard by other players near them as well. It's the same for the awakened dislocator.

**Comment by covers1624** [comment]
Update to .284.
