### ISSUE TITLE
Chaos Island, Reactor Explosions

### ISSUE THREAD

**Issue by Explosivee** [brandon3055/Draconic-Evolution#1070]
Hello,
Is there anyway to turn these stuffs off for the servers? It kills the server everytime someone kill chaos dragon etc

**Comment by tyler489** [comment]
Chaos dragon  no... reactor is in the config.

**Comment by tyler489** [comment]
Get a better server prehaps?

**Comment by covers1624** [comment]
Don't be a dick @tyler489. I'm locking this until brandon comments.

**Comment by brandon3055** [comment]
I could have sworn this config already existed but i must have just been thinking of the reactor. I will add a config for this in the next release.

**Comment by tyler489** [comment]
My apologies if i came off as a dick was not my intent

**Comment by Explosivee** [comment]
@brandon3055 Could you make something temporary to disable those explosions, maybe a server side mod?

**Comment by Explosivee** [comment]
@tyler489 My server got 64GB (16 Located for the Minecraft server) RAM i7 7700K 5 GHz OC. 1TB NVMe SSDs and 1Gbps internet speed, still doing the same.

**Comment by Saklad5** [comment]
You should _not_ be having an issue with specs like that. Whatever the problem is, it isn’t the Chaos Island explosion.

Honestly, it’s really not that laggy. Especially compared to the swarm of projectiles in the fight itself, not that that is too bad either. The only part that really lags my machine is when lightning starts destroying the pillars and spamming the area with an absurd amount of light and block updates.

You sure it isn’t that?

**Comment by Explosivee** [comment]
My server dies whenever someone kills the chaos guardian and blow the island up so yes, i'm sure

**Comment by Saklad5** [comment]
Has anyone ever killed the Chaos Guardian without immediately blowing up the island afterwards?

**Comment by tyler489** [comment]
You might be able to /kill the entitychaosdragon vortex not sure never tried it

**Comment by Saklad5** [comment]
I am nearly certain that wouldn’t work, since it’s not just an entity. It’s a bunch of code that is called when the Chaos Crystal is broken. Doing that would, at best, do nothing but remove some visuals. At worst, it would crash in terribly fascinating ways.

**Comment by Explosivee** [comment]
@Saklad5 If people tp away right after they killed the dragon nothing happens because the chunk is unloading directly

**Comment by tyler489** [comment]
it is actually an "entity" as it can be summoned using the /summon command

**Comment by scrouthtv** [comment]
Is there any fix to this yet?

My server died upon killing the Chaos Dragon
`[19:57:52] [Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[19:57:52] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.`

Both copying the world to a client and starting & joining the server crashes with this error.
Can I somehow cancel the explosion effect? I already enabled the config option but the explosion is already happening...

_The server setup should be pretty decent, 16 GB RAM, SSD, ..._

**Comment by FoxMcloud5655** [comment]
Can you provide mod versions for DE and it's dependencies?

**Comment by scrouthtv** [comment]
Newest:
Draconic 2.3.24.349
BC 2.4.17.208

**Comment by FoxMcloud5655** [comment]
RedstoneFlux and CodeChickenLib are dependencies as well. Would you provide those as well?

**Comment by scrouthtv** [comment]
Sorry, didn't know.

RF - 2.1.0.6 (universal)
RF tools - 7.72
CCLib - 4.6.3.27 (universal)

Also Minecraft 1.12 on Forge 14.23.5.2838

**Comment by scrouthtv** [comment]
I got the server back up by deleting the End world, but is that the only solution?

**Comment by FoxMcloud5655** [comment]
There is no version of CodeChickenLib that is higher than 3.2.3.357...  Perhaps you listed the version of a different mod?

In any case, the reason why I asked is because the latest version of CodeChickenLib has been known to have issues syncing custom packets.  Also, forge version 2838 is unstable; try running it with 2836.

**Comment by scrouthtv** [comment]
Oh yeah my fault. Mixed CoFHCore with CCLib, CCLib is the newest, 357. 
I'll try CCLib 353 and Forge 2836 & come back with results
