### ISSUE TITLE
[Suggestion]More armour/tool upgrades

### ISSUE THREAD

**Issue by q3AEWRSDTFGYHUJNKMIHUGBTYRFDYSIYGUH** [brandon3055/Draconic-Evolution#1071]
I have a few kinds of armour/tool upgrades in mind that i thought would be cool for this mod to have. Maybe some of them are a bit OP though :P 
Armour: Entropy removal (could make the armour use more power for this if you want)
              Damage reflecting
Tools: Fortune/Looting
Everything but capacitors: Energy Efficiency

**Comment by CTH999** [comment]
@q3AEWRSDTFGYHUJNKMIHUGBTYRFDYSIYGUH  ummm. this mod is already OP...

Also, would work great with [Harder](https://github.com/brandon3055/Draconic-Evolution/issues/1046)

And, [[Suggestion] Cross-mod fusion crafting upgrades for Draconic armor](https://github.com/brandon3055/Draconic-Evolution/issues/1050)

Also, don't forget Entropy Increase! Adds in storage to the 64-bit integer limit. and also makes it have a massive efficiency boost, but, makes entropy a lot more of a problem!

**Comment by Saklad5** [comment]
It might be interesting to add those properties by substantially decreasing the base values. It would make the mod slightly less OP, too.

**Comment by gigabit101** [comment]
This might happen in DE3 with a fancy new API, Right @brandon3055 ;)
