### ISSUE TITLE
i/o mode balance

### ISSUE THREAD

**Issue by davidb265** [brandon3055/Draconic-Evolution#1072]
## Base information
* Minecraft version: 1.10.1
* Mod version:2.1.6.
* Minecraft Forge version:12.18.3.2477
* Mod Pack: (if applicable)sky factory 3

cant put the i/o crystal in input/output mode in the tablet it said to shift right click to cycle to each one but no matter how many times i try that it wont come out of balance mode 

![untitled](https://user-images.githubusercontent.com/37049184/36949621-d3255af2-1fe2-11e8-8e26-05eacbcd1c4d.png)

**Comment by CTH999** [comment]
First, Balance is a WIP,
Second, did you have any tick lag? (Try /forge TPS) It might not cause very many visible delays, but there it could be a problem.
Third, I don't know if these would be a problem... I don't know for sure, just asking from expirence!

**Comment by covers1624** [comment]
Balance was removed in 1.11, Please update your mods.
