### ISSUE TITLE
Costum Dire crafting table recipe for creative capacitor

### ISSUE THREAD

**Issue by exceptionofend** [brandon3055/Draconic-Evolution#1073]
Hey,

Im pretty new here so i have probably just no clue what im doing but, i was trying to make a costum recipe for the creative flux capacitor.... i did make it to work just without the nbt tag that has the energy on it so basicly making the creative flux capacitor only a infinite amout of rf but not really useable since it doesnt recharge fast enough.

Q: how do i add the nbt tag, thats what i got -> its just a test with the sand /stone 

mods.avaritia.ExtremeCrafting.addShaped(<draconicevolution:draconium_capacitor:2>,
 [[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>],
  [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>],
  [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>],
  [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>],
  [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>],
  [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>],
  [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>],
  [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>],
  [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>, <minecraft:sand>, <minecraft:stone>, <minecraft:stone>]]);

thanks anyway for your time

**Comment by exceptionofend** [comment]
Oh right i also tried adding nbt tags but since i have no clue how exactly that works even after reading a lot on wikis i finally stoped even trying before i brake anything ...

**Comment by brandon3055** [comment]
Your doing it wrong. I have not really messed with minetweaker scripts so i cant tell you exactly how to do this but what you have there looks wrong. I suggest you look up some minetweaker tutorials. Or just take a look at scripts from other mod packs that add dire crafting recipes.
