### ISSUE TITLE
Laser Go through portals

### ISSUE THREAD

**Issue by gigabit101** [brandon3055/Draconic-Evolution#1074]
DO IT!!!! Brandon

**Comment by covers1624** [comment]
Yes.

**Comment by brandon3055** [comment]
[groaning noise]

**Comment by Saklad5** [comment]
Is this some sort of inside joke?

**Comment by covers1624** [comment]
Yes.

**Comment by brandon3055** [comment]
And no

**Comment by gigabit101** [comment]
And Yes?

**Comment by gigabit101** [comment]
![x2yzxnp](https://user-images.githubusercontent.com/5615438/36997886-03f5b0e8-20b3-11e8-87c1-41fd236b3849.png)

**Comment by gigabit101** [comment]
I can do this from my phone so...

**Comment by brandon3055** [comment]
![](https://puu.sh/zBi51/d9b1849148.png)

**Comment by gigabit101** [comment]
Lol

**Comment by gigabit101** [comment]
https://twitter.com/Gigabit_101/status/970758734296309760?s=19

**Comment by armkrub** [comment]
Wait! please add draconic reactor bomb `Go through` portal.

**Comment by doritobob269** [comment]
[https://coubsecure-s.akamaihd.net/get/b97/p/coub/simple/cw_timeline_pic/7ef1ee2e411/244c291d86a041abea2b4/big_1470800996_image.jpg]

**Comment by doritobob269** [comment]
![krusty_towers_111](https://user-images.githubusercontent.com/9941480/37571386-51a6856e-2ad2-11e8-9c10-f973bd363647.jpg)

**Comment by doritobob269** [comment]
![draconic towers](https://user-images.githubusercontent.com/9941480/37571474-88bdf612-2ad3-11e8-9f55-b260c29e12b1.png)

**Comment by tyler489** [comment]
What laser are we talking about :)
