### ISSUE TITLE
Draconic ball of power not outputing

### ISSUE THREAD

**Issue by DerpyNinja476** [brandon3055/Draconic-Evolution#1077]
## Base information
* Minecraft version: 1.10.2
* Mod version: 1.10.2-2.1.8.273-universal
* Minecraft Forge version: 1.10.2-12.18.3.2511

CRASH REPORT HERE
the game did not crash

i posted this a while ago but when i went to go look for it, i couldnt find it.
basicaly im having the same issue.  what side does the input on the draconic ball of energy and which side does the out put go on(the top or the bottom of the actual ball of energy)? thank you in advance for the help
Edit: when i put the out put on the top, it doesn't output to a flux point from Flux Networks, it is the same on the bottom

**Comment by brandon3055** [comment]
Yes the pylons have an input and output mode. Also Flux Networks is a very broken mod mask i checked so i wouldn't be surprised if it just does not work at all.

**Comment by DerpyNinja476** [comment]
@gigabit101 i did right click it and it still doesn't work no matter what i do.
@brandon3055 so what do i do, get an older version of zero core and flux networks. i really like the mod, its broken in 2 ways, its op and its broken and doesn't work half the time

**Comment by gigabit101** [comment]
try using something other than flux networks? to make sure the orb is working

**Comment by DerpyNinja476** [comment]
every thing but flux networks works, does anyone know a mod that does the same thing that i can have cross dimensional charging? before(a few weeks ago on the same version) everything worked, now nothing does

**Comment by wamc2017** [comment]
Quantum Entangloporter from Mekanism, Power cell from RFTools or Dimensional Transceiver from Ender IO should work cross dimensional... ;)

**Comment by DerpyNinja476** [comment]
ok thank you!
