### ISSUE TITLE
Loot Core compatibility issue (Wireless Crafting Terminal)

### ISSUE THREAD

**Issue by zedekblue** [brandon3055/Draconic-Evolution#1079]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.9.283-u
* Minecraft Forge version: 14.23.2.2618
* Mod Pack: FTB Revelation v1.6.0

## Info
If this is an issue for Wireless Crafting Terminal just make note of it and close this, I'll go ahead and report it over there.

## Issue
Loot cores, when enabled, don't get picked up by the WCT magnet card.

That's all. Thank you~

**Comment by brandon3055** [comment]
This isnt really a bug in ether mod just an incompatibility due to the fact that the loot cores are not actually items therefor the WCT does not know to pick them up.

**Comment by brandon3055** [comment]
I recommend DE's item dislocator as it has support for them and in the next update it will also be a bauble

**Comment by operinko** [comment]
That's not a perfect solution as Wireless Crafting Terminal can push whitelisted items straight into the ME system as opposed to your inventory, but as you said, it's not an issue with DE.
If you need that functionality, there's the config option to disable loot cores :)
