### ISSUE TITLE
Item Duping

### ISSUE THREAD

**Issue by silveranstavern** [brandon3055/Draconic-Evolution#108]
I notice that when I did my standard set up (dropping items from an open crate onto the explosion site, while behind a blast proof wall) that when I set up multiple blocks of TNT controlled by a red stone signal that it doubled the number of dragon hearts (or ore that it could affect if I went through the entire process).  The glitch has to do with the multiple blocks of TNT exploding at exactly the same time.  If the timing is off, or there is only one block of TNT, then the heart is not duplicated.

**Comment by brandon3055** [comment]
This is fixed in one of the latest versions.
