### ISSUE TITLE
Quarries generate invalid Draconic Ore

### ISSUE THREAD

**Issue by a20eac1d** [brandon3055/Draconic-Evolution#1080]
## Base information
* Minecraft version: 1.12.2
* Mod version:  1.12-2.3.10.284-universal

The Environmental Tech Void Ore Miners generate an invalid ore for Draconic Evolution:

https://i.imgur.com/PuW7Aja.png

**Comment by a20eac1d** [comment]
The reason for this is seems to be the fact, that the quarry generates all over with an OreDict entry of "oreDraconium" and this untextured block has that entry.

**Comment by covers1624** [comment]
This is a problem with EnvirommentalTech, They do not respect the OreDictionary wild card (meta 32767) Please open an issue with them and reference this one.
