### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by yurioh89** [brandon3055/Draconic-Evolution#1085]
## Base information
* Minecraft version: 1.12.2
* Mod version: 
Brandon's Core 1.12-2.4.0.152
Draconic Evolution 1.12-2.3.10.284
* Minecraft Forge version: 14.23.2.2616
* Mod Pack: (if applicable)

I have three questions.

Because when I break the manufacturing injector and the crystal with the pick, it disappears once and will not go into my inventory?

And why does my reactor core simply leave the site and start rolling over the map and then back to the site again?

And when I use the dragon heart in the recipe for fabrication, does it simply disappear once and for all?

Sorry for english

**Comment by brandon3055** [comment]
Regarding the crafting injector what pick are you using? It should drop as an item.

The dragon heart is used in the recipe yes.

And the core... Sorry dont know what your talking about xD

(If you haven't figured it out yet consider the fact that the core started rolling around April 1st)

**Comment by yurioh89** [comment]
kkkkkkkkkkkkkkkkkkkkkkkk

I'm going to make a video demonstrating these bizarre things.

**Comment by yurioh89** [comment]
Here's the proof video, as I do not know how to edit Minecraft mods, and you're responsible for the mod, so you'll know where the error is: kkkkkkkkkkkkkkk

https://www.youtube.com/watch?v=erTahV6XSQk

**Comment by gigabit101** [comment]
First of all the orb rolling around the world was a April fools joke. not a issue
Second the heart is used for the recipe you can get more. not a issue
Third Injectors not dropping seems to be a issue in the modpack as they should drop

**Comment by yurioh89** [comment]
Well according to the video that is posted on YouTube is not a joke anyway, it's real, and very bizarre, I'm going to test with the mod only to see what happens.

**Comment by covers1624** [comment]
1, The dragon heart is meant to be consumed.
1, The Reactor rolling arround is a joke for april fools, IT IS NOT a bug.
3, If you could set your language back to english and record the breaking again so we know what pickaxes you are using that would be amazing.

**Comment by Saklad5** [comment]
They’re using a Diamond Pickaxe and a Certus Quartz Pickaxe in that video.

It’s probably worth remembering that someone unfamiliar with the idea of respawning the Ender Dragon will assume using up the item it drops for something you need a lot of is a bug. I mean, that doesn’t excuse them from reading the manual before filing a bug report, but still.

**Comment by yurioh89** [comment]
Hahahahaha sorry, but I managed to clear the conflict, it may close, but it was funny the nucleus was rolling, I do not know how it happened but it will not happen again. But I have the folder if you want to get one up and test yourself, just talk. rs XD
