### ISSUE TITLE
Unable to link Energy Crystal I/O or Wireless Energy Crystal with AE2 Devices

### ISSUE THREAD

**Issue by landonreams** [brandon3055/Draconic-Evolution#1088]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.9.283
* Minecraft Forge version: 14.23.2.2618
* Mod Pack: FTB Revelations 1.6.0
* AE2 Version: rv5-stable-8

## Description
AE2's Energy Acceptor and ME Controller do not appear to accept input from Energy Crystals. When using the Energy I/O Crystal, the crystal charges, but the acceptor does not draw power. When linking a wireless crystal, the message "Device Linked!" appears and a link is briefly visible, before immediately being removed. No other information is shown in the log.

**Comment by Saklad5** [comment]
Huh. I’ve seen similar symptoms with Industrial Foregoing’s machines, but ony when changing the sides that energy can be accepted on. I’m nearly certain it isn’t Draconic Evolution’s fault there.

Is AE2 doing anything odd with sidedness?

**Comment by gigabit101** [comment]
This is not a DE issue.
