### ISSUE TITLE
[Logging] Stop the changeMode log spam

### ISSUE THREAD

**Issue by Nadermane** [brandon3055/Draconic-Evolution#109]
Hello, just a quick little issue I have with the mod: Every time I or another player on my server switches the Draconic bow's mode, that mode is being put into the server's console. When one player does it, it's fine, but on a server with multiple people, the log entries can quickly start becoming annoying. Please disable or add an option to disable the log spam from changeMode on line 111.

**Comment by brandon3055** [comment]
Oh wow... Thats some really old debug code i must have forgotten to remove when i added the bow. Thanks for letting me know it will be gone in the next release.
