### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Nicon4454** [brandon3055/Draconic-Evolution#1090]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12-2.3.10.284-universal
* Minecraft Forge version: 2651
* Mod Pack: (if applicable)

http://prntscr.com/j2aje9

**Comment by covers1624** [comment]
Turn on extended info, F3 + H, I'm fairly sure this is a duplicate of an Environmental tech bug.

**Comment by boosterdev** [comment]
go to
`config/environmentaltech/multiblocks/void_miner/ore`

replace
`"id": "OD:oreDraconium" `
with
`"id": "draconicevolution:draconium_ore"`

in all json files within that directory

**Comment by Nicon4454** [comment]
Thank you :)
