### ISSUE TITLE
Request: Player OP and Ease of Use

### ISSUE THREAD

**Issue by PyroFlareX** [brandon3055/Draconic-Evolution#1091]
Okay, I would make a add on myself but, simply I'll say I have no idea how. My request would be to make the draconic tablet (e.g. info guide thing) a bit cheaper... and to add EMC support to the mod natively or via config.

**Comment by gigabit101** [comment]
Its stone and 1 dust by default. (Its cheap)
Currently there are no plans on adding EMC support.
