### ISSUE TITLE
shift right clicking not changing modes

### ISSUE THREAD

**Issue by otsns** [brandon3055/Draconic-Evolution#1098]
Shift right clicking on energy I/O crystal with empty hand not changing modes because there is an item in 2nd hand! With both hands empty its changing fine.
Pls fix.
* Minecraft version: 1.12.2
* Mod version: 2.3.10.284-universal
* Minecraft Forge version: 14.23.3.2661

**Comment by brandon3055** [comment]
You can blame vanilla/forge for this one. There is not simple way around this that does not involve listening for all interact events which is kinda annoying. I may implement a solution for this but if i do it wont be any time soon.
