### ISSUE TITLE
Draconic Chests not sorting in FTB Revelations 1.8.0

### ISSUE THREAD

**Issue by Kvothealar** [brandon3055/Draconic-Evolution#1099]
I saw someone posted this a year ago about how Draconic Chests weren't sorting with Inventory Tweaks and a fix was going to be included in the next update. I'm not sure if it was fixed and then broke again or what?

Maybe I'm the one doing something wrong haha. All other chests are sorting.

**Comment by brandon3055** [comment]
Sorting does seem to work with the latest Inventory Tweaks. At least in my dev environment t it does...
