### ISSUE TITLE
Draconium Chest Inefficiency

### ISSUE THREAD

**Issue by Itszuvalex** [brandon3055/Draconic-Evolution#11]
Cause:
Draconium Chest's Description Packet is a copy of the full state of the entire inventory.

Issue:
When players put NBT heavy data inside the chest, such as ME drives, they receive
http://puu.sh/fUJwx/1c34eab0ad.png
while attempting to log in.

Fix:
Remove inventory itemstack synchronization from getDescription Packet.

Move into Container/Gui data flow, as normal chest inventories are.

Resolves:
Unnecessary data synchronization to multiple clients.  Everyone nearby receives the entire inventory data, even when it is completely unnecessary for them to do so.

**Comment by brandon3055** [comment]
Thanks for pointing that out i will fix it asap.

**Comment by brandon3055** [comment]
Fixed in snapshot 4
