### ISSUE TITLE
Admin dislocator

### ISSUE THREAD

**Issue by valveo** [brandon3055/Draconic-Evolution#110]
Looks like admin dislocator is not working if someone is opped on server.
Few players have been reported issue to me and when i deop myself (im only opped) it start working again.

**Comment by brandon3055** [comment]
Need more information. How is it setup, how is it activated etc.
If the player is too far away from it when it is activated it wont teleport them.

**Comment by valveo** [comment]
I have made spawn platform to air and there are screens to tell players some rules etc. Dislocator is between those 2 screen and stone button is one of dislocator sides. Player standing position is right next to dislocator marked by block.
I will post image of setup as soon as I get to home and login to game.

**Comment by brandon3055** [comment]
Hmm... I know of at least 2 servers and a popular mod pack (Tolkiencraft2) that use the advanced dislocator and none of them have this problem. Is it possible for the player to press the button while standing too far away? 

The best way to use it in your situation would be to have it in the ground with a pressure plate on top. That way you ensure the player is going to be close enough when it is activated.

**Comment by GreatOrator** [comment]
There is a range for the admin dislocator, the room I use it in for tolkiencraft II ensures the players are close enough when they use it.
