### ISSUE TITLE
Upgrading Wyvern armor/tools to Draconic makes them lose upgrades

### ISSUE THREAD

**Issue by nullifiedcat** [brandon3055/Draconic-Evolution#1101]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.10.284
* Minecraft Forge version: 14.23.3.2655
* Mod Pack: custom

I've applied some Basic upgrades to my wyvern tools and armor, and after I've upgraded them to draconic (fusion crafting), upgrades were lost and I had to apply Basic again. I think upgrades should stay on item.

**Comment by godleydemon** [comment]
Can confirm, same draconic version using the FTB Revelations pack. Had a Wyvern Chest with Wyvern full upgrades in it. When upgrading to Draconic, all upgrades were lost. Including the energy stored in it.

**Comment by gigabit101** [comment]
Can you please confirm that the modpack you are playing is not changing the recipes of the armour,
If this is the case that is what is causing this to happen.

**Comment by nullifiedcat** [comment]
Pack was without recipe changes, but it had hard recipes enabled in DE config

**Comment by gigabit101** [comment]
Can i ask what version of DE you are running?

**Comment by brandon3055** [comment]
Was never able to reproduce this bug.
