### ISSUE TITLE
[Request] Achievements

### ISSUE THREAD

**Issue by jstaff62** [brandon3055/Draconic-Evolution#1104]
The main one I'm requesting is one for perfecting the Chaos Guardian fight (taking no hits), or something similar just for fun, and because I noticed the mod has never had an achievement like this (it would also be an immensely satisfying achievement to have).

**Comment by chaos234** [comment]
At this place I would also add achievements for the reactor and for the energy storage multiblock (not only for it's core component)

**Comment by gigabit101** [comment]
There is no plans currently to add Achievements, A lot of effort for little gain,
This might come in DE3??
