### ISSUE TITLE
[1.7.10] OC Integration not correctly done

### ISSUE THREAD

**Issue by chaos234** [brandon3055/Draconic-Evolution#1105]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.7.10-1.0.2h
* Minecraft Forge version: 10.13.4.1614
* Mod Pack: FTB Infinity Evolved (sligthly edited - added ArsMagica 2)

## Detailed Problem

The problem depends on how OC API is integrated. The problem is, that I can control your Reactor over any Control Script but if it comes to a server reboot the script failes because the state isn't safed correctly in the region file applied to the coresponding block connected to the adapter.

Here is a screen from the NBTExplorer with the coresponding region:

![nbtexplorer_2018-05-11_14-28-56](https://user-images.githubusercontent.com/340106/39924850-b2b6c2ca-5529-11e8-9db0-0ce76aac0912.png)

This coresponds to the following:

![javaw_2018-05-11_14-44-05](https://user-images.githubusercontent.com/340106/39924865-ca561d86-5529-11e8-8bbf-c13ec28dc40f.png)

This applies to all other OC related connections and as long as this isn't fixed, new addresses are generated every time when the server restarts which makes it impossible to use OC for DE which is bad.

I hope that you'll take a look into this and fix this. Would be glad :)

**Comment by gigabit101** [comment]
1.7.10 is no longer supported.
