### ISSUE TITLE
Not showing percentage?

### ISSUE THREAD

**Issue by acoolghuy** [brandon3055/Draconic-Evolution#1106]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12-2.3.10.284-universal
* Minecraft Forge version: 14.23.3.2688
* Mod Pack: (if applicable)

When using the mod in the core at tier 8 it tells you the Percentage full
When using rftools in the screen module it doesn't show percentage?

![2018-05-15_17 59 17](https://user-images.githubusercontent.com/5675422/40072084-933a9cb6-586a-11e8-864a-6374d4e1b971.png)
![2018-05-15_17 58 53](https://user-images.githubusercontent.com/5675422/40072085-9356b3ce-586a-11e8-966e-c3f96222d815.png)

**Comment by gigabit101** [comment]
unfortunately this is not a issue that can be fixed this side
