### ISSUE TITLE
Fake Players able to Kill the Chaos Dragon

### ISSUE THREAD

**Issue by FallenEagle1** [brandon3055/Draconic-Evolution#1108]
Base information:
* Minecraft version: 1.12.2
* Mod version: 3.11.290
* Minecraft Forge version: 2687
* Mod Pack: All the Mods 3

This was first discovered with the mob crusher from industrial foregoing, but I also tested this with the draconic grinder and found the same results. Both the chaos dragon and the crystals that protect the dragon can be instantly defeated (kill the dragon, set the crystals to the inactive state) with these machines. Killing the dragon in this fashion also bypasses the need to take care of the crystals.

**Comment by gigabit101** [comment]
Yeah so there is not alot the can be done to stop this unfortunately
