### ISSUE TITLE
Massive Lag when Core overloads, when have max draconium inside

### ISSUE THREAD

**Issue by dilgar** [brandon3055/Draconic-Evolution#1109]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.4.265
* Minecraft Forge version: 14.23.3.2655
* Mod Pack: -
Everytime, i set core, which is loaded with 8 draconium blocs to overload, in a few seconds game freezes non stop every second, while this doesnt happens to the cores, which loaded less, then 8 draconium blocs.

**Comment by gigabit101** [comment]
Don't overload the core? There is not much that can be done about this.
