### ISSUE TITLE
fake player in chunkloaded chunks acks like real player for mob spawns with no despawns

### ISSUE THREAD

**Issue by Prophious** [brandon3055/Draconic-Evolution#111]
well what i'm meaning by title is that when i have chicken chunk spotloader(this is what i used, but might still happen with normal chunkloaders not just spotloaders) loading the chunks where the draconic evolution mob grinder is, its causing mobs to spawn, but not despawn

basically when i teleported to my mob spawners/grinder(ender IO powered spawners, not active at the time of teleport and for a long time before) there was over 800 mob entities near, it was very difficult to move

but i have no real idea why there was over 800 mobs near when i teleported there

the mob spawner/grinder is in the nether

version of draconic evolution is "Draconic-Evolution-1.7.10-v1.0.1-RC-4" i know there is an update but have not updated yet

**Comment by GreatOrator** [comment]
That has been improved in later versions.

**Comment by brandon3055** [comment]
Are the mobs being spawned by a stabilized spawner? If this is the case they would never despawn. This has been fixed in one of the latest versions.

**Comment by Prophious** [comment]
no, the mobs that would spawn are like the normal spawning(zombie pigmen and skeletons in a stronghold), but only in the chunks that are loaded with spotloaders/chunkloaders 

the spawners were off(ender IO powered spawners), tho not sure if any spawned in in the mob holding cell(i dont know what to call it) the floor is lined with conveyer belts and lead to the mob grinder

not totally sure if this makes sense to you tho.... let me know

**Comment by brandon3055** [comment]
Yea i know what you mean. But i dont think there is anything in de that could do that.

**Comment by Prophious** [comment]
i'll double check this in a few days with just DE, Ender IO, and chicken chunks (along with cores that are needed)... then i'll check with just ender io and chicken chunks to see if it still happens if it happened at first

**Comment by Prophious** [comment]
closing issue for now, but still will do testing, if you want to make a comment on it for "needs testing" please feel free

tho atm i am upgraded to the latest 1.0.1c
