### ISSUE TITLE
Magnets on FTB Revelation 2.0.0

### ISSUE THREAD

**Issue by RJHaytree** [brandon3055/Draconic-Evolution#1119]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12-2.3.11.290-universal
* Minecraft Forge version: forge-1.12.2-14.23.4.2707-universal
* Mod Pack: (if applicable): FTB Revelation 2.0.0

Hey there, Brandon! On our FTB Revelation 2.0.0 server, we've been having some lag spikes ever since our re-launch a couple days ago, which we have been profiling whenever we can. In a lot of the profile snapshots, there is a common occurrence: magnets. I don't suppose there is much that can be done on your side to help minimize this, as we're currently out of ideas on what more we can do. 

A few screenshots of the magnets appearing in the snapshots can be found below:
![image](https://user-images.githubusercontent.com/31384792/41820752-72fcd44a-77ce-11e8-9fee-c1c6fd11f7b3.png)
![image](https://user-images.githubusercontent.com/31384792/41820762-9a94695a-77ce-11e8-933e-ee8b13a65054.png)

Hopefully a fix of sorts can be found

**Comment by brandon3055** [comment]
I will need to look into this but i suspect this is not directly caused by the magnets but rather by massive numbers of entities / items within the magnets range. I may be able to improve efficiency a bit on my end but if you have that many entities in the world then you probably have other problems.

**Comment by brandon3055** [comment]
I have made some adjustments for the next release that should help but i do need to re write some of the logic to make it more efficient.
