### ISSUE TITLE
Reactor not producing ft 

### ISSUE THREAD

**Issue by thedeadgamer1** [brandon3055/Draconic-Evolution#1120]
First want to say enjoying the mod. Love it. So I know I'm a little late to party but anyways
I built my first reactor with the help of the mindcrafters and comoutercraft (so I don't end up on the couch for blowing up mine and my wife's base)  so I got it charged and it had its surge of power then both power production and heat started dropping. Its currently sitting at 0 RF/t any ideas? 

## Base information
* Minecraft version:1. 7
* Mod version:
* Minecraft Forge version:
* Mod Pack: ftb infinity 

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by brandon3055** [comment]
if i recall correctly in 1.7 the reactor will automatically shut down if you let its saturation reach 100% (can be used to implement an auto shut down feature) that may be what happened if you were not pulling enough power from it.

**Comment by thedeadgamer1** [comment]
I can get it to produce around 20k-21k but no higher. No matter what I set up output to it won't go above 20750ish RF/t.  I'm going to try a few things as well get on a different modpack in a different version. I'm determined to get a reactor up lol

**Comment by brandon3055** [comment]
what are you using for energy transport?

**Comment by thedeadgamer1** [comment]
From stabilizer is a cryo fluxduct into a the flux gate then a tesseract

**Comment by brandon3055** [comment]
and im guessing the other end of that tesseract is dumping into an energy core?

**Comment by thedeadgamer1** [comment]
You're correct. Tier 6 with only 115b RF in it

**Comment by brandon3055** [comment]
in that case Im guessing the computer program is setting the flux gate to 20k throughput (it should gate in the gate gui) i have not messed with that program much so im not sure why it would be doing that... Can you upload a screenshot of the reactor ui with the stats display enabled?

**Comment by thedeadgamer1** [comment]
Sure no problem. Give a little bit to get it (not home at the moment)

**Comment by thedeadgamer1** [comment]
i got a shot of everything for you btw my spacing  from reactor to my stablerizers is 6 blocks 

![2018-06-28_19 37 17](https://user-images.githubusercontent.com/40647320/42065800-2311d080-7b0b-11e8-95a1-79c432938dbd.png)
![2018-06-28_19 37 05](https://user-images.githubusercontent.com/40647320/42065804-27eec4be-7b0b-11e8-96bd-43f9f1d10164.png)
![2018-06-28_19 36 54](https://user-images.githubusercontent.com/40647320/42065807-2b75ee8c-7b0b-11e8-8c13-9c013a4f82dd.png)
![2018-06-28_19 36 39](https://user-images.githubusercontent.com/40647320/42065811-2e6ad2f6-7b0b-11e8-9165-1bbd77d67013.png)

**Comment by thedeadgamer1** [comment]
I followed the tur exactly on my ohibe and building along with pausing where needed. I was super careful with it knowing the dangers. Yes we have a back up copy of our world. Made it just after I rebuilt the last time to see if I made a mistake somewhere. Btw I really appreciate the assistance

**Comment by brandon3055** [comment]
In that case i really have no idea what the problem could be...
I guess if the program is regulating the input gate it should be safe to manually adjust the output gate as long as you dont push it too far (recommend starting around 200-300k). But i have no idea whats wrong with the computer setup. As far as i can tell it should be working...

**Comment by thedeadgamer1** [comment]
Thanks. I know its put of modded gaming (been around long enough to remember some of the classic mods)  was just hope maybe I screwed up somewhere and couldn't see it. I'll give it another go with a different reactor on that world if not in a different mod pack (ftb beyond)  and get out going

**Comment by thedeadgamer1** [comment]
I figured it out. Its the tesseract. I did some testing trying different energy transportation. Finally removed the tesseract and its functions properly.  Thanks again for that the help
