### ISSUE TITLE
Item Dislocator pulls from IE conveyor belts

### ISSUE THREAD

**Issue by jinks** [brandon3055/Draconic-Evolution#1125]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.12-297
* Minecraft Forge version: 2709
* Mod Pack: DW20 with manually updated DE
* IE version: 0.12-82

## Issue
I just noticed that the Item Dislocator pulls ItemStacks from Immersive Engineering's conveyor belts again.

Since this was already fixed ages ago, I suspect either you or @blusunrize changed something recently that breaks the proper interaction.

**Comment by brandon3055** [comment]
@BluSunrize nothing changed on my end.

**Comment by BluSunrize** [comment]
nothing on mine either, to my knowledge :V 

I honestly can't remember if I did anything to specialcase against your dislocator. I'll take a look next time I actually get to work on IE ^^

**Comment by jinks** [comment]
Did some further testing...

The same thing happens with the TE Fluxmagnet.

It works when I throw items manually on the belt. (I think the latest DE update which force sets the thrower did a lot of good here, it was more problematic before.) Items get pulled off immediately when they are put on the belt by a machine.

The Botania magnet ring seems to ignore conveyor belts completely.

**Comment by comp500** [comment]
Found the issue and fixed in #1154
