### ISSUE TITLE
DE change and create profiles

### ISSUE THREAD

**Issue by jonaspauleta** [brandon3055/Draconic-Evolution#1128]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.12.297-universal.jar
* Minecraft Forge version: FORGE 14.23.4.2729
* Mod Pack: FTB Revelation 2.2.0

## Bug Report
So, that is happening that I cannot change profiles or create profiles on the armor(as well as other items), I set the bind to NUMPAD1 to change profile, and the key does nothing, because I wanted to have 2 profiles, 1 for High speed flying and other for normal flying,
what can I do? is that a bug?

**Comment by brandon3055** [comment]
The armor does not currently support the profile system. I had intended to add support but never really figured out a good option for switching profiles. I guess for now i can just add a different keybinding for armor but in the 1.13 update that entire system will be re written.
