### ISSUE TITLE
Wireless Energy Crystal with sided target

### ISSUE THREAD

**Issue by fscan** [brandon3055/Draconic-Evolution#1129]
When validating the wireless connections, the side of the connection is not passed in. Therefore any target TE with sided energy will be removed from the active links.

https://github.com/brandon3055/Draconic-Evolution/blob/f91eb576de6192651ee7c092e5764532876c80c6/src/main/java/com/brandon3055/draconicevolution/blocks/energynet/tileentity/TileCrystalWirelessIO.java#L484

## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.112.287
* Minecraft Forge version: 14.23.4.2705

**Comment by fscan** [comment]
After looking through some issues, i found Issue #1088 .. which is basically the same problem (All AE2 machines are sided).

**Comment by ixanza** [comment]
I'm getting the same with ender io machines.

**Comment by covers1624** [comment]
I believe Brandon fixed this in dev iirc.

**Comment by fscan** [comment]
You're sure? The line i posted is still the same in master.

**Comment by covers1624** [comment]
`fixed in dev` can mean one of 2 things, its fixed locally and brandon is yet to push (90% of the time) and its been pushed and on the repo but a release hasn't been pushed.
