### ISSUE TITLE
License makes forks on Github illegal

### ISSUE THREAD

**Issue by Joaz** [brandon3055/Draconic-Evolution#113]
Hello,

I don't know why you don't use a FLOSS license, but what you use there is problematic to use with Github.

"You CANNOT
-Redistribute this in its entirety as source or compiled code."
-Create or distribute code which contains 50% or more Functionally Equivalent Statements* from this repository."

Well, if I just hit the fork button (as some people did), I'd be thereby violating your license because it makes me redistribute 100% of your code immediately, on my github. So that means that making a bug fix for your work would violate your license.

**Comment by brandon3055** [comment]
I have no problem with you forking the project for the purpose of creating a pull request or for private use as long as you are not compiling and distributing the mod. But thank you for pointing this out. I will adjust the licence.
