### ISSUE TITLE
crafting ejector crashes server

### ISSUE THREAD

**Issue by redgoblin88** [brandon3055/Draconic-Evolution#1131]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.12.297
* Minecraft Forge version: 14.23.4.2729
*modpack: https://www.curseforge.com/minecraft/modpacks/hades-reborn

## Crash report
[latest.log](https://github.com/brandon3055/Draconic-Evolution/files/2172866/latest.log)

the server has been running for several months to a year now but upon trying to add a discord/minecraft chat bot the server started to crash non stop pointing to numerous things, but after we tried dissabling Advanced Generators this is the log that we got which said something about "unable to get draconic ejector tier"

**Comment by brandon3055** [comment]
It sounds like something you changed is just causing a bunch of things to break... I cant imagine a discord bot doing something like that unless it has some heavy game integration to do things in world. Im not sure what could cause this.
