### ISSUE TITLE
Souls and Stuff

### ISSUE THREAD

**Issue by ItsOswin** [brandon3055/Draconic-Evolution#1136]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.12.297-universal
* Minecraft Forge version: 14.23.4.2729
* Mod Pack: FTB Revelations 

Hey mates wanted to know if in my Version Boss souls (Wither Boss and/or others) can be made droppable and if it can be made, how.
Even if I had to write smthng new id do it (Serverside)

Cheers to everybody
Ozz

**Comment by brandon3055** [comment]
I will add a config option to the next release. If you want to create a custom build for your server you should be able to just cherry pick the commit and build a custom version. 
Or an easier option would be to just extract the modified class "com.brandon3055.draconicevolution.handlers.DEEventHandler" from the new jar and insert it into the old jar used on your server. It should be compatible.
