### ISSUE TITLE
[1.12.2] Bow of the Wyvern auto-fire doesn't work

### ISSUE THREAD

**Issue by TheOpalium** [brandon3055/Draconic-Evolution#1137]
## Base information
* Minecraft version: v1.12.2
* Mod version: 2.3.12.297
* Minecraft Forge version: 14.23.4.2705
* Survival Multiplayer

## Issue
I'm having trouble with the Bow of the Wyvern on my server. When auto fire is enabled, the bow doesn't shoot at all when I hold down the right mouse button - it pulls all the way backward and then immediately snaps back, but no arrow is ever fired. Only once I release the button a single arrow is fired. Not entirely sure what could cause this.

Demonstration: https://gfycat.com/UnselfishCompassionateBuck

**Comment by TheOpalium** [comment]
It also affects the Draconic Bow. Oddly enough, I'm starting to suspect this is indeed a problem not only related to DE. I'll try some other mods with auto-fire bows and see if it also affects those.

**Comment by Awebb** [comment]
I have been observing this behavior over different versions of two FTB modpacks (SkyFactory 3 and Revelations). Both bows are affected. However, I suspect it has something to do with the energy, because the effect goes away, if you play with the bows settings for a bit. I have not been able to figure out how to reproduce the effect, though.

**Comment by brandon3055** [comment]
@Awebb That was my first thought but then i noticed he was testing in creative mode which should completely bypass the energy checks. Though possibly related if some mod is modifying the item's nbt or damage value in some way as the bow is about to fire that may reset the item preventing it from firing.

**Comment by brandon3055** [comment]
I will be adding a command to the next version of Brandon's Core that will dump a list all all event handlers. That may at least narrow down the list of mods that could be causing this (if it is another mod thats causing this).

**Comment by brandon3055** [comment]
Is this still an issue?
