### ISSUE TITLE
Enderio adds a second recipe for the End Crystal

### ISSUE THREAD

**Issue by CorruptedLink01** [brandon3055/Draconic-Evolution#1138]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.12.297
* Minecraft Forge version:14.23.4.2730

Enderio adds a recipe for the End Crystal and it uses the eye of ender

**Comment by HenryLoenwind** [comment]
This is outdated, we removed the "make End Crystal with oredicted glass" recipe when Forge started fixing the vanilla recipe with the glass ordict.

**Comment by covers1624** [comment]
Thanks @HenryLoenwind! I shall close this.
