### ISSUE TITLE
[Request] Revised CC Methods for Energy Pylon

### ISSUE THREAD

**Issue by cdl1051** [brandon3055/Draconic-Evolution#114]
It is well understood that ComputerCraft cannot cope with the energy storage in higher tier multiblock energy storage setups because CC is only 32 bit but we don't actually need CC to hold the value in a single variable.  A method that returned a decimal with a handful of significant digits as well as an exponent would work perfectly fine with CC.  For instance .getEnergyStored could return a 1x2 array containing 1.3457 in the first element and 9 in the second element thus representing 1.3457 billion RF.  I would display that on a screen but building the string 1,345,700,000 would be very easy as well.

**Comment by brandon3055** [comment]
This is due to a limitation in the RF API. I am going to add proper CC support for the core in the future. If you cant wait Computertronics has already added CC support for the core.
