### ISSUE TITLE
Draconic Flight Speed

### ISSUE THREAD

**Issue by Shybella** [brandon3055/Draconic-Evolution#1140]
## Base information
* Minecraft version: 1.12.2
* Mod version: latest
* Minecraft Forge version: 2705
* Mod Pack: (if applicable) DW20

Is there a way to turn down the Draconic armor speed modifier. I turned down the flight speed modifier in the config but doesn't seem to affect flight speed. 

This needs to be controllable on multiplayer servers.

**Comment by brandon3055** [comment]
There will be a config option in the next update.
