### ISSUE TITLE
Weird form of item duplication with Draconic Bow

### ISSUE THREAD

**Issue by Gutawer** [brandon3055/Draconic-Evolution#1141]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.11.290
* Minecraft Forge version: 14.23.4.2705
* Mod Pack: FTB Revelation 2.1.0 (stable)

## Bug report
With the Draconic bow on the following settings:
```
Arrow of Draconic Fire: On
Shock Wave Power: 4.0
Arrow Base Damage: 3.0
Arrow Velocity Modifier: +100%
Auto Fire: On
Explosion Power: 0.0
Magnification 300
```
I managed to get an OpenBlocks grave to spawn with a previous version of my inventory by shooting an arrow at full pull-back straight into the air and standing near the landing spot. I got the on-screen message `death.attack.customArrowEnergy`, and upon entering my house noticed a grave which, when dug up, contained a previous version of my inventory. Unfortunately I could only get this to happen twice, else I would have recorded a video to show proof of this.

**Comment by Gutawer** [comment]
I was using full draconic armour with no enchantments, and I did not die, the Draconic Armour appeared to stop me from dying while also causing me to "die", creating a grave inside my house (which is not where I was standing when this happened, weirdly enough). It seems like it killed some phantom version of my player from a while ago that the server was remembering, because an old form of my inventory was contained in the grave (the second time this happened, it had a slightly newer version of my inventory, I was in the process of upgrading from Wyvern to Draconic stuff). The server also has a Discord bot which reports chat logs which gave the message "Gutawer just died due to death.attack.customArrowEnergy!" in our Discord chat, except "I" never died.

**Comment by brandon3055** [comment]
Hmm... That's a tough one... I have no idea where to even start debugging this. Mi first thought would have been the gravestone mod is not waiting to see if the death event was cancelled before spawning your grave but that wouldn't account for the older inventory.. That sounds like as you said the server is for some reason keeping an old version of your player entity in the world and when the death event fires its running on that invalid entity. If that is the case this may not be an issue with DE or the gravestone mod but with whatever is causing that "ghost player" to exist...

**Comment by Gutawer** [comment]
Only just checked my github notifications, sorry for taking so long to reply - I have noticed since reporting this that upon closing the server down, it'll say "Player Name has disconnected" when they weren't online in the first place, so it appears as if the older players thing is what's causing this. My hunch would be that the inventories being dropped by these graves are the inventories of the players when they logged off, and that each "ghost" player is caused by leaving the server.

**Comment by brandon3055** [comment]
Yea that's pretty much what i thought. Unfortunately i dont think there is much i can do from my end to fix this issue.

**Comment by brandon3055** [comment]
I have made an adjustment on my end that may or may not fix this in the next release.
