### ISSUE TITLE
Typo in the fusion craftign area of Info Tablet. Low priority.

### ISSUE THREAD

**Issue by Wea1thRS** [brandon3055/Draconic-Evolution#1143]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.12.297
* Minecraft Forge version: 14.23.4.2739
* Mod Pack: (if applicable)

[Redacted crash report text as it is not applicable.]

There is a typo at the bottom of the Fusion Crafting section of the DE's Information Tablet. It is shown here below the "Comparator Output" text.
![image](https://user-images.githubusercontent.com/30428646/43065374-410dad0a-8e27-11e8-91c6-a16f629b93a2.png)

**Comment by brandon3055** [comment]
I am currently working on a complete re write for the system i use to document DE so i wont be pushing a new documentation build for this. Though i will fix that in the new system.
