### ISSUE TITLE
MobSoul is not showing in Stabilized Spawner

### ISSUE THREAD

**Issue by FaiThiX** [brandon3055/Draconic-Evolution#1144]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.12.297(2.3.12)
* Minecraft Forge version: 14.23.4.2705
* Mod Pack: FTB Revelation 2.2.0

## Crash report
```
NO CRASH REPORT AVAIVABLE
```

The Mob soul is not showing in the Stabilized Spawner after changing or placing it. But the spawner is spawning the monsters/animals.

![fce45053-928f-4b7b-b02c-bd0397bab852](https://user-images.githubusercontent.com/22944855/43141726-f077212e-8f56-11e8-932f-66d382cc775f.png)

**Comment by covers1624** [comment]
This was a deep with pick block, I remember Brandon fixing this issue, no idea if he has pushed the change.
