### ISSUE TITLE
[1.12.2] Stabilized spawner Issue

### ISSUE THREAD

**Issue by Elvarion** [brandon3055/Draconic-Evolution#1149]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.12.297-universal
* Minecraft Forge version: 14.23.4.2715
* Mod Pack: All the Mods 3 - Custom Lite version (Just removed a handful of filler mods)

Placing a Core on a Spawner containing a Wither Skeleton works fine until you place it down andthen break it again.
Then NBT data goes from minecraft:wither_skeleton to minecraft:air when broken the second time

- https://gyazo.com/c4f5f563230397dcc7f9e6dd6ef67f21
- https://gyazo.com/c16ac009eda4dcd9c78eb0d7776fc9ed

**Comment by brandon3055** [comment]
Breaking a spawner is supposed to clear its soul.

**Comment by Elvarion** [comment]
Ok, thanks for the clarification! :)
