### ISSUE TITLE
draconic evoulution crash with baubles

### ISSUE THREAD

**Issue by TheNimbleNinja** [brandon3055/Draconic-Evolution#1153]
## Base information
* Minecraft version:1.12.2
* Mod version: brandoncore 1.12.2-2.4.4.173 /draconic evolution1.12.2-2.3.13.306/ baubles1.12-1.5.2
* Minecraft Forge version:forge-14.23.4.2747
* Mod Pack: (if applicable)my custom modpack im working on

## Crash report
```
CRASH REPORT HERE
```
https://gist.github.com/TheNimbleNinja/a9c4138e72b01d46bad3ede115d80bcc

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by brandon3055** [comment]
Found your problem https://gist.github.com/TheNimbleNinja/a9c4138e72b01d46bad3ede115d80bcc#file-draconic-bauble-crash-L450
"ImprovedBackpacks" is repacking an ancient version of the baubles api and for some reason that is being loaded instead of the newer version.
