### ISSUE TITLE
bow enchants have no effect

### ISSUE THREAD

**Issue by shadoxxhd** [brandon3055/Draconic-Evolution#1155]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.12.297
* Minecraft Forge version: 14.23.4.2739
* Mod Pack: modified DW20

Issue: I enchanted a wyvern bow with power 5 and it deals the same damage as without the enchantment (zombies/skeletons survive with 4 hearts). I can't toggle enchantments on the bow either (infinity works, but doesn't have a toggle button).
On a wyvern sword, enchantments behave strangely too: sharpness seems to work only for the first mob hit, not for the AoE attack.

**Comment by brandon3055** [comment]
Yea enchantments have always been a bit broken. Especially on the bows. Its kinda tricky to dynamically support all vanilla bow enchants given how custom those bows are so i didn't really bother. I will try to add better enchantment support when i re write DE for 1.13.
