### ISSUE TITLE
[balance] bow massively underpowered compared to sword

### ISSUE THREAD

**Issue by shadoxxhd** [brandon3055/Draconic-Evolution#1156]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.13.306
* Minecraft Forge version: n/a
* Mod Pack: modified dw20

Draconic Bow: base damage 3, arrow speed +150%: deals around 20 damage, but needs >400k RF
Draconic Sword: deals 35 damage w/o upgrades; energy drain with wyvern damage upgrade still ~1300RF per hit incl. AoE
bow RF/damage: 20000
sword RF/damage: 23.4 (upgraded case); 37 unupgraded if energy cost stays constant

also, swords have AoE while bow shockwave makes shots prohibitively expensive (zombie killing shockwave 1 costs >4.5MRF)

**Comment by shadoxxhd** [comment]
Also, an power 5 enchanted ender bow (enderIO) deals more damage than any resonable-cost draconic bow for like 1kRF and has a quicker fire rate.

**Comment by BadLucKWyvern** [comment]
Bow seems over powered, but it cost a shiton RF per shot, instead of the sword that don't cost that much each hit. the bow is make for destructive purpose, when the sword is made if you run out of RF, that weapon can still make you able to attack. For PvP, that sword is also useless when all players have got the draco armor, maybe some skills like homing arrows on bows or waves attacks on the slowrd could be good for PvP

**Comment by shadoxxhd** [comment]
Actually, it does not - it deals *less* damage than an enchanted ender bow from enderIO (which doesn't even have DEs theme of endgame powerful stuff). While most draconic stuff is WAY more powerful than equivalent gear (most swords deal <10 damage, the draconic one 35 *before any upgrades* and also has an AoE; armor from other mods doesn't have a fancy shield and doesn't let you fly through fire unharmed), the bow is just average in most regards and has an INSANE energy cost. Making the bow have a faster baseline fire speed and an acceptable energy cost would already make it somewhat balanced, if sub par for DE. Adding special skills to tools would be nice to go with the debuff/fire immunity and flight of the armor, but is not directly related to this issue.

**Comment by brandon3055** [comment]
I do agree the bows could use some work especially in their base un-upgraded state tho once upgraded they are pretty darn powerful if you have the power to run them. I will be re balancing them in the 1.13 re write.
