### ISSUE TITLE
[Feature Request] Draconic Chest OreDoubling "Forceable Domain" to config

### ISSUE THREAD

**Issue by StevenSeegal** [brandon3055/Draconic-Evolution#1157]
We are running a custom Mod Pack with the UniDict mod (Changes recipes of most mods to output Ore Dictionary entries based on a priority list). Currently there is no Integration for Draconic Evolution in the UniDict mod.
I did made the Integration but the current version of UniDict is beyond the recommended build of Forge, and we are on the recommended build with our pack so we cannot update UniDict.

As for the normal recipes (without doubling) it's just pulling the furnace recipes which are already changed by UniDict, but on the OreDoubling you're forcing it to "thermalfoundation" if available.

Are you willing to put this "Forceable Domain" to the config so we, Mod pack developers, can chance the output of the OreDoubling to a different domain?

https://github.com/brandon3055/Draconic-Evolution/blob/14ce04a751a88c280baa59dbaa40936287eef94a/src/main/java/com/brandon3055/draconicevolution/lib/OreDoublingRegistry.java#L55

**Comment by brandon3055** [comment]
Done!
