### ISSUE TITLE
The mob grinder is running slowly 25 to 30 second pause between kills

### ISSUE THREAD

**Issue by Tawnyman** [brandon3055/Draconic-Evolution#1159]
* Minecraft version: 1.12.2
* Mod version:1.12.2-2.3.13.306
* Minecraft Forge version:14.23.4.2707
* Mod Pack: StoneBlock (server)

The mob grinder is running slowly on this server I have used the grinder on other 1.12 servers and have not run into this before. 

What is happening is it will kill the first few mobs to start but then it seams to have a internal 25 to 30 sec cool down before it will start killing again. This is a dam long time when you have a wither spawner running they can not break out of the draconium infused obsidian but they pile up to fast with the grinder not killing. 

After killing the server and having to set the world to peaceful I went to test and see what went wrong. Using spawn eggs it will kill the first few mobs, then it go's into cool down and will not kill anything for a count of between 25 to 30 seconds. Is there anyway to fix or change this I could not find anything in the mod config. Server tps was at 20 the whole time I was testing.

**Comment by shadoxxhd** [comment]
Maybe you just don't have enough RF to tun the grinder? It needs 80 RF per HP, I think - this would equal 1600RF per skeleton. Killing one skeleton per second would thus need 80 RF/t power generation.

**Comment by xElementzx** [comment]
This is an issue with a mod in the modpack, it does not happen with just D.E, TinyProgressions, ExU2.

**Comment by brandon3055** [comment]
Looks like @xElementzx figured this out. It seems to be caused by evilcraft vengeance spirits. They are invulnerable so the grinder gets stuck trying to kill them. I will have a fix and a blacklist in the next update.
