### ISSUE TITLE
[suggestion]Please provide a way to config reactor to avoid explosion after running out of fuel

### ISSUE THREAD

**Issue by FlandreCirno** [brandon3055/Draconic-Evolution#1160]
As I know if the reactor runs out of fuel, the reactor temperature will keep raising and finally explode. I suggest add a config when set to be true will force stop the reactor after it runs out of fuel, since it's a bit uncommon that a reactor explode after it runs out of fuel.

**Comment by CatRabbit499** [comment]
There is a fail-safe toggle in the reactor GUI...

**Comment by brandon3055** [comment]
You have the option of preventing the massive explosion but most of the balance for the DE reactor comes from these little dangers that you need to be aware of. 
I should also point out that the failsafe alone wont save you but it does allow you to automatically shut down the reactor when it gets low on fuel using no more than vanilla redstone.

**Comment by FlandreCirno** [comment]
The point is that you barely expect the reactor to explode that way before you are told or actually make that mistake. I knew that after blowing up a reactor and working through the equations in source code. I suggest that it is not pleasent for new comers repeat that mistake  in my server.

**Comment by brandon3055** [comment]
Ok considering the current state of the reactor documentation i can see your point. In 1.7 when the reactor actually had proper documentation there were very clear warnings about not letting the reactor run out of fuel. Fortunately i have almost finished the re write of my documentation mod for 1.12 which will finally contain proper documentation for the reactor.
