### ISSUE TITLE
loot dissapears after defeating chaos guardian[1.12.2]

### ISSUE THREAD

**Issue by tonimark** [brandon3055/Draconic-Evolution#1162]
issue after i successfully beat the chaos guardian I then died be the guardian itself(<-yeah that's another issue) i respawn back and go back to end searching for the loot but even some minutes with awakened item dislocator not even 1 of the 5 chaos shard can find this means that the loot got completely lost please make the loot of guardian everything loot as some explosives from guardian may blow up its shard

**Comment by Tawnyman** [comment]
the chaos shards are in the island you need to dig down in the middle of the island to find them then break them to get them -.-

**Comment by brandon3055** [comment]
Btw once you kill the guardian you still need to watch out form any its player seeking fireballs still flying around xD
