### ISSUE TITLE
Draconic Evolution + Botania Ring of Far Reach, Not breaking correct amount of blocks

### ISSUE THREAD

**Issue by TheFacelessOne** [brandon3055/Draconic-Evolution#1163]
* Minecraft version: 1.12.2
* Mod version: 2.3.13.306
* Minecraft Forge version: 14.23.4.2739
* Mod Pack: DireWolf20

- Using the ring of far reach from Botania (extends the distance you can interact with blocks from).
- Staff of power does not break the correct size of blocks. 
- Tested this with other mods that break multiple blocks and they work as normal. 
- https://youtu.be/SIgEzq6sLNo (ignore audio, I was watching Netflix on my second monitor, "Kim's Convenience" is the show for the curious... 7/10 passes the time)

**Comment by brandon3055** [comment]
This should be fixed in the next release.
