### ISSUE TITLE
Draconic Reactor does not output to adjacent flux gates.

### ISSUE THREAD

**Issue by DannyB5544** [brandon3055/Draconic-Evolution#1164]
## Base information
* Minecraft version: 1.12.2
* Mod version:2.3.13.306-universal
* Minecraft Forge version:14.23.4.2760
* Mod Pack: Sjincraft

**OLD**
Title says it all really. We've been trying to set up a draconic reactor on the server to look "nice" (as well as be useful) but after serveral restarts we've found that you cannot extract power from it. at all. charging is fine, but not extraction.

So far I've tried
 - Directly connecting a flux gate
 - Connecting energy crystals
 - Mekanism cables
 - Cryo fluxducts (yes, directly piping them isnt a good idea, but the reactor was off at the time since it needed about a minute to fill up its saturation.)

all to no avail. ive double and triple check all my crystal links, the flux gate directions, and more, but nope its not having none of that. Thanks in advance.

**EDIT/NEW**
It does now work, though as cat has mentioned reactor stabilisers don't export into adjacent flux gates. Updated the title to reflect this

**Comment by DannyB5544** [comment]
Ah, IO shoulda worded and explained that one better. It never worked in the first place, but I saw somewhere that a restart fixed it. so I waited for our daily restart but it still didnt work afterwards either.

**Comment by CatRabbit499** [comment]
Suggested title change: "Draconic Reactor Stabilizers do not send RF to adjacent Flux Gates"
![2018-09-10_12 56 41](https://user-images.githubusercontent.com/15235082/45312266-9eddea00-b4f9-11e8-941a-1305bdacd964.png)
Demonstrated here with the color of the Universal Cables from Mekanism set up as indicators.

**Comment by DannyB5544** [comment]
thanks for the help Cat but i cant extract the power either way.

**Comment by Tahakk** [comment]
If it never worked properly give us some screenshots so that we can see your setup :)

It's best to control it with computer, there are few [programs](https://tenyx.de/draconic_control/) that can run it.

**Comment by DannyB5544** [comment]
Alright, slept since then, it works now. Cat is right, it will not export to adjacent flux gates. Updating the thread now.

**Comment by brandon3055** [comment]
I have hat a test reactor in my dev environment dumping directly into a flux gate for months now and never had an issue. Pleas post screenshots of your setup including the flux gate and reactor GUI's

**Comment by DannyB5544** [comment]
@brandon3055 Here is a video in a empty fresh superflat [https://youtu.be/kuyzESvE9dM](Youtube)

I will add now that I **DID** try with redstone high too, still nada

**Comment by BadLucKWyvern** [comment]
Hi, im here to tell that i have the SAME issue
Ive followed a simple safe tutorial setup and ive noticed that imput gate under the infuser is working, but the output gate near a stabiliser isn't transfering RF.
I tryed many experimentations wich resulted to a meltdown...
Is it possible if a reactor setup is separated into 2 or more different chunk could make it not working ?

**Comment by DannyB5544** [comment]
i doubt it, it seems to be an issue with what the stabilzer detects as a cable. I know its not the flux gates themselves, since they do work, just not when adjacent.

**Comment by BadLucKWyvern** [comment]
Im wondering how brandon3055 didn't have that problem too
I also want to knwo why is there no explainations in the draconic tablet about the draconic reactor. theres clearly 0 info about it
The first time that ive played DE i never know there was a reactor :$

**Comment by brandon3055** [comment]
Yea... so don't mind me being a complete moreone over here. Turns out that reactor i had working perfectly fine in my dev environment... wasn't actually working perfectly fine anymore... Not sure how i missed that. 
In any case i found the issue and it will be fixed in the next release.

As for reactor documentation. I guess i just never got around to it. It was just one of those big annoying time consuming tasks where i was like... yea i will do this later... Yea later never came... Well actually it did! At this point i have almost finished Project Intelligence (the prototype of which is whats currently used to display DE's doc) once that releases it will include doc for the reactor.

**Comment by DannyB5544** [comment]
Heh, no worries. Thanks man

**Comment by BadLucKWyvern** [comment]
Thanks a lot :P
