### ISSUE TITLE
Resserection Stone + Chaos Islands in 1.12.2

### ISSUE THREAD

**Issue by DragoneerLaila** [brandon3055/Draconic-Evolution#1165]
## Base information
* Minecraft version: 1.12.2
* Mod version:1.12.2 2.3.13.306-universal
* Minecraft Forge version:14.23.4.2747
* Mod Pack: (if applicable)
The Wiki and previous DE versions have a resurrection stone to revive the dragon, the 1.12.2 version doesn't have that. without the resserection stone, theres no way out of the end and IF you kill the dragon to get back, you have no dragon to get eggs from, which means you CANT get the draconic armor and Tiered stuff. 
also in the 1.12.2 version of the mod, theres end cities so finding a chaos island is non existent, theres no way to find one.  can both of these get implemented? so the mod is actually possible?

**Comment by Tahakk** [comment]
There is vanilla function for this, look it up

**Comment by covers1624** [comment]
Vanilla has a mechanic for respawning the dragon, please use that. And yes the islands do spawn.
