### ISSUE TITLE
[Suggestion] 'disable shield' setting

### ISSUE THREAD

**Issue by shadoxxhd** [brandon3055/Draconic-Evolution#1166]
It would be nice if you could tweak your shield settings in the UI: disabled, emergency only (shield only blocks dangerous/lethal blows), full protection.
Since some mods provide bonuses when you receive damage or are low on health, preventing any incoming damage can be a disadvantage in some situations. In these cases, an option that only blocks dangerous (<2 hearts left) blows would grant protection as well as low health/damaged bonuses.
Likewise, if you just drank a protection 5 potion (or used some other temporary method of complete invulnerability), you wouldn't want to waste shield negentropy/energy on attacks you are fully immune against - allowing you to switch to a shield-less profile would allow you the benefits of flight, debuff immunity, etc while preventing unneccesary shield depletion.

**Comment by brandon3055** [comment]
Will add this to my todo list for the 1.13 re write.

**Comment by FoxMcloud5655** [comment]
Huh.  I actually didn't know this issue existed, but I already made a pull request for this exact thing.  #1352, to be in-fact.

**Comment by brandon3055** [comment]
PR #1352 has been merged.
