### ISSUE TITLE
[Issue?] Draconic Staff of Power Enchantments

### ISSUE THREAD

**Issue by accessdenied0** [brandon3055/Draconic-Evolution#1168]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.13.306
* Minecraft Forge version: 1.12.2-14.23.4.2707

Edit:
The original issue was that I was unable to apply _Looting_ and _Silk-Touch_ at the same Staff. I figured out that you had to disable the "conflicting" Enchantment in the Tool first (despite it said default off), to apply the Enchantment.

The issue that these two Enchantments somehow Conflict with each other persists which is actually not logically because _Looting_ is applied on the "Sword" part of the Tool, while the _Silk-Touch_ is applied on the Pickaxe part.

Is it possible to "loosen" this rule for the Staff in particular?

**Comment by brandon3055** [comment]
I will look into it but that is mostly controlled by vanilla so i cannot promos anything. In any case once you have applied them both by switching one off then applying the other they should both work normally rite?

**Comment by shadoxxhd** [comment]
A possible fix would be to make vanilla think of disabled enchantments as nonexistent (remove the enchantment tags, store in custom nbt) - with the side effect of allowing stacking reenchanting of the item.

**Comment by brandon3055** [comment]
Ok so i looked into this and the issue is that looting and fortune use the same code because they are similar enchants and fortune is not compatible with silk touch. There really isnt an easy work around for this.
