### ISSUE TITLE
Clientside crash with the wyvernsword.

### ISSUE THREAD

**Issue by ivardensphere** [brandon3055/Draconic-Evolution#117]
Hello!

got a clientside crash when someone uses the WyvernSword.

https://gist.github.com/ivardensphere/df3c7f4c951508aca04a

Forge version: .1408
Mod Version: Draconic-Evolution-1.7.10-1.0.1c

Please let me know if you need more information.

-Combi

**Comment by brandon3055** [comment]
Sorry for the late response. I cant figure out how this crash is even possible but i added an extra check to hopefully prevent it from happening in the future. 
Was this a one off or dose it happen often?

**Comment by ivardensphere** [comment]
Glad to hear from ya.

It happened every time someone used it. We did narrow it down to when hitting a mob from Infernal Mobs. I haven't tested out any of the other weapons however.

Let me know if you need more info from me.

-Combi

**Comment by brandon3055** [comment]
Ok just let me know if it still happens in the next release.

**Comment by GreatOrator** [comment]
Have not seen this crash since the latest version, anyone confirm?

**Comment by GreatOrator** [comment]
Closing issue so no further confirmation if issue exists
