### ISSUE TITLE
Reactor does not work properly

### ISSUE THREAD

**Issue by maxfun03** [brandon3055/Draconic-Evolution#1170]
* Minecraft version:1.12.2
* Mod version:1.12.2-2.3.12.297
* Minecraft Forge version:14.23.4.2715
* Mod Pack: All the Mods 3

When I first build and start the reactor in a new world, it works without any issues. But when I restart the game (all done without issues), and I need to restart the Reactor for any reason, it does not explode but it then sits there at 2001 C° and does nothing more no energy is extracted the heat doesn't rise but it happily destroys all the energy I pump in.
All is correctly connected, it ran without issue when I build it first and tested it. Also, Open Computer program has the same issues the gates are also correctly configured.

![2018-09-13_19 54 59](https://user-images.githubusercontent.com/43248851/45506274-0a8cb500-b78f-11e8-8e81-539bba7bb7b0.png)

**Comment by BadLucKWyvern** [comment]
#1164

**Comment by maxfun03** [comment]
Reactor works now and I feel dumb, it seems the reactor doesn't like the Cryo-Stabilized Fluxducts have them changed out with the DE Crystals and it works fine now.

**Comment by BadLucKWyvern** [comment]
For my part, its not working with any cable, i also tryed with capacitors as cable: no results
