### ISSUE TITLE
Cannot put misc. items in fusion injectors

### ISSUE THREAD

**Issue by ghost** [brandon3055/Draconic-Evolution#1171]
## Base information
* Minecraft version: 1.12
* Mod version: 1.12.1-2.3.13.306
* Minecraft Forge version: 14.23.4.2749
* Mod Pack: Modern skyblock 3 v3.4.2

Self explanatory title. Attempting to place some items in fusion injectors (I've tested nether stars and draconic cores) just doesn't work. Other items (draconium blocks, vanilla stuff, epic bacon) works fine

Here's my current setup if it's of any relevance:

![screenshot000993](https://user-images.githubusercontent.com/17183816/45603128-d3b8d800-b9f6-11e8-96b7-760ab2de1a6c.png)

Edit: seems to only affect multiplayer 🤔

**Comment by brandon3055** [comment]
There are absolutely no restrictions on what you can place in an injector. Is it possible you have some client/server inventory desync?

**Comment by DemonfangArun** [comment]
It happened over multiple client restarts, and the items existed in that I could use them for other crafting recipes.

**Comment by brandon3055** [comment]
I have do idea... Guessing you have tried breaking and replacing everything? 
This makes absolutely no sense to me... 
Not that it should matter but do you have your injectors in single item mode?

**Comment by DemonfangArun** [comment]
The wtf feeling is mutual. I didn't break everything, but I did try breaking one and placing it down, same behavior. I also tried single item mode both on and off (out of curiosity for what it does) with no change.
