### ISSUE TITLE
Client Hard-Lock upon creative pick-block on in-world item/block with NBT Data

### ISSUE THREAD

**Issue by CatRabbit499** [brandon3055/Draconic-Evolution#1174]
## Base information
* Minecraft version: `1.12.2`
* Mod version:
  - `Draconic-Evolution-1.12.2-2.3.13.306-universal`
  - `BrandonsCore-1.12.2-2.4.4.173-universal`
* Minecraft Forge version: `forge-14.23.4.2760`
* Mod Pack: (if applicable): `N/A`
* Optifine: Happens with and without Optifine. (Provided crash log gist is without OF)

If you use the `Ctrl` + `middle_mouse_button` on a placed item (draconicevolution:placed_item) that has NBT data, the client hard-lock crashes with a StackOverflowException involving NBT writing. I have only tested this in Singleplayer, however I would assume that this would crash you or the server if on a MP world given the hard-lock with mouse still grabbed in SP.

## Crash report
[Gist Link](https://gist.github.com/CatRabbit499/4c15b18cac85e1b76e7da580a021974d)

**Comment by brandon3055** [comment]
This was a fun one... Will be fixed in the next release.
