### ISSUE TITLE
Tinker Parts for CustonFusionRecipes.json

### ISSUE THREAD

**Issue by Nachtflame** [brandon3055/Draconic-Evolution#1175]
## Base information
* Minecraft version: **1.12.2**
* Mod version: **2.3.13.306**
* Minecraft Forge version: **14.23.4.2759**
* Mod Pack: **In-Dev pack**

## Crash report
**N/A**

No Crash, simply trying to figure out _IF_ it's possible to add Tinkers' Construct toolparts as ingredients with CustomFusionRecipes.json  So far I've tried - 
            "tconstruct:pick_head,1,0,{Material:[stone]}",
            "tconstruct:pick_head,{Material:"stone"}",
            "tconstruct:pick_head.withTag({Material:"stone"})",
and none of them seem to work.  Am I terribly mis-reading the instruction file? or is this something that's going to be trickier than the usual .nbt tagging?

**Comment by brandon3055** [comment]
You should be able to use "tconstruct:pick_head,1,0,{tag}" but you will need to use the exact NBT tag. To get that you can use "/bcore_client nbt" while holding the item. (it will be copied to your clipboard)

**Comment by Nachtflame** [comment]
Aha, that'll be useful.   Thank you! 
(I've been using '/ct hand', since i'm using CraftTweaker, and that seems to be a bit, uh, specialized for the mod.)

**Comment by Nachtflame** [comment]
And of course, the root issue is my inability to follow proper formatting in a .json...  >.<
Last item in any list DOES NOT get a comma at the end!

**Comment by Nachtflame** [comment]
Actually, even with formatting corrected, the recipe still doesn't appear to be working properly.  With proper nbt tag (from the bcore command), this is what I end up with: 
"tconstruct:pick_head,1,0,{Material:"stone"}"
Notepad++ appears to think the actual material type (between the extra "") is not a valid portion of anything, like it's only picking up on **"tconstruct:pick_head,1,0,{Material:"**  and _maybe_ **"}"** at the end.

**Comment by brandon3055** [comment]
If that is your entire file then it should actually be this.
`
[
    {
        "mode": "ADD",
        "result": "draconicevolution:wyvern_pick",
        "catalyst": "iceandfire:dragonbone_pickaxe",
        "energy": 10000,
        "tier": 1,
        "ingredients": [
            "tconstruct:pick_head,1,0,{Material:"wyvern_plustic"}"
        ]
    }
]
`
Just make sure thats in `config/brandon3055/CustomFusionRecipes.json`
There should be an error in the log somewhere if it fails to load. Feel free to post your log using gist or a pastebin like service.

**Comment by Nachtflame** [comment]
one of several recipes I'm adding.  Everything else loads/shows properly in JEI.
Error section from my latest log: https://pastebin.com/dQa2zZW9

**Comment by brandon3055** [comment]
Ok so figured it out. Just a little quirk of json you need to escape quotes inside a string like this
```
[
    {
        "mode": "ADD",
        "result": "draconicevolution:wyvern_pick",
        "catalyst": "iceandfire:dragonbone_pickaxe",
        "energy": 10000,
        "tier": 1,
        "ingredients": [
            "tconstruct:pick_head,1,0,{Material:\"wyvern_plustic\"}"
        ]
    }
]
```

**Comment by Nachtflame** [comment]
Excellent! Muahaha!
