### ISSUE TITLE
Ender Energy Manipulator not usable in Sky Factory 3

### ISSUE THREAD

**Issue by BlackFranky** [brandon3055/Draconic-Evolution#1178]
## Base information
* Minecraft version: 1.10.2
* Mod version: 2.1.6.263
* Minecraft Forge version: 12.28.3.2477
* Mod Pack: Sky Factory 3

The Ender Energy Manipulator is still not usable in Sky Factory 3. While it can now be placed down, nothing happens even after a long wait. As a side effect, the end crystals are no longer destructible until the End Dragon has been killed and the Ender Energy Manipulator has disappeared.

**Comment by brandon3055** [comment]
It needs to have a large land area around it where it can spawn a bunch of enderman.
