### ISSUE TITLE
Question - Reusable CFR Ingredients?

### ISSUE THREAD

**Issue by Nachtflame** [brandon3055/Draconic-Evolution#1180]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.14.308
* Minecraft Forge version:  14.23.4.2759
* Mod Pack: **In-Dev pack**

Once again, no Crash/issue, just a question - 

How would I make an ingredient Re-Usable in CustomFusionRecipes.json?  I'm thinking specifically of functionality like the *Upgrade Keys*, leaving the one specific ingredient in the injector.
Much thanks for your response!

**Comment by brandon3055** [comment]
This is not currently supported via the CFR config. The only way to do this would be via a mod that uses DE's fusion crafting API.

**Comment by Nachtflame** [comment]
Okay. Thanks for letting me know. :)
