### ISSUE TITLE
Chaos dragon lagging Tick rate

### ISSUE THREAD

**Issue by noezinho** [brandon3055/Draconic-Evolution#1182]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.4.5
* Minecraft Forge version: lastast

when i killed chaos dragon i broked the crystal in center, after this happen a explosion, and after the explosion the world started to lag, not in FPS but in tick rate, like 15 seconds to pick a item on floor, i dont know what to do

**Comment by brandon3055** [comment]
If will lag until the explosion completed which depending on your PC specs should take anywhere from a few seconds to a couple minutes. If your pc can not handle it then set "disableChaosIslandExplosion" to true in the DE config.
