### ISSUE TITLE
[Suggestion] Ring of Speed, Strength, Shield

### ISSUE THREAD

**Issue by shadoxxhd** [brandon3055/Draconic-Evolution#1188]
all rings:
-only one of each type can be equipped at a time; any further ring will be deactivated (background of item box turns red)

Ring of Speed stats:
-bauble-able ring that configurably increases moving speed, flight speed and vertical flight speed
-wyvern tier; possibly draconic tier upgrade for flight speed function
-enhancements increase speed (single or multiple enhancements for different buffs?)
-might need energy; draconic armor does this w/o though, so probably not
-buff stacks with armor buff
-doesn't allow flight on its own, but does buff angelic ring/environmental tech flight modifier/...
-draconic tier can be enhanced to prevent knockback (each enhancement reduces by 33/50%)

Ring of Strength stats:
-bauble-able ring that gives the old vanilla strength potion effect, multiplying all damage done
-wyvern tier gives new vanilla buff, adding a few hearts to each attack
-draconic tier gives %-based buff
-both buffs can be infusion-enhanced
-not sure if it should need energy
-additional enhancement?

Ring of Shield stats:
-bauble-able ring that gives a small amount of armor (a bit less than headgear of the appropriate tier)
-normal armor enhancements, but more effective than on armor
-better entropy resistance than armor, but low initial energy storage makes it practically worse than normal gear
-fully enhances draconic variant could have a shield as strong as a slightly enhanced draconic chestplate
-can be enhanced to polarize the shield
-polarization adds one of 3 buffs (can be changed in config; change color of shield; might be enhanced to add multiple??):
  -projectile reflection (doesn't take damage from normal projectiles (arrows, blaze/ghast fireballs; wither and up still do normal damage), reflects them back to source)
  -push back melee attackers
  -area shield (2m-15m radius, configurable, max range depends on total shield strength)
-projectile reflection and melee pushback only reach 100% respective immunity when either armor is equipped or ring is upgraded to max (depends on total shield)

other stuff:
-draconic tools should get speciality enhancements too
  -sword: damaging energy wave (like eg. nier automata)
  -hoe: makes farmland speed up tickrate (like that botania item (pasture seed I think))
  -bow could get its energy arrow from this; energy arrows should be mildly armor piercing and homing (toggleable)
-draconic armor should only get its special buffs after enhancement (anti-poison, strong flight speed boost, strong speed boost, strong jump boost)
-rings should be able to be equipped to the armor, freeing up the ring slot and making the special buff armor-native (fused ring type can't be used in ring slot as well)

**Comment by brandon3055** [comment]
These sound like good suggestions but i am a bit past the point of adding major features to 1.12.
I will keep these in mind for 1.13 but i'm not sure if they will fit with the other changes i have planned.

**Comment by FoxMcloud5655** [comment]
Revisiting this, I'm actually making a mod myself called Draconic Additions for 1.12.2, and I was thinking of adding rings that allow you to have a minor shield boost (for a more mid-game friendly approach).  These are some good ideas, so I might be taking some inspiration off of these.

**Comment by brandon3055** [comment]
@FoxMcloud5655 Sounds like a good idea. I think a lot of these would be better suited to an addon anyway.
