### ISSUE TITLE
Mobs instantly disappear when using notch apple on spawner.

### ISSUE THREAD

**Issue by Talon32** [brandon3055/Draconic-Evolution#1189]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.7.10-1.0.2h.jar
* Minecraft Forge version: 10.13.4.1614
* Mod Pack: FTB Presents CrackPack

Issue - I've been testing Stabilized mob spawners in a Creative world. I ran into an issue where adding a Notch Apple to a spawner of a hostile mob (Blaze and Enderman) let them spawn but they would instantly disappear. When I attempted it with Sheep, they spawned normally, I'm not sure if it's because I spawned in the souls with commands or if it's something else.

**Comment by brandon3055** [comment]
Sounds like your playing on peaceful mode. That or they are instantly despawning because you are too far away. Though if you are that far away it should not spawn unless you have applied a nether star which should prevent them from despawning.
