### ISSUE TITLE
Crash When Shooting Blue Slime With Draconic Bow

### ISSUE THREAD

**Issue by RoloEdits** [brandon3055/Draconic-Evolution#119]
When Shooting A Blue Slime With The Draconic Bow I Crashed

http://pastebin.com/w2ARyeEX

**Comment by Ianaver** [comment]
unable to reproduce... sorry :/

**Comment by RoloEdits** [comment]
Yes it may be an enchant causing it then

**Comment by Ianaver** [comment]
try going into a test world and enchant the bow then hit a blue slime, tell me what happens and if it crashes then I will attempt to reproduce this

**Comment by RoloEdits** [comment]
i updated my enchanting mods and it seems to fix it though i am getting weird rendering when holding the bow in my hand and looking at any creature. but not with a bow with any enchantments which means i have another problem to find and i dont think its with the bows but an enchant

**Comment by RoloEdits** [comment]
actually even just a bow with power enchant on it i'm getting weird rendering.

![2015-07-29_12 55 27](https://cloud.githubusercontent.com/assets/12489689/8968322/4c347966-35f1-11e5-8d95-9717ea799422.png)


![2015-07-29_12 55 33](https://cloud.githubusercontent.com/assets/12489689/8968332/519908cc-35f1-11e5-90c7-8fb4c9a1565d.png)

normal bow its just fine

![2015-07-29_12 55 39](https://cloud.githubusercontent.com/assets/12489689/8968334/54a07e2e-35f1-11e5-9d1f-a99a6283d4af.png)

**Comment by RoloEdits** [comment]
i should mention i have had rendering problems before with the bow before,but i figured it was something else causing it and im not much of a bow person so i hardly ever use it.

I also have fastcraft in my pack.

**Comment by Ianaver** [comment]
if you have AMD drivers then something weird may be going on there

**Comment by RoloEdits** [comment]
i have no amd i have nvidia

**Comment by GreatOrator** [comment]
do you have Optifine installed as well?

**Comment by RoloEdits** [comment]
no just fastcraft

**Comment by Ianaver** [comment]
try without fastcraft, if that doesn't work try updating your graphics drivers

**Comment by brandon3055** [comment]
I am also unable to reproduce this crash. Please let me know if you figured it out.

**Comment by RoloEdits** [comment]
I have not been able to figure it out as it does not always happen so i'm guessing its some problem with the way my GFX Card is handling rendering.

**Comment by Ianaver** [comment]
Just out of curiousity, what is name of the card that you have? Also try updating your drivers if you have not done so already, maybe somehow one of the fixes will fix your render issue! :)

**Comment by GreatOrator** [comment]
RoloEdits can you list all of the mods you have along with DE?  Also, have you tried loading a world with DE and brandonscore as the only mods?

**Comment by RoloEdits** [comment]
After updating DE and Fastcraft it does not seem to happen anymore
