### ISSUE TITLE
[Possible Issue] Shield blocks hunger damage

### ISSUE THREAD

**Issue by KertaLosataure** [brandon3055/Draconic-Evolution#1197]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.13.306
* Minecraft Forge version: 8.0.99.99
* Mod Pack: (if applicable) FTB Revelation v2.5.0

After playing with Draconic Evolution's armor, I noticed that my shield was pinging constantly as though it was absorbing damage even though I was inside a closed area with no mobs around. After a bit of confusion, I discovered it was somehow absorbing the hunger damage as I had not eaten any food for a while in the game. It seems like that shouldn't be happening to me so I thought I would report this behavior. Not sure if it's intentional or if there's just no way to code around it so hunger damage still applies even when wearing the armor. Note: This occurred with Draconic-level armor, I have not tested it with Wyvern armor.

**Comment by brandon3055** [comment]
This is technically working as intended because the shield was meant to block any and all damage sources. In the next re write i will be making changes so damage sources like this bypass the shield.
