### ISSUE TITLE
Redstone Furnace Recipe broken

### ISSUE THREAD

**Issue by unpure** [brandon3055/Draconic-Evolution#120]
Hey there.
It seems like the recipe to smelt draconium dust to draconium ingots is broken in the TE4 redstone furnace. NEI shows the recipe but it is not possible to place the dust inside of the redstone furnace.
Item conduits or ME export bus cant place them into the furnace too.

A full list of mods that are used in my modpack can be found here:
http://upclan.de/modpack/info/

I'm using Draconic Evolution 1.0.1c with forge 10.13.4.1481

Sorry for my bad english, i hope its not to hard to understand.

**Comment by brandon3055** [comment]
i am aware of this issue and i will be looking into it as soon as possible.
