### ISSUE TITLE
Item Dislocator Not Attracting Items

### ISSUE THREAD

**Issue by douglasg14b** [brandon3055/Draconic-Evolution#1201]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.15.312
* Minecraft Forge version: 14.23.5.2768
* Mod Pack: ATM3

Fairly simple, the item dislocator and the awakened item dislocator are not attracting items in any way.

Not sure if this is a bug, a config, or a user issue.

**Comment by drunkripper** [comment]
@douglasg14b What does your config look like? It seems to work fine for me. (Keep in mind it just puts the dropped item into your inventory, it doesn't pull them towards you like some other magnets do. it "dislocators" them into your inventory as far as I can tell [first you have to shift right click with it in your hand to activate it, and if you're sneaking with it, it will not work either)

**Comment by douglasg14b** [comment]
@drunkripper Is there a way for me to test or debug this with the modpack I'm using?

Items will stay on the ground until I get within vanilla pickup range, then they will fly towards me and into my inventory.

**Comment by drunkripper** [comment]
@douglasg14b make sure you've actually activated it.

**Comment by douglasg14b** [comment]
Oh wow, it was user error. I assumed it was always active. Shift-Right Click when in hand actives. Sorry to waste your time.
