### ISSUE TITLE
[Feature Request] Max Long I/O into a core

### ISSUE THREAD

**Issue by drunkripper** [brandon3055/Draconic-Evolution#1202]
Currently as far as i can tell is that the max RF/t into a core is max_int. Is there any reason it doesn't just use the java long as the max I/O? :)

**Comment by brandon3055** [comment]
Both the RedstoneFlux api and Forge Energy use integers. And TBH with the exception of say messing around in creative or draining one T8 core into another you will never need more than the current max throughput.
