### ISSUE TITLE
Mob Grinder Crash

### ISSUE THREAD

**Issue by Nadermane** [brandon3055/Draconic-Evolution#121]
Hello Brandon,

I have another issue for you to potentially address; every time I allow a Mob Grinder to kill a Wither after it did its initial explosion, the client crashes with the error message:

* "Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: The received string length is longer than maximum allowed (20 > 16)"

I am powering the Mob Grinder with a Tesseract, and it only is supposed to kill a single Wither. I have not tested this with anything other than a Tesseract yet, but I'm guessing that's got nothing to do with it. The server doesn't seem to be faced with it. I have included the latest FML logs below, having only edited out my PC account username.

The log files (I would post this to Pastebin, but it does not handle 22MB text files well... MEGA it is!):
* [FML-server-latest.log](https://mega.nz/#!uYIgFRLB!VmHQZDVk8UcEBTECjwLUD9hQbhKw7E0LUXqHpmwVs7g)
* [FML-client-latest.log](https://mega.nz/#!7RICnRhT!9Ho0XDqb-r-afaVPKiHejngmR2RUBQmyznEa9Hs-RdM) (Warning; Ginormous)

**Comment by brandon3055** [comment]
Sorry it took me so long to get to this i have been a bit busy and am only just getting to go through all the issues.

I was unable to recreate this issue and i have setup some pretty crazy wither farms on servers in the past with no issues. It seems the links you have posted have expired so could you please repost them. And perhaps just cut out the interesting parts and use pastebin.

**Comment by GreatOrator** [comment]
Hopefully they eventually reply.  Closing until they do since can not replicate

**Comment by cdl1051** [comment]
I just got the same error message as did the other player on my server.  The server is up but no one can connect.  The game immediately crashes with a ticking screen error.

**Comment by cdl1051** [comment]
pastebin.com/35D6sTqS

**Comment by Yurdol** [comment]
I recently encountered this same issue with the mob grinder on my infinity evolved server.   Better yet i have a backup of the world that is loadable until you try entering the nether where the mob grinder is located.  As soon as you try and enter the nether you are met with the string length exception and reloading the world becomes impossible unless you use mcedit and delete the mob grinder.   

If you'd like i can give you a copy of the backup for testing purposes.
