### ISSUE TITLE
Tool Textures and Values Broken? 

### ISSUE THREAD

**Issue by bigbluu722** [brandon3055/Draconic-Evolution#1212]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.17.321-universal
* Minecraft Forge version: 14.23.5.2775 (I think) 
* Mod Pack: (if applicable): N/A

## Crash Report
N/A
## Other Info

Not sure what would've caused this, but the tools/textures from draconic seem to be broken as well as damage values + attack speed being broken. Any help fixing this would be appreciated.

https://i.imgur.com/CSp2CXu.png
https://i.imgur.com/ScraDVI.png

**Comment by brandon3055** [comment]
If i had to guess another mod in your pack is probably screwing with things.

**Comment by bigbluu722** [comment]
Turns out restarting the pack a few times fixed the issue.
