### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by joshuasuperboy** [brandon3055/Draconic-Evolution#1213]
Can i make a 1.12.2 spotlight on this mod? Or is it not really needed? Not that much has changed since 1.10. The only things that have changed are the new enchanted reaper books and single item mode on the draconic fusion crafting. The only thing direwolf20 in the 1.10 spotlight he did not talk about was the draconic reactor. I was thinking about making a new spotlight for 1.12.2.

**Comment by brandon3055** [comment]
You are correct. Not much has changed but there is nothing stopping you from creating a spotlight if you want to.
