### ISSUE TITLE
Pack Dev Question Regarding Chaos Islands

### ISSUE THREAD

**Issue by Vyraal1** [brandon3055/Draconic-Evolution#1214]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.17.321
* Minecraft Forge version: 2772
* Mod Pack: FTB Interactions (FTB's next expert pack)

Hi, I'm working on an upcoming modpack and was curious if there was any way I could get Draconium/GTCE Tungstate to spawn specifically only in chaos islands. Do you use a certain structure or chunk generator when creating the islands? Would it be possible to maybe turn it into a specific Biome like chaos island so that common ore generation methods like CoFHWorld can make a distinction to spawn ores on the island?

There are certain endgame ores we want to occur in the end, but at the time we also want to have them appear more frequently in the island to possibly make the mining more hazardous.

**Comment by Vyraal1** [comment]
Customizing the Chaos Island Spawn level would actually be a terrific workaround and the simplest way to do it. That would be a pretty good solution if you could implement that.

**Comment by brandon3055** [comment]
Will be in the next update.
