### ISSUE TITLE
Arrow model causing low framerate

### ISSUE THREAD

**Issue by bathrobehero** [brandon3055/Draconic-Evolution#1215]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.13.306
* Minecraft Forge version: 8.0.99.99 (14.23.4.2759)
* Mod Pack: FTB Revelation 2.5.0

Arrows shot from the Draconic Bow are crippling the framerate.

I have 120 FPS with Vsync but shooting a bunch of arrows drops my FPS to around 10 until they disappear:

https://i.imgur.com/N3lXSVM.png

So the bow is practically useless when you have to shoot a lot and others can trigger it for you as well. Without shaders mod you need like double the arrows but the effect is the same.

I'm guessing the red arrow model has a shitton of polygons or something. Regular arrow models have no effect on the FPS.

**Comment by brandon3055** [comment]
Next release will have a config option to disable the custom model.

**Comment by bathrobehero** [comment]
Awesome! Thank you!
