### ISSUE TITLE
[1.12.2] Chaotic Upgrades/Tools Still WIP?

### ISSUE THREAD

**Issue by AwesomeAlec1** [brandon3055/Draconic-Evolution#1216]
Minecraft version: 1.12.2
* Mod version: 2.3.13.306
* Minecraft Forge version: 14.23.4.2760
* Mod Pack: Direwolf20 v2.3.0

I haven't seen this question asked anywhere else in the last 10 months, but I still have the sneaking suspicion that you've gotten it a lot; still, here it is anyway.

Are the draconic tools/armor ever going to be given chaotic tier upgrades? Also, will there ever be a set of chaotic armor/tools?

**Comment by brandon3055** [comment]
You are correct. This is a very common question. 
The answer is Chaos tier "everything" will be coming in DE 3 (for MC 1.13+)

**Comment by mendel3** [comment]
> You are correct. This is a very common question.
> The answer is Chaos tier "everything" will be coming in DE 3 (for MC 1.13+)

Is the source of this public yet? And are you currently developing it using the 1.13 forge builds or are you changing all of the BlockIDs and stuff

**Comment by brandon3055** [comment]
tbh i have barely started the DE3 rewrite. It will eventually be on github but so far i have just been messing with ideas for new tool models and thats about as far as i have got so far.
Chances are it will not be backported to 1.12 but thats mainly because i suspect 1.13+ will have mostly taken over by the time i finish DE3

**Comment by GeorgerGamer** [comment]
**Please backport it to 1.12.2 for the sake of those 0.3 (random number:) million people who are still playing on 1.12.2!!!**

**Comment by GeorgerGamer** [comment]
> tbh i have barely started the DE3 rewrite. It will eventually be on github but so far i have just been messing with ideas for new tool models and thats about as far as i have got so far.
> Chances are it will not be backported to 1.12 but thats mainly because i suspect 1.13+ will have mostly taken over by the time i finish DE3

I saw that a youtuber (MrLololoshka) had chaotic items. **WHY?**

**Comment by FoxMcloud5655** [comment]
To the person who keeps posting here and deleting their posts, the reason why you are seeing Chaotic anything is because of my mod, Draconic Additions.  Chaotic tier stuff will not be backported to 1.12.2.
