### ISSUE TITLE
[Suggestion] draconic helmet 

### ISSUE THREAD

**Issue by MasterSloth1** [brandon3055/Draconic-Evolution#1218]
## Base information
* Minecraft version:1.12.2

so with the feature auto feed on the draconic helmet it will automatically eat food in your inventory, maybe add a new item wyvern lunchbox which can be upgraded to a awakened lunchbox possibly a chaotic lunchbox lol which can be upgraded using the upgrade keys to hold more items, maybe make it require rf. what it does is it will hold onto all your food so that the helmet can automatically grab food out and eat it taking up one space in your inventory compared to several, also the ability to list food that doesnt have a hunger stat like the fruit of grisaia from botania would be appreciated also the ability to place the advanced disloactor into a bauble slot and then have it bound to a hot key would also be quite nice

**Comment by brandon3055** [comment]
There are already mods that add lunchboxes. I kinda like the idea of making dislocators baubles so i will add it to my ideas list for DE3
