### ISSUE TITLE
Reactor GUI not showing.. [1.7.10]

### ISSUE THREAD

**Issue by JavaCalorious** [brandon3055/Draconic-Evolution#1219]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.0.2h
* Minecraft Forge version: 10.13.4.1614
* Mod Pack: Own Modpack (Used with JEI, if thats helpful in solving)

## Problem:
 - Reactor GUI not opening

## Details:
   Ok, I tried doing this draconic reactor before and the GUI showed, but now, I have checked the stabilizers and injector positions, and nothing works. I right click the stabilizer and nothing shows, I right click the injector and nothing happens too. However, the comparator mode works.

![2018-12-09_19 43 06](https://user-images.githubusercontent.com/40225169/49696825-c7ee4380-fbea-11e8-8463-f714a9314cf7.png)

## Additional Information
  - GUI Scale: Normal

**Comment by brandon3055** [comment]
So... ahhh... it looks to me like there may be a block of cobble... or 24. Blocking line of sight between the core and the stabilisers.
You may need to break and replace the core after you remove the cobble but im not sure about that 1.7 was a very long time ago.

**Comment by JavaCalorious** [comment]
I've tried that before, however it didn't work.

Yeah sorry that I'm commenting on something about 1.7.10, its really the only version that I play with mods.

**Comment by JavaCalorious** [comment]
Never mind, I'm just dumb, I tried your solution again and it worked. The problem was that the core had to be placed within line of sight between the stabilizers and injector.
