### ISSUE TITLE
Unable to use "back" button with information tablet

### ISSUE THREAD

**Issue by Lordstarwolf** [brandon3055/Draconic-Evolution#122]
Using GUI size "auto" at any resolution crops the information tablet GUI so I am unable to click the "back" button.  Under small, medium and large it is legible and clickable. Using most recent version of DE (1.0.1c)

Previous versions of DE I have played didn't have icons on the tablet.  Unsure which version this started with. 

Problem persists in both vanilla and with resource packs. 

I play with a triple monitor setup, bezel-corrected 6060x1200.  After having changed it to 1920x1200 figuring it was a cropping issue, I found that a maximized window on a single monitor still crops the bottom of the GUI, but "auto" works when you run minecraft in a non-maximized window. 

Workaround is obviously to either not use "auto" GUI scale, not play in maximized window or fullscreen, or just change the GUI scale while reading the tablet.  A minor annoyance, but great mod.

**Comment by Ianaver** [comment]
sadly I believe the whole cropping thing may just be a minecraft bug but I could be wrong...

**Comment by brandon3055** [comment]
Yea that is something that has been reported meany times I just made the gui to big but it would require a bug rewrite to fix. Another option is to just press backspace to go to the previous page (i added that when this issue was first brought to my attention)
