### ISSUE TITLE
Issues with DE I/O Crystals

### ISSUE THREAD

**Issue by jonkke8** [brandon3055/Draconic-Evolution#1223]
Okay, so i was just trying to input energy into my tier 8 energy storage, but my first problem was, the flux points (different mod) limited the capacity to 2.147bRF, then i looked up a solution in github (here) i got my tier 5 core to input power with the Draconic I/O Crystals, so i tried the same with the tier 8, nothing. No power being put out whatsoever (picture of my setup: https://imgur.com/a/xsIw0lh)
And yes, i have the energy pylons the right way and i have linked the I/O Crystals.

## Base information
* Minecraft version:1.10.2
* Mod version:1.10.2-2.1.6.263-universal
* Minecraft Forge version:forge-12.18.3.2477
* Mod Pack: Sky Factory 3

**Comment by brandon3055** [comment]
Flux networks is a broken mod. There isnt much i can do about that especially in 1.10
