### ISSUE TITLE
No DE Reactor information in the DE Info Tablet

### ISSUE THREAD

**Issue by TheMightyMcGrew** [brandon3055/Draconic-Evolution#1224]
Not a crash report, just pointing out there isnt any information on any of the draconic reactor parts or anything about setup/running them. More info on the 1.12+ reactors would be greatly appreciated as its not in the draconic evolution information tablet
Forge Version: 14.23.5.2768
Modpack: Stoneblock (Twitch Launcher)

**Comment by brandon3055** [comment]
The current documentation built into DE is now obsolete. 
DE is now documented with Project Intelligence https://minecraft.curseforge.com/projects/project-intelligence
You say your using the twitch launcher? If that is the, and assuming stone block isnt using ancient versions of my mods you should be able to add PI via the launcher (its not needed server side)
