### ISSUE TITLE
Mob Grinder Witchery Crash

### ISSUE THREAD

**Issue by Solidflip** [brandon3055/Draconic-Evolution#123]
I believe im having the same issue as https://github.com/brandon3055/Draconic-Evolution/issues/72. When the Mob Grinder kills a mob from witchery it kicks everyone on the server. 

Log from Server: http://pastebin.com/tiaNPYRp ( no full crash log as the server doesnt crash, just kicks everyone. Using DE version 1.0.1C and Witchery v0.24.1 from Resonant Rise 3 V3.2.7.1 )

For the client side all it says is the exception on channel Witchery.

I saw there was a way to blacklist mobs on the spawner, is there some way to do that for the grinder as well? Also im not sure which mob it is, its a mob that spawns from Cursed Earth though.

**Comment by brandon3055** [comment]
This has been reported before but so far i have not been able to track down the problem. I suggest you bring this up on the Witchery bug tracker aswell.

**Comment by Solidflip** [comment]
Will do, ill go to their IRC as they dont have a github. Ill try to see which mob it is in the meantime
