### ISSUE TITLE
Flux Capacitor Not Charging Baubles

### ISSUE THREAD

**Issue by gudenau** [brandon3055/Draconic-Evolution#1230]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.18.329
* Minecraft Forge version: 14.23.5.2796
* Mod Pack: N/A

## Crash report
N/A

When the Draconic Flux Capacitor is set to charge everything it does charge items in the bauble slots. (Specifically AR glasses from openglasses) In order to get the flux capacitor to charge baubles it needs to be placed into a bauble slot, not anywhere inside the player's inventory.

![2018-12-30_16 11 32](https://user-images.githubusercontent.com/5642329/50551401-b8907200-0c4d-11e9-8012-3908c098eca7.png)

**Comment by FoxMcloud5655** [comment]
Actually, even if it's set to "Inactive", it still charges baubles when equipped into a baubles slot.  I'm going to see if I can take a crack at this and implement it properly.
