### ISSUE TITLE
[Suggestion] Something to factor in defence reductions to lower the damage inflicted on the shield, or an Upgrade.

### ISSUE THREAD

**Issue by Z-Tunic** [brandon3055/Draconic-Evolution#1232]
The Energy Shield takes the full damage rather that being reduced by Protection, Resistance, etc. While the Draconic Armor can get enchantments or other forms of defense such as Angel of Veneagece's Shield of Faith which would block 50% of the damage taken...  the shield apparently doesn't account for those and just takes it head-on.

I was wondering if either an upgrade of some sorts that can be applied to the armor can help with cutting down the damage taken for the shield... or let Protection, Resistance & other defense factors take into account for the damage being reduced and then apply it to the Energy Shield.

If the upgrade were to be decided... I dunno how much of a reduction the tiers would use, maybe just like Protection Enchantments but for the Energy Shield? Protection goes to IV  normally so that would be... 4 tiers? As for the name... I suppose 'Shield Strength' which by the /de_upgrade command it would be 'shieldStr', I think.

**Comment by brandon3055** [comment]
The shield is designed to be your first line of defence. It is an energy barrier that exists separate from your physical armor. It would not make any sense for the enchantments designed for physical armor to also apply to your energy shield. These enchants will still have an effect bu buffing the underlying armor when the shield fails. I could add separate upgrades for the shield but in my opinion its already plenty powerful enough. Not to mention i will be re writing the shield soon anyway.

**Comment by Z-Tunic** [comment]
That's true... it's quite powerful enough as it is. Just figure some kind of upgrade to offset the damage taken to the shield if using mods that scales up the damage taken from damage sources.

Then again... one could altar the configs for that, such as Last Stand's Energy Requirement. Although I don't see an entry for Shield Capacity.
