### ISSUE TITLE
Ender IO Soul Vials captures Guardian Crystal

### ISSUE THREAD

**Issue by ibox233** [brandon3055/Draconic-Evolution#1233]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.18.329
* Minecraft Forge version:2796

## Crash report
The game didn't crash.
When you are holding Soul Vials, you can capture it by right-clicking on the crystal.

**Comment by brandon3055** [comment]
This looks like very poor design on the part of EnderIO. By default the soul vial can not pick up boss mobs (which the crystals are) but there is a flag that enables this in EIO. However from what i can tell this isn't actually tied to a config that the user has control over. So ether something in your pack is triggering EIO to enable boss pickup or another mod is messing with EIO to enable it. I suggest you open an issue on the EIO github. In the mean time i will see what i can do from my end.
