### ISSUE TITLE
Draconic Sword and Staff of Power cannot be enchanted with CoFH enchants

### ISSUE THREAD

**Issue by LuciusV** [brandon3055/Draconic-Evolution#1237]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-14.23.5.2768
* Minecraft Forge version: 1.12.2-14.23.5.2768

Cannot Apply Holding, Vorpal, Insight, Leech etc enchants to Draconic weapons
They can be applied to tools from another mods (EnderIO) so seems bot to be CoFH problem

**Comment by brandon3055** [comment]
This is because the CoFH enchants are hard-coded to only work with tools that are directly based on the vanilla tools which mine are not. CoFH does provide a way around this issue so i will implement that if i get time.
