### ISSUE TITLE
Missing dig AOE keybind

### ISSUE THREAD

**Issue by NeonWizard** [brandon3055/Draconic-Evolution#1238]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.17.321
* Minecraft Forge version: 14.23.5.2768
* Mod Pack: FTB Revelation

What happened to the keybinds for dig AOE? Last I remembered you could `shift+rclick` to modify your tool's dig AOE, but it no longer works. It's very frustrating to have to open the tool config GUI every time I want to change my dig size. Was it changed to a different keybind, or just removed altogether?

**Comment by brandon3055** [comment]
That was removed in the 1.10 update in favour of the config profile system.

**Comment by brandon3055** [comment]
I am adding an optional (unbound by default) keybinding that will allow you to cycle tool and weapon AOE.
