### ISSUE TITLE
Awakened energy core crafting issue

### ISSUE THREAD

**Issue by N0od1es93** [brandon3055/Draconic-Evolution#1239]
## Base information
* Minecraft version:1.12.2
* Mod version:1.12.2
* Minecraft Forge version:14.23.5.2796
* Mod Pack: (if applicable)Stone block 2

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by brandon3055** [comment]
So what exactly is it doing? Does it just not show up as a valid recipe in the gui? Please post a screenshot of your crafting setup and the crafting core gui.

**Comment by N0od1es93** [comment]
![minecraft 1 12 2 1_20_2019 1_58_56 am](https://user-images.githubusercontent.com/46856152/51436232-62fd2300-1c57-11e9-8653-f6ab594f3add.jpg)
![minecraft 1 12 2 1_20_2019 1_58_59 am](https://user-images.githubusercontent.com/46856152/51436233-642e5000-1c57-11e9-98f6-1ed26e6e32aa.jpg)
![minecraft 1 12 2 1_20_2019 1_59_06 am](https://user-images.githubusercontent.com/46856152/51436234-6690aa00-1c57-11e9-848c-2283430e43ca.jpg)

**Comment by brandon3055** [comment]
I'm guessing its just some weird lighting in that mage but those dont look like awakened draconium ingots in the injectors. They look more like copper to me.

But assuming thats not the case the only thing i can think of would be a config miss-match between client and server. If you are on a server check if this recipe works in a single player creative world.

**Comment by N0od1es93** [comment]
PLaying sp but I made a creative world and set it up exactly the, only difference being what is supplying power, it worked on the creative world, not sure if they may be connected but i know when I finished the Wyvern cap quest it auto completed the Draconic cap quest, I never got one from a loot crate or as a quest reward.

**Comment by N0od1es93** [comment]
Seems that the crafting recipe doesn’t work in the awakened injectors, I had to make a set of wyvern to make the awakened cores

**Comment by brandon3055** [comment]
If i had to guess its probably more likely one or more of the injectors was in some sort of invalid state that would have been fixed by breaking and replacing them with the wyvern injectors. Awakened injectors should be able to craft lower tier recipes no problem...
