### ISSUE TITLE
The Info Tab is missing Documentation.

### ISSUE THREAD

**Issue by herbert164** [brandon3055/Draconic-Evolution#1241]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.18.329
* Minecraft Forge version:14.23.5.2796
* Mod Pack: (if applicable) FTB Stone Block 2

The info tab operates,but when the gui is loaded i get an error message in a gui where the help info should be.

**Comment by brandon3055** [comment]
https://github.com/brandon3055/ProjectIntelligence/issues/1
