### ISSUE TITLE
[Suggestion] Wyvern/Draconic Armor + Tools & Weapons Fully Upgraded/Charged in the jei?

### ISSUE THREAD

**Issue by ReiDaTecnologia** [brandon3055/Draconic-Evolution#1242]
It will be soo useful for testing purposes in the creative!
Btw thx for this awesome mod 😄 
and for allowing me to become God-like xD

**Comment by brandon3055** [comment]
I may get around to adding this at some point. In case you missed it there is already a `/de_upgrade` command that allows you to set the upgrades on the item your holding. It also lets you set the upgrade level higher that would normally be possible.

**Comment by ReiDaTecnologia** [comment]
> I may get around to adding this at some point. In case you missed it there is already a `/de_upgrade` command that allows you to set the upgrades on the item your holding. It also lets you set the upgrade level higher that would normally be possible.

Nice! thx for info! <3
And i agree with you totally, this is a "low-priority" suggestion (You can even put this label if you want) and you can do this whenever you feel good to add it :D
Letting this issue open as a "Remember me/Todo" suggestion.
