### ISSUE TITLE
Mob soul removed upon breaking

### ISSUE THREAD

**Issue by dovaezburn** [brandon3055/Draconic-Evolution#1244]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.18.329
* Minecraft Forge version: 14.23.5.2796
* Mod Pack: FTB Revelation

Wither Skeleton souls disappear from spawner when broken, the spawner keeps the core but the soul is no longer inside, not a visual bug as even a chaotic core will not spawn anything.

**Comment by Famous5000** [comment]
INTENTIONAL. Mob souls will be destroyed upon breaking any spawner, as per the in-game guide: "The soul is too fragile to be retrieved again after use" or something like that. Not a bug.

**Comment by dovaezburn** [comment]
Ah, how is it that in the past I was able to retrieve the spawner back with the soul in servers? Is there a config option for that?

**Comment by brandon3055** [comment]
There has never been a way to break a spawner without loosing the soul. Though some mods may allow you to move it without breaking it.
It also keeps its initial entity type when you convert a regular spawner.
