### ISSUE TITLE
Failed to download the PI mod manifest error

### ISSUE THREAD

**Issue by Meepish** [brandon3055/Draconic-Evolution#1253]
## Base information
* Minecraft version:1.12.2
* Mod version:3.18.329
* Minecraft Forge version:14.23.5.2796
* Mod Pack: stoneblock2 v. 1.2

No crash, mod is unable to download manifest.json from pi.brandon3055.com making the information tablet unusable, sorry if this has already been reported.
![javaw_2019-02-08_09-10-45](https://user-images.githubusercontent.com/46975089/52486871-e7213700-2b81-11e9-8d53-f3d8aa0696a8.png)

**Comment by brandon3055** [comment]
This has been reported. This is caused by outdated java. For now the solution is to ether update java or install VanillaFix https://minecraft.curseforge.com/projects/vanillafix
I should have a fix in PI soon.

**Comment by NillerMedDild** [comment]
I'm getting reports that this is an issue once again, with `ProjectIntelligence-1.12.2-1.0.9.28-universal`, same error - Reported by two people here: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1314
