### ISSUE TITLE
Astral sorcery mob prevention ritual and stabilized spawner

### ISSUE THREAD

**Issue by blackdragonIV** [brandon3055/Draconic-Evolution#1254]
## Base information
* Minecraft version: 1.12
* Mod version: 2.3.18.392
* Minecraft Forge version: 14.23.5.2807
* Mod Pack: (if applicable): custom made

stabilized spawners seem to get affected by the astral sorcery ritual that prevents mob spawning, any chance to make them ignore the effect of the ritual?.

**Comment by brandon3055** [comment]
This is kinda intended. The base tier spawner is designed to act exactly like a vanilla spawner. Upgrading to wyvern removes the need for a player nearby and upgrading to awakened forces it to ignore all spawn requirements.

**Comment by blackdragonIV** [comment]
i went ahead and double checked my setup just to confirm, the spawners were all chaotic tier and they still refused to spawn mobs while the ritual was active.

**Comment by brandon3055** [comment]
Oh yay... Sounds like Astral sorcery is ignoring the "I'm a spawner" flag and blocking my spawner... Does it also block vanilla spawners? I'm curious because i do things a little different to vanilla.

**Comment by blackdragonIV** [comment]
it does not appear to, i tested it with vanilla mob spawner of blaze
