### ISSUE TITLE
Fusion crafting draconic tools does not carry over enchantments from wyvern tools

### ISSUE THREAD

**Issue by kiroma** [brandon3055/Draconic-Evolution#1255]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.18.329
* Minecraft Forge version: 14.23.5.2811

Upgrades are carried over though.

**Comment by andyad8865** [comment]
i can confirm that happens on the server i run as well
Minecraft version: 1.12.2
Mod version: 2.3.20.333
Minecraft Forge version: 14.23.5.2781
