### ISSUE TITLE
Dislocators dont work anymore

### ISSUE THREAD

**Issue by LuciusV** [brandon3055/Draconic-Evolution#1259]
## Base information
* Minecraft version: 1.12.2 
* Mod version: Draconic-Evolution-1.12.2-2.3.19.330-universal.jar
* Minecraft Forge version: 1.12.2-forge1.12.2-14.23.5.2768
[crash-2019-02-13_01.48.01-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/2857031/crash-2019-02-13_01.48.01-server.txt)

## Crash report
After update all dislocators stop working with exception shown in attacted crash log. (Both simple, fusioncrafted and player-binded)

**Comment by FoxMcloud5655** [comment]
Draconic Evolution requires Forge build 2811, the latest at the current time.  You're running 2768.

**Comment by FoxMcloud5655** [comment]
Hmm...  Though I am also getting the same error, just without hard crashing.  Looks like it IS broken.

**Comment by FoxMcloud5655** [comment]
Found the issue.

Line 96 of file "DESoundHandler.java" contains the line;
```
Object o = ReflectionHelper.getPrivateValue(SoundEvent.class, soundIn, "field_187506_b", "soundName");

```
It needs to be changed (because of depreciation) to:
```
Object o = ObfuscationReflectionHelper.getPrivateValue(SoundEvent.class, soundIn, "field_187506_b");
```

**Comment by LuciusV** [comment]
> After changing to the newly supported method, Dislocators work as expected again.

When I do this change building fails for me with
`:processApiResources NO-SOURCE
:apiClasses
:sourceMainJava
:compileJava
/home/lucius/local/mcmods/Draconic-Evolution/build/sources/main/java/com/brandon3055/draconicevolution/lib/DESoundHandler.java:95: error: cannot find symbol
        Object o = ObfuscationReflectionHelper.getPrivateValue(SoundEvent.class, soundIn, "field_187506_b");
                   ^
  symbol:   variable ObfuscationReflectionHelper
  location: class DESoundHandler
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

**Comment by brandon3055** [comment]
Thanks for bringing this up. Will be fixed in the next release.

**Comment by FoxMcloud5655** [comment]
I guess you have your answer now :P

**Comment by Architect46** [comment]
Sorry for my bad english. 
I got the same crash. Writin on mobile now. There was aout sound error something like that. Where is this “DESoundHandler.java” file and how can i change it... i Put on to dislocater and when i jump or wither jump the portal it is crashing..

**Comment by FoxMcloud5655** [comment]
This issue is closed.  There's no need to edit the source code, as there's already a new build available; go download it on Twitch or CurseForge!
