### ISSUE TITLE
Crash while using DE Portal

### ISSUE THREAD

**Issue by warriorplatypus** [brandon3055/Draconic-Evolution#1269]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.19-330
* Minecraft Forge version: 14.23.5.2808
* Mod Pack: (if applicable) Stoneblock 2

## Crash report
```
Crash occurred while attempting to use a draconic evolution portal. 

https://paste.dimdev.org/ubobubemuq.mccrash

```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by brandon3055** [comment]
You need to update to the latest version of DE
