### ISSUE TITLE
Bad texture sizing in manual, must be root of two for compatability

### ISSUE THREAD

**Issue by Ianaver** [brandon3055/Draconic-Evolution#127]
There are a few textures such as that in the title of the manual (in the the first image, its fixed after I edited it manually) where the textures are a strange size. Some people have older GPUs where the buffer cannot "skew" or use some other related render method to fit the texture correctly (sadly this current PC that I plan to replace is one of them with the problem). Since Skyboy explains this better here is a comment from another issue that explains this: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/86#issuecomment-114513489

I only included a few examples and will find more later, I will also submit a pull request once I resize the  pictures/icons properly (some I may not be able to resize such as the gifs but I will try anyhow)

Edit: I don't know where the gifs and images are located in the mod files, however I did resize the index page

Edit 2: I guess I don't know enough about github as I thought I did (I won't do a pull request) so here is the file on dropbox with the fixed index texture: https://www.dropbox.com/sh/t7nquh7c2wliook/AAA2cmsfPSeRbelO2B47_5FKa?dl=0

![2015-07-24_14 27 37](https://cloud.githubusercontent.com/assets/8153290/8885272/f0de1a72-3212-11e5-9dde-4e2992d60e0d.png)
![2015-07-24_14 31 07](https://cloud.githubusercontent.com/assets/8153290/8885304/339d6890-3213-11e5-9c05-1177b13ca19e.png)
![2015-07-24_14 33 47](https://cloud.githubusercontent.com/assets/8153290/8885307/35ec69ac-3213-11e5-9728-6e02163c6d05.png)

**Comment by Ianaver** [comment]
I guess I don't know enough about github as I thought I did so here is the file on dropbox with the fixed index texture: https://www.dropbox.com/s/gatzw915bozgyi1/debanner.png?dl=0

I will add more to this comment as I find more of the images and fix them

**Comment by brandon3055** [comment]
Thanks for pointing that out that is something that i did not know about. I have a lot of changes i need to make to the manual which i plan to do all at once before ether the next update or the one after that. I will add this to the list. 
BTW the reason you cant find the images is they are not in the jar. They are actually downloaded the first time the game starts and stored in config\draconicevolution\resources\assets\draconicevolution\textures\gui\manualimages
But dont worry about resizing them for me now that i know what i need to do i can do it easily.

**Comment by Ianaver** [comment]
ok :)

**Comment by Ianaver** [comment]
@brandon3055 can you give me the folder with the resized images once you are finished? I really want  the images since for all I know the next release may not come for another month.

**Comment by Ianaver** [comment]
Also, one last thing, when will this be fixed? The snapshots so far (v1.0.2 snapshot 3) don't have the fix :( I had to manually change the front page again...

**Comment by Ianaver** [comment]
@brandon3055 can you possibly fix the texture sizing in the next snapshot? or is there so much stuff to do still to the tablet that you are going to hold off on that until the first major release?

**Comment by Ianaver** [comment]
@brandon3055 Can you please re-open this until it is fixed? Its still not fixed in the snapshots....
