### ISSUE TITLE
Cages around Crystal Don't Spawn On Chaos Islands When adjusting their height

### ISSUE THREAD

**Issue by Vyraal1** [brandon3055/Draconic-Evolution#1272]
## Base information
* Minecraft version:1.12.2
* Mod version: 2.3.20.333
* Minecraft Forge version: 2795
* Mod Pack: FTB Interactions (in closed beta, can provide pack files upon request)

Copy of configs used to alter the height: https://gist.github.com/Vyraal1/3998f3ef353b402ec3838fece4cf0d3f

**Comment by FoxMcloud5655** [comment]
Have you considered updated Forge to 2811?  That's what DE is officially built on.  I'll take a look and see if I can fix this, but no guarantees; I've never done world gen before.

**Comment by FoxMcloud5655** [comment]
Found the issue.  DE sets the maximum y offset limit of the Chaos Island to 150, which in turn generates features above the world height limit, up to 266.
You'll need to set the new offset to 140, and (for brandon3055) the limit in the settings needs to be reduced down to 140 in line 87 of DEConfig.java:
```
@ModConfigProperty.MinMax(min = "-50", max = "140")
```
Happy modpack curating!

**Comment by Vyraal1** [comment]
Thanks Fox!

**Comment by FoxMcloud5655** [comment]
Of course!  Happy to help.
