### ISSUE TITLE
Draconic evolution 3d armor models not appearing.

### ISSUE THREAD

**Issue by TheDiamondMan3** [brandon3055/Draconic-Evolution#1273]
## Base information
* Minecraft version:1.12.2
* Mod version:1.12.2-2.3.18.329-universal
* Minecraft Forge version:14.23.5.2797
* Mod Pack: my personal pack

## Crash report
```
no report, just some problem.
```
i really dont want this to be insta-closed but it seems like i am the only one with this problem, for some reason or no reason, when i wear wyvern or draconic armor, the 3d models are just the 2d ones, i have checked if the 3d models are on or off and they are set to on. the models only load if i make npcs from customnpcs wear it or any other npc. this problem is very bothersome, and i literally cant find anything about this. do i have to see if there is an update or what do i do??? i really would like some help with this.

**Comment by FoxMcloud5655** [comment]
I'll say 4 things:
1. Your mod version is 2 versions out of date.
2. Your Forge version needs to be 2811 or higher.
3. Your problem is most likely because of your modpack.  It's not exactly regulated by multiple people, so issues between mods happen sometimes.
4. Post a log if you can't post a crash report.  It helps, trust me.

**Comment by TheDiamondMan3** [comment]
Okay, thank you, i will try and use your advice.

**Comment by TheDiamondMan3** [comment]
i think i have set it to false, sorry for the long reply, but it still
doesnt work.

otrd., 2019. g. 9. apr., plkst. 16:55 — lietotājs brandon3055 (<
notifications@github.com>) rakstīja:

**Comment by FoxMcloud5655** [comment]
Why don't you try listing all of your mods?  That way, someone else can test it and see if a mod is conflicting.

**Comment by TheDiamondMan3** [comment]
oh yeah, i could do that.


pirmd., 2019. g. 15. apr., plkst. 16:26 — lietotājs FoxMcloud5655 (<
notifications@github.com>) rakstīja:

**Comment by brandon3055** [comment]
No reply from OP

**Comment by evantam123** [comment]
i have this problem too
