### ISSUE TITLE
Dislocator not working

### ISSUE THREAD

**Issue by baiamc** [brandon3055/Draconic-Evolution#1274]
## Base information
* Minecraft version: 1.12
* Mod version: 1.12.2-2.3.19.330
* Minecraft Forge version: 8.0.99.99
* Mod Pack: Stoneblock 2

## Crash report

https://paste.dimdev.org/xicotahiku.mccrash

**Comment by FoxMcloud5655** [comment]
Update DE.  This is a duplicate issue.

**Comment by baiamc** [comment]
Did a quick search but didn't find that issue.  Closing.
