### ISSUE TITLE
Inverted Inventory in Tool & Armor Config GUI

### ISSUE THREAD

**Issue by FoxMcloud5655** [brandon3055/Draconic-Evolution#1278]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.20.337; 2.3.20.333
* Minecraft Forge version: 14.23.5.2811
* Mod Pack: N/A

## Bug Report
Just a minor visual bug.  The player's inventory is inverted when viewing it from the Tool & Armor Config GUI.

Minecraft Inventory GUI
![2019-03-04_08 58 10](https://user-images.githubusercontent.com/4934172/53742930-59262c80-3e5f-11e9-9b88-c43bf1df55c8.png)
Tool & Armor Config GUI
![2019-03-04_08 58 36](https://user-images.githubusercontent.com/4934172/53742934-5aeff000-3e5f-11e9-8ae0-8f15d5f4df81.png)

**Comment by FoxMcloud5655** [comment]
I've taken to making issues like you've requested.  If you're interested in the fix, I've made it here:
https://github.com/FoxMcloud5655/Draconic-Evolution/tree/configguifix

**Comment by GreatOrator** [comment]
Not exactly sure what you are pointing out.  If you mean the colors and positions, that is deliberate

**Comment by ate0ate** [comment]
I think he means the order of the pieces of armor, excluding the hotbar. If you compare the two images the order of the armor pieces is reversed from top to bottom in the three rows of inventory above the hotbar. I guess it boils down to the top row of inventory displaying on the bottom row in the Tool and Armor Config GUI and bottom row displaying on the top of the GUI. Its upside down. The real inventory order is as shown in the top image, Helmet/chestplate/leggings where the GUI shows it as leggings/chestplate/helmet. Would be easier to notice with a full inventory.

**Comment by FoxMcloud5655** [comment]
Yes; sorry, clarification was needed.  The main inventory (minus the hotbar) is rendered upside down because of the order that "player.inventory.mainInventory" exposes items.
