### ISSUE TITLE
Text skewed in info tablet

### ISSUE THREAD

**Issue by Ianaver** [brandon3055/Draconic-Evolution#128]
![2015-07-24_14 27 37](https://cloud.githubusercontent.com/assets/8153290/8885329/61da1c8a-3213-11e5-8763-0a9b4dbc9b95.png)

**Comment by brandon3055** [comment]
That is temporary text so i did not bother to check its alignment on different gui scales/monitor resolutions.

**Comment by Ianaver** [comment]
lol ok
