### ISSUE TITLE
Infusion Custom Crafting

### ISSUE THREAD

**Issue by AllInMods** [brandon3055/Draconic-Evolution#1281]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.20.333
* Minecraft Forge version: 14.23.5.2810
* Mod Pack: (if applicable) TechVival

Hi Brandon, i would like to know if there is a documentation of a guide on how to create, edit and remove infusion crafting.

Thank you very much.

**Comment by FoxMcloud5655** [comment]
There's a pretty good in-depth tutorial located in your "config/brandon3055" folder named "Custom Fusion Recipe Info.txt".
