### ISSUE TITLE
/give with upgraded items

### ISSUE THREAD

**Issue by talpidae** [brandon3055/Draconic-Evolution#1282]
Hello!

Is there a way to /give an upgraded Item to a player? 
Like Draconic Boots with Wyvern Tier.

Thanks a lot!

**Comment by FoxMcloud5655** [comment]
It is possible with a command like the following:
`/give @p draconicevolution:draconic_boots 1 0 {DEUpgrades:{rfCap:1b}}`
I would advise against this method, however, as there seems to be an issue (with whatever my setup is, granted) with it giving 2 of the item to the player; one in the inventory and one dropped in front of them.

**Comment by brandon3055** [comment]
you can use this to upgrade the item in your hand
`/de_upgrade <upgradeName> <level>`
Use tab complete to figure out the upgrade names.

**Comment by talpidae** [comment]
Awesome!

If someone else need this too, here is a full list of commands:
Basic

**Comment by talpidae** [comment]
Awesome!

If someone else need this too, here is a full list of commands:
Basic Tier = <1>
Wyvern Tier = <2>
Draconic Tier = <3>
Chaotic Tier = <4>

Example: `/de_upgrade shieldCap 4` while holding Draconic Helmet will upgrade Shield Capacity to Chaotic Tier.

**Draconic Helm:**
`/de_upgrade rfCap <level>`
`/de_upgrade shieldCap <level>`
`/de_upgrade shieldRec <level>`

**Draconic Chestplate:**
`/de_upgrade rfCap <level>`
`/de_upgrade shieldCap <level>`
`/de_upgrade shieldRec <level>`

**Draconic Leggings:**
`/de_upgrade rfCap <level>`
`/de_upgrade moveSpeed <level>`
`/de_upgrade shieldCap <level>`
`/de_upgrade shieldRec <level>`

**Draconic Boots:**
`/de_upgrade rfCap <level>`
`/de_upgrade jumpBoost <level>`
`/de_upgrade shieldCap <level>`
`/de_upgrade shieldRec <level>`

**Draconic Axe:**
`/de_upgrade rfCap <level>`
`/de_upgrade digSpeed <level>`
`/de_upgrade digAOE <level>`

**Draconic Bow:**
`/de_upgrade rfCap <level>`
`/de_upgrade arrowDmg <level>`
`/de_upgrade arrowSpeed <level>`
`/de_upgrade drawSpeed <level>`

**Draconic Hoe:**
`/de_upgrade rfCap <level>`
`/de_upgrade digAOE <level>`

**Draconic Pickaxe:**
`/de_upgrade rfCap <level>`
`/de_upgrade digSpeed <level>`
`/de_upgrade digAOE <level>`

**Draconic Shovel:**
`/de_upgrade rfCap <level>`
`/de_upgrade digSpeed <level>`
`/de_upgrade digAOE <level>`

**Draconic Staff of Power:**
`/de_upgrade rfCap <level>`
`/de_upgrade digSpeed <level>`
`/de_upgrade digAOE <level>`
`/de_upgrade attackDmg <level>`
`/de_upgrade attackAOE <level>`

**Draconic Sword:**
`/de_upgrade rfCap <level>`
`/de_upgrade attackDmg <level>`
`/de_upgrade attackAOE <level>`
