### ISSUE TITLE
Interdiction torches effect Wyvern arrows.

### ISSUE THREAD

**Issue by Wgairborne** [brandon3055/Draconic-Evolution#1283]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.18.329
* Minecraft Forge version: 14.23.5.2796
* Mod Pack: FTB Sky Adventures 

There is no crash report, the title says directly, shooting Wyvern arrows at Interdiction torches (which make mobs avoid the torch) from ProjectE will cause them to act like a mob and swerve away.

**Comment by gigabit101** [comment]
Can you try this with vanilla arrows? I believe you will have the same result.

**Comment by Wgairborne** [comment]
Yep, standard bow and arrow has the same result.

**Comment by FoxMcloud5655** [comment]
This is not a problem on Draconic Evolution's end.  Double check to make sure that the config option for Interdiction Torches is only targeting hostile mobs (instead of all living entities).
