### ISSUE TITLE
Info tablet (PI) doesn't show Reactor details?

### ISSUE THREAD

**Issue by Wgairborne** [brandon3055/Draconic-Evolution#1284]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.18.329
* Minecraft Forge version: 14.23.5.2796
* Mod Pack: FTB Sky Adventures

## Crash report
No crash report, just seems like there is supposed to be information on the reactor according to a closed issue. A little picky, but just wondering if it could be an issue.

**Comment by FoxMcloud5655** [comment]
You're kinda 4 builds out of date.  Try seeing if your problem persists after updating.

**Comment by Wgairborne** [comment]
ouch, thanks for letting me know. Hopefully it shouldn't fry my modpack

**Comment by Wgairborne** [comment]
just updated it and looked through, still not seeing anything about it?

**Comment by brandon3055** [comment]
Does your pack have Project Intelligence? If not then what you are seeing is the old outdated documentation that does not include the reactor.

**Comment by ShadowofCubes** [comment]
Just to confirm: His modpack (FTB Sky Adventures) doesn't have Project Intelligence installed. (Maybe add a dependency to Draconic Evolution so that it gets downloaded automatically?)

**Comment by Wgairborne** [comment]
that's odd? I thought it was installed since it showed a GUI named Project Intelligence. That should fix it, thanks for the help.

**Comment by brandon3055** [comment]
It is listed as an optional dep. I dont want to make it a required dep because its in no way required.
You also get this when you first open the info tablet after launch... 
![](https://ss.brandon3055.com/65f00)

**Comment by brandon3055** [comment]
Oh... That reminds me... I totally forgot to remove the old documentation in the last update... Well maybe next time xD
