### ISSUE TITLE
3x3 mining wont put items in to inventory

### ISSUE THREAD

**Issue by Voutsjude** [brandon3055/Draconic-Evolution#1287]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.20.333
* Minecraft Forge version: 14.23.5.2821
* Mod Pack: (if applicable) direwolf20 1.12

dunno if its server or client/mod side issue so posted it here. also junk filter wont work if the blocks wont teleport to your inventory

**Comment by brandon3055** [comment]
I cant seem to reproduce this issue... I will have to load up DW20 to test it when i get time.

**Comment by FoxMcloud5655** [comment]
Just loaded up DW20 with all of your settings as stated above; everything works as intended.

Would you care to upload a video reproducing this issue?  It might have to do with an item in your inventory that interferes/blocks/is incompatible with AOE mining, though I'd have no clue what item could do that.

**Comment by brandon3055** [comment]
Also do the items drop as actual items or as loot balls?

**Comment by FoxMcloud5655** [comment]
Not sure about OP's situation, but in my testing, it was actual items.  Not until I get to a higher AOE (more items dropped) do I get the loot balls.
