### ISSUE TITLE
I Don't have all Draconic Evolution Items,Blocks and more

### ISSUE THREAD

**Issue by Cixiid** [brandon3055/Draconic-Evolution#1288]
Hello, 

I have a problem i don't have all things Draconic Evolution add 

![Capture](https://user-images.githubusercontent.com/49339619/55668908-a3d90100-5870-11e9-93d2-fd97d3247a0f.PNG)

![Capture1](https://user-images.githubusercontent.com/49339619/55668911-a9364b80-5870-11e9-91f8-9b801073abf0.PNG)

![Capture2](https://user-images.githubusercontent.com/49339619/55668912-ae939600-5870-11e9-8f60-7b5c1320c40b.PNG)

![Capture3](https://user-images.githubusercontent.com/49339619/55668918-b5baa400-5870-11e9-81fc-dfa752cf86c9.PNG)

Please can someone help me because i don't have all blocks and i can't do reactor or other things

Thanks you

**Comment by FoxMcloud5655** [comment]
First things first, have you checked the config to make sure that all blocks and items are enabled?

**Comment by Cixiid** [comment]
No i don't check the config

**Comment by Cixiid** [comment]
I checked and yes all block are enabled

**Comment by GreatOrator** [comment]
What version of DE is this (i.e. what version of minecraft are you playing)?what blocks/items do you think you are missing?

**Comment by Cixiid** [comment]
I'm playing minecraft 1.7.10,version of DE : 1.0.2 but he said their is an update for version 1.0.2 and for blocks : 
 Admin Dislocator 
 Advanced Entity Detector 
 Basic Fusion Crafting Injector 
 Celestial Manipulator 
 Chaotic Fusion Crafting Injector 
 Creative RF Source 
 Disenchanter 
 Dislocator Pedestal 
 Dislocator Receptacle 
 Draconic Fusion Crafting Injector 
 Energy Core 
 Energy Core Stabilizer 
 Energy Infuser 
 Energy Pylon 
 Entity Detector 
 Fusion Crafting Core 
 Generator 
 Mob Grinder 
 Potentiometer 
 Rain Sensor 
 Wyvern Fusion Crafting Injector
Awakened Draconium Block 
 Charged Draconium Block  

AND much more

**Comment by GreatOrator** [comment]
Most of those blocks were in later versions of DE, you might want to consider moving away from 1.7 and move on to 1.10 or 1.12 but I can see most all of those blocks you listed in your images.

The fusion crafting was introduced in 1.10
