### ISSUE TITLE
Energy Vortex Particle still lagging the game even after despawning of particles.

### ISSUE THREAD

**Issue by ShadowofCubes** [brandon3055/Draconic-Evolution#1289]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.20.333-universal
* Minecraft Forge version: forge-14.23.5.2781
* Mod Pack: (if applicable)

No Crash. But immense lag from "BC Particles" 
First of all, the energy vortex particles are kind of laggy. That wouldn't be a big problem since they aren't rendered very often. 
The issue is that they still lag even if they despawned: http://prntscr.com/n8he8n
Before "BC Particles" wasn't even shown: https://prnt.sc/n8hdcr
The only way to get rid of the lag is to restart the game. Even opening another world doesn't help
The lag remains in the world select screen: https://image.prntscr.com/image/fJm9lNLZTZqwFjml0IECbw.png
Steps to reproduce (Use the Shift+F3 function to see if it's rendered): 
-Summon an entitychaosenergyvortex
-experience lag
-wait for it to despawn
-still lagging
-leave world
-still lagging
-restart
-lag gone
I hope you can reproduce this bug.

**Comment by brandon3055** [comment]
Where are you spawning this entity? You realise this is the entity that "deletes" the chaos island. Spawning it anywhere but the end will destroy your tps as it tries to consume a sizeable chunk of your world. It also has lighting issues in the overworld which amplify the lag..

**Comment by ShadowofCubes** [comment]
I'll try to demonstrate what I mean:
Before/During the fight: http://prntscr.com/n9nuuv Some lag from BCParticles
After the fight/Before breaking the crystal: http://prntscr.com/n9nvjv
Breaking the crystal: http://prntscr.com/n9nvv5 Lag from BCParticles occurs, completly normal because they are rendered
After the explosion: http://prntscr.com/n9nwes The game is still lagging even if the explosion is over.
After leaving the world: http://prntscr.com/n9nx6c The BCParticle lag still occurs
Starting a new world: http://prntscr.com/n9ny9v
After restarting the lag is gone. I don't now why.
There is no diffrence where the explosion happened or if its naturally spawned or not.
