### ISSUE TITLE
[Suggestion] improve scroll sensitivity 

### ISSUE THREAD

**Issue by Ianaver** [brandon3055/Draconic-Evolution#129]
scroll sensitivity is really low and makes it a pain to scroll through the info in the tablet

**Comment by brandon3055** [comment]
I am going to add a scroll bar but if you just hold shift it will scroll faster.

**Comment by Ianaver** [comment]
thanks!

**Comment by Zaflis** [comment]
Could you increase the shift-scroll speed too, would be great. It still only goes up 1 line at the time with a scroll. It's what i'd expect basic rate to be, and maybe 3 lines with shift.
