### ISSUE TITLE
Advanced Disclocator Losing saved points.

### ISSUE THREAD

**Issue by xxakirhaxx** [brandon3055/Draconic-Evolution#1292]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.20.333
* Minecraft Forge version: 12.23.5.2781
* Mod Pack: (if applicable) Enigmatica 2 Expert

Not a crash report but a bug none the less.  I'm using the Advanced Dislocator, and I have enough end points to have to scroll at this point. If it matters I have just enough to start scrolling. If I delete the location that made my list scrollable it causes all of my saved points to be shifted up 1 and deletes my first saved point. If I remake the deleted point (this point can be anywhere, it just has to be a saved point) my saved points return to normal. I'm not sure if this description will help so I'll try to make it visual.

1: Point A
2: Point B
3: Point C
...
12: Point L
(Becomes scrollable)
13: Point M

Then I delete Point M. It becomes.

1: Point B
2: Point C
3: Point D
...
12: Point K

Then I add 13 back (with any point, doesn't have to be M, it'll be X). And it becomes.

1: Point A
2: Point B
3: Point C
...
12: Point L
(Becomes scrollable)
13: Point X

Hope this helps. Might be Enigmatica, the pack changes a lot, but it would be easy to test for you probably.

**Comment by brandon3055** [comment]
I cant seem to reproduce this issue.
![](https://ss.brandon3055.com/77f7c)
Are you playing on a server? If so can you check if the issue can be reproduced in singleplayer?

**Comment by xxakirhaxx** [comment]
I am doing this in a single player world. The gif goes a little too fast for me to see, but just to confirm: The labels (A-N in your gif) stay the same, as they should. The locations of each label shift when the 13th label is deleted (N). 

If that's not repeatable then it's something on my end, but the bug is still persisting, I'm just keeping the random spot I saved.
