### ISSUE TITLE
Game stops working and freezes when opening Draconic book.

### ISSUE THREAD

**Issue by Azzezima** [brandon3055/Draconic-Evolution#1293]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.21.342
* Minecraft Forge version: 14.23.5.2823

## Crash report
Because the game doesn't actually crash but rather stops working here's the log file:
https://pastebin.com/s6VEzLC7

**Comment by brandon3055** [comment]
This looks like an issue with the old builtin documentation. The simple solution would be to install Project Intelligence. https://minecraft.curseforge.com/projects/project-intelligence
PI is the replacement for the old documentation which will be removed in the next update.

**Comment by Azzezima** [comment]
Will do.
Thanks for the quick reply, appreciate it.
