### ISSUE TITLE
Draconium Ore does not spawn in the End

### ISSUE THREAD

**Issue by Goddfrey** [brandon3055/Draconic-Evolution#1295]
## Base information
* Minecraft version: 1.7.10
* Mod version:  1.0.2h
* Minecraft Forge version:  10.13.4.1614
* Mod Pack: (if applicable)

I can't find it anywhere in the End, and also NEI does not show it spawning anywhere either. 

Config apparently does not disable it:

```
# Set to true to prevent draconium ore from spawning in the end
B:"Disable Ore Spawn (End)"=false
```

It's my private kitchen sink modpack assembled using twitch launcher, and I did not manually mess with worldgen in any way. It has ExtraBiomes XL if that matters.

**Comment by FoxMcloud5655** [comment]
This is outdated.  1.12.2 is the only version of MineCraft that Draconic Evolution is being updated for currently.

**Comment by Goddfrey** [comment]
> 
> 
> This is outdated. 1.12.2 is the only version of MineCraft that Draconic Evolution is being updated for currently.

I dont expect this v to be updated but if you or someone else could help me to debug it by offering hints on where to begin, I'd greatly appreciate it. Chances are it's not a bug in the code itself but rather a problem somewhere in the configs or mod interactions, because I've played with this version a lot and it's the first time I encounter this problem. If you've seen something like this before maybe you could help me. Are there any mods known for disabling Draconium Ore in the end? Or just ore generation in The End in general? Maybe you know any reasonably easy way to find it out from some kind of log files? I could read them if I knew where and what to look for at least approximately. Maybe people reported something like this before and you remember most common causes for this? And if not well nevermind then just close the issue and sorry for taking your time :)

**Comment by Goddfrey** [comment]
I managed to find the issue by re-adding every mod one by one, the problem was Galacticraft's addon called Space Research disabling all the ore spawn in The End, including but not limited to Draconium. I hope this at least helps if someone else has similar problem.
