### ISSUE TITLE
Dislocator and Advanced Dislocator Crash

### ISSUE THREAD

**Issue by Taccio33** [brandon3055/Draconic-Evolution#1298]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.19.330
* Minecraft Forge version:14.23.5.2768
* Mod Pack: (if applicable)

## Crash report
```
https://paste.dimdev.org/qudicegoca.mccrash
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by brandon3055** [comment]
You need to update DE. This is fixed in the latest version.
