### ISSUE TITLE
[SUGGESTION] Automatic junk compressor

### ISSUE THREAD

**Issue by Nova001Sol** [brandon3055/Draconic-Evolution#13]
This one comes from my dislike of both cobble and wasting, and it involves a new option for the Staff of Power. I'd like to see the option to autocraft or auto-compress dropped items into a storage variant. This means redstone to blocks, lapis to blocks, cobble (so much cobble) to compressed cobble if the player has Extra Utilities, etc. This vastly decreases the loss caused by the void junk option without drowning you in waste like without void junk. Note that this is meant to be a sort of in-between, a way to have the best features of both with and without void junk, not a replacement for either.

**Comment by brandon3055** [comment]
Thats not a bad idea. But if i do something like that it will probably be in the form of a seperate item.

**Comment by Nova001Sol** [comment]
I'll change the title of the post then.
