### ISSUE TITLE
Bows have no charge/durrability

### ISSUE THREAD

**Issue by Ianaver** [brandon3055/Draconic-Evolution#130]
The bows don't accept nor use charge when arrows are shot, is this intentional? The documentation on the tablet says nothing nor shows the weapon using RF

**Comment by brandon3055** [comment]
The bows do not currently use RF or have durability. This is because i plan to rewrite a lot of their code at some point and i will implement RF usage in them then.

**Comment by Ianaver** [comment]
ok
