### ISSUE TITLE
Draconium core t8

### ISSUE THREAD

**Issue by weird272** [brandon3055/Draconic-Evolution#1300]
so i accidentely deleted the preset for this but im just wondering how do i supply power to my t8 draconium core ive put energy pylons down and everything and supplied power to them and its still not getting power im on minecraft version 1.12 and forge version 2.6.1.81

**Comment by FoxMcloud5655** [comment]
Note: These potential solutions are provided without knowing your mod version, your particular setup, your modpack, or anything else.

Sounds like you're in creative mode.  In this case, make sure the you have summoned and placed some glass on top of the pylons.  Also, make sure that you also have right-clicked the glass (once it transforms) to be set to input energy, not output.

**Comment by brandon3055** [comment]
You can also find documentation in PI if you have it installed
https://minecraft.curseforge.com/projects/project-intelligence
