### ISSUE TITLE
Chaos crystal dropping instead of chaos shards

### ISSUE THREAD

**Issue by adstheorganic** [brandon3055/Draconic-Evolution#1301]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.21.342
* Minecraft Forge version: 14.23.5.2820
* Mod Pack: The Culmination
##Avaritia version: 1.12.2-3.3.0.33

##Issue

When breaking the chaos crystal with the world breaker from avaritia without defeating the chaos guardian in its default pickaxe mode it gave me an un-textured chaos crystal instead of the 20 shards it was supposed to, breaking it in its hammer form give the crystals correctly though. 
We're speculating that breaking the crystal before killing the dragon is where the issue lies and that the hammer mode on the world breaker is just doing something clever that gets around this.

**Comment by brandon3055** [comment]
I have no idea what the "world breaker" is doing but its doing it wrong. It should not be possible for any tool (if its coded correctly) to break the chaos crystal without first defeating the chaos guardian. It also sounds like its completely disregarding the block's drops and and just giving you the raw item block.
