### ISSUE TITLE
Possible to make T8 Core store more energy?

### ISSUE THREAD

**Issue by Testo0987** [brandon3055/Draconic-Evolution#1302]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.20.333
* Minecraft Forge version: v2815
* Mod Pack: (if applicable) N/A

If you do not provide these your issue will be insta-closed.
So i know this might sound a bit crazy, but is it POSSIBLE to make the T8 energy core storage more than Long.MAX_VALUE? I'm not a coder or anything, it seems possible. Maybe have it store something like: Double.MAX_VALUE energy? I'm just curious.
Thanks.

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!<Not a crash report>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.<N/A>
Failing that please give me your entire minecraft log from the session when the crash occurred.<N/A>

**Comment by FoxMcloud5655** [comment]
Theoretically, yes.  One possible way is to have 2 energy values.  One keeps track of the actual energy stored, and the other one will keep track of how many multiples of energy it is storing.

An example of this: Let's pretend that int.MAX_VALUE is 1000.  Once you have more than 1000 energy attempting to be stored, the first value would hold the remainder of the energy while the second value would read as a 1.

Practically, NO.  How would you even display such a large number to something like a ComputerCraft computer?  Also, why do you even need more than a quintilian of RF?!

**Comment by Testo0987** [comment]
This probably would not be a viable idea.
