### ISSUE TITLE
UnsupportedOperationException from capacitors

### ISSUE THREAD

**Issue by runescapejon** [brandon3055/Draconic-Evolution#1303]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.21.342
* Minecraft Forge version: 1.12.2-14.23.5.2836
* Mod Pack: (if applicable)
Also using versions 
BrandonsCore-1.12.2-2.4.10.198
Draconic-Evolution-1.12.2-2.3.21.342
## Crash report
```
https://pastebin.com/raw/MGVgiG6i
```
Please note assuming the issue is a crash something like this

```Error: java.lang.UnsupportedOperationException```
How to reproduce this crash
1) get a capacitor
2) Shift- right click it then crash
Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
Duplicate of #1294.

**Comment by runescapejon** [comment]
oops, going to close this thank you
