### ISSUE TITLE
energy core not accepting any type of power ( did not crash)

### ISSUE THREAD

**Issue by sallie123** [brandon3055/Draconic-Evolution#1305]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.20
* Minecraft Forge version:14.23.5.2808
* Mod Pack: stoneblock 2

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
Assuming this was just a mistake on your part?

**Comment by sallie123** [comment]
Yes i have figured out that it was the glass placement
