### ISSUE TITLE
[Feature Request] CFG setting for fusion craft speed

### ISSUE THREAD

**Issue by Pultex** [brandon3055/Draconic-Evolution#1306]
Looking in the settings I did not see any way to speed up the crafting system.

You can not increase energy that go into the crafting system or accelerate the crafting itself.

I placed an item that gave the blocks EACH 2 billion RF and it went as slow as if it had 1000 rf.

so 12 x 2 billion fr could not speed up the charging system.

**Comment by sallie123** [comment]
ProjectE's watch of flowing time and a dark matter pedestal or the time in a bottle will speed up both the crafting speed and infusion time

**Comment by brandon3055** [comment]
To increase speed you need to use higher tier crafting injectors.
