### ISSUE TITLE
linkedlist prob

### ISSUE THREAD

**Issue by Diekrahe1138** [brandon3055/Draconic-Evolution#1307]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.21.342
* Minecraft Forge version:
* Mod Pack: (if applicable)
![TFP5V47DN8A 3%Z36DBS}OR](https://user-images.githubusercontent.com/50409626/57376940-cb0a5180-71d3-11e9-99c4-1b271db9249a.png)

No.it's not a error.but it use half of performance.
linkedlist search speed is too slow.Could you fix it?

**Comment by brandon3055** [comment]
I can optimise that. But how many chunks do you have loaded? I suspect you would need an insane number of chunks to be loaded for that to be an issue...

**Comment by Diekrahe1138** [comment]
No.Only 500-700chunks.But even though my server don't have anyone.It still likes this. (50% isn't not so high.It always 80%.)
