### ISSUE TITLE
Draconic reactor won't heat up

### ISSUE THREAD

**Issue by purringcat248** [brandon3055/Draconic-Evolution#1309]
StoneBlock 2
Minecraft 1.12.2
Draconic Evolution 2.3.21.342
Minecraft Forge 14.23.5.2836

In StoneBlock 2, I was trying to build a draconic reactor. I connected it to my Extreme Reactors reactor, and then outputted to my tier 8 draconic energy storage. The stabilizers and injector are a sufficient distance from the core. There are 8 awakened blocks in the input to the reactor. The animation plays. However, the containment field strength gets to 50% and then stops, and it won't heat up from 20° C. Does anyone have any assistance?

**Comment by brandon3055** [comment]
How fast are you feeding it power? The startup process has 3 phases. First it charges the shield to 50%, then in charges the saturation to 50% and then finally it heats up the core and once the core reaches i think 2000c (don't quote me on that) you can start it. Its worth noting that each phase requires significantly more power than the last. So just check if the saturation is increasing. If it is then you just need to wait or feed it more power.

**Comment by purringcat248** [comment]
Saturation is steadily increasing. I just have a dimensional transceiver from EnderIO feeding power directly into the energy injector from my Extreme Reactors reactor.

**Comment by gigabit101** [comment]
If it's slowly increasing you are more than likely not feeding it power fast enough
