### ISSUE TITLE
Chaotic Core

### ISSUE THREAD

**Issue by aigiz010** [brandon3055/Draconic-Evolution#1310]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.21.242
* Minecraft Forge version: 14.23.5.2836
* Mod Pack: (if applicable) OGW 1.0.7

https://prnt.sc/nmjx3w

https://prnt.sc/nmjxh4

I can't craft Chaotic Fusion Crafting Injector without Chaotic Core!
and
I can't craft Chaotic Core without Chaotic Fusion Crafting Injector!

**Comment by FoxMcloud5655** [comment]
See that text in the first screenshot at the top that says, "Tier: Draconic"?  That doesn't require a Chaotic Fusion Crafter.

**Comment by FoxMcloud5655** [comment]
This is not an issue with Draconic Evolution.  Someone changed the recipe for the Chaotic Core.

![image](https://user-images.githubusercontent.com/4934172/57483206-f0e33500-726b-11e9-95f9-ae49215be37c.png)

This is the original recipe.

**Comment by aigiz010** [comment]
How to change crafting with craft Tweaker mod?

**Comment by FoxMcloud5655** [comment]
Go read up on it here: https://crafttweaker.readthedocs.io/en/latest/#Getting_Started/

Since you're using a modpack, I suggest closing this issue and opening a new one with the modpack author instead so they are aware of this issue and can fix it for everyone.

**Comment by aigiz010** [comment]
Thanks, I found the author's mistake in the configs.
