### ISSUE TITLE
Mining tools in AoE mode drop no xp orbs

### ISSUE THREAD

**Issue by avlad171** [brandon3055/Draconic-Evolution#1313]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.21.342
* Minecraft Forge version: 14.23.5.2824
* Mod Pack: custom

Ok so I decided to use an automated fortune III block breaking setup with a pickaxe of the wyvern. At first it was single block and it all worked as intended. When I upgraded the pick and set it to 3x3 mode, ores started giving loot cores and no xp. I disabled the loot cores in the config file but there are still no xp orbs spawning.
![Untitled](https://user-images.githubusercontent.com/42695636/57776316-d3104700-7727-11e9-823b-dbfa24d1d2bc.png)
 
![Untitled](https://user-images.githubusercontent.com/42695636/57776204-875d9d80-7727-11e9-9e59-468d4c9f47bd.png)

And here it is in 1x1 mode doing what it is supposed to do.
![image](https://user-images.githubusercontent.com/42695636/57776461-369a7480-7728-11e9-92f6-5b473c931d2d.png)

**Comment by gigabit101** [comment]
AOE mod does not drop the XP orbs the XP is given directly to the player.
