### ISSUE TITLE
Server randomly crashing after adding draconic evloution 

### ISSUE THREAD

**Issue by Schale94** [brandon3055/Draconic-Evolution#1314]
## After adding draconic evolution and brandons core, server works normally but it have random crasher, no matter what im doing sometimes im crafting, some time just flying around.
* Minecraft version: 1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.22.343-universal.jar
* Minecraft Forge version: ForgeMultipart-1.12.2-2.6.1.81-universal.jar
* Mod Pack: FTB Ultimate reloaded 1.6.0
## Crash report
https://pastebin.com/9t7hBgu9

**Comment by gigabit101** [comment]
Nothing in this stack trace to point DE, This log just shows that your server is taking to long to tick and causing Minecraft watchdog to stop the server.
