### ISSUE TITLE
Draconic Capacitor crash when Baubles not installed

### ISSUE THREAD

**Issue by runescapejon** [brandon3055/Draconic-Evolution#1315]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.22.343
* Minecraft Forge version: 14.23.5.2836
* Mod Pack: (if applicable)

## Crash report
```
https://pastebin.com/raw/ARm1YvcF
```
Please note assuming the issue is a crash something like this

```java.lang.UnsupportedOperationException```

Basically same issue from https://github.com/brandon3055/Draconic-Evolution/issues/1294 Draconic Capacitor crash when Baubles not installed, you had close the github issue. But the problem is still there on the latest version (1.12.2-2.3.22.343) and commit figure make a proper issue about it.
Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by qq512065439** [comment]
I have the same issue too.
