### ISSUE TITLE
Sound crash with extra utils

### ISSUE THREAD

**Issue by Testo0987** [brandon3055/Draconic-Evolution#1318]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.22.343-universal
* Minecraft Forge version: v2815
* Mod Pack: (if applicable)

## Crash report
```
https://paste.dimdev.org/ejomehapez.mccrash
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by Testo0987** [comment]
I was just afking while my auto-fusion crafting system crashed. I have vanilla fix on, and i came back to that. It says that extra utilities and DE were the problem.

**Comment by FoxMcloud5655** [comment]
DE is using a standard way of playing a sound.  XU is the one crashing you, not DE.

**Comment by brandon3055** [comment]
Actually... this is partially my fault. playing sounds from the render thread which definitely is not standard but isn't really a problem... until another mod tries to iterate the active sound list which is a perfectly reasonable thing to do. I will fix this in the next release.
