### ISSUE TITLE
Crash when using shift click for NEI recipes

### ISSUE THREAD

**Issue by GreatOrator** [brandon3055/Draconic-Evolution#132]
When in the Draconic Chest interface, using shift click to make smart cables in the crafting interface caused a client crash.

http://pastebin.com/NpRXUCx6

This is using the experimental version of the mod

**Comment by ajay1770** [comment]
I'm getting the same thing, but not only in the Draconic Cheat. I used multiple crafting tables, still having the same crash. Also when pulling AE2 cables from EE3's transmutation tablet, I got the same crash. 

Using v1.0.1c

**Comment by Ianaver** [comment]
strange :/

**Comment by GreatOrator** [comment]
As of build rv3.alpha build 3 they fixed the issue, but brandon has put a work-around in DE to fix it for now as most modpacks don't use alpha version of mods
