### ISSUE TITLE
Placement of Draconic Crystals not working - found a way to legitimately get them in modpack.

### ISSUE THREAD

**Issue by c0ldk453** [brandon3055/Draconic-Evolution#1321]
## Base information
* Minecraft version: 1.12.2 Project Ozone 3 version 3.0.40
* Mod version: Draconic-Evolution-1.12.2-2.3.21.342-universal.jar
* Minecraft Forge version: 14.23.5.2836
* Mod Pack: Project Ozone 3

Process of Obtaining Draconic Crystals without creative or JEI hax: Using the Wand of Animation from Erebus, I was able to turn the object itself into an entity called an Animated Block, which I promptly captured using a Mob Imprisonment Tool from Industrial Foregoing. (Surprisingly it still set off the explosion sequence which lag-destroyed the server I was on.)  Using a mob duplicator from the same mod, I was able to duplicate the actual item itself.  Erebus animated blocks drop whatever block they are made from when killed, so guess what I got?

I know these can be dangerous items on their own, so it'd be nice if there was something to do with them or some special thing that happens when you place them.  Even if they just instantly split into shards when placed.  But I have a bunch of them now, and all they do is make chaos noises and disappear when I attempt to place them.  Being able to do something with them would enable me an already late-game method of mass-producing chaos shards without causing terrible server lag.

(Oh and on a separate note: those explosions really kill servers.  It'd be nice if you could turn off block destruction and just make it a damage nuke.)
![2019-05-25_16 53 17](https://user-images.githubusercontent.com/19635392/58375351-c6e96e00-7f0d-11e9-88bd-59a952a6f887.png)

**Comment by gigabit101** [comment]
These are not meant to be placed and should not be able to be gotten If the Modpack author has made a way of getting them this is a ModPack issue.

Note: There is already a config to disable block destruction
