### ISSUE TITLE
Guardian crystals instantly respawning preventing chaos guardian kill completely.

### ISSUE THREAD

**Issue by SirAron111** [brandon3055/Draconic-Evolution#1322]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.22.343-universal 
BrandonsCore-1.12.2-2.4.12.205-universal 
* Minecraft Forge version:14.23.5.2838
* Mod Pack: (Dimension Zero 7.9 Beta)

## Crash report
Its not a crash just a bug

BUG:
Guardian crystals instantly respawning preventing chaos guardian kill completely.

Ok here is the Problem With and without wussmode this option doesn’t seem to matter at all.
The Crystals protecting the Chaos guardian instantly revives once you move a bit too far away from them do I have to kill the guardian standing in the middle or what? Here is what I mean I fly to one end of the crystal circle and kill a crystal and then move along the circle killing every crystal I do that pretty fast even tested it with cages mined away to be faster. But the moment the crystals move out of render distance they instantly revive normally as far as I remember it takes some of these green balls to revive one of them. I even tested it by killing all crystals with a command than moving a bit away and the once that got unloaded got revived instantly once I moved back to them. This makes killing the chaos guardian completely impossible as he is always immune to damage.

My modpack is a hardcore pack I even set the guardian to have 10k hp since dmg can be boosted from many sources (you still need the draconic armor to survive his attacks but I also boosted the damage from his attacks x4 to make them more dangerous for players who have 200 hp) I tweaked the draconic shield recovery rate to make it more of a hit and run fight where the player can’t keep standing on the same spot tanking the balls. (to be true I wish I could make it so that the totally unbalanced instant revive of the armor would be disabled so the player has to work with the shield and never have it drop down to 0 or get killed and than just buff the shield a bit but that’s impossible) But in the end all that is totally unimportant if you are never able to damage the big guy at all. Also is it normally that all the yellow fireballs turn into Red following fireballs there is no hard limit for them at some point I had like over 1000 chasing after me.

Is there a way to fix this? I think it’s some mod messing with them but it only happens with the crystals no other mob has this problem. And I have no idea what could be the cause.

**Comment by SirAron111** [comment]
Here are zips with videos clips about 1 min long of the bugs 
http://www.mediafire.com/file/ltimjcn5o99flhh/Fireballs_turn_into_Energy_OP_Balls_to_many_red_balls.zip/file
http://www.mediafire.com/file/rz4p257o2c66794/Respawn_BUG_Video_2_min.zip/file

**Comment by FoxMcloud5655** [comment]
I like the fact that you think it's too OP!  It's why I believe in providing as many tweaks in the config file as possible.  In my own modpack, I did exactly the same, I just took it down instead of up.  I like small numbers :)  There is a way to disable the revive mechanic; change the Last Stand Energy Requirement in your config to Int.MAX_VALUE (2147483647).

Back to the issue, the last time I defeated a Chaos Guardian, I did not have this problem.  However, I did set my render distance to 32, as I like to see the entire battlefield during my fight (mainly so I can hit & run effectively).  Let me do some tests and see if I can figure out what's happening here.

**Comment by SirAron111** [comment]
Well I provided videos about 1 – min long sowing the bug. Hoping that will help a bit

I just uploaded the version of my modpack (7.9 Beta) in which I experienced the Bug First so others can download and test around with it. I don’t know if it happened before maybe one of the mods that updated since last time like COFcore etc or the new Forge version are messing with things. But I can’t find what’s causing it all I know is that not being able to kill the crystals means not being able to kill the guardian. I keep testing in case I find something just thought reporting it would mean a person who can actually code can have a look all I can do is mess with configs and up/downgrading the mod versions that exist.

I even joined the discord so I am easier to contact since I mostly respond there in less than a minute.

OH and as for the Int.MAX_VALUE (2147483647). Ye that makes it nearly impossible to provide enough energy for the last stand function but I was thinking of isn’t it possible to set it to -1 to disable it or something? It pretty buggy since it isn’t really preventing death more like instant revive and that drains hardcore hearts like crazy if the function would simply prevent the last 2 or so harts from vanishing that would be better but as it is it’s hard to balance.

And even if I set it high just taking multiply capacitors with you can make the fight super easy but I was trying to make the fight based on player skill dodging hit run killing the balls so they can’t hit you even if they have a super small hitbox and always spread out when one explodes which is kind of annoying  since you can’t set their speed etc) and not about how many capacitors can I fill up with my big reactor XD but as for this post this isn’t the main problem the crystal respawn is way worse.

**Comment by FoxMcloud5655** [comment]
I did everything that you did in your second video to attempt to reproduce this issue in vanilla DE; everything worked fine.

Code-wise, DE activates the live-saving event in CustomArmorHandler:
```java
public void onPlayerDeath(LivingDeathEvent event) {
```
It then checks if the player has more than 500 armor points, and if so, cancels the death event and sets the player to half vanilla HP:
```java
if (summery.protectionPoints > 500) {
   event.setCanceled(true);
   event.getEntityLiving().setHealth(10);
   return;
}
```
If not, then it checks for Draconic or higher tier armor:
```java
if (!summery.hasDraconic) {
   return;
}
```
If it finds Draconic, then it checks for the last stand energy requirement specified in the config and compares it to the armor's current total RF:
```java
if (totalCharge < ToolStats.LAST_STAND_ENERGY) {
   return;
}
```
Only if this goes through does it save you from death, and at the end, sets you to 1 HP:
```java
player.setHealth(1);
```
I hope that helps you understand the whole process!

**Comment by SirAron111** [comment]
Ok with further experimentation i found out at least one thing. It has to do with the crystals being loaded. Because if I set render distance from 8 to 24 so I can see the full island they don’t respawn unnaturally only if I go really far away (24+ far away) they start showing the same behavior and simply respawn all together. Could it be that they need to be loaded in order for them to know if they are defeated or alive??? And on loading them new they just think they are alive again. Do I need to fight the dragon with a chunk loader there or so going to test that next with my render on 8 again (have to keep in mind that no all players in a pack with 200+ mods can keep high render distance up).---yep after testing this with render on 8 and a chunk loader in the middle that loads them constantly they stay down until the green balls heal them normaly so I think this can be fixed by making them chunk load/spot load their location or making the chaos crystal achunkloader to keep the area loaded until you kill the dragon and break it…….. But what I totally can’t find out what mod is causing the chunks to unload instantly or I tried it with only draconic on render 8 and there it happened to but not always only if I stayed away for a bit longer.

**Comment by SirAron111** [comment]
as for the 500 armor and health checks well I do have scaling health mod installed but the most armor and health a player can get is around 300+ hp and 250+ armor with astral sorcery perks and literally every booster possible. But the bug with the crystals must have something to do with them getting unloaded like in the test I did above. (I don’t know if another mod is causing it all I can say is that it does happen in the beta version of my pack you can download it and test it maybe you can see what is happening with them there if something messes with things I have no idea) @FoxMcloud5655

**Comment by brandon3055** [comment]
If scaling health is modifying the guardian crystals that could be causing your issues because the guardian crystals use custom health handling.

**Comment by SirAron111** [comment]
nop i blacklisted the guardian and the crystals from any mod that messes with health as the guardian has its own hp setting i like to use the implemented configs for such cases 

            # Mobs listed here will never receive extra health, and will not become blights. There is also a separate blacklist for blights, if you still want the mob in question to have extra health. [default: ]
            S:Blacklist <
                draconicevolution:guardiancrystal
                draconicevolution:chaosguardian
                thebetweenlands:fortress_boss
                ebwizardry:zombie_minion
                ebwizardry:skeleton_minion
                ebwizardry:spirit_wolf
                ebwizardry:blaze_minion
                ebwizardry:ice_wraith
                ebwizardry:lightning_wraith
                ebwizardry:shadow_wraith
                ebwizardry:spider_minion
                ebwizardry:ice_giant
                ebwizardry:spirit_horse
                ebwizardry:phoenix
                ebwizardry:silverfish_minion
                ebwizardry:storm_elemental
                ebwizardry:wither_skeleton_minion
             >

as well as setting them to be ignored by the damage control by setting them to -1


    # The maximum health value for draconicevolution:chaosguardian. Negative values deactivate health modification for this entity. [range: -1.0 ~ 100000.0, default: 10000.0]
    S:"MaxHealth_draconicevolution:chaosguardian"=-1

    # The maximum health value for draconicevolution:guardiancrystal. Negative values deactivate health modification for this entity. [range: -1.0 ~ 100000.0, default: 50.0]
    S:"MaxHealth_draconicevolution:guardiancrystal"=-1

And I even tested it without these 2 mods as I to thought maybe they still do something but nop. It must be something to do with unloading the chunk they are In. since setting the render higher so now that I can see the island if I am far away it keeps them down. But not everyone has a super pc and can handle 32+ (default of my pack is 8 and that’s just around 2 or so to little so that they unload when you reach the other side of the crystal circle keeping it endless like in the clip I linked) render and servers mostly set it to some fix value. Best solution I found is placing a chunk loader in the middle to keep it loaded. That’s why I thought making the crystal into a chunk loader with the range of the crystals or making the crystals spot loader would fix it no matter what mod messes with them. And once the island explodes or the shard gets mined they stop chunk loading.
