### ISSUE TITLE
Generation Rate

### ISSUE THREAD

**Issue by MDMRA3b** [brandon3055/Draconic-Evolution#1325]
Hello, help to understand.
My Reactor doesn't Generate the RF that's listed in the gate.
Values jump.
Draconic-Evolution-1.7.10-1.0.2h

![2019-06-22_21 04 51](https://user-images.githubusercontent.com/42772642/59967355-6a3f9a00-9531-11e9-9c54-d44861ba229b.png)
![2019-06-22_21 04 54](https://user-images.githubusercontent.com/42772642/59967356-6a3f9a00-9531-11e9-93f5-75fbbcc9acf2.png)

**Comment by brandon3055** [comment]
It may take a while for the generation rate to stabilise.
