### ISSUE TITLE
error C6013

### ISSUE THREAD

**Issue by Tolans** [brandon3055/Draconic-Evolution#1326]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.22.343
* Minecraft Forge version: 14.23.5.2838
* Mod Pack: -

## Crash report
[crash-2019-06-26_04.40.39-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/3329667/crash-2019-06-26_04.40.39-client.txt)

**Comment by FoxMcloud5655** [comment]
Would you mind describing how you came to produce this crash?  Is this a repeatable crash?

**Comment by Tolans** [comment]
> Would you mind describing how you came to produce this crash? Is this a repeatable crash?

This happens when turning pages in the JEI (13-14 page with my list of modifications), or in the inventory of the creative mode.
First there is a "stop local server", then the game is closed and an error is displayed.
Have not tried to repeat in survival, but I think it will be the same.

**Comment by FoxMcloud5655** [comment]
Alright.  I'll see if I can reproduce this later today.

**Comment by Tolans** [comment]
> Alright. I'll see if I can reproduce this later today.

Okay.

**Comment by FoxMcloud5655** [comment]
Couldn't reproduce this...  It may be a mod conflict.  Mind sending a list of mods?

**Comment by Tolans** [comment]
> Couldn't reproduce this... It may be a mod conflict. Mind sending a list of mods?

The attached file has the entire list of mods, and their versions.

**Comment by FoxMcloud5655** [comment]
I was hoping for something like a "modlist.html" (if using Curse/Twitch) for ease of installing, but I can go with that.  If I get time today, I'll give it a test.

**Comment by Tolans** [comment]
Removed all mods except OptiFine - still mod crashes.
And this is when you go to the tab blocks "Draconic Evolution" (with the tab "tools" all right) in creative mode or in the JEI. It seems that drawing some object closes the game.

**Comment by Tolans** [comment]
Reinstalled the game, and without mods at all (except for the necessary dependencies for Draconic Evolution) the same crash. Judging by the magazine, the problem is in "draconicevolution: energy_crystal".
I do not know what to do. I would like to play with this mod..

**Comment by Tolans** [comment]
Found information about this error. It is connected with a video card.
Here is more information:
1) https://github.com/falltergeist/falltergeist/issues/566
2) https://www.gamedev.net/forums/topic/520607-error-c6013-only-arrays-of-texcoords-may-be-indexed-in-this-profile--and-only-wit/

As I understand it, in the code of this mod some kind of shader is used, which some video cards, including mine, do not support.
I hope the developer of the modification can fix it.

**Comment by FoxMcloud5655** [comment]
That might explain why I could never reproduce the crash today.

**Comment by brandon3055** [comment]
Try disabling shaders in DE's config.

**Comment by Tolans** [comment]
> Try disabling shaders in DE's config.

Great, it helped! Thanks. =)
I do not know what I am losing at the same time, but the main thing is that now it does not crash and can be passed.

If someone else has this: Mods Settings> Draconic Evolution> Config> Client Settings> useShaders - "false".

**Comment by brandon3055** [comment]
Yea... Unfortunately some older hardware just does not support shaders. Everything still works the same without shaders they are just a lot less fancy and the core stabiliser renderes are a little bit broken.
[https://youtu.be/yHwNpmvQ3lE](https://youtu.be/yHwNpmvQ3lE)
