### ISSUE TITLE
How do I actually access the inventory of the Draconic Staff of Power?

### ISSUE THREAD

**Issue by ExplosiveGamer0** [brandon3055/Draconic-Evolution#1327]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.22.343 (2.3.22)
* Minecraft Forge version: 14.23.5.2769
* Mod Pack: (if applicable)

So I would actually like to know if my game is bugged or not as I cannot see the inventory button of the Draconic Staff of Power. Has it been removed or not? I would like to be able to take my Enchantments off freely when ever I am exploring and just replace them with what is needed.

**Comment by FoxMcloud5655** [comment]
That was removed quite a while ago.  You need to use the Disenchanter to remove the enchantments.  If you'd like to temporarily disable them instead, you may do so through the "Tool & Armor Config GUI" button.

**Comment by ExplosiveGamer0** [comment]
> 
> 
> That was removed quite a while ago. You need to use the Disenchanter to remove the enchantments. If you'd like to temporarily disable them instead, you may do so through the "Tool & Armor Config GUI" button.

Ah okay thank you for the information
