### ISSUE TITLE
Minecraft server constantly crashing

### ISSUE THREAD

**Issue by Alexxkill03** [brandon3055/Draconic-Evolution#1329]
## Base information
* Minecraft version: 1.10.2
* Mod version: Draconic-Evolution-1.10.2-2.1.5.262-universal.jar
* Minecraft Forge version: forge-1.10.2-12.18.3.2511.jar

## Crash report

https://pastebin.com/DaqyhDbL

## FML server Lastest logs

[fml-server-latest.log](https://github.com/brandon3055/Draconic-Evolution/files/3334762/fml-server-latest.log)

**Comment by Alexxkill03** [comment]
Hello, i'm trying to open a little server with 4gb of ram (to be sure that there is no problem) with my friends but at least when I tried to launch it, i always get this crash. I tried many such as downgrade the version of draconic evolution, brandons core or even ccl but i always get the same crash. Can someone help me please ?

**Comment by brandon3055** [comment]
What java install are you using. Im not familiar with OpenJ9
```
Java VM Version: Eclipse OpenJ9 VM
```
Perhaps try a standard java 8 install? Other than that i have no idea why this could be happening...

**Comment by Alexxkill03** [comment]
Thank you, I didn't notice that I installed the wrong version of Java. I'm totally dumb. Thank you for your help ! Have a good day !
