### ISSUE TITLE
Advanced Player Detector is not nearly as unlimited as the docs imply.

### ISSUE THREAD

**Issue by shadow7412** [brandon3055/Draconic-Evolution#133]
According to the wiki's I read, this block should have an (up to) unlimited range. I was going to use it to turn off a bunch of equipment at my base, but at a range of 100m. I can't get it set beyond 20, which completely defaults the purpose in my case :(

http://www.tolkiencraft.com/draconic-evolution/ (blocks, advanced player detector)
http://ftbwiki.org/Draconic_Evolution

So, are the docs wrong? Or is there something I have to do to it to get it to kick off?

If it helps, I'm currently using FTBInfinity 1.7 (v1.8.2) running Minecraft Version 1.7.10

**Comment by brandon3055** [comment]
Ok so im not sure why it says that... The max range of the advanced detector has only ever been 20 blocks. But now that you mention it i think i will consider increasing it.
