### ISSUE TITLE
Cant disable tweaked recipe for end crystals

### ISSUE THREAD

**Issue by ImVipox** [brandon3055/Draconic-Evolution#1331]
## Base information
* Minecraft version:1.12.
* Mod version: 2.3.13.306
* Minecraft Forge version: 14.23.2.2611
* Mod Pack: spacecraft(galacticraft)

Even if i change the expensive end crystal recipe to false it still makes it expensive.
If for some reason the cheap recipe is true, ive tried that too, it doesnt work. 
Edit: maybe you should now, that by now i only tried changing the config in the server files, not in my modpack files.

**Comment by brandon3055** [comment]
This setting needs to be changed both server and client side.
