### ISSUE TITLE
Draconic Axe Right Click Crash

### ISSUE THREAD

**Issue by NillerMedDild** [brandon3055/Draconic-Evolution#1333]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.21.342-universal
* Minecraft Forge version: 1.12.2-14.23.5.2836
* Mod Pack: (if applicable) Enigmatica 2

## Crash report
```
https://pastebin.com/KWmDbJWR
```

The game crashes when using the Draconic Axe right click harvest ability.

**Comment by brandon3055** [comment]
Looks like a null stack issue. Whatever you are trying to harvest is dropping an item entity with a null item stack. That breaks one of the fundamental rules of modding 1.12. An item stack can **NEVER** be null. Only empty. I will add a check for this to the next release of BrandonsCore but i really shouldn't have to. I suggest you try to figure out what mod is causing this and yell at them for me.

**Comment by NillerMedDild** [comment]
The culprit seems to be Twilight Forest :)

**Comment by NillerMedDild** [comment]
Scratch that, it does not happen with only DE / TW + dependencies, so I'm not sure what causes it.
