### ISSUE TITLE
Bug: Chaos explosion/vortex destroys indestructible blocks like bedrock and graves

### ISSUE THREAD

**Issue by SirAron111** [brandon3055/Draconic-Evolution#1335]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.23.345-universal 
* Minecraft Forge version:14.23.5.2838
* Mod Pack: Dimension Zero (but also if only this mod is installed)

Draconic evolution chaos explosion vortex destroys even bedrock and graves like corailtombstone graves.

I understand that the explosion should be devastating but at least keep graves and bedrock intact. For safety reasons.

**Comment by brandon3055** [comment]
This isn't a bug the crustal is designed to destroy absolutely everything within its blast radius. This is part of the danger of the fight. If your not prepared when you break the crystal you have the potential to loose everything you have with you including the chaos shards you just fought so hard to acquire. 

This is also why i put so much work into making it absolutely impossible to move the chaos crystal.

**Comment by SirAron111** [comment]
MM ok I just thought it was a bug. I used the explosion vortex as part of the final quest in my Questbook it’s intended to blow up the facility at the end after the player gets killed by the big bad guy. Well than I guess the player needs to be fast enough to grab his grave or he will lose all he worked so hard for even his drac armor etc (if he didn’t soul bind it). Was hoping that once all blows up only the grave remains but during testing the underground facility blow right trough grave and bedrock XD

**Comment by Corail31** [comment]
@Brandon it's a little disrespectful for others mods... or at least allow some compatibilities in the api for it... you don't know, or do you think all blocks should be destructible?
