### ISSUE TITLE
[Enhancement] Chaos upgrades

### ISSUE THREAD

**Issue by Nethet** [brandon3055/Draconic-Evolution#1336]
I'm in End Game stade and i wanna perfection, but i realized that there aren't chaotic upgrades for every thing (just for the capacitor). When do you add other chaotic upgrades ? (soon please)

I spend 3 hours to farm all ressources, and now I don't know what to do with them.
By the way: you do a great job

**Comment by FoxMcloud5655** [comment]
This has been asked multiple times.  There will be no Chaotic upgrades until the next version of DE.  If you really want full upgrades, however, let me self promo and look for a mod called Draconic Additions.
