### ISSUE TITLE
Draconic Evolution not taking energy in from other mods

### ISSUE THREAD

**Issue by quinti00** [brandon3055/Draconic-Evolution#1337]
Minecraft version: 1.12.2
Mod version: 1.12.2-2.3.20.333
Minecraft Forge version: 14.23.5.2821
Mod Pack: FTB Presents Direwolf20 1.12

DE isn't recieving energy from any other mod from the pack, I've used the different cables but it just wont pass into the fusion crafting injectors. I've used Ender IO, Thermal Expansion and IC2 and they connect to the blocks but they don't input the energy.

**Comment by FoxMcloud5655** [comment]
Does DE's Crystal Network still function?  Also, try updating to 1.12.2-2.3.22.343.
