### ISSUE TITLE
Custom fusion recipe dont work

### ISSUE THREAD

**Issue by jxdelta** [brandon3055/Draconic-Evolution#1338]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.21.342-universal
* Minecraft Forge version: 14.23.5.2838
* Mod Pack: my own

I try to write recipe using the custominfusionrecipe.txt but its not work. Why?

https://pastebin.com/7u6sM2Cd

**Comment by FoxMcloud5655** [comment]
Your JSON is invalid.  You can paste your file in a parser online or use your choice of IDE to help you form valid JSON.
