### ISSUE TITLE
draconic evolution 1.12.2

### ISSUE THREAD

**Issue by lecrusade** [brandon3055/Draconic-Evolution#1342]
hello I come to ask you why there is no cryo-stabilized fluxduct in 1.12.2 and if then there will be soon (PS: if there is already cryo-stabilized fluxduct in 1.12.2 send me the versions because in the version that I installed is the last there is none and if possible the link) thank you ah yes and I am French and I use google translation so if my English is wobbly if you have why ;)

**Comment by FoxMcloud5655** [comment]
Cryo Stabilized Fluxduct is not a part of any version of Draconic Evolution.  This item is part of Thermal Dynamics.

**Comment by brandon3055** [comment]
Yea sorry you have the wrong mod. But as far as i know all version of Thermal Dynamics for 1.12 have cryo fluxducts

**Comment by lecrusade** [comment]
ok so with thermal dinamic I could do the draconic reactor?

**Comment by FoxMcloud5655** [comment]
You'll have to clarify what you mean by that last question.  You can make and use the reactor with and without Thermal Dynamics and it will work.

**Comment by lecrusade** [comment]
okay thanks i'm going next will blow up my draconic reactor ;)
