### ISSUE TITLE
Issue with Custom Infusion NBT

### ISSUE THREAD

**Issue by Focamacho** [brandon3055/Draconic-Evolution#1343]
I'm trying to add a Custom Infusion Recipe using a Thaumcraft Essentia Phial as ingredient, but It didn't work.

Here is my json:
![image](https://user-images.githubusercontent.com/48870573/61596409-9f471700-abd9-11e9-843e-7c242e7cc2a9.png)

Result:
![image](https://user-images.githubusercontent.com/48870573/61596415-ac640600-abd9-11e9-8764-14c3c372ae91.png)

I tried it too:
`"thaumcraft:phial,1,1,{Aspects:[0:{amount:10,key:"desiderium"}]}"`
and:
`"thaumcraft:phial,1,1,{Aspects: [{amount: 10, key: "desiderium"}]}"`

but...
![image](https://user-images.githubusercontent.com/48870573/61596416-af5ef680-abd9-11e9-9f8f-bf5bc6b1b772.png)

**Comment by brandon3055** [comment]
All quotes within the string need to be escaped with backslash. 
e.g 
this `"thaumcraft:phial,1,1,{Aspects:[0:{amount:10,key:"desiderium"}]}"`
Should be this: `"thaumcraft:phial,1,1,{Aspects:[0:{amount:10,key:\"desiderium\"}]}"`

**Comment by Focamacho** [comment]
Same problem. JSON:
![image](https://user-images.githubusercontent.com/48870573/61607832-dee82000-ac26-11e9-8330-471a9be3c057.png)
Result:
![image](https://user-images.githubusercontent.com/48870573/61607843-e8718800-ac26-11e9-9e5d-608a2df0b89f.png)
Phial /ct hand:
![image](https://user-images.githubusercontent.com/48870573/61607853-fa532b00-ac26-11e9-8d51-87a0b78a174f.png)

**Comment by brandon3055** [comment]
Ok with the correct item in your hand run this command and show me the output
```/bcore_util nbt```

**Comment by Focamacho** [comment]
![image](https://user-images.githubusercontent.com/48870573/61651884-2f926400-ac8d-11e9-9b68-664ed5be5b55.png)

**Comment by brandon3055** [comment]
Sorry i didn't get back to you. The correct tag is as follows.
`"thaumcraft:phial,1,1,{Aspects:[{amount:10,key:\"desiderium\"}]}"`

**Comment by Focamacho** [comment]
Oh sorry, I forgot to answer. Everything works fine using `thaumcraft:phial,1,1,{Aspects:[{amount:10,key:\"desiderium\"}]}`
But it means /bcore_util nbt is giving the wrong nbt for this item.

Thanks for helping-me! :)

**Comment by FoxMcloud5655** [comment]
Good to know.  Was wondering if this worked myself, though I have yet to try.
