### ISSUE TITLE
Reactor output lowers to bellow shield input

### ISSUE THREAD

**Issue by Thdoctor4D** [brandon3055/Draconic-Evolution#1346]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.22.343-universal
* Minecraft Forge version:forge1.12.2-14.23.5.2838

The draconic reactor works until, at some point the generation rate lowers to below field input. No mater what I do this always happens. The generation rate always end up a bit below the field input. Usually 50000 to 20000 rf/t.
![2019-07-25_16 59 45](https://user-images.githubusercontent.com/53316744/61911683-d2e9b000-aefd-11e9-8947-a6d44072bad0.png)
![2019-07-25_16 51 23](https://user-images.githubusercontent.com/53316744/61911685-d2e9b000-aefd-11e9-8203-c1ae5cd9a81a.png)
![2019-07-25_16 51 27](https://user-images.githubusercontent.com/53316744/61911686-d2e9b000-aefd-11e9-91d5-c8cbb62f15b8.png)
![2019-07-25_16 51 34](https://user-images.githubusercontent.com/53316744/61911687-d2e9b000-aefd-11e9-9dd3-6ca6ca7aa4af.png)
![2019-07-25_16 51 40](https://user-images.githubusercontent.com/53316744/61911688-d3824680-aefd-11e9-9583-6c976e698e16.png)
![2019-07-25_16 51 43](https://user-images.githubusercontent.com/53316744/61911689-d3824680-aefd-11e9-850c-c7609b984ee2.png)
![2019-07-25_16 51 50](https://user-images.githubusercontent.com/53316744/61911691-d41add00-aefd-11e9-8537-0e25e0d2fb82.png)
![2019-07-25_16 51 59](https://user-images.githubusercontent.com/53316744/61911692-d41add00-aefd-11e9-85d8-6a6ed0b9f5fd.png)
![2019-07-25_16 52 03](https://user-images.githubusercontent.com/53316744/61911693-d54c0a00-aefd-11e9-820b-ac1096851243.png)
![2019-07-25_16 52 07](https://user-images.githubusercontent.com/53316744/61911694-d67d3700-aefd-11e9-97a8-23190997dff0.png)
![2019-07-25_16 52 11](https://user-images.githubusercontent.com/53316744/61911696-d67d3700-aefd-11e9-8bae-fac2d6c2c0e2.png)
![2019-07-25_16 52 19](https://user-images.githubusercontent.com/53316744/61911698-d67d3700-aefd-11e9-99d2-fa7b5b89df6c.png)
![2019-07-25_16 53 03](https://user-images.githubusercontent.com/53316744/61911699-d7ae6400-aefd-11e9-9945-b209eb43a713.png)
![2019-07-25_16 53 12](https://user-images.githubusercontent.com/53316744/61911700-d846fa80-aefd-11e9-80fb-30d184e78539.png)
![2019-07-25_16 53 16](https://user-images.githubusercontent.com/53316744/61911702-d8df9100-aefd-11e9-8c28-c382042e7a15.png)
![2019-07-25_16 53 38](https://user-images.githubusercontent.com/53316744/61911703-d8df9100-aefd-11e9-88ca-ef6b9e2edbd4.png)
![2019-07-25_16 55 23](https://user-images.githubusercontent.com/53316744/61911705-d9782780-aefd-11e9-8cc0-da4630bf0973.png)
![2019-07-25_16 56 11](https://user-images.githubusercontent.com/53316744/61911707-da10be00-aefd-11e9-8cf2-f9dfb45c69a1.png)
![2019-07-25_16 56 29](https://user-images.githubusercontent.com/53316744/61911708-daa95480-aefd-11e9-80c6-42cf107cb362.png)
![2019-07-25_16 56 30](https://user-images.githubusercontent.com/53316744/61911710-db41eb00-aefd-11e9-98ed-f021448d4560.png)
![2019-07-25_16 56 44](https://user-images.githubusercontent.com/53316744/61911711-db41eb00-aefd-11e9-8322-de0670cf7222.png)
![2019-07-25_16 56 50](https://user-images.githubusercontent.com/53316744/61911712-dbda8180-aefd-11e9-88cb-657b043e90cc.png)
![2019-07-25_16 56 56](https://user-images.githubusercontent.com/53316744/61911714-dc731800-aefd-11e9-94e8-88ef1b91713d.png)
![2019-07-25_16 57 10](https://user-images.githubusercontent.com/53316744/61911716-dd0bae80-aefd-11e9-8da9-7f762abe84df.png)
![2019-07-25_16 57 20](https://user-images.githubusercontent.com/53316744/61911717-dda44500-aefd-11e9-90db-12e15d2d9bbe.png)
![2019-07-25_16 57 31](https://user-images.githubusercontent.com/53316744/61911718-de3cdb80-aefd-11e9-844c-e2cc6a82d75d.png)
![2019-07-25_16 58 35](https://user-images.githubusercontent.com/53316744/61911719-ded57200-aefd-11e9-836f-6ec54080b1ef.png)
![2019-07-25_16 58 44](https://user-images.githubusercontent.com/53316744/61911721-ded57200-aefd-11e9-8921-d3d4e71130fc.png)
![2019-07-25_16 59 41](https://user-images.githubusercontent.com/53316744/61911722-df6e0880-aefd-11e9-8c09-eb8d32da1843.png)

**Comment by brandon3055** [comment]
It sounds like failsafe shutdown is triggering. But that should only happen if saturation hits 99% and temperature drops below 2500. That should not be possible if the reactor is powering its own shield with no external help. Does this still happen if you turn of fail-safe mode? 
Also not entirely related but how are you limiting the amount of power you're pulling from the reactor?
