### ISSUE TITLE
There is no info when i open information tablet 

### ISSUE THREAD

**Issue by adamsonich** [brandon3055/Draconic-Evolution#1347]
## Base information
* Minecraft version: 1.12
* Mod version: Draconic-Evolution-1.12.2-2.3.21.342-universal.jar
* Minecraft Forge version:
* Mod Pack: (if applicable) Enigmatica2Expert

When i open "Information Tablet" in any my saves and get "No documentation pages were found! this most likely means the documentation failed to download for some reason."

I dont found any fix information in issues.

How to fix it?

**Comment by FoxMcloud5655** [comment]
First, this is a Project Intelligence issue, if anything.

Second, can you post your latest.log?  That should help us determine the issue.

**Comment by adamsonich** [comment]
[latest.log](https://github.com/brandon3055/Draconic-Evolution/files/3452313/latest.log)
Ok. But it has no info about PI or tablet.
![2019-07-31_19 29 07](https://user-images.githubusercontent.com/12843115/62220470-899bd380-b3c9-11e9-845c-e488520a1eb0.png)

**Comment by adamsonich** [comment]
Ok. After installing "VanilaFix" mod, i get correct work in tablet.

**Comment by FoxMcloud5655** [comment]
Interesting.  I wonder why that is?  I'm not sure I would be able to drill down and figure out exactly what happened, but at least it's resolved on your end.

**Comment by brandon3055** [comment]
This issue occurs because the outdated java versions used by most launchers does not support the newer SSL standard used by the project intelligence server. (Well its something along those lines i don't recall the exact details)
This This should be fixed in the most recent version of Project Intelligence.

**Comment by EscolarProgramming** [comment]
Hello brandon,
I've the same problem. Updating to latest Project Intelligence (1.0.7.24) and latest Brandons Core (2.4.17.208) hasn't solved it. Or do you mean a version which will be published in future?

**Comment by 8qBITs** [comment]
Same problem, All the mods 3 modpack.
