### ISSUE TITLE
Receiving an intant kill causes half dead state when wearing draconic/wyvren armor

### ISSUE THREAD

**Issue by adamsong** [brandon3055/Draconic-Evolution#1348]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.20.333
* Minecraft Forge version: 14.23.5.2808
* Mod Pack: Modern Skyblock 3 Departed

Any source of instant death, such as `/kill` and the Death Generator for Extra Utilities 2 that the player receives while wearing the draconic armor results in them getting a respawn screen. However the player has not fully died, and clicking respawn just dismisses the overlay, without respawning them. The third time this happens the player will be unable to move and the screen will twitch.

This is what is seen from the inventory screen while in this half dead state
![Player Partially Dead](https://user-images.githubusercontent.com/4607006/62845857-93f78080-bc99-11e9-886c-34f1c6ab26e3.png)

**Comment by FoxMcloud5655** [comment]
First, try updating BrandonCore and Draconic Evolution to their latest versions and see if the problem persists.

If it does, then please let us know.  If not, then bug the modpack author to update.
