### ISSUE TITLE
API hack: "RF-Big"

### ISSUE THREAD

**Issue by SoniEx2** [brandon3055/Draconic-Evolution#135]
Make it so you return a negative integer from the RF API indicating how many times you should call it again to get all the bits. For longs, you'd return -2. Other negative integers would require BigInteger precision (except -1 which would be invalid).

I like to call this negative variant/hack "RF-Big", because it's passing BigIntegers thru the RF API. It's similar to how Unicode/UTF-8 works.

**Comment by Oxosorrel** [comment]
Not the DE dev here, so dont take my word for it. But as an observer of mod dev, and player of DE and other RF mods, this discussion probably belongs in the Cofh API git. Like it was discussed here:

https://github.com/CoFH/Feedback/issues/759

Alternatively, it be a stand alone hack and not part of a content mod like DE. If it was stand alone, all other mod authors can decide if they want to be tied to the performance hit you are proposing. 

Enderio said no already: https://github.com/SleepyTrousers/EnderIO/issues/2700#issuecomment-128195267

**Comment by SoniEx2** [comment]
I'm sure if we pushed it other mods would adapt.

**Comment by brandon3055** [comment]
The issue with this is every mod that uses the RF API would have to implement it and that is just not going to happen. It may also cause serious issues with some mods since the api should only ever return a positive number for energy stored (or 0) most mods wont be expecting the possibility of a negative number and it could cause some serious issues.

**Comment by SoniEx2** [comment]
Adding the hack will cause crashes, at first, but then the other mods will adapt to it. (or ppl will just stop using your mod, both reduce crashes)

**Comment by brandon3055** [comment]
In my opinion that would just be very bad practice. Mod A should not have to change how it uses an api because mod B dose something that the api was never designed for.

**Comment by SoniEx2** [comment]
You could add it for pushing/pulling only.

At least you'd have to trigger it first (pass in a negative value) and you'd know the caller knows how to handle negative values.

(Transfer speeds of upto 2^63-1 RF/t? why not!)

**Comment by brandon3055** [comment]
Because even i dont need to move energy that fast... (and thats really saying something)
