### ISSUE TITLE
Creative Fly Dont Work

### ISSUE THREAD

**Issue by GJungle1** [brandon3055/Draconic-Evolution#1350]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.22.343
* Minecraft Forge version:  14.23.5.2838

## Crash report
Theres no crash but i cant fly when i hit double space it gives me some kind of a double jump or so please help!!

**Comment by FoxMcloud5655** [comment]
There are known issues with forge version 2838.  Try downgrading to 2836 and see if that fixes your issue.  For me, I can't even create a server using 2838

**Comment by brandon3055** [comment]
No reply from OP
