### ISSUE TITLE
Draconic evolution items crash the game when shaders are enabled

### ISSUE THREAD

**Issue by BoobieWoobie** [brandon3055/Draconic-Evolution#1354]
[crash-2019-09-01_08.02.38-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/3563202/crash-2019-09-01_08.02.38-client.txt)

**Comment by FoxMcloud5655** [comment]
First, try removing Optifine.  It always complicates things.

Second, try upgrading to Forge version 2836.  That's the most stable, I've found.

**Comment by BoobieWoobie** [comment]
Without Optifine I cannot use shaders lol, but i will try that version of forge.

**Comment by FoxMcloud5655** [comment]
Not exactly true.  Not only can mods use shaders on their own accord, but you also have an alternative mod to add your own shaders; GLSL Shaders.

Convenience link: https://shadersmod.com/downloads/

**Comment by brandon3055** [comment]
If this is still an issue then i suggest you disable DE's shaders via the DE config.
