### ISSUE TITLE
Disconnecting from the local server when opening blocks from the mod

### ISSUE THREAD

**Issue by TheStrix21** [brandon3055/Draconic-Evolution#1359]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.24.349 - universal
* Minecraft Forge version: 14.23.5.2844

Play with friend on local networks. When I or a friend opens blocks from the mod, I disconnect from the server.

## Crash report
```
Jinkiie lost connection: Internal Exception: io.netty.util. illegalReferenceCountException: refCnt:0
[NotEnoughItems]: Error thrown whilst accessing JEI internals!
```

**Comment by brandon3055** [comment]
Looks like an issue with NotEnoughItems. That mod is currently a little broken so i suggest you try uninstalling it.

**Comment by TheStrix21** [comment]
We just tried only with draconic evolution and the problem remained

**Comment by brandon3055** [comment]
I need to see the new error without NotEnoughItems installed.
It may also help to see both the host and client logs.

**Comment by FoxMcloud5655** [comment]
I suspect this is an issue related to CodeChickenLib again.  Please update that mod and report back.

**Comment by TheStrix21** [comment]
https://pastebin.com/sV4utQE8 - Friend
https://pastebin.com/5MGxRWcz - Host

**Comment by TheStrix21** [comment]
> I suspect this is an issue related to CodeChickenLib again. Please update that mod and report back.

My friend and I have the latest versions installed

**Comment by TheStrix21** [comment]
And although there is no, I have was established 357 version of, and a new 358. Updated, now check.

**Comment by TheStrix21** [comment]
Обновил CodeChickenLib до версии 358 и перестало вылетать. Спасибо вам!

**Comment by FoxMcloud5655** [comment]
I figured it was the case...  Mind closing the issue?

**Comment by TheStrix21** [comment]
FoxMcloud5655 thanks!!!
