### ISSUE TITLE
death problem

### ISSUE THREAD

**Issue by XiNaru** [brandon3055/Draconic-Evolution#1360]
so, what nonsense have you programmed there? I die in chaos kites even in creative mode AND in God Mods all the time. That's unlogical in EVERY respect.

**Comment by FoxMcloud5655** [comment]
I'm assuming that it's because some mods were able to give a player "creative" mode in terms of invincibility.  Chaos damage goes through that invincibility.  Funnily enough, Minecraft actually has a built-in way to bypass creative mode invincibility.

**Comment by XiNaru** [comment]
sorry that I was a bit mad. it's just very frustrating to just want to look at something in the creative, and zack, death ....

**Comment by FoxMcloud5655** [comment]
Try going into spectator mode.

**Comment by XiNaru** [comment]
Unfortunately it brings me nothing :) but thank you very much.

only one question ... can not revive the NEW Enderdrachen at 1.12.2?
I do not find this resurection stone.

**Comment by FoxMcloud5655** [comment]
It was worth a try!  In 1.12.2, vanilla Minecraft actually has a way of reviving the Ender Dragon.  Craft 4 "End Crystal" items and place each one on the sides of the End Portal in the End.

**Comment by XiNaru** [comment]
sry, but I'm not talking about the NORMAL ender kite :)

in a wiki I read about this:
https://ftbwiki.org/Ritual_of_Draconic_Resurrection

**Comment by FoxMcloud5655** [comment]
That was for when there was no natural way of resurrecting the dragon.  The ritual has been removed in favor of the vanilla method.

**Comment by XiNaru** [comment]
Oh, it's a pity, but good to know. Thank you

then one last question.

is there any way to load weapons and armor FAST?

Because..I use big reactor for energy production and the draconic energy core.

And to load I use the enderio wireless charger, but it takes forever if I want to charge my armor with over 1G.

Are there perhaps better methods for charging?

**Comment by FoxMcloud5655** [comment]
I use wired chargers to charge my Flux Capacitors.  Draconic Evolution's charger and Mekanism's Ultimate Energy Cube are my preferred methods, as they are nice and fast.  EnderIO's Enhanced Wireless Charger is good to keep it topped off for small fights and tool usage, but not for recovering after a battle with a Chaos Dragon!

**Comment by XiNaru** [comment]
charger from draconic? do you mean the capacitor? or is there still a device that I have overlooked?

unfortunately the enhanced wired charger is just as fast as the wireless one

I currently only use the basic wireless energy crystall and not wyvern or draconic

**Comment by FoxMcloud5655** [comment]
It's a device you probably overlooked :)  It's called the Energy Infuser.

**Comment by XiNaru** [comment]
unfortunately just as fast so far

are the wyvern wireless energy crystall and the draconic wireless energy crystall faster than the basic? or do you just have more link places?

**Comment by FoxMcloud5655** [comment]
Don't use the Wireless Energy Crystals; they are for powering/gathering from most basic machines.  Use the I/O variation, as it's designed to transfer much more energy.

I would also recommend at least upgrading to Wyvern.

**Comment by XiNaru** [comment]
but then i would have to lay cable everywhere and i had assumed, especially the wireless variants transmit the most current.

**Comment by FoxMcloud5655** [comment]
Don't know how your base is set up, but all of the Energy Crystals (Relay, I/O, and Wireless) can connect to each other through walls.  There's no need to set up cabling.

**Comment by XiNaru** [comment]
Did not you just say I should not use the wireless? :)

and as far as I know I can not connect relay crystals directly to machines.

or do you mean the HALF CRYSTALS that you put on the machines?

**Comment by FoxMcloud5655** [comment]
Did I not keep saying the I/O Crystals? :)  Yes, the I/O Crystals are the half size crystals.  The Relay Crystal is not able to connect to machines; just to other crystals.  Connecting to other crystals is done wirelessly, hence why I said "Wireless I/O Crystal".  Most people don't know how the system works without a tutorial, so I use that term to make them realize it's wireless.

**Comment by XiNaru** [comment]
okay I have to look
i have made a relay to wyvern and an i / o crystall from wyvern to the energy injector. I'll see soon when my armor has lost a lot of energy. (p.s .: have you ever sent an email because of another question)

**Comment by FoxMcloud5655** [comment]
I saw it, I just haven't had time to respond.  I'll take any further inquiries on my support email as to not gum up this issue.

**Comment by brandon3055** [comment]
There will be a config option to disable chaos guardian creative damage in the next release. So i am closing this issue.
