### ISSUE TITLE
How to change the staff of his radius 1 7 10

### ISSUE THREAD

**Issue by AlexandrMix** [brandon3055/Draconic-Evolution#1361]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.0.2h
* Minecraft Forge version:
* Mod Pack: (if applicable)

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
What exactly are you trying to report here?  There is no crash report, and you missed the Minecraft Forge version.

If you're asking how to change the digging area of the Staff of Power, then look through the controls for "Tool & Armor Config GUI".

**Comment by AlexandrMix** [comment]
Post actively dig 11 by 11 I want maxim to dig 7 by 7 on the server in the config there is no this config to configure

**Comment by FoxMcloud5655** [comment]
No, there is no option to limit how big the dig radius is as far as I'm aware.  You're also asking for support for an older version of Minecraft, so unfortunately, this won't be integrated into 1.7.10.

However, it does raise a valid question on why this should be an option.  I'll see if I can edit the appropriate code if it's not there already for 1.12.2.

**Comment by AlexandrMix** [comment]
It’s unfortunate that I think it would be nice to add such an opportunity for the server; more load when digging with this staff and gray can just fall
