### ISSUE TITLE
Draconic Evolution Crafting Injectors Not Work

### ISSUE THREAD

**Issue by JamesMuhammad** [brandon3055/Draconic-Evolution#1366]
Unable to get RF into the Draconic Evolution Crafting Injectors. I have try'd a few things 
( listed below ).

Mod Pack: ATM 3 Remix
Version: 1.5.1
* Try'd putting creative capacitor behind each and none of them accepted power.
* Swapped out Enderio energy conduit for Draconic Evolution crystals.

Gifs Showing The Setup

![Number 1 Opt](https://user-images.githubusercontent.com/57921568/69106576-cc4aef80-0a3c-11ea-9707-31948f0048df.gif)

![Number 2 Opt](https://user-images.githubusercontent.com/57921568/69107210-9dce1400-0a3e-11ea-948f-5dcfbab92850.gif)

![Number 3](https://user-images.githubusercontent.com/57921568/69107220-a6bee580-0a3e-11ea-8d63-23a115bc7eef.gif)

**Comment by FoxMcloud5655** [comment]
Have you tried actually crafting with them?  They don't request RF until you put in a valid recipe.

**Comment by JamesMuhammad** [comment]
Doesn't show up

**Comment by FoxMcloud5655** [comment]
Guessing that was it.
