### ISSUE TITLE
Advanced Dislocator is causing issues with attributes

### ISSUE THREAD

**Issue by SokyranTheDragon** [brandon3055/Draconic-Evolution#1368]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.24.349
* Minecraft Forge version: 14.23.5.2847

- Issue: After using Advanced Dislocator (potentially a normal one could cause this as well, but I haven't tested this), the player attributes seem to be ignored until any change is applied to them. This is the most noticeable with reach attribute (and in case ArtemisLib is installed, as well as any mod utilizing it, the size attribute being ignored is very noticeable as well). The attributes can be 'refreshed' in game if any of attributes is changed, making them work as desired.

- Additional info: This might be a client-only issue, as the attributes (or at least some of them) seem to be handled properly on the server side.

- How it should be: The attributes should still work as intended without having to 'refresh' them after teleporting.

**Comment by FoxMcloud5655** [comment]
Uh...  Have you tried using ANY teleportation method?  This happens to everyone, thanks to Minecraft bugs in 1.12.2.  Hop into a nether portal and see if it happens again.

**Comment by exploder1531** [comment]
It does not really happen with any other method I tried. I tried using RandomPortals Nether/End portals, EnderIO travel anchors and telepads, and using commands. None of the other methods have that issue. I did not, however, test normal Nether/End portals.

**Comment by FoxMcloud5655** [comment]
Interesting...  I know this has happened to me on many occasions, and Mojang only recently patched the relevant bug.  If I get time over the next few days, I will test this myself and report back.
