### ISSUE TITLE
[Suggestion] Draconic leggings

### ISSUE THREAD

**Issue by MoonKill** [brandon3055/Draconic-Evolution#137]
The movement speed forward is really fast. But you keep sidewalking at a vanilla speed which can be hard to get used to (and annoying :P ). Can you make the sidewalking speed half of the forward movement speed ?
Thanks

**Comment by GreatOrator** [comment]
You can adjust the speed of the leggings in the gui.

**Comment by brandon3055** [comment]
Not what he meant he is talking about the strafing speed which is unaffected by the speed boost.
