### ISSUE TITLE
Charged Draconium Block

### ISSUE THREAD

**Issue by Zolonos** [brandon3055/Draconic-Evolution#1372]
Minecraft version: 1.10.2
Mod Draconic-Additions-1.12.2-1.10.0.28
Minecraft Forge version: 14.23.5.2847
Mod Pack: (if applicable): own assembly

Hello, I decided to resurrect the dragon, but I saw that the Charged Draconium Block was disabled. Are there other ways to resurrect a dragon?

**Comment by FoxMcloud5655** [comment]
First of all, 1.10.2 can't be your MineCraft version, as the forge version you listed is for 1.12.2.

Second, you're listing Draconic Additions.  That's my mod, not brandon3055's.

Third, and most importantly, the ritual for resurrecting the dragon was removed in favor of the vanilla method.  You can look it up here: https://minecraft.gamepedia.com/Ender_Dragon#Spawning
