### ISSUE TITLE
"Place item in world" feature will ignore server's spawn protect area.

### ISSUE THREAD

**Issue by RainEffect** [brandon3055/Draconic-Evolution#1373]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.24.349
* Minecraft Forge version: 14.23.5.2847
* Mod Pack: [EnigTech2](https://github.com/ET-Team/EnigTech2)

## Bug report
"Place item in world" feature will ignore that server's spawn protect area.
So I can place that a lots of garbage at server's spawn point...
And I can't take it back without permission...

(I'm sorry but my English is not good.)

**Comment by FoxMcloud5655** [comment]
I've known about this issue for a while.  I don't know if there is a clean fix for it on Draconic Evolution's side.

**Comment by brandon3055** [comment]
It does fire the place event so protection plugins should have no trouble blocking it.

**Comment by RainEffect** [comment]
Nope It can't. Because our server was getting trouble in it.

**Comment by brandon3055** [comment]
What protection plugin are you using?

**Comment by RainEffect** [comment]
Nope, we only use that original forge on our server. Because some mods will crash in sponge or others.

**Comment by brandon3055** [comment]
Ahh... So your talking about vanilla spawn protection? Yea that won't work. I should probably fix that...
