### ISSUE TITLE
Mob grinder server crash

### ISSUE THREAD

**Issue by BoxingSheep** [brandon3055/Draconic-Evolution#1375]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.0.2h 
* Minecraft Forge version: forge-1.7.10-10.13.4.1614-1.7.10-universal
* Mod Pack: Crundee Craft
I have a wither farm that automatically spawns withers and whenever the mob grinder tries to kill the wither the server crashes, this issue only occurs in multiplayer, it doesn't crash when done in singleplayer.

## Crash report
```
https://pastebin.com/C8iy9cWV
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

**Comment by FoxMcloud5655** [comment]
First of all, this is a crash with Minecraft Comes Alive, not Draconic Evolution.  They don't handle fake players properly.

Second, you're using Minecraft version 1.7.10.  This version is no longer supported by Draconic Evolution.
