### ISSUE TITLE
Armor Model Bug Report

### ISSUE THREAD

**Issue by RainEffect** [brandon3055/Draconic-Evolution#1378]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.24.349
* Minecraft Forge version: 14.23.5.2847

## BUG report
Armor Model was wrong when it was wearing on Zombie or CustomNPCs(When it was using hugging pose)

![Armor Model Bug Image](https://user-images.githubusercontent.com/14258727/71975411-dcb66400-324e-11ea-85c9-56a9be1622b1.png)

**Comment by RainEffect** [comment]
Hmmmm......
![Bug Image](https://user-images.githubusercontent.com/14258727/71977145-0a051100-3253-11ea-8415-fa809583a2f0.png)

**Comment by FoxMcloud5655** [comment]
Interesting.  The player shouldn't perform these animations by default, so I can see why this was overlooked.

**Comment by brandon3055** [comment]
This is an issue i am aware of but unfortunately its not that easy to fix. The armor model parts are essentially "bound" to the wearers model parts so no matter how the entity moves the armor model should just work. But minecraft is weird... so things rarely "just work" I have spend some time looking into this and short of writing custom handling for every entity in existence i have not found a fix.

**Comment by RainEffect** [comment]
Oops, Hope I will easy to fix.

**Comment by brandon3055** [comment]
If anyone knows of a good solution to this issue then feel free to comment because i am out of ideas.
