### ISSUE TITLE
weird pink gradient replacing usual UI for power on Armor

### ISSUE THREAD

**Issue by Dynamic225** [brandon3055/Draconic-Evolution#1382]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.0.2h
* Minecraft Forge version: 10.13.4.1614
* Picture of bug: https://i.imgur.com/P58evzW.png

**Comment by FoxMcloud5655** [comment]
First of all, you're asking for support for an unsupported version of Draconic Evolution. 1.7.10 is no longer supported, as 1.12.2 is the latest edition of Minecraft that DE is built for.

Secondly, you didn't provide log files for the time period that the issue happened at, so we wouldn't have known what was happening anyways.

Sorry, but this issue will most likely be closed.

**Comment by brandon3055** [comment]
@FoxMcloud5655 is correct. That said my best guess is another mod is probably breaking the renderer. Or maybe the DE jar is corrupt resulting in a broken texture but that seems unlikely.
