### ISSUE TITLE
Stabilized Spawner with Quest Ram spawns Vexes

### ISSUE THREAD

**Issue by Venom31** [brandon3055/Draconic-Evolution#1385]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.24.349
* Minecraft Forge version: 14.23.5.2846
* Mod Pack: Feed The Beast Academy 1.1.0
* Version(s) of other mod(s) involved: The Twilight Forest 3.9.984, mob_grinding_utils 0.3.13

## Crash report
Doesn't crash

## Description
1. Used mob_grinding_utils to obtain a spawn egg of Quest Ram from The Twilight Forest (Mob Swab it, combine with seeds/XP etc.).
2. Used spawn egg on some zombie villager spawner. It successfully spawned Quest Rams.
3. Applied a Draconic Core (the lowest tier) on the spawner. That successfully turned it into Stabilized Spawner and was picked up.
4. Placed down the Stabilized Spawner. It displays and spawns vanilla Minecraft Vexes instead of The Twilight Forest Quest Rams.

Unfortunately, I have no screenshots/video evidence, as I had to break it as soon as I confirmed that it indeed would spawn what it displayed. It's also quite expensive to reproduce in survival (wasted spawner every time), so I didn't double-check it, sorry. Also, maybe Quest Rams are just not intended to be in Stabilized Spawners?

**Comment by FoxMcloud5655** [comment]
Interesting.  If the spawner is a vanilla spawner, then that means DE may have incorrectly stored the data.  I'll see if I can reproduce the issue.

**Comment by Venom31** [comment]
Yeah, idk if a **Zombie Villager** spawner may be considered vanilla..

**Comment by FoxMcloud5655** [comment]
While a spawner of that type may never be found in vanilla, it's a vanilla block using vanilla mobs.

Also, just tried the same thing as above in FTB Academy.  Everything works as intended.  I will try using your exact method as a final test.

**Comment by Venom31** [comment]
This was over more than one session. For the record, I've put it into Actually Additions small crate and then into Refined Storage drive... I hope it doesn't matter.

**Comment by FoxMcloud5655** [comment]
So, it was created, stored in other containers (especially Refined Storage, which has a history of not working with metadata correctly), then it was used?  Okay...  That's probably nothing on DE, then.  I already tested using your method above; everything worked.
