### ISSUE TITLE
Tier 5 energy core in tablet.

### ISSUE THREAD

**Issue by srg6222** [brandon3055/Draconic-Evolution#139]
The visual for the Tier-5 energy storage multi-block in the information tablet seems to be inaccurate.
 The gif in the tablet shows the "corners" of the sphere missing a block while your site and the game require it to be there.

I am currently playing on version 1.0.1 c through the ATL project Flux pack if that makes a difference.

**Comment by brandon3055** [comment]
Hmm... i thought i fixed that in 1.0.1-c but it will definitely be fixed in the next release.
