### ISSUE TITLE
Stabilized Spawner performance

### ISSUE THREAD

**Issue by bigenergy** [brandon3055/Draconic-Evolution#1392]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.351
* Minecraft Forge version: forge-1.12.2-14.23.5.2847
* Mod Pack: (if applicable) no

Stabilized spawner causes high server load

https://sparkprofiler.github.io/#g0GU9bHadz
https://sparkprofiler.github.io/#ru25GGVD6A

![image](https://user-images.githubusercontent.com/17977139/74752847-598e2200-5280-11ea-83d3-e599e8e2d473.png)

**Comment by FoxMcloud5655** [comment]
Going to have to give more info than that.  What mob was it spawning?  What spawner tier was it?

**Comment by bigenergy** [comment]
> What spawner tier was it?
Wyvern only.

Unfortunately, it is extremely problematic to find all spawners on my server, so I don’t know which mobs it will spawn.

**Comment by bigenergy** [comment]
> What mob was it spawning?

Most likely it is spawnners with golems

![image](https://user-images.githubusercontent.com/17977139/74839830-01662700-5337-11ea-983f-7c2cf59457cb.png)

**Comment by BadLucKWyvern** [comment]
What program/mod allow us to see the game performance like this ?

**Comment by hduelme** [comment]
I am not sure, but it looks like[LagMonitor](https://www.spigotmc.org/resources/lagmonitor.21348/). @BadLucKWyvern

**Comment by BadLucKWyvern** [comment]
Ok, Thanks for the info :)
