### ISSUE TITLE
Stabilized Spawner crashes the game

### ISSUE THREAD

**Issue by DarkLord005** [brandon3055/Draconic-Evolution#1393]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.351-universal
* Minecraft Forge version: 14.23.5.2847
* Mod Pack: (if applicable) custom
## Description 
 So I'm facing an issue with stabilized mob spawner,  I play with my friend through LAN, he is a host. When he places a stabilized spawner from DE, Minecraft just disconnects me from the server, and i can't relog until the spawner is removed. The host doesn't have this problem. This issue occured on a different LAN server before with the same modpack, and there was the same crash for players, except for the host.
BTW the spawner is for Wither Skeleton, 1st tier.
## Crash report
```
[crash-2020-02-19_14.59.02-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/4224740/crash-2020-02-19_14.59.02-client.txt)

**Comment by FoxMcloud5655** [comment]
I've seen something similar to this before.  Ensure that CodeChickenLib is up-to-date along with BrandonCore.

**Comment by DarkLord005** [comment]
Updating CCL fixed this problem. Thank you for the support!
