### ISSUE TITLE
Second Wireless Wyvern Energy Crystal can't connect to machines

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#1395]
## Base information
* Minecraft version: 1.12.2
* Mod version:  1.12.2-2.3.25.351
* Minecraft Forge version: 1.12.2-Forge14.23.5.2846
* Mod Pack: (if applicable) Ultimate Reloaded - Heavily modified 

Not a crash, just unable to do something in game. I created an energy sphere, attached a Wyvern tier I/O Crystal to the output pylon, linked that to a Wyvern tier relay, relay to two Wyvern tier wireless  energy crystals. The first I used up all 32 connecting to my machines in my workshop and autocrafting setup. I go to connect the rest using the second wireless energy crystal and it can't connect to any of the machines without an I/o Crystal. It gives me the error "That tile can not supply energy on that side! " . And I've clicked the Crystal Wrench on all 6 sides with no luck. So far, for that wireless crystal, I've tried it on an RFTools Dialer, a TF Magmatic Crucible, and a TF Pulverizer. No luck, I have to slap an I/O Crystal onto them to get them powered. 
![2020-02-23_23 14 08](https://user-images.githubusercontent.com/7238110/75134725-fcd1a380-5693-11ea-8c90-f6785172d8ff.png)
![2020-02-23_23 27 51](https://user-images.githubusercontent.com/7238110/75134768-1ecb2600-5694-11ea-87ad-c2f248f07639.png)

**Comment by FoxMcloud5655** [comment]
Have you made sure that the Wireless Crystal in question is in output mode, not input mode?

**Comment by llloyd4** [comment]
... 

I didn't even know that was a thing, ok... Let me check. Ok... So it was, didn't think the wireless worked both ways. O.o Apologies.
