### ISSUE TITLE
 Crash of Energy Crystals

### ISSUE THREAD

**Issue by Ranios200** [brandon3055/Draconic-Evolution#1396]
Hey. A dragon evolution crashes on 1.12.2. I know the reason. These are the crystals with which you transmit energy. I don’t know why it crashes. Please help. 
When I go into DE tools and weapons everything is fine, but when I go into DE blocks and objects it flies out. And on version 1.7.10 everything is fine. Why is that?
Machine info: -------------------------------------------------------
Windows 7 6.1, Java 1.8.0_231, jvm bit x64, 5982 MB RAM
java path=C:\Program Files\Java\jre1.8.0_231\bin\javaw.exe
Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
 Intel(R) HD Graphics 4000, Intel(R) HD Graphics Family, 1760 MB
-------------------------------------------------------
Selected locale: ru_RU
[Loading] LOADING_CONSOLE
[Swing] Favicons loaded: 256px, 128px, 96px, 64px, 48px, 32px, 24px, 16px

> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000301c0f1b, pid=7788, tid=0x00000000000017a8
> #
> # JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode windows-amd64 compressed oops)
> # Problematic frame:
> # C  [ig7icd64.dll+0x10f1b]
> #
> # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
> #
> # An error report file with more information is saved as:
> # C:\Users\�����\AppData\Roaming\.minecraft\hs_err_pid7788.log
> #
> # If you would like to submit a bug report, please visit:
> #   http://bugreport.java.com/bugreport/crash.jsp
> # The crash happened outside the Java Virtual Machine in native code.
> # See problematic frame for where to report the bug.
> #
> AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (1217 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1
[Launcher] [Crash] Signature "Bad video drivers" matches!
[Crash] Signature "Bad video drivers" matches!
[Launcher] [Crash] Crash has been recognized!
[Crash] Crash has been recognized!

**Comment by FoxMcloud5655** [comment]
Without a crash report from Minecraft, there's nothing we can do.  This crash happened outside of Minecraft, so we can't see what triggered the problem to fix it.

**Comment by Ranios200** [comment]
Thanks. Drivers already tried to update. Did not help. It's a pity. But thanks anyway.

**Comment by Ranios200** [comment]
[hs_err_pid8556.log](https://github.com/brandon3055/Draconic-Evolution/files/4286475/hs_err_pid8556.log)

**Comment by FoxMcloud5655** [comment]
I see.  This is a problem with the shaders; somehow, your computer is unable to render the shaders for the Energy Crystals.

There's an option to disable shaders on said crystals so you won't experience crashes like this; try disabling them!

**Comment by Ranios200** [comment]
But as

**Comment by Ranios200** [comment]
Turn off animation?

**Comment by Ranios200** [comment]
thanks a lot. I decided.
