### ISSUE TITLE
When DE3 and they will be on 1.12.2?

### ISSUE THREAD

**Issue by N-stack-oss** [brandon3055/Draconic-Evolution#1398]

**Comment by FoxMcloud5655** [comment]
Not sure exactly what you're asking.  This is not an issue, and not a great place to ask questions.  However, I will answer as best as I can understand your question.

If you're talking about when you're Draconic Evolution 3 will come out, good luck.  It's in progress, but still is a while away.  No one knows the exact date.

If you're talking about when Draconic Evolution will be available for 1.12.2, that's actually the latest edition, so feel free to enjoy it.
