### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by cauliflower69** [brandon3055/Draconic-Evolution#14]
http://pastebin.com/gKVKxNW7

**Comment by brandon3055** [comment]
Update to the latest snapshot to fix that

**Comment by cauliflower69** [comment]
Thanks so much for the fast response. Could you link me to the latest version please?

**Comment by brandon3055** [comment]
http://minecraft.curseforge.com/mc-mods/223565-draconic-evolution/files/2225633

**Comment by cauliflower69** [comment]
Wow, you've been busy. Thanks again for the help. I checked the MCF link and Curse but didnt spot it. Also if all goes well with the test I just wanted to let you know that we plan on using your mod in out private pack with indeedcommunity.com if that is ok?

**Comment by brandon3055** [comment]
thats fine! thanks for letting me know

**Comment by cauliflower69** [comment]
Thanks again, really enjoying the mod so far. On a side note is it possible to add a cfg option for RF usage on some of the tools etc ?

**Comment by brandon3055** [comment]
maby... just let me know exactly what you mean and i will look into it in the morning.

**Comment by cauliflower69** [comment]
The rate at which the tools use RF. So you could add a multiplier etc ?
