### ISSUE TITLE
Disappearing Reactor Stabilizer's

### ISSUE THREAD

**Issue by jmac460** [brandon3055/Draconic-Evolution#1400]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.25
* Minecraft Forge version: 1.12.2   .2847 forge
* Mod Pack: (if applicable)

## Crash report
```NA
CRASH REPORT HERE
```NA


So basically, I spawn in the Reactor Stabilizer and when placing the block, it disappears. It shows that there is a block there, but the stabilizer does not show up. Also, when right-clicking on said ghost block, (SP and MP) the GUI does not show up. Config is default.


![image](https://user-images.githubusercontent.com/34420502/77877224-c818b500-721a-11ea-83d1-c3bb873abed0.png)

**Comment by FoxMcloud5655** [comment]
First of all, would you mind listing out your mods?  There may be a conflict somewhere.

**Comment by jmac460** [comment]
> First of all, would you mind listing out your mods? There may be a conflict somewhere.

Yes, the mods listed are installed on the server.
https://prnt.sc/rpqai2

**Comment by FoxMcloud5655** [comment]
Try removing VanillaFix first, and see if that fixes your problem.

**Comment by jmac460** [comment]
VanillaFix solved the issue.
