### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Ubus99** [brandon3055/Draconic-Evolution#1403]
Brandon, I want to fork your Mod, change some recipes and redistribute it as part of my modpack, but am not sure if this is allowed under your license.

Would that be ok with you?

**Comment by FoxMcloud5655** [comment]
According to the "Don't Be A Jerk" License:
```
#### You CANNOT
- Redistribute this in its entirety as source or compiled code (Except in the case of mod packs).
- Create or distribute code which contains 50% or more Functionally Equivalent Statements* from this repository.

#### You MUST
- Maintain a visible repository of your code which is inspired by, derived from, or copied from this code. Basically, if you use it, pay it forward. You keep rights to your OWN code, but you still must make your source visible.
- Not be a jerk**. Seriously, if you're a jerk, you can't use this code. That's part of the agreement.
```
The part that says "Except in the case of mod packs" means that your situation is allowed.  As long as it is ONLY hosted inside of your modpack and not hosted somewhere else, you may do so.

Alternatively, if all you're doing is changing recipes, I suggest going with CraftTweaker/MineTweaker and using DE's built in support for modifying Fusion Crafting recipes.

**Comment by Ubus99** [comment]
Ok, after re-reading I wasn't sure if the modpack part only refers to the original version or intersects with the 50% rule.
We are trying to move away from CT for performance reasons and because it lacks some capabilities, see https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4278

**Comment by FoxMcloud5655** [comment]
Ah, you were referencing an old build of DE for 1.7.10.  Unless otherwise specified, it's assumed that you're referencing the latest version of DE.  In that case, rebuilding the mod yourself is definitely the best way.
