### ISSUE TITLE
Chaos Guardian cannot be killed

### ISSUE THREAD

**Issue by EricBuist** [brandon3055/Draconic-Evolution#1404]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.20.333
* Minecraft Forge version:
* Mod Pack: Modern Skyblock 3

Is NOT a crash report!</br>

The Chaos Guardian just cannot be killed. There is too much going on at the same time and I cannot figure out what to do. Even with all the upgrades on draconic armor (all pieces are charged and installed), the boss is inflicting constant dammage pretty much ignoring the armor. This can be partially compensated by a Personal Nanobot beacon with Saturation and Regeneration modifiers, but the boss is pretty much immune to draconic bow (all upgrades installed up to Draconic level, bow is charged, Infinity enchantment so it can shoot arrows). Crystals protecting the dragon are hard to break, requiring many many shots, sometimes regenerate and there is no reliable way to figure out whether some crystals remain.
I understand the Chaos Guardian is an optional end-game boss, but many quest-based modpacks make it mandatory and that just prevents me from going on. Modern Skyblock 3, for example, if choosing the staged or gated progressions, cannot be completed because of that, and switching to kitchen sink cannot be done without restarting from scratch or tweaking (I searched and no obvious solution was available to switch progression, and didn't want to anyway). There is no obvious way to know in advance that a given modpack with questing will leads to that dead end, unless if I pick a pack without Draconic Evolution to know from sure.
This boss should not exist or at least the Draconic Armor should protect against it. Otherwise, only a few number of people with excellent gaming skills can defeat it.

**Comment by FoxMcloud5655** [comment]
I'd like to say "git gud", but there is a method to the chaos, so to speak.  Number one tactic is FLY FAST and perform hit and run tactics on the crystals.  After they are down, just stay out of the guardians way while chasing it down from the back as much as possible, sniping it with the bow.

**Comment by jamezrin** [comment]
> I'd like to say "git gud", but there is a method to the chaos, so to speak. Number one tactic is FLY FAST and perform hit and run tactics on the crystals. After they are down, just stay out of the guardians way while chasing it down from the back as much as possible, sniping it with the bow.

"git gud" hahah p
