### ISSUE TITLE
charging stuck at 99.996%

### ISSUE THREAD

**Issue by Gladyon** [brandon3055/Draconic-Evolution#1406]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.12.297
* Minecraft Forge version: 1.12.2
* Mod Pack: custom

Draconic crafting was working perfectly, until one day charging got stuck, power flowing properly, crafting recipe shows up, process just gets stuck in "charging".

**Comment by FoxMcloud5655** [comment]
Try updating Draconic Evolution first.  Your current mod version is out of date.  If this persists, then please let us know.

**Comment by Gladyon** [comment]
Fixed it by using different power cables.


st 8. 4. 2020 v 13:36 odesílatel FoxMcloud5655 <notifications@github.com>
napsal:
