### ISSUE TITLE
Question: Plans for 1.15.2?

### ISSUE THREAD

**Issue by TheUntamed** [brandon3055/Draconic-Evolution#1407]
The title says it all

**Comment by FoxMcloud5655** [comment]
The main code is already updated for 1.14.  the rewrite must be finished for 1.14 and an official version published before 1.15 can even be considered.

**Comment by XiNaru** [comment]
may I ask WHEN will you release the mod for 1.14.4? I'm currently playing a small modpack on the version and would really like to use the mod :)

**Comment by FoxMcloud5655** [comment]
That's a great question; it'll happen when it happens.  Personally, I'd love to know the answer to that as well, as I need a 1.14 version to exist before my mod can update to it!
