### ISSUE TITLE
Question regarding Draconic flux capacitor and interaction

### ISSUE THREAD

**Issue by Burakkurozu** [brandon3055/Draconic-Evolution#1409]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.0.2
* Minecraft Forge version:
Infinity Evolved 3.1.0
* Mod Pack: (if applicable)

The draconic flux capacitor doesn't seem to work correctly in this version. It charges when set to recharge items when they are full, and goes over the cap. It also seemed to bring my boots down to -170,000 RF.
Is there a natural work around or should I just forego the capacitor??

![image](https://user-images.githubusercontent.com/63438691/78961837-bf4c9c80-7ac0-11ea-8f1b-eda38f30bd09.png)

If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
Minecraft version 1.7.10 is no longer supported.
