### ISSUE TITLE
new crash with the energy core

### ISSUE THREAD

**Issue by LordGoldbludgeon** [brandon3055/Draconic-Evolution#141]
crashes when placing it down in the new 102 snapshot
http://pastebin.com/UTFvn4HT

**Comment by GreatOrator** [comment]
Already reported in

https://github.com/brandon3055/Draconic-Evolution/issues/136

**Comment by LordGoldbludgeon** [comment]
This one is reports your core mod as the cause
java.lang.NoSuchMethodError: com.brandon3055.brandonscore.common.utills.Utills.formatNumber(J)Ljava/lang/String;

**Comment by brandon3055** [comment]
Oh my bad i forgot that fix will also require me to push an update to BrandonsCore. I will upload it shortly.
