### ISSUE TITLE
Energy saturation keeps increasing

### ISSUE THREAD

**Issue by Kybolt420** [brandon3055/Draconic-Evolution#1412]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.20.333
* Minecraft Forge version: 14.23.5.2821
* Mod Pack: Direwolf20

Draconic evolution reactor is  set up like this: 
![image](https://user-images.githubusercontent.com/63613785/79157437-3a71c380-7ddd-11ea-8df0-9f6d98dea351.png)

i am inputing 125k with a flux gate and i set up the output on the fluxgate to be 550k and the reactor is generating 388k while  energy saturation is rising what should i do is this a bug? i read that the reactor generates infinite rf/t ?
![image](https://user-images.githubusercontent.com/63613785/79157624-989ea680-7ddd-11ea-86f7-a414eb8995c9.png)

**Comment by FoxMcloud5655** [comment]
This is not a bug; that's intended. The more awakened draconium (your fuel source) that gets converted into liquid chaos, the more efficient your energy output is.

At some point, you will have to shut down the reactor to refuel it and take out crystallized chaos shards, otherwise you'll have your reactor go out of control and explode on you.

**Comment by Kybolt420** [comment]
my heat is not going up 5k and my power generation is not going up too while i set up my flux gate to take out more that is being generated

**Comment by Kybolt420** [comment]
when i set my reactor to take out 550k it should generate 550k as i understand and energy sarturation should go down but when i googled how to lower energy sarturation nothing comes up so idk

**Comment by Kybolt420** [comment]
> This is not a bug; that's intended. The more awakened draconium (your fuel source) that gets converted into liquid chaos, the more efficient your energy output is.
> 
> At some point, you will have to shut down the reactor to refuel it and take out crystallized chaos shards, otherwise you'll have your reactor go out of control and explode on you.

so you are saying that i have to wait like a day for the reactor to start generating more rf? because idk the energy saturation is going up and up

**Comment by Kybolt420** [comment]
So i left  the reactor running in the night its not producing more energy, the temperature is lower and fuel saturation is still going up

**Comment by fdevx** [comment]
In case you are still wondering how to increase the temperature:
https://youtu.be/8rBhQP1xqEU?t=918

Also if you have a fresh reactor (almost no fuel converted yet) with 8 awakend draconium blocks in it you can lower the saturation to about 20% to  get the reactor temperature to about 7k degree. ANd dont forgeet to increase the saturation the more fuel gets converted or else your temperature will rise even further and you wont be able to maintain the containment field!

**Comment by Tahakk** [comment]
Or you can automate it with [Open Computers program](https://oc.cil.li/topic/873-draconic-control-get-everything-out-of-your-draconic-reactor/) that have few modes, config etc etc

**Comment by fdevx** [comment]
True - I personally have a modified version of the program thats presented in the video which basically keeps the Reactor at a configurable temperature until the fuel runs out. Its very safe and requires human interaction only for refueling - good for getting those chaos fragments!

**Comment by Kybolt420** [comment]
Yeah so the reactor blew up ages ago and i don't play the modpack anymore but in the video it says extract power =  temperature increase but the problem was that the reactor was generating somewhere around 300k rf/t but i made the fluxpoint to take 500k out of it so it was bugged or smth idk

**Comment by fdevx** [comment]
Did it  actually extract power? I think I  had a similar problem where I couldnt directly connect the flux gate to the reactor (the flux gate just didnt want to accept power from the reactor) I needed something in between to transfer energy
