### ISSUE TITLE
World border command

### ISSUE THREAD

**Issue by Xman102003** [brandon3055/Draconic-Evolution#1413]
In the end I am trying to get to the next boss but it says there is a world border and when I use the world border command it doesn't expand it in the end. I don't have a mod that does this, so do you know if there is any possible fix for this?

**Comment by brandon3055** [comment]
The vanilla world border is at 30,000,000 blocks in each direction by default. If it is not the vanilla border than it can only be a mod or server plugin.
How far out can you go? If you cant figure out how to remove the border maybe you can just go to another island within the border. Remember that the islands spawn in a grid 10k apart. 
```
*    *    *    *    *    *    *

*    *    *    *    *    *    *

*    *    *    *    *    *    *

*    *    *  0x,0z  *    *    *

*    *    *    *    *    *    *

*    *    *    *    *    *    *

*    *    *    *    *    *    *
```
