### ISSUE TITLE
[1.12.2] Chaotic Upgrades dont work

### ISSUE THREAD

**Issue by XiNaru** [brandon3055/Draconic-Evolution#1414]
## Base information
* Minecraft version: 1.12.2
* Mod version: Brandons Core: 2.4.18.210-universal --- Draconic Evolution: 2.3.25.351-universal
* Minecraft Forge version: 4.23.5.2847 (because the latest version somehow spins around when creating a server file)
* Mod Pack: (if applicable) : Custom Modpack

Good day,

I have the following problem:
I have 18 Chaotic Fusion Injectors and the materials I need. The Draconic Staff of Power is completely upgraded to Draconic, but with the merger I am shown that the fusion level is too high. Evidence in the pictures.

Drachonic Staff:
https://i.imgur.com/zoIdNIW.png

Level too high:
https://i.imgur.com/LODV7Ku.png

Fusion Left:
https://i.imgur.com/ptnwHvD.png

Fusion Right:
https://i.imgur.com/WCHzaiY.png

**Comment by FoxMcloud5655** [comment]
The Draconic Staff of Power is not supposed to be upgraded to Chaotic.  The only item that supports Chaotic upgrades is the Draconic Flux Capacitor.

Minecraft version 1.12.2 will never receive an update to allow you to upgrade to Chaotic tier, so I made a mod and added it myself, as well as quite a few accessories you may find useful.  You can search up Draconic Additions if you'd like the ability to upgrade the item.

**Comment by XiNaru** [comment]
I have the mod on it and built the chatotic staff of power, but it is complete with all upgrades to wyvern, but CANNOT dismantle anything. and with the menu from draconic I can not set anything.
