### ISSUE TITLE
Using the Draconic Hoe With Land Fill On Crashes Project Ozone 3 With "Invalid hand null"

### ISSUE THREAD

**Issue by canpan14** [brandon3055/Draconic-Evolution#1416]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.25
* Minecraft Forge version: forge-14.23.5.2847
* Mod Pack: Project Ozone 3 - 3.2.55

## Crash report
https://pastebin.com/xpNfPhLf

With it turned off the hoe worked fine. But when I turned the land fill on and use it, it crashes the game every time. I had dirt blocks in my inventory and plenty of power. When I logged back in, it had tilled the land correctly, it just crashes my game every time.

Sometimes it works once or twice, and then crashes the game. Always the same error.

Picture of exactly hoe in case it's needed https://i.imgur.com/3Mg5bdv.png

**Comment by brandon3055** [comment]
It looks like the mod 'netherex' is listening for the place event fired by the hoe. Its then attempting to retrieve the held item is the players 'null' hand. Which 'null' is obviously not a valid hand so its throwing a null pointer exception. I'm not sure exactly how they are managing to make that mistake or how its related to the hoe. I recommend you contact the netherex developer. 

Actually i just spent some time looking into it and as far as i can tell the crash in question should not be possible. But regardless the NetherEx already released a fix for this issue 5 days ago. 
https://www.curseforge.com/minecraft/mc-mods/netherex/files/2937750

**Comment by canpan14** [comment]
The wonders of coding :D Thanks for looking that far into it! For now I'll slave away like a peasant placing my own dirt.
