### ISSUE TITLE
Cannot open large size portal

### ISSUE THREAD

**Issue by therob** [brandon3055/Draconic-Evolution#1419]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.25.351-universal
* Minecraft Forge version: 14.23.5.2847
* Mod Pack: Project Ozone 3 3.2.55

## Issue
I tried to create a 11 x 145 (size of the frame) horizontal portal, but it didn't open. The largest size i was able to open was 11 x 101 (size of the frame). I have not checked wider portals.
According to the information tablet the maximum size should be 150 x 150.

**Comment by FoxMcloud5655** [comment]
Have you made sure that the entire portal is loaded?  I would highly recommend chunk-loading the entire portal if you're going to make one that big.

**Comment by therob** [comment]
Yes, i placed a spot loader from ChickenChunks in every chunk (10 chunks). Also i'm in single player with a render distance of 16 and can see the whole area. So it should definitely be loaded.

**Comment by therob** [comment]
I took a quick look at the code and found [this line](https://github.com/brandon3055/Draconic-Evolution/blob/c3063f381fee845e8667ace667abbd74c899b644/src/main/java/com/brandon3055/draconicevolution/blocks/tileentity/TileDislocatorReceptacle.java#L556). Looks like just 100 blocks (Euclidean distance) from the Dislocator Receptacle are scanned for the portal ignition.

I had the Dislocator Receptacle placed in the center of the shorter side. Placing it in the center of the long side works in my case. But if i understand this code correctly, 150 x 150 portals are not possible. The maximum size depends on the actual shape of the portal frame.

If i found the right spot, it would be really hard to explain to players how big the portal can be. I think the size check should to be changed.

**Comment by brandon3055** [comment]
Yea that documentation does need to be updated. Technically the largest you can make is a 198x198 circle with the receptacle in the center but even that isn't actually possible possible unless you increase your lvm stack size.
![](https://ss.brandon3055.com/bbf16)
Oh yea. The receptacle does not actually need to ba a part of the frame. It can be anywhere inside the frame's area..
