### ISSUE TITLE
Incorrect Update Notification

### ISSUE THREAD

**Issue by spannerman79** [brandon3055/Draconic-Evolution#142]
[Draconic-Evolution-1.7.10-1.0.2-Snapshot_2.jar](http://minecraft.curseforge.com/mc-mods/223565-draconic-evolution/files/2252803)
Forge 1448

    [CHAT] §d[Draconic Evolution]§r New version available:
    [CHAT] §aDraconic Evolution v1.0.1c
    [CHAT] Fixed crash with RFTools Force Field.

**Comment by brandon3055** [comment]
Hadn't pushed the update to github yet it should be fixed momentarily.
