### ISSUE TITLE
Fusion crafting stopped working

### ISSUE THREAD

**Issue by hernanmendez** [brandon3055/Draconic-Evolution#1421]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.25.351
 Download
* Minecraft Forge version: don't know
* Mod Pack: StoneBlock 2

After getting the Draconic Fusion Crafting Injector fusion crafting stopped working. (the items on the injectors weren't showing up)

I tried using other injectors, crafting new ones, crafting a new core and nothing worked

I tried using other power sources (I was using ender io conduits), nothing.

**Comment by FoxMcloud5655** [comment]
It seems like this issue may happen more often than anticipated.  Would you mind recording a short video demonstrating the issue?

**Comment by hernanmendez** [comment]
https://www.loom.com/share/705d2cb66afe4423bb2ad1a5c7501443

**Comment by FoxMcloud5655** [comment]
The recipe for an Awakened Core is 5 Awakened Draconium Ingots and 4 Wyvern Cores.

**Comment by hernanmendez** [comment]
Goof on my side, thank you
