### ISSUE TITLE
Negative capacity value on draconic staff of power

### ISSUE THREAD

**Issue by Speak2Erase** [brandon3055/Draconic-Evolution#1424]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.25.351-Universal
* Minecraft Forge version:14.23.5.2487
* Mod Pack: (https://github.com/wistlyr/Realistic-Unreality)
No clue why but when I upgraded my staff of power to draconic capacity it has a large negative value and I am unable to put it into any chargers
Using it to try and break things causes the amount of RF stored to jump to the negative value, and using it again causes it to go back to 0
I have tweaked the capacity for armour in configs, but not the staff

**Comment by FoxMcloud5655** [comment]
This is not DE's fault.  The modpack author has ignored (or didn't realize) the fact that the staff of power increases power stored compared to normal draconic tools by three times.

What you're seeing there is an integer overflow.  The mod pack author needs to reduce the amount of total RF tools can hold.

```I:draconicBaseRFCapacity=50000000```

This is way too much.

**Comment by Speak2Erase** [comment]
Ok, thanks
I thought it was an integer overflow
