### ISSUE TITLE
Wireless Energy Crystal Texture

### ISSUE THREAD

**Issue by dagantang** [brandon3055/Draconic-Evolution#1425]
I dont know why suddenly Suddenly become like this.How to fix it?
![2020-05-24_22 56 20](https://user-images.githubusercontent.com/32885622/82757309-2c6a8600-9e12-11ea-856c-ab839fea296e.png)

**Comment by FoxMcloud5655** [comment]
Not sure what you're trying to show here...  Everything looks okay to me.

**Comment by dagantang** [comment]
urm the colour is wrong.I remeber that the right colour is orange not grey.

**Comment by FoxMcloud5655** [comment]
Sometimes, particles will turn gray like that if there are too many things to render on the screen.  Usually, a restart will fix that issue.

**Comment by dagantang** [comment]
I have restart a few times.But its still turn grey,

**Comment by covers1624** [comment]
Likely caused by some other mod breaking rendering somehow, nothing can be done about this.
