### ISSUE TITLE
Custom Fusion recipes do not respect item stack size requirements

### ISSUE THREAD

**Issue by Saereth** [brandon3055/Draconic-Evolution#1426]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.351-universal.jar
* Minecraft Forge version: 14.23.5.2854
* Mod Pack: (if applicable) FTB Interactions

## Crash report
```
No crash
```
Please note assuming the issue is a crash something like this

The custom fusion crafting recipe works but it will not enforce the stack size requirements. This is the problematic recipe:

`
    {
        "mode": "ADD",
        "result": "enderutilities:enderpart,1,81",
        "catalyst": "enderutilities:enderpart,1,80",
        "energy": 22100000,
        "tier": 3,
        "ingredients": [
		"draconicevolution:chaotic_core",
		"draconicevolution:chaotic_core",
		"avaritia:block_resource,32,1",
		"avaritia:block_resource,32,1",
		"avaritia:block_resource,16,0",
		"avaritia:block_resource,16,0",
		"draconicevolution:awakened_core,8,0",
		"draconicevolution:awakened_core,8,0",
		"gregtech:meta_item_2,1,32501",
		"gregtech:meta_item_2,1,32501",
		"contenttweaker:overworldessencer",		
		"contenttweaker:overworldessencel"
        ]
    Which works fine 
![image](https://user-images.githubusercontent.com/9200909/82757792-bbdf4d00-9db0-11ea-9507-2cabacc52e99.png)

BUT it is crafting with only a single infinity block instead of requiring all 32...
![image](https://user-images.githubusercontent.com/9200909/82757824-dd403900-9db0-11ea-8c28-77a72ef3ad38.png)

same with neutronium blocks or any blocks Iv'e tested, stack size >1 is ignored and single stack size is accepted as valid for the craft. 

`

**Comment by FoxMcloud5655** [comment]
Stack size always has to be one.  That's the way all fusion crafts are coded.

**Comment by Saereth** [comment]
hrm, the Custom Fusion Recipe Info.txt does not make this clear then, why bother having a stack size as part of the formatting at all then? If that's Working as intended that's fine I can manage a work around. Probably worth noting in the instruction files that's the case in the future however.

**Comment by brandon3055** [comment]
I did originally plan to add support for stack sizes greater than 1 but in the end i decided to stick with the more standard 1 ingredient per slot. 
I also figured if a pack dev really wants to torture you they can just force you to setup 54 chaotic crafting injectors xD

**Comment by Saereth** [comment]
Hahah that's a good point, evil, I like it :p
