### ISSUE TITLE
[GUI problems] I don't see any way to configure Redstone behavior on a Draconic Reactor

### ISSUE THREAD

**Issue by macks2008** [brandon3055/Draconic-Evolution#1429]
## Base information
* Minecraft version:
* Mod version:
* Minecraft Forge version:
* Mod Pack: (if applicable)

## Crash report
```
N/A (issue is not a crash. I don't understand how to do something because, going off the instructions provided by Project Intelligence, the resulting expected behavior apparently conflicts with the actual behavior)
```
I'm trying to follow the instructions in the tablet about using Redstone Comparators took control a reactor, but when I open the interface on any of the stabilizers or the injector, I don't see anywhere that it can be configured for Redstone. 
![image](https://user-images.githubusercontent.com/7110033/83343815-4e11b480-a2cd-11ea-8c65-bf372aba862a.png)
and a screenshot of the injector with adjacent Comparator
![2020-05-30_22 46 22](https://user-images.githubusercontent.com/7110033/83343927-9b425600-a2ce-11ea-9440-74bdc7509453.png)
the only thing I could think is that maybe the reactor needs to be on before the controls can be configured... but that seems like backwards thinking, since you typically want to regulate a volatile system before you start pumping more energy into it...

And it probably goes without saying, though maybe not, that I never built one of your reactors before, out of fear of nuking my entire base and its surroundings. This is also why I'm doing this in a creative world right now: I want to learn how to do it right before I end up with a 10-chunk-diameter (or radius) crater in a survival world.

**Comment by brandon3055** [comment]
The button will show up once you start charging the reactor. Keep in mind the reactor is safe until you actually activate it. Though if its charged and you break a part of the reactor it will explode.

**Comment by macks2008** [comment]
I see. Thank you.
