### ISSUE TITLE
1.12.2 forge2813 crash

### ISSUE THREAD

**Issue by Vincent98740** [brandon3055/Draconic-Evolution#1430]
[crash-2020-06-13_12.44.55-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/4774016/crash-2020-06-13_12.44.55-client.txt)

**Comment by FoxMcloud5655** [comment]
This issue does not follow the template.

**Comment by brandon3055** [comment]
Have you removed any mods that added enchantments?
