### ISSUE TITLE
Particle generator mod

### ISSUE THREAD

**Issue by DedMaxim** [brandon3055/Draconic-Evolution#1432]
I really love your particle generator but a lot of modpacks don't iclude the mod itself because of variaty of reasons. Can you, please, create a mod that will only contain the particle generator?

Or maybe I can do that? I just really doubt that I will manage to make something working because I'm not very good with Java...

**Comment by FoxMcloud5655** [comment]
If that's something you want, I can strip it out for you, though it might take some time.

**Comment by FoxMcloud5655** [comment]
Though, it would be much easier to just disable all the items you don't need and make a custom recipe for the particle generator.

**Comment by DedMaxim** [comment]
I understand that but a separate mod gives some benefits: it's very easy to update it, since it's very small; it will eat less ram on items that will never be used in game, etc. Actually, I'm not sure about updating. Does particle genetator depend on any custom libraries?

**Comment by FoxMcloud5655** [comment]
If I recall correctly, it depends on CodeChickenLib...  Don't quote me on that, though :P  Been a while since I've been in that code.

**Comment by DedMaxim** [comment]
Just checked and CodeChickenLib is already out for 1.13, 1.14 and 1.15, so it should not cause problems. But, as I understood, you don't like my idea anyways, right?)

**Comment by FoxMcloud5655** [comment]
You never mentioned anything about porting Draconic Evolution's particle generator to a later version!  That's a completely different ball game.

I'm not saying that your idea is bad; I'm just saying that I don't want to "be a jerk" according to the license and post a mod publicly that includes 100% the work of brandon3055 under my own name.

If you really want me to make YOU a mod that YOU can use for YOURSELF that only contains what's necessary for the particle generator to function on Minecraft version 1.12.2, then I can do that for you.

Anything else would either take too much time or would break the terms that brandon3055 put in place.

**Comment by DedMaxim** [comment]
I didn't even realise that you're not Brandon, until you said it XD
Where is he btw?...

Ok, got it now. Originally, I was thinking to separate particle generator, update it to 1.15 and add to mod list on a private minecraft server. Guess it won't happen. Maybe, I'll try to learn Java a bit and code it from scratch later...

**Comment by FoxMcloud5655** [comment]
Haha!  You're fine!

Good luck with that.  I've not coded much in 1.15 yet, but it's certainly different than 1.12.2.  Brandon is actually porting Draconic Evolution to 1.15 right now, so that's where he's at.

**Comment by gigabit101** [comment]
Did someone call for @brandon3055 ?? Good luck... He's never around when he's needed

**Comment by brandon3055** [comment]
Thanks @gigabit101 btw shouldn't you be in bed at this time instead of bothering me? Just saying... xD 
The current 1.12 particle generator is a less than ideal port. At some point i want to re write it. At that point i may consider also releasing it as a separate mod but it isn't a high priority atm.

**Comment by NujnMC** [comment]
Hi there, I’m working on a 1.12.2 mod pack, just wondering if this question ever got finished? Are you able to have the particle generator as a completely separate mod, if so would it be possible to get access to it? I’d love to use it in my mod pack! 

Fingers crossed for your reply!

**Comment by FoxMcloud5655** [comment]
No, the particle generator has not been pulled out and placed in a separate mod.  It wouldn't be that hard if you wanted to pull it out yourself for 1.12.2!

**Comment by NujnMC** [comment]
I'd be more than happy to pull it out myself, would you be able to guide me in which files are needed? Obviously the ParticleGenerator, and TileParticleGenerator, and GuiParticleGenerator. Anything else?

**Comment by FoxMcloud5655** [comment]
You'd also need the recipe and the main mod loader, as well as the common proxy and the client proxy.  I haven't actually looked at the particle generator code, but I would assume that there are couple more classes dealing with the renderer.

If you do end up making this mod, please don't publish it; it would break the license agreement.  It would be fine to use for private servers and to have a separate download for interested parties, though.

**Comment by NujnMC** [comment]
Would you be willing to extract the required files etc for me? I’d credit you in the mod pack of course! I thought I could do it however I can’t

**Comment by FoxMcloud5655** [comment]
I understand.  I've gotten permission from brandon himself to create a mod that just contains the Particle Generator, so I'll be publishing it publicly here in a few days.  I'll update this issue when it's ready.

**Comment by NujnMC** [comment]
Any update yet?

**Comment by NujnMC** [comment]
Did this get forgotten about? Or is it still in the works? @FoxMcloud5655
