### ISSUE TITLE
Server crash when left clicking a player with an unbound player dislocator

### ISSUE THREAD

**Issue by shroomdog27** [brandon3055/Draconic-Evolution#1433]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.351-universal.jar
* Minecraft Forge version: forge-1.12.2-14.23.5.2854-universal.jar
* Mod Pack: (if applicable): custom

## Crash report
```
https://pastebin.com/TMr7BMBM
```

The item in question has no NBT data, as I had just freshly crafted it. The issue appears to be here 
https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/items/tools/DislocatorBound.java#L180

If I had to guess, `stack.getTag()` returns null because the item lacks any NBT data.

**Comment by FoxMcloud5655** [comment]
That sounds exactly like the problem.

Also, this is the proper link:
https://github.com/brandon3055/Draconic-Evolution/blob/9f9eb05c06e6371ddb309fb7db83727b4a0951b7/src/main/java/com/brandon3055/draconicevolution/items/tools/DislocatorBound.java#L183

The master branch is for 1.15, not 1.12.2.
