### ISSUE TITLE
Death Message

### ISSUE THREAD

**Issue by WHIINKER** [brandon3055/Draconic-Evolution#1434]
## Base information
* Minecraft version:1.7.10
* Mod version:1.7.10
* Minecraft Forge version:1.7.10
* Mod Pack: (if applicable)

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

I've server minecraft, but draconic evolution flood chat with death messages for all mobs and I want to know how to disable, please help-me

**Comment by FoxMcloud5655** [comment]
First of all, your information above is incorrect, as there is mod version or forge version that match with a Minecraft version of 1.7.10 with 1.7.10.

Secondly, Minecraft version 1.7.10 is no longer supported.

Finally, even if we were to help, without a log of the actual event, we don't know what's going on, so we cannot help.
