### ISSUE TITLE
Stingy Wireless Energy Connections

### ISSUE THREAD

**Issue by embermctillhawk** [brandon3055/Draconic-Evolution#1435]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.25.351
* Minecraft Forge version: 14.23.5.2847
* Mod Pack: [in development]

## Other mentioned mod versions
* Actually Additions: 1.12.2-r151
* Immersive Engineering: 0.12-98
* Industrial Foregoing: 1.12.13
* NuclearCraft: 2.18u-1.12.2
* RFTools: 1.12-7.73
* Thermal Expansion: 5.5.7.1
* Mekanism Generators: 1.12.2-9.8.3.390
* Cyclic: 1.20.3
* Ender IO: 5.2.57

During the process of developing a modpack, I have found some oddly stingy aspects of the DE wireless energy network.
Not all of the mods mentioned have issues; some of them are included simply as a sanity check that I'm not completely stupid and don't know how to get the wireless network to work at all.

Also I recognize that probably some of these are not DE's fault; I would like advisement as to which so they may be contacted appropriately.

Actually Additions, Industrial Foregoing, NuclearCraft, Thermal Expansion, Cyclic, Mekanism don't seem to have any issues outside of minor quirks which are easily worked around.

Immersive Engineering, the Thermoelectric Generator cannot be connected to the network. It says "That tile cannot supply energy on that side!", regardless of the side clicked on.

RFTools, the Coal Generator gives the same error, "That tile cannot supply energy on that side!".

Ender IO, no generator can be connected to the network, with a different message, "That is not a valid device!"
Furthermore, while a wireless output can be connected to an Ender IO capacitor, wireless input cannot be connected to an Ender IO capacitor, with the message "That is not a valid device!", even with setting a given side of the capacitor to output mode.

This may be related to #1129 but that got fixed forever ago. It seems something else has changed since then that broke compatibility again, though.

EDIT: Ender IO machines such as the SAG Mill have no issues connecting to a wireless output. It's only the generators and capacitors which are having issues connecting to wireless input.

**Comment by KirikaAetheria** [comment]
have you checked whether the devices will link regardless of "valid device" message? for some reason, woot's mob farm multiblock structures have the same issue. when connecting a wireless crystal to a woot factory's powercell, it'll say it is not a valid device. but regardless, the link is still formed, and the factory will still be provided with power

**Comment by brandon3055** [comment]
Ok so if this is what i think it is then it isn't really anyone's 'fault' Its just some energy suppliers handle things differently. Pretty much all energy suppliers with themselves 'push' energy to an adjacent block. This is how most energy transfer works. However its also in most cases possible for another block to 'pull' energy from a supplier if the supplier allows it. And this is how the wireless crystals work when in input mode. They obviously cant rely on the source block pushing power into the crystal so instead the crystal needs to pull power from the source block and this may not be supported by all source blocks. It really should be but this isn't a common use case so i'm sure it gets overlooked by some modders.

**Comment by embermctillhawk** [comment]
> 
> 
> have you checked whether the devices will link regardless of that "valid device" message? for some reason, woot's mob farm multiblock structures have the same issue. when connecting a wireless crystal to a woot factory's powercell, it'll say it is not a valid device. but regardless, the link is still formed, and the factory will still be provided with power

Double-checked. No power transfer is occurring.



> 
> 
> Ok so if this is what i think it is then it isn't really anyone's 'fault' Its just some energy suppliers handle things differently. Pretty much all energy suppliers with themselves 'push' energy to an adjacent block. This is how most energy transfer works. However its also in most cases possible for another block to 'pull' energy from a supplier if the supplier allows it. And this is how the wireless crystals work when in input mode. They obviously cant rely on the source block pushing power into the crystal so instead the crystal needs to pull power from the source block and this may not be supported by all source blocks. It really should be but this isn't a common use case so i'm sure it gets overlooked by some modders.

Noted. Attaching an IO crystal works fine for network, but the wireless crystals cant be connected directly I guess. At least not for everything. Thank you.

**Comment by brandon3055** [comment]
Correct. Wireless crystals do not allow 'direct' connections. Even if you place a crystal directly next to the source / sink it will still be a 'wireless' connection.
