### ISSUE TITLE
Portal client crash

### ISSUE THREAD

**Issue by KirikaAetheria** [brandon3055/Draconic-Evolution#1436]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.351-universal
* Minecraft Forge version: 1.12.2 - 14.23.5.2854

## Crash report
```
https://pastebin.com/UDER3CBc
```

--

![2020-06-26_01 41 43](https://user-images.githubusercontent.com/61053558/85809020-8088c300-b74e-11ea-9a26-7823213bca43.png)

When right-clicking on a black portal tile, the game crashes immediately. This happens regardless of whether the portal is linked through bound dislocators or is just a simple one-way portal. This issue is limited to the client, the server suffers no effects from this crash. Also, this only happens on the portal tiles themselves; right-clicking on the receptacle works as intended.

![2020-06-26_01 37 29](https://user-images.githubusercontent.com/61053558/85809375-9a76d580-b74f-11ea-89ad-d5cee9f162fc.png)

VanillaFix reported that Reskillable might have something to do with it.

Feel free to let me know if you need any further information

EDIT: Loop issue moved to  #1437

**Comment by FoxMcloud5655** [comment]
Please separate out these two issues.  I'll only address the first; the portal client crash.

This looks like a mod compatibility issue, as Reskillable expects the TilePortalClient to have a right-clickable action:
```
codersafterdark.reskillable.base.LevelLockHandler.rightClickBlock(LevelLockHandler.java:334)
```
I'm not sure at this point if something can be done on DE's side to help with this or not, but that's my initial hunch.

**Comment by KirikaAetheria** [comment]
Will do
