### ISSUE TITLE
Getting stuck in a portal loop while teleporting between two different dimensions

### ISSUE THREAD

**Issue by KirikaAetheria** [brandon3055/Draconic-Evolution#1437]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.351-universal
* Minecraft Forge version: 1.12.2 - 14.23.5.2854

## Crash report
```
N/A
```

![2020-06-26_01 46 33](https://user-images.githubusercontent.com/61053558/85809248-24726e80-b74f-11ea-84e3-612076cfad3b.png)

When making a pair of bound dislocator portals such as this, entering one of them will cause you to get stuck on an infinite teleport loop; you will teleport back the -moment- you load into the new area, over and over again. I imagine we are placed directly above or inside the other teleport tile and thus interact with it immediately.

**Comment by brandon3055** [comment]
This should not be possible for 2 reasons. 
First of all when you teleport using bound portals the portal at the receiving end is disabled until you exit the portal specifically to prevent this exact thing.
And secondly even if that fails or you have 2 regular dislocators teleporting to each other there is a 10 tick cool down on the portals so you would be teleported to the destination then immediately back to the origin where there would be a 10 tick delay before you are teleported again. This is more than enough time to fall out of the portal.
I thought maybe there is a bug with horizontal portals but i have not been able to reproduce this issue.

**Comment by KirikaAetheria** [comment]
I see. Back when I first posted this, I tried twice just to make sure, and it happened both times. The dislocators were connected to two different dimensions, would the loading time from switching between dimensions be a factor here?

**Comment by KirikaAetheria** [comment]
I was going to put away this server and thought I'd log back in to test and properly record the issue. When trying to teleport between bound dislocators in the same dimension, everything happens exactly as you described, and the portal deactivates for a short while after you arrive at the destination: https://www.youtube.com/watch?v=SK27M0Tm34k

However, when traveling between portals placed in different dimensions, the loading time does indeed seem to mess with the plan. By the time you load into the new dimension the portal is already activate again, causing you to be stuck in a loop: https://www.youtube.com/watch?v=badGDPTggJ8

So that mystery's solved. I'll update the title accordingly, hopefully these examples will adequately demonstrate the issue
