### ISSUE TITLE
Tier 8 Draconic Energy Storage is causing server lag when loaded by chunk loader but not by a player

### ISSUE THREAD

**Issue by quantumSuperposition** [brandon3055/Draconic-Evolution#1438]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.25.351
* Minecraft Forge version: 14.23.5.2847
* Mod Pack: Project Ozone 3

## Issue
Tier 8 Draconic Energy Storage ball is causing some serious server side lag, making the TPS drop down to the low hundreds (around 15%-30% according to CoFH) when being loaded by a chunk loader and not a player.

## Steps to Reproduce
This was discovered on a server, I have not yet tested it on client only. As well, the Draconic Energy ball was being loaded by the ChickenChunks Chunk Loader.

1. Create server
2. Make tier 8 Draconic energy ball
3. Chunk load it
4. Have the player unload it (We tested this by going into another dimension. I don't know if this is any different than just going far away and haven't tested it yet)

**Comment by quantumSuperposition** [comment]
**DISREGARD THIS ISSUE
Turns out I was being a really big idiot and blamed the mysterious lag on the wrong mod. Turns out the lag was caused by my dumb self. REALLY SORRY ABOUT THIS.

**Comment by FoxMcloud5655** [comment]
Understandable.  I've done the same thing, so no worries :P
