### ISSUE TITLE
Chaos Guardian Crystals Invulnerable to Damage

### ISSUE THREAD

**Issue by gerethd** [brandon3055/Draconic-Evolution#1439]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.20.333
* Minecraft Forge version: 14.23.5.2821
* Mod Pack: (if applicable) Direwolf20 1.12.2

When fighting the chaos guardian crystals at times are invulnerable to damage making the guardian impossible to kill as anytime any damage is done to the dragon a crystal will become active and will take a single hit and then become immune to subsequent damage for an indeterminate amount of time. Sometimes hitting the crystal from a different angle helps but not always.

**Comment by brandon3055** [comment]
Yes. When you hit a crystal a shield goes up around that crystal indicated by the red beam that appears when you damage a crystal. You must then wait for that shield to go down before you can hit the crystal again.
Alternatively if you can deal at least 50 hearts of damage per hit it is possible to one shot the crystals. .
