### ISSUE TITLE
Can't charge energy core

### ISSUE THREAD

**Issue by Igor006** [brandon3055/Draconic-Evolution#1440]
* Minecraft version: 1.12.2
* Mod version: 2.3.25.351
* Minecraft Forge version: 14.23.5.2854
* Mod Pack: my own
I can't for some reason charge energy core i tried for a really long time but its not working.
Here is my video with setup on google disk.
https://drive.google.com/file/d/1VK0YToHA5jAfqYebLmMK6zI_Eaa1fujs/view?usp=sharing
.

**Comment by FoxMcloud5655** [comment]
Two things:

First, check your draconic wireless energy crystals and make sure that their inputs and outputs are set correctly.  the input and output displayed in the lower right-hand corner of the screen is from the crystals perspective, so you input from your energy source and output to the energy pylon.

Secondly, make sure the pylons are set to input energy, not to export energy.

**Comment by Igor006** [comment]
I found out on wikipedia that energy pylons needed to be lower and it worked thanks for fast respond
