### ISSUE TITLE
Cascading lag

### ISSUE THREAD

**Issue by Tombstone1973** [brandon3055/Draconic-Evolution#1441]
Cascading lag caused by this mod causes my server to crash. I can't post the crash file as I'm not home, and won't be till tomorrow. I just want this issue solved.

**Comment by FoxMcloud5655** [comment]
I assume you're talking about world generation lag?  We can't really do anything without the crash report, so we'll wait on that.

**Comment by Tombstone1973** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LevelUpCore (levelup2-1.4.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 7/19/20 8:08 PM
Description: Exception ticking world

java.lang.ClassCastException: com.brandon3055.draconicevolution.entity.EntityGuardianCrystal cannot be cast to net.minecraft.entity.EntityLiving
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.getEntity(CraftEntity.java:232)
	at net.minecraft.entity.Entity.getBukkitEntity(Entity.java:124)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:308)
	at net.minecraft.world.World.spawnEntity(World.java:1435)
	at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1361)
	at net.minecraft.world.World.func_72838_d(World.java:1411)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1355)
	at com.brandon3055.draconicevolution.world.ChaosWorldGenHandler.generateObelisk(ChaosWorldGenHandler.java:229)
	at com.brandon3055.draconicevolution.world.ChaosWorldGenHandler.generateObelisks(ChaosWorldGenHandler.java:211)
	at com.brandon3055.draconicevolution.world.ChaosWorldGenHandler.generateStructures(ChaosWorldGenHandler.java:172)
	at com.brandon3055.draconicevolution.world.ChaosWorldGenHandler.generateChunk(ChaosWorldGenHandler.java:48)
	at com.brandon3055.draconicevolution.world.DEWorldGenHandler.addOreGen(DEWorldGenHandler.java:73)
	at com.brandon3055.draconicevolution.world.DEWorldGenHandler.generate(DEWorldGenHandler.java:53)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1190)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1149)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:169)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:175)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.getEntity(CraftEntity.java:232)
	at net.minecraft.entity.Entity.getBukkitEntity(Entity.java:124)
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:308)
	at net.minecraft.world.World.spawnEntity(World.java:1435)
	at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1361)
	at net.minecraft.world.World.func_72838_d(World.java:1411)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1355)
	at com.brandon3055.draconicevolution.world.ChaosWorldGenHandler.generateObelisk(ChaosWorldGenHandler.java:229)
	at com.brandon3055.draconicevolution.world.ChaosWorldGenHandler.generateObelisks(ChaosWorldGenHandler.java:211)
	at com.brandon3055.draconicevolution.world.ChaosWorldGenHandler.generateStructures(ChaosWorldGenHandler.java:172)
	at com.brandon3055.draconicevolution.world.ChaosWorldGenHandler.generateChunk(ChaosWorldGenHandler.java:48)
	at com.brandon3055.draconicevolution.world.DEWorldGenHandler.addOreGen(DEWorldGenHandler.java:73)
	at com.brandon3055.draconicevolution.world.DEWorldGenHandler.generate(DEWorldGenHandler.java:53)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1190)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1149)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:169)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:175)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:432)

-- Affected level --
Details:
	Level name: DIM1
	All players: 1 total; [EntityPlayerMP['LordWhisky'/239024, uuid='b20d43bf-34e8-4029-bd29-6f25e7653c8d', l='DIM1', x=-9.99, y=100.00, z=9840.23, cx=-1, cd=615, tl=2371357, v=true, d=false](LordWhisky at -9.99371057905249,100.0,9840.226738458363)]
	Chunk stats: ServerChunkCache: 1683 Drop: 0
	Level seed: 6722421647202402310
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6412351 game time, 6412351 day time
	Level dimension: 1
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 44e91f6
	Operating System: Linux (amd64) version 5.4.0-39-generic
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 27573058200 bytes (26295 MB) / 33451671552 bytes (31902 MB) up to 33451671552 bytes (31902 MB)
	JVM Flags: 2 total; -Xmx32000M -Xms32000M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version                  | Source                                             | Signature                                |
	|:------ |:------------------------ |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                      | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                      | 8.0.99.99                | Magma-44e91f6-server.jar                           | None                                     |
	| LCHIJA | forge                    | 14.23.5.2854             | Magma-44e91f6-server.jar                           | None                                     |
	| LCHIJA | openmodscore             | 0.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | bspkrscore               | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar             | None                                     |
	| LCHIJA | treecapitator            | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar              | None                                     |
	| LCHIJA | jei                      | 4.15.0.296               | jei_1.12.2-4.15.0.296.jar                          | None                                     |
	| LCHIJA | abyssalcraft             | 1.10.1                   | AbyssalCraft-1.12.2-1.10.1.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | chisel                   | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LCHIJA | mantle                   | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | thaumcraft               | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCHIJA | twilightforest           | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar      | None                                     |
	| LCHIJA | tconstruct               | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCHIJA | acintegration            | 1.11.2                   | AbyssalCraft Integration-1.12.2-1.11.2.jar         | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | aether_legacy            | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
	| LCHIJA | codechickenlib           | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ancientwarfare           | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCHIJA | redstoneflux             | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.772         | ancientwarfare-1.12.2-2.7.0.772.jar                | None                                     |
	| LCHIJA | bibliocraft              | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | biomesoplenty            | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCHIJA | guideapi                 | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LCHIJA | bloodmagic               | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
	| LCHIJA | bloodmoon                | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | brandonscore             | 2.4.18                   | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
	| LCHIJA | chunkpregenerator        | 2.1                      | Chunk+Pregenerator+V1.12-2.3.jar                   | None                                     |
	| LCHIJA | conarm                   | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | customnpcs               | 1.12                     | CustomNPCs_1.12.2-(05Jul20).jar                    | None                                     |
	| LCHIJA | props                    | 2.6.3                    | Decocraft-2.6.3_1.12.2.jar                         | None                                     |
	| LCHIJA | draconicevolution        | 2.3.25                   | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
	| LCHIJA | dungeontactics           | DT-0.16.8                | DungeonTactics-1.12.2-0.16.8.jar                   | None                                     |
	| LCHIJA | ebwizardry               | 4.2.11                   | ElectroblobsWizardry-4.2.11-MC1.12.2.jar           | None                                     |
	| LCHIJA | extragems                | 1.2.8                    | ExtraGems-1.12.2-(v.1.2.8).jar                     | None                                     |
	| LCHIJA | fastleafdecay            | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| LCHIJA | forgelin                 | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHIJA | ichunutil                | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | hats                     | 7.1.1                    | Hats-1.12.2-7.1.1.jar                              | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | waila                    | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | llibrary                 | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire               | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
	| LCHIJA | infernalmobs             | 1.7.6                    | InfernalMobs-1.12.2.jar                            | None                                     |
	| LCHIJA | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | journeymap               | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCHIJA | earthenbounty            | 2.1.6                    | just_a_few_more_ores-2.1.6.jar                     | None                                     |
	| LCHIJA | levelup2                 | ${version}               | levelup2-1.4.4.jar                                 | None                                     |
	| LCHIJA | libraryex                | 1.1.3                    | LibraryEx-1.12.2-1.1.3.jar                         | None                                     |
	| LCHIJA | megaloot                 | 0.2.40                   | megaloot-1.12.2-0.2.40.jar                         | None                                     |
	| LCHIJA | netherex                 | 2.1.8                    | NetherEx-1.12.2-2.1.8.jar                          | None                                     |
	| LCHIJA | yurtmod                  | 9.5.2                    | NomadicTents-1.12.2-9.5.2.jar                      | None                                     |
	| LCHIJA | recipehandler            | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
	| LCHIJA | nei                      | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | openmods                 | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks               | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | patchouli                | 1.0-21                   | Patchouli-1.0-21.jar                               | None                                     |
	| LCHIJA | progressivebosses        | 1.5.4                    | ProgressiveBosses-1.5.4-mc1.12.x.jar               | None                                     |
	| LCHIJA | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| LCHIJA | subcommonlib             | 1.2.0.1                  | subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
	| LCHIJA | rpginventory             | 1.12.2                   | rpginventory-1.12-5.3.0.0.jar                      | None                                     |
	| LCHIJA | silentlib                | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                    | None                                     |
	| LCHIJA | scalinghealth            | 1.3.37                   | ScalingHealth-1.12.2-1.3.42+147.jar                | None                                     |
	| LCHIJA | scalingwealth            | 1.0.1                    | ScalingWealth-1.0.1.jar                            | None                                     |
	| LCHIJA | somanyenchantments       | 0.4.3                    | somanyenchantments V0.4.31.jar                     | None                                     |
	| LCHIJA | tails                    | 1.12-1.10.0              | Tails-1.12-1.10.0.jar                              | None                                     |
	| LCHIJA | tfspellpack              | 1.0.1                    | TFSpellPack-1.0.1-MC1.12.2.jar                     | None                                     |
	| LCHIJA | tinkertoolleveling       | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | travelersbackpack        | 1.0.33                   | TravelersBackpack-1.12.2-1.0.33.jar                | None                                     |
	| LCHIJA | vampirism                | 1.6.2                    | Vampirism-1.12.2-1.6.2.jar                         | None                                     |
	| LCHIJA | teamlapen-lib            | 1.6.2                    | Vampirism-1.12.2-1.6.2.jar                         | None                                     |
	| LCHIJA | wawla                    | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones                | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                         | None                                     |
	| LCHIJA | worldedit                | 6.1.10                   | worldedit-forge-mc1.12.2-6.1.10-dist.jar           | None                                     |
	| LCHIJA | xlfoodmod                | 1.12.2-1.9.2             | XL-Food-Mod-1.12.2-1.9.2.jar                       | None                                     |
	| LCHIJA | vt                       | 1.12.2-1.5.6             | VanillaTweaks-1.12.2-1.5.6.jar                     | None                                     |
	| LCHIJA | betteranimalsplus        | 9.0.1                    | betteranimalsplus-1.12.2-9.0.1.jar                 | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LevelUpCore (levelup2-1.4.4.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 75; [EntityPlayerMP['LordWhisky'/239024, uuid='b20d43bf-34e8-4029-bd29-6f25e7653c8d', l='DIM1', x=-9.99, y=100.00, z=9840.23, cx=-1, cd=615, tl=2371357, v=true, d=false](LordWhisky at -9.99371057905249,100.0,9840.226738458363)]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Tombstone1973** [comment]
[crash-2020-07-19_20.08.16-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/4949363/crash-2020-07-19_20.08.16-server.txt)

**Comment by Tombstone1973** [comment]
Any idea @FoxMcloud5655

**Comment by FoxMcloud5655** [comment]
It certainly looks like DE's fault, but I'm having trouble replicating it.  Still looking into it; I'll update if I find anything.

**Comment by brandon3055** [comment]
This is a bukkit issue. Its trying to cast EntityGuardianCrystal to EntityLiving. But EntityGuardianCrystal does not extend EntityLiving. However it does extend EntityLivingBase which may be why bukkit is getting confused. But regardless bukkit should not assume that any class extending EntityLivingBase is also an EntityLiving. They should be instanceof checking for EntityLiving.

**Comment by FoxMcloud5655** [comment]
Thanks for the clarification.  No wonder I couldn't reproduce this!

**Comment by Tombstone1973** [comment]
> This is a bukkit issue. Its trying to cast EntityGuardianCrystal to EntityLiving. But EntityGuardianCrystal does not extend EntityLiving. However it does extend EntityLivingBase which may be why bukkit is getting confused. But regardless bukkit should not assume that any class extending EntityLivingBase is also an EntityLiving. They should be instanceof checking for EntityLiving.

So, is there a fix for it yet?
