### ISSUE TITLE
Can't get reactor to produce more energy

### ISSUE THREAD

**Issue by Igor006** [brandon3055/Draconic-Evolution#1442]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.25.351
* Minecraft Forge version: 1.12.2 - 14.23.5.2854
* Mod Pack: my own

I can't for some odd reason get reactor to be hotter its been like 1 hour and stats haven't changed at all. Here are some screenshots of my set up.
## Screenshots
![image](https://user-images.githubusercontent.com/34749822/88304282-58b65c00-cd08-11ea-93f9-63c40d33130e.png)
![image](https://user-images.githubusercontent.com/34749822/88304346-708de000-cd08-11ea-8dce-c7666c25640e.png)
![image](https://user-images.githubusercontent.com/34749822/88304382-797eb180-cd08-11ea-80f0-4defbeadd23e.png)
![image](https://user-images.githubusercontent.com/34749822/88304450-93b88f80-cd08-11ea-88e4-61f083e56ce2.png)

**Comment by Igor006** [comment]
ok got it to work it was not issue with draconic evolution sry

**Comment by FoxMcloud5655** [comment]
Was gonna say, I just tested this not too long ago and made sure everything was working as intended!

What ended up being the problem?

**Comment by Igor006** [comment]
the dimensional transceiver
