### ISSUE TITLE
Invalid Core when upgrading Energy Core tier.

### ISSUE THREAD

**Issue by hyperionterror** [brandon3055/Draconic-Evolution#1444]
## Base information
* Minecraft version: 1.12.2
* Mod version: Unknown
* Minecraft Forge version:
* Mod Pack: FTB Presents Direwolf20 Version: 2.5.0

No crash occurs during gameplay. When attempting to build Tier 4 Energy Core, an error occurs stating, "Core: Invalid Error At: x:396, y:52, z:207 Expected: draconicevolution:draconium_block"

This has happened every time I've upgraded the energy core. The other instances appear to correct themselves automatically after a while. It is not correcting itself this time.
I have the correct blocks necessary (26 Redstone Blocks and 54 Draconium Blocks).
Stabilizers are valid.
Nothing is in the way of the core when building. No unseen blocks.
Blocks were built in faulted position (x,y,z) and destroyed to make sure nothing was there.
![Screenshot (52)](https://user-images.githubusercontent.com/26046467/88856805-ffd44100-d1a9-11ea-86ea-8c1ee999803f.png)

**Comment by hyperionterror** [comment]
I found the Forge Version.
forge-14.23.5.2821

**Comment by hyperionterror** [comment]
Manually placing blocks allows the user to select a stabilizer and successfully activate the core. This just became an ease of use issue rather than a blocking issue (because I'm dumb).

**Comment by FoxMcloud5655** [comment]
Let me ask this; do you have Railcraft installed?

**Comment by FoxMcloud5655** [comment]
Interesting.  I don't know what it could be other than blocklag, but I'll take a look at the pack when I get some time and see if there's anything that could be interfering.
