### ISSUE TITLE
Make autofeed compatible with Botania

### ISSUE THREAD

**Issue by FolfyBlue** [brandon3055/Draconic-Evolution#1445]
[Botania](https://github.com/Vazkii/Botania) adds an item named "[The Fruit of Grisaia](https://ftb.gamepedia.com/The_Fruit_of_Grisaia)" which is basically an apple that you can eat infinitely to regain hunger. However, the draconic helmet's "autofeed" option doesn't allow it to use said fruit, would it be possible to make the both compatible?

**Comment by FoxMcloud5655** [comment]
The Fruit of Grisaia is not actually a real food item.  It consumes Mana to fill your hunger bar; you can see this if you as soon as you right click.  It will would take Botania adding itself as a proper food item and DE not permanently consuming it.
