### ISSUE TITLE
Can't upgrade items through fusion crafting

### ISSUE THREAD

**Issue by Igor006** [brandon3055/Draconic-Evolution#1447]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.25.351
* Minecraft Forge version: 1.12.2 - 14.23.5.2854
* Mod Pack: my own

When i try to upgrade items like draconic bow it doesn't let me to do so.
Here are some screenshots (and incase you ask i have draconic additions installed)
## Screenshots
![image](https://user-images.githubusercontent.com/34749822/89278595-9d19f400-d646-11ea-8d15-5413c19fab67.png)
![image](https://user-images.githubusercontent.com/34749822/89278615-a4410200-d646-11ea-812e-b9c69328f9f8.png)

**Comment by FoxMcloud5655** [comment]
This is not a Draconic Evolution bug.  The latest build of Draconic Additions breaks upgrades.  Please revert and close this issue.
