### ISSUE TITLE
1.7.10 Enchant books from other mods are not dragged

### ISSUE THREAD

**Issue by relogb** [brandon3055/Draconic-Evolution#1449]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.7.10-1.0.2h
* Minecraft Forge version: 1.7.10
When I try to transfer it to a pickaxe, let's say auto-melting, does not work, even after configuring the config.
The setting itself is attached below
`"magicid's" {
    I:"Enchant id" <
        180
        46
        45
        101
     >
}`

**Comment by FoxMcloud5655** [comment]
Sorry, but 1.7.10 is no longer supported :(
