### ISSUE TITLE
Search Draconic Evolution Permission for a permission mod

### ISSUE THREAD

**Issue by Pilou26021** [brandon3055/Draconic-Evolution#1450]
Hi everyone,
Can somebody find the permission from draconic evolution ?
Thanks.

**Comment by FoxMcloud5655** [comment]
The LICENCE file contains all the permissions you need.

https://github.com/brandon3055/Draconic-Evolution/blob/master/LICENSE

**Comment by Pilou26021** [comment]
Hi,
It's not that permission. I search the permission for a command. For a permission plugins, like luckperms.

**Comment by MJDeveloping** [comment]
The permissions would be "draconicevolution.command.de_upgrade" and "draconicevolution.command.de_reload_custom_fusion"... If you're going to try running a server, I recommend you learn how to use LuckPerm's Verbose. it will save you many hours... Luck did a excellent job on that.
