### ISSUE TITLE
Problem with improving tools

### ISSUE THREAD

**Issue by Hellyclaster** [brandon3055/Draconic-Evolution#1451]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.25.351
* Minecraft Forge version: 14.23.5.2854
* Mod Pack: own

Tools don't improve: https://youtu.be/LFqWimfqlNk

**Comment by FoxMcloud5655** [comment]
This is not an issue with Draconic Evolution.  It's with Draconic Additions, and the update is already pulled due to this bug.  Please downgrade DA for now.

**Comment by Hellyclaster** [comment]
thx! its work
