### ISSUE TITLE
Damage taken from using regular Dislocator bypasses all forms of protection

### ISSUE THREAD

**Issue by James103** [brandon3055/Draconic-Evolution#1452]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.20.333
* Minecraft Forge version: 14.23.5.2821
* Mod Pack: FTBPresentsDirewolf20112-2.5.0-1.12.2.zip + VanillaFix 1.0.10

## The problem
When you use a regular Dislocator (not a Bound Dislocator or Advanced Dislocator), you lose 2 HP, as expected.

However, when you have armor enchanted with Feather Falling and/or Draconic armor (both of which reduce/eliminate fall damage which is inflicted from ender pearl teleportation), the 2 HP of damage taken from using a regular Dislocator bypasses it all, since it directly sets your health to your previous HP minus 2.
https://github.com/brandon3055/Draconic-Evolution/blob/82c8244b6aedf49d11c521ecbe05c98e3e76be96/src/main/java/com/brandon3055/draconicevolution/items/tools/Dislocator.java#L64-L67

I suggest that using a regular Dislocator should instead deal 2 HP of chaos damage (configurable), which allows Draconic armor to absorb the damage using it's shield at the cost of RF instead of HP.

**Comment by brandon3055** [comment]
I will just add that this is the intended behavior. It's not really explained anywhere but the basic dislocator effectively uses your life force as fuel to power the teleport. Though it does feel a little redundant considering it also consumes durability from the dislocator so I am considering removing the health cost in 1.16.
