### ISSUE TITLE
DraconicEvolition 1.7.10 Mod Does not Affects The End — no Dust, no Comets, no Chaos

### ISSUE THREAD

**Issue by AykaSova** [brandon3055/Draconic-Evolution#1454]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.0.2h
* Minecraft Forge version: 1614
* Mod Pack: (if applicable)
Using Multiword Plugin.

Trying several times to delete all worlds on my server for regenerating them. 
There is dracionium dust in normal world, in nether, in deepdark — but nothig in The End: no dust, no comets, no Chaos Gardian Island.

All *.cfg seems to be OK
I:"Chaos Island Separation"=10000
B:"Disable Guardian Crystal Respawn"=false
B:"Disable Item Lore"=false
B:"Disable Ore Spawn (End)"=false
B:"Disable Ore Spawn (Nether)"=false
B:"Disable Ore Spawn (Overworld)"=false
S:"Disabled Blocks & Items" <
     >
I:"Ender Comet Rarity"=1000
B:"Generate Chaos Islands"=true
I:"Ore gen dimension blacklist" <
     >

Should it be specific seed for The End creation or something else outside the configs?
Players start leaving my project :((

**Comment by FoxMcloud5655** [comment]
Minecraft version 1.7.10 is no longer supported.
