### ISSUE TITLE
Draconic evolution + broken spawner

### ISSUE THREAD

**Issue by Jojo5480** [brandon3055/Draconic-Evolution#1457]
## Base information
* Minecraft version: 1.12.2
* Mod version: lastest
* Minecraft Forge version:
* Mod Pack: Chroma technology 1.3.1

There is no crash but i've spawned 2 chaos guardian on my overworld with broken spawners + chaos core. 2 dragons have spawned, i killed them but they wont dispawn and i get a white screen.
![2020-09-11_05 03 47](https://user-images.githubusercontent.com/70121117/92851862-55794b80-f3ee-11ea-987f-3490519632a8.png)

**Comment by FoxMcloud5655** [comment]
Spawning boss mobs forcefully with mob spawner is not supported.  There's a reason why it's disabled in the config.

**Comment by Jojo5480** [comment]
I didn't change anything in the pack. 

If u can't help stop comment for saying nothing.

**Comment by covers1624** [comment]
No need to be rude, @FoxMcloud5655 is correct, Spawning boss mobs are disabled by default in the config, either the Modpack creator or yourself has changed the config.

You will need to kill the dragons with Console commands, and don't do that in the future.

**Comment by brandon3055** [comment]
Try this. `/kill @e[type=draconicevolution:chaosguardian]` 
The guardian should not break like this in the overworld but something in your pack is probably breaking it. I suggest avoiding trying to spawn guardians with spawners.

**Comment by Jojo5480** [comment]
I already tried to kill them by commands but nothing happens. Thooses dragons stay here like that.

**Comment by brandon3055** [comment]
You might have to use MCEdit to delete them.
