### ISSUE TITLE
Draconic Reactor Not Accepting Power

### ISSUE THREAD

**Issue by Dr-DaNk** [brandon3055/Draconic-Evolution#1459]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.25.351
* Minecraft Forge version: 14.23.5.28
* Mod Pack: (if applicable): Enigmatica 2

I'm trying to get the Draconic Reactor starting and it's just not working. I've got a Quantum Entangloporter set up literally on the energy injector and everything is set up correctly. When I press the startup button, the status changes from offline to warming up, then nothing. The core takes in NO POWER. I've verified that the quantum entangloporter is set up properly and outputting power. I've got it on a separate channel feeding directly from my tier 7 energy core. I can't find any reason why this isn't working.

**Comment by FoxMcloud5655** [comment]
First of all, I'm going to assume your forge version is 2847, as the last bit is cut off there.

Secondly, is this hooked up to a flow regulator of some sort?  Kinda need that when starting up the core.

**Comment by Dr-DaNk** [comment]
Yeah, the DE Regulators are the only things between my Quantum Entangloporters and the reactor Stabilizer/Energy Injector.

**Comment by Dr-DaNk** [comment]
I've done this like a million times in 1.7.10 with no problems but I just can't get it to work in 1.12.2
