### ISSUE TITLE
The Draconic Bow's "Explosive" Fire Mode defective

### ISSUE THREAD

**Issue by zzApotheosis** [brandon3055/Draconic-Evolution#146]
Minecraft 1.7.10
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1492
Optifine Optifine_1.7.10_HD_C1
Draconic-Evolution-1.7.10-1.0.2-Snapshot_3

I updated DE in my private modpack to 1.0.2-Snapshot_3 before I acquired the Draconic Bow, so I don't know if this issue has been around in 1.0.1, but in this version, the Draconic Bow doesn't fire at all when it's in its "Explosive" fire mode. I had gunpowder and arrows (and also tried with enchantment Infinity I) and it didn't work. I tried using the mod with only CoFHCore, Thermal Foundation, and Brandon's Core and that didn't work, so there are no other mods conflicting with it. I tested it adequately and I'm certain that it's a bug in the latest snapshot. On the bright side, I can report that the "Devastation" fire mode worked on Creative Mode.

**Comment by brandon3055** [comment]
How long did you hold right click? Explosive mode has a really long draw time.

**Comment by zzApotheosis** [comment]
Oh, my report was premature... Thanks for the heads up. I'm gonna go sulk now (ノಠ益ಠ)ノ彡┻━┻

**Comment by brandon3055** [comment]
I plan to make the bows very configurable in the future (ether after or towards the end of the 1.0.2 update) so you will be able to adjust the draw speed and a few other things after that.
