### ISSUE TITLE
[1.12.2] Question about disabling the stabilized spawner

### ISSUE THREAD

**Issue by ghost** [brandon3055/Draconic-Evolution#1466]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.351-universal

## Question
Hello. It is necessary to disable the creation of a stabilized spawner I can't find information on this. How can this be done? I tried to set the parameter "B: draconic_spawner = false" in the configs. No result was given. Spawner creation has not been disabled.

**Comment by felipeolivera** [comment]
Alguém saber pq não tem draconium na dimensão deep dark do meu mundo, tem todos os outros minerios

**Comment by FoxMcloud5655** [comment]
Most likely because the dimension is not whitelisted in the list of allowed dimensions to spawn in.  If you need help, you can always visit the Draconic Evolution discord!
