### ISSUE TITLE
Chaos Guardian healing crystals do not take damage from melee attacks when the mod "Tough as Nails" is installed

### ISSUE THREAD

**Issue by KirikaAetheria** [brandon3055/Draconic-Evolution#1468]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.353-universal
* Minecraft Forge version: 1.12.2 - 14.23.5.2854

## Crash report
```
N/A
```
Full Modlist: 
-CodeChickenLib-1.12.2-3.2.3.358-universal
-BrandonsCore-1.12.2-2.4.19.214-universal
-RedstoneFlux-1.12-2.1.1.1-universal
-Draconic-Evolution-1.12.2-2.3.27.353-universal
-ToughAsNails-1.12.2-3.1.0.141-universal

When Tough as Nails (https://www.curseforge.com/minecraft/mc-mods/tough-as-nails) is installed, melee strikes on the Chaos Guardian healing crystals will cause zero damage. The attack is still registered, since the crystal's shield is raised after the strike, but no damage whatsoever is dealt. Attacking the crystals with long-range weapons such as bows works as usual.

Tough as Nails has been discontinued, and I'm not sure if it's possible to fix this bug on DE's end at all, but if nothing else the mod can be added to the incompatibility list.

**Comment by FoxMcloud5655** [comment]
I was going to say that Tough as Nails is a discontinued mod, but you already said that.  I don't think the issue can be fixed easily, but it's worth at least looking at.

Soon enough, however, Draconic Evolution 3 will be coming out, and will render this issue useless.

**Comment by KirikaAetheria** [comment]
Oh that's great to hear, Tough as Nails is a buggy mess but I do enjoy the added early-game challenge it provides. I wasn't really expecting this bug to be fixed or to become a non-issue, so I was kind of bummed out having to remove the mod from future playthroughs.

Incidentally, would it be alright if you let me in on why this won't be an issue anymore once DE3 comes out? I'm actually having another long-standing issue with the crystals, the same as reported in https://github.com/brandon3055/Draconic-Evolution/issues/1322 , and was planning to look into which mod may be at fault later today. But if the crystals are going to be removed or something along those lines, I might as well save the time.

**Comment by FoxMcloud5655** [comment]
The entire chaos fight is being redone, but I can't give specifics yet on what that will entail.  It will also be ported to 1.15, then 1.16 very shortly after, so it wouldn't be compatible with Tough as Nails anyways.

**Comment by KirikaAetheria** [comment]
I see, that's understandable. In that case looking into that other bug isn't worthwhile, right?

People playing in 1.15 and 1.16 won't be able to use TaN of course, but for those who are playing in 1.12.2 it's a nice option. Will DE3 come out on 1.12.2 as well, or is it intended to be for 1.15+ only?

**Comment by FoxMcloud5655** [comment]
1.15 and 1.16 only.  Probably 1.17 as well when it comes out next year.

**Comment by KirikaAetheria** [comment]
Got it, in that case I might as well hunt down that other bug. Even if it might not be fixed as the dev team's focus shifts to DE3's release, at least those who stay in 1.12.2 will know which mod is incompatible.

Thank you very much for answering all those questions Fox. Seems like there are big things being worked on for DE, so feel free to close the issue at any time if you think it's not worth the hassle.

**Comment by FoxMcloud5655** [comment]
I wish I had the power to, but I don't.  You're welcome any time!

**Comment by KirikaAetheria** [comment]
Oh sorry, not entirely sure how github roles work. Should I close the issue then?

**Comment by FoxMcloud5655** [comment]
Yes, please!

**Comment by KirikaAetheria** [comment]
Sure thing! Thanks again for your time and help
