### ISSUE TITLE
Potion Core mod default settings cause Chaos Guardian healing crystals to respawn instantly when unloaded (fix included at the end)

### ISSUE THREAD

**Issue by KirikaAetheria** [brandon3055/Draconic-Evolution#1469]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.25.353-universal
* Minecraft Forge version: 1.12.2 - 14.23.5.2854

## Crash report
```
N/A
```

## Full Mod List
* CodeChickenLib-1.12.2-3.2.3.358-universal
* BrandonsCore-1.12.2-2.4.19.214-universal
* RedstoneFlux-1.12-2.1.1.1-universal
* Draconic-Evolution-1.12.2-2.3.27.353-universal
* PotionCore-1.9_for_1.12.2

## Report
Same issue as reported in https://github.com/brandon3055/Draconic-Evolution/issues/1322 

As per the title, having the mod Potion Core installed with default settings will cause chaos crystals to respawn as soon as they're unloaded. Looking at their issue tracker, it seems that mod is very disruptive by design, and they're aware it causes a number of issues with other mods. As such, it's safe to assume reporting this issue to them likely won't result in a fix. And since it's definitely not worth the trouble for DE's team to go through, I am posting this simply to keep this information documented for future reference in case someone else runs into this problem.

## Fixing the issue
To fix this issue, open Potion Core's config file, and change the value "**Fix Effects When Changing Dimensions**" to "**false**". This will cause the crystals to work as intended, staying dead even when unloaded.

**Comment by KirikaAetheria** [comment]
Is it alright if I close this one as well Fox?

**Comment by FoxMcloud5655** [comment]
That would be great.  At least it's documented for people trying to create another issue!
