### ISSUE TITLE
Energy Core Crash

### ISSUE THREAD

**Issue by spannerman79** [brandon3055/Draconic-Evolution#147]
Crash log http://paste.ee/p/XtPZx
Draconic-Evolution-1.7.10-1.0.2-Snapshot_3
BrandonsCore-1.0.0.6

Steps done;
1.  Created clean instance in MultiMC of Minecraft 1.7.10
2.  Added Forge 1448 into new clean instance
3.  Added in Draconic-Evolution-1.7.10-1.0.2-Snapshot_3 and BrandonsCore-1.0.0.6 only into instance
4.  Started MC, created SP world (flat)
5.  Placed down Energy Core
6.  Right click on Energy core (empty hand) - crash occurs - crash log supplied (above)

**Comment by brandon3055** [comment]
Looks like i missed something when i fixed the "crash on right click" error. Will be fixed in the next update. In the mean time try not to right click the core :) (You should not need to right click the core anyway and shift right click to place blocks around it should not crash.)

**Comment by spannerman79** [comment]
I know the snapshots are considered testing only for bugs - hence this issue.
