### ISSUE TITLE
Mod don't work crash

### ISSUE THREAD

**Issue by Jenss98** [brandon3055/Draconic-Evolution#1470]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.27.353-universal, BrandonsCore-1.12.2-2.4.19.214-universal
* Minecraft Forge version: 1.12.2-14.23.5.2854:universal
* Mod Pack: (if applicable) FTBUltimateReloaded

## Crash report
```
https://hasteb.in/ulezoyos.rb
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
Despite the extremely generic issue name and zero details, I know what the issue is, but it does not have to do with Draconic Evolution!

The crash report states that 4096 is an invalid ID, which means that you've hit the limit.  Install NotEnoughIDs to remove this limit, and you'll be good to go.

**Comment by Jenss98** [comment]
Thanks, im not so experienced with Mods. I`ll close
