### ISSUE TITLE
After Using Injectors every item that is left clicked is now placed on the surface

### ISSUE THREAD

**Issue by tdawg4** [brandon3055/Draconic-Evolution#1473]
## Base information
After using the injectors for the first time every item that is left clicked onto a block is placed as if it is an injector. Breaking blocks is now impossible.... 
* Minecraft version: 1.12.2
* Mod version: 1.12.2-2.3.25.351
* Minecraft Forge version:  14.23.5.2847
* Mod Pack: (if applicable)
Mech and Magic Lite

**Comment by FoxMcloud5655** [comment]
I don't exactly understand what the problem is. Do you have a way to record your screen and show us what's happening?

**Comment by tdawg4** [comment]
Yeah, I wasn't even sure how to google the problem. 
https://streamable.com/5kkrou

**Comment by FoxMcloud5655** [comment]
Looks like you've accidentally bound the "place item in world" button with left click.

**Comment by tdawg4** [comment]
i was losing my mind thank you
