### ISSUE TITLE
Mob soul drop chance code

### ISSUE THREAD

**Issue by caribhunt** [brandon3055/Draconic-Evolution#1474]
Where is the soul drop chance calculation located? I'm highly interested in the implementation, but can't find the exact file.
It is probably just the rand function, but nevertheless

**Comment by brandon3055** [comment]
https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/handlers/DEEventHandler.java#L131
