### ISSUE TITLE
Compatibility Suggestions

### ISSUE THREAD

**Issue by Shadow5300** [brandon3055/Draconic-Evolution#1475]
Allow the Wyvern/Draconic bows to use arrows from Thermal Innovation quivers and other arrows from other mods, like the Ender Arrow from Quark.

**Comment by FoxMcloud5655** [comment]
That is a great suggestion, but with the way it's coded, it may be hard trying to get that to work.

**Comment by Shadow5300** [comment]
> That is a great suggestion, but with the way it's coded, it may be hard trying to get that to work.

Well, Thermal Bows work with Quark arrows. It may depend on what the DE Bows 'see' as arrows.
