### ISSUE TITLE
Draconic helm ignores Pam's harvestcraft foods

### ISSUE THREAD

**Issue by BLucky-gh** [brandon3055/Draconic-Evolution#1476]
## Base information
* Minecraft version: 1.12
* Mod version: 2.3.27.33 (2.3.27)
* Minecraft Forge version: 14.23.5.2854
* Mod Pack: custom

Draconic helm ignores any food from Pam's harvestcraft and goes for any other food in the inventory and lets me starve when a stack of a top-tier food is all I have in my inventory. It works ok with vanilla food, and I am able to eat the food from Paam's Harvestcraft normally.

**Comment by FoxMcloud5655** [comment]
You know, for how many years I've been playing with Draconic Evolution and Pam's Harvestcraft installed, I've never noticed this issue.  I'll take a look when I get a chance.

**Comment by MCSuperplayer** [comment]
it may be because the Draconic Helm will only auto feed you when you nave as much hunger as the item gives you
(Example: 2 Youtubers are Playing ATM3, the Burger gives a bit more than 10 hungeer points and they only get fed when they have that exact amount of hunger missing)
