### ISSUE TITLE
Issue building with gradle

### ISSUE THREAD

**Issue by maxall41** [brandon3055/Draconic-Evolution#1477]
HI. i'm trying to build the 1.15 version with gradle. But I get the error below.
I changed the gradle properties file a bit to use a newer version of gradle:
```
#Wed Aug 09 15:49:49 ACST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip

```
A problem occurred configuring root project 'Draconic-Evolution-1.15.2'.
> Failed to notify project evaluation listener.
   > 'org.gradle.internal.nativeplatform.filesystem.FileSystem org.gradle.internal.nativeintegration.services.FileSystems.getDefault()'
```
Syatem data:
Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          15.0.1 (Oracle Corporation 15.0.1+9)
OS:           Mac OS X 10.15.4 x86_64

**Comment by covers1624** [comment]
The 1.15 branch is not ready, no support is provided for building it yourself.
