### ISSUE TITLE
Custom Fusion Crafting Error Help

### ISSUE THREAD

**Issue by BathToast** [brandon3055/Draconic-Evolution#1478]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.27.353
* Minecraft Forge version: 14.23.5.2854
* Mod Pack: Custom, Building my own currently

## The Error in question

[17:54:02] [Client thread/INFO]: Loading custom fusion recipes...
[17:54:02] [Client thread/ERROR]: **Recipe result does not support ore dictionary! Recipe will not be added/removed**
[17:54:02] [Client thread/ERROR]: Failed to load recipe entry!
{"mode":"ADD","result":"ore:blockVerinium","catalyst":"ore:blockGlorymetal","energy":1000000,"tier":0,"ingredients":["dimdoors:unravelled_fabric,16","dimdoors:unravelled_fabric,16","thermalfoundation:material,64,1024","tconstruct:materials,1,14","taiga:adamant_ingot","taiga:adamant_ingot","taiga:adamant_ingot","taiga:adamant_ingot"]}
[17:54:02] [Client thread/INFO]: Successfully removed 3 Fusion Recipe(s)
[17:54:02] [Client thread/INFO]: Successfully added 11 Fusion Recipe(s)
[17:54:02] [Client thread/WARN]: Failed to add 1 Fusion Recipe(s)
[17:54:02] [Client thread/INFO]: Finished PostInitialization

Notes: 

So currently I'm building a modpack, and I'm building a custom mod through the use of MCreator 2020.2 (as I'm personally not familiar with custom dimension building, so I'm using a tool to add it and some items so its all just one packaged deal rather than make two separate mods for content). 

The mod is called HadronicCore and adds a few items. Two of these items are called Verinium and Glory Metal. To avoid the headache of making multiple metals and alloys I wanted to be able to use a fusion crafter to directly turn Glory Metal into Verinium. 

However, it looks like when I try to add the recipe it tells me that the result doesnt support ore dictionary, even though I have in fact added ore dictionary support for these mod items within MCreator, and even tried using Crafttweaker to modify the ore dictionary to support the item. Directly referring to the items without using Ore Dict will cause the recipe to break entirely if its a material that goes on the Crafting Injectors

Would anyone happen to know a work around or is there just some really strange incompatibility caused by how MCreator builds its mods that prevents them from working properly with fusion crafting? I apologize if more info is needed, ill be glad to add it but I just dont know what to include in this case

**Comment by covers1624** [comment]
An ore dictionary entry is effectively `List<Item>` which one should it give you? 
What DE is saying to you, is you cannot use _any_ ore dictionary entry as the result stack, you must specify the specific item.

**Comment by BathToast** [comment]
> An ore dictionary entry is effectively `List<Item>` which one should it give you?
> What DE is saying to you, is you cannot use _any_ ore dictionary entry as the result stack, you must specify the specific item.

Thank you for the quick response, I suppose in that sense I misread the error and didnt even think of it.

However, whats weird is after removing the Ore Dict references and going straight to the actual items themselves, it still generates the same error

whats even more confusing is that I even went as far as to completely pull the items from oreDict and it *still* generates the same error. 

Currently as such
`[00:19:06] [Client thread/INFO]: Loading custom fusion recipes...
[00:19:06] [Client thread/ERROR]: Recipe result does not support ore dictionary! Recipe will not be added/removed
[00:19:06] [Client thread/ERROR]: Failed to load recipe entry!
{"mode":"ADD","result":"hadroniccore:veriniumblock","catalyst":"hadroniccore:glorymetalblock","energy":5000,"tier":0,"ingredients":["minecraft:diamond"]}
[00:19:06] [Client thread/INFO]: Successfully removed 3 Fusion Recipe(s)
[00:19:06] [Client thread/INFO]: Successfully added 11 Fusion Recipe(s)
[00:19:06] [Client thread/WARN]: Failed to add 1 Fusion Recipe(s)
[00:19:06] [Client thread/INFO]: Finished PostInitialization`

Is the output into the log, if anyone has any idea how to work around this, it would be much appreciated

**Comment by FoxMcloud5655** [comment]
It would be very hard to debug without having access to the mod you've created.  A quick search online reveals that this is not a public mod, so you'd have to attach what you've made here; a stripped down version if you're concerned about releasing the mod publicly before it's time is fine.

MCreator is notorious for using redundent and outdated code in created mods, so I wouldn't be surprised if it's causing an issue here, though I could be wrong.

**Comment by BathToast** [comment]
> It would be very hard to debug without having access to the mod you've created. A quick search online reveals that this is not a public mod, so you'd have to attach what you've made here; a stripped down version if you're concerned about releasing the mod publicly before it's time is fine.
> 
> MCreator is notorious for using redundent and outdated code in created mods, so I wouldn't be surprised if it's causing an issue here, though I could be wrong.

I figured as much, the tool itself is very jank and takes alot of trial and error to get it to work correctly to begin with, I will be trying to use Crafttweaker to make intermediate items to circumnavigate this issue, none the less I'm not worried about releasing the mod here for testing purposes, the mod itself is pretty bare bones, constantly changing and being tweaked, and the meat of the modpack is crafting recipe tweaks, balance changes in configs, etc anyway.

If you're able to find a work around or more information regarding this, it would be much appreciated. If you're not, then I'll probably find a work around. Thanks for the assistance regardless. Cheers.

v1.2.2.0 contains the OreDict references for the 2 blocks and 2 ingots in question, used for debugging
[Hadronic_Core_V1.2.2.0.zip](https://github.com/brandon3055/Draconic-Evolution/files/5726404/Hadronic_Core_V1.2.2.0.zip)

v1.2.2.1 contains no OreDict references for any item, which is how the mod is usually run, Crafttweaker is used to add OreDict entries because it seems to work more consistently than the Tag system for MCreator
[Hadronic_Core_V1.2.2.1.zip](https://github.com/brandon3055/Draconic-Evolution/files/5726416/Hadronic_Core_V1.2.2.1.zip)

Its worth noting that in my experience: I cannot use direct references to the items if its a material on a fusion crafting injector either, I _have_ to use oreDict or else the item will leave an empty space in the crafting recipe and it wont work even if all items are present. 

Hopefully we'll be able to find an incompatibility or solution out of this, if you need any further info lemme know! Cheers!
