### ISSUE TITLE
Icons/Assets bug

### ISSUE THREAD

**Issue by Tank-203** [brandon3055/Draconic-Evolution#1479]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.27.353-universal
* Minecraft Forge version: 1.12.2-forge-14.23.5.2854
* Mod Pack: (if applicable) N/A self-,made with other mods

I have no clue if someone else solved this, but I've spent like an hour researching and could find no fix. My problem is the assets in the mod itself. All the Wyvern tools and Draconic sword textures are messed up. The Wyvern tools are all pixelated, and all the Draconic Swords look like pickaxes. Sorry if this has been solved on here! If so I couldn't find it. You can see the messed up Icons in the JEI menu on the right of the picture below.

![2020-12-27_17 18 39](https://user-images.githubusercontent.com/60994567/103181638-f63e2a80-4868-11eb-8089-05d3adf35ef3.png)

## Crash report
```
No crash happened.
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
You might have something that messes with the display of 3D models.  The textures you're seeing there are the color palettes that the 3D models draw from.  if you continue to have troubles and can't get it to work with your modpack, disable 3D models in Draconic Evolution's settings

**Comment by Tank-203** [comment]
I'm not sure if my game was bugged lol. It's fixed now with a restart

**Comment by Tank-203** [comment]
I think I know what caused it. It can happen after Reloading resource packs with F3 + T.
