### ISSUE TITLE
help

### ISSUE THREAD

**Issue by reconsolidate** [brandon3055/Draconic-Evolution#1480]
## Base information
* Minecraft version:1.12.2
* Mod version:3.4.0
* Minecraft Forge version:
* Mod Pack: FTB revelations 

injector not working but works if you use chest and hoppers watched countless guieds will not allow any players to place items in the fusion crafting core only via the hopper

https://user-images.githubusercontent.com/58376584/103321161-2edc3080-4a30-11eb-83f8-37ae9a4de538.mp4

**Comment by FoxMcloud5655** [comment]
First, Draconic Evolution 3.4.0 does not exist.  The latest version is 2.3.27.353.  Secondly, the forge version needs to be here to help deduce this problem.

**Comment by reconsolidate** [comment]
FoxMcloud5655 no the revelations version game version is 3.4.0?
and the forge version 
forge-14.23.5.2846

**Comment by reconsolidate** [comment]
i thought it was meaning modpack version
