### ISSUE TITLE
Except, the point of the chaos dragon is to buck that trend.  It is intended.

### ISSUE THREAD

**Issue by Alexogo96** [brandon3055/Draconic-Evolution#1481]
Except, the point of the chaos dragon is to buck that trend.  It is intended.

_Originally posted by @GreatOrator in https://github.com/brandon3055/Draconic-Evolution/issues/175#issuecomment-301316328_

Except you can spawn in more than enough items to do it with creative, so this makes no sense.

**Comment by covers1624** [comment]
What are you trying to explain? What is your issue here?

The Chaos guardian _can_ kill creative players, the linked issue has nothing to weather a creative player could spawn in items to kill it.
