### ISSUE TITLE
Energy Core particles not centered

### ISSUE THREAD

**Issue by MGSchultz-13** [brandon3055/Draconic-Evolution#1482]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12.2 - 2.3.27.353
* Minecraft Forge version: 14.23.5.2847
* Mod Pack: Antimatter Chemistry

When an Energy Pylon transfers energy to the Energy Core, energy can be visualized as blue particles going from the Pylons to the Core. I expected that the particles went to the centre of the core, however when looking closely, they go to the north-west corner of the core centre block. This can be easily seen in a small (1 block) core (in the picture). 

![image](https://user-images.githubusercontent.com/16447647/103437228-bded7200-4c03-11eb-882d-d3187f8b175f.png)

**Comment by brandon3055** [comment]
Will be fixed in the next update
