### ISSUE TITLE
Crafting Injectors Not Accepting Power

### ISSUE THREAD

**Issue by Treat5043** [brandon3055/Draconic-Evolution#1483]
So, I'm not sure why, but the crafting injectors for fusion crafting are not accepting power. I've looked at other people having the same issue, but none of the solutions worked. I tried to make an Advanced Dislocator, which would explain the set up.

Here's what I'm using:

- I'm on StoneBlock 2
- 8 Wyvern Injectors
- 9 Wyvern I/O
- 1 Wyvern Energy Relay
- Tier 7 Core

![2021-01-05_13 08 27](https://user-images.githubusercontent.com/77022252/103689550-13ee4c80-4f59-11eb-82d4-497720549612.png)
![2021-01-05_13 08 41](https://user-images.githubusercontent.com/77022252/103689561-18b30080-4f59-11eb-8c19-46c0317d710b.png)

From what people have said, it was due to the injectors not accepting power until you start the recipe. But the ability to start the recipe wouldn't even show up if I had everything in the right spaces.

It was also weird that I was able to make the injectors, and then the power stopped. I've tried restarting the game, and that didn't work either.

**Comment by FoxMcloud5655** [comment]
First, you're crafting injectors are too far apart.  You need to have a one block air gap between the core and the plane on which the injectors sit.

Second, ensure that the wireless crystals are set up correctly.  You can still start the crafting process even if you have no RF present, though, of course, it will sit there and do nothing.

**Comment by Treat5043** [comment]
I've moved the injectors and even rebuilt the entire setup just to see if I might've messed up somewhere. The thing I'm confused about is that the injectors could accept power before, but now won't.

![2021-01-05_14 18 37](https://user-images.githubusercontent.com/77022252/103694769-2076a300-4f61-11eb-98e8-7ebe6373a12e.png)

Even with the proper setup, this is the only thing I see...

**Comment by FoxMcloud5655** [comment]
That's an invalid recipe or the placement of the crafting injectors is wrong.  You'd see the ingredients on the sides of the GUI and a big start button otherwise, regardless of power provided.

**Comment by Treat5043** [comment]
Well, I'm not sure why the Dislocator doesn't work (even though JEI sys it should work), but everything work now. Hopefully this won't happen again...

**Comment by FoxMcloud5655** [comment]
Mind closing the issue, then?
