### ISSUE TITLE
Nether generation with COFH

### ISSUE THREAD

**Issue by KazzaKING** [brandon3055/Draconic-Evolution#1485]
For version 1.12.2, using cofh to spawn the overworld ores uses draconicevolution:draconium_ore, what does the nether one use? draconicevolution:draconium_ore:1?

**Comment by FoxMcloud5655** [comment]
This is a question, not an issue with the code.  If you have a question, please ask it on the Discord server.

**Comment by KazzaKING** [comment]
ah my bad
