### ISSUE TITLE
server crash - chaos dragon killed

### ISSUE THREAD

**Issue by weaver8185** [brandon3055/Draconic-Evolution#1486]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.27.353
* Minecraft Forge version: 14.23.5.2855
* Mod Pack: personal pack

when the chaos dragon goes into the middle of the island, server crashes although client is fine, normal dragon does not crash server when it dies

crash report: 
[crash-2021-01-08_13.57.00-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/5784671/crash-2021-01-08_13.57.00-server.txt)

**Comment by FoxMcloud5655** [comment]
```
java.lang.ClassCastException: com.brandon3055.draconicevolution.entity.EntityGuardianCrystal cannot be cast to net.minecraft.entity.player.EntityPlayer
    at com.iamshift.mineaddons.entities.EntityAncientCarp.isEntityInvulnerable(EntityAncientCarp.java:144)
    at net.silentchaos512.scalinghealth.event.DamageScaling.onPlayerHurt(DamageScaling.java:69)
```
This means that there's a mod conflict between something called Scaling Health, Mine Add-ons, and Draconic Evolution.  One of the two other mods is thinking the Chaos Dragon is a player.
