### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by V4kodin** [brandon3055/Draconic-Evolution#1488]
Should we wait for update to new Minecraft versions for example 1.16.5? And if answer is "yes" can we have any dates?

**Comment by FoxMcloud5655** [comment]
If you're asking if you want to port the code to 1.16.x if brandon3055 isn't going to update Draconic Evolution, then no.  There's no need; if you take a look at the master branch, you'll see that it's 1.16.4 already.

As for the dates, I'll tell you what I've told everybody else; Soon:tm:.
