### ISSUE TITLE
Chaos dragon, scared???

### ISSUE THREAD

**Issue by DJLinx** [brandon3055/Draconic-Evolution#1489]
## Base information
* Minecraft version: 1,12,2
* Mod version: 1.12.2-2.3.25.351
* Minecraft Forge version: 1.12.2-14.23.5.2847

All that happened was the chaos dragon flew off after I broke all the crystals that heal him, then after that he just flew far, far away to the point I just couldnt find him and the boss bar was also gone. I also couldnt get the chaos crystal either. Dont really know if im just a dumb dumb or what.

**Comment by FoxMcloud5655** [comment]
The Chaos Guardian does have a phase where he flies really far away, then charges at you.  By default, he will chunk load everything around him so he doesn't get stuck, but a server operator may have disabled that feature.

If this has been disabled, then all you can do is follow him to keep him chunk loaded.

**Comment by DJLinx** [comment]
Welp hes already long gone now hope I can find him again, thanks for the help tho, I appreciate it.

**Comment by FoxMcloud5655** [comment]
No problem.  Mind closing the issue?

**Comment by brandon3055** [comment]
The guardian will try to avoid the player when it is low on health but it should never go more than 260 blocks from its home position which is the center of the island.. 
The only thing i can think of is something may have interfered with the guardian and reset its home position to 0, 0.
