### ISSUE TITLE
Crash when encountering ice and fire mob

### ISSUE THREAD

**Issue by Sember225** [brandon3055/Draconic-Evolution#1490]
https://pastebin.com/NfPdpvKf

Breif explination, When playtesting my modpack a player encountered this crash when approaching or attacking an Ice and fire Dragon. He recieved several other crashes when encountering different mobs from that same mod.

The reason I'm posting this issue here is because it seems the interactions between Drac evo and Tink evo is somehow effecting ice and fire mobs.

Any help would be appreciated 

How to recreate:
Have latest 1.12.2 versions of Draconic evolution, Tinker's evolution and Ice and fire. Attack an Ice and fire mob, in this pastebin it was a dragon.

How to resolve: 
Removing either Tinker’s evolution or Draconic evolution seems to fix this issue.

**Comment by FoxMcloud5655** [comment]
```xyz.phanta.tconevo.integration.draconicevolution.DraconicHooksImpl.isShieldEnabled(DraconicHooksImpl.java:215)
```
This line looks to be the culprit.  This is the other mod you mentioned above not working properly with Draconic Evolution and something to do with the DE shielding system.

**Comment by Sember225** [comment]
I found another similar issue on Tinkers evolution, without ice and fire. This may just be an issue with Tinker’s evolution.

https://github.com/phantamanta44/tinkers-evolution/issues/76

**Comment by FoxMcloud5655** [comment]
Exactly what I thought.  Mind closing the issue here, then?
