### ISSUE TITLE
Is it possible to hide the energy links?

### ISSUE THREAD

**Issue by Lord-Volkner** [brandon3055/Draconic-Evolution#1492]
The links will only show up if I'm holding the binder unless there's power flowing through them. I built a Extreme Reactor in the basement of my tower-style base and a Tier 7 Energy Core way up at the top. The link between the two I/O crystals is now always visible running through every single floor of my base. I've searched the web for how to hide them, but found nothing. Is it possible to hide the link lines?

I'm running Infinity Evolved: Reloaded modpack v3.5.0
1.12.2 MC version
14.23.5.2847 forge version.

Thanks,
Eric

**Comment by FoxMcloud5655** [comment]
No, it is not.  If you don't like link where it's at, you can always move it elsewhere using more links.  I typically have 8 I/O crystals linked up in a way so the transfer of power looks like it would actually makes sense instead of running a bunch of power lines through my base.
