### ISSUE TITLE
Hello, can I upload this mod to Minecraft China Version

### ISSUE THREAD

**Issue by yihan520** [brandon3055/Draconic-Evolution#1498]
## Base information
* Minecraft version:
* Mod version:
* Minecraft Forge version:
* Mod Pack: (if applicable)

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
No.  According to the license:
```
You CANNOT
- Redistribute this in its entirety as source or compiled code (Except in the case of mod packs).
```
