### ISSUE TITLE
Custom recepie

### ISSUE THREAD

**Issue by LeeMan00** [brandon3055/Draconic-Evolution#1499]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic Evolution 2.3.27.353-universal
* Minecraft Forge version:
* Mod Pack: (if applicable)

No crash reports. Just trying to add Custom Fusion Recepies through CustomFussionRecepies.json. I put it as told in instruction into "config/brandon3055", but the game doesn see it. Thats the code I wrote:
[
	{
  		"mode": "ADD",
  		"result": "minecraft:nether_star",
  		"catalyst": "minecraft:diamond_block",
  		"energy": 1000,
  		"tier": 1,
  		"ingredients": [
    			"minecraft:dye",
    			"minecraft:blaze_rod",
    			"draconicevolution:draconic_core",
    			"draconicevolution:draconic_ingot",
    			"draconicevolution:draconic_ingot"
  		]
	}
]

**Comment by FoxMcloud5655** [comment]
"CustomFussionRecepies" is not a valid name.
