### ISSUE TITLE
Crash when adding enchants/Opening item GUI

### ISSUE THREAD

**Issue by Tgiguy** [brandon3055/Draconic-Evolution#15]
Adding an enchantment to Draconic tools through the item GUI causes the client to crash when exiting the GUI. Enchants stick when reloading the world. Haven't yet tested Wyvern tools.

Crash Log:
http://pastebin.com/UENm7rSQ

**Comment by brandon3055** [comment]
That seems to be related to another crash i am already investigating. I hope to have a fix out soon.

**Comment by Labs4077** [comment]
I get the exact same crash report when I attempt to open up the tool configuration screen while my character is moving.

**Comment by Tgiguy** [comment]
Indeed, further experimenting has revealed that the GUI just likes to crash...a lot. Let me know if there's anything I can do to help test. I bloody love the work you've done with this mod.

**Comment by ryan2109** [comment]
im having the same issue only does it on mp server, single player it works fine, and i get the same error report

**Comment by brandon3055** [comment]
This crash is fixed in snapshot 4
