### ISSUE TITLE
Advanced Wireless Transceiver

### ISSUE THREAD

**Issue by XFactHD** [brandon3055/Draconic-Evolution#150]
It is impossible to connect the Advanced Wireless Transceiver to Mekanism and Thermal Expansion machines (I didn't try it with any other). For the Mekanism machine the Crystal Binder doesn't do anything and the Thermal Expansion Machines are just rotated.
I am using the latest version of Draconic Evolution (latest on Curse) and Thermal Expansion but not the latest Mekanism.

**Comment by brandon3055** [comment]
this bug has been reported and will be fixed in the next release. Please keep in mind this is a snapshot build.

**Comment by XFactHD** [comment]
Sorry for creating a duplicate. I know that this had already been reported but I thought that the fix was already in a released version.
