### ISSUE TITLE
End Crystals too expensive

### ISSUE THREAD

**Issue by subandrew684626** [brandon3055/Draconic-Evolution#1502]
* Minecraft version: 12.2.2
* Mod version:1.12.2-2.3.27.353
* Minecraft Forge version: 14.23.5.2855
* Mod Pack: (if applicable) Draconic Evolution

Is there a way to change the recipe that draconic evolution made for End Crystals or disable it so it goes back to the vanilla form. Thank you

**Comment by FoxMcloud5655** [comment]
Yes.  There is a config option for it.

**Comment by subandrew684626** [comment]
where

**Comment by brandon3055** [comment]
`B:expensiveDragonRitual=true` /config/brandon3055/DraconicEvolution.cfg CHange that to 
`B:expensiveDragonRitual=false`

**Comment by CyBrine** [comment]
Is there a way to do this on 1.16.5?
