### ISSUE TITLE
End Crystal too expensive. Part 2

### ISSUE THREAD

**Issue by subandrew684626** [brandon3055/Draconic-Evolution#1504]
* Minecraft version: 12.2.2
* Mod version: 1.12.2-2.3.27.353
* Minecraft Forge version: 14.23.5.2855
* Mod Pack: (if applicable) Draconic Evolution

What config do i change to make the End Crystal go back to its original recipe. Also where is the config file.

**Comment by FoxMcloud5655** [comment]
First of all, Minecraft version 12.2.2 doesn't exist.  I'm going to assume you meant 1.12.2.  Secondly, there is no modpack by the name of "Draconic Evolution", so I'm going to assume that you're using Draconic Evolution by itself.

The config option is located in-game under the "Mods" menu on the main menu.  Search for "Draconic Evolution", click on it, then select the "Config" button.  After hitting the "Tweaks" button, you'll see a list of config options.  Find the one labeled "expensiveDragonRitual" and click the button to change it from `true` to `false`.  You'll need to restart Minecraft for the change to take effect.

You can also directly modify the config if you want to bypass having to load Minecraft just to have to restart Minecraft after your config change is finished.  It's located under your instance folder inside of `/config/brandon3055/DraconicEvolution.cfg`.  Just open the file in any text editor and search for "expensiveDragonRitual", then change the `true` to read `false`.

**Comment by subandrew684626** [comment]
Thank you so much it worked
