### ISSUE TITLE
[1.16] Will there be an option to use the 1.12 models and textures in the final release?

### ISSUE THREAD

**Issue by glencoe2004** [brandon3055/Draconic-Evolution#1507]
I noticed the '1.12-assets' folder and couldn't help but ask: Are there plans for an optional 1.12 models mode, a la Programmer Art?

**Comment by FoxMcloud5655** [comment]
Brandon is actually looking for a new modeler right now to make improved models for DE3.  I'm sure there will be an option to toggle between these new models and the ones we have currently, but I'm not sure about DE2 models.

It wouldn't be too hard to include, so if it doesn't end up being a part of the base mod, I'm sure someone will make a mod to do just that after the full release.
