### ISSUE TITLE
Crash, when dirt block deleting the draconic energy core, with CREATIVE MODE!

### ISSUE THREAD

**Issue by Sasikaa** [brandon3055/Draconic-Evolution#151]
Sorry my bad english!
My hand is DIRT block. Creative mode in my single player world. Clicking the energy core because delete it. BUMM! Crashing!

This is my crash report:
http://pastebin.com/iWVRUAzH

**Comment by brandon3055** [comment]
This is a bug that will be fixed in the next release. I have not released a hot fix for this because it is a snapshot and it is not a game breaking bug. Just dont right click the core block unless holding shift to place a block and it wont crash.
