### ISSUE TITLE
Crash when interacting with Idealland 

### ISSUE THREAD

**Issue by TaoismDeepLake** [brandon3055/Draconic-Evolution#1512]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.27 
* Minecraft Forge version:Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5
* Mod Pack: (if applicable)

## Crash report

[EventsRainCurse.java.txt](https://github.com/brandon3055/Draconic-Evolution/files/6929534/EventsRainCurse.java.txt)

[crash-2021-07-13_23.57.20-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/6929532/crash-2021-07-13_23.57.20-client.txt)
The decompiled java seems to point to a wrong line, the source file will help nevertheless.

**Comment by TaoismDeepLake** [comment]
Some player provided me with this, yet I can not find why it crashed at there. Idealland is not an open-source mod yet, but if you need it's full code, I can provide it.

**Comment by TaoismDeepLake** [comment]
[related_mod.zip](https://github.com/brandon3055/Draconic-Evolution/files/6929588/related_mod.zip)
This is the jar file of Idealland he used. Zipped as Github doesnot allow direct jar upload.

**Comment by covers1624** [comment]
Line 64 of the class you posted.

Entities can have null worlds when used for pure rendering related things.

**Comment by TaoismDeepLake** [comment]
Ok, so Entity::getEntityWorld will not return null even in these cases, right? The comment of forge said so.

**Comment by brandon3055** [comment]
I'm not sure what comment your referring to but  getEntityWorld just returns the world and at the point that event is called (Entity construction) the world can be null.
