### ISSUE TITLE
[Suggestion] A configuration setting which defines which single item mode is the default - active or inactive.

### ISSUE THREAD

**Issue by jk1895** [brandon3055/Draconic-Evolution#1513]
Hello!
In the modpack (Omnifactory) I play, I placed 600 injectors and had to set the single item mode to active 600 times. It was very tedious and so I came up with this idea.

It would be great if there was an option in the DraconicEvolution.cfg file to set which mode is the default when placing injectors.
I would then inform the modpack makers and ask them to change it in their modpack. Of course I would also change it myself.

Something like this:
#If true, injectors placed in the world will be placed with the Single Item Mode: Active 
B:disableSingleItemModeInactive=true
or something like that. :)

Thank you very much!

**Comment by brandon3055** [comment]
Will consider adding this to the next update.

**Comment by jk1895** [comment]
It's brilliant and so much more comfortable now. My next round of Omnifactory will be so much more enjoyable.
You are great! Thank you so much!
