### ISSUE TITLE
Dislocator Receptacle Max Size issue

### ISSUE THREAD

**Issue by Robohedgehog** [brandon3055/Draconic-Evolution#1515]
MC Version: 1.12.2
Mod version: 2.3.27.353
Minecraft Forge version: 14.23.5.2855
Mod Pack: FTB Revelations 3.5.0

Max dislocator receptitcle portal size is different between documentation and code; Documentation lists 1x150x150 but the check in code (From what I understand) seems to be capped at 100. Discovered trying to make a meme 128x128 portal on the internal wall of an Applied Energistics Spatial Dimension. I want a full wall portal damn-it! 😂 

To clarify, the portal just doesn't form. No crash, just the portal does not form.

(For transparency, the code I saw with this was in TileDislocatorReceptacle.java and in the scanPortal method. It seems to be checking that the maximum distance between 2 points of the portal frame is no greater than 100 rather than 150?)

**Comment by brandon3055** [comment]
I know the portal max size isn't well defined but to be honest the portal generation code isn't very efficient and gets a bit buggy at extremely large sizes so ordinarily, I would recommend building a smaller portal. 
But if it's just for the memes then technically the limit is defined as 'all portal blocks must be within 100 meters of the receptacle' And the receptacle does not need to be a part of the frame so it may look a bit odd but you could have it floating in the center of the portal. 
Also, keep in mind that's 100 meters circular radius so if you tried to build a 200x200 square portal with the receptacle in the middle the corners would be too far away.

**Comment by Robohedgehog** [comment]
Ohhhh I see, the detailed explaination is greatly apprecated. Tried dropping it down right into the middle, but still hit an issue. Guessing the 100m radius is still clipping the corners of the 128x128 portal diameter.

I'll look into another way to get the effect I'm after. Thank you for your time!
