### ISSUE TITLE
[1.16] Jump Boost Modifiers Config Not Respected

### ISSUE THREAD

**Issue by milkev** [brandon3055/Draconic-Evolution#1517]
## Base information
* Minecraft version: 1.16.5
* Mod version: [3.0.7.389](https://www.curseforge.com/minecraft/mc-mods/draconic-evolution/files/3431994)
* Minecraft Forge version: 36.2.2
* Mod Pack: (if applicable) JEI + DE, nothing else aside from required libraries in latest available versions applicable to 1.16.5

### Crash report
Not a crash

### Description / steps to reproduce

1. get modular chestplate (any tier)
2. put jump boost modifier in it (any tier) and energy core (any tier)
3. set jump boost modifier percent to 0% (or other value) in item config
4. attempt to jump, you still jump full boosted height

### WORKAROUND:
workarounds fairly easy with this, since you can just directly pull the module out.

**Comment by brandon3055** [comment]
Thank you. This will be fixed in the next update.
