### ISSUE TITLE
[1.16] Staff of Power Incompatable with Weapon Enchants despite being compatable with tool enchants

### ISSUE THREAD

**Issue by milkev** [brandon3055/Draconic-Evolution#1518]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.7.389
* Minecraft Forge version: 36.2.2
* Mod Pack: (if applicable) JEI + DE, nothing else aside from required libraries in latest available versions applicable to 1.16.5

### Crash report
No Crash

### Description / steps to reproduce

1. attempt to put a weapon enchant such as looting or sharpness on a staff of power, such as via a anvil or /enchant
2. weapon enchants are unable to be applied
3. attempt to put a tool enchant such as fortune or efficiency on a staff of power, such as via a anvil or /enchant
4. tool enchants apply properly

**Comment by brandon3055** [comment]
Thank you. This will be fixed in the next update.
