### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by 0dikpah** [brandon3055/Draconic-Evolution#152]
when i build a draconic energy storage the texture don't appear on the sphere...i can still use tho...plz fix it :)

Btw AWESOME MOD!

**Comment by GreatOrator** [comment]
Are you using optifine?

**Comment by brandon3055** [comment]
Dose it show a missing texture? or is it just invisible?

**Comment by GreatOrator** [comment]
Not enough info to fix and no response.
