### ISSUE TITLE
[1.16] Brandon's Core incompatibility

### ISSUE THREAD

**Issue by PixusPanic** [brandon3055/Draconic-Evolution#1520]
## Base information
* Minecraft version: 1.16
* Mod version: 3.0.11.396
* Minecraft Forge version: 36.2.2
* Mod Pack: Personal

### Crash report

[crash-2021-08-21_19.31.12-fml.txt](https://github.com/brandon3055/Draconic-Evolution/files/7026360/crash-2021-08-21_19.31.12-fml.txt)

### Description / steps to reproduce

I recently put the latest version of Draconic Evolution inside my mods folder for my 1.16.5 modded instance, but the game is asking that I need a version of Brandon's Core (3.0.8.232 or above - I currently have 3.0.7.230) that, as far as I know, either doesn't exist or isn't uploaded to the public. Is this intended, or was the latest version of BC not updated publicly?

**Comment by FoxMcloud5655** [comment]
No, this was not intended.  Brandon has fixed this issue after it was pointed out and you can now download the latest version of Brandon's Core to fix this.
