### ISSUE TITLE
[Feature Request] <Extension of some GUI elements>

### ISSUE THREAD

**Issue by Bytegm** [brandon3055/Draconic-Evolution#1522]
When translating the mod to Russian there is not enough space for text on the GUI elements.  If not difficult, then make their size larger. I think this will be useful when translating into other languages.
![Screenshot Advanced Translocator GUI](https://user-images.githubusercontent.com/45900969/130367172-d6c029f2-e80b-4d61-ace4-5b5b8b234d98.jpg)
![Screenshot Mob frinder GUI](https://user-images.githubusercontent.com/45900969/130367174-512f0b13-d17d-4b13-b53c-eb2d1e52e006.jpg).

And one more question. Why specify the module tier on the "Module Type" line? The module level is already in its name.
![Скриншот 22-08-2021 210346](https://user-images.githubusercontent.com/45900969/130367450-0b68695b-78c1-404c-ac50-bba239d3c577.jpg)

**Comment by brandon3055** [comment]
I generally do try to leave some extra room to help with translations but sometimes I am working with limited space and try to 'squeeze things in' 
I have increased the width of these GUI's by 20. Hopefully that will help. Other than that maybe try re-wording things if possible? I don't speak Russian so forgive me if that's a dumb suggestion. 

Let me know if this helps. I can expand them a bit more but I would rather not.
https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.12.398/Draconic-Evolution-1.16.5-3.0.12.398-universal.jar

**Comment by FoxMcloud5655** [comment]
About your question; sometimes modpack authors like to change the names of certain items.  This ensures that if people look the item up in JEI, they can still find it.

**Comment by brandon3055** [comment]
Ahh yes I was going to mention that. The reason I made that way is the "module type" is completely separate from the module 'item' it's attached to. So it is possible for the module name to not mention the tier. But realistically all modules will most likely include the tier in their name. And on top of that, the module type is colour coded so I can probably drop the redundant tier prefix.
![](https://ss.brandon3055.com/8e13f)
![](https://ss.brandon3055.com/3add7)
![](https://ss.brandon3055.com/d8b82)
![](https://ss.brandon3055.com/45c76)

**Comment by FoxMcloud5655** [comment]
I had forgotten about the color coding!  That's actually a much better way of doing it.

That's my fault.  Though, I still stand by the fact that if they weren't, having the tier in there is more helpful than it isn't.

**Comment by Bytegm** [comment]
> I generally do try to leave some extra room to help with translations but sometimes I am working with limited space and try to 'squeeze things in'
> I have increased the width of these GUI's by 20. Hopefully that will help. Other than that maybe try re-wording things if possible? I don't speak Russian so forgive me if that's a dumb suggestion.
> 
> Let me know if this helps. I can expand them a bit more but I would rather not.
> https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.12.398/Draconic-Evolution-1.16.5-3.0.12.398-universal.jar

Thank you for your understanding! This solved the problem of lack of space for the mob grinder and advanced dislocator. The same situation is with the Draconic Reactor GUI. There is not enough horizontal space for just 1 character on the "Redstone Mode" button. And also 4 symbols for the drop-down block of options for this button.
![Скриншот 24-08-2021 020533](https://user-images.githubusercontent.com/45900969/130534548-d0d1df3a-85aa-4e65-87fc-1607f6ff7f0a.jpg)

I also found a couple of bugs:
1. The drop-down block on the right continues to remain active after the complete shutdown of the reactor.
2. When you hover over an option, the description is not displayed.
![Скриншот 24-08-2021 015810](https://user-images.githubusercontent.com/45900969/130535612-c15bc365-3a81-45d5-bea0-91c7c56f93de.jpg)

And in the GUI of gates, 4 characters do not fit into the "Apply" button, and it is impossible to shorten this word.
![Скриншот 24-08-2021 032204](https://user-images.githubusercontent.com/45900969/130536837-c1aef2b3-a7f4-408f-a12b-e3d74d1a97f0.jpg)

**Comment by brandon3055** [comment]
I can't really make the reactor gui any wider because it has not been converted to my more modular gui format yet. So I expanded the buttons as much as I could with the available space. 
You could also shorten `Fuel (in) / Chaos (out) to `Fuel / Chaos` or better `Draconium / Chaos` if it will fit. The reason being in 1.16 you can now add chaos as well as remove it so it's no longer strictly 'input/output'

https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.12.402/Draconic-Evolution-1.16.5-3.0.12.402-universal.jar
https://maven.covers1624.net/com/brandon3055/brandonscore/BrandonsCore/1.16.5-3.0.9.233/BrandonsCore-1.16.5-3.0.9.233-universal.jar
https://maven.covers1624.net/codechicken/CodeChickenLib/1.16.5-4.0.3.431/CodeChickenLib-1.16.5-4.0.3.431-universal.jar
You will need all three of these because I am in the process of making changes to DE which require newer versions of CCL and BrandosCore

**Comment by Bytegm** [comment]
> I can't really make the reactor gui any wider because it has not been converted to my more modular gui format yet. So I expanded the buttons as much as I could with the available space.
> You could also shorten `Fuel (in) / Chaos (out) to `Fuel / Chaos`or better`Draconium / Chaos` if it will fit. The reason being in 1.16 you can now add chaos as well as remove it so it's no longer strictly 'input/output'
> 
> https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.12.402/Draconic-Evolution-1.16.5-3.0.12.402-universal.jar
> https://maven.covers1624.net/com/brandon3055/brandonscore/BrandonsCore/1.16.5-3.0.9.233/BrandonsCore-1.16.5-3.0.9.233-universal.jar
> https://maven.covers1624.net/codechicken/CodeChickenLib/1.16.5-4.0.3.431/CodeChickenLib-1.16.5-4.0.3.431-universal.jar
> You will need all three of these because I am in the process of making changes to DE which require newer versions of CCL and BrandosCore

Thanks, now everything is fine.

Found a crash when disable snapping

https://user-images.githubusercontent.com/45900969/130705463-584ae03b-3c02-4b54-b9a9-6db29f8f7c04.mp4

**Comment by brandon3055** [comment]
Cool! and thanks for the bug report. That will be fixed in the next update.
