### ISSUE TITLE
[1.16] java.util.ConcurrentModificationException(HashMap run on Muti-Thread Exception)

### ISSUE THREAD

**Issue by TheSmileCat** [brandon3055/Draconic-Evolution#1525]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.11.396
* Minecraft Forge version: 36.2.2
* Mod Pack: (if applicable)

### Crash report
[crash-2021-08-31_13.18.38-fml.txt](https://github.com/brandon3055/Draconic-Evolution/files/7081746/crash-2021-08-31_13.18.38-fml.txt)

### Description / steps to reproduce
On Client Launching.

### Suggest
Create a copy with key set or value set to foreach, do not foreach at original HashMap 
(if you use foreach in HashMap on Muti-Thread)

**Comment by brandon3055** [comment]
This should be fixed in the latest release. (version 3.0.12)
