### ISSUE TITLE
[1.16] crash

### ISSUE THREAD

**Issue by KostromDan** [brandon3055/Draconic-Evolution#1528]
## Base information
* Minecraft version: 1 16 5
* Mod version: 406
* Minecraft Forge version: 36 2 4
* Mod Pack: (if applicable)

### Crash report
(If applicable)

### Description / steps to reproduce

crash when scrolling creative menu
[crash-2021-09-03_15.14.40-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/7105786/crash-2021-09-03_15.14.40-client.txt)

**Comment by FoxMcloud5655** [comment]
Try reproducing this without Optifine.

**Comment by KostromDan** [comment]
> Try reproducing this without Optifine.

Same without optifine.
[crash-2021-09-04_22.36.27-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/7110408/crash-2021-09-04_22.36.27-client.txt)

**Comment by KostromDan** [comment]
https://user-images.githubusercontent.com/90044015/132106222-55b0c664-39e7-47f3-a380-5b95ac0cd9e2.mp4

**Comment by FoxMcloud5655** [comment]
Looking through the crash report, it seems like this is indeed a bug.  Doesn't appear to happen with any other mod, and all related mods are fully up-to-date.  Affected line is as follows:
https://github.com/brandon3055/Draconic-Evolution/blob/c99b106b25b5665b23eb3aa040cb0af1067fafe5/src/main/java/com/brandon3055/draconicevolution/client/render/item/RenderModularChestpeice.java#L131

**Comment by KostromDan** [comment]
> Looking through the crash report, it seems like this is indeed a bug. Doesn't appear to happen with any other mod, and all related mods are fully up-to-date. Affected line is as follows:
> https://github.com/brandon3055/Draconic-Evolution/blob/c99b106b25b5665b23eb3aa040cb0af1067fafe5/src/main/java/com/brandon3055/draconicevolution/client/render/item/RenderModularChestpeice.java#L131

I've done many tests and i found a reason. I have a laptop and to ensure greater energy saving i disabled my rtx 3070 mobile and minecraft was running on intel integrated gpu. Now i turned on my rtx 3070 and it doesent crash.

**Comment by KostromDan** [comment]
https://user-images.githubusercontent.com/90044015/132107274-f27de0fb-7a4f-4200-8ff2-1dc84750d470.mp4

**Comment by tweakbsd** [comment]
It also crashes on Radeon RX580 on my MBP 2016. Same if I use the integrated Intel Iris iGPU. Basically I can't play anymore cause always the Wyvern Chestpiece is shown somewhere my game is gone. Only way to play is disabling all shaders in the config file. Hope this get's fixed soon. On

**Comment by FoxMcloud5655** [comment]
Test build is already out for the testers.  Once they can validate (or we don't hear that it still crashes) that it's all good, it will be published to CurseForge.

**Comment by brandon3055** [comment]
The build i pushed to curse earlier today should fix this issue. (version 3.0.13)

**Comment by longhirar** [comment]
Same exact thing happened in version 3.0.18.428.

I'm running with an AMD Radeon RX 570 and I don't have integrated graphics to test with.

Mods loaded:
![image](https://user-images.githubusercontent.com/72895064/147144452-bd2a2d0f-8595-425a-98bb-22856fb0aee4.png)


[latest.log](https://github.com/brandon3055/Draconic-Evolution/files/7764732/latest.log)
[hs_err_pid17624.log](https://github.com/brandon3055/Draconic-Evolution/files/7764736/hs_err_pid17624.log)
