### ISSUE TITLE
[1.12] Dislocators ignoring pitch/yaw NBT data and looking directly up/down when teleporting

### ISSUE THREAD

**Issue by ashridah** [brandon3055/Draconic-Evolution#1529]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.28.354
* Minecraft Forge version: 14.23.5.2855
* Mod Pack: (Omnifactory, dev build abfab61)

### Crash report
(no crash)

### Description / steps to reproduce

When using dislocators (in pedestals), the pitch and yaw information is being ignored/misinterpreted, and my character spawns looking directly down and facing due north.

The dislocator is created normally (standing, facing the direction I want to spawn, then shift-click to set the nbt data for the dislocator) and then placed into a pedestal in the other dimension. The nbt data appears correct when inspected (pitch is only 1 or 2 degrees off of 0, yaw is 318ish or so, pointing south-east. (See the attached screenshot for example.)

However, when I spawn in, I'm facing directly due north, and turned all the way down to look directly at the ground.

This repeats for most of the dislocators I've created, except for the dislocator that goes to the nether (seems to be behaving normally) and the end (seems to be pointing straight up instead).

If i roll back to DE 2.3.27.353 and reload the save, all of the existing dislocators function as expected, I teleport in, with the direction I was expecting to be facing. If I roll forward to 354, they stop working, and I'm facing the ground when I teleport.

As Omnifactory does not have a standard overworld dimension (it has Lost Cities as the default, and a void dimension as an optional dimension available early game), so I can't easily check there to see if it's just these dimensions causing problems, unfortunately.

<img width="648" alt="2021-09-04_13 47 43" src="https://user-images.githubusercontent.com/3069777/132108753-7b92c0bc-c319-47c2-b281-fd94ac7764e0.png">

**Comment by brandon3055** [comment]
This is an issue with a recent fix I implemented for better portals. This will be fixed the next time I push a 1.12 update.
