### ISSUE TITLE
[SUGGESTION] Draconic Hoe Inventory/size

### ISSUE THREAD

**Issue by p455w0rd** [brandon3055/Draconic-Evolution#153]
I like to put soulbound on all my items, but the draconic hoe has no inventory for me to do so. It also cannot be enchanted in an anvil. Also it would be nice to be able to define the size of the area being tilled.

**Comment by brandon3055** [comment]
These changes have been implemented and will be available in snapshot 10. The hoe wont have an enchantment inventory but it should be possible to enchant it.
