### ISSUE TITLE
[1.16] Minecraft crashes

### ISSUE THREAD

**Issue by Eric9922** [brandon3055/Draconic-Evolution#1530]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.13.408
* Minecraft Forge version: 36.2.2
* Mod Pack: (if applicable)

### Crash report
[hs_err_pid6008.log](https://github.com/brandon3055/Draconic-Evolution/files/7120587/hs_err_pid6008.log)

### Description / steps to reproduce
When I open my inventory or press F5, Minecraft crashes. But as soon as I clear my Draconic Chestplate from my inventory everything works again.

**Comment by FoxMcloud5655** [comment]
Ensure that CodeChickenLib is up-to-date.  If that doesn't work, ensure you're using your actual GPU and not any kind of integrated graphics.  If that doesn't work, make sure you're not running with Optifine.  If that doesn't work or you don't have it, try turning off shaders in DE's config.

**Comment by Eric9922** [comment]
I don't use optifine and code chicken lib is on version 4.0.3.433

**Comment by Eric9922** [comment]
I don't use optifine and code chicken lib is on version 4.0.3.433

**Comment by FoxMcloud5655** [comment]
What about the other two steps?

**Comment by Eric9922** [comment]
I have now disabled the shaders and everything works fine now

**Comment by brandon3055** [comment]
Try this DE build.
https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.13.410/Draconic-Evolution-1.16.5-3.0.13.410-universal.jar

**Comment by Eric9922** [comment]
thank you

**Comment by brandon3055** [comment]
Did that fix the issue?
