### ISSUE TITLE
[1.16] Mob Spawning

### ISSUE THREAD

**Issue by Eric9922** [brandon3055/Draconic-Evolution#1531]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.13.408
* Minecraft Forge version: 36.2.2
* Mod Pack: (if applicable)

### Crash report
(If applicable)

### Description / steps to reproduce
Mobs can spawn on the Energy Core.

**Comment by brandon3055** [comment]
Will be fixed in the next update.
