### ISSUE TITLE
[1.16] [Android] Render crash with shaders.

### ISSUE THREAD

**Issue by tavimxis7** [brandon3055/Draconic-Evolution#1532]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.13.408
* Minecraft Forge version: 1.16.5 - 36.2.0
* Mod Pack: A modified version by me of All the Mods 6

### Description / steps to reproduce
My game crashes when I go to my jei and type @draconic (this also goes for the draconic mod creative play mode tab)
the crash log says it's something related to rendering the wyvern chestpiece. Can you help me ? (Sorry if English is wrong, I'm Brazilian)

### Crash log
https://pastebin.com/8Rn07CxG

**Comment by brandon3055** [comment]
Please check if this makes a diference. 
https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.13.410/Draconic-Evolution-1.16.5-3.0.13.410-universal.jar

**Comment by tavimxis7** [comment]
no, still with the same error.

**Comment by brandon3055** [comment]
You forgot to mention your using Android. Draconic evolutions shaders simply don't work on android and there is nothing I can do about that.
Turn off all shaders in both the Draconic Evolution and Brandons Core config files and it will *probably* work. But I can't make any promises.
