### ISSUE TITLE
[1.16] <Incorrect CodeChikenLib versioning makes it impossible to start minecraft>

### ISSUE THREAD

**Issue by Cynix32** [brandon3055/Draconic-Evolution#1533]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.14.411-universal
* Minecraft Forge version: 36.2.4
* Mod Pack: Its my own personal modpack

### Crash report

I think a screenshot is more than enough for this:
![Screenshot (237)](https://user-images.githubusercontent.com/69455883/132837899-e251466a-e44b-4655-ae68-91fa14413383.png)

(ignore the ironjetpacks & nocreativedrift, I am planning to open a separate issue for those mods on their respective github)

### Description / steps to reproduce
The CodeChickenLib available on curseforge is only CodeChickenLib-1.16.5-4.0.3.433-universal
DE asks for 4.0.3.434 which from what I know does not exist yet as of writing of this issue.
See:
https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/3448050
CCL was last updated Sept. 3

**Comment by Bytegm** [comment]
I also encountered this problem. 
But you can download manually here:
https://nexus.covers1624.net/repository/maven-releases/codechicken/CodeChickenLib/1.16.5-4.0.3.434/CodeChickenLib-1.16.5-4.0.3.434-universal.jar

**Comment by ModernGamingWorld** [comment]
I also just Encountered this Problem

**Comment by brandon3055** [comment]
I think there is an issue with the way covers and I are handling versioning. I just pushed a new build which should fix the issue.

**Comment by Cynix32** [comment]
Issue fixed after updating DE & its core dependency, closing issue.

**Comment by ModernGamingWorld** [comment]
@brandon3055 Covers just released the version you wanted to use https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/3456069

**Comment by brandon3055** [comment]
I am aware. The issue was DE should not require that version. Covers changed the way versions are handled in 1.16 so I need to change the way my dependencies are configured to account for that.

**Comment by ModernGamingWorld** [comment]
ah okay
