### ISSUE TITLE
[1.16] Crashing ATM6 server.

### ISSUE THREAD

**Issue by Jauska** [brandon3055/Draconic-Evolution#1534]
## Base information
* Minecraft version: 1.16
* Mod version: Draconic-Evolution-1.16.5-3.0.12.403-universal
* Minecraft Forge version: forge-1.16.5-36.2.2
* Mod Pack: (if applicable) ATM6 -Server pack

### Crash report
(If applicable)
[crash-2021-09-10_16.17.23-fml.txt](https://github.com/brandon3055/Draconic-Evolution/files/7147861/crash-2021-09-10_16.17.23-fml.txt) https://pastebin.com/fYMkC1BK 
[latest.log](https://github.com/brandon3055/Draconic-Evolution/files/7147865/latest.log) https://pastebin.com/t5FJ7Sj4 

### Description / steps to reproduce
Add Draconic evolution and its dependencies to the atm6  server and try to launch the server. In the client the mods work fine.

**Comment by brandon3055** [comment]
Your using an old test build that was never even released to curse. ATM6 now includes the latest version of DE. Update and your issue will be solved.
