### ISSUE TITLE
[1.16] upgrading a tool loses it's modules and enchants

### ISSUE THREAD

**Issue by RedStorm1024** [brandon3055/Draconic-Evolution#1535]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.11.396
* Minecraft Forge version: 36.2.0
* Mod Pack: Custom modpack made by a friend, can give the list of mods if needed

### Description / steps to reproduce

When you upgrade tools with fusion crafting, it gives the right tool but without enchants or modules (done with a wyvern to draconic sword for me but i assume it's the same for every tier/type of tool)

It might be hard to keep the modules of every tool when merging them into a staff of power but in that case maybe you could disable fusion crafting if one of the tools still has modules in it

**Comment by FoxMcloud5655** [comment]
This is a known issue as the functionality has yet to be coded.  It's not an issue per se, more of still a WIP.  Fusion Crafting is still just hacked in just to make it work functionally while it's being rewritten, so after that system is fully functional, then the effort will be made to make this compatible.

In the meantime, it's a simple matter to just pull out all the modules before upgrading it.

**Comment by brandon3055** [comment]
This will be fixed in the next update.
