### ISSUE TITLE
[1.16] Update 3.0.15.414

### ISSUE THREAD

**Issue by PlatiniumOfficial** [brandon3055/Draconic-Evolution#1536]
## Base information
Since the launch of the modpack the game crashes no crash report and only with the update of draconic evolution.

### Crash report
https://hastebin.com/kejeciwawu.sql

**Comment by zISKo666** [comment]
Hi there,

Having the same issue.

**Comment by Cynix32** [comment]
Reporting the same issue, reverting back to the previous update solves the problem.
MC 1.16.5
Forge 36.2.2

**Comment by PlatiniumOfficial** [comment]
307748f3e8a30b2740f7876b191dfbf355c20188 The problem should be fixed for the next update or at the plu cation of the fixed in expectation brandon to remove the version 414 I close the topic.

Thank you.

**Comment by FoxMcloud5655** [comment]
Was just about to say the same thing.  Good.

**Comment by brandon3055** [comment]
New version was pushed to curse 25 minutes ago. Still waiting for it to be approved. I guess curse is running a little slower than normal today.

**Comment by PlatiniumOfficial** [comment]
It's good it's public on curse ^^.

No problem I just closed by indicating the fix to try to help a little can not being developer I thought it was a good idea :p or not ^^.
