### ISSUE TITLE
[1.16] Corrupted?

### ISSUE THREAD

**Issue by Fatsharky** [brandon3055/Draconic-Evolution#1538]
9/12/2021 i received an update for "Code Chicken Lib" and applied the update and now when i go to load into my world i have played on for more then a week by now and the game crashes instantly as soon as i load in and i loaded the game 32 times just to see if i can still get it to work but i can't. i just want to know if that is a chance that my whole world is now corrupted from the update i had to do from "Code Chicken Lib" witch was something that came with the mod "Draconic evolution" on curse forge. if this helps to say i can tell you that i had the wyvern sword and the wyvern chest armor and that is all i had made from that mod so far. i am a bit sad since this happened i hope to still play on that world and i made so much progress but if you can find out if my world could be doomed i would like to know before i just throw everything away. Thank you for your time and most importantly your time and effort :D
[Crash report.txt](https://github.com/brandon3055/Draconic-Evolution/files/7149922/Crash.report.txt)

**Comment by FoxMcloud5655** [comment]
Disable shaders in Draconic Evolution's config.  That should at least get you loaded into the game.

**Comment by Fatsharky** [comment]
oh my that worked, thank you so much!! your awesome :D
