### ISSUE TITLE
Crash using Energy Multiblock in 1.0.2-Snapshot_3

### ISSUE THREAD

**Issue by Compegen** [brandon3055/Draconic-Evolution#154]
Getting memory crash in version 1.0.2-Snapshot_3, even though 4 gigs are allocated (normally for massive mod pack, just isolated this mod for this). Happens when right-clicking on an activated energy core. Can be reproduced.

Latest Log: http://pastebin.com/j7LNA0ng

Crash Log: http://pastebin.com/sBCPDKux
Description: Ticking memory connection

**Comment by spannerman79** [comment]
Dupe #147

**Comment by GreatOrator** [comment]
Same bug recognized in earlier report.  Will close as it is being worked on for an upcoming update.
