### ISSUE TITLE
[1.16] module does not remain in the tools in multiplayer on server

### ISSUE THREAD

**Issue by Elvundil** [brandon3055/Draconic-Evolution#1542]
## Base information
* Minecraft version:1.16.5
* Mod version: 3.0.15.415
* Minecraft Forge version:36.2.0
* Mod Pack: (if applicable) Ragnamod 6

### Crash report
no crash report

### Description / steps to reproduce
the modules do not remain saved in the tools (chaotic staff of power and chaotic bow in my inventory) when I play on the server no problem in single player .
but it remains in the chaotic chest piece.

**Comment by Elvundil** [comment]
sorry for this after having searched more in depth it seems that it comes from my server

**Comment by brandon3055** [comment]
You are most likely experiencing the known issue where switching to creative (on a server) can clear modular item's data. This is a forge capability bug that I am currently unable to fix.

**Comment by Elvundil** [comment]
ok, thank you for your reply(I had a synchronization problem on my server who is settled so I thought it would have come from that).
