### ISSUE TITLE
[1.16] <Title>

### ISSUE THREAD

**Issue by TheSatanicFlame** [brandon3055/Draconic-Evolution#1544]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.15.415
* Minecraft Forge version: 36.2.4
* Mod Pack: (if applicable)

List:
inzhefop's Core (by inzhefop)
Spartan Weaponry (by ObliviousSpartan)
Botania (by Vazkii)
Waystones (by BlayTheNinth)
Cloth Config API (Forge) (by shedaniel)
Flux Networks (by sonar_sonic)
Performant (by someaddon)
Dynamic Trees - Forbidden And Arcanus (by supermassimo0310)
mGui (by mickelus)
Obfuscate (by MrCrayfish)
Polymorph (Forge) (by TheIllusiveC4)
Mantle (by mDiyo)
PackagedAuto (by TheLMiffy1111)
Stalwart Dungeons (by Furti_Two)
FTB Library (Forge) (by FTB)
Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
FTB Teams (Forge) (by FTB)
Mini Utilities (by OneLemonyBoii)
Structure Gel API (by ModdingLegacy)
AutoRegLib (by Vazkii)
Brandon's Core (by brandon3055)
Draconic Evolution (by brandon3055)
When Dungeons Arise - Forge! (by Aureljz)
Macaw's Roofs (by sketch_macaw)
Citadel (by alex_khaan)
Thermal Innovation (by TeamCoFH)
Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
Dynamic Trees - Biomes O' Plenty (by cadaverous_queen)
Cyclic (by Lothrazar)
Dungeons Plus (by ModdingLegacy)
Macaw's Paintings (by sketch_macaw)
Silent's Gems (by SilentChaos512)
Cooking for Blockheads (by BlayTheNinth)
Biomes O' Plenty (by Forstride)
Simple Generators (by TeamKrypticLink)
Dynamic Trees - Quark (by supermassimo0310)
Mekanism Additions (by bradyaidanc)
Titanium (by Buuz135)
Simple Farming (by enemeez1)
Blood Magic (by WayofTime)
Create Plus (by Robocraft999)
Mowzie's Mobs (by bobmowzie)
Valhelsia Core (by ValhelsiaTeam)
Just Enough Items (JEI) (by mezz)
Create Automated (by kotakotik22)
Wilds (by spicybananamodding)
Serene Seasons (by TheAdubbz)
FFS - Fancy Fluid Storage (by Lordmau5)
Tinkers Construct (by mDiyo)
Akashic Tome (by Vazkii)
Thermal Locomotion (by TeamCoFH)
Dynamic Trees (by ferreusveritas)
Chicken Chunks 1.8.+ (by covers1624)
Psi (by Vazkii)
Applied Energistics 2 (by AlgorithmX2)
Inventory Pets (by Purplicious_Cow_)
More Create Stuffs (by JerryLu086)
Thermal Cultivation (by TeamCoFH)
Tetra (by mickelus)
Simple Storage Network (by Lothrazar)
Atum 2: Return to the Sands (by Shadowclaimer)
Macaw's Fences and Walls (by sketch_macaw)
CodeChicken Lib 1.8.+ (by covers1624)
Exotic Birds (by ThePavoReality)
Astral Sorcery (by HellFirePvP)
Forbidden and Arcanus (by cesar_zorak)
Pipez (by henkelmax)
Storage Drawers (by Texelsaur)
Mystical Agradditions (by BlakeBr0)
Architect's Palette (by Jsburg)
Just Enough Resources (JER) (by way2muchnoise)
Mekanism (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Flywheel (by jozufozu)
Stoneholm, Underground Villages (Forge) (by TheGrimsey)
Curios API (Forge) (by TheIllusiveC4)
Advent of Ascension (Nevermine) (by Scimiguy)
Traveler's Backpack (by Tiviacz1337)
Macaw's Windows (by sketch_macaw)
Ender Storage 1.8.+ (by covers1624)
Simple Voice Chat (by henkelmax)
Lollipop (by owmii)
Budschie's Morph Mod (by budschie_)
Dank Storage (by tfarecnim)
GeckoLib (by ThanosGecko)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
LazierAE2 (by DamnRelentless)
Thermal Foundation (by TeamCoFH)
Silent Lib (silentlib) (by SilentChaos512)
Ice and Fire: Dragons (by alex_khaan)
ConnectedTexturesMod (by tterrag1098)
Environmental Core (by ValkyrieofNight)
BetterF3 (by cominixo)
BlockCarpentry (by PianoManu)
Morph-o-Tool (by Vazkii)
Industrial Foregoing (by Buuz135)
Chisel (by tterrag1098)
Patchouli (by Vazkii)
Paintings ++ (by AbsolemJackdaw)
ObserverLib (by HellFirePvP)
Quark (by Vazkii)
Immersive Engineering (by BluSunrize)
Doggy Talents (by percivalalb)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
My Hero Academia (by R3TR0st)
Mahou Tsukai (by stepcros)
YUNG's API (Forge) (by YUNGNICKYOUNG)
♪ Boss Music Mod ♪ (by my_name_is_krossy)
FTB Ultimine (Forge) (by FTB)
RandomPatches (Forge) (by TheRandomLabs)
Powah! (by owmii)
Create Gears (by kotakotik22)
Create (by simibubi)
Iron Generators [Forge] (by inzhefop)
YUNG's Extras (Forge) (by YUNGNICKYOUNG)
CreateFoodAdditions (by StacheGamer_Sebastian)
Create Addon (by celsiusqc)
Architectury API (Forge) (by shedaniel)
Aquaculture 2 (by Shadowclaimer)
Environmental Tech (by ValkyrieofNight)
Macaw's Lights and Lamps (by sketch_macaw)
ValkyrieLib (by ValkyrieofNight)
Farmer's Delight (by vectorwing)
Numina (by machinemuse)
Modular Powersuits (by machinemuse)
Pyromancer (by nikgub_)
Lemon Lib (by OneLemonyBoii)
Mouse Tweaks (by YaLTeR)
Iron Chests (by ProgWML6)
The Twilight Forest (by Benimatic)
Mana and Artifice (by AWildCanadianEh)
Farmer's Delight Compats (by burritoeatinghamster)
Mystical Agriculture (by BlakeBr0)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Cucumber Library (by BlakeBr0)
Create Crafts & Additions (by MRHminer)
Spartan Shields (by ObliviousSpartan)
Growable Storage Cells 2 (by Trhod177)
Project: Vibrant Journeys (by OrderedChaosDev)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Ars Nouveau (by baileyholl2)
Alex's Mobs (by alex_khaan)
Macaw's Furniture (by sketch_macaw)
Macaw's Bridges (by sketch_macaw)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Chisels & Bits (by AlgorithmX2)
Pandoras Creatures (by andrew0030)
Create : Stuff Additions (by Furti_Two)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Farmer's Delight Integration (by iku_tv)
CoFH Core (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
FTB Chunks (Forge) (by FTB)
Silent Gear (by SilentChaos512)
Dungeon Crawl (by xiroc_)
Macaw's Trapdoors (by sketch_macaw)
Create Deco (by talrey)
Comforts (Forge) (by TheIllusiveC4)
Dungeons Mod (by dainxt)
BetterEnd (Forge) (by Beethoven92)
Macaw's Doors (by sketch_macaw)
Dynamic Trees - Atum 2 (by supermassimo0310)
AE2 Extras (by tfarecnim)
Tetra Pak (by noobulus__)

### Crash report
https://pastebin.com/Sr7Juz9f
### Description / steps to reproduce

Just start the modpack and it said "Draconic Evolution (daconicevolution) encountered an error during the complete event phase"

**Comment by FoxMcloud5655** [comment]
This kind of error can happen if you minimize the Minecraft window while it's still loading or put it into the background and start doing other things on your computer while it's loading.  Minecraft 1.16.5 is very sensitive about that kind of thing, unlike previous Minecraft versions.

Try loading the modpack again while keeping your focus inside the Minecraft window.

**Comment by brandon3055** [comment]
This is an issue related to the fact that mod loading is now multi-threaded. I'm trying to iterate over a list while another mod just happens to be modifying that list at the same time. I thought I fixed this by making my code run later but apparently, someone else had the same idea.
