### ISSUE TITLE
[1.16] <Title>

### ISSUE THREAD

**Issue by Nqwq** [brandon3055/Draconic-Evolution#1546]
In the Minecraft Version 1.16.5, I use Draconic-Evolution-1.16.5-3.0.15.415-universal.jar.My client will crash when I open the mod's inventory.I love this mod and I hope the author fixes this bug.

**Comment by FoxMcloud5655** [comment]
Turn off shaders in the DE config.

**Comment by brandon3055** [comment]
Cant investigate this crash without a crash report.
