### ISSUE TITLE
[1.16] Draconium ore generation seems very low

### ISSUE THREAD

**Issue by patw** [brandon3055/Draconic-Evolution#1547]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.14.412-universal
* Minecraft Forge version: 36.2.4
* Mod Pack: Custom

### Crash report
No crash

### Description / steps to reproduce
No mods installed that impact oregen (afaik).  Using a builder block quarry, grabbing a 64x64 area down to bedrock I'll get 7-10 draconium dust.  Not sure what the frequency should be but it seems really low compared to the 1.12.x version with default settings.  Same problem in nether, I can fly around forever and not see a draconium ore.

**Comment by FoxMcloud5655** [comment]
That is 100% intended.

The Nether is your place to find big rare patches of Draconium Ore, the Overworld is your place to find extremely small and semi-rare Draconium Ore patches, and The End is where you find consistently medium patches of Draconium Ore.

**Comment by patw** [comment]
Thanks for the reply! I checked the code, and I didn't see any config vars for modifying this behaviour.  I'm building a pack and looking to have the players progress DE a bit earlier than getting to the end.  Is there a plan to allow this to be configurable in the future?  Or is there a better way to mess with DE orgen outside of the mod?

**Comment by FoxMcloud5655** [comment]
It is not configurable as of right now.  Most of the major features still need to be coded in before QoL things are written, so it may be a while before you see this feature.

**Comment by patw** [comment]
Fair enough, I'll close this one out as it's not really a bug.
