### ISSUE TITLE
[1.16] Weird visual bug

### ISSUE THREAD

**Issue by AimUprr** [brandon3055/Draconic-Evolution#1548]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.14.412
* Minecraft Forge version: 36.2.4
* Mod Pack: ATM 6

### Description / steps to reproduce

I was playing normally on a server, with sum people, but yesterday I started having visual bugs like this
![image](https://user-images.githubusercontent.com/59490875/134519636-990863e9-75e3-436f-a998-be40cb20c054.png)

At the time I thought it was my Minecraft being weird, and because the other player left It stopped
but today I figured out it only happens when my camera is directed at the armor.

(Without the armor)
![image](https://user-images.githubusercontent.com/59490875/134520044-1fbf7aed-635a-4812-93b9-cae83539d2ef.png)

**Comment by brandon3055** [comment]
This looks like the common optifine fast render bug. If you are using optifine with its fast render enabled it simply does not work with DE's shaders.

**Comment by AimUprr** [comment]
Yet that fixed it, ty
