### ISSUE TITLE
[1.16] Draconic Ore still spawns in the end while disabled.

### ISSUE THREAD

**Issue by hacktheplanet86** [brandon3055/Draconic-Evolution#1549]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.15.415 Beta
* Minecraft Forge version: 36.2.0
* Mod Pack: Custom Modpack

### Crash report
No Crash

### Description / steps to reproduce
Disable end ore generation in the config.  End draconium ore still spawns in the end.  Pretty simple :P.  I'm making a pack where draconium ore should only spawn in the nightmare dimension using oretweaker which is working fine, overworld and nether ore are able to be turned off just fine via built in config.  Seems to be only the end ore that doesn't like to cooperate.  I just made another oretweaker script to remove it manually for now, which also works fine.

**Comment by brandon3055** [comment]
This will be fixed in the next update.
