### ISSUE TITLE
Lore Localization error with caveworld mod

### ISSUE THREAD

**Issue by Ianaver** [brandon3055/Draconic-Evolution#155]
Well for some reason when MC detects this error, I get a "crash" but the only thing it spits out is this log, the error is what for some reason throws everything off. There is no set amount of time that this will happen after, I just happen to notice that it happens about after 10-30 minutes

http://paste.ubuntu.com/12505561/

Edit: this is a problem with the caveworld mod and the tools; I am attempting to fix this by setting in the config to "fake the base tool" and maybe stop the mod from reading non existent lore localization

Edit 2: sadly my "trick" didn't work... :(

**Comment by GreatOrator** [comment]
What version of brandon's core are you using?  I haven't seen this using 1.0.0.6 ans snapshot 3 of DE

**Comment by Ianaver** [comment]
Sorry about that, yes I was using 1.0.0.6 (core) and snpsht 3 of DE

**Comment by GreatOrator** [comment]
Are you using this on a cauldron server or just a forge server?

**Comment by brandon3055** [comment]
Ok thats just weird... Looks like my lore code is trying to run on vanilla tools which obviously dont have lore localization. I dont even know how that is possible... And even if that is the case it should not crash the game it should just keep spamming that message whenever you mouse over a vanilla tool.

**Comment by brandon3055** [comment]
whats even weirder is it looks like java itself actually crashed not minecraft. Although i have no idea if that is what actually happened there

**Comment by Ianaver** [comment]
No server only single player

**Comment by Ianaver** [comment]
also, I am forced to use java 8 v51 because with v60 it kills my graphics driver. I have an old core 2 duo CPU and the driver for some reason is no longer supported by java at that version and intel ended support for the driver a while back

**Comment by GreatOrator** [comment]
That may be part of the issue, as far as I am aware java 8_25 works, but have untested higher versions

**Comment by Ianaver** [comment]
All I know is that THAT was the last thing I see on the log everytime it crashes

**Comment by Ianaver** [comment]
Also that's not a list of vanilla tools that its trying to read the localization rather that from the cave world mod which uses the vanilla and modded tools to create new "mining" versions.

**Comment by brandon3055** [comment]
I made a minor tweak in one of the later versions that may or may not fix this issue but if it doesn't there really isn't much more i can do on my end...
