### ISSUE TITLE
[1.16] Crash when trying to render DE item in JEI

### ISSUE THREAD

**Issue by mtbrenner** [brandon3055/Draconic-Evolution#1550]
## Base information
* Minecraft version: 1.16.5
* Mod version: 1.16.5-3.0.15.415
* Minecraft Forge version: 36.2.4
* Mod Pack: (if applicable) FTB OceanBlock 1.1.0

### Crash report
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.opengl.GL20C.nglShaderSource(IIJJ)V+0
j  org.lwjgl.opengl.GL20C.glShaderSource(ILjava/lang/CharSequence;)V+38
j  org.lwjgl.opengl.GL20.glShaderSource(ILjava/lang/CharSequence;)V+2
j  codechicken.lib.render.shader.AbstractShaderObject.alloc()V+64
j  codechicken.lib.render.shader.ShaderProgram$$Lambda$24135.accept(Ljava/lang/Object;)V+4
J 18402 C2 java.util.ArrayList.forEach(Ljava/util/function/Consumer;)V (75 bytes) @ 0x00000000052affac [0x00000000052afee0+0xcc]
j  codechicken.lib.render.shader.ShaderProgram.compile()V+39
j  codechicken.lib.render.shader.ShaderProgram.pushCache()Lcodechicken/lib/render/shader/UniformCache;+1
j  com.brandon3055.draconicevolution.client.render.item.ToolRenderBase.getShaderType(Lnet/minecraft/client/renderer/RenderType;Lcom/brandon3055/brandonscore/api/TechLevel;Lcodechicken/lib/render/shader/ShaderProgram;F)Lcodechicken/lib/render/shader/ShaderRenderType;+1
j  com.brandon3055.draconicevolution.client.render.item.ToolRenderBase.getShaderType(Lnet/minecraft/client/renderer/RenderType;Lcom/brandon3055/brandonscore/api/TechLevel;Lcodechicken/lib/render/shader/ShaderProgram;)Lcodechicken/lib/render/shader/ShaderRenderType;+4
j  com.brandon3055.draconicevolution.client.render.item.RenderModularPickaxe.renderTool(Lcodechicken/lib/render/CCRenderState;Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/model/ItemCameraTransforms$TransformType;Lcodechicken/lib/vec/Matrix4;Lcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;ZI)V+248
j  com.brandon3055.draconicevolution.client.render.item.ToolRenderBase.renderItem(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/model/ItemCameraTransforms$TransformType;Lcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;II)V+59
j  net.minecraft.client.renderer.ItemRenderer.handler$zcd000$onRenderItem(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/model/ItemCameraTransforms$TransformType;ZLcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;IILnet/minecraft/client/renderer/model/IBakedModel;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V+58
j  net.minecraft.client.renderer.ItemRenderer.func_229111_a_(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/model/ItemCameraTransforms$TransformType;ZLcom/mojang/blaze3d/matrix/MatrixStack;Lnet/minecraft/client/renderer/IRenderTypeBuffer;IILnet/minecraft/client/renderer/model/IBakedModel;)V+28
J 36866 C2 net.minecraft.client.renderer.ItemRenderer.func_184391_a(Lnet/minecraft/entity/LivingEntity;Lnet/minecraft/item/ItemStack;II)V (10 bytes) @ 0x0000000008aadf40 [0x0000000008aabda0+0x21a0]
j  mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(Lcom/mojang/blaze3d/matrix/MatrixStack;IILnet/minecraft/item/ItemStack;)V+53
j  mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(Lcom/mojang/blaze3d/matrix/MatrixStack;IILjava/lang/Object;)V+9
j  mezz.jei.render.IngredientListElementRenderer.renderSlow(Lcom/mojang/blaze3d/matrix/MatrixStack;Lmezz/jei/config/IEditModeConfig;Lmezz/jei/config/IWorldConfig;)V+65
J 40677 C1 mezz.jei.render.IngredientListBatchRenderer.render(Lnet/minecraft/client/Minecraft;Lcom/mojang/blaze3d/matrix/MatrixStack;)V (398 bytes) @ 0x0000000008b66c04 [0x0000000008b5cbc0+0xa044]
J 39330 C1 mezz.jei.gui.overlay.IngredientGrid.draw(Lnet/minecraft/client/Minecraft;Lcom/mojang/blaze3d/matrix/MatrixStack;II)V (66 bytes) @ 0x00000000085b802c [0x00000000085b7680+0x9ac]
J 39326 C1 mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(Lnet/minecraft/client/Minecraft;Lcom/mojang/blaze3d/matrix/MatrixStack;IIF)V (58 bytes) @ 0x00000000085c5d74 [0x00000000085c4f60+0xe14]
J 39176 C1 mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(Lnet/minecraftforge/client/event/GuiScreenEvent$BackgroundDrawnEvent;)V (106 bytes) @ 0x0000000006455f34 [0x00000000064556c0+0x874]
J 37400 C1 mezz.jei.gui.GuiEventHandler$$Lambda$23269.accept(Ljava/lang/Object;Ljava/lang/Object;)V (12 bytes) @ 0x0000000006c7b414 [0x0000000006c7b1c0+0x254]
J 40375 C2 mezz.jei.events.EventBusHelper$$Lambda$23111.accept(Ljava/lang/Object;)V (16 bytes) @ 0x000000000973b7f4 [0x000000000973b760+0x94]
J 23437 C2 net.minecraftforge.eventbus.EventBus$$Lambda$2842.invoke(Lnet/minecraftforge/eventbus/api/Event;)V (21 bytes) @ 0x0000000005139164 [0x00000000051390a0+0xc4]
J 26578 C2 net.minecraftforge.eventbus.EventBus.post(Lnet/minecraftforge/eventbus/api/Event;Lnet/minecraftforge/eventbus/api/IEventBusInvokeDispatcher;)Z (182 bytes) @ 0x0000000006151c10 [0x0000000006151ae0+0x130]
J 23692 C1 net.minecraft.client.gui.screen.Screen.func_238651_a_(Lcom/mojang/blaze3d/matrix/MatrixStack;I)V (58 bytes) @ 0x0000000006514a14 [0x0000000006514440+0x5d4]
J 37399 C1 net.minecraft.client.gui.screen.inventory.InventoryScreen.func_230430_a_(Lcom/mojang/blaze3d/matrix/MatrixStack;IIF)V (143 bytes) @ 0x00000000059150cc [0x0000000005914ee0+0x1ec]
J 23612 C1 net.minecraftforge.client.ForgeHooksClient.drawScreen(Lnet/minecraft/client/gui/screen/Screen;Lcom/mojang/blaze3d/matrix/MatrixStack;IIF)V (56 bytes) @ 0x00000000064b2c8c [0x00000000064b27c0+0x4cc]
J 40504 C2 net.minecraft.client.renderer.GameRenderer.func_195458_a(FJZ)V (856 bytes) @ 0x000000000984f6b4 [0x000000000984d740+0x1f74]
J 40502 C2 net.minecraft.client.Minecraft.func_195542_b(Z)V (994 bytes) @ 0x000000000985e148 [0x000000000985c9a0+0x17a8]
j  net.minecraft.client.Minecraft.func_99999_d()V+68
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1379
v  ~StubRoutines::call_stub
j  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0
j  sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100
J 1938 C1 sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (10 bytes) @ 0x000000000330370c [0x0000000003303600+0x10c]
J 1937 C1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (62 bytes) @ 0x0000000003303eac [0x0000000003303ac0+0x3ec]
j  net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(Lcpw/mods/modlauncher/api/ITransformingClassLoader;[Ljava/lang/String;)Ljava/lang/Void;+50
j  net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$489.call()Ljava/lang/Object;+12
j  cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch([Ljava/lang/String;Lcpw/mods/modlauncher/api/ITransformingClassLoader;)V+11
j  cpw.mods.modlauncher.LaunchServiceHandler.launch(Ljava/lang/String;[Ljava/lang/String;Lcpw/mods/modlauncher/TransformingClassLoader;Lcpw/mods/modlauncher/LaunchPluginHandler;)V+57
j  cpw.mods.modlauncher.LaunchServiceHandler.launch(Lcpw/mods/modlauncher/ArgumentHandler;Lcpw/mods/modlauncher/TransformingClassLoader;Lcpw/mods/modlauncher/LaunchPluginHandler;)V+19
j  cpw.mods.modlauncher.Launcher.run([Ljava/lang/String;)V+116
j  cpw.mods.modlauncher.Launcher.main([Ljava/lang/String;)V+37
v  ~StubRoutines::call_stub

### Description / steps to reproduce
Typing DR in JEI searchbar triggers the crash (probably anything that makes that item display in the JEI panel)
Graphics card is a Radeon RX 580, no shaders installed.

**Comment by FoxMcloud5655** [comment]
As a temporary fix, you should be able to turn off DE's shaders in the config.

**Comment by FoxMcloud5655** [comment]
Turn off tool shaders in the config for Draconic Evolution.

**Comment by FoxMcloud5655** [comment]
No.  That's not the same config.  That's for Brandon's Core, not Draconic Evolution.  Turn off the tool shaders specifically.
