### ISSUE TITLE
[1.12] Void Junk 

### ISSUE THREAD

**Issue by LeChikito** [brandon3055/Draconic-Evolution#1551]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.27.353-universal / Draconic-Additions-1.12.2-1.16.4.44-universal
* Minecraft Forge version: forge-1.12.2-14.23.5.2847-universal
* Mod Pack: Infinity Revolved Reloaded 3.7.0

### Crash report
(If applicable)

### Description / steps to reproduce

Hello,
The Void Junk of Draconic tools does not work, whether multiplayer or solo. After checking the config files, I couldn't find anything related to this. Would it be possible to have more information on this subject?
Thanks in advance

**Comment by brandon3055** [comment]
In 1.12 the junk filter only works in AOE mode. 
Also once you enable the just filter there is another option to configure the junk filter.
