### ISSUE TITLE
game crash after opening tools tab 1.16.5 version

### ISSUE THREAD

**Issue by memexyz123** [brandon3055/Draconic-Evolution#1554]
game crash after opening tools tab

**Comment by memexyz123** [comment]
[crash-2021-10-07_11.31.19-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/7298832/crash-2021-10-07_11.31.19-client.txt)

**Comment by FoxMcloud5655** [comment]
There should be a fix in place for this already.  Try updating Draconic Evolution.

If this doesn't work for you, then try disabling shaders for now.  You can find it in Draconic Evolution's config file.

**Comment by brandon3055** [comment]
For now just disable shaders in the DE config

**Comment by chaotickille** [comment]
there is no config in config folder

**Comment by chaotickille** [comment]
if there is way please tell me

**Comment by chaotickille** [comment]
which shaders shall i disable in the config

**Comment by FoxMcloud5655** [comment]
Be on the safe side and disable all of them for now.

**Comment by chaotickille** [comment]
thanks

**Comment by chaotickille** [comment]
i also have found that the tool shader crashed the game
