### ISSUE TITLE
[1.16] Chaotic Staff of Power deletes blocks

### ISSUE THREAD

**Issue by Eric9922** [brandon3055/Draconic-Evolution#1556]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.16.417
* Minecraft Forge version: 36.2.8
* Mod Pack: (if applicable)

### Crash report
(If applicable)

### Description / steps to reproduce
The Chaotic staff of power erases blocks. If I set the AOE up, I won't get the blocks. If I mine blocks with vein mining, it also feels like blocks are being deleted.

**Comment by brandon3055** [comment]
Is this a reproducible issue? If so can you please tell me how to reproduce it because AOE seems to be working fine in all my testing.

**Comment by SirMaxwellSmart** [comment]
https://youtu.be/Nk0hDfh5q9c

I have been experiencing a similar problem on the Oceanblock Modpack, however whether or not I have the AOE upgrade in it, the staff seems to be deleting blocks.
(above is a link to a quick video showing what I'm talking about)

**Comment by FoxMcloud5655** [comment]
Can't very well view a video that's completely private.  You're going to need to set it to unlisted.

**Comment by SirMaxwellSmart** [comment]
https://youtu.be/Nk0hDfh5q9c

Sorry, Unlistd now. 😅

**Comment by SirMaxwellSmart** [comment]
> https://youtu.be/Nk0hDfh5q9c
> 
> I have been experiencing a similar problem on the Oceanblock Modpack, however whether or not I have the AOE upgrade in it, the staff seems to be deleting blocks. (above is a link to a quick video showing what I'm talking about)
> 
> Edit* I just tried it with the Chaotic Pickaxe and had the same thing happen.

After doing some more testing, the problem I'm having is actually a bug with the Oceanblock. It seems that when item entities are stacking, they're not being counted up properly.
I just may have only noticed when I had the ability to mine heaps of blocks at once.
