### ISSUE TITLE
[1.16] Crafter Bug

### ISSUE THREAD

**Issue by Eric9922** [brandon3055/Draconic-Evolution#1557]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.16.417
* Minecraft Forge version: 36.2.8
* Mod Pack: (if applicable)

### Crash report
(If applicable)

### Description / steps to reproduce
(https://user-images.githubusercontent.com/90250387/136811991-dbafd9cf-2e4c-4013-b6b5-95714c2ed71e.png)
This setup doesn't work because the Crafter on the right is displaying the items from the Crafter on the left. As soon as I dismantle the right Fusion Crafting Core everything works again after a restart

**Comment by brandon3055** [comment]
This will be fixed in the next update
