### ISSUE TITLE
[1.12] <Title> Lots of Lag and getting kicked from server

### ISSUE THREAD

**Issue by mlgnoob312** [brandon3055/Draconic-Evolution#1558]
## Base information
* Minecraft version:1.12.2
* Mod version:Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
* Minecraft Forge version:forge-1.12.2-14.23.5.2854-installer (1)
* Mod Pack: (if applicable)

### Crash report
(If applicable)

### Description / steps to reproduce
I have a about 70 mod loaded in a custom modpack that runs on a 20g ram server that i play with about 2-3 friends at a time the problem is that when ever the player model is visible on screen it dramatically
reduces the fps of that player and as soon as the player looks away the lag stops this also goes for the player model in the inventory it makes it impossible to play sometimes but optifine helps bring the 6-8 fps up to about 18-20 but it does not crash the game but it does in some cases like my friend with a top tier 
gaming pc it would Couse problems and even kick him from the game I solved the problem by switching to Draconic-Evolution-1.12.2-2.3.27.353-universal.jar which is the version just before but it still has the problem but a much watered down version (25-40fps) of it am not sure how much this problem affects the mod on its own since I did not test the mod on its own I'm just letting you know and I hope this helps.

EDIT I forgot to add the specific mods I used if u want me to list them I will

**Comment by mlgnoob312** [comment]
Hi here's the screenshot
 [image: 2021-10-13_18.34.59.png]

**Comment by mlgnoob312** [comment]
my bad here's the vanilla screenshot:
![2021-10-13_18 50 19](https://user-images.githubusercontent.com/92352341/137237537-4afbafc4-c2f9-44b1-9c09-33e83540c6c6.png)


and here's the mod on its own
 
![2021-10-13_18 34 59](https://user-images.githubusercontent.com/92352341/137237648-8128ccd4-c205-45d2-9ae1-6e5642fc955b.png)

**Comment by FoxMcloud5655** [comment]
From what I see, you're getting 145 FPS, both modded and vanilla.  I don't really see sub-20 FPS.

Also, when playing modded, you really shouldn't have anything over 8 GB allocated.  That can actually slow you down unless you use up all that space with shaders and texture packs or something.  You want that to be about 50% upon startup.

**Comment by mlgnoob312** [comment]
thanks for the advice It only happened when I looked at another player on the server otherwise it ran fine but after playing with it on its own with no other mods it seemed fine so some other mod must be conflicting with the player model or something so I'm going to look for that thanks for you time
