### ISSUE TITLE
[1.16] Ore Generation

### ISSUE THREAD

**Issue by willtarax** [brandon3055/Draconic-Evolution#1561]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.16.417
* Minecraft Forge version:
* Mod Pack: (if applicable) Taraxia Compilation 

### Crash report
(If applicable)

### Description / steps to reproduce

Draconium does not spawn in the Overworld or Nether. Using an RFTools builder I was able to scan over a 512*512 area and found no draconium.

**Comment by djoveryde** [comment]
Can confirm the nether at least to have no ore generation of Draconium. Currently running on Draconic-Evolution-1.16.5-3.0.17.420. Modpack Arcadian Skies (hence no confirmation of overworld spawning as there is no overworld land).

**Comment by Seniorendi** [comment]
And a lot does generate in the end.

**Comment by brandon3055** [comment]
![](https://ss.brandon3055.com/29d7c)
![](https://ss.brandon3055.com/d8920)
![](https://ss.brandon3055.com/f9778)

**Comment by Seniorendi** [comment]
Yeah
