### ISSUE TITLE
[1.16] Opening creative inventory wipes Draconic Evolution modules from all items.

### ISSUE THREAD

**Issue by LivacoNew** [brandon3055/Draconic-Evolution#1564]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.16.417
* Minecraft Forge version: 36.2.8
* Mod Pack: FTB Oceanblock

### Crash report
N/A

### Description / steps to reproduce
Friend of mine was in creative mode to fix something on our server, before going back into survival. He then noticed all his Draconic Modules in his Draconic Chestpiece, Sword and Pickaxe had all disappeared. He then spawned them back in, tried it again and they were gone. It seems whenever you open the creative mode inventory with modules installed on a item, they get removed somehow. Nothing in our servers console.

**Comment by brandon3055** [comment]
Not a terrible idea.
Will add this in the next release.
![](https://ss.brandon3055.com/d55cd)
