### ISSUE TITLE
[1.16] Crash gui Modules

### ISSUE THREAD

**Issue by SuperNon0** [brandon3055/Draconic-Evolution#1565]
## Base information
* Minecraft version: 1.16.5
* Mod version: 1.16.5-3.0.17.420
* Minecraft Forge version: 36.2.0
* Mod Pack: Ragnamod VI

### Crash report
https://pastebin.com/j9y1ici2

### Description / steps to reproduce
I configure the key to open the tool config menu, I press the key then my game crashes.

**Comment by brandon3055** [comment]
According to the crash report you are using DE version 3.0.15. This should be fixed in the latest version.
