### ISSUE TITLE
【1.16.5】The Mob Grinder can‘t kill the Mowzie's Mobs’ Grottol

### ISSUE THREAD

**Issue by sakezerto** [brandon3055/Draconic-Evolution#1566]
As the title， the Mob Grinder can‘t kill the Mowzie's Mobs’ Grottol，The version is  3.0.16.417.

**Comment by brandon3055** [comment]
This is not a bug. It looks like the grottol needs to be hit with a silk touch tool. Try putting a pickaxe with silk touch in the grinders weapon slot.
