### ISSUE TITLE
[1.16] Chaos Guardian doesn't spawn

### ISSUE THREAD

**Issue by MLDEG** [brandon3055/Draconic-Evolution#1569]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.17.420
* Minecraft Forge version: 36.2.8

### Description / steps to reproduce

The bug is easy to reproduce:
If I disable Draconium Ore generation in the end (in DraconicEvolution.cfg), the chaos guardian doesn't spawn.
I tested with an instance that only had Draconic Evolution, Brandon's Core, and CodeChicken Lib.

Thank you for your work :)

**Comment by brandon3055** [comment]
will be fixed in the next release
