### ISSUE TITLE
manual.json not locatable

### ISSUE THREAD

**Issue by ReneMuetti** [brandon3055/Draconic-Evolution#157]
Hello
I'd like to complete the translations. But instead takes the file somehow be stored at a different location or with a different name. Currently I can not translate it. Is there something to do? I would prepare the translation of the time - it is quite a lot :)

**Comment by GreatOrator** [comment]
If you open the jar (or follow the path here) it is under assets\draconicevolution\

**Comment by ReneMuetti** [comment]
I am not a Java programmer, unfortunately. Therefore, I have asked the question of whether this can be achieved. Also, I do not know how Java under a meaningful name-environment can be reached.

**Comment by GreatOrator** [comment]
https://github.com/brandon3055/Draconic-Evolution/tree/master/src/main/resources/assets/draconicevolution

Nothing to do with being a programmer, just follow the folder path :P

**Comment by ReneMuetti** [comment]
That's what I've found ...
Only first names I can no translation in the file because it is only 1x and therein only the English language is included. Maybe it would help to ensure a similar approach, as with the lang/*-files

**Comment by GreatOrator** [comment]
That would be correct sir :)

**Comment by brandon3055** [comment]
The manual dose not currently support language localization but when i finally get around to working on the manual i will look into adding it.

**Comment by brandon3055** [comment]
Just a heads up if you are still interested it will be possible to add language localization to the tablet in the next version. To do so just add your translated json to the following package via a pull request and replace en_US with your language.

https://github.com/brandon3055/Draconic-Evolution/tree/master/src/main/resources/assets/draconicevolution/manual

**Comment by ReneMuetti** [comment]
Hi

I think it's great. I will sit down in the next few days to the translations :) Thanks
