### ISSUE TITLE
[1.12] Can't Fly

### ISSUE THREAD

**Issue by xMrNeverDie** [brandon3055/Draconic-Evolution#1570]
I can't use the flight feature idk why when i try to fly it gives me some effect on the ground and says "You lose control of youre wings" and some other things. Do i need to learn anything to fly?

**Comment by FoxMcloud5655** [comment]
Sounds like you have another mod force disabling flight.  You might be in a special dimension that disallows flight to prevent cheesing.

**Comment by xMrNeverDie** [comment]
> Sounds like you have another mod force disabling flight. You might be in a special dimension that disallows flight to prevent cheesing.

Yee, i'm sry i didn't see that "Broken Wings" was installed -.- I just changed the config. Sry :D
