### ISSUE TITLE
[1.16] <i cant change capacitor mode >

### ISSUE THREAD

**Issue by chaotickille** [brandon3055/Draconic-Evolution#1571]
## the capacitor cant change modes
* Minecraft version: 1.16.5
* Mod version:3.0.17.420
* Minecraft Forge version:
* Mod Pack: (if applicable)

### Crash report
(If applicable)

**Comment by FoxMcloud5655** [comment]
Have you considered the fact that the entire mod has been reworked and maybe you don't right click the item anymore?

There are new options in the tool's GUI that you can set to change what the capacitor charges.  From there, you can also set up key binds in the advanced mode that allow you to create all sorts of combinations of modes across your entire tool and armor set.

**Comment by chaotickille** [comment]
thanks
