### ISSUE TITLE
[Feature Request] Access transforming

### ISSUE THREAD

**Issue by Seniorendi** [brandon3055/Draconic-Evolution#1572]
Hey, 
I want to create an add-on for DE, for that I would need access to the fields and methods `core`(TileEnergyPylon), `lastTickEnergy`(TileEnergyCore) and `getCachedCore`(TileReactorComponent) (Probably more in the future).
I just want to ask, am I allowed to create an PR for this to change the access of these methods/fields or create getters for them?

**Comment by FoxMcloud5655** [comment]
If you really want to access those fields, you can always use reflection.

**Comment by Seniorendi** [comment]
I wanted to prevent that, that's the reason I created this request.
If DE does not change the access of the fields/methods, I will use reflection.

**Comment by FoxMcloud5655** [comment]
Understandable. I'm guessing this is for DE2 (for MC 1.12.2)?

**Comment by Seniorendi** [comment]
Nah, 1.16

**Comment by brandon3055** [comment]
Your best bet would be to use mixin accessors. 
For example:
```java
@Mixin (ServerWorld.class)
public interface ServerLevelAccessor {

    @Accessor
    Int2ObjectMap<Entity> getEntitiesById();
}
```
Exposes the `entitiesByID` field on ServerWorld.
Then to use that you do
```java
ServerWorld world = ...;
Int2ObjectMap<Entity> entitiesById = ((ServerLevelAccessor)world).getEntitiesById();
```

**Comment by Seniorendi** [comment]
Thank you for the advice
But I did it already with reflections.
https://github.com/Seniorendi/AdvancedPeripherals/blob/1.16/src/main/java/de/srendi/advancedperipherals/common/addons/draconicevolution/EnergyPylonIntegration.java

**Comment by brandon3055** [comment]
Ok that should work. Just be aware reflection is rather slow so if you will be calling that method a lot a mixin would be much more efficient.
