### ISSUE TITLE
[1.16] how to disable curio slot shield animation

### ISSUE THREAD

**Issue by chaotickille** [brandon3055/Draconic-Evolution#1573]
i am using the first person mod it glitches with the shield animation is there a way to disable the shield animation in curio slot 

### Crash report
(If applicable)

**Comment by FoxMcloud5655** [comment]
This is a place for bug reports, not for questions. If you have a question, please go to the Discord and ask it.

With that being said, you can disable the always on shield inside of your tool config, but when you get hit, the shield will still display.

**Comment by chaotickille** [comment]
i cannot find the tool config

**Comment by chaotickille** [comment]
i have gone through the config completely

**Comment by FoxMcloud5655** [comment]
Are you sure about that?  In-game, go to your options menu and find your keybinds.  Look for the category of draconic evolution and find the GUI button that allows you to change the tool's config option.  Take note of the key you need to press, then go back to the game and press the key.  Click on your chest piece, then near the top is the option to turn off the shield always displaying.
