### ISSUE TITLE
[1.16] Create, DE, Brandon's Core Mixin Crash

### ISSUE THREAD

**Issue by ReeCodes** [brandon3055/Draconic-Evolution#1574]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.17.420-universal
* Minecraft Forge version: 36.2.9
* Mod Pack: (if applicable)

### Crash report
https://mclo.gs/V7xtkqH

### Description / steps to reproduce
Start MC

**Comment by FoxMcloud5655** [comment]
Seems like this may be a RandomPatches issue instead.

**Comment by covers1624** [comment]
This is a Random Patches issue. Brandons Core is just stepping on a landmine.
