### ISSUE TITLE
Game crashing from looking at a particular item

### ISSUE THREAD

**Issue by Fatsharky** [brandon3055/Draconic-Evolution#1575]
when i go into the search menu from JEI i always type "@Dra" and can see everything in the mod its self but when i go to scroll to the next page of items the game instantly crashes from an item i assume looking at it. i also tried to decrease the GUI scale to 1 so everything is small like your inventory and tool belt, then when i go to type again "@Dra" the game does crash right off the bat. then i increased the GUI scale to 4 to where everything is big in the inventory i go to type it again "@Dra" the game does not crash until i scroll down to the next page it then crashes 
which may mean that it is a item. i am also willing to get rid of any mod to make it work because this is my most favorite mod and its no fun without it. (i will send a crash report if that is any help i hope)
[aga tt.txt](https://github.com/brandon3055/Draconic-Evolution/files/7559048/aga.tt.txt)
i need to also mention that today i gotten a update for CodeChicken Lib And JEI

**Comment by FoxMcloud5655** [comment]
Turn off DE shaders in the config.  This issue has been reported multiple times, and it has something to do with older hardware or AMD GPU's not supporting the higher level of shaders iirc.

**Comment by Fatsharky** [comment]
i opened the folder of modpack and went to config and did not find a DE shaders i also checked brandon3055 folder in the config and didnt find anything like that but i do see "draconic evolution" "Modulestats" "hud_settings.json" and brandonsCore in the brandon3055 folder in config and i also found "ccl" in the config. i may be doing it wrong

**Comment by Fatsharky** [comment]
oh wait i know what you mean i just have to find in in the actuall file with the info
