### ISSUE TITLE
Draconic Evolution[1.16] <Modules disappearing from gear>

### ISSUE THREAD

**Issue by YaBoiSwoozy** [brandon3055/Draconic-Evolution#1576]
## Base information
* Minecraft version:1.16
* Mod version: idk
* Minecraft Forge version: idk
* Mod Pack: (if applicable) ATM 6 mod version 1.8.9

### Description / steps to reproduce
So I was chillin in my base and suddenly all the modules on my gear disappeared. I am not sure what caused it but now when I spawn in a new chaotic chest piece and new modules, they still disappear from inside the 10x8 grid. I am using the chest piece on my player and not my curio slots so I can use elytra flight.
My first chest piece is enchanted with soulbound and is renamed in the anvil

**Comment by FoxMcloud5655** [comment]
Due to a bug in Forge, if you ever enter creative mode, you will lose all modules on all gear.  Brandon has already raised this issue with forge, and like the Forge devs typically like to do, their deliberating it very heavily on how best to fix the issue before actually implementing a fix.

There is literally nothing that can be done about this until that bug is fixed, and it may not ever be fixed for 1.16.x.

**Comment by YaBoiSwoozy** [comment]
Oh thats right I did go creative mode to spawn my friend in some boots since the server crashed while he was enchanting and they despawned

**Comment by brandon3055** [comment]
I'm hoping to find a proper fix for this at some point but in the meantime, I am adding a chat warning whenever you switch to creative mode on a server.

**Comment by dabigmoose** [comment]
Just curious if this is one time event or after you enter creative one time its like this forever?  I  replaced an item for someone in FTB Oceeanblock at beginning of server we arent even into draconic yet so is this going to happen and server is shot or are we ok and just dont enter creative again?

**Comment by FoxMcloud5655** [comment]
Let me explain exactly what happens.  When you open your inventory in Creative mode, all items that contain modules that you can see in that inventory will be cleared.  Simple as that.
