### ISSUE TITLE
[Feature Request] Please bring back the Celestial Manipulator

### ISSUE THREAD

**Issue by e30Birdy** [brandon3055/Draconic-Evolution#1577]
This would really be helpful in a lot of packs where one has to use mekanism reactors and needing daylight all the time. Please bring back the Celestial Manipulator.

**Comment by FoxMcloud5655** [comment]
As of December 23rd of 2020, Brandon has already stated that the Celestial Manipulator is not yet implemented.  This means it is making a comeback, but DE3 is still in beta.  Expect machines and items to be missing or a work in progress.

**Comment by e30Birdy** [comment]
> As of December 23rd of 2020, Brandon has already stated that the Celestial Manipulator is not yet implemented. This means it is making a comeback, but DE3 is still in beta. Expect machines and items to be missing or a work in progress.

Ok I didn't know if it was missed or what was going on, thought I would mention it since there are a lot of packs that would profit off of it since there is no other item in the game except command blocks that would do the same
