### ISSUE TITLE
 [1.16] <Title>

### ISSUE THREAD

**Issue by NJM1564** [brandon3055/Draconic-Evolution#1578]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.17.420
* Minecraft Forge version: 36.2.9
* Mod Pack: (if applicable) Ocionblock

### Description / steps to reproduce

Draconic staff of power acceptances projectile damage modals.
As far as I know the staff doesn't shoot anything.

Ether the modules shouldn't go in there.
Or it should fire a projectile/beam. I personally would love a laser.

**Comment by brandon3055** [comment]
I do have plans to make the staff a projectile weapon which is why you can install those modules. I just have not figured out a good weapon mechanic that I like yet so it's currently on hold. I have some good ideas but rendering is tricky.
