### ISSUE TITLE
[1.16] client side crash when rendering fusion crafting core gui

### ISSUE THREAD

**Issue by Kzeroko** [brandon3055/Draconic-Evolution#1581]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.17.420-universal
* Minecraft Forge version: 36.2.8
* Mod Pack: (if applicable) Personal modpack

### Crash report
(If applicable)
[crash-2021-11-28_03.26.16-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/7612835/crash-2021-11-28_03.26.16-client.txt)

### Description / steps to reproduce
Open fusion crafting core GUI causes client side crash, I figured out that polymorph may have caused this crash so I have also reported this issue to polymorph, but I'm not sure which to blame.
https://www.toptal.com/developers/hastebin/cacebaquto.rb

**Comment by Kzeroko** [comment]
I updated to the newest version of Polymorph and it fixed this issue.

**Comment by FoxMcloud5655** [comment]
Good to know.  I'll keep this in mind for my server if it ever encounters this issue.
