### ISSUE TITLE
[1.16] Fusion Crafting Core putting out comparator signal even when no item inside after craft complete

### ISSUE THREAD

**Issue by e30Birdy** [brandon3055/Draconic-Evolution#1582]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.17.420-universal
* Minecraft Forge version: 1.16.5-forge-36.2.9
* Mod Pack: FTB OceanBlock

### Description / steps to reproduce

So i can a crafter from refined storage set to a chest and redstone signal that a pulse unlocks it so that it will input next recipe. Problem is that after fusion crafting core is complete with crafting it continues to send out signal to comparator unless one clicks don't the comparator twice by hand. I have this same setup running with Powah energizing orb crafting and it works flawlessly. When it is crafting the comparator lights up and when it is complete it send out the pulse and allows my crafter to put in next recipe.

**Comment by FoxMcloud5655** [comment]
The entire Fusion Crafting system is going to be rewritten.  The current system is pretty much hacked together just to work good enough until it's finished.

Once that goes through, I'm sure this issue will simply disappear due to the rewrite.

**Comment by e30Birdy** [comment]
> The entire Fusion Crafting system is going to be rewritten. The current system is pretty much hacked together just to work good enough until it's finished.
> 
> Once that goes through, I'm sure this issue will simply disappear due to the rewrite.

Oh cool, looking forward to the update, would love to finally see a controller or something making it a bit nicer to automate/power.

**Comment by brandon3055** [comment]
@FoxMcloud5655 Most of the fusion rewrite has already been finished. [00dd64a](https://github.com/brandon3055/Draconic-Evolution/commit/00dd64a78fa3a42c45208db6237c098dd2038ef6)
That was mainly complete were write of the core logic, rendering and GUI. But the new GUI is a bit boring and I'm not entirely happy with the rendering so I will probably revisit it at some point but for now it is 'done'

But with rewrites coms the potential for new bugs to creep in. In this case, it seems I am simply forgetting to trigger a block update when the crafting operation completes. This will be fixed in the next update.

**Comment by FoxMcloud5655** [comment]
Oh, neat!  I didn't know the actual progress of the rewrite, so I'm glad it's mostly finished then.

**Comment by brandon3055** [comment]
@e30Birdy Considering I just pushed the last batch of fixed/updates yesterday it may be a little while before this fix makes it to curse. In the meantime if you need the fix now you can get the latest build directly from maven.
https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.18.429/Draconic-Evolution-1.16.5-3.0.18.429-universal.jar

**Comment by e30Birdy** [comment]
> @e30Birdy Considering I just pushed the last batch of fixed/updates yesterday it may be a little while before this fix makes it to curse. In the meantime if you need the fix now you can get the latest build directly from maven. https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.18.429/Draconic-Evolution-1.16.5-3.0.18.429-universal.jar

Thanks so much that fixed the issue and auto crafting and pulling redstone signal from core works great. Can't wait to read the changelog to see what else is fixed/changed.
