### ISSUE TITLE
Draconic-Evolution infinity pipe 

### ISSUE THREAD

**Issue by acuLerer** [brandon3055/Draconic-Evolution#1586]
An energy pipe with infinite transfer for the draconic reactor.
Maybe an endgame item.

**Comment by FoxMcloud5655** [comment]
Attaching an Energy Pylon directly to the Flow Gate isn't fast enough?

**Comment by acuLerer** [comment]
Unfortunately no, the reactor explodes for me

**Comment by FoxMcloud5655** [comment]
The reactor will only explode if you pull too much RF from it, causing the cost of the shield to go up and eventually outpase the RF generated.  Sounds to me like you're just not setting up the Flux Gate properly.

**Comment by acuLerer** [comment]
The problem is that I don't have a cable that doesn't have a fast tranzver so that I can supply the shield

**Comment by brandon3055** [comment]
I will be overhauling the crystals at some point but Draconic energy crystals should be more than adequate unless you have increased the reactor generation config or something.
Also Reactor stabilizer -> Flow gate -> Energy pylon should allow a max configurable transfer of up to
9,223,372,036,854,775,807RF/t

**Comment by acuLerer** [comment]
OK thank you
