### ISSUE TITLE
[1.16] Draconic Bow ignores arrow properties

### ISSUE THREAD

**Issue by JeNoVaViRuS** [brandon3055/Draconic-Evolution#1587]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.17.420
* Minecraft Forge version: 36.2.8
* Mod Pack: All the Mods 6

### Description / steps to reproduce
Draconic Bow fires every arrow as if it was a vanilla arrow. Tested with arrows from several other mods (Silent Gear arrows, Apotheosis: Obsidian Arrow, Forbidden & Arcanus: Boom Arrow).

**Comment by brandon3055** [comment]
This is hard to implement because it requires me to use the custom arrow entities provided by other mods but doing so would disable a lot of my custom effects which require me to use my own arrow entity. 
I will look into it.

**Comment by brandon3055** [comment]
Custom arrows should theoretically work in the next release but many of DE's custom effects will not work with other mods custom arrows.
