### ISSUE TITLE
[1.16] Server freeze & loop

### ISSUE THREAD

**Issue by bigenergy** [brandon3055/Draconic-Evolution#1589]
## Base information
* Minecraft version: 1.16.5
* Mod version: 1.16.5-3.0.18.428
* Minecraft Forge version: 1.16.5-36.2.19
* Mod Pack: (if applicable)

### Crash report
Thread dump https://gist.github.com/bigenergy/6f557cc940c2b6804442bcdd66e6b8ab

### Description / steps to reproduce

Server loop https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/entity/projectile/DraconicArrowEntity.java#L213

**Comment by FoxMcloud5655** [comment]
Non-Forge only server environments are not supported by basically most mods.

**Comment by brandon3055** [comment]
That is a simple ray-trace between two points. It should not be possible for it to break in this way.
