### ISSUE TITLE
Junk Filter Request

### ISSUE THREAD

**Issue by Mohron** [brandon3055/Draconic-Evolution#159]
The junk filter is a great feature! I have a feature request that would even make it better.

Allow mob drops in the junk filter on the Draconic Staff of Power and add a junk filter to the Draconic and Wyvern swords.

This would allow you to destroy trash drops from mobs when farming them. It might be also notable that it would be more useful as a fuzzy type detection for weapons or armor drops that drop with varying damage to them.

**Comment by GreatOrator** [comment]
This suggestion has been moved to http://www.brandon3055.com/suggestions/
