### ISSUE TITLE
[1.16] Bow projectile desync between visual trajectory and actual trajectory  (possibly velocity upgrade related)

### ISSUE THREAD

**Issue by fuj1n** [brandon3055/Draconic-Evolution#1592]
## Base information
* Minecraft version: 1.16.5
* Mod version: 1.16.5-3.0.18.428
* Minecraft Forge version: 36.2.20
* Mod Pack: (if applicable) FTB OceanBlock

### Crash report
(If applicable)

### Description / steps to reproduce
I have a chaotic bow (still worked pre-chaotic) set-up as follows: 
![image](https://user-images.githubusercontent.com/4004193/146379802-f0e87843-99ea-4f75-874f-8ab5d4eec057.png)
Here are the enchantments in case that matters for this issue:
![image](https://user-images.githubusercontent.com/4004193/146379938-f1d2f8d0-7caf-4f44-abf0-2f6bc71a9180.png)

When I shoot with it, the arrow appears to curve-off in a direction, and then the actual arrow materializes where I was pointing.
The direction it curves off is a bit weird as it is based on the direction I am looking, if I align my view perfectly on any axis, the arrow will appear to travel straight, however, the farther from the center of an axis I get, the more the arrow curves away from the axis.

After about a second, the arrow appears where I was actually aiming, so it seems to be a desync.

This seems to only happen with the velocity modules, and the more I add (chaotic, so no inaccuracy, but also worked at lower tiers with accuracy modules), the more the arrow seems to curve off.

[Here is a short video to demonstrate this in case I was too rambly in my description.
](https://youtu.be/PGkKUIeEoJU)

**Comment by FoxMcloud5655** [comment]
If I remember what Brandon said correctly, it's not actually a bug in Draconic Evolution.  The vanilla arrow class does not render properly at such high velocities.  He's not exactly sure on the best method to fix this, though there are some options.

**Comment by brandon3055** [comment]
DE has mixins that are supposed to fix this syncing issue. Something must be breaking them.

**Comment by fuj1n** [comment]
I will do an exclusion test to try and find it when I get home

**Comment by brandon3055** [comment]
I would start by confirming the mixins actually still work with just DE installed and go from there.

**Comment by fuj1n** [comment]
Tried with just DE and the required library mods (CCC, BC), and the issue seems to still be occurring

**Comment by brandon3055** [comment]
For some reason the mixin isn't getting loaded for you but I have no idea why. Can you please upload your debug log file.
It should be located at `<Minecraft directory>/logs/debug.log`

**Comment by fuj1n** [comment]
Of course, [here's the debug log](https://pastebin.com/k38h6frB)
