### ISSUE TITLE
[1.16] <Title> Can't smelt Draconium dust or awakened Draconium dust.

### ISSUE THREAD

**Issue by vladdeda** [brandon3055/Draconic-Evolution#1593]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.18.428-universal
* Minecraft Forge version: 36.2.8
* Mod Pack: Enigmatica 6

### Crash report
Stable

### Description / steps to reproduce
Can't smelt dust into ingots.

Trying to use Crafttweaks to add the recipe but it's giving me errors as I do not know how to use Crafttweaks yet.

**Comment by vladdeda** [comment]
Also no recipe for Awakened Draconium dust at all.

**Comment by FoxMcloud5655** [comment]
This is not a bug with Draconic Evolution.  It's your modpack.  Report this to the modpack author.  Draconium Dust smelts just fine without other mods removing the built-in recipe, and there is no way to obtain awakened draconium dust normally.  If there is a way to obtain it in this modpack, then it's up to them to make the recipe to smelt it back into an ingot.

**Comment by brandon3055** [comment]
As fox said this is most likely an issue with the mod pack changing recipes. 
Awakened draconium dust only exists for possible future implementation and so that mods like thermal or mekanism can add grinding recipes.
