### ISSUE TITLE
[1.16] <Title>

### ISSUE THREAD

**Issue by vladdeda** [brandon3055/Draconic-Evolution#1594]
## Base information
* Minecraft version: 1.16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.18.428-universal
* Minecraft Forge version: 36.2.8
* Mod Pack: Enigmatica 6

### Description / steps to reproduce

Energy Tansfuser not accepting power. I have hooked up several types of power cables including draconic evolution. It just will not accept power on any of it's faces.

**Comment by FoxMcloud5655** [comment]
You're sure?  Because it works just fine for me.  Make sure you have a valid power source hooked up to the bottom face pushing RF into the transfuser, then place an item to charge on one of the sides of the block or use the GUI to insert an item.

**Comment by vladdeda** [comment]
Yes, I've placed several different types of power cables including crystals on all sides and I get no charging at all. Link to pics of setup.

https://imgur.com/gallery/cl2rrhR

**Comment by vladdeda** [comment]
Okay, yea. It works. Just didn't know how exactly it works until I reread your comment. Gotta put something to charge in it. I thought it held power. Thanks!
