### ISSUE TITLE
[Feature Request 1.16.5] Redstone activation fusion crafting

### ISSUE THREAD

**Issue by vladdeda** [brandon3055/Draconic-Evolution#1595]
Would it be possible to get redstone activation on the fusion crafting core in 1.16.5? I'd love to automate my setup but it's a pain to go to the setup and have to click craft when I'm trying to craft several items repeatedly at a time.

**Comment by brandon3055** [comment]
It can already be triggered with a redstone pulse. It's exactly the same as it was in 1.12. Or is that not working for you?

**Comment by vladdeda** [comment]
Yes, it works. I didn't know it worked by redstone pulse as there was no documentation on the 1.16.5 version. This is the first version I've ever played with. Thank you for the information.
