### ISSUE TITLE
[Feedback] Keep it simple

### ISSUE THREAD

**Issue by DemonfangArun** [brandon3055/Draconic-Evolution#1596]
Firstly, I recognize it's your mod to do with as you please, and I don't pay anything for it, I'm not some entitled person. I'm just here to give some genuine input as a longtime user of this mod.

I have been playing 1.12 for a long time because of the whole rewrite nonsense, and am only recently looking beyond that. After looking at the 1.16 version I am saddened to see this heading in the direction of the modular powersuits mod (and other similar mods). A lot of people that loved this mod over the years did so because of it's relative simplicity for endgame. With the whole "you must make a bunch of different things to actually make the armor do something useful", on top of what it takes to craft already, it's not out there to say that a fair chunk of people are going to look elsewhere for a solution. I don't mean this to be negative, but you may wish to pause for a moment and consider how those coming from 1.12 (and there are a lot of us) are going to take this.

**Comment by FoxMcloud5655** [comment]
I don't want to be one of those people, but if they don't like it, then they can look elsewhere.  Draconic Evolution was in serious need of a nerf to balance out with other mods, and this is exactly what enables the mod to do so.

Draconic Evolution was never designed to be played by itself, though it is possible to do so.  Considering how OP DE has been in the past, it's safe to say that this change is very welcome.  The fact that it uses so much Draconium, Netherite, or potions in the crafting recipes makes you seek out faster and better ways of harvesting these materials.  It plays very well with mods like Mekanism and the Thermal series.

With all this being said, the modules are completely customizable, and even the grid sizes for placing modules into is completely customizable too.  Combine this with the fact that you can change out all of the recipes in the entire mod, and you can now balance the entire mod yourself literally however you like.

**Comment by DemonfangArun** [comment]
Oh I did most certainly play it in a pack. Said pack had plenty of other OP stuff in it, but it was all balanced in a reasonable way where nothing was outright broken. That OPness is actually what a lot of people LIKE about the armor, set it once and forget about it and actually go on and do other stuff. There's nothing WRONG with having OP stuff by choice, yet everyone seems to treat it like this great evil. Let people have fun, there are other mods for armor that already act like what this is turning into for those that want complex systems.

Unfortunately, yes, people will be looking elsewhere, myself included. I have loved the aesthetic and the relative simplicity of it in the past, but now that it's going with this nonsense I am going to be relegating it to the same place that WoW legendaries are sitting right now.

**Comment by FoxMcloud5655** [comment]
Sad to see you go.  It's not like DE can't still reach the power levels of previous versions, it's just that the amount of time, effort, and material cost has been increased.  Literally almost every aspect of the mod can be changed, including the passive RF costs, the recipes, the amount of RF stored in the energy modules, the strength of the modules, etc.

If you don't like it, then you are free to change it.  If you don't want to put the effort into making it your own, then you're free to find a modpack that suits you.  If you don't like any of that, then unfortunately you're out of luck.

**Comment by DemonfangArun** [comment]
Yeah and that increase in time, effort, and materials is the crux of things. While it could be tweaked, not everyone is interested in that, it was nice to just drop it in and go. Ah well, guess I'm out of luck with this mod then. Have fun~
