### ISSUE TITLE
[1.16] Fusion Crafting stops 

### ISSUE THREAD

**Issue by Terminator81** [brandon3055/Draconic-Evolution#1599]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.18.428
* Minecraft Forge version: 36.2.20
* Mod Pack: FTB OceanBlock

### Description / steps to reproduce

I am currently playing the modpack FTB Oceanblock.
I play it as a client server. My problem is that when I use Fusion Crafting, the process starts briefly and then stops after a few percent. Energy etc is enough and the recipe is valid.

Apparently this only occurs when using a server and not in single player.

what else do you need ?

**Comment by FoxMcloud5655** [comment]
Make sure that all of the Fusion Crafting Injectors have RF/OP flowing into them.  Many, MANY people claim to have this exact issue when in reality they aren't putting RF into every one of the injectors.  A common mistake is people with I/O Crystals not setting them to output RF and instead setting them to input.

**Comment by Terminator81** [comment]
I put the enery in the back of the injector with flux enery points

**Comment by FoxMcloud5655** [comment]
Have you ensured that it actually outputs RF on every single injector?

**Comment by Terminator81** [comment]
yes i have also tried the wireless draconic rf transfer... 
so:
https://i.imgur.com/PWZos9Y.png

if i tick accelerate it the percent goes up every try ....after a 20-30 tries it sometimes works

**Comment by FoxMcloud5655** [comment]
I don't know what to tell you other than that there are thousands of people who don't have this issue.  I highly suspect the issue is with the RF flow.

**Comment by Terminator81** [comment]
i will try

**Comment by Crazafax** [comment]
I'm having the same issue on Oceanblock singleplayer.  Energy should also be plenty. I tried tick accelerating the block and using fast redstone signals and was able to get a craft done.

**Comment by xElementzx** [comment]
@Terminator81 
> yes i have also tried the wireless draconic rf transfer... so: https://i.imgur.com/PWZos9Y.png
> 
> if i tick accelerate it the percent goes up every try ....after a 20-30 tries it sometimes works

Just so you're aware.
The Fusion Crafting Injectors don't accept power from any face except the rear face so this is an invalid test. but as has been mentioned by others, my guess would be power supply to it.

is your power supply chunkloaded is one of the biggest questions.

**Comment by brandon3055** [comment]
Minor correction. It will accept energy from any face except the front face.

**Comment by Terminator81** [comment]
now connect to the back of the injector ....and ported to single player....still does not work ..the wireless relay has a buffer of 100mio rf ...

**Comment by brandon3055** [comment]
Does it stop during the "charging" or the "crafting" stage? Also is it possible something you have attached is modifying the contents of one of the injectors or the core during the craft?

**Comment by Terminator81** [comment]
during the charging stage

**Comment by brandon3055** [comment]
Is the crafting actually canceled? or does it just "pause"

**Comment by Terminator81** [comment]
the crating is canceled.... when i try to craft it again the percent value goes a little bit higher

**Comment by brandon3055** [comment]
Then that suggests something is modifying the contents of an injector or the core which would momentarily invalidate the recipe. 
What are you using to insert/extract items?

**Comment by Terminator81** [comment]
so i have cleaned up nothing is connted to the injectors and the core 

https://i.imgur.com/gzHJLJ9.png

https://i.imgur.com/ScbrJeu.png

https://i.imgur.com/WIgyOnM.png

**Comment by xElementzx** [comment]
@Terminator81 that last image doesn't say cancelled... it just is no longer crafting is that what you're implying?

**Comment by Terminator81** [comment]
yes it goes back to ready to craft....the i push craft.....counts percent to 2-3 percent and back to ready to craft

**Comment by FoxMcloud5655** [comment]
Try this for me.  Put all of the injectors just one block closer.  I don't think the redstone in the back is doing anything, but that would eliminate it from the equation.

**Comment by Terminator81** [comment]
I will try

**Comment by Terminator81** [comment]
now it works too ...maybe too far away?
