### ISSUE TITLE
[SUGGESTION] Ore generation manipulation

### ISSUE THREAD

**Issue by JimmyTheBoat** [brandon3055/Draconic-Evolution#16]
It would be nice if there was a config option to change how common Draconium Ore is found.

**Comment by brandon3055** [comment]
At the request of the FTB Team iam going to be adding an option to disable ore gen so that it can be controlled using cofh.

**Comment by JimmyTheBoat** [comment]
Will that include full manipulation of spawn rates, or just disabling it?

**Comment by brandon3055** [comment]
Just disabling it but cofh has the ability to to spawn ores from any mod and it has very good controll over where and how it spawns. So you will be able to disable DE ore spawn and have cofh handle the spawning of draconium ore... Assuming you use cofh.

**Comment by JimmyTheBoat** [comment]
Yeah, I'm using CoFH for all my other world generation as well :)

**Comment by brandon3055** [comment]
Config option to disable ore generation has been added in snapshot 4
