### ISSUE TITLE
Chaos Guardian

### ISSUE THREAD

**Issue by MythixDino** [brandon3055/Draconic-Evolution#160]
Issue with Chaos Guardian, sometimes he just turns invisible and it isn't possible to kill him without a command. You also can't spawn them using /summon DraconicEvolution.ChaosGuardian

**Comment by brandon3055** [comment]
This issue is no longer relevant because the chaos guardian has been re written for the next update which should be released fairly soon. You will also be able to use the summon command in the next update.
