### ISSUE TITLE
[Feature Request] Waterlogged Energy Core and Reactor models

### ISSUE THREAD

**Issue by Boolyman** [brandon3055/Draconic-Evolution#1600]
It would be very nice, especially for my upcoming pack, to have the models for the Energy Core and Reactor to be waterloggable.  This would only be a cosmetic blockstate function.  Your multiblock models would really look great underwater if this was added.

**Comment by FoxMcloud5655** [comment]
Now this is a good suggestion.  I really like this idea, and you could even have a bunch of bubbles coming off of the reactor to signify that there's a lot of heat being generated, but it's at barely boiling levels.

**Comment by xElementzx** [comment]
@Boolyman and @FoxMcloud5655 
Covers said and i quote "You're not waterlogging a sun" 

I do think it would be great persionally.. and expanding on Fox's idea, i think that with 100% shield, no bubbles and as the shield drops.. increase the amount of bubbles.

**Comment by FoxMcloud5655** [comment]
If you're not waterlogging a sun, then it should at least do fire damage to nearby players, imo.  I could totally see the shield percent playing a factor too!

**Comment by Boolyman** [comment]
@xElementzx  If you guys don't think it's appropriate, I have to accept it.   But "the sun" already works underwater in the mod as it is right now.   I'm just asking if you could toggle the blockstate so it looks better while doing what it _already_ does.

**Comment by xElementzx** [comment]
@Boolyman it was more or less a joke my friend 😂 relax

**Comment by Boolyman** [comment]
I am relaxed.

**Comment by brandon3055** [comment]
This will happen... eventually.... when i get around to it....
