### ISSUE TITLE
[1.16] Game crash during loading (probably caused by player soul)

### ISSUE THREAD

**Issue by filzaw80** [brandon3055/Draconic-Evolution#1602]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.18.428
* Minecraft Forge version: 36.2.20
* Mod Pack: (if applicable): AllTheMods 6-1.8.16

### Crash report

https://pastebin.com/k28a4geW

### Description / steps to reproduce

I was killed by my friend, and probably I dropped soul, everytime when I load right now or someone open my inventory, game crash. Friend was using fully enchanted Morgan. We are playing on server.

**Comment by brandon3055** [comment]
Try this build.
https://maven.covers1624.net/com/brandon3055/draconicevolution/Draconic-Evolution/1.16.5-3.0.20.434/Draconic-Evolution-1.16.5-3.0.20.434-universal.jar

**Comment by wxwildcat** [comment]
Not OP here but we encountered the same issue, we updated to the suggested version above but he still cant open his inventory. Is there a way to clear it from his inventory at all? Not entirely familiar with DE and the souls functions.

**Comment by filzaw80** [comment]
Hi @wxwildcat,

You can fix your problem using server command `/clear [targets] [item] [maxCount]`
You need to check what name have item, and who have it in inventory, after that you should be able to remove it without problem.

**Comment by brandon3055** [comment]
@wxwildcat Can you post your crash report please? The original crash posted by OP should not be possible now.
Also the command to clear mob souls from a player's inventory is 
`/clear [playername] draconicevolution:mob_soul`

**Comment by wxwildcat** [comment]
When the crash occurred I was on a previous build (3.0.19.428) but we then updated to .432 and used the clear command to fix it. Sorry for the confusion.

**Comment by FoxMcloud5655** [comment]
But you didn't try the build that Brandon posted above?

**Comment by wxwildcat** [comment]
I moved to the newer build after I read this post and the player still crashed when they opened their inventory. However once I ran the clear command on mob soul the problem was resolved
