### ISSUE TITLE
[1.16] <Title>game crash after opening tools tab 1.16.5 version

### ISSUE THREAD

**Issue by HMSRenown** [brandon3055/Draconic-Evolution#1603]
## Base information
* Minecraft version:1.16.5
* Mod version:Draconic-Evolution-1.16.5-3.0.19.432-universal
* Minecraft Forge version:36.2.22

### Crash report
[crash-2022-01-02_23.53.09-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/7799388/crash-2022-01-02_23.53.09-client.txt)

### Description / steps to reproduce
game crash after opening tools tab
I had disable shaders in the DE config
I use Magnesium but not Optifine

**Comment by FoxMcloud5655** [comment]
Try removing Magnesium first.

**Comment by HMSRenown** [comment]
> Try removing Magnesium first.

Yup，The Problem is solved

**Comment by HMSRenown** [comment]
> Try removing Magnesium first.

But when will DE adapt to Magnesium？

**Comment by Peca21** [comment]
Probably never

**Comment by FoxMcloud5655** [comment]
Never say never.  The Forge port of Magnesium is open source, so we can actually do something about it eventually.

**Comment by brandon3055** [comment]
This looks like an incompatibility between Magnesium and CCL. But CCL isn't in the business of writing custom support for every other mod that does funky stuff with the rendering system so this would have to be fixed from Magnesium's side.
