### ISSUE TITLE
[1.16] Problem with fusion crafting

### ISSUE THREAD

**Issue by phrostt** [brandon3055/Draconic-Evolution#1605]
## Base information
* Minecraft version: 16.5
* Mod version: Draconic-Evolution-1.16.5-3.0.18.428-universal
* Minecraft Forge version: 
* Mod Pack: (if applicable) ATM6

### Crash report
(If applicable)

### Description / steps to reproduce
Have automated infusion setups with redstone clocks connected to both. Sending a redstone signal to the 2nd injector, while the first injector is crafting, cancels the operation of the first injector.

**Comment by brandon3055** [comment]
Can you post a screenshot of your setup please

**Comment by hendrik1120** [comment]
was this fixed or closed because of inactivity?
