### ISSUE TITLE
[1.16.5] Mod draconic crashing when I mount the desktop

### ISSUE THREAD

**Issue by LeonardoBrunoCoro** [brandon3055/Draconic-Evolution#1606]
## Base information
* Minecraft version:1.16.5
* Mod version:1.16.5
* Minecraft Forge version:1.16.5 
* Mod Pack: I created

### Crash report
I am stirring on the draconic mod with other mods that I put in my .minecraft folder but it has reached a point where the mod simply crashes the minecraft and the world does not load

**Comment by FoxMcloud5655** [comment]
Crash report?  Gotta have that before we can diagnose anything about this.

**Comment by LeonardoBrunoCoro** [comment]
I set up draconic's desktop, when I went to link the crystals the game crashed

**Comment by FoxMcloud5655** [comment]
Again, we can't diagnose your issue without the crash report.  You can find it in `/crash-reports/`.

**Comment by LeonardoBrunoCoro** [comment]
[crash-2022-01-04_00.29.55-fml.txt](https://github.com/brandon3055/Draconic-Evolution/files/7834118/crash-2022-01-04_00.29.55-fml.txt)

**Comment by LeonardoBrunoCoro** [comment]
[crash-2022-01-08_20.30.26-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/7834122/crash-2022-01-08_20.30.26-client.txt)

**Comment by FoxMcloud5655** [comment]
```
java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:329) ~[?:?] {re:computing_frames,xf:OptiFine:default,re:classloading,xf:OptiFine:default
```
See that one thing there called OptiFine?  That's your problem.  OptiFine is not supported.

**Comment by brandon3055** [comment]
If you absolutely must have optifine then try disabling all shaders in the draconic evolution config.

**Comment by pingouin1743** [comment]
do you have brutal bosses in your modpack ?

**Comment by FoxMcloud5655** [comment]
Please don't necro an old issue.  Make a new one if you have one.

**Comment by pingouin1743** [comment]
but his problem isn't solve

**Comment by pingouin1743** [comment]
if you need brutal bosses in yout modpack try using the 2.5 version

**Comment by FoxMcloud5655** [comment]
Yes, his problem was solved.  Also, looking at the crash report, he does not have Brutal Bosses.  There is no reason to necro a near 9 month old issue for something completely unrelated.
