### ISSUE TITLE
[1.16] Breaking fusion crafting injector deletes it content

### ISSUE THREAD

**Issue by theArhar** [brandon3055/Draconic-Evolution#1608]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.19.432
* Minecraft Forge version: 36.2.22
* Mod Pack: TNP Limitless 3 1.11.7

### Crash report
Not a crash

### Description / steps to reproduce

Title says enough - put expensive stuff into injector, pickaxe it - opposite of profit

**Comment by brandon3055** [comment]
The injectors (and all other DE inventories) should retain their inventory when harvested. If that is not the case in your pack then something is interfering with DE's harvest logic. What pickaxe are you using to harvest the injectors?

**Comment by theArhar** [comment]
maybe lagged, cant reproduce
