### ISSUE TITLE
Unable to perform resurection ritual

### ISSUE THREAD

**Issue by Gloval** [brandon3055/Draconic-Evolution#161]
I am running DE 102 Snapshot 3.
I built the ritual but when I right click on the ritual stone the charged draconium blocks discharge but nothing happens.  No crash and no errors.  I got the effect of a lightening strike once but that's it.
Any ideas?

**Comment by brandon3055** [comment]
Is it possible you are right clicking the ritual stone more the once? Clicking the stone once will activate it but clicking the stone a second time will cancel the ritual and discharge the draconium blocks.

Sorry for that late reply i could have sworn i already replied to this issue.

**Comment by Gloval** [comment]
I  thought I may have done that the 1st time so had tried again to be sure before opening on this post. 
Ended up downgrading DE 1 version and the ritual worked. 
Have since moved on from the infinity pack. 

Thank you for responding.
