### ISSUE TITLE
the mod crashing my launcher in 1.10.2

### ISSUE THREAD

**Issue by Owther** [brandon3055/Draconic-Evolution#1612]
Hello
I want to play Mincraft with Draonic Evolution in 1.10.2 but when I started the game wih Draconic Evolution and Brandon’s Core because I can't play without Brandon’s Coreand the game crashing

Can you help me please, the mod is extraordinary

Owther

**Comment by FoxMcloud5655** [comment]
Draconic Evolution for 1.10.2 is unsupported.  If you ask on the Discord, you might get someone there who can help you, but it won't be official.
