### ISSUE TITLE
[1.16] Information Tablet light mode

### ISSUE THREAD

**Issue by NordicGamerFE** [brandon3055/Draconic-Evolution#1615]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.19.432
* Minecraft Forge version: 36.2.23
* Mod Pack: (if applicable)

### Description
I don't know if this fits in here, And I know its work in progress, The Information Tablet in light mode is incredibly hard to read, Why did I post this? well the Information Tablet has some information even tho its WIP so I thought it might be an easy fix since its already working fine in other GUI's

**Comment by FoxMcloud5655** [comment]
The information Tablet uses Project Intelligence as the backend for its info.  I suggest opening up an issue there instead.

**Comment by NordicGamerFE** [comment]
@FoxMcloud5655 Same creator, And even so Project Intelligence is not used in 1.16.5 as far as I know

**Comment by brandon3055** [comment]
I am about to release an alpha build of project intelligence for 1.16 which will resolve this issue.
