### ISSUE TITLE
[1.16] deserializeNBT crash (ConcurrentModificationException)

### ISSUE THREAD

**Issue by R4YVEN** [brandon3055/Draconic-Evolution#1624]
The server sometimes randomly crashes on ModuleHost.java:113

pls fix :)))))))

Stacktrace:

18.02 15:03:28 [Server] Netty Epoll Server IO #0/ERROR [minecraft/NettyPacketEncoder]: Error encoding packet
18.02 15:03:28 [Server] INFO java.util.ConcurrentModificationException: null
18.02 15:03:28 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390) ~[?:1.8.0_292] {}
18.02 15:03:28 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292] {}
18.02 15:03:28 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292] {}
18.02 15:03:28 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_292] {}
18.02 15:03:28 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292] {}
18.02 15:03:28 [Server] INFO at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:546) ~[?:1.8.0_292] {}
18.02 15:03:28 [Server] INFO at com.brandon3055.draconicevolution.api.capability.ModuleHost.getModuleData(ModuleHost.java:113) ~[draconicevolution:1.16.5-3.0.17.420] {re:classloading}
18.02 15:03:28 [Server] INFO at com.brandon3055.draconicevolution.items.equipment.IModularItem.lambda$initCapabilities$0(IModularItem.java:90) ~[draconicevolution:1.16.5-3.0.17.420] {re:classloading,pl:runtimedistcleaner:A}
18.02 15:03:28 [Server] INFO at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_292] {}
18.02 15:03:28 [Server] INFO at com.brandon3055.draconicevolution.api.modules.lib.ModuleHostImpl.gatherProperties(ModuleHostImpl.java:215) ~[draconicevolution:1.16.5-3.0.17.420] {re:classloading}
18.02 15:03:28 [Server] INFO at com.brandon3055.draconicevolution.api.modules.lib.ModuleHostImpl.deserializeNBT(ModuleHostImpl.java:333) ~[draconicevolution:1.16.5-3.0.17.420] {re:classloading}
18.02 15:03:28 [Server] INFO at com.brandon3055.draconicevolution.api.modules.lib.ModuleHostImpl.deserializeNBT(ModuleHostImpl.java:34) ~[draconicevolution:1.16.5-3.0.17.420] {re:classloading}
18.02 15:03:28 [Server] INFO at com.brandon3055.brandonscore.capability.MultiCapabilityProvider.lambda$deserializeNBT$2(MultiCapabilityProvider.java:63) ~[brandonscore:1.16.5-3.0.11.238] {re:classloading}
18.02 15:03:28 [Server] INFO at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_292] {}
18.02 15:03:28 [Server] INFO at com.brandon3055.brandonscore.capability.MultiCapabilityProvider.deserializeNBT(MultiCapabilityProvider.java:63) ~[brandonscore:1.16.5-3.0.11.238] {re:classloading}
18.02 15:03:28 [Server] INFO at com.brandon3055.brandonscore.capability.MultiCapabilityProvider.deserializeNBT(MultiCapabilityProvider.java:20) ~[brandonscore:1.16.5-3.0.11.238] {re:classloading}
18.02 15:03:28 [Server] INFO at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:139) ~[forge:?] {re:classloading}
18.02 15:03:28 [Server] INFO at net.minecraftforge.common.capabilities.CapabilityProvider.deserializeCaps(CapabilityProvider.java:152) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
18.02 15:03:28 [Server] INFO at net.minecraftforge.common.capabilities.CapabilityProvider.getCapabilities(CapabilityProvider.java:94) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
18.02 15:03:28 [Server] INFO at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:173) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
18.02 15:03:28 [Server] INFO at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
18.02 15:03:28 [Server] INFO at com.brandon3055.draconicevolution.api.capability.DECapabilities.writeToShareTag(DECapabilities.java:47) ~[draconicevolution:1.16.5-3.0.17.420] {re:classloading}
18.02 15:03:28 [Server] INFO at com.brandon3055.draconicevolution.items.equipment.IModularItem.getShareTag(IModularItem.java:224) ~[draconicevolution:1.16.5-3.0.17.420] {re:classloading,pl:runtimedistcleaner:A}
18.02 15:03:28 [Server] INFO at net.minecraftforge.common.extensions.IForgeItemStack.getShareTag(IForgeItemStack.java:376) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
18.02 15:03:28 [Server] INFO at net.minecraft.network.PacketBuffer.writeItemStack(PacketBuffer.java:308) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
18.02 15:03:28 [Server] INFO at net.minecraft.network.PacketBuffer.func_150788_a(PacketBuffer.java:290) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
18.02 15:03:28 [Server] INFO at net.minecraft.network.play.server.SEntityEquipmentPacket.func_148840_b(SourceFile:54) ~[?:?] {re:classloading}
18.02 15:03:28 [Server] INFO at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:38) ~[?:?] {re:classloading}
18.02 15:03:28 [Server] INFO at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[?:?] {re:classloading}
18.02 15:03:28 [Server] INFO at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at net.minecraft.network.NetworkManager.lambda$sendPacket$5(NetworkManager.java:196) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
18.02 15:03:28 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [server-1.16.5-20210115.111550-extra.jar:?] {}
18.02 15:03:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

**Comment by ItzPAX** [comment]
same, brandon fix plz man

**Comment by vierbaum** [comment]
same issue here, really annoying

**Comment by FoxMcloud5655** [comment]
Update Draconic Evolution to the latest version and verify that this still happens, please.  I have not noticed these issues with build 432.

**Comment by brandon3055** [comment]
As Fox stated please update and check if the issue is resolved.
A patch for this issue was implemented 4 versions / 5 months ago.
If by some chance this issue still occurs on the latest version then please open a new issue with the new crash report.
