### ISSUE TITLE
Enchantment of Tools and Armor

### ISSUE THREAD

**Issue by Ianaver** [brandon3055/Draconic-Evolution#163]
Enchanting tools by books is nice however I have noticed that some enchantments that are proper for the tool don't get accepted (like enderIO's XP boost for a sword). Also only books with SINGLE enchants are accepted, now I am not sure if this is intentional or not, but if it is, unless you add an enchant isolator to take off enchants, apply them to other books and have each book only contain one enchant or allow a book with 2+ enchants to be used (only applying those proper for the tool as most of the time books have enchants that pertain to multiple things) then enchanting will be a pain as often times as stated before, enchanted books usually apply to more than one type of thing.

**Comment by ReneMuetti** [comment]
I just noticed that as the Draconic Sword only Sharpness accepted. It is not possible for me, any hinzuizufügen another book. When bow I had success with any single book. I can not add a book so there.
Too bad I found that easy to get lost the books previously included when upgrading the weapons.

**Comment by brandon3055** [comment]
I have already added what you refer to as an "enchant isolator" The disenchanter can also be used to disenchant enchanted books. Allowing you to take a book with multiple enchants and transfer the extras to separate books.

**Comment by Ianaver** [comment]
ok, sorry about that.... I guess I need to go do more research before I post XD
