### ISSUE TITLE
Chaos Guardian crashing (ClassNotFound)

### ISSUE THREAD

**Issue by superckl** [brandon3055/Draconic-Evolution#166]
Hey there,

**Info**
Forge: `1.7.10-10.13.4.1448`
Draconic Evolution: `1.7.10-1.0.2-snapshot_4`
Stacktrace: http://pastebin.com/jGfC2uPE

We are running Draconic Evolution on a server (full modpack [here](http://www.curse.com/modpacks/minecraft/230575-nolimyn)), and one of the players recently traveled to fight the Chaos Guardian. However, when the Guardian spawned, the server immediately crashed with the above stacktrace. Any attempt to come in contact with the Guardian result in an immediate crash with the same stacktrace. It seems that the Chaos Bolt is looking for a class from ComputerCraft, which we are not running.

**Comment by brandon3055** [comment]
Oh darn i guess i wasnt paying attention when i imported that class... Will have a bug fix out as soon as possible.

**Comment by brandon3055** [comment]
Fix uploaded

**Comment by japherwocky** [comment]
Thank you, that was ridiculously fast!
