### ISSUE TITLE
Charm of dislocation crash

### ISSUE THREAD

**Issue by Goten87** [brandon3055/Draconic-Evolution#169]
https://gist.github.com/Goten87/691b24158405238ac530 

Draconic-Evolution-1.7.10-1.0.2-Snapshot_3

dont know if you have fix it alrdy with a newer version of the mod but right now with FTB infinity i crash when i try to make a waypoint on my server with the Enhanced Charm of Dislocation

edit: its only on my server singleplayer works oke

**Comment by brandon3055** [comment]
What dimension were you in when this happened? Or dose it happen in every dimension?

**Comment by Goten87** [comment]
its alrdy fixed with updating ftb infinety to 2.0.0
sorry for not updating but it was happening in age 997
