### ISSUE TITLE
Sword of the Wyvern wrong attack tooltip

### ISSUE THREAD

**Issue by GonzaloXavier** [brandon3055/Draconic-Evolution#17]
The tooltip says +15 damage but does actually 8 and with sharpness V says +21.5 but does 13.

**Comment by HighSpy** [comment]
I noticed this also.  Same problem with Smite.  Also seems to provide knockback by default, which imo is a terrible thing.

**Comment by brandon3055** [comment]
Thats because i use custom attack code so the vanilla tool tip is inaccurate. I will be fixing that at some point and increasing the attack damage.
