### ISSUE TITLE
Hovering mouse over "Unnamed" tools crashes the game.

### ISSUE THREAD

**Issue by SaKGEE** [brandon3055/Draconic-Evolution#172]
Forge: 10.13.4.1448
DE: 1.0.2 Snapshot 5 Bugfix.

Game crashes after hovering over tools. After opening the GUI the tools are also named "Unnamed" and don't have any tooltip info also before opening the GUI they are perfectly normal.
http://pastebin.com/k063Uezt
http://pastebin.com/vFJeGjmx

**Comment by XFactHD** [comment]
Please try to reproduce this crash without Botania, it is mentioned in the stack trace.

**Comment by SaKGEE** [comment]
It doesn't crash when Botania isn't enable but I cannot play on FTB Infinity server where it needs to be enabled :/

**Comment by GreatOrator** [comment]
Report this over at botania, looks like vazkii is doing something to the tooltip display which is causing this.
