### ISSUE TITLE
When using Sword of the Wyvern "true" is printed in server console

### ISSUE THREAD

**Issue by hErbsDK** [brandon3055/Draconic-Evolution#173]
Hey ..

This is my first time ever going in to the source code and looking for something, so please bear with me.

It seems that these lines are "spamming" the MC server console when the forementioned sword is in use.

> Found in:
> /src/main/java/com/brandon3055/draconicevolution/common/items/weapons/WyvernSword.java

>	public boolean hitEntity(ItemStack par1ItemStack, EntityLivingBase par2EntityLivingBase, EntityLivingBase par3EntityLivingBase)
>	{
>		System.out.println(par2EntityLivingBase.isEntityAlive());
>		System.out.println(par3EntityLivingBase.isEntityAlive());
>		return super.hitEntity(par1ItemStack, par2EntityLivingBase, par3EntityLivingBase);
>	}

If it isn't these lines then I don't know, but it is however still writing true ever so often when the sword is in use ;)

Side note: I have used it in a chest with a peaceful table, and it doesn't lose energy - not sure if this is DraEv or ExUtil though .. But it's pretty overkill to be able to have any enchanted book in a sword, and just leave it there for days without anything happening (well other than the "true" spam in console :P )

Thanks for listening

hErbs

**Comment by brandon3055** [comment]
oh oops that looks like some really old debug code i forgot to remove. I haven't used System.out in ages. Thanks for pointing that out.
