### ISSUE TITLE
Draconic Evolution 1.16.5 - 3D Models won't Render, only in first person hand or inventory

### ISSUE THREAD

**Issue by CalamityXIII** [brandon3055/Draconic-Evolution#1731]
Hey, having problems with Draconic Evolution in 1.16.5
BrandonsCore-1.16.5-3.0.15.248-universal
CodeChickenLib-1.16.5-4.0.7.445-universal
Draconic-Evolution-1.16.5-3.0.27.462-universal
forge-1.16.5-36.2.39
Custom Modpack

DE items will render in the inventory screen, as items, and in your hand in the 1st person view, but will not render out of first person or dropped on the ground. I've already tried disabling shaders but this just worsens the quality of the items and still doesn't render the items.
![image](https://user-images.githubusercontent.com/123514123/231186345-f8afdaf6-b3e5-4c31-a5f6-4d8722f4edc8.png)
![image](https://user-images.githubusercontent.com/123514123/231186481-ef60afb2-aa76-4545-b43d-522a85da3170.png)
![image](https://user-images.githubusercontent.com/123514123/231186544-e1841a39-790a-48a8-afc4-9a968ba54f22.png)
![image](https://user-images.githubusercontent.com/123514123/231186592-e82ff79c-3d01-4293-9924-982b2cee5025.png)

Modlist:
3dSkinLayers-forge-1.1.0
abnormals_core-1.16.5-3.3.1
abnormals_delight-1.16.5-1.2.1
Adorn-1.14.3+1.16.5-forge
alexsmobs-1.12.1
appliedenergistics2-8.4.7
Aquaculture-1.16.5-2.1.23
Architects-Palette-1.16.4-1.1.5
architectury-1.32.66
Artifacts-1.16.5-2.10.5
atmospheric-1.16.5-3.1.1
AttributeFix-1.16.5-10.1.4
AutoRegLib-1.6-49
autumnity-1.16.5-2.1.2
Babel-1.0.5
backpacked-2.1.8-1.16.5
BackTools-1.16.5-10.2.0
BadMobs-1.16.5-9.1.9
bamboo_blocks-1.16.5-3.0.1
Bayou-Blues-1.16.5-1.0.5
BetterAdvancements-1.16.5-0.1.1.115
Better-Badlands-1.16.5-2.0.3
BetterCaves-Forge-1.16.4-1.1.2
BetterCompatibilityChecker-1.0.7-build.22+mc1.16.5
BetterDungeons-1.16.4-1.2.1
betterendforge-1.16.5-2.8
BetterMineshafts-Forge-1.16.4-2.0.4
BetterModsButton-v1.0.5-1.16.5-Forge
BetterStrongholds-1.16.4-1.2.1
BH-Menu-1.16.5-1.3
BiomesOPlenty-1.16.5-13.1.0.488-universal
BloodMagic-1.16.4-3.1.13-39
blue_skies-1.16.5-1.1.3
Boat-Item-View-Forge-1.16.5-0.0.2
Bookshelf-Forge-1.16.5-10.4.33
Bountiful-1.16.4-3.3.1
BrandonsCore-1.16.5-3.0.15.248-universal
buzzier_bees-1.16.5-3.0.3
byg-1.3.5
byg-1.3.6
bygonenether-1.2.2-1.16.5
caelus-forge-1.16.5-2.1.3.2
carryon-1.16.5-1.15.5.22
cavebiomeapi-1.16.5-1.4.2
cavesandcliffs-1.16.5-7.2.0
CavesCliffsBackportAdditions-3.4.1jar
chipped-1.16.5-1.2.1-forge
chocolate-1.3.0-1.16.4
chunksavingfix-0.1.0
citadel-1.8.1-1.16.5
cleancut-mc1.16-2.2-forge
ClientTweaks_1.16.3-5.3.0
cloth-config-4.16.91-forge
Clumps-6.0.0.28
CNB-1.16.3_5-1.2.11
CodeChickenLib-1.16.5-4.0.7.445-universal
cofh_core-1.16.5-1.5.0.11
collective-1.16.5-5.49
ColtCosmeticArmorMod-1.2.5
combustivefishing-forge-1.16.3-4.0.0.1
comforts-forge-1.16.5-4.0.1.5
ConfigMenusForge-v1.2.0-1.16.5-Forge
connectivity-2.4-1.16.5
Controlling-7.0.0.29
copperpot-1.16.5-1.2.0
corpse-1.16.5-1.0.6
corpse-1.16.5-1.0.7
CosmeticArmorReworked-1.16.5-v5
create-mc1.16.5_v0.3.2g
crumbs-forge-1.0.7
culturaldelights-1.16.5-0.9.2
cuneiform-1.16.3-1.2.5
curioofundying-forge-1.16.5-5.2.0.0
curios-forge-1.16.5-4.0.8.2
curios-forge-1.16.5-4.1.0.0
curiouselytra-forge-1.16.5-4.0.2.3
curiouselytra-forge-1.16.5-4.0.2.4
darkerdepths-1.16.5-1.1.4
DarkPaintings-1.16.5-6.0.11
decorative_blocks_abnormals-1.2
decorative_blocks-1.16.4-1.7.2
deepdark_4.2
DefaultOptions_1.16.5-12.2.1
deuf-1.16.5-1.1
DiagonalFences-v1.1.1-1.16.5
differentiate-1.16.5-0.5.3
does_potato_tick-1.16.5-3.3
Draconic-Evolution-1.16.5-3.0.27.462-universal
drippyloadingscreen_forge_1.6.6_MC_1.16.2-1.16.5
dungeons_plus-1.16.5-1.1.5
DungeonsArise-1.16.5-2.1.49-beta
dynamiclightsreforged-mc1.16.5_v1.0.1
DynamicSurroundings-1.16.5-4.0.5.0
EasyMagic-v1.0.4-1.16.5
Electrodynamics-1.16.5-0.5.0-2
elevatorid-1.16.5-1.7.13
EnchantmentDescriptions-1.16.5-7.1.20
endergetic-1.16.5-3.0.2
EnderStorage-1.16.5-2.8.0.170-universal
enhancedcelestials-2.0.9-1.16.5
Enhanced-Mushrooms-1.16.5-3.0.9
entity_texture_features_forge_1.16.5-4.3.1
entitycollisionfpsfix-1.16-1.0.1
entityculling-forge-mc1.16.5-1.5.2
environmental-1.16.5-1.1.1
EquipmentCompare-1.16.5-1.3.2
expandability-2.0.0-forge
expandability-2.0.1-forge
extendedmushrooms-1.16.5-1.7.0.5
extraboats-1.16.5-2.1.1
Fallingleaves-1.16.3-1.2.4
FallingTree-1.16.5-2.11.6
fancymenu_forge_2.13.3_MC_1.16.2-1.16.5
FarmersDelight-1.16.5-0.6.0
farmersdelightintegrations-1.16.5-1.2
farsight-1.7
FastLeafDecay-v25.2
ferritecore-2.1.1-forge
flywheel-1.16-0.2.5
forge-branders-spawnermod-1.16.5-1.8.14
frozenup-1.0.1
ftb-backups-2.1.2.2
ftb-chunks-forge-1605.3.4-build.220
ftb-library-forge-1605.3.4-build.90
ftb-quests-forge-1605.3.7-build.165
ftb-teams-forge-1605.2.3-build.40
geckolib-forge-1.16.5-3.0.106
glasscutter-1.1.1-1.16.5
goblintraders-1.7.3-1.16.5
guardvillagers-1.16.5.1.2.6
Highlighter-1.16.5-1.1.1
HostileNeuralNetworks-1.16.5-1.0.7
HunterIllager-1.16.5-1.4.0
iceandfire-2.1.10-1.16.5
Iceberg-1.16.5-1.0.45
iChunUtil-1.16.5-10.6.1
illagersweararmor-1.0.5
immersivecooking-1.2.0
ImmersiveEngineering-1.16.5-5.1.0-148
InventoryHud_[1.16.2-1.16.5].forge-3.4.1
ironchest-1.16.5-11.2.21
irregularchef-1.16.5-1.0.1
item-filters-forge-1605.2.5-build.9
Jade-1.16.4-2.8.3
jei-1.16.5-7.7.1.152
jei-1.16.5-7.8.0.1009
JEIEnchantmentInfo-1.16.5-1.3.0
JEPB-1.0.0
JustEnoughProfessions-1.16.5-1.2.2
JustEnoughResources-1.16.5-0.12.1.133
Kiwi-1.16.5-3.6.1
KleeSlabs_1.16.5-9.2.1
konkrete_forge_1.6.0_MC_1.16.2-1.16.5
kotlinforforge-1.17.0-obf
kryptonreforged-mc1.16.5_v1.0.0
L_Enders Cataclysm-0.48 Changed Theme -1.16.5
lazydfu-0.1.3
letmedespawn-forge-1.16-1.0.2a
lootintegrations-1.2
magnesium_extras-mc1.16.5_v1.4.0
Mekanism-1.16.5-10.1.2.457
MekanismAdditions-1.16.5-10.1.2.457
MekanismGenerators-1.16.5-10.1.2.457
MekanismTools-1.16.5-10.1.2.457
modernfix-mc1.16.5-1.9.1
MorePaths-1.16.1-1.3.2
morevillagers-FORGE-1.16.5-1.5.5
MouseTweaks-2.14-mc1.16.2
mowziesmobs-1.5.27
NaturesCompass-1.16.5-1.9.1-forge
neapolitan-1.16.5-2.2.1
NekosEnchantedBooks-1.16-1.7.0
NetherPortalFix_1.16.3-7.2.1
nethers_delight-2.1
NightConfigFixes-v1.0.1-1.16.5-Forge
Nuclear_Science-1.16.5-0.4.0-1
Nuclearcraft-1.16-A0.3.2
obfuscate-0.6.3-1.16.5
oculus-1.4.5
omnis-1.16.5-1.2.3
OuterEnd-0.2.14
overloadedarmorbar-5.1.0
paintings-1.16.4-7.0.0.1
Patchouli-1.16.4-53.3
Paxi-Forge-1.16.4-1.0
personality-1.16.5-1.0.3
PGA-1.16.4-1.1.2.1
PickUpNotifier-v1.2-1.16.3
Placebo-1.16.5-4.7.0
polymorph-forge-1.16.5-0.41
PuzzlesLib-v1.0.15-1.16.5-Forge
Quark-r2.4-322
randompatches-2.4.4-forge
repurposed_structures_forge-3.4.7+1.16.5
ResourcePackOverrides-v1.0.0-1.16.5-Forge
RevampedWolf-1.16.4-0.7.1
RoadRunner-mc1.16.5-1.4.1
rubidium-0.2.11
saturn-mc1.16.5-0.0.3
savageandravage-1.16.5-3.2.0
seasonhud-1.16.5-1.4.6
selene-1.16.5-1.9.0
SereneSeasons-1.16.5-4.0.1.127-universal
shieldexp-1.16.5-alpha-0.1
SimpleDiscordRichPresence-1.4.0-build.3+mc1.16.5
simpleshops-1.1.3
SimpleStorageNetwork-1.16.5-1.5.3
smarterfarmers-1.16.5-1.2.1
smoothboot-forge-1.16.4-1.2.2
snowrealmagic-1.16.5-2.10.0-1.16.5
snowundertrees-1.16.5-v1.3
SoL-Carrot-1.16.5-1.10.1
sophisticatedbackpacks-1.16.5-3.15.16.669
sophisticatedbackpacks-1.16.5-3.15.20.755
spark-1.9.1-forge
SpawnerFix-1.16.2-1.0.0.2
stalwart-dungeons-1.16.5-1.1.7
starlight-1.2
starterkit_1.16.5-4.1
strawgolem-1.16-1.9
structure_gel-1.16.5-1.7.8
supplementaries-1.16.5-0.18.5
takesapillage-1.0.3-1.16.5
Talpm 1.0.0 1.16.5
TextruesRubidiumOptions-1.0.4-mc1.16.5
TheAbyss2 2.2.3-4 1.16.5
the-conjurer-1.16.4-1.0.13
thermal_cultivation-1.16.5-1.5.0.4
thermal_expansion-1.16.5-1.5.0.7
thermal_foundation-1.16.5-1.5.0.14
thermal_innovation-1.16.5-1.5.0.4
thermal_locomotion-1.16.5-1.5.0.4
Tips-1.16.5-4.0.18
torchmaster-2.3.8
toughnessbar-6.1
TradingPost-v1.0.2-1.16.5
travelers_index-1.16.4-1.0.2
TravelersBackpack-1.16.5-5.4.14
twilightforest-1.16.5-4.0.870-universal
upgrade_aquatic-1.16.5-3.1.2
upgradedcore-1.16.5-1.1.0.3-release
upgradednetherite_items-1.16.5-1.1.0.2-release
upgradednetherite_ultimate-1.16.5-1.1.0.3-release
upgradednetherite-1.16.5-2.1.0.1-release
veinmining-forge-1.16.5-0.18
villagernames_1.16.5-4.3
villagertools-1.16.5-1.0.2
VisualWorkbench-v1.1.0-1.16.5
voidtotem-1.16.5-1.4.0
walljump-forge-1.16.4-1.3.7
Waystones_1.16.5-7.6.4
what_did_you_vote_for-1.16.5-1.0.5
woodcuttercompats-1.16-1.2
Xaeros_Minimap_23.1.0_Forge_1.16.5
XaerosWorldMap_1.28.9_Forge_1.16.5
xlpackets-1.16.4-1.2
xptome-1.16.5-v2.1.5
YungsApi-1.16.4-Forge-13
YungsBridges-Forge-1.16.4-1.0.1
YungsExtras-Forge-1.16.4-1.0

**Comment by FoxMcloud5655** [comment]
Don't use Rubidium or Oculus.
