### ISSUE TITLE
Chaos Guardian Able To Kill Players In Creative

### ISSUE THREAD

**Issue by HyperionNexus** [brandon3055/Draconic-Evolution#175]
So in the latest DE snapshot I noticed that when fighting the Guardian that it can kill you with a chaos ball. It can also kill you with it's fireballs if you don't have any armor. Since this is creative I'd expect the attacks to not work on players (aside from knockback.). If you get hit by even one fireball without armor, you're dead, if you're hit with a chaos ball with armor... you're dead. 

I'm not sure if this is intentional or not but it'd be nice if we didn't die in creative while fighting it for the fun of it.

Also, I noticed that the Guardian can use a chaos ball really early with next to no damage on itself. Personally, I think he should use that once his health is below half or a quarter.

**Comment by GreatOrator** [comment]
That is because the Chaos dragon uses the only damage type known that kills create players...void damage

**Comment by HyperionNexus** [comment]
Is there a way to kill it though without constantly dying? I mean, unless you're on a server with lots of others I find it unlikely of defeating the guardian as if you die you loose your stuff or it's in a grave which is hard to get too since you'd need to go back to the end and than travel all the way to the cords and most likely die again.

**Comment by GreatOrator** [comment]
It is intended to be the toughest mob in minecraft, full draconic with no enchants, and a handfull of draconic capacitors should be enough to kill it, oh and draconic staff

**Comment by HyperionNexus** [comment]
Yeah, I remembered about the draconic capacitors and was able to defeat it with one capacitor and 5 TE creative capacitors.

**Comment by GreatOrator** [comment]
so you effectively cheated to kill him :D

**Comment by kkjdroid** [comment]
No mob should be able to kill creative players. That's the point of creative mode.

**Comment by GreatOrator** [comment]
Except, the point of the chaos dragon is to buck that trend.  It is intended.
