### ISSUE TITLE
Custom Fusion Recipe not working

### ISSUE THREAD

**Issue by GabrielM2025** [brandon3055/Draconic-Evolution#1765]
Im creating a modpack in 1.18.2 for me and my friends and i wanted to add some custom recipes with draconic, im using the json metode but it isnt working can someone help me??

Wheres the code:
[{"mode": "ADD",
"result":"avaritia:crystal_matrix_ingot",
"catalyst":"minecraft:nether_star",
"energy": 5000000,
"tier": 2,
"ingredients": [
"minecraft:diamond_block",
"minecraft:diamond_block",
"extendedcrafting:ender_star",
"extendedcrafting:ender_star"
]}]

**Comment by FoxMcloud5655** [comment]
Custom Fusion Crafting recipes do not exist in JSON form anymore. Use datapacks instead. If you're curious about the format, look at the source code here.
