### ISSUE TITLE
Crash When Trying To Open Anything With Tablet

### ISSUE THREAD

**Issue by HyperionNexus** [brandon3055/Draconic-Evolution#177]
Whenever I try to open the Draconic portal, and Draconic reactor in the tablet I crash. I'm not sure if it affects all of them.

Crash Report: http://pastebin.com/GsK8LMFt

**Comment by Ianaver** [comment]
Confirmed

**Comment by karakufire** [comment]
I have encountered this crash same exception.
My situation: when I tried to open chaos island's page.
Crash report -> http://pastebin.com/nnV8Yri4

**Comment by DestinyPlayer** [comment]
Can confirm this, crashes me whenever I try to open anything in the tablet.

**Comment by Ianaver** [comment]
This is confirmed with opening anything....

**Comment by wlhlm** [comment]
Yep, looks like a copy'n'paste error. Fix should be fairly straight forward.

**Comment by GreatOrator** [comment]
I've let brandon know, and this is exactly why we do snapshots :D

**Comment by brandon3055** [comment]
Will be uploading another bugfix today.

**Comment by Ianaver** [comment]
@brandon3055 Confirmed again with the snapshot bugfix 8 http://paste.ubuntu.com/13657073/

**Comment by Ianaver** [comment]
for those who saw my last comment, I realized I made a mistake XD I had forgotten to get the latest snapshot and thought the bug was still there
