### ISSUE TITLE
Draconic Resurrection ritual would not work

### ISSUE THREAD

**Issue by TheTenthDoctor95** [brandon3055/Draconic-Evolution#178]
https://www.youtube.com/watch?v=ZlIsHhuKHpo

I start setting up the ritual at 17:45

**Comment by wlhlm** [comment]
Does it work using regular Quartz Pillars?

**Comment by HyperionNexus** [comment]
You used Certus Quartz Pillars. Pretty sure you can only use vanilla Quartz Pillars.

**Comment by GreatOrator** [comment]
Nice catch!  Was watching to see what was out of place but did not cotice that.  Yes, has to be vanilla quartz pillars

**Comment by TheTenthDoctor95** [comment]
Ah gotcha, alright thanks!
