### ISSUE TITLE
Item Conduit Won't Extract from Draconic Chests

### ISSUE THREAD

**Issue by NuclearTogekiss** [brandon3055/Draconic-Evolution#179]
Modpack Name : FTB Infinity

Modpack Version : 2.1.0

Launcher Version  1.4.11

I have not edited the mod pack

**Comment by GreatOrator** [comment]
Do you have any screen shots of your setup?

**Comment by NuclearTogekiss** [comment]
![2015-11-28_14 30 11](https://cloud.githubusercontent.com/assets/16063242/11454327/ac302a0e-95dc-11e5-8d79-9779cf220dfe.png)
![2015-11-28_14 29 15](https://cloud.githubusercontent.com/assets/16063242/11454325/ac2f2302-95dc-11e5-8c1d-4032dbb60da0.png)
![2015-11-28_14 29 26](https://cloud.githubusercontent.com/assets/16063242/11454326/ac2fcbe0-95dc-11e5-98c3-0b6067b881c6.png)
![2015-11-28_14 29 34](https://cloud.githubusercontent.com/assets/16063242/11454328/ac33081e-95dc-11e5-92db-9f5ae108c694.png)
![2015-11-28_14 32 10](https://cloud.githubusercontent.com/assets/16063242/11454334/da08c346-95dc-11e5-9fa8-d59f11d2b992.png)
![2015-11-28_14 32 05](https://cloud.githubusercontent.com/assets/16063242/11454335/da0b84aa-95dc-11e5-9845-8a7867a937d6.png)

do item conduit not work with item barrels?
