### ISSUE TITLE
RF API is out of date.

### ISSUE THREAD

**Issue by KingLemming** [brandon3055/Draconic-Evolution#18]
Just a heads up for you, your RF API is outdated. That will cause a few issues. ;)

When sending power, you should be looking for IEnergyReceivers.

**Comment by brandon3055** [comment]
Thanks for the heads up! Infact i bet that is the cause of a bug i have been meaning to investigate (A block not outputting directly to tesseracts)

**Comment by brandon3055** [comment]
RF API is now up to date.
