### ISSUE TITLE
awakening ritual blast absorption 

### ISSUE THREAD

**Issue by theboo89** [brandon3055/Draconic-Evolution#183]
just did the awakening ritual in the latest update and i noticed that the heart no longer absorbs the TNT blast, making a large hole underneath making it hard to place the charged blocks under the heart.. dunno if this was on purpose, but im just glad i didnt do it in my base like i normally do haha... its not that big of a problem, i just do it away from my base on a layer of obsidian... just thought id let you know.

**Comment by brandon3055** [comment]
It has always worked like this.
