### ISSUE TITLE
Draconic Evolution Snapshot 7 Crash Problem

### ISSUE THREAD

**Issue by TheTenthDoctor95** [brandon3055/Draconic-Evolution#185]
The newest version of Draconic Evolution, snapshot 7, crashes my game whenever I click on any entries in the Draconic Evolution Information Tablet
[crash-2015-11-29_23.01.35-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/46969/crash-2015-11-29_23.01.35-client.txt)

**Comment by wlhlm** [comment]
#177

**Comment by GreatOrator** [comment]
This has already been reported. Closing
