### ISSUE TITLE
[1.20.1] AMD driver DLL crash after adding Draconic Evolution

### ISSUE THREAD

**Issue by MiguelEXE** [brandon3055/Draconic-Evolution#1858]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.598
* Minecraft Forge version: 47.3.0
* Mod Pack: a private modpack. Mod list [here](https://pastebin.com/ZnXWngpd)

### Crash report
- https://files.catbox.moe/rz9n32.log (JVM crash)
- https://files.catbox.moe/uc83n3.log (latest.log)

### Description / steps to reproduce
Unknown, after adding Draconic this error ocurred
Seeing the repo issues it's possibly a conflict between Ice and Fire, Draconic and FTB Chunks (both included)

**Comment by FoxMcloud5655** [comment]
Try updating your GPU drivers first, then we'll see if this problem persists.

**Comment by MiguelEXE** [comment]
> Try updating your GPU drivers first, then we'll see if this problem persists.

I updated the driver before making the issue, still doesnt work
(the JVM which crashed was running on the latest driver)

**Comment by FoxMcloud5655** [comment]
Then yes, it's the issue opened at #1826.
