### ISSUE TITLE
[1.20.1] Crash on opening draconic items config screen

### ISSUE THREAD

**Issue by oskarbukovsky** [brandon3055/Draconic-Evolution#1859]
## Base information
* Minecraft version: 1.20.1
* Mod version: 3.1.2.598
* Minecraft Forge version: 47.3.12
* Mod Pack: (if applicable) https://www.curseforge.com/minecraft/modpacks/tech-craft-neobox

### Crash report
[crash-2024-12-08_22.57.33-client.txt](https://github.com/user-attachments/files/18054175/crash-2024-12-08_22.57.33-client.txt)

[crash-2024-12-08_22.44.44-client.txt](https://github.com/user-attachments/files/18054180/crash-2024-12-08_22.44.44-client.txt)

### Description / steps to reproduce
When clicking keybing to open draconic items config screen, game crash. Crashing on at least 2 pcs with my modpack. I'm not sure where the problem come from, maybe some incompatiblity, but in update it was more things, so i'm reaching here as it shows DE screen render problem from what i can understand from crashlog.

**Comment by FoxMcloud5655** [comment]
Not only is your modpack huge (please test with minimum required mods and work up from there to find mod incompatibilities), you also have Fabric mods installed.

On top of that, your single Fabric mod heavily affects rendering.

To say that this is unsupported is a vast understatement.
