### ISSUE TITLE
[1.20.4] Chaos island not generating

### ISSUE THREAD

**Issue by QwerProba1** [brandon3055/Draconic-Evolution#1861]
## Base information
* Minecraft version: 1.20.4
* Mod version: 3.1.2.601 (Alpha)
* Minecraft NeoForge version: 20.4.237
* Mod Pack: None

### Crash report
None

### Description / steps to reproduce

Chaos island (nor chaos guardian nor chaos crystal ) not generating at 10k coordinates. I have checked configs, they are ok. I have also tried only DE mod with requiered dependecies (brandons core, codechickenlib), but still nothing. New worlds didn't helped as well.
Also draconium ore was not generating at all.

Maybe this feature is not added yet in this version (because its Alpha). If so, please answer which is highest version that works normally.

**Comment by FoxMcloud5655** [comment]
That would be the 1.20.1 release that I have personally tested.

I'm actually surprised that I missed this in my own testing.

**Comment by QwerProba1** [comment]
Oh I see. Do it planned to service 1.20.4 version (and fix this bug as well)? Im creating own modpack, where one key mod is on 1.20.4 at least or on Fabric, so i cannot switch version to 1.20.1. Draconic evolution is second key mod here

**Comment by brandon3055** [comment]
Fixed, 
Should be on curse and Modrinth soon.

**Comment by QwerProba1** [comment]
**Thank you,** chaos guard and ore spawn **works** as intended. I found other bugs, but will write them in new post
