### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TheTenthDoctor95** [brandon3055/Draconic-Evolution#189]
It would be really cool if there were some way to trap the Ender Dragon :P I mean you can bring it to the overworld with the Draconic Portal, but I'd like to be able to keep it as a pet
:P

**Comment by brandon3055** [comment]
Have you considered dragon mounts?

**Comment by TheTenthDoctor95** [comment]
I don't want or need to ride it, I have a TARDIS! I want to put it on display in my TARDIS 😁

**Comment by GreatOrator** [comment]
Dragon mounts would still allow for that
