### ISSUE TITLE
[Bug] Chaos Guardian does not respect gamemode or difficulty

### ISSUE THREAD

**Issue by the-maldridge** [brandon3055/Draconic-Evolution#191]
Moderators in creative mode are being targeted by the chaos guardian.  It does not ignore them like other mobs, it also seems to ignore the difficulty setting of the world and fails to despawn in peaceful mode.  Since these are both non-standard mob behaviors, I believe this to be a bug.

**Comment by HyperionNexus** [comment]
The Chaos Guardian is meant to be the hardest boss so difficulty isn't really a factor. Unless brandon adds a config option for the old Chaos Guardian behavior. Also, the Ender Dragon doesn't despawn or disappear in peaceful mode and a Chaos Guardian is a more intense Ender Dragon so it's not going to despawn or disappear.

**Comment by the-maldridge** [comment]
Thank you for your reply.  While I will accept that this behavior is normal during peaceful mode.  I still cite targetting creative, op'd players is non-standard and still a bug.

**Comment by XFactHD** [comment]
This is not a bug, it is vanilla behaviour. The damage source used by the chaos dragon is void damage and even a player in creative mode is killed when he jumps into the void.

**Comment by luckyp3616** [comment]
Then you should change the damage type. Someone needs to make a mod to change void damage behavior.
