### ISSUE TITLE
(SUGGESTION) EMC

### ISSUE THREAD

**Issue by TheTenthDoctor95** [brandon3055/Draconic-Evolution#194]
Hey, I wanted to make the suggestion of implementing EMC values to some of the items, specifically draconium ingots. The reason is, unless you have hardcore ender expansion, which is a huge mod, like 15,000 kb, you're kind of screwed on getting draconium after you mine the little bit in the end. In contrast, ProjectE is only about 1,000 kb, and it would fix that problem. Now I know some people think that ProjectE is basically cheating, but 1. It takes a very long time to be able to generate a good amount of EMC, and 2. if you make it to where the draconium dust has a medium to high emc value, like Yellorium ingots are about 4.5k EMC, so maybe make draconium ingots have an EMC value of like 10,000 EMC or something like that? I have a limited amount of KB that I can use in my modpack, and I don't really want Hardcore Ender Expansion installed, because there are a LOT of other cooler mods that I'd rather use, so for those of us that use your amazing mod (one of my favorites by the way) that also have limitations on how big of a modpack our computers can handle, I think I can speak for all of us when I say that we'd really appreciate you to at least consider it! Thanks for taking the time to read my suggestion! Allons-y!

-TheTenthDoctor95

**Comment by HyperionNexus** [comment]
Ender Comets provide a ton of Draconium Ores and I doubt you've mined every single one. You can also install some of Reika's mods to add an infinite end (not sure if any others add that). You would need to regenerate the end though.

**Comment by TheTenthDoctor95** [comment]
The problem with ender comets is that they are so damn hard to find! And how would one regenerate the end?

**Comment by GreatOrator** [comment]
First - End regeneration: Simply delete the folder for the end from your world, it will be regenerated after a server restart or when you reload the world in single player.

As for EMC, Draconium is deliberately hard to find, that is one of the key ways the power of the mod is balanced and was also after a TON of discussion between brandon and I

**Comment by TheTenthDoctor95** [comment]
Alright, well it was just a suggestion :) thanks for your time! Oh, also do you know if it's possible to create a block that not even the ender dragon can break?

**Comment by GreatOrator** [comment]
As far as I am aware, any block with hardness of bedrock can't be broken by the dragon.

**Comment by TheTruth77** [comment]
i have a emc value suggestion, the doctor here said 10000 emc, but once you have a good amount it becomes too easy to get items of that emc value, i myself have over 20 mil emc in my transmutation table, i know it it supposed to be hard to get but my suggestion is balanced to your standards, why not set the emc value to a VERY expensive amount, something like, here it goes, 10 MILLION EMC PER DUST, that is 10 times more expensive than a red matter block by the way, this will force people to continue to search for the comets for the ores, along with trying to get enough emc to actually get one dust. 
ps. i have the emc set to this number via the /setemc command in project E as a thought it was fair.

**Comment by GreatOrator** [comment]
The only issue is that no matter what it is set at, players can still choose any value using commands honestly, and as far as ProjectE, I have watched players using that mod in videos, and honestly, while well written, is still way to cheaty, so I think leaving players to decide their own EMC values should stand.

**Comment by TheTruth77** [comment]
that is fine its all up to you after all.

**Comment by TheTruth77** [comment]
i have a question regarding the caos guardian, is he supposed to take literally five hours to kill?, i time it myself.
