### ISSUE TITLE
Bug Involving stabilized spawners.

### ISSUE THREAD

**Issue by Fatthunder** [brandon3055/Draconic-Evolution#196]
-BrandonsCore-1.0.0.10
-Draconic Evolution-1.7.10-1.0.2-Snapshot_8

So I am using fully upgraded stabilized spawners and I have a possibly a bug.  I will be referring to the images within the link. (http://imgur.com/a/41yJR).  As you can see each of the current stabilized spawners I have place a mob just below y coord 0.  I believe this is intentional, however as you can see there is a multitude of ghasts just floating their.  I would assume if the ghast spawner was working like the others there should only be one, but as you can see there are many. They do not despawn, and can not be attack, they also count as entities within the world.

**Comment by GreatOrator** [comment]
Not sure what I am looking at actually, but the mobs from the spawners are intended to not despawn especially if they are upgraded to ignore player requirement.

**Comment by Fatthunder** [comment]
So don't think I was specific, but picture #4 shows where the mobs are spawning within the game and being killed.  Pictures #1-3 show the void of the same dimension in which the spawners are in.  The floating mobs seen are just at the void level.  I assume that they are placed there by the mod for some reason and the the would normally fall into the void, but b/c ghasts can fly they just sit there an accumulate, causing entities to build up.

**Comment by GreatOrator** [comment]
not so much a bug as a mechanic of minecraft, why would you build your spawners at y0 anyways?

**Comment by Fatthunder** [comment]
The spawners themselves aren't at y0, they are at around y12,  there just happens to be mobs spawning at y0 for some reason,  and they are that low since I am using transfer nodes to suck up the items, and I don't wont to have to be bothered with where I drop other items.

**Comment by brandon3055** [comment]
I have not been able to replicate this. In my testing when a ghast spawns and goes bellow y 0 it just continues to fly around and can still be killed. If this is in your private world (meaning you have access to cheat mode) try replacing the spawner with a few vanilla ghast spawner and let me know if they have the same problem.

**Comment by Fatthunder** [comment]
Sorry for such a delayed response, but I have have been able to do the test you requested.  When done I have found that a vanilla spawner does indeed cause the same problem. Removing both the empowered and vanilla spawners does make the fake entities disappear after I reload the world.  So it does seem as if it is on my side.  I will look deeper into the problem and see if I can find the cause.  Sorry for the trouble.
