### ISSUE TITLE
Dragonic/Wyvern armor enchants

### ISSUE THREAD

**Issue by Mr-Rixa** [brandon3055/Draconic-Evolution#197]
I've noticed that you can get Thorns enchant on boots (and leggings) by enchanting but if you take them off you can't put them back on from GUI. I'm not sure if this is intended functionality or a bug.

**Comment by 6210classick** [comment]
some enchants are like that you just have to apply them again using an Anvil

and seriously Thorns ? why do you even need any enchantment beside EIO soul-Bound ?

**Comment by Mr-Rixa** [comment]
Besides the point. I just happened to notice that this occurs while I was playing around with enchants and wondered if it's a bug.

**Comment by brandon3055** [comment]
Not sure how you are able to put it on your boots with an enchanting table but thorns is a chestplace only enchant which is why you cant reapply it via the gui.
