### ISSUE TITLE
Energy Core Energy display occasionally freezes

### ISSUE THREAD

**Issue by chaNcharge** [brandon3055/Draconic-Evolution#199]
I'm not sure what causes it to stop showing you how much energy is in the core, but basically, what happens is that on occasion, usually around 2 billion RF and filling up at around 12kRF/tick, the energy display just freezes. For example, it will be stuck at exactly 2,234,543,275 RF and only updating occasionally. I have to break the energy core and then replace it starting with 0 RF and it really annoys me that I have to waste 2 billion RF just to make it work again. Energy is going in and out of the core, but when you look at the core, nothing changes so I can't tell if my energy is going up or down.

**Comment by wlhlm** [comment]
I have observed similar behavior. Though I wasn't able to find any pattern. It would get stuck get stuck on varying energy levels. Sometimes this was just a visual glitch, meaning that the overlay would get stuck, but the energy level still changes in background. On other occasions, it froze completely, essentially meaning the core provided free energy.

This wouldn't go away across world reloads. My fix was to adjust the the energy level slightly using a NBT editor.

I haven't encountered it since upgrading to Snapshot 8, which doesn't mean that it has been fixed.

@chaNcharge What version of Draconic Evolution + Brandons Core are you using?

**Comment by HyperionNexus** [comment]
Are you looking at the core/sphere itself or the pylons that insert/extract RF? It seems that the pylons show the accurate RF/t.

**Comment by wlhlm** [comment]
@HyperionNexus I've only looked at the core. The pylons only show data in WAILA and their value is capped at 2 billion, which I assume is a limitation of the RF API. I remember freezes happening at 11 billion and 24 billion RF on a Tier 6 (upgraded from Tier 5) core, so I don't think it's limited by MAXINT.

**Comment by chaNcharge** [comment]
@wlhlm Yes, sometimes, I have an MFR Laser Drill at maximum power, and I just get free infinite energy, reloading doesn't work, but yes, sometimes it is a visual glitch. I also just realized that I haven't updated my Draconic Evolution (I have snapshot 7). Funny, the update checker didn't say anything that there was an update. I'll have to do some more testing, see if it's in the snapshot 8 version.

**Comment by brandon3055** [comment]
What version are you using? Im guessing by snapshot 7 you mean 1.0.2-Snapshot 7 but if your somehow still back in 1.0.1-Snapshot 7 then updating may fix it. The last change i made to the core that could effect this was in 1.0.2-Snapshot 1. 

Regarding "Visual" freezing the only thing i can think of that may cause this is if the RF/t input/output was very low. The display only updates when the energy stored changes by 1000RF or more.

**Comment by chaNcharge** [comment]
I am using 1.0.2 snapshot 8 and I can confirm that the bug is still in this version. Although this time, I was just getting free energy and reloading the world does not help resolve the issue. The number is stuck at 2,897,433,323 RF and it's input is about 13kRF/t constantly.

**Comment by brandon3055** [comment]
are you playing in singleplayer or on a server?

**Comment by chaNcharge** [comment]
@brandon3055 Singleplayer

**Comment by chaNcharge** [comment]
So after extensive testing, I seem to have found a pattern. At 13k RF/t, at around 3-5 billion RF and 7-8 billion RF stored, the display HUD freezes and only updates at around every 10 million RF, then freezes again.

**Comment by brandon3055** [comment]
So i still wasnt able to reproduce this perhaps because i didnt have the patience to watch it charge at 13KRF/t for hours. But i changed the way it updates the data client side which *should* hopefully fix it. So let me know if you still see this issue after the next release.

**Comment by chaNcharge** [comment]
Ok since the beta came out, I tried to see if the bug was fixed, but now the HUD has disappeared, so I can't tell if it was fixed or not. When you right click the energy core however, it works just fine I believe.

**Comment by brandon3055** [comment]
Umm... the hud has disappeared? Well thats interesting... It should be on my default but check the hud config to make sure (Accessible via the tool config gui)

**Comment by chaNcharge** [comment]
It just says Toggle Hidden, but when I click on it, nothing happens. I have OptiFine installed, maybe that's the issue?

**Comment by brandon3055** [comment]
This is what the gui is supposed to look like
http://puu.sh/njbat/33d0eaa27b.png
pressing the "Toggle Hidden" button should make the "HUD Display" ether appear or disappear.
When hidden you should still see the purple square that allows you to move the display.

**Comment by chaNcharge** [comment]
So here's the issue, the HUD doesn't even show at all, even in the config. http://prntscr.com/a76e42

**Comment by brandon3055** [comment]
Ok so looks like one of your other mods is breaking the hud... It could be optifine or it could be one of the other mods that make changes to the UI such as your minimap mod or whatever mod is increasing the size of the hotbar. Could you try removing those mods and figure out if one of those mods is the cause? That will give me a place to start when trying to figure this out.

**Comment by chaNcharge** [comment]
So I've narrowed it down to Dual Hotbar, or Ars Magica 2. I'm not sure which one is the real culprit (I haven't finished yet, I had to go do something else) But at least it's a place to start. I'll edit this later when I finish testing

**Comment by chaNcharge** [comment]
After removing Dual Hotbar, the GUI renders just fine, and I noticed that the issue involving the Energy Core display no longer freezes. Hopefully you can get the GUI compatible with Dual Hotbar!

**Comment by brandon3055** [comment]
This should be fixed in the next release.
