### ISSUE TITLE
Add energy-bar for half-charged draconium blocks

### ISSUE THREAD

**Issue by athre0z** [brandon3055/Draconic-Evolution#20]
I would really appreciate if there was an energy-bar for half-charged draconium blocks. On our server we have a wireless charger and it took me a good while to figure out why my draconium suddenly refused to stack and where all of our energy went.. :grin: With an energy-bar (or at least some kind of progress display in the tooltip this would have been a lot easier to figure out. Also, this is probably also pretty useful on it's own.

**Comment by brandon3055** [comment]
I plan to do that i just haven't gotten around to it yet.

**Comment by brandon3055** [comment]
I plan to do that i just haven't gotten around to it yet.

**Comment by athre0z** [comment]
Wonderful, thanks for the fast response!

**Comment by brandon3055** [comment]
Note to self: dont double click the comment button.
