### ISSUE TITLE
[Cosmetic]

### ISSUE THREAD

**Issue by Conmyster** [brandon3055/Draconic-Evolution#200]
Hello,

I was wondering if you could remove the either remove the enchanting effect for the Wyvern & Draconic armour or fix it so it does not flash constantly. 

Below you can see an image:
![draconic armour](https://cloud.githubusercontent.com/assets/5269015/11811412/3a5e4b50-a32d-11e5-8e5d-61848f5d7213.png)

It doesn't come of too well in the image, but instead of being a constant enchanted colour it flashes. Which is quite annoying and also makes it look much worse. 

Thanks,
Conmyster

**Comment by brandon3055** [comment]
This is something i am aware of and will be removed in the next update (there is really no way i can find to fix it)
