### ISSUE TITLE
[Request] Allow configuration of potion effects given by Dezil's Marshmallow

### ISSUE THREAD

**Issue by PrincessRTFM** [brandon3055/Draconic-Evolution#201]
I generally play with equipment that increases my move speed and jump height, and that makes the Speed V and Jump Boost V rather annoying. I'd appreciate if there were a config option to at least disable those two, although I'd rather have something to control what effects are given. Maybe a string array option, where each value is in the form of `id[:level` such that level can be left out and will default to 0?

**Comment by GreatOrator** [comment]
That is a special item that is creative only and was made as a gift for a specific player.  Not intended for regular use.

**Comment by PrincessRTFM** [comment]
Fair enough, but "creative only"? I've found it in dungeon chests, is that intended?

**Comment by GreatOrator** [comment]
Sounds like a mod is adding it to loot tables, what pack are you playing?

**Comment by PrincessRTFM** [comment]
Uh... I made my own, and it has 244 mods, so I have *no idea* what's doing it.

**Comment by brandon3055** [comment]
I have heard of this happening before but there are only two ways i can think of that it could happen.

1. An item id mix up. This could happen if you removed a mod that added dungeon loot then when you added draconic evolution the marshmallow may have been assigned the id of an item that still exists in some previously generated dungeons.
 
2. Some mod is just randomly picking items from the item registry and adding them to dungeon chests.

**Comment by PrincessRTFM** [comment]
Probably the second, it's shown up in newly generated worlds.

**Comment by brandon3055** [comment]
Unfortunately there isnt really much i can do on my end unless you can figure out which mod is adding it.
