### ISSUE TITLE
Armor and weapons do not work.

### ISSUE THREAD

**Issue by shadoskill** [brandon3055/Draconic-Evolution#202]
Video if the issue: http://a.pomf.cat/rideqe.mp4

Basically the armor un equips its self, and the weapons either move to inventory or rapidly act like they are just picked up and become unusable.

**Comment by GreatOrator** [comment]
Video link isn't working, but that sounds like another mod, I suggest some basic troubleshooting of the mods you are using currently.

**Comment by wlhlm** [comment]
The video works for me. I'm unable to reproduce your issue with just Draconic Evolution installed. This sounds like a mod interaction problem. You can try to remove mods one by one and see what causes the problem.

What version of DE are you using? Maybe an update fixes your problem.
