### ISSUE TITLE
Already tesselating!  Particle generator

### ISSUE THREAD

**Issue by ProsperCraft** [brandon3055/Draconic-Evolution#203]
http://pastebin.com/XzQNmUCc

particle generator crashes the client when you have opengl and you run away from it unrendering the block.

Disabling opengl in the video settings stops the crash so you can break the block.

**Comment by wlhlm** [comment]
Does it work when you remove Optifine?

And just to be clear, you mean the "Advanced OpenGL" option? Minecraft renders everything with OpenGL, you can't just disable it.

**Comment by GreatOrator** [comment]
Yeah, I see optifine listed at the bottom, this is a bug with optifine unfortunately.  Usually the result of a mismatch in forge versions

**Comment by Bebabo10** [comment]
You crash with or without optifine.

**Comment by GreatOrator** [comment]
then I need a crash report for this without optifine installed

**Comment by Builderb0y** [comment]
Most optifine-related "already tessellating" errors can be fixed by setting the chunk loading mode to default.

**Comment by brandon3055** [comment]
Looking at the code i dont see any reason for the crash. If it dose crash without optifine please post that crash report and i will investigate further.

**Comment by GreatOrator** [comment]
Closing until we get a crash report without optifine
