### ISSUE TITLE
Regarding Adv. Charm of Dislocation and Fake Players

### ISSUE THREAD

**Issue by Avarai** [brandon3055/Draconic-Evolution#204]
Today I encountered a bug. I accidently placed a enchanced charm of dislocation inside of an autonomous activator (In forge, the autonomous Activator registers as the fake player: CoFH). The activator teleported and reappeared at the set location. At this location was a entity that looked like a player and was named "CoFH" which was holding the charm. Could not hurt it, access its inventory, gravity didnt effect it and at the same time I was invincible too. So we wiped my player data. Upon reloading the world and logging in I was still invincible. Unsure how to fix this. So yeah any thoughts or questions feel free to message me. This was encountered on a forge multiplayer server. Possibly adding a check for fake player use to the charm would solve it but unsure what problems that could cause.

**Comment by GreatOrator** [comment]
Will test that in my pack to see if it happens there as well.  If it does, will look into a fix, if not, may be an issue with another mod.

**Comment by brandon3055** [comment]
@GreatOrator Did you ever manage to reproduce this? Because so far i have not been able to.

**Comment by wlhlm** [comment]
I also cannot reproduce this. The Activator will burn the fuel of the charm and it will make the teleportation sound, but no fake player will appear.

This sounds like some other mod is messing around with it. @Avarai can give a modlist? Also, are you using Forge, or some other incarnation like cauldron?

**Comment by GreatOrator** [comment]
@brandon3055 and @Avarai I have not been able to reproduce this in my pack, I would suggest removing mods one by one until you find the culprit.  Sounds like another mod is not handling or changing fake players improperly.
