### ISSUE TITLE
Populate mcmod.info metadata file

### ISSUE THREAD

**Issue by wlhlm** [brandon3055/Draconic-Evolution#205]
The `mcmod.info` file is shipped with the mod jar and includes metadata for the use for tools. One example is the MultiMC launcher:

![screen shot 2015-12-20 at 10 19 14](https://cloud.githubusercontent.com/assets/1928113/11917330/2bc09696-a703-11e5-8f5a-40483e612563.png)

Unfortunately, [Draconic Evolution's `mcmod.info`](https://github.com/brandon3055/Draconic-Evolution/blob/58a892f6f52d296c79bb2630948f1bae875b6518/src/main/resources/mcmod.info.disabled) is disabled at the moment, and [Brandons Core's file](https://github.com/brandon3055/BrandonsCore/blob/a42bb32a58a412ba43a66f02bf1a1db5868c8162/src/main/resources/mcmod.info) is still from the example project, listing it as "Example Mod" as can be seen in the above screenshot.

**Comment by brandon3055** [comment]
I dont use the mcmod.info instead i specify this information at startup like so https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/DraconicEvolution.java#L52-L60
The reason i do it like this is it means i dont have to update it every time i release a new version. 

And i guess i just completely forgot about that in BrandonsCore.

If i ever get around to figuring out custom build scripts i will fix this.

**Comment by wlhlm** [comment]
> The reason i do it like this is it means i dont have to update it every time i release a new version.

You _don't_ have to update it every time. ForgeGradle takes care of that. You just have to fill in the file _once_. There is substitution for version numbers. The file gets automatically included in your jar with `gradle build`.

Here's an example:

```json
[
{
  "modid": "DraconicEvolution",
  "name": "DraconicEvolution",
  "description": "This is a mod originally made for the Tolkiencraft mod pack",
  "version": "${version}",
  "mcversion": "${mcversion}",
  "url": "http://www.tolkiencraft.com/draconic-evolution/",
  "updateUrl": "",
  "authorList": ["brandon3055"],
  "credits": "",
  "logoFile": "banner.png",
  "screenshots": [],
  "dependencies": []
}
]
```

The Draconic Evolution gradle build script [already includes the necessary parts](https://github.com/brandon3055/Draconic-Evolution/blob/master/build.gradle#L58-L76) to have a `mcmod.info` file automatically included and updated with the correct version infomation.
