### ISSUE TITLE
Localization errors-Snapshot 9

### ISSUE THREAD

**Issue by GreatOrator** [brandon3055/Draconic-Evolution#206]
The localization for warning the players dragon must be summoned in the end does not display, only the unlocalized text in snapshot 9

**Comment by GreatOrator** [comment]
Also nuggets both regular and awakened are not showing localization either,

msg.SpawnDragonMustBeInTheEnd.txt=You must perform this ritual in the End dimension!
item.draconicevolution:nugget.draconium.name=Draconium Nugget
item.draconicevolution:nugget.awakened.name=Awakened Draconium Nugget

**Comment by GreatOrator** [comment]
Pull request with updates made

**Comment by brandon3055** [comment]
Couldn't find your pull request butt added the localization. Thanks!
