### ISSUE TITLE
GUI request 

### ISSUE THREAD

**Issue by fxstriker** [brandon3055/Draconic-Evolution#207]
Not a huge issue but slightly annoying can we have a lock button on the GUI that shows power level range etc so we do not move it when we go to change a settings this is more of a feature request then anything really :)

While on the topic another cool idea would be to have favorite settings on a tool and a hotkey to toggle it so you could press a hotkey and go from
width 1 x 1
depth 1 x 1 
directly to 
width 9 x 9
depth 9 x 9

**Comment by brandon3055** [comment]
I am planning to add presets to the tool config which you can configure and then switch between with a hotkey i just haven't gotten around to it yet.
