### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by DeathRebiRtH** [brandon3055/Draconic-Evolution#209]
When attempting to remove books from my Sword of the wyvern by hovering over a book in the tool GUI, and pressing the hotkey that the sword/item is in, it will move the sword to another slot in my inventory (hotbar full) but keep the GUI open, it will allow to remove the rest of the enchanted books the same way by pressing the hotkey, without them being removed from the sword.

Edit: Just in case, I am running the FTB Infinity modpack V. 2.3.3 on a locally hosted server.
 Draconic Evolution version : "1.7.10-1.0.2-Snapshot_9"

**Comment by GreatOrator** [comment]
Can you provide a short video or screen shots to show what it is you are describing?

**Comment by DeathRebiRtH** [comment]
Hopefully this makes sense. https://youtu.be/ozlje3OVMLA

When removing the books I press the key for the slot the sword is in. So 1,2,3,4 as I remove the books. As you can see the books end up in my inventory but aren't removed from the sword.

**Comment by GreatOrator** [comment]
What mod does the inventory modification?  My best guess is that's the culprit.  Can you try loading up with that mod disabled and see what happens?

**Comment by DeathRebiRtH** [comment]
I just tried it with 1.7.10 Forge Version 10.13.4.1558 with only BrandonsCore 1.0.0.10-bugfix and Draconic Evolution 1.0.2-Snapshot_9 and nothing else and it is still possible.

**Comment by brandon3055** [comment]
Thanks for letting me know about this. I have successfully recreated the issue and will attempt to fix it.
