### ISSUE TITLE
enderman head and draconic chest

### ISSUE THREAD

**Issue by flashamm** [brandon3055/Draconic-Evolution#21]
Accidentally right clicked my draconic chest with a tinkers tweaks enderman skull and it erased my chest with everything in it. I am using Draconic Evolution v1.0.1_snapshot 3 and tinkers tweaks v2.1.2. Both for 1.7.10. We are using the Flashcraft modpack through Technic Launcher

**Comment by brandon3055** [comment]
Hmm... I cant emagin that being a problem with DE... Can you try recreating it in single player and see if it produces an error in the log?
