### ISSUE TITLE
Draconic Chest bug

### ISSUE THREAD

**Issue by UNK1LL4BL3** [brandon3055/Draconic-Evolution#210]
Hey the draconic chest has been acting up recently, it will randomly wipe its own inventory into oblivion which is rather disheartening.

**Comment by GreatOrator** [comment]
Version/mod list with it?

Would have to be able to reproduce the error to be able to fix it.  What were/are you doing prior to the wipe, etc.

**Comment by UNK1LL4BL3** [comment]
The version is FTB Infinity Evolved. I don't know if this was supposed to be a part of the chest function, but I noticed that when mined up it keeps its inventory, so I always kept a chest on me when I went mining or while exploring the twilight etc. I can't say whether this is a factor but all the chests were half or more full when the incident happened, I just happened to place the chest and when I looked inside all the loot was gone. On a similar note I also had a chest back in my base of operations that stayed there and it wiped its inventory as well, similarily it was half or more full.

**Comment by brandon3055** [comment]
This was reported a while back in issue #88 That turned out to be an issue with the server running low on ram. Basically it the server (or client if singleplayer) is at or very close to 100% ram utilization when you break the chest the contents can not be saved and are deleted.

**Comment by UNK1LL4BL3** [comment]
Hmm, as stated above it also happened to chests that weren't mined up so does that mean that if the ram is full, whether mined up or placed and left the inventory somehow gets saved and if ram is to low than it becomes impossible?

**Comment by brandon3055** [comment]
Hmm... Im not so sure about that one because that data should be written to disk where it should be safe...
