### ISSUE TITLE
Smart Moving Compatible

### ISSUE THREAD

**Issue by Horneat** [brandon3055/Draconic-Evolution#211]
Hey that is not realy a issue i just wanne ask if you can add smart moving Compatibelety

**Comment by brandon3055** [comment]
I will add it to my list but not sure when i will get to it.

**Comment by Horneat** [comment]
okey thanks

**Comment by jakbruce2012** [comment]
Not only is it smart moving compatible, but 1.0.2 includes smart moving.  Is there a way to remove it now?
