### ISSUE TITLE
Wrath enchantment not working on sword of the wyvern.

### ISSUE THREAD

**Issue by JadeDrgn** [brandon3055/Draconic-Evolution#213]
Forbidden Magic adds this enchantment, it works just like sharpness does but stacks with sharpness. I was trying to get both wrath and sharpness on but found out wrath isn't effecting the sword at all. 

Here's some screens showing it's effect on a normal iron sword, then me having the wyvern sword with just sharpness, then sharpness and wrath.

http://imgur.com/a/RFCwF

**Comment by brandon3055** [comment]
The swords use custom damage code which is not effected by most enchants. I had to manually add support for all the vanilla enchants.
