### ISSUE TITLE
energy storage core bug

### ISSUE THREAD

**Issue by estorio** [brandon3055/Draconic-Evolution#214]
i found a bug where when you first made a tier x core (x=the core you want above 1) and then remove everything except the energy core, then you put the particle generator directly near the core, the particle generator will vanish and the core will have still have tier x. 
Right now i'm uploading a video on youtube with german instructions how it works.
I hope this gets fixed.
~Estorio

**Comment by brandon3055** [comment]
Go back and try to do this with your game-mode set to survival. It looks like a little glitch in the creative activation code meaning it only works if you activate the core in creative mode. 

And although it was not indented i like the idea of being able to creatively make a core without stabilizers so i will be leaving this bug in as a creative feature.
