### ISSUE TITLE
Set Multishot(CoFHCore) in Draconic Bow, but not applied the enchant effect.

### ISSUE THREAD

**Issue by karakufire** [brandon3055/Draconic-Evolution#216]
As title, the enchant 'Multishot' effect is some arrows launching at once, but I can't see that effect with draconic bow.

**Comment by estorio** [comment]
I tried it with the draconic bow and wyvern bow and the same happened to me. Maybe it happens because the bow has different shooting modes?

**Comment by brandon3055** [comment]
I suspect this is just because there are a lot of differences between my bows and more vanilla type bows. But my bows will hopefully be getting an upgrade before the next release that should make up for this.
