### ISSUE TITLE
energy net question

### ISSUE THREAD

**Issue by TheTruth77** [brandon3055/Draconic-Evolution#218]
Can someone please tell me how the heck to connect a energy transceiver to a de block that requires power i can seem to figure it out (i cant install te the cofh core not responds at the mojag screen every time) i realy need the help please.

**Comment by brandon3055** [comment]
Place an energy transceiver on the device supplying the power. Shift right click your crystal binder untill the function is set to "Mode Change" then right click the transceiver to set it to input mode. You should now see the transceivers internal buffer filling,

Place another transceiver on the target device and set it to output mode. Then link the two tranceivers with the binder set to the bind function. 

Look at the following pages in the information tablet for more information.
http://puu.sh/mxnmB/a471512402.png
