### ISSUE TITLE
Ability to add to OreDoublingRegistry

### ISSUE THREAD

**Issue by MikeLydeamore** [brandon3055/Draconic-Evolution#22]
It would be very much appreciated if there was some way to interface with the OreDoublingRegistry, outside of registering to the OreDictionary.

In Ex Nihilo/Astris, the broken ores are (deliberately) not added to the ore dictionary, but this means that the Draconic Chest won't double them, even though it probably should.

My suggestion would be to use a List that stores an input, and then call FurnaceRegistry to get the output, then double it.

**Comment by brandon3055** [comment]
Do you mean add a list to OreDoublingRegistry that stores additional items to be doubled so that other mods can add things to that list? If so that shouldn't be a problem. I could probably also add a way to register new items to be doubled using inter mod communications. I just have to learn how to use it.

**Comment by MikeLydeamore** [comment]
That's exactly what I'm referring to. An IMC would be great actually.

**Comment by brandon3055** [comment]
Ok i will get that up and running asap.

**Comment by brandon3055** [comment]
Done! 
Here is an example of how to add a recipe:
FMLInterModComms.sendMessage("DraconicEvolution", "addChestRecipe:item.coal", new ItemStack(Items.diamond, 2));

-addChestRecipe:(unlocalized name of the input item)
-The result ItemStack (the result stack size can be any number you want from 1 to 64)

And here is a build with the changes for testing: http://puu.sh/goajW/bc5248fbe2.jar
Also pushed the changes to github

**Comment by MikeLydeamore** [comment]
I was too slow to download this, are you able to re-up?

**Comment by brandon3055** [comment]
Here you go.
http://puu.sh/gx7D8/314586b4d0.jar
