### ISSUE TITLE
Staff of Power fails to dig grass when it has plants on it.

### ISSUE THREAD

**Issue by Tesserex** [brandon3055/Draconic-Evolution#225]
This only happened to me when my staff was set to a max area of 9x9x9, and I haven't tested any other sizes or tools so far.

When I try digging down on some grass, any grass blocks that have plants on them like flowers or tall grass won't get broken on the server. They will appear to break on the client, but then you will be out of sync and get clipping resets. I had to re login to sync up again. For now I'm doing mowing before I dig.

**Comment by brandon3055** [comment]
I was not able to reproduce this error. My guess is ether some weird interaction with another mod or a one off glitch.

Pro tip: Simply right clicking any of my tools will update any ghost blocks around you so you dont have to relog.
