### ISSUE TITLE
Reactor-Energy Injector

### ISSUE THREAD

**Issue by apdjz** [brandon3055/Draconic-Evolution#226]
It doesnt seem to be accepting energy from any forms of pipes that can transfer  rf

**Comment by SliderHavoc** [comment]
You closed this with no replies, I am just curious as to if you ever found out a solution. I have the same problem with the rest of the set up working fine.

**Comment by apdjz** [comment]
Unfortunately I am no longer playing mc. If I remember correctly the solution was breaking the core, which caused a block update
