### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bookerthegeek** [brandon3055/Draconic-Evolution#228]
I understand that Yes, void/chaos damage will damage a player in creative mode. This request is not asking you to fix this. (altho it is stupid for it to kill creative players imho)

And yes, I've read the repo... As such I've already looked at; https://github.com/brandon3055/Draconic-Evolution/issues/191, https://github.com/brandon3055/Draconic-Evolution/issues/175 & https://github.com/brandon3055/Draconic-Evolution/issues/209

What I am asking for is for the chaos dragon to ignore players in creative and/or opped and/or in vanish on a server. This is purely so that admins on a server can perform their duty without having to /kill the dragon, and then spawn one in.

**Comment by brandon3055** [comment]
Ok then in the next version the chaos guardian will not attack creative players... Unless they piss it off.

**Comment by luckyp3616** [comment]
How about not using void damage?
