### ISSUE TITLE
chaos crystal (heart of the dragon layers or idk)

### ISSUE THREAD

**Issue by minecrafterseppe** [brandon3055/Draconic-Evolution#229]
# at the center of the chaos dragon its island is somting called ''chaos crystal" it seems like a block and waila says i can break it with my draconic wand of power  but i have been mining it for like 10 minutes stil not broken and i saw that u where an encoder i  would love some more info btw i killed the dragon all the crystals i just dont know what to do now pls help

**Comment by brandon3055** [comment]
I was recently made aware of an issue which makes it impossible to mine the crystal if you are using AOE mode. I will investigate this issue but for now just switch your staff to 1x1 mode.
