### ISSUE TITLE
Flux Gates in series picking wrong rate

### ISSUE THREAD

**Issue by Ipiano** [brandon3055/Draconic-Evolution#231]
See the two pictures attached for context. Basically, I'm trying to set up a program using computercraft to automatically regulate a reactor. Originally, I had one fluxduct line heading away from site, and it was used for energy input and output from energy storage, but the output from the reactor, and the input to the field generator were both regulated.

What I noticed, is that even though the output from the reactor was regulated to 5k RF, it was being drained MUCH faster, (I think) because I was regulating the field generator to 100K (just for testing purposes)

When I split the input/output to go through the energy storage, I stopped seeing this.

![2016-02-05_23 00 49](https://cloud.githubusercontent.com/assets/5333611/12864991/9a1957da-cc5c-11e5-90a2-5fc5eef3121f.png)
![2016-02-05_23 01 00](https://cloud.githubusercontent.com/assets/5333611/12864990/9a1729d8-cc5c-11e5-962b-43d0cfe73878.png)

**Comment by brandon3055** [comment]
Hmm thats a bit odd... The only thing i can think of is that maby the conduit is extracting from the gate twice per tick. once to send to the core and once to send to storage. In any case i would recommend your second setup over the first. Its kinda tricky to both send and receive energy via a single conduit.

**Comment by Ipiano** [comment]
I figured you might say that, but I also wanted to make you aware of it just in case it's something that's a major issue. Thanks!
