### ISSUE TITLE
Lot of trouble with the chaos guardian !

### ISSUE THREAD

**Issue by Mhawon** [brandon3055/Draconic-Evolution#232]
We playing on this version : 1.7.10-1.0.2-Snapshot_9 (MP)

I have tried to kill this chaos guardian and i have got lot of issues like older issues:
- Some crystal still heal the dragon when they are at 0/50 (i tried to unload/reload the chunck and no changes)
- No dragon heart was dropped (but the draconium ore was dropped)
- No Draconium ore/hive/lily seed was generated on the island
- And on the middle of this island, no crystal shard. (Just wither proof obsidian but no crystal shard)

I tried to kill an other one : 
- The chaos crystal appear :+1: 
- Thechoas guardian send like 10k red bullet per tick, no way to kill him

**Comment by GreatOrator** [comment]
I can assure you that it works, http://www.twitch.tv/soaryn/v/38495667 soaryn did it in under 10 minutes

**Comment by GreatOrator** [comment]
the heart will drop, just be careful it is over land or you have some kind of item magnet, the ore, etc is not intended to generate on the island, the shard is the only possible issue.
