### ISSUE TITLE
One new Bow mode

### ISSUE THREAD

**Issue by Fortist** [brandon3055/Draconic-Evolution#234]
"Normal" mode.
Sharpshooter zooms in way too much, explosive is explosive, and rapid doesnt allow for holding a draw.
Plus Im using the beta/first release of this mod "Bow Overhaul" which changes and adds a few things to all bows, including headshots, drawing mechanics, and arrow mechanics.

**Comment by brandon3055** [comment]
I will be making changes to the bow soon and may add the option to configure the "zoom" effect. explosive is supposed to be explosive... and rapid fire is supposed to be... rapid fire...

In an upcoming version i will be doing an overhaul of my own in which i will be making the bows very configurable.

**Comment by Fortist** [comment]
I know that they are explosive and rapid fire, hence why I said a need for "Normal" mode.
Since that one isnt explosive, nor rapid. And doesnt zoom.

But, good to hear.

**Comment by brandon3055** [comment]
Ahh i get what you were saying now. I wasnt sure what you meant by "Normal Mode"
