### ISSUE TITLE
[Question] Why Snapshot_9's armor model has been back before Snapshot_3?

### ISSUE THREAD

**Issue by karakufire** [brandon3055/Draconic-Evolution#235]
Look these image.
![Snapshot_8](http://i.imgur.com/q9OU29z.png)
In snapshot 8 models.  
![Snapshot_9](http://i.imgur.com/f39qJcX.png)
In snapshot 9 models.
why turn back these model?

**Comment by brandon3055** [comment]
I didn't. I did however add a config option to re enable those models for the few people who liked them better. Check that you dont for some reason have that option enabled.

**Comment by karakufire** [comment]
when I regenerate DraconicEvolution.cfg, these models turn back into new 3D model.
Maybe B:"Use the original 3D armor models" works?

**Comment by brandon3055** [comment]
"Use the original 3D armor models" is the setting that enables the older 3D models

**Comment by karakufire** [comment]
I got it. thank you.
