### ISSUE TITLE
Tinker Construct - Large Blade Pattern

### ISSUE THREAD

**Issue by Syclone81** [brandon3055/Draconic-Evolution#237]
How to grade the Large Blade in Draconium and Awaked Draconium? I can not found any discription or anything about this. How can i make this, can u add a wiki or some other documentations, where we can see "how to work with Thinkers in Drac Evo" ?

**Comment by Bennyboy1695** [comment]
Those items are added by ExtraTiC not Draconic Evolution, You'll need to ask the author of that mod instead.

**Comment by shadoxxhd** [comment]
for draconium you need wyvern cores, for awakened draconium you need awakened cores. just put the large blade pattern and 8 cores of the material you want in the part builder and you're good to go

**Comment by Syclone81** [comment]
ok thanks is see it a wile later ... thats the mod is ExtraTic ;) but thanks for ur answer
