### ISSUE TITLE
Unnamed?

### ISSUE THREAD

**Issue by cj89898** [brandon3055/Draconic-Evolution#240]
Why are some of the tools unnamed for me? I can never figure out why. This is every time I use the mod.

**Comment by wlhlm** [comment]
This sounds similar to #178. Did you encounter any crashes? Maybe a Botania update helps.

**Comment by cj89898** [comment]
No crashes, and my friend runs the same modpacks I do and they work fine for him.

**Comment by brandon3055** [comment]
What do you have the config gui hotkey bound to? If its bound to something other then a keyboard key such as a mouse button you will get this issue. And under certain circumstances it will crash your client.

**Comment by cj89898** [comment]
Oh... I have it bound to a button on my mouse. It used to crash me on my old PC. Is there any way to fix it?

**Comment by brandon3055** [comment]
The crash and "Unnamed" issue will be fixed in the next version but it still acts buggy when you bind those buttons to your mouse.

**Comment by cj89898** [comment]
Great! I hope the pack I'm playing will update! lol
