### ISSUE TITLE
[Suggestion] Uncharging Draconium Blocks

### ISSUE THREAD

**Issue by Awsumonium** [brandon3055/Draconic-Evolution#241]
Dear developer of DE,

A feature where I could uncharge my draconium blocks which are accedently charged? my flux capacitor was on hotbar mode, so a full stack of draconium blocks got 1% charged, rendering them borderline useless. I already tried the enervation dynamo from Thermal Expansion, but it didn't accept the draconium blocks.
The way i have to uncharge them now is by iniciating and canceling the dragon resurrection ritual so the fully charged blocks come out as normal ones, but that means I have to waste 10m RF per block.

(sorry for any grammer mistakes english isn't my native language)

I hope there's something you can do about this problem ;)

Kind regards,

A fellow minecrafter

**Comment by brandon3055** [comment]
If they are only partially charged then you can discharge them by simply placing them and breaking them.

**Comment by GreatOrator** [comment]
This request has been moved to http://www.brandon3055.com/suggestions/
