### ISSUE TITLE
Chaos Guardian unkillable on servers

### ISSUE THREAD

**Issue by Antillar** [brandon3055/Draconic-Evolution#242]
While in unloaded chunks, killed crystals still heal the dragon. It is not a problem in a singleplayer, where you can pop a chunkloader or just set render distance to far to keep all the crystals loaded. But it is an issue on multiplayer. 

On our server we have only 5x5 chunks sent to player. So every crystal farther than 48 blocks from the player is in unloaded chunk, and counted active, and heals the dragon. And, you know, dragon is moving very fast, so it reaches unloaded chunks in no time, where it gets healed.

What I suggest is totally removing the crystals once they are "dead", because now they present even with 0/50 HP, and still function in unloaded chunks. If they were removed as entity, it would solve the problem.

PS. Adding chunk loaders is not an option, all normal servers have them banned completely either only purchasable for donation, because these machines lag out the server much.

**Comment by brandon3055** [comment]
What version of DE are you using?

**Comment by Ipiano** [comment]
I'm currently running a server out of my dorm, and was able to get the Guardian down to like 10% health without experiencing this. Haven't gotten him lower because of how crazy his attack gets after that :P

**Comment by brandon3055** [comment]
I made some changes in snapshot 9 which "Hopefully" fixed a lot of those issues.

**Comment by Antillar** [comment]
Version 1.0.2-Snapshot_9 (FTB Infinity)

**Comment by brandon3055** [comment]
Ok i will look into it... again......

**Comment by Antillar** [comment]
If you want, I can film my countless attempts to beat it.

**Comment by brandon3055** [comment]
I think i figured it out (Was not hard to reproduce just turned my render distance down) And i think i have it fixed.

**Comment by Antillar** [comment]
When are you going to release it? My mission ends here, when you release the new snapshot. And I will go annoy FTB devs XD

**Comment by brandon3055** [comment]
This is going to be a big update and the first release will be a beta (Meaning FTB wont use it because its potentially so unstable) But it shouldn't take to long to get the bugs worked out.
