### ISSUE TITLE
Draconic armor don't remove mining slowdown with AetherII mod

### ISSUE THREAD

**Issue by ArthixFR** [brandon3055/Draconic-Evolution#243]
Hi,

I've a server running FeedTheBeast Infinity Evolved 2.3.5 with AetherII. I think there is a conflict with the Aether mod because the mining slowdown when you fly or you are underwater is still present with the draconic armor. Do you think it comes from the Aether mod or this mod ?

Using DraconicEvolution **1.0.2 snapshot 9** and AetherII **1.7.10-1.6**

**Comment by brandon3055** [comment]
I cant see how that could be an issue on my end... The only thing i can think of that could cause that is if another mod is resetting the break speed for some reason. I will try delaying the event when i make that adjustment so hopefully i can adjust it after whatever mod is resetting it but if that dose not work i dont think there is much else i can do.
