### ISSUE TITLE
"Draconium Infused Obsidian" Dupe Bug

### ISSUE THREAD

**Issue by unpure** [brandon3055/Draconic-Evolution#244]
Hey there.
I created a small hollow room (5x5x3) out of Draconium Infused Obsidian.
Inside of it enough space to create a wither (3x3x1).
Everytime the wither shoots at the Draconium Infused Obsidian, it seems to dupe them.
Picked up 3 Stacks of dropped obsidian after killing him.

I dont know if it is a bug from DE or a mod incompatibility, but here is a list of used mods:
http://upclan.de/modpack/info/

Sorry for my bad english, i hope its not to hard to understand.

**Comment by Ipiano** [comment]
If you're seeing the same thing I saw, this only occurs in creative mode, not survival.

**Comment by Aquadin** [comment]
I found the same dupe bug yesterday. I use the FTB Infinity Evolved modpack with the addition of iguana tweaks.
The Wither seems to break the blocks which are then replaced immediately. He was also able to destroy blocks around the enclosure.

**Comment by brandon3055** [comment]
I actually just discovered this myself yesterday. I also discovered it on Infinity Evolved but it must be some weird mod interaction because it dose not do it in my test world. This should be fixed in the next release.
