### ISSUE TITLE
[Energy Core] Energy dissapeared

### ISSUE THREAD

**Issue by Sheldor5** [brandon3055/Draconic-Evolution#245]
Today I built my own Tier 7 Energy Core on our FTB Infinity Evolved Server (2.3.5) and placed a tesseract under one of the Energy Pylons and "accidentally" configured an already used frequency from another Tier 4 Energy Core meaning that the Energy from the T4 instantly flow to my new T7.

I thought OK just change the Send/Receive directions to put the Energy back to the T4 but ... both are empty now (lost 9B RF).

The Energy Cores are about 12 chunks apart.

**NO, there is no other thing on the tesseract's frequency!**

**Comment by Sheldor5** [comment]
Server restart fixed it.

**Comment by brandon3055** [comment]
Well thats good to hear. I wasn't looking forward to debugging that one. But my initial guess was some sort of chunk loading error.
