### ISSUE TITLE
I'm bored fighting the Chaos Guardian

### ISSUE THREAD

**Issue by Leasara** [brandon3055/Draconic-Evolution#246]
I have gotten bored of fighting the Chaos Guardian.  Suprised myself when I realized I had been at it for the last 8 hours (quite literally) and I've only managed to get the thing down to 5% health or thereabouts a couple of times.  After the first hour I was really into it, had this whole Hemingway style Old Woman and the Sea thing going on, but after hour 3 I was just angry, and now I'm bored.   I'm not getting the healing-outside-of-render-distance thing, My problem seems to be that the dragon itself keeps disappearing if it's more than 30 blocks from the player.  I expect that this is more to do with Spigot than with Draconic Evolution, but our server's owner (a YouTuber called Biffa2001) likes his Core Protect, so we have to deal with Spigot.
I'd love to see some config options to adjust the difficulty of the Chaos Guardian fight, maybe cap the number of times the healing crystals can be regenerated, turn off the teleportation attack, that sort of thing.  Baring that, maybe a system where guiding the Guardian's attack into its healing crystals destroys the crystal or bouncing the fireballs back at the dragon does a bunch of damage.  Really, just something to make it possible on our poor little server.

**Comment by brandon3055** [comment]
Very well the next version will have a config option to disable the guardians ability to respawn the crystals. This should make it very easy to finish him off.
