### ISSUE TITLE
Flux Capacitor drains super fast

### ISSUE THREAD

**Issue by cj89898** [brandon3055/Draconic-Evolution#248]
My flux capacitors keeps draining super fast when I have my Wireless Terminal from AE2 in my hotbar. I'm not sure who's fault this is, but because of it I can't use my flux capacitors. It does not charged the Wireless Terminal at all.

Edit: The Energy Infuser also does not charge the Wireless Terminal

**Comment by brandon3055** [comment]
That can really only be an issue with the AE2 item

**Comment by GreatOrator** [comment]
I just tested, it does charge just fine (and extremely fast mind you) if it is not working it is another mod interfering with the function or some server configuration.

p.s. had to try it several times because it happened so fast I thought the crafting recipe was wrong
