### ISSUE TITLE
client dimensions bug

### ISSUE THREAD

**Issue by timmmmeh** [brandon3055/Draconic-Evolution#249]
Depending on what your client dimensions are you will not be able to see the far left and right inventory spots in your Draconic chest.
Windowed: http://puu.sh/nh28h/2445b73539.png
full screen: http://puu.sh/nh290/8358c2c30c.png

**Comment by brandon3055** [comment]
There isnt really much that can be done about this. You will find that most mods that add massively over sized inventory screens like this will have the same issue. Its a limitation of minecrafts base gui code.
