### ISSUE TITLE
[Informative] Some TE's with no updateEntity override

### ISSUE THREAD

**Issue by spannerman79** [brandon3055/Draconic-Evolution#253]
Server: KCauldron (using my own build forked from build 152 of KCauldron)

[Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar](http://minecraft.curseforge.com/projects/draconic-evolution/files/2271371)
[BrandonsCore-1.0.0.10-bugfix.jar](http://minecraft.curseforge.com/projects/brandons-core/files/2268437)

````
com.brandon3055.draconicevolution.common.tileentities.TileParticleGenerator with canUpdate set to true and no updateEntity override!. Please report to mod author as this can hurt performance
com.brandon3055.draconicevolution.common.tileentities.multiblocktiles.TileInvisibleMultiblock with canUpdate set to true and no updateEntity override!. Please report to mod author as this can hurt performance.
````
Is this intended behavior or something that needs to be addressed?

**Comment by brandon3055** [comment]
Hmm... Its a very minor thing but i guess it couldn't hurt do disable updating for those blocks. This would be more of an issue if the blocks in question were used for something like decoration where you can have a lot of them.

**Comment by brandon3055** [comment]
Hmm... Its a very minor thing but i guess it couldn't hurt do disable updating for those blocks. This would be more of an issue if the blocks in question were used for something like decoration where you can have a lot of them.

**Comment by brandon3055** [comment]
Hmm... Its a very minor thing but i guess it couldn't hurt do disable updating for those blocks. This would be more of an issue if the blocks in question were used for something like decoration where you can have a lot of them.

**Comment by spannerman79** [comment]
Thank you and I knew it was minor - hence the tag of this issue.

I don't use the Particle Generator or the Energy Storage Multiblock as decoration. Besides you know the number of resources that are required in creating one of those yourself :stuck_out_tongue_winking_eye:
