### ISSUE TITLE
Draconic armor - faster slowing movement during flight.

### ISSUE THREAD

**Issue by VerisZG** [brandon3055/Draconic-Evolution#256]
Hey, please consider disabling inertia during flight. I'm using the armor to construct mid-flight and find the inertia not allowing me to build effective. I would love to have an option to adjust or disable inertia completely. What i mean is i would like to stop immediately when i stop moving.

**Comment by brandon3055** [comment]
Inertia is added by vanilla minecraft and trying to counteract it without introducing lots of bugginess when moving may be rather tricky but i will give it a try. Have you considered just reducing your flight speed while building?

**Comment by VerisZG** [comment]
Thank you! Yes, it has that option working. Perfect! :+1:
