### ISSUE TITLE
Chaoz Guardian attacks creative players and KILLS them!

### ISSUE THREAD

**Issue by BlazingGamer** [brandon3055/Draconic-Evolution#257]
![2016-03-01_20 05 09](https://cloud.githubusercontent.com/assets/13196222/13432914/a7c4bdc4-dfe0-11e5-9d41-5f9c1412130f.png)
Draconic Evolution 1.0.2 s.9.

**Comment by GreatOrator** [comment]
Yes, been mentioned and is going to be fixed, please remember to search both open and closed issues before posting.  thank you.

**Comment by brandon3055** [comment]
Changelog:

> ######## 1.0.2-Snapshot 10-beta ########
> -fixed hover text for stats in the reactor gui showing when the stats page is closed.
> -beacons can now pass through energy core.
> -fixed bug in old 2D armor models.
> -fixed Draconic helm night vision checking light value at your feet resulting wierd behavior like activating when walking on soul sand.
> -fixed rounding issue with energy core display so it will show decimals like 23.5M / 1.64B instead of just 23M / 1B.
> -fixed a dupe bug in the tool inventory gui
> **-chaos guardian will nolonger attack creative players unless they do something to piss him off.**
> -added a better config gui for the HUD (Still accessible via the tool config gui)
> -completely re-wrote the armor and added a shield mechanic instead of the old "Just block ALL the damage" mechanic.
> -added an upgrade system for the tools and armor.  
> -change: If you logout while flying you will be flying when you login again.
> -added tool config profiles.
> -fixed chaos guardian crystals in unloaded chunks showing as alive then they are not.
> -updated documentation.

**Comment by BlazingGamer** [comment]
Thanks!
