### ISSUE TITLE
Decorative Chaos Crystal?

### ISSUE THREAD

**Issue by SupernovaCo** [brandon3055/Draconic-Evolution#259]
Would it be possible to add a decorative 'Stable Chaos Crystal', either creative-only or craftable using Chaos Shards, for aesthetic purposes? I love how the crystal looks and sounds, and the fact that you cannot place them in creative for decoration purposes has been driving me a little nuts, since I have a really neat base build in mind using them. If this is possible, please have the decorative ones produce the cool sound that normal ones make too.

**Comment by SupernovaCo** [comment]
I mean the one that spawns in the center of Chaos Islands, which you mine after killing the Chaos Guardian, not the Endercrystal-like things.

**Comment by brandon3055** [comment]
There is already a way to spawn them creatively but remember they will still go boom if you break them.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2093099-draconic-evolution-1-0-2-snapshot-10?comment=925
