### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by Shadow232** [brandon3055/Draconic-Evolution#26]
Crash log:
http://pastebin.com/7fyE3cFF

Forge - 1.7.10 latest ( 1291 )
Mod version - latest ( snapshot 6 )

**Comment by brandon3055** [comment]
Thanks. I just have one question... How and why are you using an untested beta that has not been publically released? I can only assume you got it from #22 Pro tip when a modder gives another modder a test build. It may not be 100% stable.

**Comment by Shadow232** [comment]
Compiling sources so, why? I and my friends want to help with making perfect mod and play for fun, because all versions have bugs :C

**Comment by Shadow232** [comment]
Fixed, you may close it :)

**Comment by brandon3055** [comment]
Yea i just fixed it :)
