### ISSUE TITLE
Computercraft API Documentation

### ISSUE THREAD

**Issue by BlackTigers** [brandon3055/Draconic-Evolution#260]
Hey brandon3055,

I personally love your work on Draconic Evolution since it's a really great mod, but I would really, really appreciate that there was a Computercraft API Documentation for the Reactor, the Energy core and the Fluxducts as well as a possibility to connect the reactor via networking (I know it's a lot work to do so but it would be really nice). What about the Documentation of the API? It's not that difficult to do such a Documentation but it would safe many people a lot of work since (after 2 hours testing) I still didn't figure out how setOverrideEnabled (I have no clue what this guy does) and setFlowOverride (same) do.

Thank you a lot for this mod,
BlackTigersHD

**Comment by brandon3055** [comment]
I see your point. I will try to add some documentation to the tablet before the next release but in the mean time

setOverrideEnabled (true) allows a computer override the value that is set in the gui. Once thats set you can use setFlowOverride(number) to actually set the flow rate. When controlled like this the gate wont respond to a redstone signal.

**Comment by BlackTigers** [comment]
Hey Brandon,

thank you so much for this little documentation, it really helped me and it's very easy to understand when you know the ComputerCraft / OpenComputers System :D.

Greetings,
BlackTigersHD

**Comment by acidjazz** [comment]
<3 https://github.com/acidjazz/drmon
