### ISSUE TITLE
Armourer Workshop and Draconic Evo armor rendering!

### ISSUE THREAD

**Issue by Alexismachina** [brandon3055/Draconic-Evolution#262]
Even when you disable the armor in the armourer workshop menu the draconic armor still renders

**Comment by brandon3055** [comment]
Im just starting on 1.8.9 now so i dont really have time to look into this. And there probably isnt much i could do from my end anyway But CosmeticArmorReworked seems to be able to manipulate my armor which means it is possible for other mods to modify my armor.
