### ISSUE TITLE
Bow error 1.0.2-Snapshot_11

### ISSUE THREAD

**Issue by robertwsf** [brandon3055/Draconic-Evolution#263]
[crash-2016-03-04_04.29.50-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/158123/crash-2016-03-04_04.29.50-server.txt)

**Comment by robertwsf** [comment]
Sorry, didn't have time to post a lot of details last night.
When I draw back the Bow and hold it getting ready to fire.  When I release the bow I get the crash.
I get it with both bows.  I removed the extra mods and reset the world and tried again to make sure it wasn't a conflict.

It's the only problem I've found so far.  I'll continue testing tonight.

**Comment by Alexismachina** [comment]
Well it does seems to be a conflict since bows work perfectly for me...

**Comment by robertwsf** [comment]
Alexismachina, are you on a server or single player local?  If a server what mod pack?
It works fine for me in single player but not on a server.  I just want to make sure it's not a problem with my server.

**Comment by brandon3055** [comment]
This is indeed a server issue ans it will be fixed before snapshot 11 is officially released
