### ISSUE TITLE
No rapid fire after bow rewrite?

### ISSUE THREAD

**Issue by olagarde** [brandon3055/Draconic-Evolution#266]
Looks like rapid fire mode is gone after the complete rewrite of the bow;  there's no equivalent in the new menu/gui/etc.  Intentional?  If so, could we have it back (although the damage should really be nerfed more, or much more power hungry)?

**Comment by brandon3055** [comment]
Rapid fire is still possible but the bows are a lot more configurable now.
First off in case you haven't found them yet all of the tools including the bows now have 5 modes which you can toggle between with a keybinding (default "\") and each of these modes can be configured separately.

To create a rapid fire mode similar to the original you would simply enable auto fire. And if you want to increase the fire rate you would upgrade the draw speed with the upgrade modifier.
