### ISSUE TITLE
Particle Generator as a computer component

### ISSUE THREAD

**Issue by GunArm** [brandon3055/Draconic-Evolution#268]
Would you consider having the particle generator implement IDEPeripheral?  What block would be more suited for computer control than one with 40ish mostly numerical settings?  

I would love to create strobe effects, a discotech, cycling colors, and spinning laser beams.  I feel like there would be a lot of ways to get really creative with programs controlling the particle generator.

**Comment by brandon3055** [comment]
Oh man... I have no objection to the idea but i just started update to 1.8.9 so i dont really have the time to do it rite now... But i dont mind pull requests if you would like to add it yourself.

**Comment by GunArm** [comment]
Ok, no problem.  The idea of attempting to do it myself is intriguing.  I will look into it although I can't promise anything as I have not done java in many years, and I'm also not familiar with the build tools.  But I'll try my luck at it :)

**Comment by wlhlm** [comment]
@GunArm That's unfortunate, I already started implementing computer support. I hope you don't mind.

![2016-03-20_01 50 43](https://cloud.githubusercontent.com/assets/1928113/13902199/b5583af2-ee3f-11e5-9d19-5ad674ae967f.png)

**Comment by GunArm** [comment]
Awesome!
