### ISSUE TITLE
Not working reactor. Seems isn't a TE. DE 1.0.2 RC 2

### ISSUE THREAD

**Issue by BlazingGamer** [brandon3055/Draconic-Evolution#269]
Hello! New issue with Draconic Reactor...
Wanted to test it in creative. Placed DR core and 4 stabilizers around it (5 blocks from core each). The Tablet says that wnen I RMB on DR core it says is this a correct building. Clicking with a core places another core on top of it, hand clicking doesn't work. Switched into Survival and clicking still didn't work. Please fix or describe what is incorrect...

**Comment by brandon3055** [comment]
Once you have the stabilizers placed try breaking and replacing the core. But make sure there are no blocks between the core and the stabilizers when you place it or the stabilizers will not be detected leading to the error you are describing.

**Comment by BlazingGamer** [comment]
1) tried replacing core, didnt work.
2) Technically there is... hmm... air between them :) nothing more.
This didn't help. :(

**Comment by GreatOrator** [comment]
There may be hidden blocks there.  As a test only, fill the space with cobble, then remove it all and try to form the reactor.

**Comment by brandon3055** [comment]
Fake air blocks shouldn't really be an issue because i have checking for them ever since the issues with the energy core... @BlazingGamer Can you post a screenshot of your setup please.

**Comment by BlazingGamer** [comment]
Sorry for disturbing, that was my fault,  because seems core isn't clickable anyway and only stabilizers... But I'm really not sure that that behavior is correct, is it?

**Comment by brandon3055** [comment]
Yes that is correct. Its usually not a good idea to put your hand into a ball of super heated plasma which is why you cant access the gui by clicking the core.

**Comment by BlazingGamer** [comment]
Then, could you probably fix manual because it says I need click core...

**Comment by brandon3055** [comment]
Thanks for pointing that out. I have fixed that mistake and added an additional paragraph about troubleshooting connectivity issues between the reactor and the stabilizers. That will be in the next update.
