### ISSUE TITLE
Client crash to server select screen when changing profile with hotkey

### ISSUE THREAD

**Issue by AryuSyrius** [brandon3055/Draconic-Evolution#270]
Upon pressing "R" key to change profile, the client crashes to server select screen.

Core Version = 1.0.0.11
Draconic Evo version = 1.7.10-1.0.2-RC2

**Comment by GreatOrator** [comment]
Link to pastebin crash report please

**Comment by AryuSyrius** [comment]
I don't have a crash log. Here is my FML-Client paste. Maybe crash is not the right work,. but I am kicked from the server back to the server select screen,

http://pastebin.com/WH42y4yE

**Comment by GreatOrator** [comment]
If you are on a server then we would need the server log as it would have the reason you were kicked typically, but will look at your client log

**Comment by AryuSyrius** [comment]
Ok, you want to look at the bottom of this log. It's the last thing I did was duplicate the issue. Line 9559 and down.

http://pastebin.com/Q1shXMCj

**Comment by GreatOrator** [comment]
@brandon3055 :

Console : [11:11:33] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
Console : java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayerMP.func_71011_bu()Lnet/minecraft/item/ItemStack;
Console :   at com.brandon3055.draconicevolution.common.network.ButtonPacket$Handler.onMessage(ButtonPacket.java:129) ~[ButtonPacket$Handler.class:?]
Console :   at com.brandon3055.draconicevolution.common.network.ButtonPacket$Handler.onMessage(ButtonPacket.java:53) ~[ButtonPacket$Handler.class:?]
Console :   at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
Console :   at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]

Looks like a forge server (no kcauldron)

**Comment by AryuSyrius** [comment]
This is a server that I built and maintain. This issue started happening immediately after I updated to the latest release of DE. I didn't change anything else and profiles were working just fine before the update. So what do I need to do to get this to work again?

**Comment by GreatOrator** [comment]
This is why I tagged brandon above, so he can look at the code to see what is happening

**Comment by AryuSyrius** [comment]
Ah, sorry. Didn't see the tag. Thank you.

**Comment by brandon3055** [comment]
Thanks for reporting this. It will be fixed in the next release which i will probably release some time today.
