### ISSUE TITLE
Stabilized Spawners doesn't work when chunkloaded

### ISSUE THREAD

**Issue by MythixDino** [brandon3055/Draconic-Evolution#272]
Hi

After using some stabilized spawners fully upgraded (So Tier 3, nether star and a notch apple), I realised they don't work when they are chunkloaded without a player nearby. Tested this with villagers, creepers and wisps.

**Comment by GreatOrator** [comment]
Right click on the spawner to make sure ignore player requirements are in fact set to true on the spawner, can not duplicate this in a test world and the only other option is if this is a server, they have protections in place that are preventing it.

**Comment by MythixDino** [comment]
It's a server. I'll try outside of the protected area (It's griefpreventionplus if you want to know).

**Comment by MythixDino** [comment]
Still the same, they don't work on the server. There's no protection present, and the spawner is fully upgraded.

**Comment by GreatOrator** [comment]
We would need server logs then most likely, as well as a complete mod list as this has been tested in several modpacks now with no issues on a forge server.  Maybe try this without any bukkit/sponge plugins and just on a pure forge server and see if it still happens. if not, then contact whatever server mod is being used (again sponge, bukkit, cauldron, etc)

**Comment by GreatOrator** [comment]
Closing unless/until response of results
