### ISSUE TITLE
Upgraded Tools don't charge beyond 1 MIL RF

### ISSUE THREAD

**Issue by RiverChief** [brandon3055/Draconic-Evolution#275]
I've increased the allowable RF capacity for the sword of the wyvern using the upgrade modifier system (Which I think is a great idea) and noticed that the now upgraded weapon wont charge beyond the defaut value.

Great mod. Love everything about it. Good Luck.

**Comment by brandon3055** [comment]
Thanks for letting me know! That was a close one lol. As i will be releasing a "final" version of 1.0.2 today.

**Comment by RiverChief** [comment]
No problem man, have patreon?

**Comment by GreatOrator** [comment]
https://www.patreon.com/brandon3055?ty=h
