### ISSUE TITLE
Draconic Evolution 1.0.2 Requires PlayerAPI

### ISSUE THREAD

**Issue by Acters** [brandon3055/Draconic-Evolution#276]
1.0.2 version of Draconic Evolution requires a mod called "PlayerAPI" version 1.3

I went and found such mod, however it still threw this error.

[Minecraft](http://i.imgur.com/kgxcyp3.png)

[log](http://pastebin.com/QR28wEzY) Error in line 165. Note that I do NOT have Smart Moving in my mod list. I can safely say that removing Draconic Evolution from the mod list allows minecraft to completely load up.

**Comment by brandon3055** [comment]
Oh F*** I was testing a bug with smart moving and the only way i could get one of the mods to work was to actually add its scr to mine. And i forgot to remove it....

**Comment by brandon3055** [comment]
Ok i have replaced the original file so you can just go download 1.0.2 again and it will be fixed. Sorry about that.

I will leave this issue open for a bit so its easy to find for anyone else who downloaded the bad version.

**Comment by Acters** [comment]
I am glad it was caught early. Cheers!
