### ISSUE TITLE
Can not charge my energy core multiblock

### ISSUE THREAD

**Issue by Assaro** [brandon3055/Draconic-Evolution#279]
I have put some mods together and build myself an energy multiblock, but it doesn't charge. Tried all tiers of the multiblock.
My mods:
advanced genetics
applied energistics
ae2 stuff
animation api
battletowers
bdlib
bibliocraft
big reactors
brandons core
buildcraft
chest transporter
chicken chunks
code chicken chunks
cofh core
cookie core
denseores
draconic evolution (latest version)
dynamic lights
dynamic mazes
enderio
enderstorage
enhanced portals
equivalent exchange
extra cells
extrautilities
fastcraft
flans mod
galacticraft core
galacticraft planets
gravity gun
hats
ic2 nuclear control
ichunutil
igw-mod
industrialcraft
infernal mobs
inventory tweaks
ironchest
journeymap
legendgear
malisiscore
malisisdoors
mantle
meteors
micdoodle core
minefactory reloaded
modular powersuits
natura
nether ores
notenoughitems
numina
openblocks
openeye
openmoslib
openperipheral
optifine
ruins
tinkersconstruct
thermal dynamics
thermal expansion
thermal foundation
tinkersmechworks
torchlevers
tinkerssteelworks
twilightforest
updatechecker mod

Hope you find a solution for my problem

Assaro

**Comment by brandon3055** [comment]
Can you post a screenshot of your setup?

**Comment by Assaro** [comment]
![2016-03-27_03 16 43](https://cloud.githubusercontent.com/assets/13085620/14063275/8fba335a-f3ca-11e5-839b-0dbf73fda1ba.png)
ok, I quickly rebuilded it but it still doesnt work :/

**Comment by brandon3055** [comment]
Hmm... Can you check it it will receive energy from another source? Something like a creative energy cell from Thermal Expansion?

I really have no idea why it wouldnt be working...

**Comment by Assaro** [comment]
Ok, Problem solved, the download was broken. I replaced the draconic evolution file and it worked. thanks for your fast support :+1:
