### ISSUE TITLE
Question about generator

### ISSUE THREAD

**Issue by lkjhgfda** [brandon3055/Draconic-Evolution#28]
Can you make a way to automatically remove empty bucket from generator like vanilla furnaces do?
I.e. if you put a hopper under furnace it will drop empty bucket into hopper if you using lava buckets to feed the furnace.
Or other option: generator will accept liquid fuel like combustion generator from Ender IO mod.

**Comment by brandon3055** [comment]
The generator is meant as a last resort incase you don't have any other mods installed capable of generating rf. However that is something that should be implemented so it will be in the next release.
