### ISSUE TITLE
Enhanced Charm of Dislocation Crashing When Adding Location

### ISSUE THREAD

**Issue by nightstick24** [brandon3055/Draconic-Evolution#280]
I'm getting an odd crash when I try to add a new location to my Enhanced Charm of Dislocation, it's happening on a server, but not my single player, and happened after adding the enchantment soulbound to it. I'm running FTB Infinity Evolved 2.4.2.

Here's my client log from when I join the server, shift rightclick try to add the point click Commit and crash.
http://pastebin.com/DtumxuFi

Upon testing without soulbound on a new enhanced charm of dislocation I'm still crashing with the message "A fatal error has occured, this connection is terminated"

**Comment by GreatOrator** [comment]
If you can, try to get the logs from the server from around that time as well.  I am running a different server using the latest version of DE and not seeing this issue.

**Comment by nightstick24** [comment]
I can't seem to reproduce it anymore either, if it does it again I'll grab the logs and reopen the issue.
