### ISSUE TITLE
Soo, why is this still a thing? Or is it inescapable?

### ISSUE THREAD

**Issue by koalalord9999** [brandon3055/Draconic-Evolution#281]
http://prntscr.com/an55g1

If it can be changed in the en_US.lang to
tile.invisibleMultiblock.name=Energy Core

it would look a bit better ;)
Just a minor suggestion, I'm assuming you've tried it, but incase you havn't here ya go.

EDIT: Okay, I see why now I think, because any invisible multiblock even none energy core is labeled that. Hmm... far fetched idea, but is it possible to add a kind of meta data to those invisible multiblocks so you can distinguish between them?

**Comment by brandon3055** [comment]
Oh i thought i fixed that. Turns out i just fixed it for DE's hud and forgot about WAILA. Will be fixed in the next release.
