### ISSUE TITLE
Playing 1.7.2 Project Ozone, has DE in it. HQM Remove all lives when dying against chaos guardian

### ISSUE THREAD

**Issue by koalalord9999** [brandon3055/Draconic-Evolution#282]
I have lost my world due to this bug, I don't know if DE sends death messages to the 'server' that HQM picks up and in turn removes lives even though you havn't died yet or not, but I'm super salty about it.

I was fighting the Chaos guardian all fine and dandy, finally blew up all the towers, then I get stun locked by 2 or 3 chaos balls, then bring my energy on the armor up to ~70%, I drop down to half a heart now each chaos ball that hits me, sends a death notice to HQM and I lose a life, even though I'm still alive. I had 25 lives, and about 50 balls chasing after me. I died, and tried to press respawn (still had about 14 lives when I actually died) but before it would let me press the respawn button, the rest of the chaos balls caught up to my corpse, and blasted it to oblivion, removing the rest of my lives AFTER I"M ALREADY DEAD, then I get kicked from the SP session, told I died, open up SP again, and map is gone. I lost my world because I died once, with 25 lives remaining. 
/rant

**Comment by GreatOrator** [comment]
So, I will put this succinctly, 1.7.2 has been dead for a long time and 1.7.10 is where nearly 100% of mods moved for almost a year.  The bug is not DE it is the modpack, let the author know it will not be "fixed" since nothing is broken.

**Comment by koalalord9999** [comment]
The pack is made in 1.7.10, it uses the latest (or very recent) version of Draconic Evolution. The pack version is 1.7.2, not the minecraft version.

**Comment by brandon3055** [comment]
In that case its still a HQM issue
