### ISSUE TITLE
energy efficiency upgrade

### ISSUE THREAD

**Issue by shadoxxhd** [brandon3055/Draconic-Evolution#284]
especially the draconic bow needs a shit ton of power if you max all the stats (max damage, max velocity multiplier, max shock wave power), so it would be awesome if you could upgrade the energy efficiency with cores (maybe using all upgrade slots but one with chaos cores would set the energy usage to 0, so you could emulate the old bow with 5*chaos efficiency and 1*awakened drawspeed).

also, i think there should be a way to increase the upgrade capacity of items using chaos cores or something like that.

the shields could use some polishing too IMHO. the draconic chestplate could have an upgradeable thorns effect ('violent shield discharge', damage depends on damage dealt to you), the helmet an active invisibility ability (needing a lot of energy, cost decreases with upgrade level and shield capacity), the boots maybe a shockwave ability when you fall down, and the leggings idk, maybe a upgradeable chance to deflect projectiles (capping at 90% or so, otherwise the chaos guardian fight would be trivial)

**Comment by GreatOrator** [comment]
Moved to http://www.brandon3055.com/suggestions/energy-efficiency-upgrade/
