### ISSUE TITLE
cant get souls in creative

### ISSUE THREAD

**Issue by MRGanboo** [brandon3055/Draconic-Evolution#285]
im building a huge automated system and for it to properly work i need to setup some spawners with different souls and the only soul i can get is pig can i know a list of all the mod soul ids so i can atleast givve them to my self since killing mobs to get them is a huge time waster for a creative project 

love your work love the mod hope u keep updating it 
have a nice day -MRGanboo

**Comment by brandon3055** [comment]
You can use the give command like so.
`/give @p DraconicEvolution:mobSoul 1 0 {Name:Enderman}`
Note that you need to use the registry name meaning the same name you would use with the /summon command.

**Comment by MRGanboo** [comment]
ty helped out alot

**Comment by MRGanboo** [comment]
have a nice day.

**Comment by Nagapito** [comment]
Just an update, in 1.10.2 its now:

`/give @p DraconicEvolution:mobSoul 1 0 {EntityName:Enderman}`

**Comment by VeraxonHD** [comment]
In 1.12 there is no such item according to chat error message
`There is no such item with name draconicevolution:mobsoul`

**Comment by ichhaa** [comment]
try draconicevolution:mob_soul

**Comment by VeraxonHD** [comment]
Yeah an underscore in there works just fine.
`/give @p DraconicEvolution:mob_soul 1 0 {EntityName:Enderman}`

**Comment by Saklad5** [comment]
It’s also in JEI, though I’m not sure if that is true by default or changed by my modpack.

**Comment by hawk2eyes** [comment]
how do i get one with wither skeleton @brandon3055

**Comment by ichhaa** [comment]
i get a soul with
/give @p DraconicEvolution:mob_soul 1 0 {EntityName:Wither_Skeleton}

**Comment by hawk2eyes** [comment]
this is the only way i can get any soul, in this case skeleton. But i can't figure out how to get wither_skeletons
/give @p DraconicEvolution:mobSoul 1 0 {Name:Skeleton}

**Comment by FoxMcloud5655** [comment]
If you search previous issues, you will find in #1044 that brandon3055 already replied with this command:
`/give @p draconicevolution:mob_soul 1 0 {EntityName:"minecraft:wither_skeleton"}`

**Comment by Simon-Dy** [comment]
To anyone searching for this command in newer modpacks, try
/give @p draconicevolution:mob_soul{EntityName:"minecraft:enderman"} 1
