### ISSUE TITLE
[Suggestion] Remote interface

### ISSUE THREAD

**Issue by rYanGap** [brandon3055/Draconic-Evolution#288]
As one of my favorite endgame mods, there is one thing that would be incredibly powerful yet hasn't been implemented yet. I am requesting a handheld tool that can bind to a block face and access it or its GUI from anywhere, even across dimensions. I know Ender IO works within a certain range, and Thaumcraft has the transvector interface, but this device/item would be incredibly powerful (think of being able to remotely access your ME interface in another dimension without having to set up a quantum gateway, or being able to bind it to the new draconic upgrade bench and upgrade your items on the fly) and should require lots of power to run. I think Draconic Evolution is the only mod that would work with such a device.

**Comment by GreatOrator** [comment]
This suggestion has been moved to http://www.brandon3055.com/suggestions/remote-interface/
