### ISSUE TITLE
Crash when open the config GUI

### ISSUE THREAD

**Issue by ooJiraiya** [brandon3055/Draconic-Evolution#29]
My client crashes when i open the Draconic config GUI here is the report:

![crash-2015-03-11_14](https://cloud.githubusercontent.com/assets/11424691/6597418/d451add6-c7fc-11e4-8200-7d32bccf9c55.png)

**Comment by brandon3055** [comment]
OMG pastebin for crash reports please!!
That crash has been fixed in the latest snapshots.

**Comment by ooJiraiya** [comment]
Sorry for that, Just saw it after posting.. Ftb hasnt updated it yet i think
