### ISSUE TITLE
Instantly die with draconic armor on against Chaos Guardian?

### ISSUE THREAD

**Issue by jake9876789** [brandon3055/Draconic-Evolution#290]
So I went to kill the chaos Guardian by myself and it was going fine until the last 20% of the fight.  I still had full energy on my draconic armor and as you can see from the inventory I still had energy in my capacitors also(about 70m total).  It instantly killed me with some kind of ball, and also then instantly killed me again through the effects of the crown of laurel(botania).  Only enchant on the armor was soulbound.  Had on the ring of experience, ring of aeseir, crown of laurel, a knapsack, 2x sets of hearts, tectonic girdle,draconic armor set.  
<img width="1279" alt="screenshot 2016-04-13 21 40 43" src="https://cloud.githubusercontent.com/assets/18456145/14517737/b8a5936e-01c5-11e6-85d7-259323888e57.png">
Log: http://pastebin.com/eDVJsVA7

**Comment by Alexismachina** [comment]
Did you have full rf on thoses capacitor ? Also did you have last stand -_- ?

**Comment by jake9876789** [comment]
Didn't have last stand.  They were full to start with and when I died they had a total of ~70m energy remaining, like I said in the OP.

**Comment by brandon3055** [comment]
First of all what version of draconic evolution are you using? Im guessing your using an older version from before i added the new shield mechanic. How many chaos charges (red projectiles) did you get hit by? If you get swarmed by enough of them and they all hit you in rapid succession its possible for them to drain your armor faster then the capacitors can recharge it. In versions before i added the shield it was best to just let those hit you and keep an eye on your energy reserve so they dont get a chance to build up to a number that can get past your armor.

**Comment by jake9876789** [comment]
Yea thats possible I was in fact trying to dodge them.  I am on version 1.0.2(snapshot 9).  Whats this new shield mechanic(or where can I read about it?)

**Comment by brandon3055** [comment]
Really the only place you can read about it at the moment is in the tablet. As im guessing you dont have access to the a version of DE that has the shield i copies this from the tablet. http://puu.sh/oloRm/3f671fef3f.txt
