### ISSUE TITLE
Strange numbers in log

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#291]
After DE and BrandonsCore update I see in log this: http://pastebin.com/b2hJ23VK

I think it's kind of your debug.

EDIT: I found in fml log - it's debug of Brandon's Core

**Comment by brandon3055** [comment]
Yea sorry about that i forgot to remove some debug code in the last update. It is printing damage received by players.

**Comment by ArcasCZ** [comment]
When it will be available for download?

**Comment by brandon3055** [comment]
its already available. http://minecraft.curseforge.com/projects/draconic-evolution/files/2294644

**Comment by ArcasCZ** [comment]
The numbers were in Brandons Core, no?

**Comment by brandon3055** [comment]
Oh sorry i should have said the numbers were actually coming from DE but for some reason i was using the BC LogHelper which meant they had the [Brandons Core] tag.

**Comment by ArcasCZ** [comment]
Good to know... :D I'll update soon and let you know ;)

**Comment by ArcasCZ** [comment]
Not all your debugs were removed

[21:38:46] [Server thread/INFO] [Brandon's Core/]: collide 2

About 20 times in log... Did you think about calling debug function, which will check debug in config and do log (or not)?

**Comment by brandon3055** [comment]
Ahh darn...  If i keep forgetting to take these things out i may have to... That one was caused by my arrows whenever you pick one up off the ground.

**Comment by ArcasCZ** [comment]
When it will be posted on CurseForge?

**Comment by brandon3055** [comment]
I will see about pushing a release today after i get some other fixes implemented.

**Comment by ArcasCZ** [comment]
Will it be available on another site? I don't want to wait 3 days before they accept it.

**Comment by p455w0rd** [comment]
@ArcasCZ Curse takes like 10-15 mins. I just posted my mod and a few updates yesterday. Getting ready to push another in a few mins.

**Comment by brandon3055** [comment]
@ArcasCZ its been live for 4 hours now. It only takes a couple minutes for curse to approve new releases. http://minecraft.curseforge.com/projects/draconic-evolution/files

**Comment by ArcasCZ** [comment]
@brandon3055 You forgot write to chagnelog that you removed that debug :D

**Comment by brandon3055** [comment]
oh oops that was such a minor change i made in like 2 seconds i forgot to include it. But i will add it.

**Comment by ArcasCZ** [comment]
It's minor change, but it's really important to not have strange numbers in console :D
