### ISSUE TITLE
Draconic Chest - lost inventory

### ISSUE THREAD

**Issue by Kotawolf** [brandon3055/Draconic-Evolution#295]
Was using a chest, and when I restart my server to correct a config file the chest that was in inventory wiped.  Chest was in my characters inventory, about 2-3 lines of inventory in it, when I went to duplicate it, had 5 stacks of just vanilla dirt in there for testing.

This is a custom server build.
Server is being ran on a Win 7 laptop, has 4gig (ram) dedicated just to MC Server.

After posting in the wrong forum, not put in correct place.
Here is my mod list, was built from mods on curse, plus  Immibis Core and Dimensional-anchor
-=-=-=-=-=-=-=-=-=-=-=-
<ul>
<li><a href="http://minecraft.curseforge.com/mc-mods/227983">MFR Magical Crops Compatibility (by Portablejim)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/220333">CoFHLib (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/60089">Mouse Tweaks (by YaLTeR97)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/237102">FTB Utilities  (by FTB)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/228756">Iron Chests (by progwml6)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/233140">Buildcraft Compat (by buildcraftchildsplay)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/73488">Waila (by ProfMobius)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/232134">SimpleLabels (by insaneau)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/237103">FTB Tweaks (by FTB)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/229876">BetterFps (by Guichaguri)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/230368">Block Properties (by docrobb)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/67504">ComputerCraft (by dantwohundred)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/77191">AnimationAPI (by thehippomaster21)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/70496">BdLib (by bdew)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223794">Applied Energistics 2 (by AlgorithmX2)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/221585">Roguelike Dungeons (by Greymerk)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/237167">FTBLib (by FTB)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/32274">JourneyMap (by techbrew)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/62121">InfiniBows (Infinity Bow Fix) (by Myrathi)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/67313">Ars Magica 2 (by Torarion)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/236203">Ender IO Addons (by Henry_Loenwind)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/221913">Pam's Clay Spawn (by MatrexsVigil)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/229306">Ender Storage (by chicken_bones)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224614">NotEnoughKeys (by dmodoomsirius)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/60092">Aroma1997s Dimensional World (by Aroma1997)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/222213">CodeChickenCore (by chicken_bones)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/64578">Ender IO (by CrazyPants_MC)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/69163">Thermal Expansion (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225605">LunatriusCore (by Lunatrius)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/229318">Translocators (by chicken_bones)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224942">Dense Ores (by RWTema)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224029">MineTweaker3 (by StanH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223896">MalisisCore (by Ordinastie)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/69118">Morpheus (by quetzi)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224728">FloodLights (by Keridos)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/229218">ExtraCells2 (by DrummerMC)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/63352">NEI Addons (by bdew)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/70635">Obsidian Boat (by zilulil)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/227443">Thermal Dynamics (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/239262">Too Many Ores (by AKTheKnightMC)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/59769">ObsidiPlates (by Myrathi)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/61811">Buildcraft (by CovertJaguar)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/227878">Minecraft Minions (by AtomicStryker)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225815">NotEnoughResources (by Way2muchnoise)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/228834">Magical Crops (by Mark719)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/236204">Waterhook (by Henry_Loenwind)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/233105">McJtyLib (by McJty)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225604">InGame Info XML (by Lunatrius)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223094">Inventory Tweaks (by Kobata)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225194">AE2 Stuff (by bdew)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/226797">Magical Crops Compat - Minefactory Reloaded (by Streuner91)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/221863">Another One Bites the Dust (by ganymedes01)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/222880">Thermal Foundation (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/66672">Minefactory Reloaded (by skyboy026)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225251">NEI Integration (by tonius111)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/69162">CoFH Core (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/66675">NetherOres (by skyboy026)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/243205">Mo' Villages (by The_WeatherPony)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223735">Aroma1997Core (by Aroma1997)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/222211">NotEnoughItems (by chicken_bones)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225561">Extra Utilities (by RWTema)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/238474">EnderOre (by adcrafter27)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223815">In-Game Wiki Mod (by MineMaarten)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/59216">Treecapitator (by bspkrs)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/241994">Big Reactors (by ErogenousBeef)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/74924">Mantle (by mDiyo)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/51195">Railcraft (by CovertJaguar)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223548">Solar Flux (by Nauktis)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/227564">OreDictionaryConverter (by EXTER7)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/220954">ModTweaker (by jaredlll08)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/79325">Simply Jetpacks (by tonius111)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225063">Adventure Backpack (by JavierDarkona)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224712">Wawla - What Are We Looking At (by darkh4x)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/228609">QuantumFlux (by jotato)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/59413">Enchanting Plus (by darkh4x)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/221910">Pam's Weee! Flowers (by MatrexsVigil)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223428">EnderTech (by voxelcarrot)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/226410">ProjectE (by sinkillerj)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/79287">Waila Harvestability (by squeek502)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225635">AgriCraft (by InfinityRaider)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223583">Solar Expansion (by TedTheRusSB624)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/78886">FlatBedrock Xplosion's Edition (by big_Xplosion)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/231853">Equivalent Energistics (by Mordenkainen3141)</a></li>
</ul>

-=-=-=-=-=-=-=-=-=-=-=-
Apparently, some sort of mod conflict, hoping someone knows and can point out what it could be, or help eliminate mods that it won't be.

**Comment by brandon3055** [comment]
Hay welcome to the DE issue tracker! 
Ok so how are you restarting your server? Do you use a restart script? or just /stop then start? 
Try running /save-all before stopping and see if it still happens.

I really dont see how this could be an issue with another mod. And the only other thing it could be is minecraft not saving the player inventory properly before stopping. Unless the contents are actually whipped when you break the chest and not when the server stops. In that case that can be caused by the server running low on ram when you break the chest which prevents the data from being saved.

**Comment by Kotawolf** [comment]
Use the stop command, then run the bat file for startup.

I'll test with that /save-all
I'd been carrying the chest with a bunch of nether ore, a couple turtles and such for a little bit.. 20-30 min maybe?

And now, I've let it sit for this time, restarted (both client and server) again, and EVERYTHING is back in the chest.    Sometimes I don't like Java.

**Comment by brandon3055** [comment]
You said you were able to reproduce this? I assume you broke the chest immediately before restarting? 

I also have java sometimes because nether me nor another modder i am currently chatting with can think of any reason this would happen.

If running save-all fixes it then maby just create a restart bat that runs save-all stop then restarts. If not... i dont know...

**Comment by Kotawolf** [comment]
Correct.    I'll remember to do that save-all command.
Just peaked, the server is only using about 1/4 of the ram allocated via the bat file.

Didn't restart the computer, maybe windows was doing something in the background.     I don't know coding, I just fix hardware normally.

**Comment by brandon3055** [comment]
Yea... an issue with windows is very unlikely.
