### ISSUE TITLE
Extra Cells

### ISSUE THREAD

**Issue by Evulperson** [brandon3055/Draconic-Evolution#296]
It seems that the Wyvern/Draconic Flux Capacitors will drain themselves entirely at an alarming rate, while trying to charge an already 100% full Wireless ME Fluid Terminal. This has also been submitted to Extra Cells.

**Comment by brandon3055** [comment]
This sounds like an extra cells bug. It sounds like they have an issue with there RF API implementation. Atleast for that item.

**Comment by brandon3055** [comment]
This is not an issue on my end.
