### ISSUE TITLE
Magnet: Don't pick up AE seeds

### ISSUE THREAD

**Issue by Viper007Bond** [brandon3055/Draconic-Evolution#297]
Ender IO's magnet is cool in that it doesn't try to pick up partially grown AE seeds from the pool of water if I get near it. It'd be great if DE's awesome magnet would do that too, especially since it can pick up through walls (I sealed up my water block).

I guess a blacklist of item IDs in the configuration file would be the way to go about this so that modpack authors can control it.

Draconic-Evolution-1.7.10-1.0.2a in FTB Infinity v2.5.0

**Comment by brandon3055** [comment]
Sure i will add a black list in the next version.
