### ISSUE TITLE
Magnet: Configuration, such as disabling through-wall pickups?

### ISSUE THREAD

**Issue by Viper007Bond** [brandon3055/Draconic-Evolution#298]
Any plans to add some options to the magnet like other tools have? One option I'd like to have is the ability to not pick up through blocks. It's picking up things from rooms I have sealed off.

Draconic-Evolution-1.7.10-1.0.2a in FTB Infinity v2.5.0

**Comment by brandon3055** [comment]
I will add the blacklist you suggested in your other comment but teleporting through walls is intentional Is is an "Item Dislocator" meaning it teleports things similar to the regular dislocator except the item dislocator just teleports items within its range directly to you.
