### ISSUE TITLE
Draconic reactor disappearing

### ISSUE THREAD

**Issue by reignbringer** [brandon3055/Draconic-Evolution#299]
I have a draconic reactor set up in Infinity Evolved 2.5.0, and the core of the reactor along with all of the fuel has disappeared 4 times now. The entire assembly is chunkloaded, and the reactor is managed by computer to automatically turn off if containment drops too low or temperature too high. No explosion damage is inflicted on the environment either, and the time from fueling that it disappears seems to be random. Sometimes it only takes 45 minutes to an hour, the most recent disappearance took nearly 5 days. Any help would be appreciated.

**Comment by brandon3055** [comment]
I cant think of anything at all that would cause that... Are there any errors in the console when this happens? (If playing on a server errors will be in the server console)

**Comment by reignbringer** [comment]
It's a public server, so I would have to talk to an admin. Would block log be helpful as well?

**Comment by reignbringer** [comment]
The staff team where I play and I fixed the issue- one of the chunks the reactor was in was corrupted, so there were chunk loading problems when I would leave the base. This was invalidating the reactor setup so the core was disappearing, along with the fuel. Everything should work as intended now. Thanks very much for the help.

**Comment by brandon3055** [comment]
Cool im glad you got it figured out.
