### ISSUE TITLE
Crash when clicking on a non existent dimension within the Dislocation charm GUI

### ISSUE THREAD

**Issue by becky15675** [brandon3055/Draconic-Evolution#30]
I have made RFTools dimensions in FTB Infinity and deleted them after they were no longer needed.
However when clicking on them in the charms GUI, it crashes.

Crash report if needed: http://pastebin.com/uMkqFzfD

**Comment by DemonSeedxp** [comment]
I've had the same issue with deleting mystcraft worlds.

I could scroll though the saves in the charm (shift+mouse) but could not open the gui and remove them , as it would crash my client as soon as I click on a missing dimension

**Comment by brandon3055** [comment]
This is something that i am aware of and will try to have fixed by the next update.
