### ISSUE TITLE
[Suggestion] Draconic Staff of Power Functionality/Possible new Recipe

### ISSUE THREAD

**Issue by zzApotheosis** [brandon3055/Draconic-Evolution#300]
I thought it would be convenient to be able to till dirt with the Staff of Power. And the size of this effect could vary depending on the current dig size like 1x1, 3x3, etc. This idea also led me to think about the functionality of the Draconic Axe as well (Ability to fell entire trees). It would be awesome to have the two functions of the Draconic Hoe and the Draconic Axe included in the Staff of Power, which leads me to suggest a new recipe for the Staff of Power:

P | C | Sh
C | Sw | C
H | C | Ax

where
P = Draconic Pickaxe
C = Awakened Core
Sh = Draconic Shovel
Sw = Draconic Sword
H = Draconic Hoe
Ax = Draconic Axe

Yes, I'm suggesting to use more expensive Awakened Cores in place of the Awakened Draconium Ingots to offset the extra functionality that the Staff of Power would provide, should you consider this suggestion. I would rather stop using my Mekanism Atomic Disassembler every time I need to till some dirt. ;)

Thanks for reading, and as always, thanks for this outstanding mod!

**Comment by GreatOrator** [comment]
Feature request moved to http://www.brandon3055.com/suggestions/draconic-staff-of-power-functionalitypossible-new-recipe/
