### ISSUE TITLE
Ported events

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#301]
If someone has armor from draconic and Forge / Bukkit (correctly ported) cancels event, player got damaged anyway (or got energy decreasion from damage).

**Comment by brandon3055** [comment]
Should be fixed in the next release. I added a check to see if the event is already canceled and if so do nothing. If that dose not fix it nothing will.

**Comment by ArcasCZ** [comment]
Still seems like shield is processing even event is cancelled - energy is going down and graphics shows.

**Comment by ArcasCZ** [comment]
I don't know, how does this exactly work on Forge, but what about setting priority to Lowest?

**Comment by brandon3055** [comment]
No i have my event priority set to normal which is exactly where it should be. If another mod needs to fire first then they should have their priority set to high. Setting my priority would only break other mods that need their event to fire after mine.
