### ISSUE TITLE
DE vs. Reis Minimap

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#303]
If you have wyvern / draconic armor and enabled Shield display, then Rei's minimap get glitched (img bellow).

Version of DE: actuall.

Images: https://ctrlv.cz/shots/2016/04/30/88aP.png , https://ctrlv.cz/shots/2016/04/30/gqfM.png

**Comment by GreatOrator** [comment]
Rei's Minimap for 1.7.10 was a completely unauthorized port.  As such, you will need to talk to the person who ported it or switch to journeymap.

**Comment by ArcasCZ** [comment]
That's nice, but still other mods with HUD doesn't have problem with it... And I don't give freak about authorized or unauthorized - if autor doesn't update...

**Comment by ArcasCZ** [comment]
I don't care about authorized or unauthorized - autor abandoned it. Also, other mods with HUD has no problem with this. So it has to be problem of DE.

There is no map so usefull and easy to controll as Rei's minimap.

**Comment by GreatOrator** [comment]
There are other options, and because the current developer does not have the permissions required to port and DE works fine with journeymap, not going to consider it.

**Comment by ArcasCZ** [comment]
That's so stupid...
