### ISSUE TITLE
WirelessCraftingTerminal drains entire Draconic Evolution Flux Capacitor

### ISSUE THREAD

**Issue by condensedapple** [brandon3055/Draconic-Evolution#304]
The WCT, when in hotbar, drains a flux capacitor (wyvern or draconic) instantly (even if the wct is at 99.99%). This does not occur when using some other flux cpacitor (Flux Capacitors from ThermalExpansion, Quitit Cell from QuantumFlux). Other AE-Terminals (AE2/ExtraCells/ThaumicEnergistics) are not affected.
Also reported to [WirelessCraftingTerminal](https://github.com/p455w0rd/WirelessCraftingTerminal/issues/4)
Possibly related to #248 and #296

**Comment by brandon3055** [comment]
I have confirmed that this is not an issue on my end.
