### ISSUE TITLE
Another spam

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#306]
[18:29:23] [Server thread/ERROR] [Draconic Evolution/]: Could not get ticket for dragon

**Comment by brandon3055** [comment]
Thats got something todo with the forge chunkloading system. For some reason it wont let the dragon chunk load. Not my problem.

**Comment by ArcasCZ** [comment]
But it's spamming console and decreasing TPS. What we can do with it? Is there any chance to fix this? Or disable this freaking spam?

**Comment by ArcasCZ** [comment]
Or what about limiting spam to 1 msg per 5 seconds?
