### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#307]
[19:54:11 ERROR]: Could not get ticket for dragon

There has to be somethink to do, my console is just stucket with it... 
!
[image](https://cloud.githubusercontent.com/assets/6602975/14962556/b6e2c0d6-109f-11e6-9efa-f2a111bd28c1.png)

**Comment by brandon3055** [comment]
http://minecraft.curseforge.com/projects/draconic-evolution/files/2297668
