### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#308]
Can you just stop closing my issues and try to cooperate?

[image](https://cloud.githubusercontent.com/assets/6602975/14962914/829cc57c-10a1-11e6-8786-4cfcd4da01ee.png)

**Comment by p455w0rd** [comment]
@GreatOrator - https://github.com/blog/862-block-the-bullies

**Comment by ArcasCZ** [comment]
Block me for what? For trying to fix some broken things in mod?

**Comment by Alexismachina** [comment]
@ArcasCZ when did the issue start happening ?

**Comment by p455w0rd** [comment]
You're using a an out-dated mod. Brandon is trying progress, not regress. @GreatOrator has given you a great alternative solution and you continue to spam the DE repo. You have been answered.

**Comment by ArcasCZ** [comment]
@Alexismachina It started few days ago - we didn't touch DE, DE config, Forge configs or Forge (KCauldron) version.

**Comment by ArcasCZ** [comment]
@p455w0rd I know he wants to progress. But I won't force players to update when this part of code was not changed at all.

**Comment by Alexismachina** [comment]
@ArcasCZ Tbh, he can't really do anything about it (easily) rigth now. Best solution go kill the dragon.

**Comment by Alexismachina** [comment]
And please don't open another issue for this, it's useless and you will just get blocked from this repo.

**Comment by Alexismachina** [comment]
@GreatOrator Can you close this?

**Comment by ArcasCZ** [comment]
It's public server, so we as owners can't just come to player and say ,,We confiscate this dragon." Better way to fix this is add config value to disable this warning.

**Comment by Alexismachina** [comment]
If you want to continue this chat go on http://webchat.esper.net/ and join #draconicevolution

**Comment by brandon3055** [comment]
http://minecraft.curseforge.com/projects/draconic-evolution/files/2297668
