### ISSUE TITLE
Crash Report Test

### ISSUE THREAD

**Issue by GreatOrator** [brandon3055/Draconic-Evolution#309]
## Description
y u brake stuf

## Base information
* Minecraft version: 2.0
* Minecraft Forge version: 9000+
* Draconic Evolution version: Too high to list

## Mod List or Mod Pack (include version)
Every mod that exists

## Crash report
y u ned this?

**Comment by p455w0rd** [comment]
you crazy XD

**Comment by GreatOrator** [comment]
Had to test the new template somehow :P
