### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by drizzt267** [brandon3055/Draconic-Evolution#31]
I was looking around at different mods in Infinity as well as Monster mod packs from the FTB launcher.   Is it possible for you to make the Mob Grinder enchantable with looting?   This was an idea i got from Rotary craft, Quarry plus.   Ender quarries and Ender IO (killer joe using enchanted weapons).

**Comment by brandon3055** [comment]
I feel that an enchanted mob grinder would be too op. But if i can think of a good fun way to balance it then maby.
