### ISSUE TITLE
Some way to nerf spawners

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#310]
Can you please add config column that can limit mob spawns in area and nerf minimal time and max number of monsters? Some idiots on our server doesn't understand fair-play and overuse this to cause lags.

**Comment by GreatOrator** [comment]
You can list the spawners as blacklisted entirely in the configs:

# add the unlocalized name of a block or item to this list to disable it [default: ]
    S:"Disabled Blocks & Items" <
     >

You can also decrease the chance of souls dropping to further limit or stop them altogether and just set up a special in-game shop for players to get them.

**Comment by ArcasCZ** [comment]
I don't want to disable them, I just want to nerf them - some kind of multiplier - basic mobs: 7, multiple by multiplier and round (so I can set multiplier to 0,5 and then will spawn only 4 mobs). And same for time.

**Comment by NolanSyKinsley** [comment]
I think you are looking for an entity/spawn limiter outside of this plugin. I cannot remember the name of it, but there is a plugin that will limit mob spawns to 8 per chunk in order to help combat lag. That way no matter what mod spawns mobs they will adhere to that limit without question.

**Comment by ArcasCZ** [comment]
No, I'm looking for limitation for spawners. This can do lot of mods such as MineFactory Reloaded. You set limits and it works. Simple.

**Comment by p455w0rd** [comment]
It seems that this mod just doesn't do what you want it to do. Brandon is currently experiencing technical difficulties and won't be back for a couple days. On top of that unless it's a game-breaking bug, I feel his attention should be more directed to his current project, DE for 1.9. So to alleviate all of your problems, I've compiled a small list of resources that will help you fix said problems:

https://docs.oracle.com/javase/tutorial/
http://bedrockminer.jimdo.com/modding-tutorials/
http://jabelarminecraft.blogspot.com/
http://www.wuppy29.com/minecraft/modding-tutorials/
http://www.minecraftforge.net/forum/
https://help.github.com/articles/fork-a-repo/

Try and be part of the solution. Be the change you wish to see in this world...

**Comment by GreatOrator** [comment]
One of the huge draws for the spawners in this pack is the fact that it has such high spawn rates. and also what p455w0rd said above

**Comment by ArcasCZ** [comment]
@p455w0rd If I want to fix it by myself, then I'll do it. But I though that there are developers to improve their mods. I have lot of work with mods we use which were abandoned. And if i'll fork this repo, I'll post it on GitLab with private access...

MC 1.9 is stupid shit - Mojang blocks servers that doesn't accepted EULA (from 1.9.3), vanilla is even more HW consumpting, lot of good mods are not at 

@GreatOrator - Tell it to our HW and players. Yes, it has high spawn rates and we wan't to let DE stay above another mods and be cool. But we don't want to let our server fall in lags. Lot of developers understood that if you let owners of public server without control of mob spawning, they'll block your spawners from using. And that's the way we don't want to go. We just want to add multipliers for spawning and entity limit check as other mods do. It's in YOUR interest to solve this, 'cause it harms reputation of your mod.

**Comment by p455w0rd** [comment]
It's public and open source to allow ANYONE to contribute. This means that instead of being an insulting dick, you could actually help to fix the problem.

**Comment by ArcasCZ** [comment]
@p455w0rd But for me it's lot of time to study, how does it works in Forge and how it's implemented here. But for brandon it's adding 2 options to config and somewhere add that multiplier. Not much work.

**Comment by p455w0rd** [comment]
As I said above...Brandon isn't even online atm and hasn't been for over a day due to issues that I'm not at liberty to discuss. He won't be for yet another couple days at least. So in the time you waste sitting here complaining and suggesting ideas you could be learning how to fix these problems. If you have all of this time to sit and inspect every aspect of this and sit and play MC in general, you have time to learn. Your argument is invalid. While brandon is away I don't think any PRs will be approved either since he is not here to give the go ahead. I could show you exactly where in the code what needs to be changed and what it needs to be changed to, but I don't care to give people fish..I'd rather help them learn to fish..

**Comment by ArcasCZ** [comment]
@p455w0rd OK, I'll do it myself. Don't estimate any PUBLIC translate to Czech language. And any other issues from me. I fi have to do somethink in code by myslef, then I put it on my Gitlab and use it only on our server - if I have to waste my time to fix somethink that mod author can't, then I'll not show it public and let it as our own original feature.

**Comment by ArcasCZ** [comment]
I don't have anythink agaist @brandon3055 , but you both are helpless and only make this mod bad reputation.

**Comment by p455w0rd** [comment]
1.2million+ downloads..yeah...we're definitely ruining the this mod XD

**Comment by ArcasCZ** [comment]
@p455w0rd It's not about people, who downloads it, It's about people who give their ideas. Do you think there will be someone who will give his idea to get fucked for not doing on his own?

**Comment by p455w0rd** [comment]
You're only "fucked" if you don't try...

**Comment by ArcasCZ** [comment]
I'm curious what will you say to #315 if there will be no function for this...

**Comment by GreatOrator** [comment]
Actually, this is a feature brandon plans to add this feature at some point but it is a lower priority under some other features he wants in.
