### ISSUE TITLE
Massive entity count at Chaos Island?

### ISSUE THREAD

**Issue by cj89898** [brandon3055/Draconic-Evolution#311]
## Description
I am using server command to check entity count and I have a plugin (ClearLag) that allows me to clear the entities (thankfully). Whenever I type my command (/lag) It shows all dimensions and some information including entity count. I noticed in the end it got up to around 120k to over 200k entities! I went there and had to force myself to use the clear entity command from console because my client can't render 120k entities... This has happened around 4-5 times now and it lowers my server's TPS quite a lot.

* Side note: The ClearLag plugin auto-removes entities, but wouldn't remove these.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: KCauldron (Not sure of version)
* Draconic Evolution version: Draconic-Evolution-1.7.10-1.0.2a

## Mod List or Mod Pack (include version)
 - Project Ozone v1.7.10

**Comment by ArcasCZ** [comment]
Update to newest version - this problem was fixed in 1.7.10-1.0.2b.

**Comment by GreatOrator** [comment]
Yeah, I believe this was addressed in the recent version.  Had to do with the despawn timer of the chaos dragons projectile weapon iirc.  Let me know if you are still seeing the issue after updating please.

**Comment by cj89898** [comment]
ugh of course it was fixed in the update I can't use...

**Comment by cj89898** [comment]
Still happens in 1.7.10-1.0.2d In modpack Sky Factory v2.5

**Comment by HadesDurin** [comment]
there is a 1.0.2 e version aviable
you may try that one to see if it still happens

**Comment by cj89898** [comment]
Dang of course it's an issue I can't fix.

**Comment by brandon3055** [comment]
I dont get it that should be fixed in your version... Im starting to think something is completely preventing the entity from updating because assuming it is actually updating it is hard coded to die after 60 ticks.

**Comment by cj89898** [comment]
This is still going on in SF2.5.2 sadly. It destroys my server's TPS

**Comment by cj89898** [comment]
I ran a /cofh killall and it did kill a chaos guardian but the entities are still there.

**Comment by brandon3055** [comment]
Ok need some more info. Are you using the latest version of furmas? And can you go into the chaos chamber and see if there are a crazy amount of particles everywear.

**Comment by cj89898** [comment]
I went there and they all dissapeared.

**Comment by cj89898** [comment]
What are "furmas"?

**Comment by covers1624** [comment]
Thermos is what i believe brandon was trying to say.

**Comment by cj89898** [comment]
I don't use Thermos, I use KCauldron.

**Comment by brandon3055** [comment]
Sooo... As far as i know KCauldron is no longer in development and has been replaced bu thermos.

**Comment by cj89898** [comment]
That is true, but I currently am using KCauldron. I don't believe it's an easy switch to do.

**Comment by covers1624** [comment]
They are essentially the exact same except Thermos is in active development.. http://cyberdynecc.github.io/Thermos/install

**Comment by cj89898** [comment]
Hold on, I'm following the link I was given.

**Comment by cj89898** [comment]
So I guess we'll put the issue on hold and see if it happens again?

**Comment by covers1624** [comment]
Sure, let us know.

**Comment by cj89898** [comment]
Alrighty then :)

**Comment by cj89898** [comment]
Oh my, it's actually happened right before updating so here's our test? Should they all despawn?

**Comment by GreatOrator** [comment]
Any word if it is fixed?  Been unable to replicate in test environments under pure forge conditions

**Comment by cj89898** [comment]
Haven't happened since I switched to Thermos so far :)

**Comment by cj89898** [comment]
Just happened again.

**Comment by Gummin** [comment]
Haven't noticed anything like this in my **many** tries defeating the Chaos Guardian in my normal forge server with version 1.0.2h.

**Comment by brandon3055** [comment]
At this point i really dont know what else could cause this issue. But if i ever push another 1.7 built i woll look into it... again...
