### ISSUE TITLE
Pet Peeve - Spelling Error

### ISSUE THREAD

**Issue by zzApotheosis** [brandon3055/Draconic-Evolution#312]
## Description
![2016-05-08_00 34 15](https://cloud.githubusercontent.com/assets/11908793/15096454/71a19ba4-14b5-11e6-95d4-5a4e1a19a8f5.png)

Self explanatory. "DraconicEvolution:draconicDistructionStaff"

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Draconic Evolution version: 1.0.2d

**Comment by cj89898** [comment]
The thing is, I believe that changing it to draconicDestructionStaff will remove all current staffs xD

**Comment by zzApotheosis** [comment]
Yeah, I kinda figured that. Personally, I'd be fine with that since I'm so late-game; I would just reclaim my enchantments and awakened cores (from upgrading it) and recraft it after my pet peeve has been satisfied, haha.

And Brandon could also warn players in the changelog about this. Honestly, if it would be a big deal for a player, I would use something like Twilight Forest's Uncrafting Table to get the components for the Staff of Power, wait for the update, and then recraft the Staff of Power without losing anything :P

**Comment by GreatOrator** [comment]
Since it is the unlocalized name, you typically do not see that unless you have a mod that shows it or you use f3+h normally anyways, so I would not worry about it.  We have known about it for awhile but like cj89898 stated, would end up removing all current staves from anyone's world which would cause more problems than a simple edit to a text that is normally not seen.

**Comment by brandon3055** [comment]
This will be fixed in 1.9 but as for 1.7.10... my response is pretty much what greatorator already said. Its not worth breaking everyone's worlds just to change a thing that most people never see.

**Comment by zzApotheosis** [comment]
Honestly, I'm even more relieved to know Draconic Evolution will be available in 1.9. Is there anywhere I can follow development like Twitter or such?

**Comment by Alexismachina** [comment]
On irc, webchat.esper.net #DraconicEvolution

**Comment by zzApotheosis** [comment]
Excellent. Thank you!
