### ISSUE TITLE
For @brandon3055 #2

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#314]
As usuall here - @brandon3055 is only one person that can get involved.

Can you please add config column that can limit mob spawns in area and nerf minimal time and max number of monsters? Some idiots on our server doesn't understand fair-play and overuse this to cause lags.

**Comment by GreatOrator** [comment]
Alright, going to close this since you don't seem to realize that I am also a member of the DE team.  Please stop spamming the github with comments if you don't like the responses you get.
