### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by ArcasCZ** [brandon3055/Draconic-Evolution#316]
@brandon3055, can you calm down your contributors (exactly @GreatOrator )? I want to give you some issues and ideas and he's locking my issues without any reason (I want YOUR answer, not his).

**Comment by GreatOrator** [comment]
If you are unhappy with the responses we provide you (especially after I have talked to brandon) you are welcome to not post here.

**Comment by GreatOrator** [comment]
And fyi, i am locking the issues because you continue to post or create new issues when you do not like the answers you are getting.
