### ISSUE TITLE
DraconiumOre always returning false for canEntityDestroy

### ISSUE THREAD

**Issue by oceth** [brandon3055/Draconic-Evolution#317]
## Description
The DraconiumOre block implementation always returns false for canEntityDestroy. This prevents some other mods from proper interaction. I tried quarrying DraconiumOre using the RfTools builder quarry, which checks this method using a fake player. According to the developer of RfTools, he has to check this method (https://github.com/McJty/RFTools/issues/530). I understand it returns false to prevent the dragon from destroying it. Would it be possible to specifically check for the dragon?

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Draconic Evolution version: 1.0.2a

## Mod List or Mod Pack (include version)
RfTools 4.23 and many more, which are not relevant here

**Comment by TheBrain0110** [comment]
I noticed this when I had an RFTools builder clear out everything below y=40 in a large area (looking for dimensional shards), and found Draconium Ore left scattered around.

I kinda enjoyed finding and mining them all actually ;)

**Comment by brandon3055** [comment]
Making a change that should* fix this in the next version. Let me know if it dose not.
