### ISSUE TITLE
Extra Utilities "Kikoku" Sword not effective against Draconic Shield

### ISSUE THREAD

**Issue by TheBrain0110** [brandon3055/Draconic-Evolution#319]
## Description

Related to the discussion of balance in end-game weaponry in #283, the Kikoku sword from Extra Utilities is another that seems less effective than it should be. It's made using an unlisted recipe involving mobius stable/unstable ingots, and was one of the first weapons designed to damage even Creative players. It deals all of regular, armor-piercing, and "divine" damage, which is supposed to be absolute, bypassing all protection. This is relatively balanced even as a high-end weapon by only dealing 7 regular, 4 armor-piercing and 2 divine damage, but with both Sharpness V and Wrath V enchants, this goes up to  

+19.5 Regular
+16.5 Armor Piercing
+14.5 Divine Damage

In the previous FTB Infinity Evolved version, pre-shielding rewrite (1.0.2-snapshot 9), this did about 15 actual damage to players in Draconic armor, as intended. (Not sure if it was coming from the armor-piercing or the divine portion. Probably Divine, since it also damages Creative players...)

Now in 1.0.2a, it does only 15 damage total to the shield, and none to the player. This is clearly much less than it should be doing.
Now, whether the correct behaviour should be bypassing the shield and damaging the player directly, or just doing significant damage to the shield, I don't know. I just know it should be doing something more than it currently is.

As a side note, how does the armor itself behave for protection when the shield is depleted? Does it still provide significant benefit? Its hard to test, because anything capable of depleting the shield is pretty much going to insta-kill you regardless. And do Protection enchantments have any effect on top of that? Do they affect the shield at all, or just the armor?

## Mod List or Mod Pack (include version)
FTB Infinity Evolved 2.5.0

**Comment by GreatOrator** [comment]
Actually, that is how it is intended.  The shield mechanic is supposed to protect players from all damage at the price of increasing shield entropy.  I wager that once the shield is knocked down the sword becomes as effective as it would against diamond armor

**Comment by TheBrain0110** [comment]
Yes, but specialty damage types designed to bypass armor and protection should at least have _some_ increased effect against it.

And if nothing else, it's supposed to be doing nearly 50 damage per hit with the different types added together, not 15.

**Comment by GreatOrator** [comment]
Well, will let brandon make the call ultimately, but if he keeps adjusting the armor to let all these "specialty" swords bypass protection of the armor, then it renders the armor not as useful becuase then what stops every mod dev from making a sword then saying, make my sword bypass your armor's special protection.

**Comment by TheBrain0110** [comment]
Well that is the danger with endgame power creep. You make something really powerful, then something to protect against that, then something to counter that protection, then something to defend against that, then something to bypass that...

I guess in my view, being effectively immortal flying around in your draconic armor is fun most of the time, but every once in a while you want to be able to hit someone and actually do something ;)

**Comment by brandon3055** [comment]
Ok this will be a thing in the next update (Note this will also make the guardian fight a lot harder because its projectiles bypass armor)

######## 1.0.2e ########
-damage that bypasses armor now deals double damage and increased entropy to the shield.
