### ISSUE TITLE
Flight Bug, DE 1.0.2D

### ISSUE THREAD

**Issue by MineWitherMC** [brandon3055/Draconic-Evolution#321]
## Description
Gamemode 0: Equip Draconic Chestplate -> Get in the air -> Unequip the Chestplate.
Result: unlimited survival flying.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: build 1614 (latest)
* Draconic Evolution version: 1.0.2D + Brandon Core 1.0.0.12 (both latest)

## Mod List or Mod Pack (include version)
Botania r1.8-249 (it's for 1.7.10)
Baubles 1.0.1.10 (for Botania)

Note: works only with botania. You'll fall without it.

**Comment by brandon3055** [comment]
Thanks for the report.Should be fixed in the next version.
