### ISSUE TITLE
Graphic Glitch/Black box when using other in-game manuals

### ISSUE THREAD

**Issue by seato39** [brandon3055/Draconic-Evolution#322]
## Description
Ever since upgrading to version 1.0.2d the in game manuals for immersive engineering and witchery (possibly others) now are surrounded by a large black box whenever you try to read them. Downgrading to version 1.0.2c however fixes this, so its definitely an issue with 1.0.2d.
## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:1.7.10-Forge10.13.4.1614-1.7.10
* Draconic Evolution version:1.7.10-1.0.2d

## Mod List or Mod Pack (include version)
...
[1.7.10]ArmorStatusHUD-client-1.28
[1.7.10]bspkrsCore-universal-6.16
AOBD-2.9.1
appliedenergistics2-rv2-stable-10
backpack-2.0.1-1.7.x
Baubles-1.7.10-1.0.1.10
bdlib-1.9.4.109-mc1.7.10
BetterFps-1.0.1
BigReactors-0.4.3A
BiomesOPlenty-1.7.10-2.1.0.1067-universal
BloodArsenal-1.7.10-1.2-5
BloodMagic-1.7.10-1.3.3-17
BrandonsCore-1.0.0.11
buildcraft-7.1.15
chunkgen-1.7.10-1.3.0
CodeChickenCore-1.7.10-1.0.7.47-universal
CodeChickenLib-1.7.10-1.1.3.138-universal
CoFHCore-[1.7.10]3.1.2-325
ComputerCraft1.75
Damage-Indicators-Mod-1.7.10
denseores-1.6.2
dimensional-anchor-59.0.3
Draconic-Evolution-1.7.10-1.0.2d
EnchantingPlus-1.7.10-3.0.2-d
EnderCore-1.7.10-0.2.0.32_beta
EnderIO-1.7.10-2.3.0.424_beta
ExtraCells-1.7.10-2.3.9b188
ExtraTiC-1.7.10-1.4.5
extrautilities-1.2.12
FastLeafDecay-1.7.10-1.4
forestry_1.7.10-4.2.10.58
ImmersiveEngineering-0.7.5
immersiveintegration-0.6.8
immibis-core-59.1.4
INpureCore-[1.7.10]1.0.0B9-62
InventoryTweaks-1.58-147
ironchest-1.7.10-6.0.62.742-universal
Jabba-1.2.1a_1.7.10
journeymap-1.7.10-5.1.4-unlimited
LycanitesMobsComplete 1.13.0.5 [1.7.10]
Mantle-1.7.10-0.3.2b
mcjtylib-1.8.1
MineFactoryReloaded-[1.7.10]2.8.1-174
MineTweaker3-1.7.10-3.0.10B
MineTweakerRecipeMaker-1.7.10-1.1.0.11
ModTweaker2-0.9.5
MoreEnchantments-1.7.10-1.3.2.1
neiaddons-1.12.14.40-mc1.7.10
NEIIntegration-MC1.7.10-1.1.2
NetherOres-[1.7.10]2.3.1-22
NotEnoughItems-1.7.10-1.0.5.120-universal
ObsidiPlates-1.7.10-universal-3.0.0.18
OpenBlocks-1.7.10-1.5.1
OpenModsLib-1.7.10-0.9.1
OpenModularTurrets-1.7.10-2.1.9-211
OptiFine_1.7.10_HD_U_D4
Railcraft_1.7.10-9.10.0.0
RedstoneArmory-1.7.10-1.2.0-41
RedstoneArsenal-[1.7.10]1.1.2-92
rftools-4.23
RTG-1.7.10-0.7.0
SimplyJetpacks-MC1.7.10-1.5.3
SolarExpansion-Basic-1.6a
StevesCarts2.0.0.b18
TConstruct-1.7.10-1.8.8
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.1.2-240
ThermalFoundation-[1.7.10]1.2.3-112
TiCTooltips-mc1.7.10-1.2.5
TMechworks_mc1.7.10_0.2.8
twilightforest-1.7.10-2.3.7
Waila-1.5.10_1.7.10
Wawla-1.3.3-1.7.10
witchery-1.7.10-0.24.1

list other mods being used
...

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
can you please post a screenshot if the issue.

**Comment by GreatOrator** [comment]
Closing since no response from original poster

**Comment by CJOak** [comment]
https://www.reddit.com/r/feedthebeast/comments/4rhle3/anyone_know_what_is_up_with_this_guide_api_book/

**Comment by GreatOrator** [comment]
Please create your own thread.  this was closed well over a month ago
