### ISSUE TITLE
[Sugesstion] DE Cable

### ISSUE THREAD

**Issue by HadesDurin** [brandon3055/Draconic-Evolution#326]
I know you have those Energy Relays and Energy Transceiver, but even with the adv. Energy Relays i can hook up 20 devices to one Relay.

Cables work the same way and in my view they are more comfortable.
At the moment i have ~50 machines in 2 rooms (each 9*18 tiles) and all wired up with mekanism cable/Cofh Mod cables. 
After my latest issue with modded cables and cross mod issues (DE-Mekanism-Cofh Mods) i found it better to have an own De set of cables to transfer energy around. That way DE is more independent to other mods and issues like https://github.com/brandon3055/Draconic-Evolution/issues/323 will be then avoided.

Another thing is the upcoming Tesla API and Cofh Mods not development, so in the futur of this mod (1.8/1.9 and so on) there will be a need for own cables. Even in late game (which i haven't reached yet) with the DE Reactor, i think its possible to realise the reactor & flow gates with energy Relays and such, but hooking it up with cables is easier.

At least let me say there can be diffrent Tiers of Cables maybe like:

Tier 1: draconium ingot, redstone, draconium ingot give you 8 basic cables, which can handle ~16k RF/t
Tier 2: draconic core, redstone, draconic core give you 8 adv. cables, to handle up to 64k RF/t
Tier 3: wyvern energy core, redstone, wyvern energy core give you 16 wyvern cables, to handle up to 256 RF/t
Tier 4: draconic energy core, redstone, draconic energy core give you 16 draconic cables, to handle up to 1024 RF/t or endless.

**Comment by brandon3055** [comment]
I will most likely be redesigning the energy net in 1.9 but i probably wont be adding cables. I do want DE to be usable on its own but it is really best used with other RF mods.
