### ISSUE TITLE
Draconic Bow 1.7.10 (New Verision)

### ISSUE THREAD

**Issue by Ethereall** [brandon3055/Draconic-Evolution#329]
I cannot make the bow work, I have the newest version of draconic evolution. The modes don't seem to be doing anything, and I cant figure out how to turn on autofire or the arrow of draconic fire. There is also a shockwave?

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: No Idea, whatever skyfactory uses.
* Draconic Evolution version: Newer one with new models

## Mod List or Mod Pack (include version)
Skyfactory 2.5
list other mods being used
Loads

## Crash report
```
CRASH REPORT HERE
```

**Comment by HadesDurin** [comment]
you should look up your key configs to review the keys of draconic evolution
also you look up your DE version in your modpack and if it is not 1.0.2 E, then inform the mod autor about the latest aviable version

**Comment by Libright1558** [comment]
I have a similar problem( I am using draconic evolution 1.0.2e)  I find draconic bow cannot 
magnify the player's sight ( I turned the magnification to 600 % , then i shot an arrow, but the sight didn't change at all )  Is it a bug?

**Comment by Ethereall** [comment]
@Libright1558 How did you manage to turn the magnification up? Or how do you turn any of them up? ex Draconic Arrow or Rapid fire or shockwave? Also, would you seem to know what the modes on other things do? Ex Pickaxe? I can make it so it's max is 11x11 digging range, but cant seem to make the digging range actually go up. Can you help me? With the newer versions of Draconic Evolution I cannot seem to find any information on. Do you have a link to an updated wiki?

**Comment by Libright1558** [comment]
you can look up the Draconic Evolution Information Tablet, it contains a fairly extensive manual for most of the items added by the mod. If you still can't make any draconic tools functional,try to reinstall this mod.

**Comment by brandon3055** [comment]
That mostly sounds like user error. As for the zoom not working  i suspect another mod is messing with the VOF and breaking the effect. I will try running the effect latter which may fix it but if it dosnt there really isnt much else i can do.
