### ISSUE TITLE
The draconic bow's ''magnification'' mode defective

### ISSUE THREAD

**Issue by Libright1558** [brandon3055/Draconic-Evolution#330]
## Description
The draconic bow can't magnify the player's view ( I turn the draconic bow's magnification to 600% , but when I shot an arrow , my view doesn't change at all )
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Draconic Evolution version: Draconic-Evolution-1.7.10-1.0.2e

**Comment by GreatOrator** [comment]
Already an open issue covering this issue.
