### ISSUE TITLE
[Hotfix Required] Config options.

### ISSUE THREAD

**Issue by OneEyeMaker** [brandon3055/Draconic-Evolution#335]
@brandon3055 
Found small typo in my code. I don't think, that this is critical, but it can break calculations at some point.
Just replace 'DIG' with 'DRAW' only in this line:
https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/common/handler/BalanceConfigHandler.java#L393

I don't want create PR only for this small hotfix.

**Comment by OneEyeMaker** [comment]
I created a PM, because I found another bug: if I set armor energy storage too high (but less, than Integer.MAX_VALUE), I've get summary capacity less then 0. (int overflow). Check my PR.

**Comment by GreatOrator** [comment]
Alright, will go mark the PR then and close this out instead.
