### ISSUE TITLE
Version not aviable 1.0.2f

### ISSUE THREAD

**Issue by HadesDurin** [brandon3055/Draconic-Evolution#339]
## Description
during the last days i get after starting minecraft ingame information, about a new version of DE 1.0.2f
and until now its not aviable for download.

**Comment by covers1624** [comment]
last i heard, Brandon was having internet issues. He will upload it to curse when he can.

**Comment by brandon3055** [comment]
Ok sorry about that i was all set to release a new version then as covers said my internet decided to completely die.

**Comment by HadesDurin** [comment]
i just thought about issues on curse. so all is fine
