### ISSUE TITLE
Issue with step assist

### ISSUE THREAD

**Issue by HadesDurin** [brandon3055/Draconic-Evolution#340]
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Draconic Evolution version: 1.0.2 E

![2016-06-15_12 23 43](https://cloud.githubusercontent.com/assets/5231067/16076560/1c8e9114-32f4-11e6-9395-b56843ed0910.png)
as you can see in the picture its very simple to rebuild
the issue is, that you cannot walk over the slab out of the window with activ step assist
the other side without slab is still usable and you can easily walk thru

**Comment by GreatOrator** [comment]
Try using step assist from other mods, I believe that is an issue with the function of that method versus just this mod from my own testing.

The problem is to make step assist work it actually has the player walk up higher than 1 block and is a problem with any mod that has the ability

**Comment by HadesDurin** [comment]
i can try thaumcraft boots, but thats all i can guess of items using step assist

**Comment by GreatOrator** [comment]
botania has the sash or whatever it's called that adds it too and I believe ender i/o has an item that gives it (that's the one I most recently had the same issue you described)

**Comment by HadesDurin** [comment]
so i tried, 
boots of the traveler from thaumcraft
journeymans sash from botania
ender io dark steel boots with extras
and non of them have passed the test with the slab in the picture
