### ISSUE TITLE
Crash using the crystal binder wrench

### ISSUE THREAD

**Issue by GreatOrator** [brandon3055/Draconic-Evolution#341]
## Description
When attempting to bind the wireless energy transceiver the server crashes and client crashes to menu.
This happens even after breaking and setting the advanced energy transceiver back down.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1566
* Draconic Evolution version: 1.0.2f

## Mod List or Mod Pack (include version)
TolkienCraft II

## Crash report
https://paste.ee/p/puUs1

**Comment by brandon3055** [comment]
Darn it... I found the problem but i dont know if i will be able to upload a fix because my internet is currently completely broken...
