### ISSUE TITLE
upgrade not presisten upon tool/armor upgrade from wyvern to draconic

### ISSUE THREAD

**Issue by krismoellegaard** [brandon3055/Draconic-Evolution#343]
## Description
so i went to upgrade my armor form wyvern to draconic as fare as i can see the cores i had instal (yousing the upgrade modfier) was not keap i replicated this in creativ dont know if it a bug or if it intented

## Base information
* Minecraft version:1,7,10
* Minecraft Forge version:10,13,4,1614
* Draconic Evolution version:1,7,10-1,0,2a

## Mod List or Mod Pack (include version)
... FTB Infinity Evolved 2,5,0

**Comment by GreatOrator** [comment]
will need to upgrade to latest version and test first.  If the issue is still there, create a new issue
