### ISSUE TITLE
Draconic/wyvern bow wont charge 

### ISSUE THREAD

**Issue by arcfiend1** [brandon3055/Draconic-Evolution#345]
## Description
Cannot charge the draconic/wyvern bow in any charger including the energy infuser, I downgraded each version until it would charge with energy which was 1.0.2e 
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: unknown
* Draconic Evolution version: 1.7.10-1.0.2g/f

## Mod List or Mod Pack (include version)
...
list other mods being used
...

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
@OneEyeMaker Looks like you durped a bit with this one. The hole point of ItemNBTHelper is to remove shit like this. https://github.com/OneEyeMaker/Draconic-Evolution/blob/24b3af116c1fc0c23d2ffa4dd5d710a5ddede23a/src/main/java/com/brandon3055/draconicevolution/common/items/weapons/DraconicSword.java#L114-L116

I will fix it myself
