### ISSUE TITLE
Explosive damage config doesn't work

### ISSUE THREAD

**Issue by Jakja2** [brandon3055/Draconic-Evolution#346]
In the config for Draconic Evolution, there is a config setting to disabled the wyvern/draconic bow explosive block damage. When I switched it to "false", I can still blow stuff up with the bow.

    # Dose Draconic bow explosion damage blocks
    B:"Bow Block Damage"=false

* Minecraft version: 1.7.10
* Draconic Evolution version: Draconic-Evolution-1.7.10-1.0.2d

Skyfactory 2.5.0

**Comment by GreatOrator** [comment]
Have you tried with version 1.0.2g yet?

**Comment by Jakja2** [comment]
I have not. I can though. Will post again with outcome.

**Comment by Jakja2** [comment]
Can confirm. Still doesn't work in 1.0.2g.

**Comment by GreatOrator** [comment]
Thank you for testing, will mark this as a bug.  I know @brandon3055 is currently working on a few bugfixes right now so hopefully he can get this one in too

**Comment by Jakja2** [comment]
Thanks for the help!

**Comment by brandon3055** [comment]
Oh... yea i may have forgotten to re implement that when i re wrote the bows.... Will be fixed in the next version.
