### ISSUE TITLE
Strange graphics bug

### ISSUE THREAD

**Issue by DestinyPlayer** [brandon3055/Draconic-Evolution#347]
## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:10.13.4.1614
* Draconic Evolution version:1.0.2g

## Mod List or Mod Pack (include version)
http://prntscr.com/boef4u

http://i65.tinypic.com/5f2qrm.png
I'm honestly not sure what mod's the problem here. I'm not even sure after which mod did the problem start. But what could be the culprit of these graphics glitches?

**Comment by GreatOrator** [comment]
Unfortunately you will have to remove mods 1 by 1 to find out.  Any mod that has custom rendering could be at fault

**Comment by brandon3055** [comment]
Yea that is being caused by another mod not resetting the render state after rendering something.

**Comment by DestinyPlayer** [comment]
Just so you know, I found out the reason why. It happens when you add Draconic Evolution to a world that didn't have DE before.
