### ISSUE TITLE
Draconic / Wyvern bow doesn't charge when crafted

### ISSUE THREAD

**Issue by TopWraith** [brandon3055/Draconic-Evolution#348]
## Description
The bow when crafted doesn't charge, when added in with NEI in cheat mode it charges fine.
What's the difference between this?

I saw a closed issue with it before, but i can't view that.

On an off-topic thing, I use Ender IO and cannot open the Vibrant Capacitor's inventory with anything from Draconic Evolution in my inventory. It'll just crash my game on the server I play on.
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: forge-1.7.10-10.13.4.1614-1.7.10
* Draconic Evolution version: Draconic-Evolution-1.7.10-1.0.2g

## Mod List or Mod Pack (include version)
...
list other mods being used (mod list is in crash report)
...

## Crash report
```
[crash-2016-07-05_17.07.43-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/347219/crash-2016-07-05_17.07.43-client.txt)
```

**Comment by brandon3055** [comment]
Oh thanks for reminding me about this issue! I was going to push a fix for it a little while ago but was having some internet issues at the time. 

The crash report you posted has absolutely no link to draconic evolution. It looks like it coming from  com.**baublelicious**.items.ItemFlyingRing

**Comment by TopWraith** [comment]
Okay, thanks I'll see if it is that that is causing the issue. I have trouble desciphering that code :/

Alright, thanks! 
I posted in ender IO thread about what the crash was because i thought it was related to me trying to access the capacitor banks.

**Comment by TopWraith** [comment]
I figured out the crashing, not related to Draconic evolution. It looks like it was my ring of flight, sorry for the confusion. :)
