### ISSUE TITLE
Upgrade Modifier

### ISSUE THREAD

**Issue by Lordicon** [brandon3055/Draconic-Evolution#349]
Wyvern Cores are meant to give 2 points per totaling 6 points where as the Draconic Cores only give 1 point per core giving you a total of 3 per. I have tested this and the only way I could get it to work was to place 2 Draconic Cores on the weapon leaving 1 slot open to add Wyvern cores. I spammed the Wyvern Cores and got all 3 placed giving me a total of 80 damage. So it is pretty much a bug where you can have 2 Draconic Cores attached to weapon and still be able to spam 3 more Wyvern Cores on as well giving more damage than intended. Works for power and other slots as well and other weapons.

[http://puu.sh/pRjHf/2a76bfaa78.png](url)

Minecraft version: 1.7.10
Draconic Evolution version: 1.7.10-1.0.2g

Mod List or Mod Pack 
FTB Crackpack 1.7.10

**Comment by brandon3055** [comment]
I will look at this is i ever push a new build for 1.7
