### ISSUE TITLE
[SUGGESTION] Tool HUD Size

### ISSUE THREAD

**Issue by jlove87** [brandon3055/Draconic-Evolution#35]
When playing on the large GUI setting, it causes the tool HUD to take up a large portion of the screen.  Can we have the tool HUD be able to be scaled down/up separately from what the user's GUI scale is set to?  Sort of like how the WAILA HUD works.

**Comment by brandon3055** [comment]
It uses vanilla rendering code so i would have to re write the entire render class. But maby i will look into it in the future.
