### ISSUE TITLE
Bow enchantments don't work.

### ISSUE THREAD

**Issue by Dark-Dragoon** [brandon3055/Draconic-Evolution#351]
## Description

Bow enchantments do not seem to be working, putting Power V on either a Bow of the Wyvern or a Draconium bow doesn't increase it's damage at all as well as Flame doesn't produce flame arrows and Punch doesn't increase knockback. I've tried adding the enchantments through the items GUI as well as with an anvil, both producing the same result of not working.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Draconic Evolution version: 1.7.10-1.0.2h

## Mod List or Mod Pack (include version)
FTB Crackpack 1.7.10 
But also tested in new instance with no other mods with same results.

**Comment by brandon3055** [comment]
The upgrade system is meant to completely replace enchantments. I did forget about the flame enchant but really who needs flame when you can already deal 300+ damage.

**Comment by Sheldor5** [comment]
If the upgrade system is meant to completely replace enchantments so why is there still the misleading inventory thing on the GUI?

Had to google to find out that I wasted XP and materials on the books ...
