### ISSUE TITLE
Reactor explosion algorithm is incorrect

### ISSUE THREAD

**Issue by DarkAyron** [brandon3055/Draconic-Evolution#352]
## Description
When the draconic reactor explodes, the explosion power is only attenuated in vertical direction. When you shield the reactor e.g. with draconium infused obsidian, all blocks below and above the shielding will stay intact, but everything else will be removed like there was no shielding at all.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Draconic Evolution version: 1.0.2h

**Comment by covers1624** [comment]
It would be a really expensive operation to do this in any other way, the current explosion sits in the "Sane" category, i have some "Insane-melt-the-cup-of-the-server" ideas in mind, you may get something better in 1.9 on wards.
