### ISSUE TITLE
draconic armor flight speed very low

### ISSUE THREAD

**Issue by shadoxxhd** [brandon3055/Draconic-Evolution#353]
## Description
the speed settings of draconic armor don't have any effect while flying - I always have the normal creative flight speed

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614 (fml: 7.10.99.99)
* Draconic Evolution version: 1.0.2h

## Mod List or Mod Pack (include version)
http://pastebin.com/y7uzWSZA

**Comment by Gummin** [comment]
Put your chestplate in the upgrade modifier.

**Comment by shadoxxhd** [comment]
there are no speed upgrades in the modifier

**Comment by brandon3055** [comment]
I assume your using the speed setting in the chestplate. I have no idea why your having this issue but i will look into it if i ever push a new 1.7 build.

If i do i will need a reliable way to reproduce the issue.

**Comment by dzaima** [comment]
I had the same issue and after a while I found out that the problem: custom pets. 
How to reproduce: have the custom pets mod installed. The flying speed shouldn't work already, but if it still does, just put any custom pet on your hotbar. So this isn't really this mods fault but the bad flying coding of custom pets.

**Comment by shadoxxhd** [comment]
is custom pets a mod, or do you generally mean mods that override/instantiate some vanilla class?

**Comment by dzaima** [comment]
the custom pets mod is one example of the flight speed modifier not changing flight speed but it may be just some way of forcing minecrafts flying. Custom pets is what I've found to be reproducable.
