### ISSUE TITLE
Zoom bug

### ISSUE THREAD

**Issue by andrewt1738** [brandon3055/Draconic-Evolution#355]
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: release 1.7.10-Forge10.13.4.1614-1.7.10
* Draconic Evolution version: Draconic-Evolution-1.7.10-1.0.2h and Draconic-Evolution-1.7.10-1.0.2g

**Comment by GreatOrator** [comment]
Actually, normal minecraft mechanic.  When you run, the screen zooms in or when you use a speed potion.  The faster the speed boost the more it zooms in.  This is normal.

**Comment by andrewt1738** [comment]
No it should zoom out the faster you go, try a speed potion in vanilla

Sent from my iPhone

On Jul 25, 2016, at 10:12 AM, GreatOrator <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, normal minecraft mechanic. When you run, the screen zooms in or when you use a speed potion. The faster the speed boost the more it zooms in. This is normal.

-
