### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by CHZZ82** [brandon3055/Draconic-Evolution#357]
## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:1614
* Draconic Evolution version:1.0.2h
 
## Problem description
* Draconic Evolution Information Tablet Chinese garbled

**Comment by brandon3055** [comment]
No idea why this would be an issue. I suggest you check if the localization file is is garbled

https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/resources/assets/draconicevolution/manual/manual-zh_CN.json

If it is i have no control over that. If its not than it must be an issue in minecraft. If its minecraft and i ever push a new bugfix build i will take a look at it.
