### ISSUE TITLE
Enhanced Charm not playing well with Mystcraft

### ISSUE THREAD

**Issue by DemonSeedxp** [brandon3055/Draconic-Evolution#36]
I’ve been playing on Feed the Beast Infinity (1.2.1) and have noticed that when using the enhanced charm of dislocation to tp to mystcraft worlds that the world weather, lighting, and sky type (eg. ender star field) are not correct. The worlds often have black skies, rain or snow when there should be none. But using the book to enter the world and everything is correct. Logging out and back in while the visual problems are present will correct the issue.

The issue is present in v.1.0.1-snapshot-3 included in the pack and in the latest v1.0.1-snapshot-5 which I manually updated too hoping to resolve the issue.

**Comment by brandon3055** [comment]
That is something that i have only recently been made aware of. I will look into it.
