### ISSUE TITLE
CraftTweaker(MT port for 1.8 +) recipe changing crash

### ISSUE THREAD

**Issue by the-creamster** [brandon3055/Draconic-Evolution#362]
I got the following crash when i used the command "/mt reload" upon attempting to edit a recipe. The reason behind changing the recipe is to fix/edit recipes given the configs/features of various mods in the modpack.

Minecraft version: 1.10.2
Minecraft Forge: build 2053
Draconic Evolution: 2.0.0.82

https://gist.github.com/the-creamster/246b1ddf2bef7aba1da9f92fa5d5733f

Edit:
The crash only ocurrs if the scripting lines are 'commented' out.

**Comment by the-creamster** [comment]
Refer to the last comment in the linked github and make the decision for yourself.

**Comment by brandon3055** [comment]
Looks like a crash related to my JEI integration. I found where the crash is occurring and came up with a fix but im not exactly sure why the crash was occurring so i cant be sure that my fix will work.  Try this and let me know if its fixed.
[Draconic-Evolution-1.10.2-2.0.0.84-universal.zip](https://github.com/brandon3055/Draconic-Evolution/files/424473/Draconic-Evolution-1.10.2-2.0.0.84-universal.zip)

**Comment by the-creamster** [comment]
I will try it anyway; even though the crash only occurred the initial once and not ever again when doing live testing with the CraftTweaker dev.

**Comment by the-creamster** [comment]
Ok, i got the exact crash again with the build you linked to me; https://gist.github.com/the-creamster/31e52bac5e7c727cfeb687b28e327e02
This time upon world reload after i had been in the world(joined successfully with all of them commented out; un-commented the first one and crash occurred again upon world reload) with all tweaked recipes bar one commented out; that recipe being the one i put in the linked CraftTweaker issue which has now been closed and not going to get fixed CraftTweaker side.

**Comment by the-creamster** [comment]
Scenario 1:
all 3 tweaked recipes commented out upon pack & world load - no crash
Scenario 2:
scenario 1 is successful so i un-comment a recipe and reload the scripts while in the world - no crash

**Comment by the-creamster** [comment]
Another update:
I've tried just about every little combination i can think of and can't seem to replicate the crash with exact replication instructions. So you got any more ideas on how to pinpoint it if at all possible??

Also could you be referencing something in JEI which in it's latest 1.10.2 builds has internally changed and you haven't taken note of it?? just a thought

**Comment by brandon3055** [comment]
Ok hopefully the latest build will finally fix this issue.
