### ISSUE TITLE
Draconic grinder multiplies

### ISSUE THREAD

**Issue by MEzmirly** [brandon3055/Draconic-Evolution#363]
## Description
The draconic grinder keep on multiplying when it has no power and two wither bosses are stuck infront of him. Everythime they shoot the grinder stays on its place and drop another one its not a ghost item because they are all working just fine
## Base information
* Minecraft version:1.7.10
* Minecraft Forge version: 
* Draconic Evolution version:1.0.2h

## Mod List or Mod Pack (include version)
...FTB Crack pack 1.1.0
list other mods being used
...

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
Will be fixed if i ever release another 1.7.10 build.
