### ISSUE TITLE
1.10.2 : mob grinder don't kill

### ISSUE THREAD

**Issue by Lorenzo77** [brandon3055/Draconic-Evolution#364]
## Description

i have a strange behavior with the mob grinder ... it dont kill zombie with a gold armor, the gold zombie is left with just half a heath and he is pushed away from the mob grinder.
enderman+wither skeleton+zombie in front of the mob grinder (the 2 killer joe from ender io a shut down)
![2016-08-16_22 31 08](https://cloud.githubusercontent.com/assets/980737/17714857/ed9e2380-6401-11e6-9349-e036620250f4.jpg)
all the other mobs a dead except the 3 zombie with gold armor
![2016-08-16_22 31 18](https://cloud.githubusercontent.com/assets/980737/17714860/f0bef2f6-6401-11e6-9c1e-26a8ac3d0b9f.jpg)
here you can see the half heath from one zombie
![2016-08-16_22 32 45](https://cloud.githubusercontent.com/assets/980737/17714861/f3c1b56a-6401-11e6-95f6-31e9de792b37.jpg)

------------------------

nb : 
since 2 day i try to make working the "fusion crafting core" without success, can't find wiki data or a manual or a least a forum with data about it :-/

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: not sure, it's the last FTB unstable (12.18.1.2046)
* Draconic Evolution version: Draconic-Evolution-1.10.2-2.0.0.82

## Mod List or Mod Pack (include version)
FTB unstable v4.2.6

...
list other mods being used
...

## Crash report
```
no crash
```

**Comment by brandon3055** [comment]
Will look into this thanks.

**Comment by HellishINC** [comment]
I too am having this issue. Mobs will sit at a half heart and the grinder endlessly hit that one mob dealing no damage. Has this issue been resolved since this stub is closed?
