### ISSUE TITLE
Problem after root server crash

### ISSUE THREAD

**Issue by chaos234** [brandon3055/Draconic-Evolution#366]
Hey, I have the following problem since my root server crashed without any reason: http://paste.ee/p/F1f1j
Here is the full log file:  https://paste.ee/p/5KHy7

There is no crash-report file because the entire root server was crashed without any reason.

**Comment by tmathmeyer** [comment]
He let his domain (http://www.brandon3055.com/) lapse, and so the contributors file that is normally brought down from that url is coming back with parked domain html, which breaks the JSON parser.

**Comment by chaos234** [comment]
this is bad because of this my entiere root server crashes so hardly that all users loosing their connections over time and MC instantly shuts down self and then the hole world is still corupted ... how can I solve this problem?

**Comment by tmathmeyer** [comment]
are you using a linux machine or a windows machine?

**Comment by covers1624** [comment]
Ill notify brandon directly when i get home in 30. 

----- Original Message -----

**Comment by chaos234** [comment]
linux should be written in the log :) - it's a debian x64 with java8u101
Am 24.08.2016 07:48:59 schrieb Ted Meyer <notifications@github.com>:
are you using a linux machine or a windows machine?

**Comment by chaos234** [comment]
thanks so far covers1624 because before the domain was down all worked fine and no server crashed :/
will the domain be back soon or imerditally down?

**Comment by tmathmeyer** [comment]
you can always add the lines:
0.0.0.1         www.brandon3055.com
0.0.0.1         brandon3055.com
to your /etc/hosts file. this will prevent the mod from contacting his broken domain.

**Comment by chaos234** [comment]
Do you mean 127.0.0.1 and should I delete the draconic evolution dir befor the next start?
Am 24.08.2016 08:05:39 schrieb Ted Meyer <notifications@github.com>:
you can always add the lines:
0.0.0.1 www.brandon3055.com [http://www.brandon3055.com]
0.0.0.1 brandon3055.com
to your /etc/hosts file. this will prevent the mod from contacting his broken domain.

**Comment by tmathmeyer** [comment]
Nope, I mean 0.0.0.1, or really any IP address that won't resolve. If you try to point it to the 127.0.0.1 loopback address and you're running anything on localhost port 80, then you'll just get a different set of garbage back.

**Comment by covers1624** [comment]
Brandon currently has capped internet so he is working on getting the domain renewed, Sorry for any inconvenience.

**Comment by chaos234** [comment]
thanks for the fast response and greatings to Brandon for doing his job as well as possible :)
Am 24.08.2016 08:23:09 schrieb covers1624 <notifications@github.com>:
Brandon currently has capped internet so he is working on getting the domain renewed, Sorry for any inconvenience.
