### ISSUE TITLE
Need a way to disable certain blocks.

### ISSUE THREAD

**Issue by joelou1** [brandon3055/Draconic-Evolution#368]
## Description:
I've been working on a modpack Server and I'm trying to remove a certain block from the Mod itself. Disabling it would be necessary as users are abusing of it. I can't seem to find the place in your configs where I can disable such IDs. I'm trying to disable the Sun Dial.

So far I've seen this: http://prntscr.com/cc43ml
But I can't figure out how it works.

In other words, the block may already has been placed, but I want a way to remove it completely so people can't craft it, nor use them because they'll be gone.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: Unknown
* Draconic Evolution version: 1.0.2h

## Mod List or Mod Pack (include version)
Modpack: FTB Presents Sky Factory 2.5 
## Crash report
None

Any help would be appreciated. Thank you.

**Comment by brandon3055** [comment]
It takes a list of unlocalized names for the items and or blocks you want to disable.

You can find a list of all unlocalized names here:
https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/resources/assets/draconicevolution/lang/en_US.lang

Example if i wanted to disable draconium ore i would use the following.
`S:"Disabled Blocks & Items" <
tile.draconicevolution:draconiumOre
>`

Note i do not include .name

**Comment by joelou1** [comment]
"Note i do not include .name"

Meaning I must not add it myself?
 Alright, let me try out something.

**Comment by brandon3055** [comment]
You would just do this

```
S:"Disabled Blocks & Items" <
    tile.draconicevolution:draconiumOre
    tile.draconicevolution:block2
    tile.draconicevolution:block3
    tile.draconicevolution:block4
>
```
