### ISSUE TITLE
[1.10.2] 2D mode results in missing textures.

### ISSUE THREAD

**Issue by HellishINC** [brandon3055/Draconic-Evolution#369]
MC/F: 12.18.1.2076 DE: 2.0.0.82

Using "B:disable3DModels=true" results in all tools and armors to either draw the missing texture checkerboard or simply render as black.

I don't know if this feature is fully implemented yet or if the textures are simply missing. I wasn't able to find any information regarding this that isn't for an older version of MC.

**Comment by covers1624** [comment]
Dont think it is fully implemented yet.

**Comment by HellishINC** [comment]
I'd be willing to create/port some textures if needed.

**Comment by covers1624** [comment]
The textures are made im pretty sure, just need to implement it properly in the baking pipe.

**Comment by brandon3055** [comment]
Will be fixed in the next release.
