### ISSUE TITLE
Draconic Chest Observations

### ISSUE THREAD

**Issue by DemonSeedxp** [brandon3055/Draconic-Evolution#37]
First off I'd like to say I love this mod, it's the most fun I've had in a while playing with a new mod. So thanks for that. Out standing work :+1: 

After playing with the chest for a while I've found some things that are very minor, but thought I'd bring to your attention anyway.

When moving bulk items from the chest to inventory using hotkey Shift+control everything moves as expected, but if you pick up a stack with your mouse press shift then double click another stack of items to transfer them, when the items move the bottom two rows (six slots) of  the crafting grid get filled with stacks of items. Thought it a bit odd.

I've been using the chest to do bulk processing of some ores along with ae2 pushing items in and out and unfortunately the export bus (even at it's lowest setting) can push out items faster then the chest can process them. So what happens is the chest gets completely full of raw ore and stops cooking completely because it has nowhere to put the new ingots. 
I wouldn't call this a bug, but maybe a spot for improvement. just an idea... 
Perhaps it could be made so that right clicking an inventory slot of the chest it would lock it (maybe turn red) and make it so the furnace always has a spot to put it's output, and cant get bogged down and stopped.

**Comment by brandon3055** [comment]
Thankyou for taking the time to post. The shift clicking in general is a little bit weird. I did spend a lot of time trying to get it working as well as possible but i was not able to get it perfect. 

As for the other thing... I didn't really intend the chest for automation. But perhaps i will close the last 5 slots of the inventory to insertion so there is always somewhere for the output to go.
