### ISSUE TITLE
Crash while connecting to a server

### ISSUE THREAD

**Issue by ZeroNoRyouki** [brandon3055/Draconic-Evolution#371]
Hi there,
I've just got another crash from DE while attempting to join a server. MC crash report here : http://pastebin.com/XRaRAu2E

If you need the full FML log just let me know

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.1.2076
* Draconic Evolution version: 1.10.2-2.0.0.89

## Mod List or Mod Pack (include version)

MMD-Dev Server

	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2076-universal.jar) 
	UCHIJA	Forge{12.18.1.2076} [Minecraft Forge] (forge-1.10.2-12.18.1.2076-universal.jar) 
	UCHIJA	actuallyadditions{1.10.2-r62} [Actually Additions] (ActuallyAdditions-1.10.2-r62.jar) 
	UCHIJA	additionalbanners{1.3.0.20} [Additional Banners] (AdditionalBanners-1.10.2-1.3.0.20.jar) 
	UCHIJA	alt{1.06} [Additional Loot Tables] (AdditionalLootTables_1.10.2-1.06.jar) 
	UCHIJA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4b.jar) 
	UCHIJA	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UCHIJA	betteragriculture{1.0} [Better Agriculture] (BetterAgriculture_(MC-1.10)-0.17-dev-build-1.jar) 
	UCHIJA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2080} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2080-universal.jar) 
	UCHIJA	bookshelf{1.3.0.289} [Bookshelf] (Bookshelf-1.10.2-1.3.0.289.jar) 
	UCHIJA	brandonscore{2.1.0} [Brandon's Core] (BrandonsCore-1.10.2-2.1.0.40-universal.jar) 
	UCHIJA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJA	chancecubes{1.10-2.2.1.120} [Chance Cubes] (ChanceCubes-1.10-2.2.1.120.jar) 
	UCHIJA	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCHIJA	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJA	chiselsandbits{12.1} [Chisels & Bits] (chiselsandbits-12.1.jar) 
	UCHIJA	cyclopscore{0.7.7} [Cyclops Core] (CyclopsCore-1.9.4-0.7.7.jar) 
	UCHIJA	colossalchests{1.3.9} [Colossal Chests] (ColossalChests-1.9.4-1.3.9.jar) 
	UCHIJA	commoncapabilities{1.1.2} [CommonCapabilities] (CommonCapabilities-1.9.4-1.1.2.jar) 
	UCHIJA	MineTweaker3{3.0.11} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.11.jar) 
	UCHIJA	wonderfulwands{2.2.0} [Wonderful Wands] (CyanosWonderfulWands_1.10.2-2.2.0.jar) 
	UCHIJA	JEI{3.9.0.246} [Just Enough Items] (jei_1.10.2-3.9.0.246.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	darkutils{1.1.3.71} [Dark Utilities] (DarkUtilities-1.10.2-1.1.3.71.jar) 
	UCHIJA	ElecCore{1.5.311} [ElecCore] (ElecCore-1.9.4-1.5.311.jar) 
	UCHIJA	deepresonance{1.2.2} [DeepResonance] (deepresonance-1.10-1.2.2.jar) 
	UCHIJA	draconicevolution{2.0.0} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.0.89-universal.jar) 
	UCHIJA	poweradvantage{2.3.0} [Power Advantage] (PowerAdvantage_1.10.2-2.3.0.jar) 
	UCHIJA	electricadvantage{2.2.0} [Electric Advantage] (ElectricAdvantage_1.10.2-2.2.0.jar) 
	UCHIJA	enchdesc{1.0.0.0} [Enchantment Descriptions] (EnchantmentDescriptions-1.10.2-1.0.0.0.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.53-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.53-beta.jar) 
	UCHIJA	EnderIO{1.10.2-3.0.1.101_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.101_beta.jar) 
	UCHIJA	modernmetals{0.11.0} [Modern Metals] (ModernMetals-0.11.0.jar) 
	UCHIJA	modularity{0.1.0} [Modularity] (Modularity-[1.10.2]-0.1.0-pre-release-10.jar) 
	UCHIJA	endmetals{1.2} [End Metals] (EndMetals-1.10-1.2-dev-build-1.jar) 
	UCHIJA	energysynergy{1.0.1} [EnergySynergy] (EnergySynergy-1.9.4-1.0.1.jar) 
	UCHIJA	everlastingabilities{1.1.1} [EverlastingAbilities] (EverlastingAbilities-1.9.4-1.1.1.jar) 
	UCHIJA	evilcraft{0.10.11} [EvilCraft] (EvilCraft-1.10.2-0.10.11.jar) 
	UCHIJA	zerocore{1.10.2-0.0.8.0} [Zero CORE] (zerocore-1.10.2-0.0.8.0.jar) 
	UCHIJA	bigreactors{0.4.5.12} [Extreme Reactors] (ExtremeReactors-1.9.4-0.4.5.12.jar) 
	UCHIJA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.9.4-1.2.1.jar) 
	UCHIJA	fluidconverters{2.0.3} [FluidConverters] (FluidConverters-1.9.4-2.0.3.jar) 
	UCHIJA	gravestone{1.5.5} [Gravestone] (GraveStone Mod 1.5.5.jar) 
	UCHIJA	hempfarmer{1.7.2} [HempFarmer] (hempfarmer-1.9.4-1.10.2-1.7.2.jar) 
	UCHIJA	integrateddynamics{0.5.1} [Integrated Dynamics] (IntegratedDynamics-1.9.4-0.5.1.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	ironchest{1.10.2-7.0.9.796} [Iron Chest] (ironchest-1.10.2-7.0.9.796.jar) 
	UCHIJA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.10.2.jar) 
	UCHIJA	lawnmower{1.0.1} [Lawnmower] (lawnmower-1.0.1.jar) 
	UCHIJA	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.7} [Morpheus] (Morpheus-1.10.2-3.1.7.jar) 
	UCHIJA	naturesgift{1.10.2-2011-0.6} [NaturesGift] (naturesgift-0.6.jar) 
	UCHIJA	nethermetals{1.2} [Nether Metals] (NetherMetals-1.10.2-1.2-dev-build-1.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJA	notenoughwands{1.3.6} [Not Enough Wands] (notenoughwands-1.10-1.3.6.jar) 
	UCHIJA	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UCHIJA	novacula{0.0.2} [Novacula Acuta] (NovaculaAcuta-[1.10.2]-0.0.2.jar) 
	UCHIJA	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCHIJA	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCHIJA	p455w0rdsthings{1.9.4-0.0.17a} [p455w0rd's Things] (p455w0rdsThings-1.9.4-0.0.17a.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2c} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2c.jar) 
	UCHIJA	PerfectSpawn{1.4} [Perfect Spawn] (PerfectSpawn-MC1.10.2-1.4.jar) 
	UCHIJA	RandomUtilities{3.1.1} [Random Utilities] (Random Utilities-1.9.4-3.1.1.jar) 
	UCHIJA	randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
	UCHIJA	recstat{1.10.2-2.2.2} [RecStat] (RecStat-1.10.2-2.2.2.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCHIJA	refinedstorage{0.9.4} [Refined Storage] (refinedstorage-0.9.4.jar) 
	UCHIJA	rflux{0.0.1} [RF Lux] (rflux-0.0.1.jar) 
	UCHIJA	rftools{5.21} [RFTools] (rftools-1.10-5.21.jar) 
	UCHIJA	rftoolsdim{4.30beta48} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta48.jar) 
	UCHIJA	solarvillage{1.1.0.15} [Solar Village] (SolarVillage-1.10.2-1.1.0.19.jar) 
	UCHIJA	steamadvantage{2.2.0} [Steam Advantage] (SteamAdvantage_1.10.2-2.2.0.jar) 
	UCHIJA	storagenetwork{1.12.8} [Storage Network] (StorageNetwork-1.9.4-1.12.8.jar) 
	UCHIJA	structuredcrafting{0.1.6} [Structured Crafting] (StructuredCrafting-1.9.4-0.1.6.jar) 
	UCHIJA	tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
	UCHIJA	teslaarsenal{1.5} [Tesla Arsenal] (TeslaArsenal-1.5-dev-build-3.jar) 
	UCHIJA	theoneprobe{1.1.0} [The One Probe] (theoneprobe-1.10-1.1.0.jar) 
	UCHIJA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.203.jar) 
	UCHIJA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.203.jar) 
	Loaded coremods (and transformers): 
DepLoader (BrandonsCore-1.10.2-2.1.0.40-universal.jar)

## Crash report
```
CRASH REPORT HERE
```
http://pastebin.com/XRaRAu2E

**Comment by brandon3055** [comment]
Build 92 on curse should hopefully finally fix this issue.
