### ISSUE TITLE
Energy Core Invalid for Draconic-Evolution-1.10.2-2.0.0.90-universal.jar

### ISSUE THREAD

**Issue by OfficialStamper** [brandon3055/Draconic-Evolution#373]
## Description

Getting Invalid Core message for any Tier Energy Core.

From 1.10.2-2.0.0.82 completely dismantled a 'working' Tier 5 Energy Core.  Updated to version 2.0.0.90.  Rebuilt Tier 5 Core, using the build guide (which now uses 8 Draconium blocks less).  Core will not start saying 'Invalid Core'.

FYI, Advanced stabilisers being used in 3x3 config, as was when previously worked.

## Base information
* Minecraft version:  1.10.2
* Minecraft Forge version: 12.18.1.2073
* Draconic Evolution version: 1.10.2-2.0.0.90

## Mod List or Mod Pack (include version)
...
All the Mods v1.20b with manual update of DE  to above version.

list other mods being used
...
Optifine HD_U_C2

## Crash report
```
CRASH REPORT HERE
```
N/A

**Comment by ilordnightmarei** [comment]
draconium block is not a valid struture block for energy core purple and black square 
http://imgur.com/Ek35e0D my thought is its not recognizing the Draconian block and when u click creative build it deletes  the blocks even tho its correct

**Comment by brandon3055** [comment]
This is fixed in the latest version.
