### ISSUE TITLE
 draconium block not a valid block for energy core multiblock

### ISSUE THREAD

**Issue by ilordnightmarei** [brandon3055/Draconic-Evolution#374]
## Description draconium block is not a valid struture block for energy core purple and black square
http://imgur.com/Ek35e0D my thought is its not recognizing the Draconian block and when u click creative build it deletes the blocks even tho its correct   if i make the smallest one it also is invalid 

## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:2076
* Draconic Evolution version: Draconic-Evolution-1.10.2-2.0.0.90-universal.jar

## Mod List or Mod Pack (include version)
... allthemods modpack 
list other mods being used
... latest draconic evolution and Brandon core
optifine

## Crash report
```no crash
CRASH REPORT HERE
```no crash

**Comment by brandon3055** [comment]
Yup... i know exactly what the problem is without even looking for it.... Will push a new build later today.

**Comment by brandon3055** [comment]
Fix uploaded.
