### ISSUE TITLE
Client disconnect on crossmod interaction with GalaxySpace

### ISSUE THREAD

**Issue by netzgeist** [brandon3055/Draconic-Evolution#375]
## Description
The advanced charm of dislocation is unable to add a waypoint to GalaxySpace's "Deimos" Dimension. The client get disconnected and the posted exception gets printed into the log.

The problem exists exclusively on Deimos from what I can tell so far. Setting a waypoint on Phobos (the prior progression step dimension) works. I doublechecked for conflicting dimension ids and included the dump for you.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1614
* Draconic Evolution version: 102h

## Mod List or Mod Pack (include version)

Infinity Evolved with the following added:
- Galacticraft
- GalaxySpace
- (More mods not affecting Oregen, Biomes and/or Dimensions)

## Crash report
```
http://pastebin.com/raw/EV4wFyfL
```

## Dimensions dump
```
http://pastebin.com/raw/wCaNkDi3
```

**Comment by netzgeist** [comment]
Rebooted the client a few times. It ocassionally works though.

**Comment by brandon3055** [comment]
I am nolonger actively developing 1.7.10. But if i ever do another bugfix build this will be on my list.
