### ISSUE TITLE
Burn event not cancelled when cancelling hit

### ISSUE THREAD

**Issue by Eufranio** [brandon3055/Draconic-Evolution#376]
When the hit/left click event is cancelled using a tool (like Draconic Staff), if the tool has a Fire Aspect enchantment, the target is not hit but it starts burning, and is hit by the fire.

Minecraft 1.7.10
Draconic Evolution 1.7.10 - 1.0.2H
Forge 1.7.10 1614

Modpack: [MagiTech Server Pack](http://www.technicpack.net/modpack/magitech-server-1710.820227)

Also, i'm using MyTown2 to cancell the hit (left click) event.

**Comment by brandon3055** [comment]
I am nolonger working on 1.10 but if i ever push a new build this will be one of the things i fix.

**Comment by Eufranio** [comment]
Thank you anyway, good job!

**Comment by Eufranio** [comment]
😄
