### ISSUE TITLE
[1.10.2] Energy Pylon Stops transfering after area unloads & stops showing xfer particles after server exit/crash...

### ISSUE THREAD

**Issue by Morpheus1101** [brandon3055/Draconic-Evolution#378]
Using build *.92 on the MMD Server .. When exiting the area i have my Mulitblock Power Storage and come back, the energy pylon has stopped transferring energy completely, in order to fix this, i had to break the power cable connected being an Ender Energy Conduit from EnderIO, then break the Pylon and glass, re-place the pylon an glass and then re-connect the power cable an it starts up again quite fine.

**Pt 2

Server crashed whilst i was at my base, came back,  this time the power is still being transfered, but the particles you normally see no longer show, but power count is increasing.

**Comment by brandon3055** [comment]
Ok i fixed the particles stopping and in theory the fix for that may also fix the other issue assuming thats caused by what i thin k its caused by but i was not able to reproduce the issue to test it.
