### ISSUE TITLE
[1.10.2] Breaking Draconic Fusion Crafting injector returns a basic Fusion Injector

### ISSUE THREAD

**Issue by Morpheus1101** [brandon3055/Draconic-Evolution#379]
When placing a Draconic Fusion injector an you break it to move or re-position it, it returns as a Basic fusion injector rather than maintaining a Draconic

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: *.086
* Draconic Evolution version: build *.93

## Mod List or Mod Pack (include version)

MMD Mod Pack v1.4.3

**Comment by UnPure** [comment]
I can confirm this. This is happening for every infusion injector, doesnt matter which tier.

**Comment by ilordnightmarei** [comment]
yep same here

**Comment by brandon3055** [comment]
Oh... well oops... Sorry about that will be fixed in the next build.
