### ISSUE TITLE
No gui for particle generator.

### ISSUE THREAD

**Issue by mrtomwolf** [brandon3055/Draconic-Evolution#380]
When I right click the particle generator I don't get the gui, just the changed texture.

**Comment by Morpheus1101** [comment]
With 1.10+ you dont use the Particle Generator, but the Advanced Core Stablizer to do the multiblock power storage

**Comment by mrtomwolf** [comment]
I'm not trying to do the power storage but rather have some fun with particles =) A very underrated part of DE in my opinion ;)

**Comment by brandon3055** [comment]
Sorry but the particle generator has not yet been re-implemented for 1.10...

**Comment by karolans** [comment]
What about now? :D

**Comment by Zeldri** [comment]
Not seem to be re-implemented sadly :/

**Comment by mrtomwolf** [comment]
I miss my rainbow =(

https://youtu.be/NAG-jHGHpaA?t=6m34s

**Comment by brandon3055** [comment]
The update i pushed last night re implements the particle generator thanks to https://github.com/brandon3055/Draconic-Evolution/pull/1122
