### ISSUE TITLE
[1.10.2] Draconium Block taking rf via Enderio wireless charger

### ISSUE THREAD

**Issue by Morpheus1101** [brandon3055/Draconic-Evolution#382]
Build *.93 of DE and Forge *.075

MMD Dev Modpack

Occasionally when i make a draconium block, it will start taking on rf presumably from my wireless charging station i have setup from EnderIO, in which case i have to turn it back into ingots in order to stop the process. 
![draconic](https://cloud.githubusercontent.com/assets/10524952/18407380/49886256-7752-11e6-86f8-64b5ba1559e5.png)

**Comment by GreatOrator** [comment]
Taking on energy is intended...charged draconium blocks are a part of a few recipes.
