### ISSUE TITLE
[1.10.2] No Dragon Eggs

### ISSUE THREAD

**Issue by UnPure** [brandon3055/Draconic-Evolution#383]
## Description
Killing the Ender-Dragon or Chaos-Guradian doesnt spawn a new Dragon-Egg.
Only the first vanilla dragon is spawning an egg, every other dragon that gets killed doesnt spawn on.
Because the eggs are part of a few crafting recipes, it seems to be a bug.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.1.2076
* Draconic Evolution version: 2.0.0.92

**Comment by brandon3055** [comment]
This sounds like a vanilla or forge bug meaning there really isnt much i can do. If its not fixed soon i may hack in a fix. In the mean time i recommend just cheating an egg for every dragon you kill because it is most definitely a bug.

**Comment by UnPure** [comment]
There is no reason why forge should change the default behavior.
If you get only one egg in vanilla even if you kill the dragon twice, thats ok for forge too! ;)
Its uo to the mods to change that behavior if needed like in Draconic Evolution.
If you need tons of eggs for the crafting stuff, it should be changed to spawn an egg everytime you kill the dragon.

**Comment by GreatOrator** [comment]
What he is saying is a change in forge may have done it.  It already is supposed to spawn a new egg at the portal for resurrected ender dragons, the chaos dragon never did.

**Comment by RealGrep** [comment]
Ah, ok, thanks for the clarification, GreatOrator. :)

**Comment by brandon3055** [comment]
Just a heads up this will be a config option in the next release (on by default)

**Comment by Hi3142** [comment]
Try Dark Utilities, they have a dragon egg recipe.
