### ISSUE TITLE
Server Crash - Draconic grinder next to a pedestal with a sentient sword killing mobs

### ISSUE THREAD

**Issue by ProsperCraft** [brandon3055/Draconic-Evolution#387]
## Description
Draconic grinder next to a pedestal with a sentient sword killing mobs

Whenever the player logs in the server goes down.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 2088
* Draconic Evolution version: Draconic-Evolution-1.10.2-2.0.0.93-universal.

## Mod List or Mod Pack (include version)
...
Allthemods 1.25 modpack - versions in the crash report.
...

## Crash report
```
http://pastebin.com/EbXVVbZ3
```

**Comment by ProsperCraft** [comment]
This isn't a crash, but I saw this one console just now-

http://pastebin.com/DxyhBZ6E

**Comment by brandon3055** [comment]
The last error looks like something between Tcon and blood magic.
As for the crash It looks like Blood Magics "EntitySentientSpecter" is trying to drop a null itemstack on death which is causing the crash. No idea why that has anything todo with my grinder but you may want to post this on the Blood Magic issue tracker.

**Comment by ProsperCraft** [comment]
BloodMagic patched, thank you.
