### ISSUE TITLE
New Types of Zombie are not spawnable

### ISSUE THREAD

**Issue by MakerTim** [brandon3055/Draconic-Evolution#388]
## Description
I was trying to put a zombie from the desert 'husk', a vanilla entity, in to a draconic spawner
and i get a normal zombie spawner as result back
So i was looking at your code, and saw only a handler for Skelletons
https://github.com/brandon3055/Draconic-Evolution/blob/d73596cb82648f0ca0eae9b5a53bd6119a96690d/src/main/java/com/brandon3055/draconicevolution/common/handler/MinecraftForgeEventHandler.java#L214
would it be possible to add husk to the special types?

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.1.2092
* Draconic Evolution version: 2.0.0.94

## Mod List or Mod Pack (include version)
$ ls
1.10.2/
3DManeuverGear-1.10.2-0.10.jar
AppleCore-mc1.10.2-2.0.1.jar
AppleSkin-mc1.10.2-1.0.3.jar
AutoRegLib-1.0-2.jar
Baubles-1.9.4-1.2.1.0.jar
bdlib-1.12.2.8-mc1.10.2.jar
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
BlockDrops-1.10.2-1.0.10.jar
BloodArsenal-1.10.2-2.0.1-11.jar
BloodMagic-1.9.4-2.0.4-56.jar
Botania-unofficial.r1.8-321.jar
BrandonsCore-1.10.2-2.1.0.40-universal.jar
Chameleon-1.10-2.1.7.jar
Chiseled-Me-1.0.jar.bc
Chisel-MC1.9.4-0.0.6.33.jar
chiselsandbits-12.1.jar
ChiselsBytes-1.9.4-0.4.jar
ClayBucket-1.9.4-1.1.jar
CodeChickenCore-1.10.2-2.1.8.79-universal.jar
CompactSolars-1.10.2-5.0.4.328-universal.jar
CompassCoords-1.10.2-3.1.7.jar
ComputerCraft1.80pr0.jar
CustomMainMenu-MC1.10.2-2.0.2.jar
deepresonance-1.10-1.2.2.jar
DefaultOptions_1.10.2-6.1.5.jar
Draconic-Evolution-1.10.2-2.0.0.92-universal.jar
DrawersBits-1.10.2-0.31.jar
ElecCore-1.9.4-1.5.303.jar
EnderCore-1.10.2-0.4.1.54-beta.jar
EnderIO-1.10.2-3.0.1.104_beta.jar
EnderStorage-1.10.2-2.1.3.72-universal.jar
environmentaltech-1.10.2-0.10.3a.jar
ExtraBitManipulation-1.9.4-2.1.0.jar
extrautils2-1.10.2-alpha-1.0.1.jar
ExtremeReactors-1.9.4-0.4.5.12.jar
FastLeafDecay-v11.jar
forestry_1.10.2-5.2.9.242.jar
gendustry-1.6.4.17-mc1.10.2.jar
Graves-1.10.2-b28-universal.jar
Guide-API-1.10.2-2.0.2-45.jar
ic2/
ImmersiveEngineering-0.10-40.jar
industrialcraft-2-2.6.45-ex110.jar
InGameAccountSwitcher-Forge-6.1.1.72.jar
InventoryTweaks-1.61-58.jar
ironchest-1.10.2-7.0.9.796.jar
itemscroller-1.10.2-0.7.0.jar
jei_1.10.2-3.9.0.247.jar
jeibees-0.9.0.1-mc1.10.2.jar
JustEnoughResources-1.10.2-0.5.0.51.jar
k4lib-1.10-1.0.58-universal.jar
'LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar'
Mantle-1.10.2-0.10.4.jar
mcjtylib-1.10-2.0.0.jar
Mekanism-1.10.2-9.1.1.290.jar
MekanismGenerators-1.10.2-9.1.1.290.jar
MekanismTools-1.10.2-9.1.1.290.jar
MKTPackMod-mc1.10.2.jar
MmmMmmMmmMmm-1.11.jar
modnametooltip_1.10.2-1.6.0.jar
morebees-1.10.2-1.0.jar
Morpheus-1.10.2-3.1.7.jar
Morph-o-Tool-1.0-11.jar
notenoughwands-1.9.4-1.3.5.jar
OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
OpenPrinter-1.9.4-0.1.0.3.jar
PackingTape-1.10.2-0.6.0.jar
'Pam'\''s HarvestCraft 1.9.4-1.10.2c.jar'
Ping-1.10.X-1.2.2.B7-universal.jar
PSIonicUpgrades-r1.14.jar
Psi-r1.0-39.jar
Quark-r1.0-55.jar
ReAuth-3.2.jar
RecStat-1.10.2-2.2.2.jar
ResourceLoader-MC1.9.4-1.5.1.jar
rftools-1.10-5.22.jar
rftoolsctrl-1.10-0.0.1beta2.jar
rftoolsdim-1.10-4.30beta48.jar
roots-1.10.2-0.202.0.jar
RTG-1.10.2-4.1.1.2-snapshot-3.jar
SaveJoin-mc1.10.2-1.3.jar
Signals-1.10.2-0.4.3-universal.jar
simpleretrogen-1.10-4.0.1+8.jar
SpiceOfLife-mc1.9.4-1.3.4.jar
StorageDrawers-1.10.2-3.2.7.jar
taiga-1.10.2-1.1.2.jar
TConstruct-1.10.2-2.4.0.jar
theoneprobe-1.10-1.1.0.jar
'Tinkers'\'' Addons-1.10.x-1.0.3.jar'
UniDict-1.10.2-1.5.jar
valkyrielib-1.10.2-0.10.3.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10.2-1.1.8.jar
zerocore-1.10.2-0.0.8.0.jar

## Crash report
404 no crashreport found

**Comment by brandon3055** [comment]
Ahh... this issue is a little confusing to me... You say you are having trouble setting the DE spawner to the new zombie type... in 1.10... That implies that you have one of my spawners... in 1.10... Slight problem with that.... The spawner has not yet been updated to 1.10... Meaning it dose not exist yet... At all... soo... ?...
