### ISSUE TITLE
energy core loses energy on world reload

### ISSUE THREAD

**Issue by gijsc1** [brandon3055/Draconic-Evolution#391]
## Description

Every time i reload my world, energy disapears from my tier 3 energy storage multiblock.
sometimes its a couple million rf, sometimes its a couple 100 million rf.
the setup has one energy pylon + tessarect for input, and a different pylon and tessasrect on a different frequency for output.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: not sure what forge, the forge modloader has 7.10.99.99
* Draconic Evolution version: 1.7.10-1.0.2h

## Mod List or Mod Pack (include version)
...
infinity evolved skyblock version 1.2.0
...

## Crash report
```
no crashes, just disappearing energy.

**Comment by brandon3055** [comment]
pretty sure this isnt an issue on my end. If it was i would have heard about it long before now. What are your tesseracts powering? It sounds like something is breaking while chunks are loading and just accepting a tone of energy on world load. If you can try chunloading the core and everything getting power from it and see if the problem still occurs. Of course there is no grantee it wont still happen while the chunkloaders are loading.

**Comment by gijsc1** [comment]
unhooking all of the power consumers stopped it, so it was probably what you said.
Thank you for replying.
