### ISSUE TITLE
portal stuck loop 1.10.2

### ISSUE THREAD

**Issue by ilordnightmarei** [brandon3055/Draconic-Evolution#392]
## Description stuck in loop teleportation
with draconic  teloportation portal set  in another portal leading in the worse  loop stuck ever
also  can duplicate entire invintory  with graves mod wile doing this if you can kill yourself
also dying will still put you in the loop still

## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:2094
* Draconic Evolution version:2.0.0,100

## Mod List or Mod Pack (include version)
... allthemods modpack v1.30
list other mods being used
...

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
I will add a 500ms (half a second) cooldown in the next version to help fix that but the inventory dupe sounds like an issue with the gravestone mod not taking teleportation into consideration. In any case the cool down should help make it harder if not impossible to perform that dupe.
