### ISSUE TITLE
Draconic Bow doesn't accept Draconic upgrades

### ISSUE THREAD

**Issue by oceth** [brandon3055/Draconic-Evolution#394]
## Description

Draconic Bow doesn't accept Draconic upgrades. It can only be upgraded up to Wyvern upgrades. 

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.1.2089
* Draconic Evolution version: 2.0.0.100

**Comment by brandon3055** [comment]
This will be fixed in the next release.
