### ISSUE TITLE
[1.7.10] Flow Gate doesn't fire a PlayerInteractEvent

### ISSUE THREAD

**Issue by Eufranio** [brandon3055/Draconic-Evolution#395]
I am trying to make a protection file (I have a modded server) for the Flow/Flux Gate, and I can't, because it doesn't fire any events in the server.

https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/common/blocks/machine/FlowGate.java

* Minecraft version: 1.7.10
* Minecraft Forge version: 1614
* Draconic Evolution version: 1.0.2H from Curse

I'm using MyTown2, all other containers can be cancelled, except by the Flow Gate

(Even when changing the values, there is a desync...)

**Comment by brandon3055** [comment]
The block itself is not responsible for firing an interact event. That gets fired by forge so im not sure why you cant cancel it...

**Comment by Eufranio** [comment]
Well, when my client right-click the block, it opens instantly, instead waiting for the server response that check if I can or not open the interface.

**Comment by brandon3055** [comment]
Oh... yea i see thats a client side gui..... Yea that would require a fix on my end... If i ever do another bugfix for 1.7.10 i will fix it. But 1.7.10 is no-longer being developed at this point.
