### ISSUE TITLE
redstone broken for dislocator receptical 1.10.2

### ISSUE THREAD

**Issue by ilordnightmarei** [brandon3055/Draconic-Evolution#397]
## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:2094
* Draconic Evolution version:2.00

## Mod List or Mod Pack (include version)
...allthemods modpack
list other mods being used
...

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
The dislocator receptical is not supposed to be controllable via redstone although it sounds like the block update caused by the redstone state change is deactivating it for some reason... I will look into it.

**Comment by ilordnightmarei** [comment]
o really lol why not make it a feature

**Comment by brandon3055** [comment]
Already done. Will be a feature in the next release. You will also be able to camouflage the receptacle by clicking it with a block of infused obsidian.  
Oh and while powered by redstone its not possible to right click and remove the dislocator.

**Comment by ilordnightmarei** [comment]
i love it \o/
