### ISSUE TITLE
Energy Pylon will not output directly to a TE Tesseract

### ISSUE THREAD

**Issue by Amadeus99** [brandon3055/Draconic-Evolution#4]
An Energy Pylon will input power directly from a Thermal Expansion Tesseract but not output directly to one.  When I say directly, I mean having the Tesseract right next to the Energy Pylon with no conduits/pipes.  Adding conduits/pipes from the Energy Pylon to the Tesseract will cause power to be output without changing any settings on the Tesseract nor moving it.

Draconic Evolution v1.0.0e
CoFH Core 3.0.0B9-71
CoFH Lib 1.0.0B8-50
Thermal Foundation 1.0.0RC1-17
Thermal Expansion 4.0.0B8-23

Tier 6 Energy Core Multi-block.

Let me know if you need any other information.

And just have to say, I really like the look of the Energy Core Multi-block.  =)

**Comment by Labs4077** [comment]
I get the exact same error when you open up the tool configuration screen while moving. If any movement is happening - even if it is the character coming to a stop after keys are released - this crash happens.

**Comment by RoyalBingBong** [comment]
Other things will not work either. Cryo-Stabilized Fluxduct into Tesseract don't seem to transfer a lot of power despite bein infinite. I have to add Ender Energy Conduits to get a decent RF/t rate.
Also machines I placed next to the Energy Pylon are not charging. I tested Ender IO Farming Stations, and SAG Mill and TE Indcution Smelter. RFTools Auto-Crafter seem to work, although slowly.

**Comment by brandon3055** [comment]
This issue was a result of the RF API in de being outdated. It has since been fixed the FTB team just needs to update.
