### ISSUE TITLE
question about enchanting regarding silktouch and a bow bug 

### ISSUE THREAD

**Issue by ilordnightmarei** [brandon3055/Draconic-Evolution#402]
## Description whetever happened to being able to put enchanted books in tools XD and  i find that  theres no silk touch mode for draconic tools  but it is a wip 
also the rf shot shockwave doesn't damage the ender dragon  really want silk touch on  my staff

## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:2093
* Draconic Evolution version:2.0.0.101

## Mod List or Mod Pack (include version)
...
list other mods being used
...

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
I will look into the shockwave issue but as for the enchantability i am waiting for forge hook that will make that possible. But if they take too much longer i will probably end up hacking it in myself (Not an ideal solution)
