### ISSUE TITLE
WAILA crash on Draconic Evolution placed blocks

### ISSUE THREAD

**Issue by thejims** [brandon3055/Draconic-Evolution#403]
## Description
Game crashes instantly when looking at a placed Pestol from the Roots mod, when placed anywhere using Draconic Evolution place feature.  

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 2094
* Draconic Evolution version:    UCHIJA  draconicevolution{2.0.0} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.0.101-universal.jar)

## Mod List or Mod Pack (include version)
All the Mods modpack

## Crash report
http://pastebin.com/cXdFnViH

**Comment by brandon3055** [comment]
That is fixed in the latest build. It was caused by a change to CCL which i needed to implement.
