### ISSUE TITLE
Crash with latest CodeChickenLib

### ISSUE THREAD

**Issue by iamomicron** [brandon3055/Draconic-Evolution#406]
CCL has been updated again by CBProject, and as a result of a [large refactor](https://github.com/TheCBProject/CodeChickenLib/commit/22dfced7b4d85e06a5d1b562c542184b33981368) Draconic Evolution crashes when initializing, assuming the latest version of CCL is installed.

I'm using this version for EnderStorage and NEI, which is how this came about.

* Forge version: ` 1.10.2-12.18.1.2095`
* Draconic Evolution version: `1.10.2-2.0.0.105`
* Newest CCL version: `2.4.1.97`

Crash Log: http://pastebin.com/ygs6meJh

**Comment by covers1624** [comment]
See CCL issue.

**Comment by brandon3055** [comment]
There will be a new DE release soon that works with the latest CCL.
