### ISSUE TITLE
[1.10.2] Recipe Fails for Draconic Core with hardmode=true enabled

### ISSUE THREAD

**Issue by Morpheus1101** [brandon3055/Draconic-Evolution#407]
## Description

The recipe for the Draconic core is the same as the one for in Easy Mode, so when trying to take the core out of hte crafting grid with hardmdoe=true enabled it fails presumably with a recipe conflict thats not showing the changed recipe.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: *.2099
* Draconic Evolution version: 2.0.0d.107

## Mod List or Mod Pack (include version)
MMD Server Pack
![mmd](https://cloud.githubusercontent.com/assets/10524952/19335668/6d383784-9148-11e6-8758-7a3ed2e79f7c.png)

**Comment by brandon3055** [comment]
I just checked to be sure and they are two different recipes. Is hard mode enabled on both the client and the server?

**Comment by Morpheus1101** [comment]
I will check tom using the latest vers of BC & DH we have to verify if this still exists

**Comment by brandon3055** [comment]
Closing this because the issue was resolves. For anyone else having the same issue make sure you dont have a DraconicEvolution.cfg file in the config file. It should be in config/brandon3055
