### ISSUE TITLE
Draconic Chest missing

### ISSUE THREAD

**Issue by Ebonhunter** [brandon3055/Draconic-Evolution#409]
Did something happen to the Draconic Chest block? I don't see it in the list of items (using JEI in 1.10.2)

![full draconic mod](https://cloud.githubusercontent.com/assets/22824548/19365306/2889b96a-9160-11e6-9884-b5de6b73c59f.JPG)

**Comment by covers1624** [comment]
I.10 is a complete rewrite. Ther are still some things missing. They will come back, don't worry.

**Comment by Ebonhunter** [comment]
OK no worries, I see that now (other items from 1.7.10 that aren't present). I love this mod, the theme, the utilities, and I can't wait for the updates. Keep up the great work!
