### ISSUE TITLE
Unable to see Ars Magica 2 Occulus GUI while wearing Draconic Evolution Armor

### ISSUE THREAD

**Issue by Remadon** [brandon3055/Draconic-Evolution#414]
Hello,

Not really sure where the issue lies in regards to Ars Magica 2 or Draconic Evolution, or perhaps somewhere else. I *assume* that something with the on-screen GUI drawn by Draconic Evolution has something to do with the Occulus GUI not showing up correctly, but I'm just speculating at this point.

Info about my install:
MC: 1.7.10
Forge: 10.13.4.1614
Draconic Evolution: 1.0.2h
Ars Magica 2: 1.4.0.009
Animation API: 1.2.4
Brandon's Core: 1.0.0.12

Below is a screenshot, The issue does not occur when not wearing Draconic Evolution Armor.

![screenshot](https://cloud.githubusercontent.com/assets/9089520/19423289/ba6782ac-93d3-11e6-963d-81243d383418.png)

I will also be posting this on Ars Magica's Bug Tracker here: (Same Title)
https://github.com/Mithion/ArsMagica2/issues

**Comment by brandon3055** [comment]
I am no longer actively developing for 1.7.10. But i will add this to my list of things to look at if i ever push another 1.7.10 bugfix.
