### ISSUE TITLE
Draconic Infusion Ritual Does Not Work

### ISSUE THREAD

**Issue by DFliyerz** [brandon3055/Draconic-Evolution#417]
It simply doesn't work, the heart just gets blasted away and that's that.

**Comment by Micro-Steve** [comment]
Your still using the old method.  With 1.10.2 you will use the new infusion process.  I believe on the Curse site there is a video sowing how the Infusion process works.  You will have to scroll down a bit.

**Comment by brandon3055** [comment]
Correct in 1.10.2 it is a fusion crafting recipe. Look in the information tablet for info.
