### ISSUE TITLE
Crash when Fusion Crafting

### ISSUE THREAD

**Issue by Medusalem** [brandon3055/Draconic-Evolution#418]
When Fusion crafting advanced Discolation Porter the client crashes.

playing  on  Server or client only is irelevant!

Crash log can be found here:

http://pastebin.com/iDq7jarb

**Comment by brandon3055** [comment]
Update Code Chicken Lib your version is way outdated. Also CCL is no longer an auto downloaded lib. Its a regular mod you have to download off curse. 

Now to go find out why it did not detect that you were using an old CCL version and give you the missing/outdated mods message on game load...

**Comment by Medusalem** [comment]
Test

**Comment by TheDeKay** [comment]
I do have this Issue with the latest version of CodeChickenLib. Which is only 3 days older than the latest version of Draconic Evolution. So I have no Idea what you call way old.

**Comment by brandon3055** [comment]
Looks like @covers1624 needs to update curse. Try the latest version here: http://chickenbones.net/maven/codechicken/CodeChickenLib/

**Comment by TheDeKay** [comment]
Has to do something with multi presence of CCLib.
Does work if I only put CCCore/CCLib/BrandonsCode and Draconic Evolution.
That should also be why it doesnt show an error on load.

**Comment by brandon3055** [comment]
Not sure what you mean there should only ever be 1 version of CCL installed and it should be in the mods folder

**Comment by Morpheus1101** [comment]
The older CCLib wasnt an actual mod so to speak and the new one is registerd as a mod, so hence why Forge dosent detect there being multiples on load and causes issues

**Comment by Medusalem** [comment]
<As far as i know this can be closed! Everything is working fine now!
