### ISSUE TITLE
end crystals not removeable, dragon heart does not drop 

### ISSUE THREAD

**Issue by acidjazz** [brandon3055/Draconic-Evolution#419]
This is on allthemods from v1.38b to v1.39 now

the crystals are not able to be damaged anymore, even block breakers and pistons do nothing.
also if i summon the dragon the vanilla way and kill him even w/ the health regen, no dragon heart drops.
the animations of the dragon being healed have also stuck at the top of x0, z0, even though he's dead

![image](https://cloud.githubusercontent.com/assets/967369/19714324/23d6590e-9b02-11e6-8906-101fd03dd53a.png)

**Comment by brandon3055** [comment]
That sounds more like another mods issue. I dont in any way modify the vanilla dragon than forcing it to spawn an egg every time it dies and dropping the heart. Nothing i do could cause what you are describing.

**Comment by acidjazz** [comment]
@brandon3055 any suggestion/idea on which mod it might be? have you run into issues in the past of other mods messing with this?

**Comment by Morpheus1101** [comment]
Have you or anyone edited the End or tried to reset The End at all ?

**Comment by acidjazz** [comment]
I have, and we also upgraded allthemods to 1.40 and ran it w/out sponge, worked fine. 

Put sponge back, end crystals wouldnt blow up again, dragon wont drop hearts.  I think it might be sponge

**Comment by Morpheus1101** [comment]
Then id say its a sponge issue an not DE ... The End also requires more then jsut del the world folder of it to reset, but it seems clear that the issue isnt in DE but sponge.

**Comment by acidjazz** [comment]
@Morpheus1101 agreed
