### ISSUE TITLE
Crashing and Obliteration Mode

### ISSUE THREAD

**Issue by Straightenup** [brandon3055/Draconic-Evolution#42]
I am currently playing on FTB Infinity. When you open up the Draconic tool menu, if you have other items that take charge in your inventory, the game will often crash. Also, the obliteration mode on the Draconic Pickaxe does not work. I have checked the config and the block id's are listed. Thanks for reading this!

**Comment by brandon3055** [comment]
That bug was fixed a while ago. 

You now place blocks you want to destroy in the config gui (The actual block. e.g. stone for stone not cobble for stone)

Also note that infinity downgraded to 1.0.0e in update 1.3.0
