### ISSUE TITLE
[1.10.2] Mob Grinder only works intermittently

### ISSUE THREAD

**Issue by FnordMan** [brandon3055/Draconic-Evolution#422]
version 2.0.1.124

subject line says it all, was doing a few wither kills with the mob grinder only to be surprised that the second wither (spawned shortly after the first died) didn't immediately die like the first. 

Also noticed the same thing with the wither spawner I had running. The skeletons would build up a lot then get mass slaughtered then build up more, etc..

**Comment by Morpheus1101** [comment]
I have used the Grinder from DE in 1.10.2 quite heavily and found it works 100% of the time .. it is never an instant kill as soon as a mob spawns, but i can assure you i have used it to kill, withers, wither skels, ghast, enderman etc etc all successfully

**Comment by FnordMan** [comment]
I never said it didn't work, just that there's very large pauses in there. in 1.7.10 the spawner always killed withers as soon as they spawned.

**Comment by Morpheus1101** [comment]
This works as intended, in the case of withers it used to do it faster in 1.7.10 due to how things were, but isnt the case now in 1.10.2

**Comment by FnordMan** [comment]
So is it the case for only withers? Because it also lets a stupid amount of normal mobs build up  before killing them as well. Like potentially seriously lag generating amounts.

**Comment by brandon3055** [comment]
How long dose it delay between kill cycles? The way it works is it scans the kill area for mobs, Kills any it finds then waits 5 seconds and scans again. This is for the sake of efficiency because scanning an area that large can be a bit lagy if you do it too often.

**Comment by FnordMan** [comment]
In my experience it's been around 20-40 seconds, usually averaging about 30. 

Tickrate's good on the thing, getting a solid 20 TPS according to forge.

**Comment by FnordMan** [comment]
I've got an idea that could work for everyone. Could you make it scan immediately after being turned on? (though the ~30 second timeout when left on would also need fixing)
