### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by xXJamieXx** [brandon3055/Draconic-Evolution#423]
Brandon's Core Version: 2.1.1.59
Draconic Evolution Version: 2.0.1.124

Crash: http://pastebin.com/qNqKGuv0

**Comment by GreatOrator** [comment]
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer

Make sure you only have one copy of the code chicken LIB  looks like you are trying to load two different versions

**Comment by brandon3055** [comment]
Yea that could be the issue. Check that you dont still have an old version of CCL in mods/1.10.2

**Comment by xXJamieXx** [comment]
Ahh thank you. Seems that I missed the whole thing about removing it from the 1.10.2 folder in the mods folder. Thanks again, now my modpack can be updated lol 👍
