### ISSUE TITLE
Crashing while loading with newest DE

### ISSUE THREAD

**Issue by Charles12875** [brandon3055/Draconic-Evolution#424]
Game crashes while loading only with the newest update of DE. All other core mods are updated.
Log says something about rendering issue with the Potentiometer. Any help with this would be greatly appreciated!

http://pastebin.com/aHB8wQAF

**Comment by brandon3055** [comment]
You have 2 versions of CCl installed. Delete the old version in mods/1.10.2 and make sure the new version is in mods NOT mods/1.10.2
