### ISSUE TITLE
[1.10.2] Celestial Manipulator crashing clients in SMP

### ISSUE THREAD

**Issue by Gepett0** [brandon3055/Draconic-Evolution#426]
Hi,

A mate and me are playing a private modpack.
Everytime one of us is using the manipulator to change daytime, the other person crashes.
No animations are shown for him.
Changing weather works fine

Crahs report:
http://pastebin.com/vsqE76Hh

Forge: 2114
DE:  2.0.1.126
BC: 2.1.1.60
CCC: 2.3.5.91
CCL: 2.4.3.124

**Comment by brandon3055** [comment]
Oh darn i thought i pushed a fix for that... Turn out i didnt. Will have a fix out soon.
