### ISSUE TITLE
Flux capacitor cannot charge EIO/AE2 items.

### ISSUE THREAD

**Issue by GuntherDW** [brandon3055/Draconic-Evolution#428]
The Flux Capacitor has issues charging items from one particular mod to the next.

Mekanism blocks/items charge just fine in your inventory, while the dark steel armor or other items from EIO don't. You can use the capacitor banks or even the wireless charger to charge the flux cap though.

The AE2 items like the wireless charger also doesn't get a charge from the flux cap.
AE2 Supports Tesla as well as Forge Energy, and was asked by their devs to ask here about the issue as well.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2527#issuecomment-257143031

Versions:
 Minecraft : 1.10.2
 Forge : 12.18.2.2116
 BrandonsCore : 2.1.1.60
 Draconic Evolution : 2.0.1.126

**Comment by brandon3055** [comment]
This issue is as mentioned in the issue you linked because i dont yet support the new forge capability system and the mods that are having issues are moving away from RF. Capability support should be coming fairly soon™
