### ISSUE TITLE
Draconic Evolution Server Balance

### ISSUE THREAD

**Issue by Ryuhouji** [brandon3055/Draconic-Evolution#429]
There's no way to nerf the items int he mod for a server. I'd like to see a feature that causes draconic evolution to use the server config instead of local when connecting. Other mods have this functionality, I've tried to do this, and it doesn't work. There IS a balance file, but this does not sync to clients. Using FTB Infinity Evolved 2.6.0 (+1 mod, iguanas tinker tweaks)

Screenshot: https://puu.sh/s38Lr.png , https://puu.sh/s38Oy.png
I have Wyvern armor and tools set to 500kRF capacity, and Draconic set to 1mRF capacity, but this change is not reflected in clients. Information would be appreciated.

**Comment by MaDmaxwell311** [comment]
I have the issue as well, I edited other vales as well, my file can be seen here: https://gist.github.com/MaDmaxwell311/64a13df6092ddf7c55d174b39d3c1767

NOTE: I am using a custom modpack, modlist here: https://gist.github.com/MaDmaxwell311/64a13df6092ddf7c55d174b39d3c1767

**Comment by brandon3055** [comment]
The balance config will only work properly if it is set both client and server side.

**Comment by ktole1999** [comment]
so if players are using a modpack for your server those files should sync on connection.

**Comment by Ryuhouji** [comment]
What I want is for the balance file on the server to be synced automatically on the client side. Most of the other core mods in the modpack do this already.

**Comment by ktole1999** [comment]
i didnt think mods had control over that. server syncs the files with client on connection. if no sync then you have issues and client/server crashing.

**Comment by Ryuhouji** [comment]
RFtools, EnderIO, BigReactors, and Thermal Expansion all sync client configuration to match server. There are others that do it as well. The balance file for Draconic Evolution Does somewhat work as it should, but if a client's balance file is different from the server one, their tools still show the data they have in their balance file. For example, I have wyvern tools nerfed to 500k max capacity. Someone could set their wyvern tools to have 50million capacity, but they'll only have access to 500k of it, and it glitches out. I would like for brandon3055 to add sync support like the other mods have had for years.

**Comment by covers1624** [comment]
Ok, let me clear up a few things here, The server ONLY syncs Block and item id's (in 1.7, there are others in 1.8+) to the client, thats final. Any other syncing of configs is handled directly by the mod in question and forge has no control over. Does DE's Balance config need syncing, yes. Will it be done for 1.7, Probably not, but if brandon does ever do a final 1.7 release this will probably be one of the fixes.

**Comment by Ryuhouji** [comment]
I know that it is up to each mod individually, hence why I posted this here, instead of in the forge forums. As much as something like this mod can impact gameplay, you'd think the author would see it being an issue, but apparently not.

**Comment by ktole1999** [comment]
thanks for info. i always thought it was server that controlled file sync
