### ISSUE TITLE
Draconic Armor Causes Black In-Game Guides

### ISSUE THREAD

**Issue by ariecos** [brandon3055/Draconic-Evolution#430]
When wearing the draconic armor, some in-game guides, such as the Circle Magic book from Witchery as well as the Oculus from Ars Magica are rendered black and unreadable. Please see images at the link below.

http://imgur.com/a/vWo4O

EDIT: It would seem the GUI is doing this. By marking the GUI as hidden (sans the tool tips for the draconic tools), these issues go away entirely.

**Comment by brandon3055** [comment]
I will add this to my todo list next time i release a 1.7 build.
