### ISSUE TITLE
1.7.10 v1.0.2h Chaos Guardian not spawning a portal

### ISSUE THREAD

**Issue by gletsch** [brandon3055/Draconic-Evolution#432]
Hey!

Title should be telling all the information needed. Is this on purpose? Maybe the FTB Wiki's arent up to date and the whole portal thing on chaos islands has been disabled?
Some information on this behaviour would be nice. Thanks.

PS.: Also no egg and only one heart.

**Comment by brandon3055** [comment]
The chaos guardian dose not spawn a portal and dose not drop an egg. And yes it is only supposed to drop 1 heart the main prize is the chaos shards.

**Comment by gletsch** [comment]
Thanks for the reply! It then seems that the FTB Wiki needs an update ;)
