### ISSUE TITLE
Making Draconic Blocks out of glass

### ISSUE THREAD

**Issue by FireIron24** [brandon3055/Draconic-Evolution#433]
I've found this bug in FTB Infinity Evolved 1.6.1 (Mc1.7.10) by using the Portal Gun to move a glass block on top of an energy pylon.
What happens: It forms an functional energy Pylon + core, but when you right click the energy core to change the transmit direction, it turns into an Draconic Block

Hope you understand

![2016-11-03_16 51 09](https://cloud.githubusercontent.com/assets/23241647/19973613/ff2613f2-a1e5-11e6-8b58-9bf82b5e121c.png)
![2016-11-03_16 51 16](https://cloud.githubusercontent.com/assets/23241647/19973615/ff291e08-a1e5-11e6-96a8-9fc1c69f19e3.png)
![2016-11-03_16 51 20](https://cloud.githubusercontent.com/assets/23241647/19973614/ff28db82-a1e5-11e6-8ab1-9bd70f18918e.png)

Flo.

**Comment by brandon3055** [comment]
Are you on a server? And if so are you running a plugin system like cauldron/thermos etc.

**Comment by FireIron24** [comment]
I've tested this on my own server (standard FTB Infinity 1.6.1 config) and in Single Player.
The only differences is that on a Server the block automatically turns into an Draconic Block without right clicking it.

If you need something tell me.
