### ISSUE TITLE
Advance Dislocator teleporting other players

### ISSUE THREAD

**Issue by SpellMaster20** [brandon3055/Draconic-Evolution#434]
Hello on my friends server we tried to do the teleportation of another player by the shift + left/right click (Sorry I can't remember off the top of my head which one) whilst they were also crouching and we got the error of 'You need a more advance dislocator to do that' message yet we had the Advanced dislocator. Sorry if this is something you are aware of I did a search on "Advance Dislocator" and nothing came up. Is there another tier of Dislocator that we are unaware of or is this feature not implemented yet? Other than that I love Draconic Evolution so much and the staff of power can very easily cut through red matter armor at max upgrades ^_^

Cheers Spell_Master

**Comment by SpellMaster20** [comment]
I should add that this is on 1.10.2 version of the mod in the pack of Wyldlife but we are changing and restarting to FTB lite 1.10.2

**Comment by brandon3055** [comment]
Oh thanks for letting me know about that. It will be fixed in the next release.
