### ISSUE TITLE
Crash During Chaos Dragon Fight

### ISSUE THREAD

**Issue by Darkosto** [brandon3055/Draconic-Evolution#435]
I'm getting a crash when heading over to the Chaos Dragon Island, I assume it has to do with Chaos Crystal respawning since I had already destroyed the first round of them:

http://pastebin.com/HQvS986H

Forge: 2112
MC: 1.10.2
Mod: 2.0.2.134

Thank you!
Darkosto

**Comment by brandon3055** [comment]
Oh... Sorry about that. I was testing some stuff using the chaos crystal renderer and it seems i kinda... accidentally broke it... just a bit... Actually a lot...

I just pushed a fix to curse.

**Comment by Darkosto** [comment]
Haha, no worries! Thanks for the fix :D
