### ISSUE TITLE
Celestial Manipulator randomly refusing to run

### ISSUE THREAD

**Issue by HyperionNexus** [brandon3055/Draconic-Evolution#438]
Every so often the Celestial Manipulator says "Already Running!" even though it finished the last operation. I have been unable to find a way to reproduce it, all I know is that it stops working randomly.

Version: 1.10.2-2.0.3.137

**Comment by brandon3055** [comment]
Interesting... What do you have to do to get it working again?

**Comment by HyperionNexus** [comment]
Breaking/replacing is one way. Another way is stopping rain (whether it's from another Celestial Manipulator or /weather clear).

I also found a way to reproduce it. 
1. Start rain/storm
2. Advance time sun rise, mid day, etc
3. Attempt to switch back to weather tab, change time, etc and it'll say "Already Running!"

**Comment by brandon3055** [comment]
Ok i found the issue. Will be fixed in the next release.
