### ISSUE TITLE
Pickaxe Enchantments

### ISSUE THREAD

**Issue by Cathillach** [brandon3055/Draconic-Evolution#439]
Hey

Been loving the new 1.10.2 mod so far. The only thing I would like to change so far is the ability to apply silk touch enchantment to tools. Either through fusion crafting or through vanilla methods. I have an awesome ore processing and fortune 4 block breaker in my base and want to just silk touch everything and send it back.

Cheers,
Cathillach

**Comment by MachinegunMarty** [comment]
Wanted to add that enchants don't work on the Draconic staff of power either.

Tried looting 3 and fortune 3. 

Soul bound Enchantment does work though.

I'm making the enchantment books in the ender IO enchanter and try to add them with a vanilla anvil.

Brandon3055 could you confirm that enchantment can't be applied to your tools atm ?

Then i don't have to try different ways and know that it just isn't possible atm.

If i find a way i will post that here. 

Thanx in advance !

**Comment by brandon3055** [comment]
This is correct. I am currently waiting for forge to add a hook that will allow me to make the tools enchantable via vanilla methods.

**Comment by brandon3055** [comment]
Looks like forge is adding the hook to 1.11 but 1.10 so i will be adding the hook myself in the next release.
