### ISSUE TITLE
Split Dragon Egg Respawn in a seperate mod

### ISSUE THREAD

**Issue by UnPure** [brandon3055/Draconic-Evolution#440]
Hey there.
I would like to know if there is any chance to see the feature that makes it possible to get a new egg after killing a new dragon in a seperate mod. Also it would be cool if the harder recipe for the crystals would be part of it.
I'm asking because i'm currently creating a modpack in which DE wouldnt fit.
But i still need to have a way to get a dragon egg after killing a new ender dragon.
So maybe it would be possible to take the code from DE and create a small mod with only the small feature in it?

**Comment by covers1624** [comment]
Its a possibility, but @brandon3055 will have to be the one to decide this.

**Comment by brandon3055** [comment]
Sure why not!

**Comment by brandon3055** [comment]
Done! https://minecraft.curseforge.com/projects/dragon-tweaks

**Comment by UnPure** [comment]
Thank you very much! :)
