### ISSUE TITLE
There are a lot of typos in the Information Tablet.

### ISSUE THREAD

**Issue by stefan7080** [brandon3055/Draconic-Evolution#442]
![typo 1](https://cloud.githubusercontent.com/assets/23392891/20204045/87856248-a7cc-11e6-8e6d-9bd1c2af4287.png)
![typo 2 and 3](https://cloud.githubusercontent.com/assets/23392891/20204046/87871728-a7cc-11e6-9150-086d110ecd6d.png)
![typo 4](https://cloud.githubusercontent.com/assets/23392891/20204049/878dab9c-a7cc-11e6-90d8-6bd13fb75ac4.png)
![typo 5](https://cloud.githubusercontent.com/assets/23392891/20204047/878cbff2-a7cc-11e6-87ad-e15c3a6e781d.png)
![typo 6](https://cloud.githubusercontent.com/assets/23392891/20204048/878dc118-a7cc-11e6-8893-2922c47d4c49.png)
![typo 7](https://cloud.githubusercontent.com/assets/23392891/20204050/879362ee-a7cc-11e6-87b4-55cef383c92b.png)
![typo 8 and 9](https://cloud.githubusercontent.com/assets/23392891/20204051/879db906-a7cc-11e6-9a45-1a4089ac1cb0.png)
![typo 10](https://cloud.githubusercontent.com/assets/23392891/20204052/879e3b06-a7cc-11e6-8a19-085f962b23bb.png)
![typo 11](https://cloud.githubusercontent.com/assets/23392891/20204053/87a7937c-a7cc-11e6-95b6-b64f0946037d.png)
![typo 12](https://cloud.githubusercontent.com/assets/23392891/20204054/87a7d454-a7cc-11e6-9671-ba09d231df53.png)
![typo 13 and 14](https://cloud.githubusercontent.com/assets/23392891/20204055/87aa416c-a7cc-11e6-95dc-9baf593e07df.png)
![typo 15](https://cloud.githubusercontent.com/assets/23392891/20204056/87ad9560-a7cc-11e6-9036-9b9a139c7689.png)

Some pages have dots and the end of sentences, some don't.
It wouldn't surprise me if I didn't notice some mistakes. I am not English myself.
These aren't all the pages, just the ones I read until I got bored :)

Have fun finding the mistakes and correcting them.

P.S. <3 the mod. Still my favorite mod after all these years!

**Comment by GreatOrator** [comment]
You can always do a pull request on the lang files to correct it

**Comment by covers1624** [comment]
No, the info tablet has changed and the data is not stored in Lang files, @brandon3055 will have to explain how he can create a pull request.

**Comment by brandon3055** [comment]
I will fix these when i get around to it. As for pull request. You could theoretically make a pull request to update the raw xml on the Project Intelligence repo but that would be very painful. When i get around to finishing this there will be an in game editor which anyone can use to update/add documentation.

**Comment by brandon3055** [comment]
A lot of these were fixed in a recent pull request.
