### ISSUE TITLE
Pedestal Tier Too Low

### ISSUE THREAD

**Issue by lawrencekellie** [brandon3055/Draconic-Evolution#443]
This is a brand new install of All the Mods, and this error occurs when I try to use the Fusion Crafting. I have the Core one block above the floor (that one block is gone), and the Basic Fusion Crafting Injectors are in a "T" formation with the bottom of the "T" resting on the floor. The "T" is made up of four injectors, and I have set them one and two blocks away from the Core. Same error occurs with both locations.

After right-clicking all the items needed for the crafting, when I open the GUI for the core, this message is at the bottom of the GUI.  I am trying to craft an Advanced Dislocator. I also tried crafting Awakened blocks, and same thing happened.

It appears this situation hasn't been reported before, as their is no Google entries about the problem.

Lawrence

**Comment by covers1624** [comment]
Don't quote me, but I think you may need a higher teir of crafting injector.

**Comment by lawrencekellie** [comment]
Ahhh. Thank you

**Comment by SpellMaster20** [comment]
Yeah if you have JEI or similar installed as well it will say something like crafting tier Wyvern or Draconic. This means the Injectors for the items to be on must be at the infused level or higher (Chaos being the highest)
