### ISSUE TITLE
[1.7.10] Wither Skeletons not dropping their skulls

### ISSUE THREAD

**Issue by DaRandom** [brandon3055/Draconic-Evolution#445]
I'm playing on FTB Infinity Evolved (Expert) hosted on a server with Iguana Tinkers' Tweak and a downgraded version of ExtraTiC, and I've noticed that the Mob Grinder doesn't make the Wither Skeletons drop their skulls upon death. No errors AFAIK in the console.

The Mob Grinder is set up in the Last Millennium and I am spawning them with the Stabilized Mob Spawner, shortly teleporting them (using the Dislocator Receptacle) into a cage where the Grinder kills them. Tested in a creative testing world in Singleplayer on normal mode as well, no difference.

Is this perhaps a mod conflict issue?

**Comment by GreatOrator** [comment]
Check the config settings for tinkers tweaks, iirc there is an option related to mob skulls that when enabled interferes with DE's mob grinder (had the same issue in my modpack)

**Comment by DaRandom** [comment]
@GreatOrator Thank you.
It would seem the option for B:MobHeads needed to be false found inside the Modules.cfg. [Pastebin, found at line 13-14](http://pastebin.com/z6wiThuE)

Much appreciated, this can be closed as it has been resolved. :)
