### ISSUE TITLE
Draconic Infusion drains all charge from items

### ISSUE THREAD

**Issue by SpellMaster20** [brandon3055/Draconic-Evolution#446]
Hey I've noticed that when infusing wyvern tier items into Draconic tier the items loose all the charge in them. Is this intentional or a bug? As loosing 4 Mrf can be awkward when you forget to drain them first.

Cheers Spell_Master

**Comment by brandon3055** [comment]
Ahh.. yea i never go around to adding a custom recipe to handle that. I will do that in the next release.
