### ISSUE TITLE
1.10.2 - Tier 8 energy core doesn't show activity in gui but seems to be working

### ISSUE THREAD

**Issue by DoomSquirter** [brandon3055/Draconic-Evolution#447]
Draconic-Evolution-1.10.2-2.0.3.137-universal
This is on a server, SMP

Tier 8 energy core seems to be working, I see particle effects going in/out but the gui shows a fixed amt of energy inside (74.526 Million rf) but no transfer rates, even if I disconnect the output side.  

It is quite near my T7 but I've shift clicked the pylons to ensure both pairs of pylons are pointing to appropriate cores as they should be.  

T7 working just fine.  

Also, when all my power is going through T7, I see more energy throughput than when I'm pushing through T8, which then puts back into T7, meaning it's losing some energy somewhere.

**Comment by DoomSquirter** [comment]
just want to update this.

So, beforehand I double checked particle effects and they were all pointing to correct energy cores

we had a server reboot tho and suddenly they are going to other cores, so maybe that's what's going on here, not that T8 has an issue, but that they aren't redirecting to other energy cores and visibly showing same.

After server reboot, and shift clicking pylons again, things seem to be working properly, tho it might still be an issue cause of reason already specified.

**Comment by PWTordenskiold** [comment]
See same behavior with T7 Energy Core. Related to leaving chunk/render distance and returning.  If relevant, using Chunk Ward from Extra Utilities for chunk loading.
Restarting or breaking energy pylon for input/output and rebuilding, restores correct GUI.

**Comment by brandon3055** [comment]
I have so far nor been able to reproduce this issue. Remember that shift clicking a pylon dose not just show you what core it is connected to it also changes what core it is connected to. Meaning if you shift right click it and the particles show that its connected to the wrong core thats because you just switched it to that core by shift right clicking it.
