### ISSUE TITLE
Not an issue, I'm sure this is a balance issue really, 1.7.10 version vs 1.10.2

### ISSUE THREAD

**Issue by DoomSquirter** [brandon3055/Draconic-Evolution#448]
Haven't done chaotic since that's not implemented yet, but just wanted to put my 2 cents in.

In 1.10.2, crafting upgrades into the different armor/tools, seems a max it all out affair, 3 levels now, 4 levels with chaos I assume.

In 1.7.10 however, you had the ability to choose the best loadout and make it specific to how you wanted to use it, per situation if need be.  shields, rf, or shield regen, with a set # of upgrades available.  Max one out at the peril of not giving enough attributes to one of the other potential upgrades.  

So now, essentially, everyone that sets up draconic armor or tools, will all just max it out and there won't really be any kind of thought process going into it which seems to me a step backwards?

Not an enormous fan of the upgrade infusion mechanism of 1.10.2 either but it is pretty.  This isn't a ding on your work, just an honest opinion.  Please don't take offense at my opinion.

**Comment by brandon3055** [comment]
I welcome your opinion. And i agree the old system did make it a bit more interesting but behind the scenes it was a complete mess so i decided to scrap it and try something new.
The armor itself still needs work. Currently i think its a bit op and the speed/jump boost upgrades are broken. I plan to re write and re balance it when i re write the chaos guardian.
