### ISSUE TITLE
Crash in Draconic Tablet - revival ritual

### ISSUE THREAD

**Issue by sciguyryan** [brandon3055/Draconic-Evolution#45]
This is with the latest RC (RC2).

http://pastebin.com/63ii24xZ

**Comment by brandon3055** [comment]
Thanks i forgot to take into account the possibility of wildcards in crafting recipes. I have fixed that but as i wouldn't consider it a game breaking bug and i will no doubt be posting a new version soon anyway i am not going to push a new RC for that bug.
