### ISSUE TITLE
1.10.2 Energy core losing energy after server reboot

### ISSUE THREAD

**Issue by Korvynus** [brandon3055/Draconic-Evolution#452]
Versions:
Draconic-Evolution-1.10.2-2.0.3.137-universal
BrandonsCore-1.10.2-2.1.1.61-universal
forge-1.10.2-12.18.2.2125-universal

Issue:
Everytime after a server reboot, my energy core is losing all of his energy...

Screenshot:
https://dl.dropboxusercontent.com/u/11797022/mc/screenshots/2016-11-20_20.30.32.png

Logs:
https://dl.dropboxusercontent.com/u/11797022/mc/logs/fml-server-latest.log

**Comment by Korvynus** [comment]
I did more test. I made a fresh new game in singleplayer with creative mode, put down a energy core tier 4, filled it up at full capacity, then saved and exit the game. After game restart and joined my newly created game, the energy core lost around 1/4 of it's capacity with nothing that may drain his energy.

Here is how the setup looks:
https://dl.dropboxusercontent.com/u/11797022/mc/screenshots/2016-11-21_17.26.33.png

As you can see, there is absolutely nothing that may interfer with the energy capacity of the energy core.

**Comment by Medusalem** [comment]
What's the source or the way you get energy in?

**Comment by Korvynus** [comment]
Well... in my singleplayer game, I just hooked up a Creative Energy Cube from Mekanism directly to the Energy Pylon, once the Energy Core was fill, I broke the Creative Energy Cube. Just to be sure that nothing may interfer with the Energy Core.

Otherwise, it's a bit more complicated in my survival server...

**Comment by kulflame** [comment]
I have a similar issue but I lose all my power on server reboot.

**Comment by brandon3055** [comment]
@Korvynus can you please repeat your singleplayer test using the Creative RF Source from draconic evolution and see if you get the same results.

**Comment by Korvynus** [comment]
Ok I think I found the issue. It's either something related to the Energy Pylon in withdraw mode or something related to the RF Api interactions with other mods. No matter wich mods I use to transport the RF energy from the Energy Pylon to something else, after a game reboot, the Energy Core lose his energy. Even if I only put down a cable with nothing else connected to it except the Energy Pylon in withdraw mode.

**Comment by brandon3055** [comment]
Hmm.. maby wait for my next release which adds support for the forge energy system. That may fix the issue. If it dose not let me know. 
I will hopefully be releasing the next build by tomorrow at the latest.
