### ISSUE TITLE
Unable to start Minecraft 1.10.2 after updating Draconic Evolution

### ISSUE THREAD

**Issue by Ther0011001100** [brandon3055/Draconic-Evolution#453]
I updated all the mods in my pack and everything worked fine until i updated Draconic and thats when it crashes on startup. My mod pack runs fine without it and it is the only mod throwing exceptions. 

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  LoadingPlugin (Quark-r1.0-60.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-6.jar)
  IC2core (industrialcraft-2-2.6.105-ex110.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.5.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 11/20/16 6:52 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Draconic Evolution (draconicevolution)
Caused by: java.lang.NoSuchFieldError: verts
	at com.brandon3055.draconicevolution.client.render.tile.RenderTilePotentiometer.<init>(RenderTilePotentiometer.java:37)
	at com.brandon3055.draconicevolution.blocks.Potentiometer.registerRenderer(Potentiometer.java:186)
	at com.brandon3055.brandonscore.config.ModFeatureParser.registerRendering(ModFeatureParser.java:184)
	at com.brandon3055.draconicevolution.client.ClientProxy.preInit(ClientProxy.java:46)
	at com.brandon3055.draconicevolution.DraconicEvolution.preInit(DraconicEvolution.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 603317784 bytes (575 MB) / 1648361472 bytes (1572 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2151 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2151.jar) 
	UCH	Forge{12.18.2.2151} [Minecraft Forge] (forge-1.10.2-12.18.2.2151.jar) 
	UCH	appliedenergistics2-core{rv4-alpha-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCH	appliedenergistics2{rv4-alpha-6} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-6.jar) 
	UCH	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	UCH	ae2stuff{0.6.0.6} [AE2 Stuff] (ae2stuff-0.6.0.6-mc1.10.2.jar) 
	UCH	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCH	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCH	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCH	Quark{r1.0-60} [Quark] (Quark-r1.0-60.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCH	Baubles{1.3.5} [Baubles] (Baubles-1.10.2-1.3.5.jar) 
	UCH	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCH	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCH	BiomesOPlenty{5.0.0.2107} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2107-universal.jar) 
	UCH	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCH	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCH	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UCH	Chameleon{1.10-2.1.8} [Chameleon] (Chameleon-1.10-2.1.8.jar) 
	UCH	chancecubes{1.10.2-2.3.2.131} [Chance Cubes] (ChanceCubes-1.10.2-2.3.2.131.jar) 
	UCH	JEI{3.13.3.382} [Just Enough Items] (jei_1.10.2-3.13.3.382.jar) 
	UCH	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCH	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCH	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCH	IC2{2.6.105-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.105-ex110.jar) 
	UCH	CompactSolars{5.0.5.329} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.5.329-universal.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	darkutils{1.1.6.99} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.99.jar) 
	UCH	forestry{5.2.16.327} [Forestry] (forestry_1.10.2-5.2.16.327.jar) 
	UCH	eleccore{1.6.345} [ElecCore] (ElecCore-1.10.2-1.6.345.jar) 
	UCH	deepresonance{1.3.1} [DeepResonance] (deepresonance-1.10-1.3.1.jar) 
	UCE	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UCH	StorageDrawers{1.10.2-3.4.6} [Storage Drawers] (StorageDrawers-1.10.2-3.4.6.jar) 
	UCH	bitdrawers{0.34} [Drawers & Bits] (DrawersBits-1.10.2-0.34.jar) 
	UCH	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCH	EnderIO{1.10.2-3.0.1.136_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.136_beta.jar) 
	UCH	shetiphiancore{3.3.5} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.5.jar) 
	UCH	endertanks{1.4.6} [EnderTanks] (endertanks-1.10.0-1.4.6.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.0.jar) 
	UCH	zerocore{1.10.2-0.0.8.1} [Zero CORE] (zerocore-1.10.2-0.0.8.1.jar) 
	UCH	bigreactors{0.4.5.19} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.19.jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCH	gendustry{1.6.4.24} [GenDustry] (gendustry-1.6.4.24-mc1.10.2.jar) 
	UCH	advgenerators{0.9.20.18} [Advanced Generators] (generators-0.9.20.18-mc1.10.2.jar) 
	UCH	InventoryPets{1.4.8.2} [Inventory Pets] (inventorypets-1.10-1.4.8.2.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCH	jeresources{0.5.7.87} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.87.jar) 
	UCH	lootbags{2.2.2} [Loot Bags] (LootBags-1.10.2-2.2.2.jar) 
	UCH	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCH	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCH	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCH	ProjectE{1.10.2-PE1.0.6B} [ProjectE] (ProjectE-1.10.2-PE1.0.6B.jar) 
	UCH	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCH	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCH	refinedstorage{1.2.4} [Refined Storage] (refinedstorage-1.2.4.jar) 
	UCH	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585.jar) 
	UCH	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCH	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCH	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCH	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCH	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCH	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCH	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCH	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	UCH	xprings{1.2.0} [Experience Rings] (xprings-1.2.0.jar) 
	Loaded coremods (and transformers): 
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
LoadingPlugin (Quark-r1.0-60.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
AppEngCore (appliedenergistics2-rv4-alpha-6.jar)
  appeng.transformer.asm.ASMIntegration
IC2core (industrialcraft-2-2.6.105-ex110.jar)
  
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.5.jar)
  shetiphian.core.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.137.1' Renderer: 'AMD Radeon R7 200 Series'
	AE2 Version: alpha rv4-alpha-6 for Forge 12.18.2.2104
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-alpha-6.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.9.4-1.0.1.1.jar
		* Baubles|API (1.3.1.1) from Baubles-1.10.2-1.3.5.jar
		* ChiselsAndBitsAPI (12.5.0) from chiselsandbits-12.7.jar
		* CoFHAPI (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.10-2.2.0.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.10-1.3.1.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.10.2-2.0.3.137-universal.jar
		* ElecCoreAPI (1.0) from ElecCore-1.10.2-1.6.345.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.10.2-1.6.345.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.136_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.136_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.136_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.136_beta.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.16.327.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.16.327.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.4.24-mc1.10.2.jar
		* jeresources|API (0.5.7.87) from JustEnoughResources-1.10.2-0.5.7.87.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.13.3.382.jar
		* McJtyLib (1.10-2.2.0) from mcjtylib-1.10-2.2.0.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* ProjectEAPI (1.9.4-1.0.0) from ProjectE-1.10.2-PE1.0.6B.jar
		* railcraft:API|core (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|items (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|signals (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|tracks (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.2.4.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.2.4.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-1.2.4.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.2.4.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.2.4.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.4.6.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.2.4.jar
		* VeinMinerApi (0.3) from VeinMiner-0.34.1-1.9r571+73be663.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
		* zerocore|API|multiblock (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.1.jar
		* zerocore|API|multiblock|rectangular (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.1.jar
		* zerocore|API|multiblock|validation (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.1.jar
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Trevo/Documents/Curse/Minecraft/Instances/Project%20E/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)`

**Comment by Ther0011001100** [comment]
Looking through Brandon's code and it is throwing the error about lines 37-58 when attempting to render the Potentiometer tile entity. Java is saying that there is no such field verts in the lines that generate the model and start with model.verts. It looks like it is trying to pull it from the java.lang package even though it shouldn't.

**Comment by covers1624** [comment]
Wrong, Remove the duplicated CCL inside /mods/1.10.2/

**Comment by niveksv** [comment]
Thank you so much covers1624

**Comment by McMark1441** [comment]
can someone explain to me what/where the file that I am removing?

**Comment by ktole1999** [comment]
removing the duplicate mod. inside your mod folder there is a 1.10.2 folder. Make sure there are no duplicates in there as there was in this case there were 2 different versions of CCL.
