### ISSUE TITLE
No item apart from armor uses power

### ISSUE THREAD

**Issue by SpellMaster20** [brandon3055/Draconic-Evolution#455]
I know most of the tools still say WIP. So I guess this is one of them but just in case no weapon or tools (Draconic at least) drain any power. So when you have a bow that use 416K RF each use it is kind of op. Just thought you should know that :)

Cheers Spell_Master

**Comment by brandon3055** [comment]
Oh darn how did i miss that... Will be fixed in the next release. 
BTW the wip really only refers to the enchantability issue.
