### ISSUE TITLE
[1.10] Wyvern Boots Jump Modifier not working

### ISSUE THREAD

**Issue by DerMax93** [brandon3055/Draconic-Evolution#458]
No matter to what i set the slider i always seem to jump the default ~1 Block height (boost on sprint doesn't change the behavior either).
My Version is 2.0.3.137

PS: The description of Jump Boost seems to be copied from the legs since it's talking about the "Speed boost" i am supposed to get despite the option being about jump-boost.

**Comment by brandon3055** [comment]
This will finally be fixed in the next release
