### ISSUE TITLE
Crashing When Trying to Open Enhanced Charm Of Dislocation 

### ISSUE THREAD

**Issue by Tidsuo** [brandon3055/Draconic-Evolution#46]
Caused by shift right clicking.

Crash Log Beneath

http://pastebin.com/1kg9eLRr

Cross Dimension Crash

http://pastebin.com/ZTYHsx35

**Comment by brandon3055** [comment]
Ok so the first crash isnt even related to the dislocator it is a crash in the manual that has been fixed in RC 3.

And the second crash is in snapshot 3. Please test bugs with the latest version before you report them. I believe that one is also fixed.
