### ISSUE TITLE
NPE on Rendering Screen

### ISSUE THREAD

**Issue by iamomicron** [brandon3055/Draconic-Evolution#460]
[Crash Log](https://cdn.discordapp.com/attachments/247415707715895297/252907951625338884/crash-2016-11-28_21.20.41-client.txt)

Reported to me by a couple of users - They were connected to a server, and putting items into the fusion crafting core caused this crash.

Happened a few times, but not consiistently.

**Comment by iamomicron** [comment]
I've found that this doesn't appear to be directly a DE issue. It's occurred on all forms of GUI's since this isntance. For exmaple, a vanilla chest: http://pastebin.com/RhzcYLzw

Not sure what the direct cause is, however it has something to do with shift-click functionality. Leaving open in case there *is* an issue anyway.

**Comment by brandon3055** [comment]
I suspect the server was just doing something dumb that the client was not expecting. Such as setting an item stack to null.
