### ISSUE TITLE
No Draconic Reactor in JEI for 1.10?

### ISSUE THREAD

**Issue by Frame1910** [brandon3055/Draconic-Evolution#461]
I've looked around and found that the reactor just is not there

I'm using the Direwolf20 1.10 pack. Is this an issue with the pack or is it not implemented yet?

**Comment by covers1624** [comment]
1.10 was a complete rewrite for DE. From my knowledge, he is working on it.

**Comment by Frame1910** [comment]
I wont be a dick and ask for a ETA thanks for the help :)
