### ISSUE TITLE
Custom Infusion recipes not working

### ISSUE THREAD

**Issue by stefan7080** [brandon3055/Draconic-Evolution#464]
Could also be that I am doing something wrong.
I copied the example and put it in a file called "CustomFusionRecipes.json"

![image](https://cloud.githubusercontent.com/assets/23392891/20744056/fbd9c848-b6d9-11e6-8476-bea7f2dc6de0.png)
![image](https://cloud.githubusercontent.com/assets/23392891/20744042/ebe90ff2-b6d9-11e6-8867-30e6306378fd.png)

Is this me doing something wrong or is this a bug in Draconic Evolution?

**Comment by brandon3055** [comment]
Ok looks like a recernt change broke the custom recipe system. It will be fixed in the next release. Also it  looks there is a mistake in the example.
https://puu.sh/sESDa/dd535bb925.png
The comma should be after the quote
