### ISSUE TITLE
[1.10.2] Wyvern Pickaxe - Enchants

### ISSUE THREAD

**Issue by ObservantCape79** [brandon3055/Draconic-Evolution#466]
Were do i go to add Enchants in the new version?

**Comment by austin5919** [comment]
You don't, it has not been implemented yet but is planned to be.

**Comment by brandon3055** [comment]
I was waiting for forge to add a hook to make this possible. They have now added that hook but only to 1.11 so i will probably have to hack it in myself for 1.10
