### ISSUE TITLE
No resurrection stone seen in latest Minecraft 1.10 version

### ISSUE THREAD

**Issue by secdeath** [brandon3055/Draconic-Evolution#467]
I'm not sure if you folks either did not get to this yet or removed it from the mod for some reason, but I'm not seeing the resurrection stone in the latest version of DE being 1.10.2-2.0.3.1.3.7. Can someone indicate what the status is on this please?

**Comment by Flatts3000** [comment]
Resurrecting the End Dragon is vanilla now, so I'm guessing its not needed.

**Comment by brandon3055** [comment]
@Flatts3000 That is correct. It really is not needed now.
