### ISSUE TITLE
[1.10.2] Draconic Grinder failing to kill mobs within its range

### ISSUE THREAD

**Issue by Morpheus1101** [brandon3055/Draconic-Evolution#468]
![2016-12-04_22 03 19](https://cloud.githubusercontent.com/assets/10524952/20866013/7a462fd2-ba6d-11e6-87f3-b82c808e4bea.png)
![2016-12-04_22 03 51](https://cloud.githubusercontent.com/assets/10524952/20866014/8ad44afa-ba6d-11e6-913c-b727ae4669d6.png)

This is so you dont forget what we talked about :p

**Comment by brandon3055** [comment]
This was an issue with the room being too large.
