### ISSUE TITLE
Tools + Blocks with metadata issue

### ISSUE THREAD

**Issue by SirWilli** [brandon3055/Draconic-Evolution#47]
hey,

if you break a block with the ID 343:4 for example it will drop the block 343 which is an big issue with creative items from thermal expansion or ender io because it will drop the creative type of the block if you break the normal one for example Hardened Strongbox -> Creative Strongbox.

**Comment by brandon3055** [comment]
I remember that happening with the awakened pick from thaumic tinkerer but it shouldn't be a problem with my tools.  At least i have not been able to recreate this.
