### ISSUE TITLE
Chaos Dragon Missing

### ISSUE THREAD

**Issue by MrSkyFire** [brandon3055/Draconic-Evolution#474]
So using EndierIO't Teleport pad I was able to teleport myself to 10000, 150(Height) 10000, Woot!
I got there and fought the dragon for about five minutes before he killed me. I later go back there to find out no more dragon.

Thankfully I had a copy of my world right before I did that, so I went rolled back, did more general construction, and continued on.

Same thing happened, but this time I didnt roll back :(

I went back, and no guardian to was there, again.

EDIT: On the latest 1.10.2 ver

**Comment by brandon3055** [comment]
The guardian is currently very broken in 1.10 and needs a complete re write. I just have not had time to do it yet.

**Comment by MrSkyFire** [comment]
Ah thanks for the info! Ill try not to die on the next encounter. :P
