### ISSUE TITLE
Fake players - Draconic evolution

### ISSUE THREAD

**Issue by Clifton-John** [brandon3055/Draconic-Evolution#475]
So, I've recently been running this server for a few of my friends and a few locals in my area. A few of them don't own premium minecraft so I set up this FTB Infinity server up with it being cracked client friendly. To keep people from logging into each other's accounts I've had to put in AuthMe.
AuthMe blocks also fake players from moving/breaking stuff. I've already resolved the issue with BuildCraft and Computercraft by doing this:
https://gyazo.com/93d3ed9e8f6a4e1db23796d914c2dadc

Now my question to you guys is how can I resolve this for draconic evolution?

**Comment by ktole1999** [comment]
resolution is to not support non-premium players.

**Comment by covers1624** [comment]
This was solved over IRC.
