### ISSUE TITLE
draconic ore not being able to be silk touched 100% of the time?

### ISSUE THREAD

**Issue by DoomSquirter** [brandon3055/Draconic-Evolution#476]
This may be the mod that gives the mining tool (actually additions drill) but I had some draconic ore that I processed with fortune V in exu2 previously in this map (I swear, memory sucks lol), but for some reason, anytime I hit the draconic ore with the drill, it drops 4 dusts and not the silk touched block.  Everything else silk touches just fine.  wondering if this was intended by your mod so I can rule out the other or vice versa.

Draconic-Evolution-1.10.2-2.0.3.137-universal

**Comment by brandon3055** [comment]
There is really no reason i can think of that silk touch would not work.  So i suspect it is not an issue on my end.
