### ISSUE TITLE
[1.10.2] DislocatorAdvanced can't teleport entites to a different dimension

### ISSUE THREAD

**Issue by flobernd** [brandon3055/Draconic-Evolution#478]
It just shows the message "You need a more powerfull dislocator". 

I traced down the problem to the `onLeftClickEntity` method of the `DislocatorAdvanced` class, Line 53. It should be
`if (entity instanceof EntityPlayer && !(this instanceof DislocatorAdvanced)) {`
instead of just
`if (entity instanceof EntityPlayer) {`.

I'm not into minecraft plugin development, but in my opinion `DislocatorAdvanced` should not even re-implement and override the `onLeftClickEntity` event, because all the code is already present in the `Dislocator` base-class.
The only piece missing is:
```
stack.damageItem(1, player);
if (stack.stackSize <= 0) {
    player.inventory.deleteStack(stack);
}
```
Just implement that block in the `Dislocator` class with a proper `instanceof` check, delete the `onLeftClickEntity` in `DislocatorAdvanced` and it should work like intended.

**Comment by brandon3055** [comment]
This has already been fixed in dev and will be in the next release.
