### ISSUE TITLE
Spawner dupe :)

### ISSUE THREAD

**Issue by Shadow232** [brandon3055/Draconic-Evolution#48]
Look to screenshots

http://prntscr.com/6mqz0y
http://i58.fastpic.ru/big/2015/0329/eb/fab5b87a2532d23c67042918447fcaeb.png
http://i58.fastpic.ru/big/2015/0329/1e/3285182e4a6437564146768d506d201e.png

**Comment by brandon3055** [comment]
More detail please. What spawner are you breaking? looks like a vanilla pig spawner? what are you breaking it with? I assume the staff? In the imageyou are in creative mode. Did you break it it creative mode? What spawner dose it drop? vanilla, the stabilized spawner or something else? And last what mods / mod pack are you using?

**Comment by Shadow232** [comment]
No, I was like spectator and simple take photos, my main actor is who have this staff. You take this staff what is images in first photo, after that i placed pig spawner ( all kind spawner have so bug ) and my helper, who wear this draconic stuff, without creative mod broke spawner and get x2 broken spawner . 

In addition we found 1 bug such bug, it`s with compitability mod of thaumcraft 4, you can get infinity amount of stabilized spawner => take magic staff, put to him Focus trade and use it on spawner. Click on spawner and you will get many many broken spawner`s :)

**Comment by Shadow232** [comment]
about addition, we found new :) Its not a problem with focus trade it is simple problem with all magic staff from thaumcraft 4 , look picture.

http://s7.hostingkartinok.com/uploads/images/2015/03/f9c596bbc32f3f0848d2d9520ee0a279.png

**Comment by Shadow232** [comment]
More we found way how make this dupe.
Take Draconic staff and enable safe mode:
picture - http://cs622724.vk.me/v622724129/26b05/EGVcwBgTJnw.jpg

**Comment by brandon3055** [comment]
Are those items real? Or are they ghost blocks that you cant actually pick up?

**Comment by Shadow232** [comment]
Of course yes, if it was only visual dupe i didnt wrote here about it :) , it is real dupe and many of us have <1000 spawners :D

**Comment by brandon3055** [comment]
This has been fixed by ender IO in the latest beta version. http://ci.tterrag.com/job/EnderIO/changes
