### ISSUE TITLE
Infinite Drac

### ISSUE THREAD

**Issue by austin5919** [brandon3055/Draconic-Evolution#480]
So, I accidently came across a method to get infinite draconium (and some other things), but obviously I wouldn't want to post the details publicly. This method uses only Draconc-Evolution items and blocks, so I'm assuming this dupe isn't caused by another mod. Where/how/who would I contact?

**Comment by covers1624** [comment]
message myself or brandon3055 on IRC, we are on Esper.net, IRC channel #DraconicEvolution

**Comment by brandon3055** [comment]
This is fixed in the latest version.
