### ISSUE TITLE
Issues creating Awakened core 1.10.2

### ISSUE THREAD

**Issue by Johnvista64** [brandon3055/Draconic-Evolution#481]
freezes up at 88%

![2016-12-11_13 31 41](https://cloud.githubusercontent.com/assets/12872677/21082690/3d9a2866-bfa6-11e6-9f26-fd9cd308bc24.png)

**Comment by AstroxV** [comment]
Could you explain what you did to get this fixed? My crafting is stuck as well at 88%.
