### ISSUE TITLE
Suggestion, Make jetpack use power from chestplate.

### ISSUE THREAD

**Issue by monkeybutt32** [brandon3055/Draconic-Evolution#483]
Currently have to stick your armor in another charging device from ic2 to charge it.

Your mod can use the jetpack and mounting plate as ingredients, but make your own chestplate handle the flying.

**Comment by brandon3055** [comment]
If i was going to implement EU support i would have to do it for the entire mod. I have no plans to do this because i am happy with RF and dont want to have to support multiple energy systems.
