### ISSUE TITLE
Chaos Guardian vanishes and never returns. MC 1.10.2

### ISSUE THREAD

**Issue by jlegion** [brandon3055/Draconic-Evolution#484]
We have mc on all the kids's pc's. All with this issue. If the chaos guardian kills you or you leave the chaos islands, he vanishes to never return. I have reloaded, rebooted, come back via dislocators and from end portal. All you get when you return is the sounds of him, but no guardian or his life bar. Pillars are still active though. Can even destroy them as usual. I will try loading only D.E., try, then cycle through other mods to check compatibility issues. Also the default key bindings don't work, you have to change them in order to get them to work.

**Comment by brandon3055** [comment]
As the warning message when you approach an island suggests. The chaos guardian is currently very buggy and requires a complete re write. I just have not had the time yet. This is just one of meny bugs.
