### ISSUE TITLE
crash when trying to sit on a furnitures mod chair

### ISSUE THREAD

**Issue by Hypsellis** [brandon3055/Draconic-Evolution#488]
I tried to sit on a chair from Furnitures mod, Draconic Evolution wasn't agree. :( 
http://pastebin.com/ird0MRS1

**Comment by covers1624** [comment]
This furnature mod needs to not return a null bounding box. If you could post an issue on the other mods end and link this issue that would be great.

**Comment by Hypsellis** [comment]
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/109
