### ISSUE TITLE
[Request] Particle Generator as a separate mod

### ISSUE THREAD

**Issue by xenoflot** [brandon3055/Draconic-Evolution#489]
Hi,

I love the particle generator for its aesthetic usefulness and versatility. Unfortunately the team on my server don't wish to install the whole of DE just to give me one block!

Would you consider separating that block out into a separate mod?

Cheers

**Comment by brandon3055** [comment]
Probably not going to happen any time soon. The particle generator has not even been updated to 1.10 yet anyway.

**Comment by xenoflot** [comment]
No worries. Thanks for getting back to me.
