### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by LawsOfScience** [brandon3055/Draconic-Evolution#491]
Ok, before I start, let me just say that I am using a MacBook Air, and that I want you to say "Draconic Evolution isn't compatible with Macs", etc if the crashing has something to do with this. Also, I apologize if this is the wrong place to put this. :)

Ok, on to the crash report. I installed and ran both the newest CCL and Brandon's Core before doing the same with Draconic Evolution. However, when I did run Draconic Evolution, this is the crash report I got: [http://paste.ubuntu.com/23649039/](url) . Could someone assist me with this?

**Comment by brandon3055** [comment]
Try updating forge you are using a very outdated version. If you still have this issue after that let me know (Will need the updated crash report)

**Comment by LawsOfScience** [comment]
Yep, that seems to have been the case. Also, what version of DE has the reactor in it? Or is it a separate file or something?

**Comment by brandon3055** [comment]
The reactor has not yet been updated to 1.10. Its currently only available in the version for MC 1.7.10
