### ISSUE TITLE
[Feature] Correct errors in Information Tablet

### ISSUE THREAD

**Issue by Rudolpher** [brandon3055/Draconic-Evolution#494]
I am aware it is heavily WIP.  
I would like to volunteer for correcting mistakes and potentially fleshing out a bit more on the different features of the mod if they are not made explicitly clear, as the book and mod develops.

**Comment by brandon3055** [comment]
I thought i already replied to this... Or maby im thinking of a similar issue. Currently the documentations system is a bit of a mess and at this time the only easy way to edit it is from my development environment. I really just slapped Project intel together as quick as possible so DE would have some documentation. When DE is feature complete i will get back to working on PI and once its in a more completed state it will be possible for users to edit documentation.

**Comment by brandon3055** [comment]
A lot of these typos have been fixed via pull requests.
