### ISSUE TITLE
[1.10.2] Exception caught during firing event net.minecraftforge.event.entity.living.LivingAttackEvent

### ISSUE THREAD

**Issue by LightningLdr180** [brandon3055/Draconic-Evolution#495]
Hello, my server is crashing on load, crash log below:
http://pastebin.com/N2d4diYv

I believe my friend said he was placing the Draconic Evolution grinder for a blaze spawner he had created.

**Comment by ktole1999** [comment]
looks like mca also has error. maybe the villager didnt want him to place it there lol

**Comment by brandon3055** [comment]
Looks like mca has issues with fake players. You need to report this to them.
