### ISSUE TITLE
Crashing with End Crystals

### ISSUE THREAD

**Issue by Anaerin** [brandon3055/Draconic-Evolution#496]
Crafted an end crystal, and placed it down on the portal in the end (aiming to re-spawn the Dragon), and the following happened:

http://paste.feed-the-beast.com/view/f4e64991

Every time I try and log in to this server I get this same crash. Which is annoying.

I know that the end crystal can display a base or not, and it seems that this check is causing an issue (crash). Is this related to something your code is doing, or do you just change the recipe?

**Comment by brandon3055** [comment]
Sorry that has nothing todo with me i only change the recipe.
