### ISSUE TITLE
Issue with DraconicEvolution, brandonscore, and CCL 1.10.2

### ISSUE THREAD

**Issue by DarkCreeper527** [brandon3055/Draconic-Evolution#497]
I am trying to install both Draconic Evolution and brandonscore on 1.10.2  When I add these to the mods folder and run the game it tells me to install CodeChickenLib 2.50 or above. However, when I do this it crashes the game with this crash report:

http://pastebin.com/02PKSLX4

I have checked for duplicates in mods/1.10.2 and the actual mods folder and not found any. Also when it tells me to download CCL it tries to download and install it for me. However, forge seems not to detect the auto-installed version.

I have no idea what could possibly be wrong. All help will be greatly appreciated. 

Thank you.

**Comment by covers1624** [comment]
There is no crash report in that log, please ensure you are running the latest brandons core, ccl / other cc mods if any. If the issue persists imnotice you have optifine, try without it and see if there is different results.

**Comment by DarkCreeper527** [comment]
Ok, thank you I must have attached the wrong log. I'll try without Optifine and see if that works.

**Comment by brandon3055** [comment]
That is actually the correct log. The game did not actually crash but it dose not give enough information to debug the issue. Can you attache the fml client latest log please

**Comment by DarkCreeper527** [comment]
Yes, 

http://pastebin.com/86x2TSFX

**Comment by brandon3055** [comment]
You have an old version of CCL in the 1.10.2 folder.
Download the latest CCL from curse and put it in the mods folder **NOT** the 1.10.2 folder
http://ss.brandon3055.com/fwa5i1p.png

**Comment by DarkCreeper527** [comment]
Ok, thank you I will inform you of any further problems.

**Comment by DarkCreeper527** [comment]
After doing what you told me the game crashed with this crash report.

http://pastebin.com/bYyiaDan

**Comment by brandon3055** [comment]
http://ss.brandon3055.com/rbk6g0g.png

Also where are you getting your mods? Unless you renames it the CCC jar looks like it has been downloaded from a repost site. If you are you need to stop.
Repost sites do nothing but rob modders of what little income they get from their mods.
They also tend to upload misslabeled jars that are not the version they say they are just so they can get downloads and worse meny have been known to add malware to jars. 
Download from the correct websites or you will not get support.

**Comment by DarkCreeper527** [comment]
Not sure where I downloaded CCC as it was a while ago I'll redownload it from Curse to be sure.

**Comment by DarkCreeper527** [comment]
Ok, not sure where I downloaded CCC as it was a while ago. I do download most of my mods from Curse so I'll redownload CCC from Curse.

**Comment by DarkCreeper527** [comment]
Still crashed with the same report.

**Comment by brandon3055** [comment]
Did you remove the duplicate CCL? Thats why it was crashing i just noticed that you also had an old version of CCC

**Comment by DarkCreeper527** [comment]
I'll check...

**Comment by DarkCreeper527** [comment]
All duplicates are removed, CCL is in the mods folder, yet forge doesn't seem to recognize that it's there

**Comment by covers1624** [comment]
Log?

**Comment by ktole1999** [comment]
sounds like you have multiple mods downlading CCL which means putting a version in the mods folder will conflict if there is also one in 1.10.2 folder. which mod is complaining?

**Comment by DarkCreeper527** [comment]
brandon's core is complaining

Here is the error message it is displaying on the game, the mods folder, and the latest log:

![error message](https://cloud.githubusercontent.com/assets/24705547/21437993/ecb4d0ba-c854-11e6-9ac8-b8e64ee9d903.png)
![mods folder](https://cloud.githubusercontent.com/assets/24705547/21438003/f61eff68-c854-11e6-866d-6e99aacecfea.png)
http://pastebin.com/ddwwa17Q

**Comment by ktole1999** [comment]
delete that from mods folder. you should be able to use the one that mek v295 downloads and it will be in the 1.10.2 folder. i ran into that same issue.

**Comment by DarkCreeper527** [comment]
Alright, so this is intesting... I looked through the logs and found some errors involving EnderStorage, so as a last resort I removed EnderStorage and the game loaded with all mods working perfectly. Is there some compatibility issue in 1.10 with EnderStorage and CCL or brandonscore? I'm not going to close the thread yet, as I want to see some explanation to it.

Thank you for all the help.

**Comment by ktole1999** [comment]
can you post the whole log with error?

**Comment by DarkCreeper527** [comment]
Yes, here you go

What I found was at lines 173-178
http://pastebin.com/VQ128FUT

**Comment by covers1624** [comment]
Update ended storage, no mod should be downloading ccl, if a mod is, update all your mods, ccl will NOT work in the 1.10.2 folder it must go in your mods folder, tripple check these things.

**Comment by DarkCreeper527** [comment]
Alright, all is working fine.

Thanks  everyone for all the help.
