### ISSUE TITLE
Ticking Entity (server crash) 

### ISSUE THREAD

**Issue by sharkck** [brandon3055/Draconic-Evolution#498]
1.10.2 Forge 2185 LC version 2.7.1 Draconic Evolution version 2.0.4.142

I had the server crash when I hit a Lightning Craft Demon Soldier that was in the Underworld with an ender bow.  It sent him to my Draconic Evolution Mob Grinder and the crash log says the mob grinder caused the crash.
 
Here is the crash log:
[crash-2016-12-21_23.29.59-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/668008/crash-2016-12-21_23.29.59-server.txt)

I have an open ticket on LC's end at: 
https://minecraft.curseforge.com/projects/lightningcraft/issues/25

**Comment by brandon3055** [comment]
That looks like an  issue on LC's end. I am using a standard forge fake player implementation and it looks like they are doing something which just breaks when a fake player is involved.
