### ISSUE TITLE
Creating Chaos Island crashs the server

### ISSUE THREAD

**Issue by Gamewalker** [brandon3055/Draconic-Evolution#5]
Error Log:
https://gist.github.com/Gamewalker/f283225af07265ab4557

**Comment by brandon3055** [comment]
The chaos islands are a work in progress if you are having trouble with them i recommend disableing them until they are ready.

**Comment by Gamewalker** [comment]
Ok, but how to get the Dragon Heart for the quest? Cheat it in or any other way?

**Comment by brandon3055** [comment]
You can use the ritual of ender resurrection to spawn a new dragon which will drop a heart that is how i intended for people to get dragon hearts.

**Comment by AnonymousPuppy** [comment]
I am also getting this crash on my server whenever a player attempts to generate a chaos island. I hope you can fix this in the next build. If not, then I would suggest disabling Chaos island generation by default in the config until you can fix this :)

**Comment by brandon3055** [comment]
This crash is now fixed in the latest snapshot.
