### ISSUE TITLE
[SUGGESTION] GUI Resize

### ISSUE THREAD

**Issue by nalkrien** [brandon3055/Draconic-Evolution#50]
Having the GUI resize based on your gui size would be helpful, because for me to read the book or to see the whole of the draconic chest I have to lower the gui size to see it.

Below are Normal GUI and Auto size as you can see when set to Auto I cannout navigate the book at all.

![2015-03-31_10 58 45](https://cloud.githubusercontent.com/assets/680239/6921820/1705f1a8-d795-11e4-9029-1ab0a6960603.png)
![2015-03-31_10 59 00](https://cloud.githubusercontent.com/assets/680239/6921821/170a2700-d795-11e4-9750-c35677453366.png)

**Comment by brandon3055** [comment]
Yea... Thats more of a problem with vanilla. Vanilla just doesn't do well with guis larger then 256x256 It may be possible with a bit of work to make the manual gui scale properly by writing my own gui code. But for containers like the chest thats not really an option.
