### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by knoxhack** [brandon3055/Draconic-Evolution#500]
Modpack: Project Ultimate

Server: MMD Public Server

Related Links:
https://minecraft.curseforge.com/projects/mmd-project-ultimate
https://github.com/MinecraftModDevelopment/Project-Ultimate/issues

Crash Report:
https://gist.github.com/knoxhack/751738aadad827bcc51622c9425d013a

**Comment by brandon3055** [comment]
You have 3 versions of ccl installed....... http://ss.brandon3055.com/tqts7dz.png

**Comment by brandon3055** [comment]
You have 3 versions of ccl installed....... http://ss.brandon3055.com/tqts7dz.png
