### ISSUE TITLE
Chaos Crystal not harvestable

### ISSUE THREAD

**Issue by Jaysleazy** [brandon3055/Draconic-Evolution#501]
Hello, ive killed the chaos guardian a few times now in the DW20 1.10.2 modpack and the crystal hasnt been harvestable any of the three times.  Im using the draconic staff of power in 1x1 mode.  Ive tried with and without silk touch.  Ive noticed some of the towers were not destroyed after the guardian was killed.  May have something to do with it.

**Comment by brandon3055** [comment]
Dose the crystal still have a red shield around it? If it dose not it should be harvestable.
The chaos guardian is still very buggy and needs a complete re write but there currently isnt anything that requires chaos shards so i am leaving that re write until i re add the reactor.

**Comment by InflamedSebi** [comment]
Experienced this too in Skyfactory 3. The shards are used in some recipes (solar panels & Fusion crafting).
The red barrier is not removed after the guardian died.

**Comment by brandon3055** [comment]
https://github.com/brandon3055/Draconic-Evolution/issues/580
