### ISSUE TITLE
Energy Pylon show wrong RF of core

### ISSUE THREAD

**Issue by AstroxV** [brandon3055/Draconic-Evolution#502]
Energy Pylons don't show the correct amount of RF stored in the core.
The Energy Pylon shows 2.1 GRF while my Tier 4 core is full and holds 9.88 BRF. This makes it that every machine to monitor the core I connect to it, thinks the core is full after it holds 2.1GRF instead of the full charge it can hold.
As far as I can see there is no way to know when the core is actually full or not other than visually checking myself.

**Comment by brandon3055** [comment]
That is due to a limitation of the RF API which only supports values up to 2.1B If you have computercraft or open computers installed the core has support for those. You can also attach a comparator to one of the pylons but that is a very analog solution.
