### ISSUE TITLE
[1.10.2]Staff of Power voiding Mekanism multiblocks

### ISSUE THREAD

**Issue by PWTordenskiold** [brandon3055/Draconic-Evolution#504]
Blocks in question are Turbine multiblocks and Induction multiblocks. Turbine Casing when placed down gains an NBT tag, Induction Casing does not.
If it is broken by Staff of Power in 3x3x3 or higher setting(instead of dropping material it drops "packets" of it), the blocks get voided(Sound of picking up something, but empty inventory). 1x1 drops the blocks as expected.

Tested Extreme Reactors and Ender IO multiblocks, they drop as expected.

Might be related to #482 ?

**Comment by PWTordenskiold** [comment]
Might be related to #482 ?

**Comment by brandon3055** [comment]
This should be fixed in the latest release.

**Comment by PWTordenskiold** [comment]
Tested with 2.0.6.157 and blocks drop as expected.
