### ISSUE TITLE
[1.10.2]Staff of Power material "packets" bypass other mods

### ISSUE THREAD

**Issue by Rudolpher** [brandon3055/Draconic-Evolution#505]
Example - You have miners/diggers backpack from Forestry in your inventory. These normally automatically pull in relevant items that you pick up(Diggers backpack for instance fills up with stone and sand). If the Staff of Power is configured to a mode high enough that it stops dropping individual items and instead drops "packets" of them, these backpacks(or equivalent from other mods that I've tested) no longer function and instead what you pick up lands in normal inventory. 
You either have to manually throw the items in the backpacks or drop the items and re-pickup. This kind of makes the larger modes useless for mining since the vanilla inventory is so limited with space.

Can the packets instead "burst open" when player walks on them(after say 5 or 10 seconds have passed), so dropped items are picked up as normal, or is this an issue that is best solved by for instance Forestry in how it handles item pickups?

**Comment by brandon3055** [comment]
The point of having the loot cores is so you dont end up with hundreds of item entities on the ground when your inventory fills up so having the burst open on contact would kinda defeat the purpose. I will look into this issue and see if i can insert the items into the players inventory in a way that mods like forestry can detect.
