### ISSUE TITLE
Connection between flux gate and cryo-stabilized fluxduct

### ISSUE THREAD

**Issue by hhhhhg** [brandon3055/Draconic-Evolution#507]
#Today I was testing what reactor in my world is the best then I construct draconic reactor and then when I connect cryo stabilized flux duct to flux gate it crashes (I'm using THermal expansion for wiring and cables +MEkanism+ Project Red and Project Blue + Other. THanks for help . Sry for bad english

**Comment by brandon3055** [comment]
Crash report or it didnt happen.
