### ISSUE TITLE
[1.7.10] While wearing Draconic Evolution armor, a lot of book's text bugs out

### ISSUE THREAD

**Issue by Atricos** [brandon3055/Draconic-Evolution#509]
While the player's wearing any piece of Wyvern or Draconic Armor, and reads the Achievement book, Tinker's Book, Rednet Manual, Engineer's Manual (and possibly more), this happens:
http://imgur.com/a/aBYck
Most of the pages in the Achievement book are unreadable, lot of pictures don't show up in the Tinker's Book, etc.
When the player takes off all the armor pieces, the books become readable again.
These pictures were taken in Project Ozone 2, and the current version of Draconic Evolution in the pack  is 1.0.2h, and it seems to be the latest version. The only other version I found was in the FTB Infinity Evolved modpack, 1.0.2a, and if I DOWNGRADE to that version, that fixes the issue. The only problem is, a lot of config files are lost when downgrading.
I also tried Draconic Evolution 1.0.2h in other modpacks, and the problem still occurs, a lot of the times interfering with other mods (like DivineRPG's breath-bar on the bottom right: wearing the armor turns the area around it from see-through to white).
I also tried changing some config options: using the older or newer Wyvern/Draconic Armor rendering doesn't fix the problem. If anyone's noticing these issues, and/or knows how to fix it, I would greatly appreciate that.

**Comment by brandon3055** [comment]
This is on my todo list but as it is a 1.7 issue it may be a while before i get around to it.
