### ISSUE TITLE
Wireless/Advanced Wireless Transceivers Crash [MP]

### ISSUE THREAD

**Issue by iDrewt** [brandon3055/Draconic-Evolution#51]
I was playing Single Player on the latest version of DE and stumbled upon the the amazing Wireless Energy Transceivers!! Played around with them and decided to go for them on a Multiplayer server, and found that each time I place either of the Wireless Transceivers, I crash the whole server, then when we restart, if I am within a certain (small) range of the transceiver I get disconnected for "A fatal error" ... Admins had to use World Edit/Voxel Tools to remove it because it was a ghost block, and never was actually placed when I tried before crash. It remains in my inventory. 

Working on getting the crash log.

**Comment by iDrewt** [comment]
https://gist.github.com/iDrewt/d0800a242ec50ba42321

**Comment by brandon3055** [comment]
Thanks for reporting this. It will be fixed in the next release

**Comment by iDrewt** [comment]
Sweet! Thank you, I really love this mod! Also, a scroll bar on the tablet of info would be amazing. 

Thank you thank you thank you.
