### ISSUE TITLE
[1.10]Infusion injectors do not accept power

### ISSUE THREAD

**Issue by Happynger** [brandon3055/Draconic-Evolution#511]
Minecraft 1.10
DE 1.10.2-2.0.5.154-universal

As the title says Injectors do not accept any means of power. I checked it in the creative later to find out that they did not accept power from anything even DE's power transfer crystals.

**Comment by brandon3055** [comment]
Can you show me a screenshot of your setup? They work fine for me and everyone else that uses them.

**Comment by Happynger** [comment]
Here is some from my single player game.
![2017-01-04_17 30 11](https://cloud.githubusercontent.com/assets/13449795/21665995/df6742a4-d2a3-11e6-8004-054a05c8cebe.png)
![2017-01-04_17 30 13](https://cloud.githubusercontent.com/assets/13449795/21665998/df6a99b8-d2a3-11e6-9d7f-72d97578279a.png)
![2017-01-04_17 29 37](https://cloud.githubusercontent.com/assets/13449795/21665999/df6b7d06-d2a3-11e6-8d21-2de16528e3b3.png)
![2017-01-04_17 29 41](https://cloud.githubusercontent.com/assets/13449795/21665997/df6a4fbc-d2a3-11e6-9f21-a88b38388f92.png)
![2017-01-04_17 29 45](https://cloud.githubusercontent.com/assets/13449795/21665996/df6a40ee-d2a3-11e6-915d-3477b52cd28e.png)

**Comment by dragonpc75** [comment]
I'm having the Same Issue, except its not working with the Wireless energy crystals, it works with ender IO direct connect, but from the Pylon (attached I/O crystal) to the Wireless crystal, to a secondary wireless crystal, then to the 8 I/O's on each of the Fusion crafters, they charge up but do not inject power into the crafters.
![2017-01-15_11 03 43](https://cloud.githubusercontent.com/assets/19497618/21965312/7f153934-db12-11e6-8425-6bf2dc87c65b.png)
![2017-01-15_11 04 12](https://cloud.githubusercontent.com/assets/19497618/21965315/89e6e6c8-db12-11e6-9df5-6d5c5eb526b7.png)

**Comment by dragonpc75** [comment]
Figured this out, you have to right click eah of the crystals and set them to output mode.. (the I/O ones)
after that it works just fine... :)

**Comment by brandon3055** [comment]
@Happynger Are you still having this issue? If so try powering them with a creative rf source attached to each injector in a creative world. If that does not work then something else in your pack must be breaking them. CHeck the log for errors.

**Comment by mrwartooth** [comment]
im haveing the same issue but the fix posted by dragonpc75 didnt work for me i still cant seem to get it to work
![2017-02-08_10 00 43](https://cloud.githubusercontent.com/assets/25643349/22748193/81325102-ede6-11e6-9507-9f7584cd30cf.png)
![2017-02-08_10 00 53](https://cloud.githubusercontent.com/assets/25643349/22748197/83396bf2-ede6-11e6-8774-efb840eb1b6e.png)

**Comment by brandon3055** [comment]
Those were notch apples not regular golden apples (We worked this out earlier in discord)
