### ISSUE TITLE
[1.10] Breaking the IO crystal with silk touch yields the crystal hub.

### ISSUE THREAD

**Issue by Happynger** [brandon3055/Draconic-Evolution#512]
Minecraft 1.10.2
DE 1.10.2-2.0.5.154-universal

Found that by breaking the IO crystal from DE yields to it's hub instead of IO. I think it is because of the Silk Touch on my pick but might be something else.
Supremium Pickaxe [From Mystical Agriculture]
Enchants:
- Efficiency 6 [From the mod Quark]
- Silk Touch

**Comment by brandon3055** [comment]
Nope looks like i somehow forgot to add the correct harvest code that tells it which item to drop. Will be fixed in the next release.
