### ISSUE TITLE
Question: for 1.10.2 are reactors added back in yet?

### ISSUE THREAD

**Issue by Kaisoul** [brandon3055/Draconic-Evolution#514]
just wonder if the reactors are added back in for 1.10.2 at this time?

only asking cause i looked and did not see them but to make sure i am asking to make sure that i did not miss them.

**Comment by covers1624** [comment]
Content currently missing from De is on the list, Brandon is Woking at his list every day, things are getting rewrites so it may take a while for some parts of his list to be ported but it all will be.
