### ISSUE TITLE
[Suggestion] Modularize the mod in a more user-friendly way.

### ISSUE THREAD

**Issue by Dragnier** [brandon3055/Draconic-Evolution#519]
For players who don't know how or don't want to mess with config files, but still want to play your mod with portions of it disabled, like armor and weapons, splitting the mod into pieces would be the most user friendly. 

**_At least_** have it separated into modules internally via a modules config file which can be edited with an in-game UI or the mod config button on the Minecraft UI. A couple of basic examples would be Charset or Tinkers. They have module config files. This prevents players/users from having to search for mutliple things to turn them all off. They can still do this if they only want one item off, but they can also turn off the entire module to get them all with less frustration.

Core = The necessities that cannot ever be disabled, like id's for ores, ingots, basic crafting, etc.
Worldgen = Oregen, etc.
Meteors = Well.. meteor gen.
Utility = Novelty, Utility, etc.
Armory = Weapons, armor, etc.
Energy = Power gen, storage, transfer, etc.

**Comment by covers1624** [comment]
No, This will not happen. Mods that do this are just silly, there are configs for a reason, use them. We will not be changing the fundamental way the mod works purely for disabling giant chunks at once. DE is an End Game mod, if you don't like part of it, there is a config or just don't use that content.
