### ISSUE TITLE
[1.10.2] Suggestion for Energy Core Build Guide

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#521]
Ugg. Got to be the worse build guide I've used so far. So, instead of complaining I will make a couple of suggestions. First, going from Tier 3 to Tier 4 the redstone blocks were covered by the draconic blocks I placed for the 3rd Tier so I didn't know they needed to be put in. Not sure how to fix that one besides telling people to dismantle the sphere, but leaving the core untouched, between upgrades. But the build guide itself is, yeah. I set it for Tier 7 and there was all sorts of blocks popping in and out it was a royal pain figuring out what to put where. I would suggest, perhaps, making it so you can set it to display each layer and make it fixed so it always shows. So, as an example, set the Tier to 7, set the build guide to show, then under would be "Layer" with a text box and two arrows,  up and down. So that someone could start at layer 1, place the blocks, click up to go to layer 2, place the blocks, etc until done. I had placed a dirt block down so I could sneak click add the first four redstone blocks, and lost track of it in the sea of phantom redstone blocks and the first build failed for obvious reasons. That would be another nice feature. Big Reactors, not sure if the successor does it too, would tell you the coordinates of the invalid block making it easy to diagnose a build and fix problems, especially in mega reactors. Perhaps this as well? Though the selectable layers option would make things a ton easier. No sea of phantom redstone blocks. >.<

**Comment by 1matto** [comment]
I do agree that the build guide should be better

**Comment by covers1624** [comment]
After reading this, i do have some ideas on how brandon can improve the build guide, ill pass those along to him.

**Comment by Bockiii** [comment]
Additional request, maybe this has been asked, maybe this can be merged: Adapt the building process from Advanced Generators or Thaumcraft.
For example: Place down the Core and the stabilizers, then hit a stabilizer with some kind of hammer/wand/doohickey that builds the structure selected in the stabilizer.

**Comment by llloyd4** [comment]
Or kinda like Blood Magic, place down the core with enough space around it and, as long as you have the materials in your inventory, keep whacking the core with a wand/hammer/thingamabob and it auto places the blocks one by one?

**Comment by Bockiii** [comment]
Wrote Thaumcraft -> Meant Bloodmagic. So I agree with lloyd.

EnvTech does the same thing.

**Comment by brandon3055** [comment]
I made some adjustments to the renderer so that it shows invalid blocks in the structure.  I will consider adding the "Auto Place" feature at a later date.
