### ISSUE TITLE
Chaos Guardian vs Wyvern Armor

### ISSUE THREAD

**Issue by Appa1990** [brandon3055/Draconic-Evolution#524]
Hello there,

i think i got an issue with the Chaos Guardian. I play on an server which is Running FTB 2.6.0 MC1.7.10 with DE 1.0.2h.
When i wear the Wyvern armor i dont have any chance to kill this beast. 1 to 2 hits and i will be dead. Also the capacitors wont work (testet with 30pcs all focused to armor, in singleplayer).
I noticed that the blue bar in the hud isnt moving, when i get a hit. A zombie could kill me in 2minutes. 
I have a full enchanted wyvern armor and every piece have 3 "update-cores". 
So is it my mistake or is something else wrong?

greetings from germany
Appa1990

**Comment by 1matto** [comment]
Your suppose to have draconic armor to take on the Chaos Guardian

**Comment by Appa1990** [comment]
ok so im forced to do the ressurection thing. cause i waste the heart for only one awakened draconium block XD. but whats the wyvern armor for? if i could fly faster i think i could kill him. But the angle ring isn't that fast. 
But so thats not an issue, just a misunderstanding.

**Comment by 1matto** [comment]
Just remember you need 4 ender crystals to summon the dragon in 1.10 and DE changed the recipe slightly
