### ISSUE TITLE
[SUGGESTION] Easy way to get wither skulls in DE?

### ISSUE THREAD

**Issue by 1matto** [brandon3055/Draconic-Evolution#525]
Can there be a way to get wither skulls without relaying on other mods like tinckers?

**Comment by 1matto** [comment]
Thats still a 5.5% chance and tinkers give you a better drop rate then looting 3

**Comment by brandon3055** [comment]
There already is. Just farm wither skeletons with the mob grinder. Currently you will need another mod to spawn them but i will be bringing back the spawner soon.
