### ISSUE TITLE
Unknown orbs created when mining and inventory is full

### ISSUE THREAD

**Issue by davelien** [brandon3055/Draconic-Evolution#526]
When mining with a Wyvern pickaxe and my inventory fills, orbs are dropped which I have never seen before.  Is this expected behavior?

This is a screenshot.

![2017-01-04_16 24 21](https://cloud.githubusercontent.com/assets/12649356/21664357/afbe08ac-d29a-11e6-9dc9-5a2d84372cf3.png)

When I free up inventory space they are picked up as the 'regular' blocks they seem to contain.

DE: 1.10.2-2.06.157
Brandon's Core: 1.10.2-2.1.3.82-universal

**Comment by covers1624** [comment]
Yes this is normal, DE as a lag reduction mechanic will drop these loot cores when you mine stuff in AOE mode(i think just that not sure).
