### ISSUE TITLE
[SUGGESTION] Draconic&Wyvern Shields please?

### ISSUE THREAD

**Issue by 1matto** [brandon3055/Draconic-Evolution#528]
Draconic and Wyvern shields could be a good addiction because I don't think there were any shields that use RF since they were added in 1.9

**Comment by GreatOrator** [comment]
https://www.brandon3055.com/suggestions/draconic-shield/

Looks like someone already suggested it :D

**Comment by brandon3055** [comment]
This will probably happen eventually...
