### ISSUE TITLE
Upgrade Wyvern items to Draconic will lose upgrade

### ISSUE THREAD

**Issue by oks1998** [brandon3055/Draconic-Evolution#529]
I dont know is orignally will make like this or is bug, when I upgrade my wyvern armor to draconic armor,
it lose all the upgrade in the armor items (wyvern level)
I checked the upgrade ingredient for both type of armor is same, why is the upgrade will lose after fusion crafting?

version: 1.10.2-206.157

**Comment by brandon3055** [comment]
If you are using the version you say they should be kept. Can you please give me your log.

**Comment by roboderpy** [comment]
@brandon3055 also, is it normal that you will also loose all enchantments on tools after upgrade?

**Comment by llloyd4** [comment]
Well, my sword kept it's Wyvern level upgrade (damage) when I upgraded it from Wyvern to Draconic but the armor lost the Wyvern level upgrades (shield recovery and shield capacity) when I upgraded them to Draconic. So I am just cheating in the ingredients as I am counting it as a bug. >.<

**Comment by BrainInBlack** [comment]
Can confirm the loss of upgrades with version 1.10.2-2.0.6.157 (currently used by SF3) on upgraded Wyvern Armor, the weapons work just fine and keep their upgrades as intended.

**Comment by funniray** [comment]
I can confirm also that in SF3.0.4, you lose the upgrades when you go from wyvern to draconic

**Comment by oks1998** [comment]
Is the logs file that owner want is come from the logs folder in minecraft folder?

[2017-01-06-1.log.gz](https://github.com/brandon3055/Draconic-Evolution/files/706406/2017-01-06-1.log.gz)
[2017-01-06-2.log.gz](https://github.com/brandon3055/Draconic-Evolution/files/706405/2017-01-06-2.log.gz)
[2017-01-07-1.log.gz](https://github.com/brandon3055/Draconic-Evolution/files/706407/2017-01-07-1.log.gz)

**Comment by oks1998** [comment]
I replicated the problem again using creative mode.
I think this is the log file you want: 
[fml-client-latest_2.txt](https://github.com/brandon3055/Draconic-Evolution/files/706413/fml-client-latest_2.txt)

![2017-01-15_11 48 36](https://cloud.githubusercontent.com/assets/9070825/21960105/fb192f62-db18-11e6-8dba-38eea051e252.png)
![2017-01-15_11 48 20](https://cloud.githubusercontent.com/assets/9070825/21960106/fb1b144e-db18-11e6-8d48-eda39b632cda.png)
![2017-01-15_11 48 18](https://cloud.githubusercontent.com/assets/9070825/21960107/fb1e0ab4-db18-11e6-913e-908646976fc4.png)
