### ISSUE TITLE
Chest leak

### ISSUE THREAD

**Issue by BloodyError** [brandon3055/Draconic-Evolution#53]
Hello,
I'm running now a FTB Infinity 1.3.4 server.
Since 1.3.0 there is a problem with the Draconic chest and there is no way I could fix it alone or disable it through the config files.
So the problem are:
1) when it used it takes alot of resources from the server, mostly memory.
2) When you don't use the chest, If you leave it after you click on one of the buttons, like 'all' and etc, it still keep using the server resources and even much more.

I could give you the server logs but it don't show anything. 
I just saw the server use too much of rams, when I did /cofh tps I saw 'Overworld [0]: 20.00 TPS/17.90MS (100%)' and then used /opis to find what happend and saw one draconic chest that eating the memory.
After I changed it to 'off' it stoped and server now is on 'Overworld [0]: 20.00 TPS/2.70MS (100%)'

**Comment by brandon3055** [comment]
Are you sure your not mixing ram memory with tick time? That is something that will be fixed soon.

**Comment by BloodyError** [comment]
Might be.
Recently there are alot of problems with the memory and ticks and each time I check the console or 'opis' i find this chest on top of the list.
When I click 'off' everything get stable again.

But i'll be honest, this chest is not the only issue in the server - mystcraft did a mess as well but it been fixed now.
