### ISSUE TITLE
Infusion crafter stops at 88% charging

### ISSUE THREAD

**Issue by KaiKamakasi** [brandon3055/Draconic-Evolution#534]
Issue: trying to craft draconic cores the infusion stops at 88% charged, i had come across this before when applying upgrades to wyvern armour but it seemed to fix itself when i changed the armour piece to another or by breaking and replacing the crafting core.

how to replicate: see video

version:  2.0.4.142
Minecraft: 1.10.02
mod pack: sky factory 3 3.0.1
forge: 12.18.3.2185

happening on my hosted server

youtube link: https://youtu.be/xtZonLP5ttk

**Comment by SSailorJupiter** [comment]
Can also concur but with the wyvern fusion crafting injectors recipe, which stops at 62% charge. None of those suggestions fixed the infusion and still stays at that charge. This is happening on version 1.2.1 of the DW20 modpack.

**Comment by brandon3055** [comment]
Are you sure all of the injectors are properly powered?

**Comment by brandon3055** [comment]
The charge will be directly proportional to how many injectors have power. Meaning if only half of the injectors have power it will only charge to 50%

**Comment by KaiKamakasi** [comment]
not really sure how this was the case but you were indeed ofcourse, correct @brandon3055  i was using the flux points from the flux network mod, at 240k rf/t i thought these would be sufficient, perhaps a note in the tablet that says how much RF/t is needed per? i know it say how much is needed per infusion but unless i've missed it, it doesn't say that each injector requires a specific amount of RF/t, at the very least perhaps a note saying 'if the fusion 'freezes' try a better cable'

**Comment by brandon3055** [comment]
The RF/t is not important. If it is too low it just will not charge as fast. Unless there is a bug somwear.

**Comment by KaiKamakasi** [comment]
I couldn't say if it is a bug exactly, but the flux points didn't work (which after checking it supplies 256k rf/t) using another cable which supplies 320k rf/t running directly from a pylon to the infusers, if anything given that now the infusers are receiving 320krf/t divided by 6 rather than 256krf/t per infuser, yes I know the individual RF/t doesn't matter as you say, but that is the transfer rate, theoretically the cable that now works should be slower, I know the power supply wasn't a problem as in both cases it was being supplied directly from a pylon with a core that has over 700bn RF stored.

**Comment by davelien** [comment]
Same issue here.  Attaching a Flux Point directly to the Crafting Injector does not work.  My workaround was to attached Ender Energy Conduits to the Injector and then attach a Flux Point to the conduit.

**Comment by brandon3055** [comment]
Just did some testing and it seems the Flux Networks mod is a steaming pile of bugs. Switch to a different energy network and see if this still happens.

**Comment by klomer** [comment]
I was using a flux point for a Awakened Core.  It stopped at 88%.  I tried removing it and replacing it, no luck.  Tried removing the nether star and destroying the fusion crafting.  Comes back at 88% and still frozen.  Unable to get it started again.

**Comment by klomer** [comment]
Also seeing this on Awakened Draconium at 85%.  I used to be able to do Awakened Draconium, but it's not working now.

**Comment by klomer** [comment]
After more testing, I discovered that one of my fusion crafters was missing power.  Adding power to it fixed the problem.

User error!  Although an error message would have been much appreciated.

Thanks for the fun mod!

**Comment by BluieMBA** [comment]
i have no problems with flux network but i play on a server, when the server restarts or crashes
the flux get reseted so i use the draconic ev wirless power things

**Comment by BluieMBA** [comment]
and it worked :D

**Comment by stomppnsmash** [comment]
Had the problem trying to power an injector from behind directly with the flux plug, only worked on the ones powered on the sides.

**Comment by brandon3055** [comment]
@stomppnsmash That sounds like the conduit you used may be buggy. I suspect its attempting to inject power into the opposite side of the block from the side its placed on.
