### ISSUE TITLE
Config to disable Crystals Particles/lasers

### ISSUE THREAD

**Issue by TonRZN** [brandon3055/Draconic-Evolution#535]
It would be awesome to have a config option to disable the Crystals particles/lasers at all and only show then when holding the Binder, I mean, disable even when they are transferring energy

**Comment by brandon3055** [comment]
If performance is an issue the lasers themselves will have almost no impact. The particle effects are also very optimized but can cause some fps drop if you have a lot of them bunched together.

**Comment by TonRZN** [comment]
I was thinking just for aesthetic purposes

**Comment by brandon3055** [comment]
Well if you dont like fancy looking energy crystals that transmit energy via energy beams the obvious solution is to just use one of the boring tesseract like transfer systems that exist in other mods.
