### ISSUE TITLE
Crystals don't work with extreme reactors mod 

### ISSUE THREAD

**Issue by 1matto** [brandon3055/Draconic-Evolution#537]
Crystals won't move energy from the reactor in the extreme reactors mod

**Comment by iirelu** [comment]
A fix I found was putting a cable between the flux port and the IO crystal. Annoying, as it limits the throughput.

**Comment by ZeroNoRyouki** [comment]
This was a bug on my side. It's fixed in ER 1.10.2-0.4.5.24

**Comment by charlesbevans** [comment]
If you're not in a position to update yet, I used multiple taps with an EIO vibrant capacitor bank. I can transfer the power faster than I generate it.
