### ISSUE TITLE
Exception caught handling a packet on channel DEvolutionNC

### ISSUE THREAD

**Issue by antisocialian** [brandon3055/Draconic-Evolution#538]
Getting an error and crash to menu when connecting Basic Energy Relays/Basic Energy IO/Basic Wireless here's the snippet of what shows in the console and logs when it happens: [http://pastebin.com/14FVcFiJ](http://pastebin.com/14FVcFiJ). The server console doesn't show any special, just that I've disconnected(the message is the same as if I had disconnected normally).

It doesn't crash the minecraft instance just disconnects from my server. I am using version "Draconic-Evolution-1.10.2-2.0.6.157-universal.jar", the pack is mainly the Direwolf20 pack, but i've added some things to it so here's my mod list [http://pastebin.com/H6fSKXCW](http://pastebin.com/H6fSKXCW).

I can't seem to reproduce it in singleplayer(maybe io.netty isn't used in singleplayer?), but it seems to happen only once every hour or so of play.

Edit: forgot to mention i'm using forge-1.10.2-12.18.3.2185

Edit 2: I have removed the Torcherino mod, my server wasn't liking that too much and I figured it may have been the cause. Unfortunately it isn't, in fact the crashes seem to be happening more frequent now.

**Comment by callmebackdraft** [comment]
im am getting the same crash to menu, especially when connecting extra relays

**Comment by TheBamby** [comment]
I have the same issue it is definitely related to the power system.

Here is my crash log: http://pastebin.com/RDCjhV4h
I'm running FTB pack Direwolf20 1.10.2 v1.3.2
Draconic Evolution v2.0.6.157 (2.0.6)
Forge 12.18.3.2185

**Comment by brandon3055** [comment]
This should be fixed in the next release.
