### ISSUE TITLE
Issues with disconnecting in SkyFactory 3 on LAN

### ISSUE THREAD

**Issue by kaosjr** [brandon3055/Draconic-Evolution#539]
Greetings, this is something that's only started happening recently.
I join my friend's world in SkyFactory 3 on LAN through Hamachi, and I have issues where when looking at Draconic Evolution blocks and clicking buttons in the GUI, I will just disconnect from the server.
It will sometimes refuse over and over to let me back in until it finally works again, but until then it's a loop of disconnecting as soon as I connect.
I have a log file attached; the issue shows up quite a few times, the most recent I can find being on line 218976 when you open the file with Notepad++. I'm sorry for the massive log, but I didn't want to put an excerpt and since the game doesn't crash...
Any help with this issue would be appreciated, as I can't do anything with draconic without repeatedly crashing.
Side note: my friend hosting the LAN world does not have the same issue.
Another side note: If he uses the fusion crafter, I end up disconnecting.
Thanks again,
kaosjr

Mediafire link to the file since it's too large for GitHub (lol it's massive)
http://www.mediafire.com/file/n0t0n24ran51baj/fml-client-latest%282%29.log

**Comment by callmebackdraft** [comment]
Do you guys use draconic evolutions power transfer system ? If so it is related to issue:

**Comment by kaosjr** [comment]
Yes, we do use the draconic evolution power system, and now that you mention it, it only happens when there's some sort of power draw.

**Comment by callmebackdraft** [comment]
Yep that really sounds farmiliar, this means brandon and co. Should look into both this issue and #538

**Comment by Dasms** [comment]
I get disconnected from my server a lot when I activate machines that draw power from them. Here is a crash log: http://pastebin.com/YBvEY59m

**Comment by brandon3055** [comment]
This should be fixed in the next release.

**Comment by kaosjr** [comment]
Issue fixed in current release.
