### ISSUE TITLE
Energy Pylon Range (on Max Size Power Cores)

### ISSUE THREAD

**Issue by cwbit** [brandon3055/Draconic-Evolution#54]
It'd be great to have a larger range in which to place the energy pylons, especially on the Tier 6 core.

Currently the max is 6 blocks up or down and 15 (?) out, but when you're using a Tier 6 Power Core this means you can't have the pylons directly under the structure, and at 6 below center-line they start to ride way up into the bottom of the core!

So on a max-size you can't have your input/output on top/bottom like you might want :/

![2015-04-02_19 32 28](https://cloud.githubusercontent.com/assets/6501207/6975839/b9c3dc44-d96f-11e4-8f6c-9a4e4112f8e2.png)

Also... this mod is my new favorite... those Cores.. OH BABY

**Comment by brandon3055** [comment]
I have just extended it to 15 in every direction but i may also increase the range for the higher tiers.

**Comment by cwbit** [comment]
well THAT just made my day :D

You, sir, are a gentleman and a scholar.
