### ISSUE TITLE
Chaotic Injectors Crafting with another mods Ender Dragon Egg

### ISSUE THREAD

**Issue by SpellMaster20** [brandon3055/Draconic-Evolution#540]
Hi I am not too sure as two who's Problem this (but I would maybe presume the mod that changes the egg)  In Sky Factory 3 there are Dragon mounts that change the normal MC egg. This prevents the use of the dragon egg in any DE Fusion crafting. Am I correct in thinking that this is an ore dictionary issue with Dragon mounts and not Draconic Ev? If so I will move this post to them instead of you :)

Cheers Spell_Master

**Comment by 1matto** [comment]
try using a piston to pick up the egg

**Comment by brandon3055** [comment]
As far as i know there is no standard ore entry for the dragon egg because it is not a widely used resource. If dragon mounts adds one i can use it otherwise there is nothing i can do.

**Comment by brandon3055** [comment]
I will be adding support for DM eggs in the next release.
