### ISSUE TITLE
Chaos Island Explosion Doesn't destroy all blocks

### ISSUE THREAD

**Issue by SpellMaster20** [brandon3055/Draconic-Evolution#541]
I have fought the Chaos Dragon a few times now and one thing I have seen happen a lot is that the Guardian Crystals are still remaining. I know that lightening does happen after the guardian is killed but it only seems to destroy some of these crystals not all. Thought you should know :)

Cheers Spell_Master

**Comment by brandon3055** [comment]
The chaos guardian is very broken in 1.10 and needs to be re written.
