### ISSUE TITLE
Reimplement the "Lock Flight" option for the Draconic Chestplate 

### ISSUE THREAD

**Issue by iirelu** [brandon3055/Draconic-Evolution#543]
This was a great feature for me back when it existed in 1.7, but it seems like it hasn't survived the port to 1.10. I'd love to see it return.

**Comment by brandon3055** [comment]
Consider it done!

**Comment by kz5ee** [comment]
Awesome work on an EPIC mod!  Not a big deal, just FYI, in the config GUI the Flight lock button is labelled "config.field.armorFlightLock.entry".

![flightlock](https://cloud.githubusercontent.com/assets/5105197/23059701/2ed1c970-f4c0-11e6-81db-03870c7df3dc.png)
