### ISSUE TITLE
Draconic Evolution Particals Causing Crash

### ISSUE THREAD

**Issue by dovahkiin4991** [brandon3055/Draconic-Evolution#544]
When I'm imputing large amount of rf into the energy core or out of on my server I get "A fatal error has occurred, this connection is terminated". This also happens to others who are near the particles. I have tried several different video setting as well as with optifine but I still get the issue
BrandonsCore-1.10.2-2.1.3.82
Draconic-Evolution-1.10.2-2.0.6.157-universal

**Comment by dovahkiin4991** [comment]
I only crash when the output exceeds 3krf/t please respond on how to fix this I continually keep crashing

**Comment by covers1624** [comment]
Without a crash report we can't do anything. It's like walking in to a VCR repair shop accross the world staying my VCR is broke plz fix..

**Comment by dovahkiin4991** [comment]
its not closing the client or server so its not generating a crash report but this is the log of what the ftb consol window created from the "crash" http://pastebin.com/qxJGQxz1 btw this is in the direwolf20 pack

**Comment by covers1624** [comment]
Dupilicate of #539

**Comment by covers1624** [comment]
Wait, #538 not the other one :P
