### ISSUE TITLE
Dragon Heart registers itself to Entity.class DataManager

### ISSUE THREAD

**Issue by williewillus** [brandon3055/Draconic-Evolution#545]
This causing offsets in all subclasses of Entity, possibly affecting Botania in multiple ways (https://github.com/Vazkii/Botania/issues/2114).

We shouldn't be adding datawatcher to entity classes that aren't ours, and it seems like this one was an oversight [here](https://github.com/brandon3055/Draconic-Evolution/blob/0e512adb1d7762b6aa242e64c808ddf1a0320fb1/src/main/java/com/brandon3055/draconicevolution/entity/EntityDragonHeart.java#L24)

That should be `EntityDragonHeart.class` not `Entity.class`

Thanks!

**Comment by covers1624** [comment]
#datclasscommentdoe.
Seems like a simple fix, ill push it.

**Comment by covers1624** [comment]
Can you try with: http://chickenbones.net/maven/com/brandon3055/draconicevolution/Draconic-Evolution/1.10.2-2.0.7.167/

**Comment by williewillus** [comment]
unfortunately, I haven't been able to reproduce it myself. it's a bug either way, so I'll just have to wait and see until the next versions get in SF/DW20

**Comment by chris54721** [comment]
Just tested, no longer crashing on Sky Factory 3.0.4!

**Comment by KnightI3T** [comment]
This issue has been fixed for version 1.10.2
Is there a fix for version 1.7.10?

I'm playing modpack Divine Journey and have next crashlog: https://pastebin.com/mQNmAETp
I think the error is related to the current topic.

**Comment by williewillus** [comment]
No, this issue doesn't apply to vanilla versions 1.8 and below, because the data watcher doesn't work the same way in those versions. This isn't your problem most likely
