### ISSUE TITLE
[1.7.10] Ender Arrows don't work

### ISSUE THREAD

**Issue by TimeConqueror** [brandon3055/Draconic-Evolution#546]
Using Draconic or Wyvern Bow, I can't throw these arrows. Says "Out of Arrows!!!".

![image](https://cloud.githubusercontent.com/assets/25156941/21993081/159956e8-dc2a-11e6-8231-6c4379a1f7bb.png)

**Comment by brandon3055** [comment]
I dont think i ever re implemented those after i re wrote the bows. I will add that to my 1.7.10 todo list
