### ISSUE TITLE
"You need a more powerful dislocator to do that"

### ISSUE THREAD

**Issue by Ricket** [brandon3055/Draconic-Evolution#547]
I have an Advanced Dislocator, I tried to use it on a friend so they crouched down (held shift) and I left-clicked on them. But all that happens is it says "You need a more powerful dislocator to do that" in my chat. I can't figure out why, it always says that message, no matter how nearby the warp spot is.

Version is Draconic-Evolution-1.10.2-2.0.6.157-universal, in modpack Direwolf20-1.10 v1.3.2.

**Comment by SimonSoby** [comment]
Still bugged on 168

**Comment by brandon3055** [comment]
Will be fixed in the next release.
