### ISSUE TITLE
Draconic Tier Energy I/O, low transfer rate ?

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#548]
Adding a "?" at the end as I am not sure if something this expensive is only suppose to transfer 20k RF/t max. I'd have expected higher. So, using AA Extreme Energy Relays or Solar Flux Reborn Ultimate Cables I can get, between the reactor and the Tier 7 Energy Sphere, close to 60k RF/t going into the sphere. I swap the AA Relays out for two Draconic Energy I/O (the draconic tier that is, the final tier until chaos is released) and now it's down to 20k RF/t into the sphere. Admittedly I had to do some jury rigging as Extreme Reactors don't support the Energy I/O natively *yet* (hopefully soon, I already brought up that issue on their forums) so I used a piece of Ultimate Cable (unlimited RF/t, like cryo fluxducts from 1.7.10 Thermal Ducts) between the reactor (and that made the energy tap light up green) and the Draconic Energy I/O. >.<

**Comment by brandon3055** [comment]
Can you show me your setup? The more crystals the energy has to go though the lower the throughput but for draconic tier crystals the throughput starts at around 30MRF/t.

**Comment by Morpheus1101** [comment]
I connected a 20x20x15 Extreme Reactor to an Energy Pylon via Draconic Energy I/O Crystals into a T8 Energy Core and it was Transfering a lil over 157k rf/t no issues at all.
![2017-02-09_23 44 54](https://cloud.githubusercontent.com/assets/10524952/22785926/0920701c-ef22-11e6-92d4-bdd01155ca02.png)

**Comment by llloyd4** [comment]
Ok, then it's my setup, let me update Extreme Reactors and see if it
actually will connect to the crystals now. When I first started to use DE
the little light above the port would stay red and not transfer power. >.<

**Comment by Morpheus1101** [comment]
On mine it stays red as well, but still transfers power

**Comment by llloyd4** [comment]
It's suppose to turn green. O.o Odd.

**Comment by Morpheus1101** [comment]
this is something not from DE but Extreme Reactors itself
