### ISSUE TITLE
Infusers lose recipes

### ISSUE THREAD

**Issue by mrgreaper** [brandon3055/Draconic-Evolution#549]
Ok so here is a wierd issue,
i updated all the mods on my 1.10.2 minecraft instance and i lost all infuser recipes....first thought was aha draconic evolution is broken, so went to my backup and updated draconic evolution ...recipes worked...updated jei still recipes..... started updating mods one by one until the recipes failed (8 hours of this) eventually i updated refined storage and the BAM no infusion recipes. 
so i downgraded refined storage ....the recipes stayed gone.
i went back to my back up and updated a few mods up to refined storage to get to the same point where i was before and the recipes again did not work! disabled the updated mods one by one to see what it could be...more bees and mob grinder utils mods disabled allowed me to see the recipes again .... ok close the client and reloaded... recipes gone again
go back to my fully updated client and tried to load that again...4 times in a row every time the recipes were gone.
so i added a custom recipe file with the default code from the txt file 
[
    {
        "mode": "ADD",
        "result": "[minecraft:beacon]",
        "catalyst": "[minecraft:nether_star]",
        "energy": 1000,
        "tier": 1,
        "ingredients": [
            "[minecraft:glass]",
            "[minecraft:glass]",
            "[minecraft:glass]",
            "[minecraft:glass]",
            "[minecraft:glass]",
            "[minecraft:obsidian]"
        ]
    },
    {
        "mode": "ADD",
        "result": "2x[minecraft:golden_apple]:1",
        "catalyst": "2x[minecraft:golden_apple]",
        "energy": 1000,
        "tier": 1,
        "ingredients": [
            "[oreGold]",
            "[blockGold]",
            "[ingotGold]",
            "[nuggetGold]"
        ]
    },
    {
        "mode": "REMOVE",
        "result": "[draconicevolution:draconic_staff_of_power]",
        "catalyst": "[draconicevolution:draconic_pick]",
        "ingredients": [
            "[draconicevolution:draconic_ingot]",
            "[draconicevolution:draconic_ingot]",
            "[draconicevolution:draconic_ingot]",
            "[draconicevolution:draconic_ingot]",
            "[draconicevolution:draconic_ingot]",
            "[draconicevolution:draconic_shovel]",
            "[draconicevolution:draconic_sword]",
            "[draconicevolution:awakened_core]"
        ]
    },
    {
        "mode": "REMOVE",
        "result": "[draconicevolution:draconic_shovel]",
        "catalyst": "[draconicevolution:wyvern_shovel]"
    }    
]

loaded up minecraft.... still no recipes in the infuser (pressing the R in the infuser block) still no infuser recipes in jei and the tablet also showed recipe not found error for the tier 2 infusers.

at this stage im stumped, it is only draconic evolution that is effected and only the infusion recipes. 
i have tried different forge versions, different mdo set ups (clearly its not playing nice with a specific mod...likely a couple of mods as sometimes i can disable a mod and they work but i can reload it with the same set and POW no infusion recipes) been tearing my hair out for 8 hours last night and a bit more today. I did try to get assistance on the irc channel as im not sure an issue is the right way to go (since de updated by itself appears to work ok....but then it is the only mod in my entire pack that has this issue and it is only the infuser.....but rolling back the versions did not fix it ...arghhhhhhh its an error i have no idea how it can be, worse yet nothing in my logs even hint at there being an issue)

**Comment by mrgreaper** [comment]
hmmm possible solution, i deleted the config folder and now i have my recipes back (loaded twice in a row to check) 
That would explain why updating the mod then downgrading it had no effect...but does not explain why only this mod is effected or why its not effected if just this mod is updated...its one of the most bizarre bugs i have ever come across

**Comment by mrgreaper** [comment]
and they just disapeared from our live server again
https://s23.postimg.org/a3s440quz/2017_01_20_00_20_48.png

**Comment by netzgeist** [comment]
I am facing the exact same issue.

**Comment by brandon3055** [comment]
I am currently looking into this issue aswell but i am almost as confused as you. It looks like it may have something todo with the latest version of IE... Or ModTweaker... Or the curse launcher.... or something else entirely....

https://github.com/Drakma/VacantSky/issues/55
