### ISSUE TITLE
Client crash on making an AM2 spell after using the enhanced charm of dislocation.

### ISSUE THREAD

**Issue by ProsperCraft** [brandon3055/Draconic-Evolution#55]
http://pastebin.com/DHjDbEZ0

Not repeatable.
Multiplayer
Tolkiencraft 2 - 2.4.8

**Comment by brandon3055** [comment]
I believe that is actually a crash that happens when you bind a basic dislocator and should have nothing todo with AM2. 
If that is the case it has been fixed in RC 3.
