### ISSUE TITLE
Fusion recipes do not display in JEI with latest version

### ISSUE THREAD

**Issue by Saereth** [brandon3055/Draconic-Evolution#550]
As per title, custom fusion recipes are not showing in JEI. they do however actually work if you somehow know the recipe and manually enter the items. Here is a screenshot of the item being craftable but no recipe shows in JEI.
http://imgur.com/a/j7BVP

custom fusion recipe file contents:
https://hastebin.com/orawiqadiz.json

JEI Version: http://imgur.com/a/j7BVP
Draconic Evolution version: 1.10.2-2.0.7.168-universal

**Comment by oks1998** [comment]
ya, my JEI also didn't show the recipe for fusion crafting.
JEI 0.9.0.4
Draconic: 1.10.2-2.0.7.168

**Comment by brandon3055** [comment]
If it works it should show up in jei... Are you testing in singleplayer, multiplayer or both? If both do they both give the same result?

**Comment by Saereth** [comment]
I tested in both SSP and MP and they both give the same result, the custom recipes do not show in JEI but they do work if you attempt to manually craft.

**Comment by brandon3055** [comment]
Hmm i will have to look into that. It must be an issue out of dev because they work fine in dev for me http://ss.brandon3055.com/gqsqwru.png

**Comment by Saereth** [comment]
Actually, I need to relabel this bug report, it appears no fusion recipes show up at all, this includes standard fusion recipes after I completely removed my custom ones and restarted. This is in SSP I have no way to test these changes in MP atm. So basically as it stands

Draconic Evolution version: 1.10.2-2.0.7.168-universal
JEi version: jei_1.10.2-3.14.3.403

Video of the issue:
https://www.youtube.com/watch?v=TMf7jv9Dxcc&feature=youtu.be

Further testing shows no fusion recipes are showing for me in JEI even with custom fusion json file removed. 

This issue didnt exist before I updated BrandonCore/DE and JEI today.

**Comment by redbaron148** [comment]
I had the same issue after updating some of the other mods in my private modpack.  The culprit seemed to be immersive engineering version 0.10 - 55.  After downgrading back to 0.10 - 54 the fusion recipes showed up in NEI again.  

However, when I tried verifying these were the only requirements in a separate instance of minecraft with only DE, JEI, and IE, the recipes showed up.  It must be a conflict between multiple mods combined with the latest version of immersive engineering.  I can provide the link to the modpack I was using on request.  

Attached is the list of mods used to create the issue.

[modlist.txt](https://github.com/brandon3055/Draconic-Evolution/files/722247/modlist.txt)

**Comment by JackOverlord** [comment]
Can confirm what redbaron said.
Downgrading IE certainly helped.

**Comment by Sanaradain** [comment]
I have some more information that might help with this issue:
I was playing Sky Factory 3 and a mod create a NBT tab that was too long, to fix this issue, I disabled the WAILA Mod that is in the Pak "HWYLA" and I could see the fusion recipes again.  I'm not completely sure this is the culprit, but hopefully helps narrow down the issue.
