### ISSUE TITLE
Breaking Any Energy crystal (IO, Wireless, Relay) returns a basic crystal of the same type.

### ISSUE THREAD

**Issue by JonoColwell** [brandon3055/Draconic-Evolution#551]
When breaking an Energy Crystal with a pickaxe, silk or not, it will return a crystal of the correct type of the basic tier rather than the correct tier

Draconic Relay Crystal
http://puu.sh/ttWxa/4b8be7b590.jpg

When broken with silk touch pickaxe gives Basic Relay Crystal
http://puu.sh/ttWyw/07d1b76373.jpg

Modpack is All The Mods 

DE Version: Draconic-Evolution-1.10.2-2.0.5.154-universal

**Comment by covers1624** [comment]
Fixed in later builds, yell at your modpack to update.
