### ISSUE TITLE
Energy Core duplication glitch

### ISSUE THREAD

**Issue by Edward-Akers** [brandon3055/Draconic-Evolution#554]
Version: 1.10.2-2.0.6.156
Replicability: I am able to successfully reproduce this bug.
Steps to produce:
1. Create an Energy Core, in my case it's a tier 7 and I have not tried this with other tiers.
2. Place a block under the Energy Core, in my case it was a Wyvern Energy Relay Crystal. And I was able to reproduce the bug using a Draconic Energy Relay Crystal.
3. Get a Staff of Power. In my case this was the one I used:  
* Enchantments/Upgrades: http://i.imgur.com/Cda1QX0.png 
* Profile: http://i.imgur.com/DTld0Di.png
4. Destroy the Energy Relay Crystal [or chosen block] underneath so that it will destroy the ACTIVE Tier 7 Energy Core.

I have not tested this bug in single player but only in multiplayer. If you require further information you can find me on lolnet by the name of WintrAU

**Comment by brandon3055** [comment]
This may be fixed in the latest version.
