### ISSUE TITLE
[1.10.2][Documentation/Tablet] Tier 8 Energy Core requirements need update

### ISSUE THREAD

**Issue by proto-chris** [brandon3055/Draconic-Evolution#555]
The documentation for the Energy Core is in dire need of an update to reflect the change made in 2.0.5.154 from Awakened Draconium blocks to mostly Draconium blocks to prevent people to needlessly farm 1.1k Awakened Draconium blocks after reading the tablet.

**Comment by brandon3055** [comment]
This has been done.
