### ISSUE TITLE
Draconic Reactors not powering up properly after server restart

### ISSUE THREAD

**Issue by ToXIQuE** [brandon3055/Draconic-Evolution#556]
Hi guys, I know this is going to be awful, but I dont actually do your mod myself, I have a few players on the server that do though, they say after a server restart the reactors just wont power up properly and the heat gets stuck at 2000C and wont go any further. The server is 1.7.10 so I know its not great to ask for support for it, but I thought Id try!

Really appreciate any insight, and please let me know what firther information that I can give you.

Version: Draconic-Evolution-1.7.10-1.0.2h

**Comment by covers1624** [comment]
What server software are you running? If you are using something like KCauldron i recommend you move to Thermos. Also, are you able to provide us with a list of the mods / plugins running on your server.

**Comment by ToXIQuE** [comment]
Heya covers1624

Yep i am running kCauldron indeedie!

My plugins are here: http://pastebin.com/S8WS2WU0
My Mods are here: http://ultim8arkitekts.enjin.com/forum/m/41508603/viewthread/29190558-list

To get them all working nicely together I kinda had to use kCauldron, but Ill look into thermos, I havent tried it before. You reckon that will fix the issue?

**Comment by covers1624** [comment]
I'm a moderator on a large Australian / New Zealand public mc network, Lolnet, They have used Thermos for all their public 1.7 servers and it has been extremely stable for them.
