### ISSUE TITLE
21 trillion rf/t power Dup / self generation

### ISSUE THREAD

**Issue by Kevincav** [brandon3055/Draconic-Evolution#557]
So I am creating 21 trillion rf/t from a tier 8 battery and only the battery.  I did this by pushing power through multiple energy pylons.  After that I send power through more energy pylons (less power) which then pushes power back through the input.  This creates an infinite loop of power.  All you need is the initial jump start from an external source.  Below are pictures of my setup.  The right side is the output and top and bottom are inputs.  This is using flux cables.

![Setup](https://cloud.githubusercontent.com/assets/3166198/22195148/57e811f8-e0fb-11e6-8219-f0062172f230.png)

![Power transfer example](https://cloud.githubusercontent.com/assets/3166198/22195166/6a006b10-e0fb-11e6-9632-e6285aa9123a.png)

**Comment by Kevincav** [comment]
And filled the "near infinite" battery in less than 8 hours.

![2017-01-23_09 03 30](https://cloud.githubusercontent.com/assets/3166198/22214531/c3b67478-e14c-11e6-89d8-7928740aa9eb.png)

**Comment by brandon3055** [comment]
What are the blocks you are using to transfer energy? Simply creating an infinite loop should not do this. I suspect there is something else going on here. Could be related to an issue with the pylons that will be fixed in the next release.

**Comment by brandon3055** [comment]
Just did some testing and it seems the Flux Networks mod is a steaming pile of bugs. Switch to a different energy network and see if this still happens.
