### ISSUE TITLE
Energy Crystal Bugs

### ISSUE THREAD

**Issue by Edward-Akers** [brandon3055/Draconic-Evolution#560]
After using the Energy Crystal I have found the following bugs:

1. Visual glitch with the particle line extending from the selected Energy Crystal to the selectee remains when you change the selected Energy Crystals link as it's active.
2. When having selected an Energy Crystal, breaking the Energy Crystal and then swapping back to the Crystal Binder reveals a see-through red block in place of the Energy Crystal (possible feature since it's bound to coordinates?)

**Comment by brandon3055** [comment]
Not sure exactly what you mean with the first issue. Can you tell me how to reproduce the issue?
Regarding the red box. As you suspected that just indicates that the block the binder is bound to is invalid.
