### ISSUE TITLE
Energy Shield is triggering WAY too fast.

### ISSUE THREAD

**Issue by Anaerin** [brandon3055/Draconic-Evolution#561]
When taking damage, even from a fixed source (like an Ender Lily), the shield is blocking (and increasing the EN) every tick, rather than every second. This means that the EN fills SUPER fast (within 5 seconds), and then takes forever to decrease. It also means that incoming damage is unbearably loud, as each time it triggers it plays the sound.

Earlier versions only triggered when you'd take damage (every second) which is much more reasonable.

Mod version: 1.10.2-2.0.7.168 (DireWolf20 1.10 pack, v1.4.1).

**Comment by brandon3055** [comment]
I am going to re write the shield after i re write the chaos guardian.
