### ISSUE TITLE
Recipes gone v2.0.7.168

### ISSUE THREAD

**Issue by BlueConfetti** [brandon3055/Draconic-Evolution#563]
I noticed in Guide-API there's no fusion crafting recipes, nor are they in the in-game tablet guide. I don't think this is local. Reinstalling the mod and modpack did not fix the issue.

**Comment by BlueConfetti** [comment]
Just realized this issue has been addressed.

**Comment by mrgreaper** [comment]
it has? i reported it over a week ago and no response or fix, did i miss a fix?

**Comment by BlueConfetti** [comment]
I meant that brandon has addressed it as an issue, not that it has been resolved.
