### ISSUE TITLE
Draconic Evolution Energy Infuser 

### ISSUE THREAD

**Issue by ckwebdev** [brandon3055/Draconic-Evolution#565]
The device will not accept any input. I'm try to charge some draconium blocks and it will not allow me to insert it. I'm playing Sky Factory 3 with the most recent Draconic Evolution mod 1.10.2-2.0.7.168. Also tried previous version 1.10.2-2.07.166 & 1.10.2-2.06.157 with the same results. Am I missing a step or something. Playing survival. Its fully charged and connect to several generator and power cells.

![infuser](https://cloud.githubusercontent.com/assets/22624134/22389401/43aee1d8-e4b3-11e6-9704-0bccd10b899b.png)

![infuser2](https://cloud.githubusercontent.com/assets/22624134/22389439/7ed052d8-e4b3-11e6-85da-c38c10b2842e.png)

**Comment by georgo** [comment]
This machine is used to charge armor, tools etc., not to charge blocks. Use Fusion crafting instead.

**Comment by brandon3055** [comment]
Correct. Awakened draconium is now made via fusion crafting. Although there is currently an issue in SF3 that is preventing fusion recipes from showing in JEI so here is the recipe. http://ss.brandon3055.com/e27uktt.png
