### ISSUE TITLE
[Netty Client IO #3/ERROR] [FML]: There was a critical exception handling a packet on channel DEvolutionNC

### ISSUE THREAD

**Issue by DigTK** [brandon3055/Draconic-Evolution#566]
Using FTB Infinity Lite 1.5.1 (1.10.2)

I have a Draconic Wireless Energy Crystal hooked up to a bunch of Mekanism and EnderIO machines and sometimes it disconnects my client with this error. Seems to be related to machines starting up or something, can't exactly pinpoint it.

Attached is the full error log
[errorlog.txt](https://github.com/brandon3055/Draconic-Evolution/files/736662/errorlog.txt)

**Comment by DigTK** [comment]
Turns out it's not just the Wireless Energy Crystal. I removed all the Wireless ones and I'm using only Relay Crystals and I/O Crystals and it's still happening :(

**Comment by brandon3055** [comment]
What version of DE are you using? That issue should be fixed in version 2.0.7.166

**Comment by DigTK** [comment]
I believe the version of Infinity Lite I was using at that point had DE version 2.0.6.157 in it. We just upgraded to the newest Infinity Lite version which updated DE to 2.0.7.168 and the bug hasn't reappeared since then.

I think we can consider it fixed, I'll reopen this issue if it happens to occur again.

Thanks! :)
