### ISSUE TITLE
Unable to see recipe for Advanced Dislocator

### ISSUE THREAD

**Issue by Mirandomness** [brandon3055/Draconic-Evolution#567]
I am unsure why its not showing up.

**Comment by brandon3055** [comment]
Are you playing skyfactory? If so there is currently an issue that is preventing fusion recipes from showing up.

**Comment by davelien** [comment]
Workaround in SF3 is to downgrade Immersive Engineering to version 0.10-54

**Comment by RebelNode** [comment]
FYI Same issue is now also in FTB Infinity Lite.
