### ISSUE TITLE
Donator wings bug

### ISSUE THREAD

**Issue by Edward-Akers** [brandon3055/Draconic-Evolution#568]
I noticed that my donator wings were not showing up so I looked into it and they're not being added until you enter single player - it is possibly fixed in later versions but I'm running 1.10.2-2.0.6.157.

**Comment by brandon3055** [comment]
Have you checked if your wings are just disable when you join a server? The state is now saved server side and its possible its set to disabled by default.

**Comment by brandon3055** [comment]
This should be fixed in the next release.
