### ISSUE TITLE
no Recipie for the Wyvern core

### ISSUE THREAD

**Issue by CamaroKing59** [brandon3055/Draconic-Evolution#569]
https://gyazo.com/bea0650743110dd98cc55b3a6e346b89

what happened?

**Comment by brandon3055** [comment]
Im guessing your using skyfactory? There seems to be an issue in skyfactory that is preventing fusion recipes from showing up. I am currently looking into it.

If you are not playing skyfactory please let me know what pack you are using.

**Comment by brandon3055** [comment]
If so this is a known issue that is proving very difficult to fix. If you can try rolling back immersive engineering to build 54 as that has been known to fix the issue in some cases. Other than that please be patient this issue will be fixed when it is fixed (Note the crafting is still possible its just JEI integration thats broken)
This is a pre written response.
