### ISSUE TITLE
Upgrades are lost during the upgrade from Wyvern to Draconic

### ISSUE THREAD

**Issue by taj1994** [brandon3055/Draconic-Evolution#571]
This was mentioned as fixed in the changelog for version 1.10.2-2.0.7.166, but I'm using version 1.10.2-2.0.7.168 and I'm losing the upgrades I had applied.

I'm using the pack [All the Mods](https://minecraft.curseforge.com/projects/all-the-mods), version 1.58

**Comment by brandon3055** [comment]
Can you tell me what you were upgrading and what upgrades it had. I have tested both armor and tools and they seem to work just fine.

**Comment by taj1994** [comment]
The entire armour set, and I believe they had wyvern tier upgrades for everything except RF capacity, which was draconic

**Comment by brandon3055** [comment]
Hmm...
http://ss.brandon3055.com/qhzrfq9.png
http://ss.brandon3055.com/2nx2u00.png
I have no idea... Can you test this is a creative world and see if you can reproduce the issue?

**Comment by taj1994** [comment]
Sure. I'll test it in about 15 or 20 minutes and get back to you with the results

**Comment by taj1994** [comment]
Weird. It worked in creative just now, but I lost all the upgrades when I did it on my server last week...

**Comment by brandon3055** [comment]
Odd... Will just have to keep en eye out for issues like this in the future.

**Comment by dmodoomsirius** [comment]
hey @brandon3055 I watched a streamer who is currently experiencing this issue as well. Noticed it happened on the bow. The modpack is FTB Beyond.
