### ISSUE TITLE
[1.10.2] Tablet Recipes

### ISSUE THREAD

**Issue by Moxiesan** [brandon3055/Draconic-Evolution#572]
It was working initially, but in the current FTB SkyFactory 3, I no longer see any fusion recipes when viewing in the tablet. Any known way to fix this? (My wife's sees it fine, so i'm really confused).

Is there a place where variables might be set for my character that I can possibly reset or delete it?

NOTE: This is ocurring on both single player and my server for me.

**Comment by brunocassol** [comment]
I also can't see fusion recipes on latest Skyfactory 3.0.6 with DE 2.0.7.18.

**Comment by brandon3055** [comment]
Does it give you any sort of message where the recipe should be? (Can you provide a screenshot)
I would also like your see your log after you open the tablet for the first time (It loads everything the first time you open it)

**Comment by brunocassol** [comment]
When I click Draconic Fusion Crafting Injector it does nothing. No error, no log, nothing is shown. This is the screenshot:
![image](https://cloud.githubusercontent.com/assets/203541/22622650/e15d153c-eb1e-11e6-9c50-d8e2ac5f971c.png)

I started a new world, gave myself the tablet and it still didn't display fusion recipes in JEI. This is the recorded gif:

![draconic_no_fusion_recipe](https://cloud.githubusercontent.com/assets/203541/22622936/5d5b35fc-eb28-11e6-9f0a-a0550c85d8e3.gif)

Not sure if this helps but this is my mid-game 19mb world save file plus config (I did some minor changes):
https://drive.google.com/file/d/0B3cp84cuja2LMXRLdVhWck9fTkU/view

**Comment by brunocassol** [comment]
I probably left out the most important info:

![image](https://cloud.githubusercontent.com/assets/203541/22623322/5f760526-eb35-11e6-8016-3da8ff20d630.png)

**Comment by SatsukoIzanami** [comment]
I've been having the same issue.  I've been running the server for about 9 days.  4 days ago, I started on draconic evol. building.  All the recipes I needed were there.  The next day, they weren't.  Reload FTB, it was fine.  Yesterday, gone again.  Reload FTB, fine.  Today, gone again.

**Comment by brunocassol** [comment]
The fusion recipes are showing again after I reinstalled ftb and Sky Factory.

Steps to fix assuming you installed in c:/ftb:
- backup these 2 folders: `C:\ftb\FTBPresentsSkyfactory3\minecraft\config` and `C:\ftb\FTBPresentsSkyfactory3\minecraft\saves` to somewhere safe like your Desktop folder
- delete c:/ftb and run FTB_Launcher.exe again to download and start Sky Factory 3.0.6
- copy back the folders you
- start Sky Fatory 3. Your world should be there and the fusion recipes will be showing again. You'll have to redo any custom keyboard config.

I created a git repo in /config to monitor what files change in case the fusion recipes stop showing again.

**Comment by brandon3055** [comment]
AH HA!! Pylon + Energy crystal = bad. Now to figure out why...

**Comment by YOYOK9** [comment]
@brandon3055 Hello I am having this same issue with fusion crafting not showing up for wyvern and higher, However I am not using Skyfactory 3. I am using a Technic modpack (Business Elite-Plus) .

**Comment by davelien** [comment]
Workaround in SF3 is to downgrade Immersive Engineering to version 0.10-54

**Comment by brandon3055** [comment]
This is a known issue that is proving very difficult to fix. If you can try rolling back immersive engineering to build 54 as that has been known to fix the issue in some cases. Other than that please be patient this issue will be fixed when it is fixed (Note the crafting is still possible its just JEI integration thats broken)
This is a pre written response.

**Comment by brunocassol** [comment]
Thanks for the update @brandon3055. This is not critical so please take your time.

Meanwhile, for those that are affected, someone posted the recipes on Reddit:

https://www.reddit.com/r/feedthebeast/comments/5s72jo/sf3_draconic_evolution_fusion_crafting_recipes/

**Comment by brandon3055** [comment]
I have finally been able to track this back to an EXACT cause which is an issue with one of IE's recipe categories. I have made the author aware of the exact problem and he will fix it as soon as possible.

**Comment by brunocassol** [comment]
Amazing. The amount of debugging and hair pulling that probably went to fix this must be huge.

Thank you.
