### ISSUE TITLE
Bug in Energy Core GUI when shift-clicking an item stack (Draconic-Evolution-1.10.2-2.0.7.168)

### ISSUE THREAD

**Issue by TractoBoy** [brandon3055/Draconic-Evolution#575]
Hello,

I'm playing SkyFactory 3.0.5 (Draconic-Evolution-1.10.2-2.0.7.168-universal.jar), I was setting up my T7 energy storage when I shift-clicked an item stack (redstone blocks) while having the energy core GUI open.
I just wanted the stack to go into my hand to place them after closing the GUI.

Here's the log : 
http://pastebin.com/xyjD1c0t
Quite long because of an "infinite" loop before call stack gave up.

**Comment by brandon3055** [comment]
Will be fixed in the next release.
