### ISSUE TITLE
Chaos Guardian disappeared

### ISSUE THREAD

**Issue by madmacf** [brandon3055/Draconic-Evolution#578]
Using most updated skyfactory 3.0

When flying too far away from the chaos guardian, it disappeares. It never reappears. Chaos crystal the not harvestable. 
At one point when going to another island. There was 2 guardians.

**Comment by 1matto** [comment]
I had a similar problem stated in issue #559

**Comment by brandon3055** [comment]
This is a known issue. The chaos guardian still needs a complete re write. I will be doing this around the same time i update the reactor. There is currently no real reason to fight the chaos guardian other than just for fun.

**Comment by madmacf** [comment]
Allright. Thanx for the reply. Keep up the good work :-)
