### ISSUE TITLE
unable to break chaos crystals

### ISSUE THREAD

**Issue by goodmangammering** [brandon3055/Draconic-Evolution#580]
hello im playing skyfactory 3 on default configs server and i just beat the chaos dragon but when i went to break the chaos crystals they acted like bedrock level hardness. i am using a draconic staff of power and im aiming at the area in which wailia sais the crystals are.  some of my friends on the server have been able to break the crystal under the same circumstances.

**Comment by brandon3055** [comment]
The chaos guardian still needs to be re written. But there is currently no reason to fight it other than for fun atm because the shards are not used fort anything yet. 

Does the crystal still have a red shield around it? If so that means for whatever reason the shield was not removed when the guardian was killed. If it does not then you should be able to break it.

**Comment by goodmangammering** [comment]
in sky factory three there is a use for it, and yes it does still have the red shield around it , should i just try fighting a second one to see if it is just that dragon ?

**Comment by brandon3055** [comment]
Ahh darn it Bacon lol. Yea your best bet would probably be to try another guardian. Or get an admin (assuming you are not an admin) to just give you 5 shards.

**Comment by brandon3055** [comment]
Actually i will leave this open for anyone else that has the same issue.

**Comment by 016Nojr** [comment]
Can confirm this, however. When I started the fight it spawned in a second guardian so I had to fight two dragons.

**Comment by AlchemicalChest** [comment]
And also, the guardian will disappear during the fight, especially when it try to fly away from the chaos island.

**Comment by shank3001** [comment]
I had the same issue in the FTB Direwolf20 1.10.2 pack. Two dragons spawned. I beat the first one, got whacked by the second one because I ran out of juice. Got back to my base reloaded and killed the second dragon. The red shield was still in place and I could not get the shards, but I got a ton of dense obsidian :)

**Comment by AstroxV** [comment]
Every guardian i fight, the first thing i do is chunkload the area, it seems to help with it despawning when you get out of range. Try placing down a chunkcloader of your choice, and then start the fight.

**Comment by AnsuzThurisaz** [comment]
SF 3.0.8 here: there are no chaos crystal on ANY of my chaos islands. I manually placed one in creative after killing a guardian in survival, placed it in the center and nothing came out. The island detonated (almost killed me). I checked the other three Islands I have found and and none of them have a protected chaos crystal in the center.

**Comment by brandon3055** [comment]
The issues with the guardian should be fixed in the next DE release.

**Comment by 21harrisont** [comment]
It wasn't fixed yet

**Comment by 21harrisont** [comment]
It still dosen't work in sky factory 3!

**Comment by AnsuzThurisaz** [comment]
SF 3 updates it's mods separately. If something is broken, you will have to manually update or ask Bacon_Donut to update the pack.

**Comment by AnsuzThurisaz** [comment]
Most recent version of DE and Bcore have been great for me for weeks. Even got the new reactor fully stable. If SF3 hasn't updated yet, again, you need to report this to the Sky Factory 3 issue tracker.

**Comment by AnsuzThurisaz** [comment]
Most recent version of DE and Bcore have been great for me for weeks. Even got the new reactor fully stable. If SF3 hasn't updated yet, again, you need to report this to the Sky Factory 3 issue tracker.

**Comment by 21harrisont** [comment]
I can't get chaos dragon

**Comment by MasterShley** [comment]
Just to make sure I'm on the same page. The 1.7.10 version (1.0.2h), doesn't have the Reactor available? And you can't break the Chaos Shard?

**Comment by covers1624** [comment]
1.7.10 HAS the reactor and you CAN break ChaosShards, We are talking abort the 1.10 version here.

**Comment by covers1624** [comment]
Regarding comments on things still not working, UPDATE YOUR MODS PLEASE!
