### ISSUE TITLE
Crystal binder shift right clicking not changing modes

### ISSUE THREAD

**Issue by iKoogar** [brandon3055/Draconic-Evolution#582]
I'm on the default sky factory 3.0 pack and I've tried this in creative too.

**Comment by Anaerin** [comment]
It should be shift-right-clicking with an empty hand to change the mode of the IO Crystals, IIRC.

**Comment by iKoogar** [comment]
I hate everything, thank you

**Comment by Exanadu** [comment]
I am having this issue except shift+right click with an open hand isn't working to change the modes of the IO Crystals. Using the Direwolf 1.7.1 modpack for 1.12.2
