### ISSUE TITLE
[Feature] Painting Energy Crystals (Cosmetic)

### ISSUE THREAD

**Issue by Lukas45** [brandon3055/Draconic-Evolution#583]
I love to use the Energy Crystals for cosmetic for various things, and is therefor my favorite go-to power transfer, but the color can often be offsetting.
![2017-02-07_13 45 37](https://cloud.githubusercontent.com/assets/4707702/22691745/2868e8d8-ed3c-11e6-8979-3d9c636975f1.png)

I know that currently the colors are used to define the 3 tiers (Blue, Purple, Orange), but maybe that could change?
The tiers could be defined by color+slight model/particle change, or maybe that's not needed at all.
I just want to color them for cosmetic purposes :D

**Comment by brandon3055** [comment]
Hmm... will add it to the "Possible future features" list but cant promise anything.
