### ISSUE TITLE
Tier 8 Energy Core Stops accepting power when I travel to another demention

### ISSUE THREAD

**Issue by Doc-O-Love** [brandon3055/Draconic-Evolution#584]
I upgraded my Tier 7 energy storage to a Tier 8 when I filled up the Tier 7. I left the stabilizers and the energy core alone and just replaced the blocks needed to upgrade. The core was valid and I enabled it. Everything looks to be working except the amount of RF stored does not go up and the displayed RF/Tick is 0, however everything is still receiving power out of the pylons and power is going into the pylons and not backing up in my generators. The only way to get the storage increasing again is to break the incoming power pylon and replace it (I need only break and replace the glass on top), after that it works fine until I go to another dimension or log off, at which point it breaks again. all chunks are loaded and I had no issues with the Tier 7

I am running the Direwolf20 1.10 pack on my server and client with Draconic Evolution upgraded to 2.0.7.168.

**Comment by brandon3055** [comment]
This should be fixed in the next release.
