### ISSUE TITLE
Celestial Manipulator stopped working

### ISSUE THREAD

**Issue by mrtomwolf** [brandon3055/Draconic-Evolution#585]
Playing Sky Factory 3 but I've updated a bunch of addons.

Issue: Celestial Manipulator was working. I'm using it with the rain sensor and a not gate to keep a storm as power source.

(not sure if related) I traveled to an rftools dimension and used /weather clear and learned that weather commands doesn't work in those dimensions.

When I came back it was sunny and I couldn't get the Manipulator to change the weather. Commands worked still.

Destroying and replacing didn't work.

When I threw it away and put down a new one, that one worked like a charm.

**Comment by brandon3055** [comment]
This sounds extremely unlikely considering no vital data is stored on the item and i could not find any issues. Fort now i think i will just write it off as one of those random unexplained mysteries. But let me know if it keeps happening and i will take a closer look.

**Comment by PhiPhiper** [comment]
I had a similar issue with trying to change time in an rftools dimension. The celestial manipulator tries to change the time, get's the time get set back a few times and then the timeflow continues as if the manipulator stopped while it still keeps running.
