### ISSUE TITLE
[QUESTION] Enchanting Wyvern Sword

### ISSUE THREAD

**Issue by ckwebdev** [brandon3055/Draconic-Evolution#586]
XP Boost not allowed by design as an enchant for the sword? Able to add vanilla enchants, but not XP boost.

**Comment by brandon3055** [comment]
The sword Should* be able to accept any enchants the vanilla sword can.

**Comment by ckwebdev** [comment]
Its definitely not accepting xp boost in the anvil.

version installed 1.10.2-2.0.7.168

![enchant](https://cloud.githubusercontent.com/assets/22624134/22780949/86923416-ee8e-11e6-8acd-7eb2b630d8ac.png)
![enchant2](https://cloud.githubusercontent.com/assets/22624134/22780981/a3d027ea-ee8e-11e6-91e2-2fb8cc0cb4b9.png)

**Comment by brandon3055** [comment]
Not sure... It may be something on the other mods end. Ether way there isnt really anything i can do on my end. As it is enchants only work at all because of a hack i had to do.
