### ISSUE TITLE
Change Armor Profile

### ISSUE THREAD

**Issue by perryprog** [brandon3055/Draconic-Evolution#587]
Draconic Evolution has the option to name armor profiles, but AFAIK you can't switch between any of them using the hotkey.

The hotkey is working on tools for me, but there seems to be no way to switch armor profiles. If this is intended maybe you could change that? I want to have one normal profile, and another for traveling very fast.

**Comment by brandon3055** [comment]
There is currently no way to change profiles on the armor. The only reason the armor currently has profiles is that they are part of the core config system. I have plans for a new config UI that will allow you to reconfigure the armor but have not gotten around to it yet.

**Comment by perryprog** [comment]
Alright, sounds good.
