### ISSUE TITLE
Creative Mode Fusion Crafting

### ISSUE THREAD

**Issue by perryprog** [brandon3055/Draconic-Evolution#588]
This is just a suggestion - could you add an item that would be creative only, and let you fusion craft without any setup or power. Possible use of this could be in a map where you need a draconic level upgraded item, which would take a good while to craft even in creative.

I was kind of thinking of something where you would right click this item, put the item (like a draconic chest plate) that you want to upgrade inside the GUI, and choose what upgrades you want for that item and what level.

This should be low priority of course, because there are a lot more game breaking bugs out there but it would be nice for you to work on it if you have time. 😄 

**EDIT:** Also, if you had time it would be nice for other sort of creative utilities. Maybe one that could help you visualize/build a reactor or something similar.

**Comment by brandon3055** [comment]
/give @p draconicevolution:debugger
This will give you my debug/test item. Shift right click until it says "Complete Crafting" in chat. Simply right click on a fusion crafting core after you start the crafting process. Be warned this is a test item meant for my own use in dev only so some of its other functions may crash your game or worse. Use at your own risk.

As for upgrading things i can do one better.  
/de_upgrade <upgrade/list/clear> [level]
This command allows you to apply upgrades to the item you are holding. You can use list to see all of the valid upgrades for the item you are holding or just use tab complete until you find it.

**Comment by perryprog** [comment]
Cool. Thanks for the detailed reply.
