### ISSUE TITLE
Power Cap with the reactor.

### ISSUE THREAD

**Issue by Grizzord** [brandon3055/Draconic-Evolution#589]
okay so this is mainly a question which is : in the draconic evolution .cfg the is an EnergyOutputMultiplier= # so my qusetion is. is this cfg capped at ten? from what i can tell it seems to be. if it is not supposed to be apped at ten please let me know.  also some context. i am trying to get a reactor to push 14mil rf/tick but not matter the injection i throw at it i cant get above 10 mil? is this a hard cap in the mod?

**Comment by brandon3055** [comment]
The logic behind the reactor is very complicated and i wrote it a while ago so im not sure how it would react to multiplayer past a certain point. I can tell you i did not intentionally add a hard cap but its possible the logic just cant be pushed past a certain point. I will know more once i re write the reactor for 1.10

**Comment by Mike-RaWare** [comment]
The 10MRF/t limit is in the stabilizer, not in the reactor. If you connect all four stabilizers you can get up to 40MRF/t.

**Comment by Grizzord** [comment]
OH OKAY. thank you
