### ISSUE TITLE
[SUGGESTION] add to the draconic chest

### ISSUE THREAD

**Issue by Goten87** [brandon3055/Draconic-Evolution#59]
will be nice if you can add a slot for trash stuff
so that when we have things in the chest we can drag it to that slot and it gets destoryed
if you want to do it as a upgrade you can combine like the Draconic chest with a trash can to unlock it xD

**Comment by brandon3055** [comment]
I think that would just be a giant pain to incorporate into the gui (referring to the code behind it). but maby i will look into it at some point.
