### ISSUE TITLE
Packet handling exception

### ISSUE THREAD

**Issue by darkrising** [brandon3055/Draconic-Evolution#591]
Hey, I'm running FTB Infinity lite for Minecraft 1.10 and I've come across an issue which is causing me to disconnect from my server.

The pack contains Draconic Evolution version 2.0.6.157 for 1.10.

Here's an exert of the log:
```
[16:09:30] [Netty Client IO #4/ERROR] [FML]: There was a critical exception handling a packet on channel DEvolutionNC
io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: writerIndex(0) + minWritableBytes(286) exceeds maxCapacity(261): UnpooledHeapByteBuf(ridx: 0, widx: 0, cap: 247/261)
```
On my map there's quite a few crystals setup with a Tier 6 storage, in a relatively small space. It's all loaded by a couple IC2 chunkloaders. Beyond that I'm not really sure what's causing the buffer to overflow.

Full stacktrace is here: http://pastebin.com/AT2Q8nP8

Edit: On further testing I removed an io crystal (wyvern tier) from a block of 12 Culinary Generators from extra utils, hooked up with an ender io power conduit, and I've yet to be disconnected.

**Comment by brandon3055** [comment]
This issue has been fixed in later versions. You need to update DE.
