### ISSUE TITLE
Tools don't render

### ISSUE THREAD

**Issue by KoenVW02** [brandon3055/Draconic-Evolution#595]
**# The tools don't render in the inventory, hand or in JEI**

> It is VERY anoying

http://imgur.com/a/ovuEK

**Comment by brandon3055** [comment]
I need more information that that. They render just fine for everyone else so it must be something on your end. What pack are you using and do you have the latest versions of DE BC and Code Chicken Lib? 
I also need your log.

**Comment by Pontiac76** [comment]
I'm having the same issue.  I'm running a modified version of the DW pack 1.1.2 (Tried to upgrade my world to the latest just last night, but that was a nuclear bomb).  For a while, things work fine , and I can see the tools in JEI and in my inventory, however, after a while, things just start going missing with just the tools.  Both draconic and wyvern.  But that is ALL that is affected.  Everything else is seen fine.

I also noticed that with some chests, I'm getting wrong Z-layers.  Fluids seem to overlap objects, ender chests (Not the vanilla one) seem to mess up the Z-Layer.  If I put a regular vanilla chest right next to an Ender Chest, sometimes the Ender Chest renders BEHIND the stock chest if looking at it a particular way.  

Kind of the same thing with fluids.  If I have a smeltry with glass to see whats in it, the Z and Y layering gets strange.  Lookup upwards, I can see the top layer fluid, but, to the left and right I see what should be on that layer of fluid, and I can see all the way through to the back.

This may not be related directly to DE, but, it does happen to just more than the OP.

**Comment by KoenVW02** [comment]
So, I backup'ed my savede folder, reinstalled my pack and moved my waves back, got back in the server and it was fixed. But, what I found out, is that when Log off, when you have a item or armor in your HAND it will not render next time.

**Comment by brandon3055** [comment]
No idea whats going on with this but i will be switching to a new rendering system in 1.11 (Wich may get back ported to 1.10) that should fix the issue.
