### ISSUE TITLE
Mob Soul Slime

### ISSUE THREAD

**Issue by oOAbaddonOo** [brandon3055/Draconic-Evolution#6]
The Slime Mob Soul Item is flickering through the different sizes like crazy...
Probably there is the same issue with the Magma Cube, but i didn't gotten this item yet.

Sorry for the horrible english...
Greetings from Germany

**Comment by brandon3055** [comment]
Yea thats a problem with all slime like mobs including the Tcon blue slime. I will get around to fixing it eventually but its not a high priority.

**Comment by oOAbaddonOo** [comment]
Okay

There is a little problem with the Draconic Chest in combination with the auto-sort from InventoryTweaks too. If there are some items in the furnace-slot while autosorting, they jump into the chest and the items that should appear exactly on this solt go to the players inventory...

hopefully you understand what I mean :D

**Comment by brandon3055** [comment]
Unfortunately there isnt really anything i can do about the sorting in the draconic chest because inventory tweaks doesn't have any way to manage complex inventories like that.

**Comment by oOAbaddonOo** [comment]
Isn't it possible to block the furnace-slots from sorting?

Unfortunately i found an other little issue... If i teleport with the "Enhanced Charm of Dislocation" between two Dimensions (in my case from the Nether to the Overworld) the NEI-Gui disappears (and i can't toggle between "show" and "hide" with the "O"-shortcut anymore)

**Comment by brandon3055** [comment]
Unfortunately no thats what i meant when i said inventory tweaks doesn't have any way to manage complex inventories.

As for the nei thing thankyou for pointing that out i have noticed it but could never figure out what was causing it so i just assumed it was a random nei bug.
