### ISSUE TITLE
Armor Config Gui Not Working

### ISSUE THREAD

**Issue by BFTB** [brandon3055/Draconic-Evolution#601]
![2017-02-12_11 38 26](https://cloud.githubusercontent.com/assets/25725171/22864073/61cd426a-f118-11e6-9e1d-e6cadb070ca4.png) Details: In this image, i am wearing the Draconic Helm and Draconic Chestplate mixed with the Wyvern Leggings and Boots

![2017-02-12_11 38 30](https://cloud.githubusercontent.com/assets/25725171/22864075/64e72a06-f118-11e6-98fa-3e9dbe887a05.png) Details: In this image, i have the tool & armor config gui open and my armor does not show up in the armor slots.

However, the armor shows up when placed in my inventory and i open the config gui, which is quite inconvenient.

The current version of Draconic Evolution i'm using is "Draconic-Evolution-1.7.10-1.0.2h"

I am playing on the modpack: Skyfactory 2
By: Bacon_Donut

The launcher i'm using is called "ATLauncher 3.2.3.7"

**Comment by brandon3055** [comment]
This is partially my fault and partially but the mod that is modifying InventoryPlayer to add more slots is also partially to blame. I will fix it if and when i release another 1.7.10 update.
