### ISSUE TITLE
Comparator to pylon not working?

### ISSUE THREAD

**Issue by AstroxV** [brandon3055/Draconic-Evolution#603]
For some reason I can't get the comparator to give me any output from an energy pylon.
I saw in the change notes it was fixed 2 versions ago but it will not work for me. 
Using version 2.0.8.177

**Comment by brandon3055** [comment]
Looks like there is an issue. Will be fixed in the next release.

**Comment by AspectMalygos** [comment]
I still have this issue using 1.10.2-2.1.2.245, running FTB Beyond with only a couple mods updated.
