### ISSUE TITLE
Feature: Comparator supprt for Fusion Crafting Core

### ISSUE THREAD

**Issue by shabble** [brandon3055/Draconic-Evolution#604]
For automation purposes it would be nice if the crafting core could provide a comparator output indicating whether a craft is ready to begin (that is, the required materials are present on the injectors, an appropriate item is in the top crafting slot, and the bottom output slot isn't blocked).

That could then be used to trigger an input pulse to the core to begin the craft.

Additional output values (similar to the botania altar & others) that represent various intermediate stages or error states (consumables present but missing or invalid core crafting item, etc) might be nice, but not as important.

Tested (in the sense of 'doesn't appear to have this feature') with:

* MC 1.10.2
* Draconic-Evolution-1.10.2-2.0.7.168-universal
* BrandonsCore-1.10.2-2.1.3.82-universal

(basically skyfactory 3.0.6)

**Comment by brandon3055** [comment]
Not a bad idea. I will add it to the todo list!

**Comment by brandon3055** [comment]
Will be in the next release http://ss.brandon3055.com/88tje2g.png
