### ISSUE TITLE
Upgrade level too high for this item

### ISSUE THREAD

**Issue by brunocassol** [brandon3055/Draconic-Evolution#605]
**Minecraft** 1.10.2
**Draconic Evolution** 2.0.7.168
**Immersive Engineering** downgraded to 0.10-54
**Sky Factory** 3.0.6

I'm trying to upgrade a Draconic Bow to Chaos tier Arrow Speed and Arrow Damage. Both of them give me this message:

![image](https://cloud.githubusercontent.com/assets/203541/23080364/32ee9f00-f52f-11e6-8b99-1b4b91f45654.png)

I was able to upgrade a Draconic Flux Capacitor to Chaotic RF Capacity tier.

Are those meant for a future "Chaotic Bow"?

**Comment by Goobaroo** [comment]
Chaos isn't implemented yet.  You can find that text under the Upgrade System section of the in game documentation.

![image](https://cloud.githubusercontent.com/assets/112187/23141219/c644d9a8-f783-11e6-8945-67dbecb786fd.png)

**Comment by brunocassol** [comment]
Thanks. I found it confusing that I was able to apply Chaos tier RF Capacity to a Draconic Flux Capacitor but not other upgrades.
