### ISSUE TITLE
[1.10.2] Question Fusion crafting

### ISSUE THREAD

**Issue by YOYOK9** [brandon3055/Draconic-Evolution#606]
I have a small question about the adding fusion crafting recipes. Is it possible to use more than 8 items around the core (not including the core item). Since you are able to fit a total of 12 crafting injectors around the core block. I wanna make a tough to get item and this would be a great way of doing it :P

**Comment by brandon3055** [comment]
Not sure where you got the number 12. You can put 9 injectors on each side so 9*6 = a max of 54 injectors. I have not actually tried using that many items in a recipe but theoretically it should work. Tho the gui would get a bit crowded but i have a fix planned for that.

**Comment by YOYOK9** [comment]
Got the number 12 from doing 3 crafting injectors on all 4 sides of the core. Have got 12 working atm how ever have noticed a weird thing with the power when creating a custom recipe. It adds a negative sign to the power. 

config energyu input: 546182249
https://puu.sh/uqOTQ/9fb731928f.jpg
