### ISSUE TITLE
IllugalArgumentException BlockstateContainer server crash

### ISSUE THREAD

**Issue by Rubbertjuh** [brandon3055/Draconic-Evolution#607]
https://hastebin.com/nunirikefi.scala
Running SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-c8dacdb
    SpongeForge: 1.10.2-2221-5.1.0-BETA-2156
    Minecraft Forge: 12.18.3.2221

Draconic Evolution version: Draconic-Evolution-1.10.2-2.0.8.177-universal
Server just crashed out of the blue, not sure what caused it. Any idea?

**Comment by brandon3055** [comment]
This is related to an annoying issue where tile entities seem to somehow load before the block they are attached to actually loads. This will be fixed in the next release.
