### ISSUE TITLE
Armor infusion Wyvern to Draconic losing upgrades

### ISSUE THREAD

**Issue by cjo9900** [brandon3055/Draconic-Evolution#608]
When doing the infusion from Wyvern to Draconic armor pieces, I am losing the upgrades applied before the infusion. Is this expected as the fusion crafting core indicates that there should still be present afterwards?

Draconic-Evolution-1.10.2-2.0.7.168-universal.jar
Pack: Skyfactory 3.0.6 

![de_pre_infusion1](https://cloud.githubusercontent.com/assets/549480/23105528/b71be8e6-f6d8-11e6-8396-61e2c21a6470.png)
![de_pre_infusion2](https://cloud.githubusercontent.com/assets/549480/23105529/b71c079a-f6d8-11e6-84ab-e6ddbc2454c3.png)
![de_pre_infusion3](https://cloud.githubusercontent.com/assets/549480/23105530/b71d59ce-f6d8-11e6-84db-0c068caffb7b.png)

**Comment by cjo9900** [comment]
Looked at the code and it should keep the upgrades.

Closing this as I cannot seem to reproduce this in any testing. so not an issue

**Comment by qcho** [comment]
Hi. I've loosed upgrades too. Had full basic upgrade on wyvern and when upgraded to draconic set basic upgrades where lost for each and every item.
