### ISSUE TITLE
crash when i put the draconic chest in to the golden bag of holding

### ISSUE THREAD

**Issue by nitsuga5124** [brandon3055/Draconic-Evolution#61]
the title says all

http://pastebin.com/z4wpFZ6z

**Comment by brandon3055** [comment]
That dose not look like a crash on my end. Did it just happen once or every time you try to put the chest in the bag of holding?

P.S. Storage inside storage is never a good idea...

**Comment by nitsuga5124** [comment]
when i put the chest in the bag crash allways

**Comment by brandon3055** [comment]
I decided to finally look into this but i am unable to recreate the crash. Furthermore the crash itself dose not make any sense at all. The draconic chest is just a standard item like any other so it should not cause this problem.
