### ISSUE TITLE
Локализация на Русский

### ISSUE THREAD

**Issue by AnTheez** [brandon3055/Draconic-Evolution#610]
Ваш мод уж очень популярен на Российском регионе
И хотелось бы видеть его с русским переводом 
RU_manual.json   и   ru_RU.lang
Надеюсь на ваше понимание )

**Comment by covers1624** [comment]
Hey, Do you mind translating this to English for us please?

**Comment by GreatOrator** [comment]
Your fashion it is very popular in the Russian region
And I would like to see him with a Russian translation
RU_manual.json and ru_RU.lang
Nadyus for your understanding)

Basically I think he wants to submit a russian translation

**Comment by linkinkov** [comment]
He just want russian translation, without any commit or work at tranlate, lol

**Comment by AnTheez** [comment]
Несовсем
уже есть перевод
осталось его исправить
и позже вышлю

**Comment by GreatOrator** [comment]
nesovsem
already translating
left to fix it
and later send

Please spend 2 minutes to translate what you are saying for our sake? Please?

**Comment by AnTheez** [comment]
I found a good translation, but it needs to be fixed
I'll post the corrected translation here later..

**Comment by TimeConqueror** [comment]
//En version
Amusing issue :)
AnTheez, If you want that the world can understand you, you must use English. Not all people use Russian language to communicate with others.
What about translate... Two months ago I decided to translate this mod (into Russian, of course). So, AnTheez, it's not an easy task, especially the article about Draconic Reactor. Too much difficult  words, too compex scientific sentences.
For now, it is the last article, and when I finish translating her, the Russian translation will be completed.
//Ru version
Забавная статья :)
AnTheez, если ты хочешь, чтобы весь мир тебя понял, ты должен использовать Английский. Не все люди используют Русский язык, чтобы общаться с другими.
Что насчёт перевода... Два месяца назад, Я решил перевести этот мод (на Русский язык, конечно). Ну, AnTheez, это не простая задача, особенно, если говорить о статье про Дракониевый реактор. Слишком много трудных слов, слишком много всяких научных предложений.
На данный момент это последняя статья, и когда я закончу её перевод, Русскоязычный мануал будет завершён.

**Comment by TimeConqueror** [comment]
So, I'm ready to give the ru_RU.lang file. (Without manual.json)
Where can I send the translation? In "Pull request"?

**Comment by brandon3055** [comment]
yes pull request is fine

**Comment by AnTheez** [comment]
У меня был на тот момент ru_RU.lang
А вот собственно и manual
[manual-ru_RU.zip](https://github.com/brandon3055/Draconic-Evolution/files/1133320/manual-ru_RU.zip)
