### ISSUE TITLE
[Visual Suggestion] Energy Relay Crystals

### ISSUE THREAD

**Issue by Lukas45** [brandon3055/Draconic-Evolution#611]
Currently Energy Relay Crystals only starts their beams from the circle around it, unlike the Energy I/O Crystals, which has it in its center.

I would like to suggest that the Energy Relay Crystals, when bound to another Crystal directly above/under, will make the energy beam from its center or top/bottom, so you can have a straight energy line going up/down.
Main reason is that it gets annoying to look at, when a Relay has a connection to a another crystal directly above/below it (I'm a very symmetrical builder).
My current workaround is to have 2 I/O Crystals in between the 2 Relays directly above/below each other, and use those as center points for the energy line, but I would love not to have to use a workaround.

Again, thanks for your work!

**Comment by brandon3055** [comment]
I would do this if i could but there is actually a very good reason i dont. The beams are not actually solid beams as they appear. The look they have is actually a rendering illusion created by rendering several semi transparent flat textures at different angles. When a beam intersects with another block you see the individual 2d quads and the illusion is broken. http://ss.brandon3055.com/2bnread.png This is why the beams are terminated on both ends with particles to hide the ends of the beams. 

It would be possible to do something similar to what the IO crystals do but it would probably require a fairly significant re write of the rendering code.

**Comment by brandon3055** [comment]
Actually it is possible via a small change to make this kinda work but its not as good as the IO crystal. With the IO crystal the termination particle is rendered bu the crystal itself and is a static effect. Its not possible to do that without a re write so the termination effect needs to be rendered by the particle which is not ideal.
http://ss.brandon3055.com/8u4t8x8.png
http://ss.brandon3055.com/ksbjruh.png

**Comment by brandon3055** [comment]
Yea i think i will keep that

**Comment by Lukas45** [comment]
That is exactly what I had in mind.
In my mind (mind you I'm not a dev), this wouldn't be a change of particle effects, but rather 2 more points from where the particles can start (in addition to the current 8) - with a condition ofc (x=0, z=0, y=±CurrentPos).

But as I said, what you showcased there, is exactly what I was thinking of (and "need"), aslong as it only uses those points when the connection is directly below/above (hell I probably wouldn't mind otherwise either).

Thanks man!
