### ISSUE TITLE
Sword of the Wyvern vanished/deleted inside Autonomous Activator

### ISSUE THREAD

**Issue by Dekutanoth** [brandon3055/Draconic-Evolution#612]
![screenshot_421](https://cloud.githubusercontent.com/assets/16315960/23234340/c278bafe-f91f-11e6-9a1e-6b58e83e3302.png)
![screenshot_420](https://cloud.githubusercontent.com/assets/16315960/23234341/c28464da-f91f-11e6-93fc-a6f50c36911c.png)

I set up an autonomous activator at a mob farm to get mob souls. I put an energetic infuser diagonal to it, with transfer nodes on the sides, to filter a fully depleted sword into the infuser, and a fully charged sword out. My wyvern sword had three draconic core upgrades to RF, looting III, sharpness v, reaper v, decay I, knockback II. The instant I put the sword into the AA, it vanished. It's not in my chests, the mob farm chests, my inventory, any feasible inventory I own, or the transfer nodes. It simply vanished/was deleted. I made another sword with only reaper/looting/sharpness, and this one works as normal and does not vanish. I don't know what caused the bug, and when I tried (above) to repeat it, it didn't happen again, but I just wanted to officially make a note of it.

 (It could also be a thermal expansion bug, and not anything draconic related)

**Comment by brandon3055** [comment]
I cant think of any way this could be caused by something on my end. Its not really possible for an item to accidentally delete itself from an inventory.
