### ISSUE TITLE
Bow of the Wyvern won't shoot explosive arrows past certain speed modifier

### ISSUE THREAD

**Issue by Chais** [brandon3055/Draconic-Evolution#613]
I have my bow enchanted with Infinity and upgraded to Wyvern level of arrow damage, arrow speed and draw speed.  
With the speed and damage modifiers set to max I can shoot just fine. When I max out the explosion modifier too I can't draw the bow any more. It just plays the "start drawing" animation over and over, but doesn't actually draw the bow. Hope it gets clear what I mean.

**Comment by cjo9900** [comment]
Check the cost of the shot, as that combination can be very high RF if i remember correctly. You may need to add the RF upgrades to the bow.

**Comment by Chais** [comment]
You're right. 5.6 GRF. Sorry, my bad.
