### ISSUE TITLE
Draconic Energy Shield Last Stand Ability

### ISSUE THREAD

**Issue by JacobMuken** [brandon3055/Draconic-Evolution#616]
Its not there.. and there's nothing anywhere that indicates that it can be toggled on or off, my armor has a total energy pool of over a billion, but no last stand. And thanks to the SUPER SUUUPER buggy chaos dragons, i just had to fight 2 dragons at once with no last stands, so that sucked.

**Comment by brandon3055** [comment]
Hmm... thats odd. It works fine in dev... http://ss.brandon3055.com/nnxczzn.png
