### ISSUE TITLE
using Advanced Dislocator in end causes effect to carry across to other dimensions

### ISSUE THREAD

**Issue by OmgImAlexis** [brandon3055/Draconic-Evolution#617]
I haven't had this issue myself but it was displayed in a let's play I just watched.

https://www.youtube.com/watch?v=rnJjYyPkYtE

Watch from 4:07 - 4:40

![screen shot 2017-02-25 at 8 32 45 pm](https://cloud.githubusercontent.com/assets/6525926/23330251/8db64472-fb99-11e6-96b0-a2a4a41567c9.png)

**Comment by GreatOrator** [comment]
If you are referring to the boss bar that is not necessarily DE, the boss bar was showing in his video long before he left the end so it was a rendering bug, yes, but nothing says it was DE
