### ISSUE TITLE
[1.10.2] Long server start delay if no connection to contributors file can be made

### ISSUE THREAD

**Issue by DeadSix27** [brandon3055/Draconic-Evolution#619]
`[draconicevolution]: Failed to download contributors list`

EDIT: I tested this again and it does actually finish starting up, but takes a very long time.

Full stacktrace: http://pastebin.com/ce2hZQqj

**Comment by brandon3055** [comment]
That downloader runs in a separate thread (As any sain downloader should) so it should not be possible for it to delay startup at all.

**Comment by DeadSix27** [comment]
@brandon3055 Odd, ye I figured its in a seperate thread, which is why I was confused.. I'll try to keep an eye on that and If that happends again ill report back, for until then I'll close this issue I guess.

**Comment by Derkades** [comment]
This just happened to me and my server is still unresponsive after 10 minutes. I guess I'll have to wait longer..

It's the first time I got this message and I've restarted the server about 15 times over 2 weeks.

**Comment by Derkades** [comment]
Nevermind - removing DE did not stop my server from hanging. It seems to be a coincidence that another mod hangs just after the DE error.

**Comment by DeadSix27** [comment]
@Derkades I think my issue back then was part of a bigger issue with other mods and chunk decoration or generation, I can't remember.
