### ISSUE TITLE
Draconic armour enchant crash

### ISSUE THREAD

**Issue by magictj** [brandon3055/Draconic-Evolution#62]
Every time I open the GUI now to enchant something like boots, I select the item and the side bar for the enchants only comes up for a split second before going to back to the GUI and crashing. 
http://pastebin.com/9Gbu7gFm

**Comment by brandon3055** [comment]
More detail please.
-Are you on a server or playing singleplayer
-Are you using a mod pack? if so what mod pack
-Which items have you tried?
-If you can try deleting the item and cheating in a new one. That will tell me if it is an NBT problem.

**Comment by magictj** [comment]
It was on a server using FTB infinity. I was trying to add enchanted books into the GUI on draconic boots when I would crash. However it has not been happening any more. The server lag had stopped and I was able to do it again. As well as this I believe the modpack was updated a couple of days after.

**Comment by brandon3055** [comment]
Ok if it starts happening again feel free to reopen this issue.
