### ISSUE TITLE
Chaos Dragon

### ISSUE THREAD

**Issue by kulwych** [brandon3055/Draconic-Evolution#620]
I've tried several times now to kill one of the chaos dragons. 
if you engage hhim and then tp out, he disappears.
if chunks are loading and he's not on site with you in current loaded, he disappears. 
any thoughts on this?
this is running, as the mod says
1.10.2-2.0.7.168

**Comment by covers1624** [comment]
As per the ingame warning the dragon is needing a rewrite. It is planed.
