### ISSUE TITLE
[Suggestion][Request] Adding NBT to custom Draconic Fusion Craft recipes

### ISSUE THREAD

**Issue by CidsADev** [brandon3055/Draconic-Evolution#621]
I would personally use the CustomFusionRecipes.json to add a few recipes to things like enchanted books. However the type and tier of the enchantment is saved in the NBT-data, so I cannot create a recipe for it.

Would you consider adding a NBT to custom recipes?

**Comment by brandon3055** [comment]
This will be in the next release.
