### ISSUE TITLE
JEI Render Crash

### ISSUE THREAD

**Issue by NicosaurusRex99** [brandon3055/Draconic-Evolution#623]
This is from the hs_err_pid file http://pastebin.com/R24PfUmX

**Comment by covers1624** [comment]
We also need your full log to provide help, The file you have provided info from is the JVM's crash log, as in stuff that has crashed outside of Java.

**Comment by NicosaurusRex99** [comment]
It doesnt provide me with an actual crash log

**Comment by NicosaurusRex99** [comment]
will FML latest do?!?

**Comment by brandon3055** [comment]
There is still no useful information in that log. Have you restarted the game (which would have overwritten the log) since the crash occurred?
The report should be in <mcdir>\crash-reports

**Comment by covers1624** [comment]
If the JVM crashes in native code, mc will NOT gen a crash report. We need your fml latest log from the time of the crash, and still usefull info might not be generated.

**Comment by NicosaurusRex99** [comment]
sorry for the delay i will get that right away

**Comment by NicosaurusRex99** [comment]
Turns out it was my JVM's dont worry my bad not yours

**Comment by NicosaurusRex99** [comment]
O.o i removed my JVM arguements and still crashed https://www.zerobin.net/?3fbc3c97e89af1ce#avQ0ofwOelIRMMrxK9qp6BLSNagGLI3Cf0/wGhrWrQ0=
