### ISSUE TITLE
[Request] Config to disable Draconic Dust drop from Ender Dragon

### ISSUE THREAD

**Issue by MasterFee** [brandon3055/Draconic-Evolution#624]
I'm currently working on a modpack in which DE forms the end game. Therefore it is really hard to get your first ingot of Draconium. Killing the Ender Dragon gives you ~30-50 Draconic Dust thus not being the _hard_ way that was intended. I tried editing the loottable using McJty's [In Control!](https://minecraft.curseforge.com/projects/in-control) but that did not work. Would be cooler to have a config anyways.

**Comment by brandon3055** [comment]
Will be in the next release.
