### ISSUE TITLE
[2.0.8-177] Unable to change I/O crystal mode with offhand occupied

### ISSUE THREAD

**Issue by Akhorishaan** [brandon3055/Draconic-Evolution#625]
If you have anything in your offhand slot, be it shield, dirt, diamond, or anything else, you cannot shift+right click with an empty hand to change the mode on an I/O crystal until you empty your offhand slot.

**Comment by brandon3055** [comment]
Sorry thats vanilla not me. When you right click a block the game first checks if you are holding anything in your main hand then your off hand and finally if there is nothing in your off hand it fires the right click block event. There is no simple way around this issue.

**Comment by Akhorishaan** [comment]
Could simply make a note of it in the block of text on the DE tablet so people aren't googling around for an hour before figuring it out :)
