### ISSUE TITLE
Grinder + RF Power issues RC4

### ISSUE THREAD

**Issue by DemonSeedxp** [brandon3055/Draconic-Evolution#63]
Hi again, back to report some pretty serious issues I've encountered with the new wireless power arrays.

I'm currently working on a massive Draconic spawner setup, and am installing 15 spawners, each contains 4 Draconic mob grinders,  1 advanced energy transceiver powered by a tesseract and 1 advanced wireless transceiver that's powering each of the 4 grinders. 

As I placed more of the wireless power items in the world and linked them up, the worse my connection to the server became. It was a very strange kind of lag tho. It didn't effect my FPS at all, the TPS of the server was perfectly fine, but I was running a solid 45-60 sec behind the server (or the otherway round, not too sure).

 I was unable to break blocks, open an inventory, interact with pretty much anything. (which btw made removing all the offending items from the world a major pain) but as soon as they where finally removed I instally was caught up to the server.

In the mean time the issue did eventually crash the server and heres a link to the server crash report https://dl.dropboxusercontent.com/u/841137/Minecraft/crash-2015-04-10_09.15.41-server.txt

If you need more info from me just let me know. I'm more then happy to also test out any patches on my setup to help test fixes. This really bummed me out, and I feel like my project just got shelved until the issue can be fixed. lol I really dont want to run wires everywhere! 

Oh, btw...
since the rc4 update I'm noticing that the staff of power very often wont break items while I'm in flight. (again major problems ensue when a tear 3 ghast spawner gets out of control, and you can't break it! :O) 
It will appear to break on my client, but the item is still there as a ghost block, and if I place example dirt in that spot it will force the item to reappear. 

Sorry for the long post...

**Comment by DemonSeedxp** [comment]
well it turns out I may have been mistaken... I have now redone my setup using extra utilities energy transfer nodes and wireless transceiver and receiver upgrades and now that I've repower a few of my spawner cells, each containing 4 draconic grinders my lag is back. I think I have 12 grinders at this point, powered full time and it's pretty much just as bad as the first time the lag was present. and as I think back powering on the grinders is exactly what I was doing when it hit last time too. 

I just mistakenly thought it was the wireless devices I was placing at the time, and additionally removing them corrected the issue, masking the fact all I was really doing was unpowering the grinders. 

So yeah, the short of it, I'm now truly dead in the water, without these grinders this project isn't budging another inch. lol help!

**Comment by brandon3055** [comment]
Will put this at the top of my todo list! The server crash is due to the server running out of memory. Weather or not that has something todo with the grinder i do not know but i will look into it.

**Comment by brandon3055** [comment]
Ok so i have a question for you. How many mobs were in the spawner/nearby when this occurred? I ask because i have been testing for about 20 minutes now and what i have found is that if you have more then around 130-160 mobs nearby your latency goes through the roof. I was getting around 10000ms+ and that was with both the server and client running on the same machine. Add a bunch of extra mods and some distance between client and server and i can see that getting rather bad.

**Comment by DemonSeedxp** [comment]
rofl, yeah it's a bit much but what I'm doing is setting up 15 individual spawner cubes (containing unique mobs), each cube contains 4 grinders. One on each exterior wall. And the spawners are being controlled by my Applied Energistics 2 setup, to toggle on any given spawner when that mob's loot is low in the system.

As far as "do I need" 4 per cell, probably not... lol but cemerity is a real  B***, and see gets 
what see wants. :p

and yes, I was only powering the grinders when I was having all the troubles, no mobs where in the world at all, building in a void age. 

Thank you sooo much for getting right on this, because there is absolutely no way a MFR grinder or 20 could begin to keep up with your tier 3 spawners. So I've basically have been on hold waiting to hear back from you. no other way of killing the mobs would do for this as I'm calling it "Hyper Spawner" since the entire build is reminiscent of a Hyper Cube

**Comment by brandon3055** [comment]
What exactly is your server setup if you dont mind me asking? If you have the ability to easily update mods i can give you a build with that fix now. Otherwise it may be a day or two before i release RC 5.

**Comment by DemonSeedxp** [comment]
yeah I have file access to the server, and can patch at any time!

**Comment by brandon3055** [comment]
ok just give me a few minutes to compile the mod. And then another few minutes to upload it on my currently very slow internet connection.

**Comment by DemonSeedxp** [comment]
awesome! 
/on pins and needles, can't wait! 

and thank you again!

**Comment by brandon3055** [comment]
Here you go http://puu.sh/hdiNc/8a437614db.jar
That release hasn't been tested outside the dev environment so let me know if you run into any problems.

**Comment by DemonSeedxp** [comment]
oh btw, did you catch the part where the staff isn't breaking blocks right while in flight? super annoying... hasn't been around too long, last update or 2 maybe.

it seems as tho the client thinks the block gets broke but the server doesnt think so, so your left with an invisible block you glitch into.

**Comment by brandon3055** [comment]
Going to look in to that but if you right click any of the tools they will update any of those ghost blocks around you.

**Comment by DemonSeedxp** [comment]
ahh good tip, would have been good to know when the ghast spawner got out of control on me
/who said that.... never happened
...

**Comment by DemonSeedxp** [comment]
little update. I now have all 60 grinders powered and all is right in the world. You nailed it! thanks so much!

**Comment by brandon3055** [comment]
Your welcome! Happy to help!
