### ISSUE TITLE
Getting rid of extra blocks

### ISSUE THREAD

**Issue by scifibob** [brandon3055/Draconic-Evolution#630]
When using the enchanced draconic pickaxe with silk touch and 7x7 or 11x11, I get an enormous amount of stone that I rather want to get rid of.
It seems that if my inventory is not capable of storing all the loot, and all I get is stone, not the ores and stuff.
Is there a way to switch off the lag protecting thing that creates the black thing on the ground, and make it act like a normal digging tool, so that my diamond backpack captures the loot and sort it?

I'm using the 1.10.2_2.0.8.177 version

**Comment by Rikj000** [comment]
Just take a look here and I am sure u will find what u need:
[Equivalent of /dev/null in AllTheMods](https://www.reddit.com/r/feedthebeast/comments/5khzkk/equivalent_of_devnull_in_allthemods_1102/)

**Comment by brandon3055** [comment]
Will be adding a replacement for destruction mode at some point.
