### ISSUE TITLE
[SUGGESTION] Ability to toggle link visualization

### ISSUE THREAD

**Issue by Rikj000** [brandon3055/Draconic-Evolution#631]
I recently started using the Energy Network and I really enjoy everything about it besides 1 little thing,
The links always showing can sometimes be annoying and pollute the looks of a build.
That is why I suggest a function to toggle the visibility of em. That way people can choose which links they wish to be hidden and to be visual.

**Comment by brandon3055** [comment]
I suggest laying out your system an such a way that the beams compliment the aesthetics. I probably wont be adding a way to remove them. If you want that you may aswell use a wireless energy mod.
