### ISSUE TITLE
[1.7.10] Issues with the Draconic Reactor

### ISSUE THREAD

**Issue by comus777** [brandon3055/Draconic-Evolution#633]
For some reason, no matter how I configure it or what I do, the Draconic Reactor always explodes due to the containment field dropping. I've messed with the flux gates, given it millions of RF per tick, etc. the containment field always sinks to 0 and goes nuclear. 

What can I do to stop this? Is this a bug or am I doing something wrong?

**Comment by covers1624** [comment]
Brandon on ts:
> If you are dumping the output of the reactor directly to storage, no matter how much power you pump in to the shield if your saturation drops you will have problems.

**Comment by comus777** [comment]
That doesn't seem to be the problem I'm having. What happens is that I activate the reactor and the containment field immediately begins to drop from 50% down to 0%, usually at about 1.x% per block update.

**Comment by brandon3055** [comment]
This sounds very odd... What happens if you dont extract any power from the core at all and just feed the shield with say 200KRF/t?
Also can you show me a screenshot of your setup?

**Comment by comus777** [comment]
Same thing. Shields just keep dropping constantly. 

My setup is exactly the same as the one you showed in the tutorial video except that I extract from all 4 of the reactor stabilizers rather than just one.

**Comment by brandon3055** [comment]
I would not recommend that as it would make regulating the reactor a bit trickier. If you have time to look in the gui as the shield id dropping can you tell me what the Saturation level is doing while the shield is dropping?
