### ISSUE TITLE
Fusion crafting recipes don't show in SKyfactory 3

### ISSUE THREAD

**Issue by SubsterNL** [brandon3055/Draconic-Evolution#634]
Latest version of FTB SkyFactory 3

None of the (fusion) crafting recipes show in JEI.

Also don't show in the tablet.. recipe not found in red.

This mod is a PITA to use without JEI integration.

**Comment by Tardnicus** [comment]
I just fixed this yesterday in my Sky Factory world. It's a bit of an odd workaround, but the current version of Immersive Engineering in SF 3.0.6 is likely causing problems with displaying fusion crafting in JEI. Fortunately IE has pushed an update to fix this but that version: `0.10 - 57` is not installed on the beta release of SF (3.0.7). So, if you want to fix this problem ASAP, then you have to manually update some mods.

It is pretty easy if you're using Curse. All you have to do is (preferably) make a new profile, install 3.0.7, then turn off the "Locked" mode in the profile options. After that is toggled, you can then manually update whichever mods you please. Find Immersive Engineering in the mod list and click the little update icon on the far right of the row it's located in. Unfortunately you have to update JEI as well, as it fails to load with just Immersive Engineering.

After updating and loading everything up, you should see all the fusion recipes and it will load in the tablet as well.

**Comment by covers1624** [comment]
This was fixed ages ago.
