### ISSUE TITLE
NBSP Localization issue

### ISSUE THREAD

**Issue by Elvarion** [brandon3055/Draconic-Evolution#635]
Using a Swedish OS on your computer will cause Draconic Evolution to display the NBSP symbol instead of a space or a , in English OS

As can be seen here
https://gyazo.com/ba697cf839a07872e9d5c25aefe3483d

- Draconic-Evolution-1.10.2-2.0.8.177-universal

**Comment by covers1624** [comment]
This should be fixed in forge.

**Comment by covers1624** [comment]
Fixed in 1.11 by forge: https://github.com/MinecraftForge/MinecraftForge/pull/3522
