### ISSUE TITLE
Can't find any draconium ore in the end

### ISSUE THREAD

**Issue by OvisMaximus** [brandon3055/Draconic-Evolution#636]
I flew around in the end - not one draconium ore found on the main island nor on the satelites I visited. Nor have I found these comets which used to be there back in Minecraft 1.7
I use Minecraft 1.10.2 and FTB Infinity Lite 1.10 with Draconic Evolution 1.20.2-2.0.7.168-universal

Something odd in the config I should check or is this a bug?

**Comment by GreatOrator** [comment]
I would reach out to the pack developers first as it is most likely a config issue they put in place.

**Comment by OvisMaximus** [comment]
The ore generation in the end is disabled, so this one is solved. Although the comets should be there, shouldn't they?
----
world {
    # This is the distance between chaos islands
    I:chaosIslandSeparation=10000

    # Ender Comets have a 1 in {this number} chance to spawn in each chunk
    I:cometRarity=10000

    # Disables draconium ore generation in the end
    B:disableOreSpawnEnd=true
----

**Comment by GreatOrator** [comment]
eventually, they are supposed to be rare so you should find them, but looks like the pack devs disabled the ore gen in the end

so reach out to them to find out why and let them know so they can fix it

most likely something they did in the pack

**Comment by brandon3055** [comment]
Yes the comets should be there.
