### ISSUE TITLE
Stats for energy network crystals?

### ISSUE THREAD

**Issue by kittymmeow** [brandon3055/Draconic-Evolution#637]
I was wondering if anyone knew exactly what all the stats were for the various tiers and kinds of energy crystals? For example, the tablet lists the max number of connections and internal buffer size for each one, but it doesn't say anything about a maximum link range or if they have a maximum transfer rate. I found a year-old thread mentioning that basic relay crystals can transfer 25k RF/t, but I'm using sets of basic I/O crystals that are transferring 130k+ RF/t each with no problem. Most wiki pages that I can find regarding them are also a year+ outdated, so I'm not sure if the information in them is accurate or not. Help?

**Comment by Tahakk** [comment]
I don't know exact number, but range should be +-128 block and I was pumping 6M RF/tick without any problem using Draconic I/O ports and Wireless crystals

**Comment by brandon3055** [comment]
I need to document this better but as far as rf/t io there is no exact number. It depends how many crystals the energy needs to bounce through before reaching its destination.

**Comment by Cancermorph** [comment]
I have a Problem in playing this modpack when i open the NEI the wireless crystals Etc. are not showing there crystal image or something i only see the rings and it is hard to determine if it is basic wyvern or draconic i need help pls

**Comment by covers1624** [comment]
Don't Hijack issues, Make a new issues and provide the correct information including screenshots.
