### ISSUE TITLE
About Draconic tablet

### ISSUE THREAD

**Issue by forestbat** [brandon3055/Draconic-Evolution#638]
Now the information of draconic tablet must be download from website，so if I want to translate to Chinese language，I can't find any document to translate。

**Comment by Tahakk** [comment]
There is xaml file in *YourMinecraftFolder*\config\brandon3055\ProjectIntelligence\ModDocs\Draconic Evolution that you can edit, just not sure where you canfind it here at Git
Good Luck

**Comment by forestbat** [comment]
@Tahakk Thanks very much。
