### ISSUE TITLE
Flux Gate overflow error

### ISSUE THREAD

**Issue by marc7636** [brandon3055/Draconic-Evolution#639]
I was setting up a Draconic Reactor on my Creative world, but when i was putting down my flux gates i accidently put their inputs together and immediatly crashed my game. Trying to start up the map again results in the same error. Looks like an overflow error.

openeye.openmods.info/crashes/0096b3c6d0aa8ae0b0b68928ecc5fe1b

**Comment by brandon3055** [comment]
I will add this to my 1.7.10 todo list
