### ISSUE TITLE
Dracon staff bug i think

### ISSUE THREAD

**Issue by Goten87** [brandon3055/Draconic-Evolution#64]
when i set my draconic staff to higer them 1x1 so 3x3-9x9 it will not drop anymore XP 
enchents from top to bottem
Soulbound 1 - efficiency 5 - looting 3 - sharpness 5 - fortune 3

so when i set my staff higher them 1x1 it will no longer drop XP from ores

im on Draconic-Evolution-1.7.10-v1.0.1-snapshot_5

**Comment by Goten87** [comment]
oke idear for the void option
if its set to true let us also void exp so we can make a auto fortune farm with a Autonomous activator
so we dont have to keep the XP colect up and running ^^

**Comment by brandon3055** [comment]
XP not dropping is now fixed (Will be in RC 5) And it will despawn faster then normal so build up shouldn't be such a big problem. But your best bet would be to just collect it with a vacuum hopper.
