### ISSUE TITLE
[Bug]Flux Point Doesn't work directly with Energy I/O Crystal

### ISSUE THREAD

**Issue by Techtronik** [brandon3055/Draconic-Evolution#640]
I can get it to work by routing thru another form of rf storage between the flux point and I/O Crystal but that creates a bottleneck in the system as the only other rf storage in Skyfactory 3 is Ender I/O Capacitors

Flux Networks: 1.1.5
Draconic Evolution: 2.0.8.177

**Comment by scerion** [comment]
I have the same issue with my Flux Points directly connected to the Injectors, they won't pull a RF charge through them.
Also on SF3 3.0.7

Flux Networks: 1.1.5
Draconic Evolution 2.0.8.177

**Comment by xob** [comment]
I can confirm the bug still occurs on SkyFactory 3 3.0.8. Not sure if it's a Flux Network problem or a Draconic Evolution problem, but the flux point will not provide power to a directly connected Energy I/O Crystal, even though it looks like it's connected.

Flux Networks: 1.1.7
Draconic Evolution: 2.0.8.177

For now, my solution to have near-infinite RF/tick transfer across dimensions is to set up a small draconic energy ball with the flux point as the input, and the crystal as the output. Not ideal, but it works.

**Comment by Zeroji** [comment]
I used to have an energy setup including DE Crystals and Energy Core, Flux Networks, and Environmental Tech T4 Solar Panels in Sky Factory 3.0.6 (DE 2.0.7.168, FN 1.1.1 and ET 0.10.5i)

After I recently upgraded the server to Sky Factory 3.0.8, I had the bug above, which also occurs with I/O Crystals not pulling energy from Solar Panel Controllers (again, putting an EnderIO conduit / capacitor bank in-between works, but that's a serious bottleneck) 

Draconic Evolution 2.0.8.177
Flux Networks 1.1.7
Environmental Tech 0.10.6b

**Comment by brandon3055** [comment]
https://github.com/brandon3055/Draconic-Evolution/issues/557
