### ISSUE TITLE
[1.10.2] Compatibility Issue w/ Environmental Tech

### ISSUE THREAD

**Issue by SnowShock35** [brandon3055/Draconic-Evolution#641]
### Important Information

- Minecraft 1.10.2
- Minecraft Forge 12.18.3.2254
- Brandon's Core 2.1.4.92
- Draconic Evolution 2.0.8.117
- Other Mods:
  - Environmental Tech 0.10.6a/b
  - Valkyrie Lib 0.10.6

### Issue Description

In a recent update to Environmental Tech, CoFH RF Support was dropped in favour for the Forge Energy system. Because of this change, Draconic Evolution and it's wireless laser energy transfer system no longer is able to directly interface with ET's blocks. 

I imagine this probably isn't easy to fix and since they are two completely different API's/systems but I do feel that DE's system should try to support both even if it means a secondary type of laser for it.

This issue seems to be occurring with a lot of mods due to them moving away from the RF API and towards the Forge Energy system, but now with the release of CoFH mods I can see this being quite divided meaning that energy transfer systems will need a way to interconnect with one another.

***

Paging @ValkyrieofNight. Best you also know that this is the case. Despite the problem being not relating to ET.

**Comment by covers1624** [comment]
From my knowledge, Basically all of DE supports FE and RF..

**Comment by SnowShock35** [comment]
@covers1624 So. . . what are you saying? That ET supports neither?

**Comment by SnowShock35** [comment]
I mean it has to support FE because it's fine with EIO conduits so idek :/

All I do know is that it's not working and needs a fix regardless of what dev and who's mod :smile:

**Comment by SnowShock35** [comment]
![IMG](https://ss.blamesnow.co.uk/2017/03/1489017495-a39797e2.png)

**Comment by GreatOrator** [comment]
What version is this?  Direwolf20 has been using it for several episodes just fine


He pumps the energy into storage and is using it to power all of his machines, including EIO

**Comment by SnowShock35** [comment]
Stated above @GreatOrator I think it's solely with ET not other mods :/

**Comment by Conmyster** [comment]
I am having the same issue only difference is 12.18.3.2239 for forge. It was working before I updated ET I was using 0.10.5i of ET. So I would presume it is an issue with that mod not DE. No idea tho I am not a mod dev.

**Comment by SnowShock35** [comment]
Problem is that ET dropped support for RFAPI and moved entirely to the Forge Energy system. Which sucks! and there's still nothing on this. @ValkyrieofNight has still yet to comment on the matter 😕

**Comment by DarkHelmet433** [comment]
I've just encountered this too.  Fortunately, rolling back the ValkyrieofNight mods (SimpleGenerators/EnvironmentalTech/etc) resolves it.

It's not just DraconicEvolution - things like ActuallyAdditions don't work right with his generators any more.

**Comment by DarkHelmet433** [comment]
From the DE code: "import cofh.api.energy.IEnergyTransport;" - I guess that's the root of the problem.

**Comment by Zeroji** [comment]
I had the same issue, and also with Flux Networks - this looks quite similar to #640
