### ISSUE TITLE
Wyvern Energy Relay not working

### ISSUE THREAD

**Issue by darkshadow543** [brandon3055/Draconic-Evolution#642]
In the most recent version, wyvern I/O crystal relays are not importing power, they do not work on any generator unless the power is directly pumped in using another mod, and Oh, yes, the crystals are on input mode.

**Comment by DarkHelmet433** [comment]
Is this regarding the Simple Generators devices, like the Netherstar III series?  The author of that mod removed CoFH RF API support on Feb 26th leaving just forge RF.  A rollback of his mods to pre-Feb 26th works around it for now.  (ValkyrieLib, Environmental Tech, and Simple Generators) but clearly that's not a viable long term solution.

I don't understand who is at fault here. Draconic Evolutioncan *send* energy to his mods, but not receive from them, so clearly there is common ground somewhere.  But something isn't working in the particular case where it would be most beneficial.

**Comment by DarkHelmet433** [comment]
From the DE code:  "import cofh.api.energy.IEnergyTransport;" - I guess that's the root of the problem.
