### ISSUE TITLE
Glass to Draconic Block using Portal Gun

### ISSUE THREAD

**Issue by Danimineiro** [brandon3055/Draconic-Evolution#644]
This Bug/Glitch changes the glass to an Draconium Block using the Version of Draconic Evolution in FTB Infinity 2.6.0.

1. Place energy pylon (Energy Core not needed)
2. Place glass. **Glass should not be placed at Energy Core for this to work!)**
3. Use a Portal Gun to move glass onto energy pylon.
4. Rightclick on the blue sphere ontop of the pylon to create an draconium block.
[https://youtu.be/uTPlP-77WhE](url)

**Comment by covers1624** [comment]
1.7 issue, brandon has noted it for a final 1.7 build if one ever happens.
