### ISSUE TITLE
Fusion Crafting: Basic tool/weapon upgrade not working

### ISSUE THREAD

**Issue by tanis82** [brandon3055/Draconic-Evolution#648]
Info:
- Minecraft 1.10.2
- Skyfactory 3 ver 3.0.8 beta
- Forge 12.18.3.2254
- Draconic Evolution 1.10.2 2.0.8.177

I'm running Draconic Evolution in Skyfactory 3 and I'm having a problem with upgrading weapons/tools in the fusion crafter. The basic upgrade for all weapons/tools doesn't work. When all the ingredients are in the injectors, no start button appears, so I can't craft.

Some relevant points:

- My crafting set-up is correct. It works for everything else.
- I have the correct recipe according to the recipe list; ie. 2 x golden apples, 2 x diamonds, 2 x eye of ender, draconic core, upgrade key
- When I put the recipe for wyvern or draconic level upgrade it recognises it and would probably work, but I obviously can't do it as it says you must do the previous tier first.
- I have tried this for the sword, bow and pick and doesn't work for any of them
- My crafting set-up is all draconic injectors, but I built another with basic injectors to test and it didn't work with them either.
- The sword, bow and pickaxe I'm trying to upgrade are all draconic. But I made another wyvern level one to test and it didn't work for that either.
- I have tested rolling back to skyfactory 3.0.6 and it doesn't work on that either.
- I have tested removing and replacing the recipe ingredients in different orders with no success
- I have tested removing and replacing the injectors and core with no success.

To me the behaviour seems like it just doesn't recognise the recipe as valid, so no start crafting button appears. Either I'm being the stupidest person ever and have put the wrong recipe in 100 times (I don't think so) or the recipe is wrong in the coding somewhere or some other unknown issue.

Any help would be appreciated.

**Comment by tanis82** [comment]
Problem Solved:

After more testing I have discovered the problem. It was the golden apples in the recipe. I was using golden apples that I have received from chance cubes. It seems that there is a difference between the golden apples you get from chance cubes and the golden apples you craft yourself. I'm not sure what the difference is, but I crafted new golden apples and put them in the recipe and it worked!!

**Comment by GreatOrator** [comment]
I am willing to bet the chance cubes add some kind of NBT data that makes them different.  Perhaps @brandon3055 can take a look and possibly exclude nbt data for the apples since the two that are in vanilla are different by meta data iirc.
