### ISSUE TITLE
Draconic Bow shockwave shoot yourself

### ISSUE THREAD

**Issue by perryprog** [brandon3055/Draconic-Evolution#649]
When shockwave is at any level on the Draconic Bow, along with arrow velocity at 600% aiming anywhere below 4.2 degrees, the arrow will hit you.

This seems to happen because the arrow spawns behind your head.

Wow, this was a short issue. Tested in latest version of SF3 and Direwolf20 1.10 pack. MC Version: 1.10.2

**EDIT**: This is weird... the arrow sometimes will hurt you instead of the target. Very strange behavior. Will upload a video soonish.

**EDIT 2** [Here you go.](https://www.youtube.com/watch?v=lxV1onqgYD4&feature=em-upload_owner) You can tell by my entropy if I'm getting hit.

**Comment by brandon3055** [comment]
This is rather odd... It should not be possible for the arrow to collide with the player when it is fired...

**Comment by perryprog** [comment]
I'm gonna guess it's `public static void onPlayerStoppedUsingBow(ItemStack stack, World world, EntityPlayer player, int timeLeft)` in `com.brandon3055.draconicevolution.handlers.BowHandler`.

It doesn't really make sense, unless there is weird behavior in `EntityCustomArrow` with high speeds. Maybe try cranking up thee arrow velocity to `1000f` and see if it collides.

Also, do you have any idea why the aiming seems off? For example, you can see the arrow going somewhere completely different from where I am aiming.

**Comment by brandon3055** [comment]
This will be fixed in the next release.

**Comment by perryprog** [comment]
Thank you!
