### ISSUE TITLE
1.0.1 RC4 - Mekanism Problem

### ISSUE THREAD

**Issue by NitroxydeX** [brandon3055/Draconic-Evolution#65]
Hey Brandon,

it seems that Draconic Evolution have some problems with the latest Mekanism Energy Rework. Output to Mekanism Cables works fine but input doesn't work.

Don't know if it's a Draconic Evolution Problem but all other Mods works fine with it.  aidancbrady/Mekanism#2474

**Comment by brandon3055** [comment]
What version of DE are you using? I updated my RF API in snapshot 5.

**Comment by NitroxydeX** [comment]
@brandon3055 Github did not pushed me your comment. Will try Snapshot 5. Seems only to bug in existing worlds. In new worlds all works fine.

**Comment by brandon3055** [comment]
Well your already using RC 4 (aka snapshot 9) so downgrading probably wont help. I'm guessing you tried breaing and replacing the offending blocks?

**Comment by NitroxydeX** [comment]
Yeah I tried that.

**Comment by brandon3055** [comment]
I am pretty sure there is nothing i can do on my end because i have correctly implemented the RF api. So i am going to close this issue for now.

**Comment by NitroxydeX** [comment]
@brandon3055 using Stable Version 1.0.1 now. working. I don't know whats going on there. But we also updated Mekanism and Forge so. Weird problem.
