### ISSUE TITLE
does the inertia cancelation work while in space w/ galacitcraft?

### ISSUE THREAD

**Issue by enderking470** [brandon3055/Draconic-Evolution#650]
just wondering, as I have yet to find any mod that allows me to have a stable flight in space station dimension.

**Comment by GreatOrator** [comment]
That would have to be specifically coded in as galacticraft has coded his own mechanic for outerspace which is why you are having difficulty with finding any mod to do what you want.

**Comment by brandon3055** [comment]
It may work. It just depends how much galacticraft modifies player movement logic.
