### ISSUE TITLE
Chaos dragon constantly vanishes

### ISSUE THREAD

**Issue by SubsterNL** [brandon3055/Draconic-Evolution#651]
SKyfactory 3.

Updated version of DE.

The dragon constally disappears when you are killing the Crystals. I guess going left or right 10 blocks isn't allowed there because the same thing Always happens.

Already deleted/recreated the end 3 times and the same thing keeps happening.

Waiting it out in the overworld so other chunks unload doesn't work. Relouding the entire client, doesn't work.

**Comment by SkipABeat** [comment]
I am also having this issue on the outerjabip modpack (via curse launcher), the only time this issue doesn't occur is when two dragons spawn.

**Comment by paucha171** [comment]
Same issue. On both Ardentcraft the beginning modpack and ftb beyond

**Comment by brandon3055** [comment]
This should be fixed in the next release.
