### ISSUE TITLE
[Request] Ability to dye armor. Can't tell anybody apart with all the orange armor.

### ISSUE THREAD

**Issue by JaSpr** [brandon3055/Draconic-Evolution#653]
At least 10 people on our server have made the orange draconic armor, and when they're in one place, it's difficult to tell any of them apart.  I imagine people would like to dye their armor, to stand out more.

**Comment by GreatOrator** [comment]
Nametags above their heads?  Otherwise there are mods for changing armor appearance.  Dying the armor wouldtake away from the iconic look and the DE orange :D

**Comment by JaSpr** [comment]
We do have nametags, but it's much quicker to identify somebody by their appearance

**Comment by covers1624** [comment]
This would be really tricky to implement under the current models used for the armor. Nametags are there for a reason imo.
