### ISSUE TITLE
[1.10.2 - Beyond] Advanced Entity Detector (Open Entity Filter Config)

### ISSUE THREAD

**Issue by Ravix-** [brandon3055/Draconic-Evolution#654]
When I open up the config for entities and go to select (Entity/Player) it toggles but there's nowhere for me to input information on my screen.  I can see the [Player] mark on the far right hand side of my screen though.

The +custom command works as intended by giving me a box in the center.

**Comment by brandon3055** [comment]
What version of DE are you using?
