### ISSUE TITLE
Draconic Block are not accepted into the Energy Infuser for charging.

### ISSUE THREAD

**Issue by Possemaster** [brandon3055/Draconic-Evolution#655]
I need to charge the Draconic block to do the resurrection ritual but the Draconic Bocks are not allowed into the Energy Infuser. (Also sneak right click does not work with my capacitor). I cannot proceed now without any ender dragons to resurrect. Playing FTB Beyond 1.1.0 Release

**Comment by covers1624** [comment]
Err.. DE no longer has a ritual for summoning the ended dragon.. use vanillas..
