### ISSUE TITLE
Full client crash when rendering particle from wireless energy crystal.

### ISSUE THREAD

**Issue by FoxFireMC** [brandon3055/Draconic-Evolution#656]
When looking at an active wireless energy crystal (Wyvern tier, I havnt tried with any other crystals yet) it crashes the client while rendering a particle. The crash report is as follows:
[crash-2017-03-18_18.54.28-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/852827/crash-2017-03-18_18.54.28-client.txt)

**Comment by covers1624** [comment]
This isn't DE, its some CamoBlock from omtteam.omlib crashing on random ticks.
