### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by jacob5426** [brandon3055/Draconic-Evolution#657]
Change draconic staff of power in 1.10 to have lower attack damage but faster attack speed feels kinda sluggish and weaker than the draconic sword.

**Comment by GreatOrator** [comment]
Well, the staff was meant as more than just a weapon, it is substantially more powerful than the sword plus it has a huge radius of attack as well as a huge mining radius.  Overall it was meant to be the one-stop weapon/tool for killing and mining.
