### ISSUE TITLE
FTB Beyond ore spawning.

### ISSUE THREAD

**Issue by shojen32001** [brandon3055/Draconic-Evolution#659]
I have made my way to the end and have done quite a lot of mining on the mainland as well as other islands, but i have yet to find a single ore of Draconium. I dont know if it is just our server that is having this issue, but it seems like a big one.

**Comment by 1matto** [comment]
Have you found the comets? They usually spawn in great numbers on those

**Comment by shojen32001** [comment]
I haven't yet, but it should also spawn on the islands in the End as well. Or so i thought anyways, I don't know if the made it so it only now spawns on the comets, but if they have I've found nothing on it.

**Comment by Suppenbiatch** [comment]
Draconium Ore wont spawn on the islands in the End as it's disabled in the config from the FTB Team.
If you are the Owner of the server you could change it in the config folder \config\brandon3055\DraconicEvolution.cfg. It will only spawn in the Nether or if you are useing the Void Ore Miners.

Necessary config changes would be from:
    # Disables draconium ore generation in the end
    **B:disableOreSpawnEnd=true**

    # Disables draconium ore generation in the nether
    B:disableOreSpawnNether=false

    # Disables draconium ore generation in the overworld
    B:disableOreSpawnOverworld=true

to

    # Disables draconium ore generation in the end
    **B:disableOreSpawnEnd=false**

    # Disables draconium ore generation in the nether
    B:disableOreSpawnNether=false

    # Disables draconium ore generation in the overworld
    B:disableOreSpawnOverworld=true

if changeing the config you need to recreate the end or you have to go chunks that haven't been loaded yet
