### ISSUE TITLE
Some console spam after updating DE:

### ISSUE THREAD

**Issue by canilsen** [brandon3055/Draconic-Evolution#66]
Hey, I noticed that after updating Draconic Evolution, I get a lot if console spam that seems like debug info. This never happen before as far as I remember, and I wonder if it was left on by mistake maybe? I don't see a config option for it. 

The repeating messages looks like this:

[Server thread/INFO]  [Draconic Evolution]: update
[Server thread/INFO]  [Draconic Evolution]: true
[Server thread/INFO]  [Draconic Evolution]: false

**Comment by brandon3055** [comment]
What version are you using? I may have already removed that debug code.
