### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by TheGameGeek** [brandon3055/Draconic-Evolution#660]
Where is the config for draconic evolution ive been looking around and cant find it

**Comment by covers1624** [comment]
DraconicEvolutions config will be in "/config/brandon3055/DraconicEvolution.cfg"

**Comment by temar96** [comment]
this really should be changed, its annoying to find and having to google and end up here to figure it out.

**Comment by FoxMcloud5655** [comment]
You do know that there's a handle little thing called searching, right?  You can search the entire config folder for "draconic" and find it very easily.
