### ISSUE TITLE
Non-consumed ingredients (i.e. keys) in Custom Draconic Infusion recipes?

### ISSUE THREAD

**Issue by OrdinatorStouff** [brandon3055/Draconic-Evolution#662]
Upgrade Keys are not "consumed" when performing standard fusion crafting upgrade recipes. Is there a way to use that same behavior for custom-added recipes in "CustomFusionRecipes.json" to have one or more of the ingredients to not be consumed once the fusion crafting is complete? If not could that feature be considered as a suggested addition?

**Comment by brandon3055** [comment]
The upgrade recipes use a custom fusion recipe implementation. But i can look into adding more functionality to the config system.
