### ISSUE TITLE
Wyvern Bow causes Skyfactory 3 to crash

### ISSUE THREAD

**Issue by Teslachu** [brandon3055/Draconic-Evolution#663]
So playing on a private (very small) skyfactory 3 server (3.0.8)... and someone made a wyvern bow. They shot the arrow for the wyvern bow and the whole server crashed. It said "Server connection closed". Now we are unable to get the server back up. Attached is the crash log
[crash-2017-03-23_17.42.05-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/866487/crash-2017-03-23_17.42.05-server.txt)

Going to config folder, forge.cfg and using an option to remove erroring entities did not change anything. As with before that fix, the server went into the boot up process but would fail before coming up. The thing it did was make it look like it had come only In the server list, which came up with an "x" and said old. With a down arrow that said "Vanilla".
The Wyvern Bow Explosion is what caused the server to crashed. The explosion power goes from 0-4 on a base Wyvern bow and at about 2.5 it really starts to lag the server on explosion. At 3, it causes the crash again.  

Image of how it looked in server list before it crashed again:
http://imgur.com/UPrmuZ1

**Comment by brandon3055** [comment]
Try updating DE
