### ISSUE TITLE
Custom Meteors Malfunction on servers

### ISSUE THREAD

**Issue by Boolyman** [brandon3055/Draconic-Evolution#664]
When performing the Mark Of The Fallen tower on servers, only default meteors work.  Custom meteors come down as a 3-4 block broken sphere... missing about 90% of te blocks that are supped tro be in the meteor.

This has been tested on multiple servers 1.10  The syntax for the meteor is fine, seeing as it works perfectly in Single Player game mods.

**Comment by GreatOrator** [comment]
What plugins are on each server?  also what server manager are you using? (i.e. bukkit, spigot, etc)

**Comment by Boolyman** [comment]
I will need some time to get that information, if I even can.  These are not my servers, they are servers for people beta testing my modpack.

**Comment by GreatOrator** [comment]
well if you can, try testing with a local server using only forge and see if the issue still happens.

**Comment by brandon3055** [comment]
I dont see how this could have anything todo with DE

**Comment by tyler489** [comment]
pretty sure this is bloodmagic.

**Comment by GreatOrator** [comment]
Yeah, agree with brandon, this needs to be reported to the blood magic dev
