### ISSUE TITLE
Celestial manipulator doesn't reset vanilla rain timer

### ISSUE THREAD

**Issue by Optimoos** [brandon3055/Draconic-Evolution#667]
When using the celestial manipulator to clear weather, it almost always returns the next day. This is indicative of the internal weather chance counter not being reset when the weather is changed. I'm not sure if this is intentional or not, but thought I'd bring it up.

Playing All The Mods v2.5.3
Which includes Draconic Evolution 2.0.8.177 and BrandonsCore 2.1.4.92.

**Comment by brandon3055** [comment]
The manipulator stops the rain in a similar way to the toggledownfal command. I think its mostly just random chance but i will look into it.
