### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by M0R3design** [brandon3055/Draconic-Evolution#669]
This mod is absolutely ridiculous. I love it!

I have some suggestions though:

1. Add toggles for enchantments for the Draconic tools. I hate to have a different tool for silk touch, because i chose fortune for my staff of power.

2. Fusion recipes for enchantments would be great. Smacking a group of mobs into space because of draconic knockback would never get old.

3. A button to switch between profiles inside the config gui would be great

4. Having a void filter for the tools would make life a lot easier. If there is a way to stop the items from dropping entirely, that would be awesome. Especially useless mob drops.

Keep up the great work, I really enjoy this mod!

**Comment by bookerthegeek** [comment]
1. Profiles. Learn them Love them.
2. Create custom recipes? Or are you talking about custom Enchants?
3. There is a Key bind... Inside the GUI would be helpful.
4. Trash slots.
