### ISSUE TITLE
Crash when calling DraconicOre.getIcon() outside of a world.

### ISSUE THREAD

**Issue by portablejim** [brandon3055/Draconic-Evolution#67]
When rendering DraconicOre outside of a world (i.e. in the configuration screen of mods), "[Minecraft.getMinecraft().theWorld.provider.dimensionId](https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/common/blocks/DraconiumOre.java#L54)" causes a NullPointerException.

See http://pastebin.com/efFKQ6fx (from portablejim/VeinMiner#24)

**Comment by brandon3055** [comment]
Added a check to make sure Minecraft.getMinecraft().theWorld != null
