### ISSUE TITLE
Mining Nether draconium ore with a Silk Touch pickaxe

### ISSUE THREAD

**Issue by PapiDimmi** [brandon3055/Draconic-Evolution#670]
You can‘t use the ore in any recipes. You can’t crush nor smelt it.

**Comment by Anaerin** [comment]
So place it down and break it with a non-silk-touch pickaxe. Or some other kind of block breaker.

**Comment by PapiDimmi** [comment]
What kind of ore can’t be crushed or smelted? Come on, man.

**Comment by Morpheus1101** [comment]
An ore that has no purpose other than being turned into an ingot singularly for recipes only in DE? It serves no purpose in Silk Touching it

**Comment by PapiDimmi** [comment]
Every single ore, except the Nether draconium ore, can be mined with a Silk Touch pickaxe and subsequently crushed or smelted to turn it into dust or an ingot. I don’t see why you can’t just crush the ore or smelt it in order to get some draconium dusts.

**Comment by Anaerin** [comment]
ISTR that in earlier versions of DE, even using a silk touch pick, breaking a draconic ore block would drop dust. I could be wrong on that part, but I seem to recall that being how it worked.

**Comment by PapiDimmi** [comment]
@Anaerin The ore drops itself when using Silk Touch in 1.10.2.

**Comment by Anaerin** [comment]
I know, I just tested it. But I seem to recall in earlier versions of the DireWolf 20 1.10.2 pack, breaking ore with a silk touch pick dropped dust.

**Comment by PapiDimmi** [comment]
But that doesn’t happen now, so it’s irrelevant.

The ore _should_ drop itself, but currently, it’s useless as itself. @brandon3055 should make the ore smeltable and/or crushable.

**Comment by legodude17** [comment]
According to JEI, you can induction smelt it with cinnabar. (Using FoolCraft 1.3)

**Comment by ktole1999** [comment]
just add the ore to block placer/breaker. done. no need to change mod, especially if its something that Brandon never intended to happen.

**Comment by brandon3055** [comment]
Im sure i have already answered this question. Draconium ore is not like most ores. It drops similar to a block like lapis but unlike lapis its dust smelts directly into ingots. Doubling this ore would be very inefficient as you can get up to 12 ingots using fortune. Thats why there is no pulverizer recipe.
