### ISSUE TITLE
Draconic reactor doesn't emit comparator signal

### ISSUE THREAD

**Issue by Froggy800** [brandon3055/Draconic-Evolution#671]
The reactor doesn't interact correctly with redstone comparators when set to output the signal according to the saturation level, always emitting zero as redstone output signal; setting the output _inverted saturation_ always outputs 15.
The other comparator output settings appear to work correctly.
Tested on version 1.10.2-2.0.9.189 and forge 12.18.3.2254.

**Comment by brandon3055** [comment]
Will be pushing a hotfix momentarily.
