### ISSUE TITLE
Using OpenComputers to set a FluxGate returns and error

### ISSUE THREAD

**Issue by PseudoEnd** [brandon3055/Draconic-Evolution#673]
When i try to set a Flux Gate with opencomputers it returns an error

"Expected integer at index:0"

getting the false and setting the override state is not an issue.
![capture](https://cloud.githubusercontent.com/assets/26850500/24585860/a476c5c6-1794-11e7-8d06-d158fd4edf7d.PNG)

**Comment by brandon3055** [comment]
Fix pushed
