### ISSUE TITLE
[1.10.2] Blast feature config idea

### ISSUE THREAD

**Issue by YOYOK9** [brandon3055/Draconic-Evolution#676]
Would it be possible to adding a explosion size config to the reactor? Just to allow servers to lower the blast range, so it won't completely obliterate the world (small worlds) when 1 player messes up... Just an idea. Also be good for people with "bad" pcs that wanna build the reactor but the explosion kills their game. 

Just a config feature idea. 

ex: tnt is 4 (i think)
so lowest possible could be 16 -20 or something. Still leaves a hole in the base but eases up on the server.

**Comment by brandon3055** [comment]
This will be in the next release.
