### ISSUE TITLE
[1.10.2] IllegalArgumentException crashing server

### ISSUE THREAD

**Issue by jarquafelmu** [brandon3055/Draconic-Evolution#677]
Having an `IllegalArgumentException` crashing our `FTB Beyond 1.3.0` server upon using the teleportation gate from Draconic Evolution. At least that's what I think the issue is. 

I hope these crash logs help. If I can provide more information please let me know.

[crash-2017-04-03_05.03.02-server - draconic evolution teleport.txt](https://github.com/brandon3055/Draconic-Evolution/files/891836/crash-2017-04-03_05.03.02-server.-.draconic.evolution.teleport.txt)
[crash-2017-04-03_06.24.00-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/891837/crash-2017-04-03_06.24.00-server.txt)

**Comment by brandon3055** [comment]
This should be fixed in the latest version
