### ISSUE TITLE
2 Chaos dragons

### ISSUE THREAD

**Issue by Nachoboi** [brandon3055/Draconic-Evolution#679]
In FTB beyond 1.3.0 there are 2 chaos dragons every chaos island. 
SS of proof: http://imgur.com/ycU8tOJ
I know the SS is bad, but i can't stop fighting just to try and get both dragons in the screenshot without dying...

How to replicate is beyond me, but i simply just head to the island, fly away and return and another dragon will be there to join the fight. I also noticed that the dupe stopped the island from exploding as well as preventing me from getting the chaos shards. This only happened in my first fight, the second time it happened i was able to loot the shards and somehow the dragon survived the explosion. 

I wish i could provide more information, but this happened just yesterday and i assumed it was to prevent the player from leaving the island to kite the dragon by breaking its AI (lead it away, hit it once, then attack it while it flies back to the chaos island).

Also, the second dragon drops the same amount of XP, but no dragon heart (which is odd b/c the first dragon does). It also has no effect on chaos shards or the chaos island itself, once killed it just dies and drops XP and that's that. Some strange anomaly happens when you TP away and stay away for about 10 minutes, the second dragon will "despawn" until you return, fly away (say from kiting the chaos guardian) then fly back to the island again.

**Comment by Viper007Bond** [comment]
#684 is newer but has a lot more details.

**Comment by brandon3055** [comment]
This should be fixed in the latest release.
