### ISSUE TITLE
Request: Dedicated furnace output slot in Draconic Chest

### ISSUE THREAD

**Issue by MystPhysX** [brandon3055/Draconic-Evolution#68]
Hey Brandon,

I was wondering if it would be possible to add an option to have a few slots in the chest dedicated to an item (set by a filter?) or an output slot like the RFTools AutoCrafters?

Basically I have been using the Draconic chest as a furnace for my glass generator because it doubles output:

ExtraUtils cobblegen -> Sag Mill (for sand) ->  Draconic Chest -> storage

as well as a dedicated draconium ingot furnace in my AE2 system.

The issue with this is if I am smelting more items than the chest can hold, the furnace function is halted as there is no space left to put the smelted items. Your chest is one of the best furnaces in the FTB Infinity pack and this would make it even better.

Thanks!

**Comment by brandon3055** [comment]
Already done.

**Comment by MystPhysX** [comment]
Oh, cheers. 

I apologise for the ignorance on my part then. I hope the changes propagate to Infinity soon.

Thanks for your awesome mod!

**Comment by brandon3055** [comment]
they should already be in infinity. Infinity just updated to RC 4

**Comment by MystPhysX** [comment]
Strange, I wasn't getting the update reminder. I'm updating now.

**Comment by brandon3055** [comment]
Maby its not recommended yet?

**Comment by MystPhysX** [comment]
You're right, 1.3.4 is still recommended whereas 1.4.1 is the latest. Thanks for bringing it to my attention.
