### ISSUE TITLE
Loot Core Compatibility Issue w/Iron Backpacks

### ISSUE THREAD

**Issue by Ghan04** [brandon3055/Draconic-Evolution#683]
Related to this issue: https://github.com/brandon3055/Draconic-Evolution/issues/593

I'm running 1.10.2-2.0.8.177 of DE via the Direwolf20 pack on my server. I've noticed that when I happen to have a compression or void upgrade on an Iron Backpack, the loot cores aren't properly processed and the loot is dumped in my inventory. For example, if I have cobblestone configured in the Compression section of my backpack (which is supposed to auto-craft it in a 3x3 and yield Compressed Cobblestone inside the backpack), it ignores this and just dumps the cobblestone directly in my inventory (not in the backpack at all). The same appears to happen with void upgrades on the backpack when picking up loot cores - I receive all the cobblestone that is supposed to be voided.

Not sure if this is actually a Draconic loot core issue or something that would have to be addressed in Iron Backpacks. If that's the case, let me know.

Thanks!

**Comment by brandon3055** [comment]
Its hard for me to do anything about this on my end other that add the basic hooks required for other mods to handle this properly which i have done already.

**Comment by Ghan04** [comment]
Understood. Sounds like Iron Backpacks maybe isn't following standard.
As a workaround, would it be possible to add a toggle to loot cores somewhere to turn them off? I'm not sure how much lag this would introduce with the max tier mining, but I wouldn't mind mining more slowly if everything got picked up properly.

**Comment by brandon3055** [comment]
Consider it done.
