### ISSUE TITLE
Draconic Reactor

### ISSUE THREAD

**Issue by forestbat** [brandon3055/Draconic-Evolution#685]
![2017-04-03_19 02 50](https://cloud.githubusercontent.com/assets/23413915/24701418/faada9f6-1a2c-11e7-8e19-c069611efc50.png)
I often can't charge RF to the reactor——where I was wrong？I have opened the creative cache of EIO。

**Comment by brandon3055** [comment]
The injector is too close. It must be astleast 3 blocks away. Any blocks the reactor touches while running will be destroyed.
