### ISSUE TITLE
Items input to fusion crafting core go into output slot

### ISSUE THREAD

**Issue by Hazmatik** [brandon3055/Draconic-Evolution#687]
When piping items into the fusion crafting core with ender IO conduit once the input slot is full it starts putting the items into the output slot.

FTB Beyond version 1.4.0
Draconic Evolution version 2.0.9.192
BrandonsCore version 2.1.5.97

**Comment by nematrec** [comment]
I'd like to add that hoppers and other item conduits also pull out from the input slot.
