### ISSUE TITLE
Text and pics in Draconic Tablet flowing over boundary.

### ISSUE THREAD

**Issue by MystPhysX** [brandon3055/Draconic-Evolution#69]
Here you go,

RC 5 FTB Infinity 1.4.1
![screen shot 2015-04-16 at 6 03 40 pm](https://cloud.githubusercontent.com/assets/6554675/7180874/46e6f19e-e463-11e4-8bb7-3da7b7f7cadc.png)
![screen shot 2015-04-16 at 6 05 08 pm](https://cloud.githubusercontent.com/assets/6554675/7180888/612123ea-e463-11e4-85fa-76e5f6bb6e31.png)

**Comment by brandon3055** [comment]
That text is temporary so im not to concerned about it. As for the pics. They are meant to fade out at the top and bottom like that. Better then to just have them pop in and out of existence as you scroll up and down.

**Comment by MystPhysX** [comment]
Okay, no issues then.
