### ISSUE TITLE
Draconic reactor continuing to produce energy after 100% fule conversion.

### ISSUE THREAD

**Issue by nematrec** [brandon3055/Draconic-Evolution#690]
Still happens even if the reactor is shut down and restarted. Additionally core temperature rises dramatically while shutting down.

Version notes
This occurred in version 2.0.9.192
Updating to version 2.0.10.193 did not fix the issue, however it was using the same reactor still in the 100% fuel converted state without replacing any fuel.

**Comment by brandon3055** [comment]
Hmm... will fix that as soon as possible. In the mean time you will just have to manually detonate your reactor by shutting off the containment field. Sorry for the inconvenience.

**Comment by nematrec** [comment]
This actually gave me an idea for a suggestion.

Once it runs out of fuel, the required field input rate to mantain the current field strength and energy generation of the current saturation point could become volatile, shifting randomly over time.

Could go well with the reactor core turning black, with bright jagged lines running over it like lightning.

**Comment by brandon3055** [comment]
i think an unpreventable explosion as already volatile enough.
