### ISSUE TITLE
Crystal Binder can't switch mode?

### ISSUE THREAD

**Issue by USCONAN** [brandon3055/Draconic-Evolution#691]
it can't be switched between the settings by shift+right-clicking
if this is new change of current version, than how to manage energy crystal?
i tested in version 2.0.9 and newest 2.0.10.193

**Comment by brandon3055** [comment]
There are no modes in 1.10+
Simply shift right click a crystal to select it then right click another crystal/block to bind.
To change the mode on an I/O crystal simply shift right click with an empty hand.
