### ISSUE TITLE
[Suggestion] Chaos tier dislocator

### ISSUE THREAD

**Issue by nematrec** [brandon3055/Draconic-Evolution#692]
In addition to previous function you can enter co-ordinates and it'll teleport you to somewhere in that chunk.

Main desire for it is to find and travel to chaos island more easily.

Should probably come with a config option for which dimensions it'll work in. 
Maybe handle cross dimensional teleports by selecting a dimension from already established teleport points saved in it.

**Comment by brandon3055** [comment]
The reason something like this has not been added is it is too powerful and can be abused in too many ways.
