### ISSUE TITLE
texture conflict? Chromaticraft lexicon, draconic armor hud [1.7.10]

### ISSUE THREAD

**Issue by lAimBotl** [brandon3055/Draconic-Evolution#693]
without armor hud
![2017-04-05_22 20 15](https://cloud.githubusercontent.com/assets/10777735/24805206/edfb2578-1b7e-11e7-9e0f-b0cab91dabff.png)

with armor hud
![2017-04-05_22 20 24](https://cloud.githubusercontent.com/assets/10777735/24805209/f052a8dc-1b7e-11e7-87c8-dd78271c2ecc.png)

 turning f3 on also works at removing it.

**Comment by brandon3055** [comment]
Added to 1.7.10 todo list
