### ISSUE TITLE
[Chunk Loading issue] UnLoaded reactor stabilizers/injecters Disassociate from it's reactor

### ISSUE THREAD

**Issue by nematrec** [brandon3055/Draconic-Evolution#695]
When a reactor stabilizer or injector is unloaded while the reactor is charging or activated it will completely disassociate from the reactor. Gui will not open, breaking it will not cause a shield failure.

This seems to only occur after the charge button has been pressed.

Version: 2.0.10.193

**Comment by nematrec** [comment]
Breaking will not cause a reactor failure, but replacing the component(s) will not reassociate them with the reactor.

Not occur 100% of the time, but is reproducible.

**Comment by nematrec** [comment]
Additionally if reactor is only charging and not activated when this occurs to all the components, it become impossible to break or otherwise destroy the reactor.

(currently only bug I found in my proper world >.> any chance for a fix that'll apply to existing occurrences?)

**Comment by brandon3055** [comment]
Unfortunately there is no easy way to automatically fix broken reactors. When the fix is pushed your best bet would be to delete the core using ether the setblock command or MCEdit and then cheat in the core and fuel you lost.

**Comment by nematrec** [comment]
Breaking the components doesn't cause it to explode, would it be possible to have it fix itself by breaking and replacing one?

**Comment by brandon3055** [comment]
There is no easy way to know if the stabilizer(s) was invalid or removed in which case the reactor would explode.

**Comment by nematrec** [comment]
???  I did mention that breaking components after they disassociate will not cause a reactor explosion. Has that changed with your fix?

**Comment by brandon3055** [comment]
Thats because when you break a component it does not tell the core "Hay i have been broken you need to explode now" Which leaves the core in a completely invalid state. There may be a way for the core to detect the issue and re-validate the components but i cant promise anything.

**Comment by nematrec** [comment]
I don't know what's possible, but can a placed component tell the reactor to connect to it after the reactor's been activated? Anyway, I'll stop bugging you on this now, at least it's fixed

**Comment by brandon3055** [comment]
Ok you will just need to leave the components in the same spot they were in originally and right click one of them. Any invalid components will be detected and re validated. 

This code will be removed in a future version because it has the potential to cause issues unforeseen issues.
