### ISSUE TITLE
[Crash] Server crash before reactor explosion

### ISSUE THREAD

**Issue by LiEyWe** [brandon3055/Draconic-Evolution#697]
As the title says, the server crashes before the reactor explodes.
In the crashlog it looks like the mana pools from botania can not be removed correctly.

Chrashlog: [https://pastebin.com/xwu9ZJZU](url)

**Comment by GreatOrator** [comment]
Looks like botania not playing nice with DE

**Comment by brandon3055** [comment]
No thats my fault. Im firing block break after removing the tile.
