### ISSUE TITLE
Dragon Heart issue

### ISSUE THREAD

**Issue by BuckitHead** [brandon3055/Draconic-Evolution#70]
So I'm running the latest on a server. A guy this morning was trying to do the Awakened Draconium ritual with the heart. He keeps saying that the tnt is doing nothing to the heart. After three try's someone says to him are you using 2 TnT's ? He said no. Then he performs it again with 2 TnT and it works but gives him his heart back. Not sure what the issue is but the only other thing that differs him from everyone on the server is the above and he build a obsidian platform in water to do it on that is 5x5 and level with water.  He is going to try and do it again but just wanted to inform that this happened.  So while I'm writing this he is talking in my ear.... Basically the Heart after it changed the blocks to Awakened Draconium stayed there and then dropped like it was coming from the Dragon fight.

**Comment by BuckitHead** [comment]
So now it seems like it happens to everyone, Only updates were CoFHCore-[1.7.10]3.0.2-262, ThermalExpansion-[1.7.10]4.0.1-182 on the server.

**Comment by brandon3055** [comment]
That is something that has been reported before but i was never able to recreate it... 
I have turned down the explosion power required to activate the heart so hopefully that will fix it. I will be releasing RC 5 (which has that adjustment) some time today if i dont find any more bugs.

**Comment by brandon3055** [comment]
Are you able to update to RC 5 and tell me if this is fixed?

**Comment by brandon3055** [comment]
oops did not mean to press close lol

**Comment by brandon3055** [comment]
I figured this out and fixed it in 1.0.1a
