### ISSUE TITLE
Default recipe for Draconic fusion inserter

### ISSUE THREAD

**Issue by Seyeght** [brandon3055/Draconic-Evolution#701]
So using Vanilla Textures it took me a few hours to troubleshoot what the issue with the recipe was in being unable to craft the Draconic Fusion inserter. This is because the Dragon Egg is completely invisible against the background of the Fusion crafting recipe GUI. Not sure how to fix this from a mod perspective, but from a modpack perspective I am going to change my textures to adjust the egg texture to something that wouldnt be completely invisible.

**Comment by brandon3055** [comment]
Yea i really do need to do something about this...
