### ISSUE TITLE
Blank Recipes

### ISSUE THREAD

**Issue by bookerthegeek** [brandon3055/Draconic-Evolution#702]
## Heyo! ##
So Using the configs I have disabled some items from in game. I also turned on Hard mode. Nice job but still I wanted harder recipes. (Yes, I am a douche).

Anyways, while browsing the Fusion Crafting usages, I noticed something interesting.... You can infuse Nothing and get Nothing! Cool right?

![javaw_2017-04-12_01-25-19](https://cloud.githubusercontent.com/assets/3230175/24948497/56727950-1f1f-11e7-8dbf-a56ab45ad36f.png)

Anyways, just thought I would let you know that the recipes for disabled items are not being removed even though the item is no longer their.
#
On a side note, how does it balance the items between the two sides, and what order in the ```CustomFusionRecipes.json```? Just because I like my recipes to look epic and like I just shoved them together.

**Comment by brandon3055** [comment]
Hmm will have to look into that. As far as item order i believe its just left to right top to bottom.

**Comment by brandon3055** [comment]
Oh yea thats an upgrade recipe which isnt bound to a specific set of items so it will show even if there are no items that can be upgraded.

**Comment by bookerthegeek** [comment]
On a pack level then I assume the way to fix that would be to remove all of the recipes then re add the ones we want to show up?
