### ISSUE TITLE
Slash Command request

### ISSUE THREAD

**Issue by bookerthegeek** [brandon3055/Draconic-Evolution#703]
## Heyo! ##
Would it be possible for you to add a command to reload your fusion crafting recipes in game? As a quality of life improvement for us poor folks who are utilizing it, it would save a vast amount of time. Thanks much.

**Comment by brandon3055** [comment]
Why do you need to reload the fusion recipes? I assume you mean the custom fusion recipe config rite? If so there is already a way to do this its just not documented. 

Use the following command to give yourself a debugger.
/give @p draconicevolution:debugger
Shift right click until its in "Recipe" mode then right click to open my recipe creation gui which contains a reload button.
Unfortunately this cannot be used to create custom fusion recipes its just used to generate my hard coded recipes.

**Comment by bookerthegeek** [comment]
Gotcha, it was so that I would not have to restart minecraft each time I am going through and testing different recipes. I will have to look into that Debugger though.
