### ISSUE TITLE
NBT Recipes

### ISSUE THREAD

**Issue by VizionG** [brandon3055/Draconic-Evolution#704]
I've been trying to understand how the nbt tags work but the items never show in the recipe

[
    {
        "mode": "ADD",
        "result": "[draconicevolution:reactor_core]",
        "catalyst": "[draconicevolution:chaotic_core]",
        "energy": 1000000,
        "tier": 3,
        "ingredients": [
            "[draconicevolution:draconium_capacitor,1,1,{Energy: 256000000}]"

        ]
    }
]

Its something wrong with the json or is some JEI/Draconic bug?

**Comment by brandon3055** [comment]
1 minor mistake. Dont need the square brackets on items anymore.  

`[
    {
        "mode": "ADD",
        "result": "draconicevolution:reactor_core",
        "catalyst": "draconicevolution:chaotic_core",
        "energy": 1000000,
        "tier": 3,
        "ingredients": [
            "draconicevolution:draconium_capacitor,1,1,{Energy: 256000000}"
        ]
    }
]`

**Comment by Jemsuper** [comment]
Oh does the fusion crafting have crafttweaker support? Didnt know that cool.

**Comment by brandon3055** [comment]
It does not it uses the default minecraft recipe string format used by the give command for example. I just replace spaces with commas
