### ISSUE TITLE
[Bug/intended?] Chaos tier upgrades can't be applied

### ISSUE THREAD

**Issue by nematrec** [brandon3055/Draconic-Evolution#705]
With the exception of the draconic flux capacitor, no items can receive any chaotic tier upgrades.
This includes rf capacity upgrades to items aside from capacitors.

**Comment by brandon3055** [comment]
There are no chaos tier tools to apply them to (yet)

**Comment by nematrec** [comment]
Is it intended for Draconic flux capacitors to receive the chaotic tier RF capacity upgrade?
