### ISSUE TITLE
DE version name

### ISSUE THREAD

**Issue by forestbat** [brandon3055/Draconic-Evolution#708]
I'm an editor of a Chinese website www.mcmod.cn which is an encyclopedia website of minecraft and mods，now we want your authority to repost your mod to there for Chinese players know more about DE，do you agree？
And we want to use “DE 2” instead of “DE for 1.10.2” to describe the mod to players，how do you think？

**Comment by brandon3055** [comment]
I dont see why you cant just post a link to curse. Curse even gives you the option to add embedded download widgets like so http://ss.brandon3055.com/4hsa1oh.jpg I do not allow reposting.
As for DE 2 the 1.10 version is technically DE 2 already as it is version 2.0.x but its usually just referred to as Draconic Evolution.

**Comment by forestbat** [comment]
@brandon3055 Yes I know。
