### ISSUE TITLE
Energy Infuser stopped automically extracting

### ISSUE THREAD

**Issue by trisity** [brandon3055/Draconic-Evolution#71]
Using Draconic-Evolution-1.7.10-v1.0.1-RC-4 and previous version I could automate the charging of Draconium Blocks to Charged Draconium Blocks in the Energy Infuser with AE2 Import Bus and Export Bus facing a chest, and that chest using Ender IO Item Conduits going to the side of the Infuser.

On RC-4 it will insert Draconium Blocks using the above method just fine with Item Conduits but it will not extract them on any side, and using AE2 import/export busses directly on the Infuser do nothing on any side.

**Comment by brandon3055** [comment]
Oh i know exactly why that is happening ***Insert technical explanation here*** Will have it fixed in RC 5 (which i plan to release some time in the next few hours)
