### ISSUE TITLE
Chaotic

### ISSUE THREAD

**Issue by DraconicEvolutionFan** [brandon3055/Draconic-Evolution#710]
When will the Chaotic Tier upgrade be available? And i think it would be cool, maybe alot of work but to have Chaos Armor. At the moment the chaotic tier upgrade on the draconium armor would be nice and i would love it. At the moment the fusion crafting recipe is there but it is telling me that this upgrade is to high of a level for the armor piece.

**Comment by DraconicEvolutionFan** [comment]
I am playing on the SF3 pack btw^^^

**Comment by GreatOrator** [comment]
Right now the reactor is the main focus as well as working out bugs remaining from the port to 1.10.  Once the core features are available and stable, then we can work on the chaotic tier of things :D

**Comment by brandon3055** [comment]
I have extensive plans for a total re write of the armor and some changes to the tools which will include the addition of a chaos tier. But needless to say this will take a while and probably wont be ready until 1.11. However i will be back porting to 1.10

**Comment by CrayzyOne** [comment]
Hey branndon3055,
do you have any news about the upgrades and changes?
Would be nice to read something.
