### ISSUE TITLE
Draconic Reactor didn't explode

### ISSUE THREAD

**Issue by chipgeekjr** [brandon3055/Draconic-Evolution#711]
Was testing the reactor in 1.10, and somehow got this to happen:
![eyeofharmony mc](https://cloud.githubusercontent.com/assets/26667926/25104750/8a85f82e-238f-11e7-9588-b76882acdfbe.png)
Said the stabilzers were fried, but it wouldn't explode. I broke them and the energy injector, and it still didn't blow up.

**Comment by covers1624** [comment]
Open its GUI, it will tell you how long you have until it explodes, its not instant like 1.7.

**Comment by chipgeekjr** [comment]
I'm aware it's not instant, but is it supposed to just sit there without the stabilizers or injector? The only thing that's left is the core. Which doesn't have a gui.
