### ISSUE TITLE
Server crash when IO-crystal directly set on  factory block proxy of Wood

### ISSUE THREAD

**Issue by TNTdesigner** [brandon3055/Draconic-Evolution#714]
[crash-2017-04-19_23.07.46-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/938482/crash-2017-04-19_23.07.46-server.txt)

**Comment by brandon3055** [comment]
Would help if you gave more detail but it looks like whatever block your inserting energy into is broken. As far as i can tell this is not a problem with DE. The target block is reporting that it has a capability but then returning null when i try to access that capability.
