### ISSUE TITLE
[Question] How does the energy net handle loops?

### ISSUE THREAD

**Issue by jinks** [brandon3055/Draconic-Evolution#715]
Just before I build something stupid, how well do the energy relays handle loops.

Let's say I have an EnderIO power bank, a few consumers and a reactor of some kind. input I/O crystal on the reactor, output on the consumers, maybe a wireless relay somewhere. 

Can I attach an input I/O crystal and an output one to the power bank and wire them through the same relay together with the reactor and the consumers?

**Comment by brandon3055** [comment]
It should work just fine. The network will just accept energy from all available inputs and balance that energy across the network.

**Comment by jinks** [comment]
Thank you. That correlates with what I observed. I just wanted to make sure I wasn't creating a horrible lag-monster that slowly eats TPS in the background due to feedback loops. Some other mods' cabling were capable of that. :)
