### ISSUE TITLE
No information on Reactor in the Tablet

### ISSUE THREAD

**Issue by SkipABeat** [brandon3055/Draconic-Evolution#716]
There is no information on the new reactor in the draconic tablet.

**Comment by brandon3055** [comment]
This is on my todo list but its pretty much the same as in 1.7.10 so feel free to go look at any of the gazillion 1.7.10 reactor tutorials. 

> Summery of 1.10 reactor changes:
> 
> As far as people using redstone control are concerned everything is essentially the same. With the exception of the reactor states.
> The states are now as follows.
> 
> Invalid Setup
> Offline
> Warming Up
> Online
> Stopping
> Cooling Down
> Explosion Imminent
> 
> These are pretty self explanatory. The "Explosion Imminent" state is a new state that the reactor goes into before exploding.
> Once this state is triggered there is no way to stop the impending explosion.
> 
> There is also a new failsafe mode which will automatically initiate shut down the reactor when the saturation reaches 99% and the temperature drops bellow 2500C 
> 
> OC users:
> The logic is also the same here.
> There is now a new setFailSafe(boolean) method that simply sets the failsafe state.
> 
> There are also some minor changes in the output of the getReactorInfo method. Specifically the status field.
> status will now contain one of the following. invalid, cold, warming_up, running, stopping, cooling or beyond_hope.
> There is also a "failSafe" field which simply contains the failsafe status.
