### ISSUE TITLE
Shift-Right clicking the crystal with an empty hand, but a non-empty off-hand, doesn't work.

### ISSUE THREAD

**Issue by RobertBouillon** [brandon3055/Draconic-Evolution#717]
Not sure if this is intended behavior, but it's frustrating when you're shift-right-clicking the energy crystal with an empty hand and it's not changing modes, just to realize you have something in your off-hand. Removing the item in your off-hand allows you to change modes again.

**Comment by brandon3055** [comment]
You can blame vanilla for this. Unfortunately there is no easy fix for this issue. I will have to do a terrible hack to make this work and im not sure if i want to do this yet.
