### ISSUE TITLE
Reactor Energy Injector not outputting redstone signal

### ISSUE THREAD

**Issue by kingchills** [brandon3055/Draconic-Evolution#720]
I'm not sure if I'm doing something wrong, but I cannot get the Reactor Energy Injector to output a redstone signal.  I have tried all of the settings in the GUI, and i cannot get it to output anything.  Is this just not implemented yet?  Am I ahead of the curve?

MC 1.10.2
Forge 12.18.3.2254
DE 2.0.10.193

FTB Beyond Modpack

**Comment by brandon3055** [comment]
That should work in the version you have. Are you using a comparator?

**Comment by kingchills** [comment]
The comparator was the part of the missing puzzle!  I saw someone else's video on that today and it cleared everything up!  Thanks for the response!

**Comment by RickyGeo** [comment]
hey i cant change the Injector mode _-

**Comment by brandon3055** [comment]
@RickyGeo Need more info than that. What minecraft version are you using? Can you not figure out how to change the mode? Or is it just not working?

**Comment by RickyGeo** [comment]
i use 1.12.2 version ... 
a new one

**Comment by brandon3055** [comment]
Ok you still have not told me what the problem is. 
Once you put fuel in the reactor and hit charge you should have the option to change the redstone mode for the block you are accessing.
![](https://ss.brandon3055.com/0d697)
![](https://ss.brandon3055.com/207e7)

**Comment by RickyGeo** [comment]
ow tqtq XD
