### ISSUE TITLE
Bug With Energy Storage Multiblock (Infinit RF)

### ISSUE THREAD

**Issue by FexMa** [brandon3055/Draconic-Evolution#721]
Hallo i play Infinity evolved skyblock on **Minecraft Version 1.7.10** and 
Draconic-Evolution-1.7.10-1.0.2h.

I build A Tier 2 Energy Core, The energy core overcharged and now dont discharge 
so i have infinite RF.

![Image](http://i.imgur.com/Ov3wE0l.png)
![Image](http://i.imgur.com/mKlOELM.png)

**Comment by brandon3055** [comment]
Im not currently developing 1.7 but that sounds like a very unusual bug that should not be possible...
I will add this to my 1.7 todo list.
