### ISSUE TITLE
Bug With Draconic generator coinciding with Iskallium Reactors

### ISSUE THREAD

**Issue by KisameSan2** [brandon3055/Draconic-Evolution#725]
Here to post a world crashing bug. Placed the generator unknowingly that it was next to the power tap. placed fuel in and it crashed my client and world. no crash log pops up and cant get into world without using MCedit. Tried to see if it was an iskallium reactor bug with other generators but it only happens with the Draconic Generator. When Iskall sets up a github i will post this there as well.

**Comment by brandon3055** [comment]
There should be a crash log in the crash-reports folder in the minecraft run directory.

**Comment by brandon3055** [comment]
Closed because no reply from OP
