### ISSUE TITLE
Draconic Reactor field input power drops almost instantly after relogging and explodes

### ISSUE THREAD

**Issue by jstaff62** [brandon3055/Draconic-Evolution#726]
I'm using the latest 2.0.10 release, and simply all I did was close minecraft for the night, then when I came back on this morning, the field power started dropping way faster than I could stop it. I didn't get a chance to see what happened with my potentiometers or comparator but as far as I know they were fine, maybe they were just loading? I don't know, and don't have a backup of just before it started, only before I turned on the reactor.

Edit: I quickly ran to test the flux point i had connected to the input, seems it lost connection with the plug... so that's the closest reason i can think of. for some reason the two mods have never worked too well together.

**Comment by SFort** [comment]
I had a similar issue i can up to the reactor (After server reboot) and tried to open the interface Which would not want to open. so i Flipped on a emergency power switch and then tried to get a signal with a comparator and then OpenComputers neither of them could interface with the reactor that was clearly still running and using my power , a few moments after this my reactor started its whole time to screw over you and your base thing. So now i took a backup of the server in hope there is a way to resolve this issue.(Is it possible to remove the reactor in creative?)

**Comment by brandon3055** [comment]
This should be fixed in the latest release. Im guessing this is related to an issue where reloading chunks would disconnect components from the core.

**Comment by SFort** [comment]
This happened in 193
I would test this again on the server but for some reason the reactor won't heat up(Charge)
Works fine in single player
Forge:12.18.3.2254
Draconic: 199
BrandonsCore: 2.1.6.98
CodeChickenLib: 4.1.1.156

**Comment by brandon3055** [comment]
Nice!
