### ISSUE TITLE
Inconsistent Fall Damage From Boots

### ISSUE THREAD

**Issue by BiohazardStuff** [brandon3055/Draconic-Evolution#727]
Versions:
- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Brandons Core: 2.1.6.98
- Draconic Evolution: 2.0.10.199

So I'm not completely sure about this but I assume it's a bug. There's a few cases that seem to be dictating the fall damage taken with wyvern and draconic boots.

These are the cases for the 'Jump Modifier' setting:
- 0%: Damage is absorbed by shield
- 1%+: Some level of fall damage absorption based on percentage

~~- 1-60%: Full damage taken~~
~~- 61%+: No damage taken to health or shield~~

**Comment by BiohazardStuff** [comment]
After double checking this it looks like my specific percentages were just the height I was testing at so those can be ignored. Is it still intentional for 0% Jump Modifier to be taken by the shield but any other setting will apply a level of I guess feather falling?

**Comment by brandon3055** [comment]
With the boots you can jump several blocks in the air. High enough that you would take fall damage which would be annoying. So when you adjust your jump height it adjusts your fall damage threshold so you dont take fall damage whenever you jump.

**Comment by MaxAstro** [comment]
I think the actual bug here was missed:

With jump boost 0, the Draconic Energy Shield absorbs all falling damage.

With jump boost 1+, the shield DOES NOT absorb ANY falling damage, and you can die from falling with a full shield.

**Comment by brandon3055** [comment]
@MaxAstro Correct there was actually a bug here. It has been addressed in a different issue.
