### ISSUE TITLE
Project intelligence crash when editing tab

### ISSUE THREAD

**Issue by yggdrasil75** [brandon3055/Draconic-Evolution#728]
I am posting this here because I do not know if you have checked the issue on the project intelligence docs project
I have found an error in your mod that fires when I right click on a category or entry. The gist is as follows:
[Gist](https://gist.github.com/yggdrasil75/c72fd8635ebc2e90f894a4476904f598)

**Comment by brandon3055** [comment]
Oops looks like i imported the wrong Arrays class... Will be fixed in the next release.
