### ISSUE TITLE
Chaos dragon dosen't even spawn!

### ISSUE THREAD

**Issue by 21harrisont** [brandon3055/Draconic-Evolution#731]
I am in sky factory 3. I manually added the latest version. As soon as I arrive at the island a couple red orbs are summoned in. I lose very little RF but then the chaos dragon despawns. How do I get chaos shards?

**Comment by ArkavianX** [comment]
This is also happening in FTB-Beyond pack. A friend tried to use a W00t Mob prism on it before it vanished the first time. 

All other 10k sites dragon sprays then vanishes.

**Comment by brandon3055** [comment]
This is an extremely frustrating issue. It seems some other mod is causing guardian to despawn or something... I will try to have this fixed before the next release.

**Comment by 1matto** [comment]
@brandon3055 maby recording the fight from scratch might fix this issue

**Comment by killerjerick** [comment]
Interesting, I also noticed the same behaviour on Ghasts (despawning even though they aren't very far away) Perhaps it's a mod that's attempting to clean up lag?

**Comment by covers1624** [comment]
No, brandon found the issue last i checked. What you are seeing killerjack is an entity de rendering because you are too far away.

**Comment by brandon3055** [comment]
Yes this should be fixed in the latest release. The issue was related to a very minor mistake i made in 1.7.10 which due to minecraft changes became a very big mistake in 1.10.2
