### ISSUE TITLE
Draconic capacitor is a bit small

### ISSUE THREAD

**Issue by forestbat** [brandon3055/Draconic-Evolution#738]
When I upgrade a capacitor（especially wywern to draconic），I cost materials 4 times，but only 128MRF，how do you think this？
In 1.7，we can upgrade a capacitor to 1450MRF。

**Comment by brandon3055** [comment]
I wasnt happy with the capacities in 1,7 i felt they were too high. Im trying to balance thing sout a bit more in 1.10. 128 million RF is more then the top tier storage offered by most mods. And to have all that in an item that can charge your inventory... I think its more than enough for a wyvern tier item.
