### ISSUE TITLE
I/O Crystal crash when connected to a woot farm, version 2.0.8.177 + tested latest curse download, also crashed.

### ISSUE THREAD

**Issue by zeddxinfinity** [brandon3055/Draconic-Evolution#739]
After setting up automated quarrying + power generation via a woot wither farm, I left my server running over night.
When I came back, I found it stuck in a crash-boot-loop. I had to deactivate DE, restart, activate DE, restart to get rid of the entity that caused the crash.

Error supposedly caused by a "draconicevolution:energy_io"
Tracing back to which one caused the crash, it appeared to be the one supplying my WOOT wither star farm with energy, coming from a 3x3x3 Vibrant Capacitor cluster (enderio, also connected via an i/o crystal).

The lever in this screenshot was the position of the i/o crystal, which was connected to a factory proxy. 
Interestingly enough, I also supplied a wither skeleton farm with power through an i/o crystal, however I chose to directly connect that one to the farm (without a factory proxy, so feeding directly into the woot farm controller) and that one seems to not have crashed the server (otherwise it would be listed as well, right?)

https://puu.sh/vGoeL/c099f9eb86.png

Here's the crash log:

https://pastebin.com/EMMkFvLL

**Comment by brandon3055** [comment]
This May be fixed in the next release. Im going to assume its related to the RF api being out of date.
