### ISSUE TITLE
With Soul Vials(Ender IO) capture the Chaos Crystals

### ISSUE THREAD

**Issue by xILikepuddingx** [brandon3055/Draconic-Evolution#740]
#### Issue Description:
You can capture the Chaos Crystals with the Soul Vials from EnderIO.

#### What happens:

see above

#### What you expected to happen:

That you cant do it

#### Steps to reproduce:

Soul Vial - Right click on the Crystal - Done, you capture it

____
#### Affected Versions (Do *not* use "latest"):

- Draconic-Evolution-1.10.2-2.0.10.193-universal
- Minecraft: 1.10.2(1.7.10 not sure but I've heard it)
- Forge:  12.18.3.2254

**Comment by brandon3055** [comment]
This should hopefully be fixed in the next release.
