### ISSUE TITLE
Disenchanter doesn't work right

### ISSUE THREAD

**Issue by EscolarProgramming** [brandon3055/Draconic-Evolution#741]
Hello everybody,
I have trouble with the Disenchanter. I think it only removes the enchantment, but it doesn't reset the amount of enchantments you can add. So you can remove the enchantment, but in the worst case you can't add a new enchantment to the item because it costs too much levels.
Is it possible to add a function that the maximum of enchantments can be reseted? It's a little bit annoying when you remove an enchantment but can't add a new enchantment.
I hope, you can understand my problem.
Greetings, Escolar

**Comment by GreatOrator** [comment]
Consider it the cost of being able to remove enchantments actually, otherwise enchanting becomes too cheap

**Comment by brandon3055** [comment]
Actually if you remove all enchants it should reset the repair cost.  Is this 1.10.2 or 1.7.10?
