### ISSUE TITLE
[Suggestion] Detailed Configurability

### ISSUE THREAD

**Issue by Notawallplan** [brandon3055/Draconic-Evolution#743]
Please add configuration options for each armor/tool set in the mod instead of lumping everything together. I constantly find myself -while nerf/buff things- wishing i can change the specific Energy Shield and Armor values on a piece of the armor set.

Speaking of Energy Shield, i wish i could set a delay between damage and when the Draconic Energy Shield recharges. Default can be 0 (recharge instantly upon damage like before), but i want the option there for myself and other modpack makers who want to tweak this specific mod.

I understand, if you choose to undertake this, that this will take time. Thank you in advance if so.

**Comment by brandon3055** [comment]
Best i can do atm is add an option to adjust the last stand energy cost. If you want to disable it just set it to 2 billion RF (but no higher or the value will overflow and become negative)

I will keep the rest of your suggestions in mind when i eventually get around to overhauling the armor.
