### ISSUE TITLE
Generator crashed server

### ISSUE THREAD

**Issue by OrbitMPGH** [brandon3055/Draconic-Evolution#744]
Placed a Generator next to a powercell from rftools. Server crashed and refuses to start.

**Comment by ktole1999** [comment]
then one of the blocks is causing it and will need to be removed.

**Comment by covers1624** [comment]
Crash report or this will be closed. We have a template for a reason please use it.

**Comment by dannydjdk** [comment]
We had the same problem on our server. Same scenario: crashed when generator was placed next to an rftools powercell, and now crashes whenever a player enters the area.
Here's a crash report:
https://pastebin.com/vAHJ4xN3

**Comment by brandon3055** [comment]
This should hopefully be fixed in the next release. Yell at me again if it isnt.
On second thought if it isnt fixed after this update its probably RFTools so go yell at them.
