### ISSUE TITLE
Draconic Reactor Failing to "Disappear" 

### ISSUE THREAD

**Issue by HyperionNexus** [brandon3055/Draconic-Evolution#747]
After intentionally making a reactor blow, the core did not get removed and is just sitting there. The first reactor  (the right one in the screenshot below) blew up after some fiddling but the core remained. I put another set of stabilizers around it and an injector to see what was going on, and the detonation calculator kept counting down from 60 seconds. I broke the injector and after a while, it exploded again, but the core was still there. I decided to build another one (the left one in the screenshot) and made it blow the proper way, but the same thing happened again.

[Screenshot](http://i.imgur.com/BwHxpKW.png)

DE version: 1.10.2-2.0.12.222

**Comment by brandon3055** [comment]
Are you running sponge?  Also have you adjusted any configs?

**Comment by HyperionNexus** [comment]
Nope, only using the recommended version of Forge and I have not adjusted configs.

**Comment by cleafspear** [comment]
this is occurring on the official FTB Beyond pack as well. vanilla modded in version 1.7.0 1.8.0 and 1.8.1 versions of the modpack, modified no configs whatsoever. it also leaves the reactor stabilizers there as well
every time the chunk loads with the glitched reactor core, it re-explodes renewing its crater on multiplayer. not occurring in SSP.
tested in both ssp and multiplayer

**Comment by Lesnige** [comment]
I also have the same problem  the reactor wont go away,  Any ideas?

**Comment by SDPhantom** [comment]
If you're ok with nerfing the reactor to a TNT explosion and putting lava everywhere, setting **B:disableLargeReactorBoom=_true_** in the config file seems to work.

**Comment by cyris69** [comment]
Was wondering why mine after blowing wouldn't go away and doing multiple explosions.

**Comment by brandon3055** [comment]
This should be fixed in the next release.
