### ISSUE TITLE
Enchanting Staff of Power

### ISSUE THREAD

**Issue by SkippyMitch** [brandon3055/Draconic-Evolution#748]
Can't put silk touch on staff of power?

I removed fortune from my draconic staff via the disenchanter wanting to add silk touch. 

When I put it in the anvil with the silk touch book it takes the book and the levels but the enchantment doesn't end up on it.

1.10.2 - 2.0.12.222

**Comment by Viper007Bond** [comment]
You need to have enough XP in order to enchant, in this case 10 levels. Note the red text. ;)

**Comment by SkippyMitch** [comment]
I took the picture to show the mouse overlay, it shows in the tooltip/overlay thing that the enchantment is not applied to the result. I had already applied one silk touch book before i took that picture. So yeah that screenshot was pretty irrelevant

**Comment by SkippyMitch** [comment]
Well, after I removed the soul bound, looting, and power V enchantments from the staff now it works. Not sure if one of those might be incompatible with silk touch but this can be closed now...

**Comment by SkippyMitch** [comment]
Ah, and it turns out that looting is not compatible with silk touch. That doesn't make any sense to me, but it would seem that it's vanilla minecraft that does that?

**Comment by SkippyMitch** [comment]
Ha this was fixed in Minecraft 1.11.1  i'm just stuck with this problem XD
https://bugs.mojang.com/browse/MC-76057
