### ISSUE TITLE
[Suggestion] Crystal Link Range Aid

### ISSUE THREAD

**Issue by Larkal92** [brandon3055/Draconic-Evolution#750]
Would it be possible to add some sort of visual aid when linking energy crystal to show which ones are in range and which aren't? Like highlighting crystals in range as blue and out of range as red with a faint sphere showing the maximum range when a crystal is selected with the crystal binder to help with placing new crystals?

**Comment by brandon3055** [comment]
Hmm... maby. Will add it to the todo list.
