### ISSUE TITLE
Item Causing mipmap issue

### ISSUE THREAD

**Issue by InvalidUs3r** [brandon3055/Draconic-Evolution#751]
https://github.com/mezz/JustEnoughItems/issues/860
occurs in the newest version, was using optifine.

**Comment by brandon3055** [comment]
This is probably optifine having trouble with my shaders. Try disabling shaders in the DE config and see if the issue goes away. If it is shaders i probably need to poke @covers1624 because it may be on CCL's end. That or its just optifine being optifine...

**Comment by brandon3055** [comment]
https://pastebin.com/

**Comment by brandon3055** [comment]
Closed because no reply from OP
