### ISSUE TITLE
Added fusion crafting recipe not working

### ISSUE THREAD

**Issue by PanSzelescik** [brandon3055/Draconic-Evolution#753]
Hello, my english is not perfect, sorry.
I added fusion crafting recipe for Master Infusion Crystal from Mystical Agriculture.
JEI show crafting, but recipe not working.

json with added recipe:
https://pastebin.com/vJsEtUU0

log:
`[17:19:59] [Client thread/INFO] [draconicevolution/draconicevolution]: Loading Default Recipes...`
`[17:19:59] [Client thread/INFO] [draconicevolution/draconicevolution]: Loading custom fusion recipes...`
`[17:19:59] [Client thread/INFO] [draconicevolution/draconicevolution]: Successfully removed 0 Fusion Recipe(s)`
`[17:19:59] [Client thread/INFO] [draconicevolution/draconicevolution]: Successfully added 1 Fusion Recipe(s)`
`[17:19:59] [Client thread/INFO] [draconicevolution/draconicevolution]: Finished Initialization`
`[17:19:59] [Client thread/TRACE] [draconicevolution/draconicevolution]: Sent event FMLInitializationEvent to mod draconicevolution`
`[17:19:59] [Client thread/DEBUG] [FML/]: Bar Step: Initialization - Draconic Evolution took 0,898s`

JEI:
![2017-05-17_17 24 34](https://cloud.githubusercontent.com/assets/26679785/26162019/dc69195c-3b25-11e7-9446-0b5c3d73d994.png)

Crafting:
![2017-05-17_17 24 51](https://cloud.githubusercontent.com/assets/26679785/26162064/f3ab35aa-3b25-11e7-92cb-a70ca5ba9a8d.png)
![2017-05-17_17 24 54](https://cloud.githubusercontent.com/assets/26679785/26162060/f29e9a4e-3b25-11e7-9738-28496090dbe2.png)
![2017-05-17_17 25 07](https://cloud.githubusercontent.com/assets/26679785/26162061/f29f5f60-3b25-11e7-9b08-11db26bdc757.png)

Versions:
Minecraft 1.10.2
Forge 2297
BrandonsCore - 2.1.7.102-universal
DraconicEvolution - 2.0.12.222-universal
JEI - 3.14.7.419
Mystical Agriculture - 1.5.3

**Comment by brandon3055** [comment]
The recipe is working just fine but the fusion crafter isnt setup correctly. The injectors need to be pointing at the core. Take a look at the info tablet for more information.
