### ISSUE TITLE
draconic armour v sword of the cosmos

### ISSUE THREAD

**Issue by superon** [brandon3055/Draconic-Evolution#754]
i read you wrote "added support for Avaritia's "Sword of the Cosmos", i did read more but feel confused as i'm unable to find this, wanting the sword to negate the shielding the draconic armor provides...  running Draconic-Evolution-1.10.2-2.0.10.199-universal and Avaritia-1.10.2-2.0.7 on the fool craft pack.

**Comment by Morpheus1101** [comment]
Avaritia-1.10.2-2.0.7 we didnt add in the various items other than the crafting table, this was done by an Addon mod, the latest version however you will find(un tested) the sword should literally 1 shot anything,  it has been tested on the chaos dragon.

**Comment by brandon3055** [comment]
Actually no. That sword does some hacky crap to get the one hit death. The Draconic shield completely negates hacky crap.
