### ISSUE TITLE
Fusion Crafting upgrade levels

### ISSUE THREAD

**Issue by yamipirogoeth** [brandon3055/Draconic-Evolution#755]
I was attempting to do some chaotic upgrades to my draconic bow to raise the arrow damage. But after putting everything on the injectors and putting my bow in the crafter I got the message "Upgrade level too high for this item" https://prntscr.com/f8zglw However, if I look at the recipes in the crafter I see that a chaotic upgrade is listed but that it seems to be missing the chaos shard and bow in the middle http://prntscr.com/f8zhrc

Is this expected behaviour and will be something added in the future? Or is this something not working right?

**Comment by brandon3055** [comment]
Ok so the way upgrades work in JEI is they are all shown no matter what and they just cycle though the different items that can accept the upgrade. There are currently no items that can accept the chaotic tier upgrade but it is something i will be working on in the future.
