### ISSUE TITLE
Does the Staff of Power no longer have Void Junk ?

### ISSUE THREAD

**Issue by Jonkar** [brandon3055/Draconic-Evolution#756]
I haven't played in quite a while and when i was last on the staff of power had a void option. Has that since been removed ?

**Comment by brandon3055** [comment]
I have been meaning to re implement that is some form or another but for the moment no it does not.

**Comment by theaussiegeek** [comment]
WTF Why has this not been fixed the whole point of spending countless resources on making a staff is for the void ... SO FRUSTRATING

**Comment by Tahakk** [comment]
It is not about if it is going to be fixed. Brandon said it is not coming at this moment. **The end**.

If you want it you can code it yourself instead of barking and mod author who is doing it for free.
