### ISSUE TITLE
Armour Models 1.10.2 All the mods

### ISSUE THREAD

**Issue by GizmoTheAssassan** [brandon3055/Draconic-Evolution#759]
Is their way to switch between these 2 Models?
![687474703a2f2f692e696d6775722e636f6d2f71394f5532397a2e706e67](https://cloud.githubusercontent.com/assets/19195834/26270187/663f5c7a-3cc7-11e7-8efa-25beb66dd011.png)
![687474703a2f2f692e696d6775722e636f6d2f663339714a63582e706e67](https://cloud.githubusercontent.com/assets/19195834/26270188/6b3855ba-3cc7-11e7-9187-e6d1fa00c724.png)

**Comment by brandon3055** [comment]
No the old models are no longer supported. The amount of extra work it would have taken to carry them over to 1.10 could not be justified considering very few people would use them.
