### ISSUE TITLE
Wireless Power issues RC5

### ISSUE THREAD

**Issue by DemonSeedxp** [brandon3055/Draconic-Evolution#76]
Hello, me again.... Back to report some more lag issues.

This time I'm actually pretty darn sure it's the wireless  arrays causing it. 

I've now moved on to building my ore processing room and I'm using only draconic wireless to provide all the machines power. So far I'm about half way though setting up machines (80 thus far) and everything was peachy during setup and configuring, linking all the machines etc. 
then I turned it all on, and oh man. Laggg city. Same as before I'm unable to open machines,  etc. it's bad...

I have a pic of my arrangement so if I'm doing it wrong, or pulling to much maybe you can point it out to me, https://dl.dropboxusercontent.com/u/841137/Minecraft/2015-04-21_18.30.53.png
To troubleshoot the lag I popped out the one relay circled in the image, and almost instantly I caught back up to the server and was able to interact with inventories again. 
Mind you, this is while the wireless transmitters in the corner where still holding power in their buffer and all the machines still running, So definitely not  something with the machines.

Once again, please help! I'm not willing to rewire this, so I'm stuck.... again... :D 

oh btw, I dont know if it's draconic doing it or something else, but my server console is getting spammed with [server thread/info] [fml]: 61
and I have no clue what it means, but it's odd timing linked to the lag makes me think it's part of it. Any ideas?

**Comment by brandon3055** [comment]
Well i can confirm the nodes have a problem with network traffic. It seems to be related to the transfer of energy between nodes. And it seems to be an accumulative effect so the more nodes you have within render distance the worse it will be. 

The few shown in the image would not be enough on their own to cause a serious problem but im guessing you have more nodes then that in your base (Any node type) It would also be more of a large base that already has a lot of other things increasing network traffic.  

I am planning a complete rework of how the nodes transfer energy which should fix the problem but that may take a while to implement. I may be able to come up with a quick fix latter today.

**Comment by DemonSeedxp** [comment]
Excellent, was hoping you'd say that! :D 

The few shown in the image and maybe 3 more are all thats in this dimension.  I'm building that ore processing inside a Spatial storage cell from AE2. So those couple are enough to completely break game play atm. As a matter of fact, I lagged out of the game a few hrs ago, and just logged back in to find my guy still ingame, lagged soo damn hard he never left the game lol

**Comment by brandon3055** [comment]
Sorry i didnt get a chance to work on this last night. But i just uploaded RC 6 which should fix (or atleast significantly reduce the problem)

I just changed the client update time from every tick to every second.
