### ISSUE TITLE
Client crash with chaos gaurdian 

### ISSUE THREAD

**Issue by frenzye** [brandon3055/Draconic-Evolution#761]
https://gist.github.com/frenzye/604595da126597ca38e3b8825c2efaea

**Comment by GreatOrator** [comment]
What modpack and mods do you have installed as well as what version of DE?

**Comment by frenzye** [comment]
https://minecraft.curseforge.com/projects/grimdark
Draconic @ 1.10.2-2.0.12.222, Brandon's core 1.10.2-2.1.7.102
also see https://github.com/brandon3055/Draconic-Evolution/issues/573

**Comment by GreatOrator** [comment]
Right, though that issue was closed over 3 months ago and there have been several updates to DE since then, so may not be the same cause, which also was never found.

Still needed the info so brandon has a better idea of what's going on, so thank you.

**Comment by brandon3055** [comment]
I keep seeing this pop up but have no idea whats causing it. Well... Thats not entirely true i know exactly whats causing it but i have no idea why. It looks like a vanilla bug but if it was im sure it would have been discovered by now and fixed. Are you running any server plugin mods?

**Comment by frenzye** [comment]
Negative, just Forge
