### ISSUE TITLE
Color Request

### ISSUE THREAD

**Issue by AveryLucky** [brandon3055/Draconic-Evolution#762]
Not so much an issue, as a request. I'm new on this website so if this is in the wrong place I am sorry.

We've been playing Draconic Evolution for years on FTB, it is the only reason my wife plays. She has asked me to contact Brandon3055 with a simple request. Can we have anything other than orange? lol

We always get everyone on the server Draconic Armor, because it is awesome. But it is all orange, we all look alike. She likes the way the purple Wyvern armor looks, but she wants what the Draconic does.  Would it be extremely hard to have some color options with your top tier stuff?

Thanks!
Avery S.

**Comment by GreatOrator** [comment]
If you are on 1.7.10, you can use this mod:

https://mods.curse.com/mc-mods/minecraft/225812-cosmetic-armor

**Comment by AveryLucky** [comment]
We are on the new one 1.10.2

But I will tell her about the old one if we go back to Infinity.

**Comment by GreatOrator** [comment]
Awesome, unfortunately because of the way the armor is coded, trying to give it the ability to change colors would be difficult.

**Comment by AveryLucky** [comment]
I'm sure everything about this mod is difficult. There is some fabulous programming and artwork going on there. But it would be cool! :)

**Comment by GreatOrator** [comment]
Maybe @brandon3055 can implement another upgrade key for camoflauge :D

**Comment by AveryLucky** [comment]
That would be a neat idea, and a good use of the fusion crafting system.  I am a programmer, but I've never done Minecraft modding, so I don't know how complex the texture/model swapping is. But the above mod you referenced is a neat idea. He could use the armor you want to use as a texture as one of the catalysts in the fusion system.

**Comment by brandon3055** [comment]
I will add this to my todo list. I cant promises anything but it would be a neat feature.
