### ISSUE TITLE
flight without holding space bar

### ISSUE THREAD

**Issue by yourshadowdr** [brandon3055/Draconic-Evolution#763]
This issue is for 
1.7.10 the latest version

With the chest, i used to be able to fly without holding down the space bar. For some reason, i now have to hold it down. I know this may not be a "issue" but i could not find anywhere else to ask.

Here is what happened, i had the chest, on a old server, we had to move to a new server, same admin and all that, 

old server could float freely, with just double tapping space bar
new server, i have to hold down space bar to fly, so i needed to know what i need to change, or what my admin needs to change to be able to resolve this, i am sure it might just be a small config setting somewhere.

To be clear, i can fly, i just have to hold down space bar, so flight has not been disabled 

When i turn lock flight off, even when i double tap space bar, nothing happens

**Comment by brandon3055** [comment]
It sounds like the DE flight is being override by the flight mechanic from another mod. Something that works more like a jet pack. Im pretty certain its nothing on my end.
