### ISSUE TITLE
Fusion Crafting Injectors drain energy from Energy Core when not used

### ISSUE THREAD

**Issue by SusiKette** [brandon3055/Draconic-Evolution#764]
I was just playing  in my singleplayer world and wondered why my energy generation was only 1 RF/t when looking at the core, so I started following the "energy lines" created by the Wyvern Energy Relays and they appeared to end up going to the Fusion Crafting Injectors even though I was not using it at the moment. To my knowledge, the injectors are only supposed to draw energy to them during the 'Charging' part of the crafting process when they are collecting enough RF to complete the crafting process.

DE Version: 1.10.2-2.0.10.193 (2.0.10)

**Comment by GreatOrator** [comment]
Try updating your DE to the most recent version and see if the issue persists.

**Comment by brandon3055** [comment]
Seems unlikely but its possible one of one of the injectors what some how in an invalid state where it was just continuously accepting power.
Has this happened more than once? If not i think we can just ignore it for now and If it becomes a serous problem i will look into it.
