### ISSUE TITLE
Draconic Sword and Mechanical Users

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#766]
So, I put Looting 3 on a Draconic Sword and put it into a Mechanical User to farm Endermen for dimlets and a day later it still has 16m charge on it, it doesn't seem to be losing charge. 

Oh! Right! That would help immensely. Draconic Evolution 2.0.10.199 in the FTB Presents Direwolf20 1.10.2 mod pack version 1.10.0.

**Comment by brandon3055** [comment]
Hmm... Does the sword have the AOE effect when in the Mechanical User? If not i suspect the fake player isnt actually using the Item#onLeftClickEntity method to attack. If that is the case there is nothing i can do on my end.

**Comment by llloyd4** [comment]
Ok, posted it over on the Extra Utilities 2 Github. - https://github.com/rwtema/extrautilities/issues/1523
