### ISSUE TITLE
Extracting Energy from Generator w/ I/O port

### ISSUE THREAD

**Issue by VadersFist0501** [brandon3055/Draconic-Evolution#767]
![2017-05-23_19 10 46](https://cloud.githubusercontent.com/assets/28911124/26381609/aae42974-3feb-11e7-8ae9-bb16581c88ad.png)

When trying to attach the I/O crystals to generators, no RF is transferred. The energy simply remains stored in the generators internal buffer. I am playing 1.10.2-2.0.12.222-universal

**Comment by covers1624** [comment]
The IO mode is from the grids perspective, not the blocks.

**Comment by brandon3055** [comment]
This will be fixed in the next release.
