### ISSUE TITLE
Draconic Evolution 2.0.12.222 Draconic Fusion crafting not functional 

### ISSUE THREAD

**Issue by raziel23x** [brandon3055/Draconic-Evolution#768]
just updated to this version with FTB Beyond 1.7.0 and the fusion crafting stopped functioning in both multiplayer and single player no log files created for a error

**Comment by Skardsen** [comment]
Do you have at least 2 blocks between Crafting Core and the Crafting Injectors?

**Comment by raziel23x** [comment]
that fixed the issue why was this changed in this update to this

**Comment by GreatOrator** [comment]
To make sure there are no issues when crafting, better aesthetics, multiple other reasons. and..."because"
