### ISSUE TITLE
Spelling error in en_US.lang

### ISSUE THREAD

**Issue by ssteinb** [brandon3055/Draconic-Evolution#769]
The following lines spell the word _color_ wrong. In the US its spelled _color_ while in the UK its spelled _colour_.

I recommend duplicating the file and name it _en_GB.lang_ for the UK users and just fix the spelling error on the US language file.

`msg.draconiumChestEditmode.txt=Colour edit mode =`
`msg.draconiumChestEditL1.txt=Right click with red green or blue dye to adjust the colour`
`msg.draconiumChestEditL4.txt=Right click with paper to copy the colour to other chests`

**Comment by GreatOrator** [comment]
Actually, that is a correct spelling, even for US english, it is simply a matter of preference, like center or centre.  While it is the preferred spelling, it is not grammatically incorrect.

**Comment by brandon3055** [comment]
Alternatively you could move to Australia. Then it will be spelled "correctly"

**Comment by ShayBox** [comment]
It may not be grammatically correct to spell it color in either country, Mojang themselves also change the spelling depending on the language selected, so that should be taken into consideration to follow the games standards.
