### ISSUE TITLE
Death Event Not Firing with Armour on

### ISSUE THREAD

**Issue by Aiidoneus** [brandon3055/Draconic-Evolution#770]
I have been going around trying to figure out the root of this problem. I have had players report this bug to my network. Originally I thought it had something to do with the Gravestones mod. 

https://minecraft.curseforge.com/projects/gravestone-mod/issues/28

^More information about what is causing this here. As the mod author stated in his response, it seems though that the damage is suppose to negate when having the armour on. When something bypasses this, IE the sacrificial dagger from Blood Magic, it doesn't register a death event. When you die, it doesn't drop the armour which leads me to believe this. 

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: forge-1.10.2-12.18.3.2281-universal
* FTB Beyond: 1.6.1

Mods: BrandonsCore-1.10.2-2.1.6.98-universal
          Draconic-Evolution-1.10.2-2.0.10.199-universal

I am willing to provide any further information if needed. =)

**Comment by Tahakk** [comment]
I will take this opportunity to report complete opposite since it seems like collision of DE + Gravestone. When you take critical damage (from player, drake etc.), DE armor will negate your death but Gravestone will appear. This can be really annoying when getting damaged repeatedly, thus making multiple gravestones.

**Comment by brandon3055** [comment]
I will adjust the priority of the event on my end so it runs before these other mods. That should fix the problem. If it does not then there is also an issue on their end,
This will be in the next release.

**Comment by Aiidoneus** [comment]
Thank you. Also wanted to say, great mod. Keep up the fantastic work.
