### ISSUE TITLE
Fluid Gate changes to Flux gate when placed

### ISSUE THREAD

**Issue by Jaksuhn** [brandon3055/Draconic-Evolution#771]
Just the title. I saw a closed bug report saying it was fixed in the next version but it seems it's still in the next version (the current one as of now).

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2254
* Draconiv EvoIution version: 2.0.12.222

**Comment by brandon3055** [comment]
I am not able to reproduce this... And i believe the issue that was closed was regarding the fluid gate turning into a flux gate when **broken**.
