### ISSUE TITLE
I/O Wyvern conduits not extracting from generators

### ISSUE THREAD

**Issue by Punisher106** [brandon3055/Draconic-Evolution#772]
## Description
Out of the blue, my I/O crystals that I use for charging my injectors outright stopped extracting power. I don't know why this is doing this, but it's insisting on not wanting to work. I swapped out generators, changed the nodes to a lower tier, everything, and it's still not working. I know they have a buffer of their own, but... see for yourself.
![2017-06-02_02 57 57](https://cloud.githubusercontent.com/assets/8642875/26714522/c50de104-473f-11e7-8c39-f03252939b1e.png)

Any ideas on how to resolve this?
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281

**Comment by Tahakk** [comment]
Same as here? [#642](https://github.com/brandon3055/Draconic-Evolution/issues/642) - try updating DE since you didn't tell which one you are using

**Comment by Punisher106** [comment]
I actually saw that thread, but these generators are Draconic Evolution generators. The mod version is up to date, at 1.10.2-2.0.12.222.

**Comment by Punisher106** [comment]
Issue still isn't resolved. Any ideas on fixing?

**Comment by Drakkim** [comment]
Have you tried shift-right-clicking them to set them to input mode? They default to balanced mode, which I've never seen work....

**Comment by Punisher106** [comment]
Uh, if you look at the bottom right of the screenshot, you can see they're in Input mode.

**Comment by brandon3055** [comment]
Hmm... my bad... Will be fixed in the next release.
