### ISSUE TITLE
zh_CN.lang doesn't work in the game

### ISSUE THREAD

**Issue by qiuzhonghui** [brandon3055/Draconic-Evolution#773]
## Description
even though i renameed zh_CN.lang to en_US.lang , it does not work also.

## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:12.18.3.2185
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by qiuzhonghui** [comment]
i updated the zh_CN.lang but i dont have the permission to upload it,here is my file


[zh_CN.zip](https://github.com/brandon3055/Draconic-Evolution/files/1050277/zh_CN.zip)

**Comment by brandon3055** [comment]
I just selected zh_CN (The secont last language in the list) and well... I cant read any of this but it seems to work. 
http://ss.brandon3055.com/fp392wu.png
