### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GizmoTheAssassan** [brandon3055/Draconic-Evolution#774]
make it so pylons for the energy core could have glass on the sides

**Comment by GreatOrator** [comment]
That would over complicate the method they use to work honestly, having them on the top or bottom simplifies it.

**Comment by GizmoTheAssassan** [comment]
ok i just thought it would be nice

**Comment by brandon3055** [comment]
I have been meaning to give the pylons an upgrade for a while Just have not got around to it yet.
