### ISSUE TITLE
JEI incorrect draconium recipes 

### ISSUE THREAD

**Issue by bortooo** [brandon3055/Draconic-Evolution#775]
Every recipes with draconium ingot is shwon by JEI with 3 draconium.
I think this is not a draconic evolution bug, but I dont know what is caused by.
I hope someone can help me

![2017-06-09_16 05 40](https://user-images.githubusercontent.com/28114042/26979499-46edc8ac-4d2f-11e7-802b-2c27f104e65b.png)

**Comment by GreatOrator** [comment]
What other mods do you have installed with DE?

**Comment by brandon3055** [comment]
Yea thats not de... Crafting recipes do not even support more than 1 input item per slot afaik

**Comment by bortooo** [comment]
[Mod list](https://pastebin.com/eV59vB4j)
