### ISSUE TITLE
Reactor energy injector not accepting power

### ISSUE THREAD

**Issue by LonelyZero** [brandon3055/Draconic-Evolution#776]
## Description
I'm trying to make the reactor, its all good but the injector doesn't seem to accept any power. I have watched various videos and read other guides, yet I have no results.
![img](https://user-images.githubusercontent.com/29333644/27003818-7c41c632-4e30-11e7-92b9-426d3a3b8ab0.png)
## Base information
* Minecraft version: 1.7.10
* DE version: 1.0.2h

**Comment by brandon3055** [comment]
It does not have an internal buffer WAWLA is wrong. It pipes energy directly into the core so it only accepts energy when the reactor is running.

**Comment by LonelyZero** [comment]
Yes, I understand but the issue is that I cant charge the reactor.
