### ISSUE TITLE
mip map issue caused by looking at de items in jei 

### ISSUE THREAD

**Issue by InvalidUs3r** [brandon3055/Draconic-Evolution#777]
Very sorry for not responding to the previous thread, had some real life stuff to deal with and completely forgot.  #751 
anyways I tried disabling the shaders and nothing changed. I can get video footage if necessary
Optifine also doesn't change anything, BUT by hiding the ender energy manipulator in JEI it solves the problem. Must have been the fancy shader effects on that one item I guess.
## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:12.18.2.2297
* TolkienCraft II version:--

## Crash report
no crash
CRASH REPORT HERE
```

**Comment by InvalidUs3r** [comment]
edit- removing Optifine does not change anything

**Comment by brandon3055** [comment]
Turns out this was an issue on my end. It is fixed as of version 2.1.2.245
