### ISSUE TITLE
Reactor not charging

### ISSUE THREAD

**Issue by LonelyZero** [brandon3055/Draconic-Evolution#778]
## Description
I'm trying to run the draconic reactor, the fuel and computer craft are working but the reactor doesn't seem to charge even with me powering it.
![image](https://user-images.githubusercontent.com/29333644/27007689-399d5554-4e8e-11e7-8b36-0249319b8375.png)

## Base information
* Minecraft version:1.7.10
* DE Version 1.0.2h

**Comment by brandon3055** [comment]
Are you powering it via an injector?

**Comment by LonelyZero** [comment]
Yes, and the injector is connected to the energy storage multiblock via tesseract

**Comment by brandon3055** [comment]
Hmm... Oh was there by any change a block between the injector and the core when you placed it? 
If so you will need to break and replace the injector so it can link with the core.
If that does not work try putting an energy conduit between the tesseract and the core. Place a machine or something on that conduit to make sure there is power available.

**Comment by LonelyZero** [comment]
Thanks a lot it is finally charging, it seems to have been the first problem you mentioned.
