### ISSUE TITLE
RC 6 Flight Speed

### ISSUE THREAD

**Issue by DemonSeedxp** [brandon3055/Draconic-Evolution#78]
Just saw you updated to 6 so I upgraded and immediately I noticed that the speed at which you move up and down while in flight has been cranked way up, and is not configurable in the armor gui. 

The current speed is way to fast. It's moving me 6-8 blocks with a tap of the spacebar, making it pretty much impossible  to align your self with things while building. 

I wouldn't mind this so much if it where configurable, but as is, it's way too fast and making game play very difficult.

**Comment by brandon3055** [comment]
The up/down speed is controlled by the movement speed multiplier on the leggings. Let me know if you think i should add a multiplier just for vertical acceleration.

**Comment by DemonSeedxp** [comment]
Ahhh yes, better...

I do think it should have it's own settings tho. I for one like to keep my speed turned up pretty high, and have mastered everyday gameplay this way, but now that vertical is part of it, I'm forced to slow down just to build.

and kudos for patching the wireless lag, everything seems to be much better. ty
