### ISSUE TITLE
Draconic Armor not recharging in 1.10.2-2.1.0.232

### ISSUE THREAD

**Issue by Ravalli03** [brandon3055/Draconic-Evolution#780]
## Description

Sorry if this was reported already. After updating to the newest version of DE and Brandon's Core 1.10.2-2.1.8.104, my Draconic Armor (fully upgraded to Draconic) will not charge up using the draconic flux capacitor after installing the new update. (I made sure it was turned on to charge armor). I found this bug while fighting the chaos dragon. It will recharge using other mods or using the energy infuser.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by sloppysailor** [comment]
Same issue , capacitors will charge hand held items but not armor

**Comment by brandon3055** [comment]
This should be fixed with the last update to BrandonsCore

**Comment by Ravalli03** [comment]
Cool, thanks for the quick fix.
