### ISSUE TITLE
[Sky factory 3] How the heck do you use the ender energy manipulator

### ISSUE THREAD

**Issue by BleesTFE** [brandon3055/Draconic-Evolution#782]
## Description
I have tried everything, only get the message: Must be placed on the end gateway. I've tried both with the dragon alive and summoned and with the portal active and the dragon dead with the crystals popped. 
## Base information
* Minecraft version:
* Minecraft Forge version:
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by BleesTFE** [comment]
I even tried deleting the dimension, creating a new one, but still doesn't work

**Comment by brandon3055** [comment]
This is a known bug. It dies not work in SF because they moved the end portal from 0, 0

**Comment by BleesTFE** [comment]
Is there a way to fix this?

**Comment by brandon3055** [comment]
I will make some adjustments in the next release. But i cant promise anything it will all depend on how exactly they hack the dragon.

**Comment by BleesTFE** [comment]
Alright, thanks for the help. Btw, I suck at using your Draconic evolution, but it seems to be very well made, props to you.
