### ISSUE TITLE
Rain sensor affects all Celestial Manipulators

### ISSUE THREAD

**Issue by CrypticArk** [brandon3055/Draconic-Evolution#783]
## Description
I have 2 Celestial Manipulators, one with a daylight sensor for when it's night and one with a rain sensor to stop the rain (both away from each other). The Daylight Sensor Celestial Manipulator works fine. However when it starts raining the Rain Sensor gives a Redstone signal which activates both Celestial Manipulators instead of the one just next to it.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
Perhaps your not taking into consideration the fact that it gets darker when it starts raining? Dark enough to trigger a daylight detector.
