### ISSUE TITLE
[1.10.2] JEI Search Bug

### ISSUE THREAD

**Issue by MrSapient** [brandon3055/Draconic-Evolution#785]
## Description
Every time i @Quantum in JEI my server gets the error code i posted spammed.
## Base information
QuantumStorage-1.10.2-3.3.4
jei_1.10.2-3.14.7.420
BrandonsCore-1.10.2-2.1.8.107-universal
extrautils2-1.10.2-1.4.4
Forge-12.18.3.2316

## Crash report
```
https://pastebin.com/3V0RLqzv
https://github.com/gigabit101/QuantumStorage/issues/87
```

**Comment by brandon3055** [comment]
Will be fixed in the next release.
