### ISSUE TITLE
Chaos Crystal explosion kills you in creativemode!

### ISSUE THREAD

**Issue by Minecraftschurli** [brandon3055/Draconic-Evolution#786]
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2297
* DE version: 2.1.0.232

Chaos Crystal explosion kills you in creativemode!

**Comment by brandon3055** [comment]
This was intentional but i think i will change it in the next release.

**Comment by Minecraftschurli** [comment]
It kills you when you are on the border but not when you are on the inside of the explosion!
