### ISSUE TITLE
CustomFusionRecipes won't load

### ISSUE THREAD

**Issue by Minecraftschurli** [brandon3055/Draconic-Evolution#787]
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2297
* DE version: 2.1.0.232

CustomFusionRecipes won't load even when I have everything right!

**Comment by Minecraftschurli** [comment]
Please tell me if I have anything wrong! 
[
    {
        "mode": "ADD",
        "result": "minecraft:beacon",
        "catalyst": "minecraft:nether_star",
        "energy": 1000,
        "tier": 1,
        "ingredients": [
            "minecraft:glass",
            "minecraft:glass",
            "minecraft:glass",
            "minecraft:obsidian",
            "minecraft:obsidian",
            "ore:blockDiamond"
        ]
    },
    {
        "mode": "ADD",
        "result": "minecraft:golden_apple,1,1",
        "catalyst": "minecraft:golden_apple,1,0",
        "energy": 2000,
        "tier": 1,
        "ingredients": [
            "ore:blockGold",
            "ore:blockGold",
            "ore:blockGold"
        ]
    },
    {
	"mode": "ADD",
	"result": "minecraft:elytra,1,0,{Unbreakable:1, AttributeModifiers:[{Name:"Armor",Operation:0,Amount:8d,UUIDMost:1789473684846091260l,UUIDLeast:-1114603339936652540l,AttributeName:"generic.armor",Slot:"chest"},{Name:"Armor Toughness",Operation:0,Amount:2d,UUIDMost:-4453743791226629100l,UUIDLeast:1629564590047667970l,AttributeName:"generic.armorToughness",Slot:"chest"}]}",
	"catalyst": "minecraft:elytra",
	 "energy": 6000,
        "tier": 1,
        "ingredients": [
            "ore:blockGold",
            "ore:blockDiamond",
            "ore:blockEmerald",
	    "ore:blockIron",
   	    "minecraft:beacon",
	    "minecraft:obsidian",
	    "minecraft:golden_apple,1,1"
        ]
    }
]

**Comment by brandon3055** [comment]
Can you please post your entire startup log. Preferably using a paste service like pastebin.com

**Comment by brandon3055** [comment]
Ahh never mind i see your problem. Do not use quotation marks in NBT 
http://ss.brandon3055.com/89mnv4k.png
Here is the corrected recipe:
http://ss.brandon3055.com/ggm9lfe.txt
