### ISSUE TITLE
Chaos Dragon

### ISSUE THREAD

**Issue by Keridos** [brandon3055/Draconic-Evolution#79]
Using Rv4 the chaos dragon seems to deal 110 armor ignoring damage per attack pretty much oneshotting a fully equipped player with 80 health and full armor. Is that intended? Player was wearing modular armour from the mod named like it.

**Comment by brandon3055** [comment]
That sounds about rite. Your best bet is wyvern or better yet draconic armor.

**Comment by Keridos** [comment]
Do you do a special check against the player's armor and if it isn't wyvern or draconic it oneshots them?

**Comment by brandon3055** [comment]
No it just dose a tone of damage that bypasses armor. The wyvern and draconic armor have the ability to protect against damage that would normally bypass armor. Wyvern only blocks 50% so it may still be a one shot but draconic blocks 100% 

Pro tip: Do not use last stand on draconic armor. When you run out of levels you will die even though the draqconic armor should protect you.
