### ISSUE TITLE
1.11.2 Question

### ISSUE THREAD

**Issue by MrSapient** [brandon3055/Draconic-Evolution#790]
I'm in the process of updating my modpack to 1.11.2 and this is one of only 4 mods not updated to 1.11.2.. I'm in no way asking you to rush or expecting you to.. I'm only asking if you do have plans to update or if you are taking a break/moved on from modding or just sticking to 1.10.2.

Thanks

**Comment by GreatOrator** [comment]
https://github.com/brandon3055/Draconic-Evolution/issues/788
