### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by millambarus** [brandon3055/Draconic-Evolution#791]
## Description
in the tablet there is a spelling mistake in the dislocator resepticle (portal) 
in the tablet it says **dislocaror** resepticle (portal) 

## Base information
* Minecraft version:
1.10.2 ( ftb infinity lite) 
* Minecraft Forge version:
most recent 
* TolkienCraft II version:

## Crash report
```-
CRASH REPORT HERE
```-

**Comment by brandon3055** [comment]
Fixed. Go restart your client and this typo will vanish!
