### ISSUE TITLE
Mob Grinder Does Not Kill Ender Dragon -- Is This Intended?

### ISSUE THREAD

**Issue by piepie62** [brandon3055/Draconic-Evolution#793]
## Description
The Draconic Evolution mob grinder does not kill the Ender Dragon, which I believe may be because it is an array of EntityDragonParts instead of a subclass of the normal EntityLivingBase class. While in the EntityDragon class it is, the actual visible part is that array. The version of Draconic Evolution I am using is a bit outdated, however I used a decompiler and saw that the TileGrinder class has the same logic then as now. I don't exactly know how to fix this, but it is a problem that I noticed, unless this is intended. If so, well, I just did a bunch of testing for nothing. :)
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281

## Crash report
```
No report available as there is no crash
```

**Comment by Shadow907G** [comment]
I think it was intinded to not kill it in one shot that wohld be too op it does damage to it but not kills it like the wither

**Comment by piepie62** [comment]
I didn't see it damage it, though I cannot check at the moment. I also doubt this, as I can see no logic for this. (I may be wrong, however)

**Comment by piepie62** [comment]
Yeah, I see no change in health.

**Comment by brandon3055** [comment]
The grinder will not kill the dragon. This is intentional.
