### ISSUE TITLE
[Suggestion] Interdimentional Transfer System

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#794]
## Description

Given that Tesseracts aren't coming back any time soon, if ever, to 1.10.2 - https://www.reddit.com/r/feedthebeast/comments/5xsjlo/what_happened_to_the_tesseract_in_thermal/ - a way to transfer energy at the crazy rates that are needed to not only feed a Draconic Reactor but to take the power from a Draconic Reactor and feed the Draconic Energy Sphere across dimensions. As Direwolf20 discovered, the RFTools version of a tesseract just doesn't transfer energy fast enough and the buffer is far too small. So a Draconic Evolution version of a tesseract would be really really useful, maybe merge the two together, a tesseract that has a maintenance cost and has the usual Draconic tiers that follow the power system.

**Comment by Tahakk** [comment]
Tesseracts are coming back. @KingLemming is remaking them :) Anyway I guess some kind of Draconic mechanic would be nice.

**Comment by llloyd4** [comment]
Yeah, what that article says he is worried about RF creep so they won't be as powerful as before. A Draconic version of it to support the massive RF that Draconic can do will need a Draconic tesseract. I don't mind if it has maintenance costs, just something tiered to support the power tiers (Basic, Wyvern, Draconic, maybe even Chaotic). Hey, crazy idea, maybe even have them support the Draconic upgrade system though fusion injection. :D

**Comment by brandon3055** [comment]
This is something on my possible future features list but not sure if or when i will implement something.
