### ISSUE TITLE
Chaos Implosion doesn't show effect on client side

### ISSUE THREAD

**Issue by SolaKun** [brandon3055/Draconic-Evolution#795]
## Description
Chaos Implosion doesn't show effect on client side

## Base information
* FTB Beyond: 1.10.0
* Minecraft version: 1.10.2
* Minecraft Forge version: 
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
This will be fixed in the next update.
