### ISSUE TITLE
i/o crystals

### ISSUE THREAD

**Issue by deadlywolf301** [brandon3055/Draconic-Evolution#796]
## Description
cannot change the input or output of the crystals
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: latest
* TolkienCraft II version:

## Crash report
```none
CRASH REPORT HERE
```

**Comment by covers1624** [comment]
Read the in-game documentation in the book, if this was an actual issue it would be effecting everyone.

**Comment by scifibob** [comment]
I'm playing Sky Factory 3, and I did read the in-game documentation.
It clearly states that shift-right clicking with an empty hand will change mode.

The problem is that nothing happens when I do that on an I/O crystal.

**Comment by scifibob** [comment]
Forget it, I found the culprit.
It was Botania, when wearing a charm it screws up shift-right click.

**Comment by deadlywolf301** [comment]
i dont have botania in my mod pack so thats not whats causing it fore me but glad you fixed another bug

**Comment by deadlywolf301** [comment]
figured it out cant be holding any thing in your off hand either

**Comment by deadlywolf301** [comment]
sorry fore this
