### ISSUE TITLE
Crash with I/O Crystals

### ISSUE THREAD

**Issue by 1matto** [brandon3055/Draconic-Evolution#797]
## Description
Theirs a crash with the i/o crystals involving Iskallium Reactors

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281
* Foolcraft version: 1.3.3

## Crash report
```
CRASH REPORT HERE
```

**Comment by covers1624** [comment]
Provide a crash report. We can do nothing without it. Its like walking in to a computer store and saying your computer is broken, without bringing your computer.

**Comment by 1matto** [comment]
Unfortunately the crash happened on a server that I don't run

**Comment by covers1624** [comment]
Without a crash, this is being closed. If you are able to get a crash report from the server, post it here. Or get the owner to post it here.
