### ISSUE TITLE
Unable to craft Disenchanter

### ISSUE THREAD

**Issue by LadyUndine** [brandon3055/Draconic-Evolution#798]
## Description
The recipe for the Disenchanter requires two Enchanted Books. However, there is no recipe to craft said books. According to the JEI, there's also no way to acquire it through loot drops either.
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3
* TolkienCraft II version: N/A

## Crash report
```
The current recipe in the JEI for Sky Factory 3 uses a Draconic Core, 2 Emeralds, an Enchantment table 2 Enchanted books and 3 bookcases. I tried Googling the recipe and it appears to be different from what is displayed on the FTB wiki and other various pages. 

I tried crafting enchanted books using both the EnderIO Enchanter and the vanilla Enchantment table. Neither enchanted book produced registers with the dienchanter recipe.
```

**Comment by brandon3055** [comment]
Soo... you need an enchanted book... Have you tried enchanting a book?

**Comment by LadyUndine** [comment]
I've tried both modded and vanilla enchanted books - neither works. It specifically requests an enchanted book that has nothing on it - all possible enchanted books have specific descriptions detailing the nature of the enchants. When I click the button that auto-fills the crafting table with recipe components, it does not recognize vanilla enchantment books or the ones created via the EnderIO Enchanter. It keeps telling me 'enchanted book' is missing.

**Comment by brandon3055** [comment]
JEI may not recognize that a book with an actual enchant is valid but it should still work if you place them in the table manually. I have tested this by simply enchanting books in a vanilla enchanting table and then using those books in the recipe. If that does not work for you then some other mod must be somehow modifying vanilla enchanted books... 

Try turning on advanced tool tips (F3 + H) and check what the tool tip says. It should look something like this. http://ss.brandon3055.com/28fkm5w.png

**Comment by LadyUndine** [comment]
I turned advanced tool tips and also tried placing the recipe components manually -  i was able to craft the item. So the JEI indeed doesn't recognize that the other books with enchants are equally valid. The advanced tool tips shortcut was very helpful. Thank you for your help.
