### ISSUE TITLE
Feature Request: Highlight blocks for AoE Mining with DE tools (similar to Builder's Wand from Extra Utils)

### ISSUE THREAD

**Issue by EnigmaticaGH** [brandon3055/Draconic-Evolution#80]
Not only would it help let you know what you're about to mine, it would also let you realize when you accidentally have your tool set to 9x9 . I know there is AoE base safe mode but also sometimes it can suck to destroy cosmetic sections (with no tile entities) so overall this would be a helpful feature.

As in the title, the highlight doesn't have to be very bright. Something like the highlight from Builder's Wand will be enough.

**Comment by brandon3055** [comment]
Thats actually not a bad idea! I will add it to the todo list. (Not sure exactly when i will be able to work on it.)
