### ISSUE TITLE
Getting No Power to my Fusion Crafter Injectors 

### ISSUE THREAD

**Issue by davetc** [brandon3055/Draconic-Evolution#800]
## Description
Hi there i have just started Playing round with fusion craft on Draconic Evolution
am still trying to figure out why my injectors arent accepting any power from a Generator  i am currently using the 222 patched version of 1.10.2 and we have a multiplayer server so any help would be greatly appreciated thank you :)

## Base information 
* Minecraft version: 1.10.2
* Minecraft Forge version:
* TolkienCraft II version:

## Crash report
```
CRASH REPORT HERE
```
![image](https://user-images.githubusercontent.com/29678933/27510391-2ae559fc-5907-11e7-8fbc-6abcc29aab3e.png)

![image](https://user-images.githubusercontent.com/29678933/27510393-39c122da-5907-11e7-86a8-05659618339c.png)

![image](https://user-images.githubusercontent.com/29678933/27510403-7b5998da-5907-11e7-8ea3-17adb690b8ef.png)

**Comment by uberfuzzy** [comment]
Move the injectors 1 more block away from the center box. Some released versions had a 2 block minimum.
Also, injectors will not accept power/show being charged in HUDs, until the craft starts.

**Comment by brandon3055** [comment]
There is an issue with the generators that is fixed in build 232. To get around it in your current version place a conduit of some sort between the generators and the injectors. Or place the generators on the side of the injectors.
