### ISSUE TITLE
Mipmap Flickering

### ISSUE THREAD

**Issue by fscan** [brandon3055/Draconic-Evolution#801]
## Description
This is kind of a strange problem and i'm not really sure if it's DE or JEI at fault here.
I started a new test world with only DE and JEI. Mipmap level is configured as 4. When I open JEI, scroll to the page with the DE items and then close JEI the world starts to flicker. It seems like it's constantly switching between mipmapped an non mipmapped rendering. It's especially noticeable with trees. The only thing that helps after this is a complete shutdown of the client, a relog does not fix it.

DE was the only mod i could reproduce this effect with in combination with JEI.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* DE: 2.1.1.236
* JEI: 3.14.7.420

**Comment by brandon3055** [comment]
This will be fixed in the next releases.
