### ISSUE TITLE
Cannot use draconic bow if wirelessly recharging

### ISSUE THREAD

**Issue by Heather-dev** [brandon3055/Draconic-Evolution#802]
Draconic bow is intermittently unavailable while it is wirelessly recharging via the Ender IO Wireless Charger or the FluxNetworks Flux Controller. The bow will flicker rapidly between the drawing and holding states.

## Base information
* Draconic-Evolution version: 1.10.2-2.0.12.222
* Forge Version: 12.18.3.2281
* FTBPresentsSkyfactory3: 3.0.10

**Comment by brandon3055** [comment]
This is an issue with forge that can not be fixed on my end.

**Comment by Heather-dev** [comment]
Bummer. I like that bow :)
Thanks for the mods
