### ISSUE TITLE
Odd crash after updating to Direwolf 20 1.10.2 pack ver 1.21.1

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#803]
## Description

So, I am setting up my RFTools Builder when the game decided to CTD. Umm. So... Since there is no tesseract and the RFTools version of the tesseract is too weak to feed the RFTools Builder I cheated in a creative capacitor bank to feed the RFTools Builder. And when I did it CTD. When I go to log in again I, again, CTD. I suspect that the Draconic Capacitor that I keep on hand to keep my armor and tools charged is trying to charge the creative energy cell and, as it's creative, causing things to crash. Also, just to be safe, posted this to the Ender IO people - https://github.com/SleepyTrousers/EnderIO/issues/4273  I also confirmed it in a test world. Once I set the Draconic Capacitor to "Charge Held Items " or "Charge Armor & Held Items" and created a Creative Capacitor Bank, boom! CTD. 

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 1.10.2-12.18.3.2316 
* TolkienCraft II version: N/A

## Crash report
```
[Pastebin of Crash Report](https://pastebin.com/pU9m2Btf)

```

**Comment by llloyd4** [comment]
Ok, a response on the Ender IO Github post - 

"HenryLoenwind commented 12 minutes ago
I had a look at the code, the reason for the crash lies in Brandon Core: It uses the return value of getCapability() without checking it for null.  "

So, hopefully this'll get fixed. >.<

**Comment by brandon3055** [comment]
This is fixed in the latest version of BrandonsCore

**Comment by llloyd4** [comment]
Cool! I update it later and post about it on the FTB mod pack site so they can update the pack. :D

**Comment by llloyd4** [comment]
Oh! Let me know when the newest Core is released? The Curse page still lists my version, from June 11th, as the latest. :D
