### ISSUE TITLE
[1.7.10] Villager mob souls

### ISSUE THREAD

**Issue by kaal-1** [brandon3055/Draconic-Evolution#804]
## Description
Ok, so I have a Project Ozone 2 server running on Thermos with some plugins, and I was having problems with fake players. Diamond spikes from Extra Utilities enchanted with reaper 5 were not dropping souls/xp/player only drops. I managed to find out that the problem was the AuthMe plugin blocking the spike fake player named [minecraft]. Then I added in the config exceptions for the various different fake players the mods use. This solved my problem and I started getting exp, player only drops AND souls.
Then I cured a bunch of zombie villagers until I got a villager soul, I set up a spawner for them, and they are NOT dropping souls at all. I've chunkloaded the area and waited overnight. More than 400 normal mob souls (creeper/skeleton/zombie), and NO villager soul. Then I decided to test in my single player cause I thought maybe draconic disabled the villager soul specifically for "non-player" kills (Like Iguana Tinker Tweaks does for the mob heads). Turns out in single player it is dropping the soul with the exact same setup. Maybe it has nothing to do with draconic and I'm opening the issue in the wrong place, but I have no idea where else I could ask for help.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1614

**Comment by brandon3055** [comment]
Sounds like an issue with the server. If your sure that your single player setup is identical to your setup on the server then they should both work exactly the same.
