### ISSUE TITLE
Crystals causing massive FPS drop

### ISSUE THREAD

**Issue by HPGMaphax** [brandon3055/Draconic-Evolution#805]
## Description
My FPS is doing fine normally, ~30-60, but the second I look at the crystals my FPS just drops down to about 5.

I have tried using optifine to disable particle effects, but have not had any luck, also have effects set to minimal.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2254

**Comment by covers1624** [comment]
Can you provide your fml client latest log, I suspect this may have something to do with system specs and shaders. Also, try disabling DE's shaders inside the config.

**Comment by HPGMaphax** [comment]
I am fully aware that it is heavily related to specs, and disabling shaders has helped, there is too much else going on to be sure about the impact DE has in particular, the biggest problems have been fixed.
