### ISSUE TITLE
Rendering item

### ISSUE THREAD

**Issue by L0rdV3ga** [brandon3055/Draconic-Evolution#807]
## Description
Rendering item ( FTB Present Skyfactory 3)
[crash-2017-06-27_11.56.49-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1105191/crash-2017-06-27_11.56.49-client.txt)

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:1.10.2-12.18.3.2316
* TolkienCraft II version:

## Crash report
---- Minecraft Crash Report ----

[crash-2017-06-27_11.56.49-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1105198/crash-2017-06-27_11.56.49-client.txt)

**Comment by brandon3055** [comment]
This probably should be happening but it should be fixed in the next release.

**Comment by L0rdV3ga** [comment]
thanks for the response, i just restore my world good luck
