### ISSUE TITLE
CTL when Wyvern Flux Capacitor charges items on toolbar and try to place a creative capacitor

### ISSUE THREAD

**Issue by TheQuadShot** [brandon3055/Draconic-Evolution#808]
Minecraft 1.10.2
Forge 12.18.3.2281
BrandonsCore-1.10.2-2.1.8.107
Draconic-Evolution-1.10.2-2.1.1.236

CrashLog:
https://pastebin.com/zdLirWbq

ModList:
https://pastebin.com/x7KV5TEB

I have a Wyvern Flux Capacitor set to charge items on toolbar. I pick up a creative vibrant capacitor(EnderIO) and try to put it in hand when the CTL occurs.

**Comment by brandon3055** [comment]
This is a confirmed bug with the enderIO capacitor bank.
