### ISSUE TITLE
Can't summon the chaos guardian. What's the entity name ?

### ISSUE THREAD

**Issue by Wyvern67** [brandon3055/Draconic-Evolution#809]
## Description
Hello. Seems like I can't summon the chaos guardian despite having entered the command at the top of this file
https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/entity/EntityChaosGuardian.java

Perhaps I have the wrong name ? Is it still /summon DraconicEvolution.ChaosGuardian ?

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: No idea :|
* Draconic Evolution version: 2.0.10.199-universal
* Modpack: Skyfactory 3

**Comment by brandon3055** [comment]
Thats just an old comment i forgot to remove.
Try /summon draconicevolution.ChaosGuardian
in 1.11+ it will be
/summon draconicevolution:chaosguardian
