### ISSUE TITLE
Nether Draconium is stated as Ender Draconium

### ISSUE THREAD

**Issue by 1matto** [brandon3055/Draconic-Evolution#811]
Nether Draconium is stated as Ender Draconium in the item description and Ender Draconium is unnamed. 

## Base information
* Minecraft version:1.11.2
* Minecraft Forge version:13.20.0.2315
* TolkienCraft II version:none

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
Will be fixed in the next release.

**Comment by 1matto** [comment]
You should also create a 1.11 label
