### ISSUE TITLE
Draconic Flux Capacitor crashing when holding a Creative Capacitor Bank

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#812]
## Description

So, I updated Draconic Evolution to 1.10.2-2.1.2.245 (uploaded a day ago) and Brandon's Core to 1.10.2-2.1.9.113 (uploaded about the same amount of time ago), created a test world, used JEI to give me a fully charged Draconic Flux Capacitor, set that to "Charge Armor and Held Items" mode (like it would be on my main world), used JEI to give me a Creative Capacitor Bank (like in the previous bug report), and CTD. Did it twice just to be sure. So... 

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 1.10.2-12.18.3.2316
* Draconic Evolution version: 1.10.2-2.1.2.245
* Brandon's Core version : 1.10.2-2.1.9.113

## Crash report
```
[https://pastebin.com/MrZ9ZewM]
```

**Comment by davqvist** [comment]
Can confirm, got reports for that in Age of Engineering modpack.

**Comment by brandon3055** [comment]
#808

**Comment by llloyd4** [comment]
Ok, as over at https://github.com/SleepyTrousers/EnderIO/issues/4273

---
HenryLoenwind commented 4 days ago
I had a look at the code, the reason for the crash lies in Brandon Core: It uses the return value of getCapability() without checking it for null.

Note: The energy capability for the creative CapBank has been disabled because some mods could not cope with its unlimited energy.
---

And marked it as "Bug in Other Software" . So your saying his mod is broke, he's saying your mod is broke and, yeah... O.o

**Comment by brandon3055** [comment]
I pointed out on their issue exactly why this is there fault. Basically the capability system has a way of checking if item x has a capability. That exists so you dont end up trying to use a capability that does not exist which would result in a crash. The ender io cap is reporting that is has the energy capability but when asked to provide that cap its like _Oh... sorry no i lied... Here have a crash instead!_
