### ISSUE TITLE
Draconic upgrades not working on a staff of power?

### ISSUE THREAD

**Issue by WaterXCubic** [brandon3055/Draconic-Evolution#813]
## Description
As shown in the picture 
https://gyazo.com/140e4fb1f3507a53bb512df478cadd05
that is what I have in my injectors while I have a staff of power with all draconic upgrades EXCEPT Dig Speed and Dig AOE, however I can't upgrade it to the draconic level for some reason..

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 1.10.2-12.18.3.2316
* Mod Pack: FTB Beyond 1.9.0

## Crash report
```
~No crash avaliable~
```

**Comment by brandon3055** [comment]
Can you show me your entire setup. Also does it give a message in the gui? or does the recipe just not show up.

**Comment by WaterXCubic** [comment]
Yep, the recipe just doesn't show up, however I made another same setup but it worked fine. The distance between the injector and the core hasn't changed in both the setups.

**Comment by brandon3055** [comment]
Odd... Can you send be a screenshot of both setups including the cores?
