### ISSUE TITLE
Draconic Evolution crashing game when it opens

### ISSUE THREAD

**Issue by DerpyNinja476** [brandon3055/Draconic-Evolution#814]
## Description
whenever i have Draconic Evolution in my small modpack that i put together, it makes my game crash.
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 1.10.2-forge1.10.2-12.18.3.2185
* Mod Pack: not a modpack made by someone, put together by me

## Crash report
this is the mesage that i got when i load up the game
![screenshot_1](https://user-images.githubusercontent.com/29805988/27755860-90fee830-5dc0-11e7-9239-c4a46cacb61e.png)
there is no crash report when i load up the game but ill put the log here 
CRASH REPORT HERE
https://pastebin.com/UG953bNR

Thanks,
DerpyNinja476

**Comment by covers1624** [comment]
Please read the Curseforge page properly, BrandonsCore and DraconicEvolution require CodeChickenLib.

**Comment by DerpyNinja476** [comment]
oh ok thanks

**Comment by DerpyNinja476** [comment]
umm... i tried to add codechickenlib and this mesage came up
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.minecraft.util.JsonUtils.hasField(Lcom/google/gson/JsonObject;Ljava/lang/String;)Z

**Comment by covers1624** [comment]
You have installed the deobf version, install the universal version

**Comment by DerpyNinja476** [comment]
oh...

**Comment by DerpyNinja476** [comment]
one question... how did you know that i did that?

**Comment by DerpyNinja476** [comment]
also i tried to do that and it asks for codechickenlib

**Comment by covers1624** [comment]
JsonUtils.hasField only exists with that name in dev, at runtime for users its JsonUtils.func_something. Full log if you are experiencing issues still.

**Comment by DerpyNinja476** [comment]
sorry but i have no clue what you just said because i dont know java script

**Comment by DerpyNinja476** [comment]
can you put it into simpler terms please

**Comment by covers1624** [comment]
Its hard to explain, Basically methods in a decompiled environment are for example "hasField", but when outside development environments it is "func_something". Thats it really, if you are still experencing an issue, i require the full log in order to help.

**Comment by DerpyNinja476** [comment]
[2017-06-30-7.log.gz](https://github.com/brandon3055/Draconic-Evolution/files/1116699/2017-06-30-7.log.gz)
here is the full log

**Comment by DerpyNinja476** [comment]
i have to go but ill be back tomorrow

**Comment by DerpyNinja476** [comment]
i really need draconic evolution in this modpack that im making

**Comment by covers1624** [comment]
That log shows that the game launched successfully.

**Comment by brandon3055** [comment]
The version of CCL you are using is too old. you need atleast 2.5.9 but you have 2.5.4
And no it does not @covers1624

**Comment by covers1624** [comment]
Right was just correcting myself.

**Comment by brandon3055** [comment]
Would be nice if that was a slightly more noticeable message in the log....

**Comment by DerpyNinja476** [comment]
is ccl brandons core?

**Comment by DerpyNinja476** [comment]
also i just came back to check

**Comment by brandon3055** [comment]
No... No its not.
https://minecraft.curseforge.com/projects/codechicken-lib-1-8/files/2429883

**Comment by DerpyNinja476** [comment]
just realized what it meant

**Comment by DerpyNinja476** [comment]
thanks

**Comment by brandon3055** [comment]
For future reference. Try to avoid posting multiple comments within seconds of each other. If you need to add something then you can edit your previous comment. Generally you should only post a new comment after someone else posts a comment or if its been some time since your last comment.

**Comment by DerpyNinja476** [comment]
thank you so much for you time, efforts, and patience to help me and I'm glad there is a community out there that cares.
