### ISSUE TITLE
draconic evolution energy storage wont output energy

### ISSUE THREAD

**Issue by DerpyNinja476** [brandon3055/Draconic-Evolution#815]
## Description
i have 2 energy pylons and both have a basic energy i/o crystal, but it wont output energy to anything it doesnt even show charge on the one probe mod
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 1.10.2-forge1.10.2-12.18.3.2185
* Mod Pack: not a mobpack, i put it together myself

## Crash report
```
it didnt crash
CRASH REPORT HERE
```

**Comment by DerpyNinja476** [comment]
sorry i meant the draconian energy ball won't output energy

**Comment by brandon3055** [comment]
Do you have the crystals and pylons in the correct io modes? Please post a screenshot of your setup.

**Comment by DerpyNinja476** [comment]
ok so here is my setup for the draconic energy ball
![2017-07-07_21 21 48](https://user-images.githubusercontent.com/29805988/27981525-f808e734-635a-11e7-9419-0ec2c5314b94.png)
![Uploading 2017-07-07_21.21.58.png…]()

**Comment by brandon3055** [comment]
Ahh because with the output pylon placed where it is the glass needs to be placed on top. If the pylon is bellow the center of the core then the glass must be placed on top, If it is above it must be placed on the bottom and if it is on the same y level then it can be placed on ether the top or the bottom.

**Comment by StArCoUnCiL** [comment]
I know this mod pack is kinda older but I need help from someone that can help if possible. I have the right setup and it looks like the original post but the pylons are right and I cant get any energy out from the energy core thing.
![image](https://user-images.githubusercontent.com/115616665/195276860-d98a5123-569e-4721-8276-3209d60d2445.png)
![image](https://user-images.githubusercontent.com/115616665/195276880-2ff25599-bc60-45ab-aea3-67bdc671f939.png)

**Comment by FoxMcloud5655** [comment]
Please don't necro old issues.  If you need help, join the Discord and many people can assist you.
