### ISSUE TITLE
InfoTablet multiplies data in the index

### ISSUE THREAD

**Issue by Techlone** [brandon3055/Draconic-Evolution#816]
## Description
Hi, I have a bug with the InfoTablet. When I open it at first time after a starting the game it works fine and records in the index are not repeated. But they will be repeated as many times as I opened the InfoTablet.
I think the bug is connected with `pageList` [here](https://github.com/brandon3055/Draconic-Evolution/blob/1.7.10/src/main/java/com/brandon3055/draconicevolution/client/gui/componentguis/GUIManual.java#L382). It's static and never be cleaned but records are always added in `pageList` when the method `loadPages` are called.
Also do you support the mod for 1.7.10?

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: idk
* Mod version: 1.0.2h
* Mod Pack: FTBPresentsSkyfactory25

## Crash report
Nope

**Comment by brandon3055** [comment]
I am not currently supporting 1.7.10 If i ever go back and fix some of the 1.7.10 bugs this will be one of them.
