### ISSUE TITLE
World generation completes, but world won't load

### ISSUE THREAD

**Issue by PsychoSwan** [brandon3055/Draconic-Evolution#817]
Not much of a crash per say, but annoying none the less. When I create a new world, the spawn point generation completes, but I cannot access the world. 

[latest.txt](https://github.com/brandon3055/Draconic-Evolution/files/1117621/latest.txt)

The error is near the bottom. The line you're looking for is:
 Caught exception from Minecraft Forge (forge)
Caused by: java.lang.ClassCastException: com.brandon3055.brandonscore.lib.FakeWorld cannot be cast to net.minecraft.world.WorldServer

**Comment by tyler489** [comment]
Is this on a spongeforge server by chance?

**Comment by PsychoSwan** [comment]
No, this is in singleplayer.

**Comment by tyler489** [comment]
Interesting looks a lot like my issue with spongeforge #818

**Comment by brandon3055** [comment]
i suspected something like this would probably happen... (one of the reasons its a beta release) Will be fixed in the next release.

**Comment by CyborgCabbage** [comment]
I think I know what's going on, remove custom npc's if you want draconic evolution to work
