### ISSUE TITLE
Spongeforge lockup with fakeworld

### ISSUE THREAD

**Issue by tyler489** [brandon3055/Draconic-Evolution#818]
## Description
Spongeforge server crashes because of fake world implemtations

I talked to the sponge devs here 
https://github.com/SpongePowered/SpongeForge/issues/1617 and they said they cant add a fix by them self but are willing to work with you. Draconic evolution is by far one of my favorite mods and i hope that you will work with aponge to get compatibility so i can play with my favorite mod on a server.
* Minecraft version: 1.11.2
* Minecraft Forge version: 
* Mod Pack: The New Frontier

## Crash report

Actually server log :)
```
https://pastebin.com/CSAk8uWj
```

**Comment by brandon3055** [comment]
i suspected something like this would probably happen... (one of the reasons its a beta release) Will be fixed in the next release.
