### ISSUE TITLE
Can't charge Draconium Block

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [brandon3055/Draconic-Evolution#819]
## Description
cannot place Drac.Block into any Rf "charger" , like drac.infuser , mekanism ind.matrix etc.
game crash if shift-right.click on infuser, mek.matrix  etc.

btw : awakening ritual isn't working eighter, heart do start spinning , or eating its food (drac.cores)

i know, it's the first port, so i expect things like this
so far: 
- vanilla dragon drops 1 heart, 
- mek.dig.miner find an mine drac.dust (ca. 4 per ore)
- flux.capacitor will charge 

## Base information
* Minecraft version: 1.11.2
* Minecraft Forge version: .2388
* Mod Pack: none, mekanism, rftools, exu2,

## Crash report
```
CRASH REPORT HERE
```

**Comment by covers1624** [comment]
Read the ingame book, things have changed.
