### ISSUE TITLE
Suggestion for Mob Grinder (Quality of Life thing)

### ISSUE THREAD

**Issue by Fatthunder** [brandon3055/Draconic-Evolution#82]
Would it be possible to add a config option for the grinder to set whether it drops xp or not?  Another option would be to add a gui button within the grinder to do this.

Would be great if something like this would be possible as even with the 5 sec xp despawn and vacuum hoppers picking orbs up it still causes some fps drop.

**Comment by brandon3055** [comment]
I already made them despawn faster then normal (30 seconds) But i guess i can add that to my list.
