### ISSUE TITLE
Custom NPC's conflicts

### ISSUE THREAD

**Issue by CyborgCabbage** [brandon3055/Draconic-Evolution#821]
The world doesn't get past 'building terrain' if Custom NPC's and Draconic Evolution are in the same pack.

 Base information
* Minecraft version: 1.11.2
* Minecraft Forge version: 13.20.1.2388

Here is the console log from a world running both mods and their required core mods.
[log.txt](https://github.com/brandon3055/Draconic-Evolution/files/1119473/log.txt)

**Comment by brandon3055** [comment]
This should be fixed in the next release.
