### ISSUE TITLE
Charm of Dislocation Crash

### ISSUE THREAD

**Issue by heyoomimi** [brandon3055/Draconic-Evolution#823]
## Description
Using Charm of Dislocation to The End causes a server crash: https://pastebin.com/hwARaMh0

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: AeonPack 1.10.2 (On Twitch App)

## Crash report
```
https://pastebin.com/hwARaMh0
```

**Comment by brandon3055** [comment]
See #681
