### ISSUE TITLE
1.11.2 Various Items Changing when Broken

### ISSUE THREAD

**Issue by DMIL421** [brandon3055/Draconic-Evolution#824]
## Description
The following items break/change when broken with any tool:
Wyvern Crafting Injectors- Change to Basic
Basic Energy I/O Crystals- Change to Basic Relay Crystals
Wyvern I/O Crystals and Relay Crystals- Change to Basic Relay Crystals

I haven't tested the rest of the items yet, but I'm guessing higher tiers will continue to do the same.
## Base information
* Minecraft version: 1.11.2
* Minecraft Forge version: 2388
* Mod Pack: Dark Aquisitions, Technic Link: http://api.technicpack.net/modpack/dark-acquisitions-111

This issue is not generating a client or server crash. I can supply a F3+C Crash if needed.
Let me know if I can provide any additional information.

**Comment by DMIL421** [comment]
I've also noticed that the Draconic Energy Storage Core does not show a RF in/out value.

**Comment by brandon3055** [comment]
Both issues will be fixed in the next release

**Comment by DMIL421** [comment]
Updated to the current Curseforge version and both issues are fixed! Working properly both on client and server. Thanks a lot!
