### ISSUE TITLE
1.11.2 Energy Core Stabilizers showing up as Particle Generators in JEI and in World

### ISSUE THREAD

**Issue by DMIL421** [brandon3055/Draconic-Evolution#826]
## Description
Running Draconic v248 and BrandonCore 115, the Energy Core Stabilizers are showing up in JEI named Particle Generators.

## Base information
Minecraft version: 1.11.2
Minecraft Forge version: 2388
Mod Pack: Dark Aquisitions, Technic Link: http://api.technicpack.net/modpack/dark-acquisitions-111

## Crash report
This issue is not generating a crash report.

**Comment by brandon3055** [comment]
oops... That will be fixed in the next release.
