### ISSUE TITLE
1.11.2 Energy Core Stabilizers not Emitting Redstone Signal to Comparator

### ISSUE THREAD

**Issue by DMIL421** [brandon3055/Draconic-Evolution#827]
## Description
Running Draconic v248 and BrandonCore 115, the Energy Core Stabilizers not emitting a redstone signal to a comparator.

Reactor in this screenshot is over 65% full.

http://i.imgur.com/undefined.png

## Base information
Minecraft version: 1.11.2
Minecraft Forge version: 2388
Mod Pack: Dark Aquisitions, Technic Link: http://api.technicpack.net/modpack/dark-acquisitions-111

## Crash report
This issue is not generating a crash report.

**Comment by brandon3055** [comment]
Your link is broken but the regardless the stabilizers do not emit an RS signal. The pylons do.
