### ISSUE TITLE
Ender Energy Manipulator

### ISSUE THREAD

**Issue by DinnerBeef** [brandon3055/Draconic-Evolution#828]
## Description
The Ender Energy Manipulator Does Not Work In The Void
Yes I Get That thee need to be enderman but i made a platform and that still did not work
(suggest make it so it work different in the void (if you want if not i will just add a recipe for the egg 
## Base information
* Minecraft version: 1.11.2
* Minecraft Forge version: `3.20.1.2393 
* Mod Pack: (In The Works FTB Pack)

**Comment by brandon3055** [comment]
If you have access to creative you can place a block of bedrock at 0,0 y level 64 if i recall correctly.

**Comment by DinnerBeef** [comment]
testing that now

**Comment by DinnerBeef** [comment]
it worked do you know how many enderman it need btw?

**Comment by brandon3055** [comment]
100 but if there are less than 20 in the immediate area it will automatically spawn more as long as it can find a spot to spawn them. Though you would need at least a 50x50 block platform to get the maximum auto spawn rate because it just tries to spawn them at random locations within a 50x50 area.
