### ISSUE TITLE
Comparator not outputting signal from Energy Pylon in FTB Beyond

### ISSUE THREAD

**Issue by AspectMalygos** [brandon3055/Draconic-Evolution#829]
Title. Checked github and it said the issue was fixed in a previous build, but its still not functioning for me.

Base information
1.10.2
forge-12.18.3.2316
Beyond (version 1.10.0)(with only a few utility mods added: analyzeio, buildersguides)
Draconic Evolution 1.10.2-2.1.2.245 (updated from pack version to see if it would fix the issue)

**Comment by brandon3055** [comment]
Seems to work fine for me...
http://ss.brandon3055.com/ui7chgc.png
Can you show me a screenshot of your setup?

**Comment by AspectMalygos** [comment]
how strange, here's a screenshot of the setup.
![2017-07-09_22 21 28](https://user-images.githubusercontent.com/10220399/27997271-304804ae-64f5-11e7-9f80-a2e1add343dc.png)

I'l try reverting and removing some of the changes too.

**Comment by AspectMalygos** [comment]
just updated brandonscore(2.1.9.113), still doesn't work.
even with a fresh beyond pack (with draconic evolution upgraded to 2.1.2.245 and brandonscore to 2.1.9.113), pack version 1.10.

**Comment by AspectMalygos** [comment]
I've chalked it up to being a mod conflict of some sort.
Since it works fine in a pure draconic evolution mod instance (so brandonscore, code chicken lib 1.8+ and draconic evolution).
I'm afraid I do not know where to go from here, in identifying the conflict.

**Comment by brandon3055** [comment]
Ok so what tier is the core and how much charge does it have? I can see you have over 2 billion but if thats a tier 7 then 2 billion would be 0.1% charged which would not produce an rs output

**Comment by AspectMalygos** [comment]
Goddamnit, Sorry brandon, I was looking at the value the Pylon was giving in TheOneProbe and assuming the unit was off, but it really was full. 
You are absolutely right. it was 0.1 percent full. And TOP is giving me the wrong information.

I'm awfully sorry for wasting your time.
