### ISSUE TITLE
[1.10.2]Can't get achievment

### ISSUE THREAD

**Issue by Boyownik** [brandon3055/Draconic-Evolution#830]
## Description
I can't get achievment "Expense vs. Power" that tells me to craft awakened core, propably because it must be crafted in normal crafting grid.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: FTB Beyond

**Comment by brandon3055** [comment]
Ahh yea... That would be a thing... Will see about fixing that before the next release.
