### ISSUE TITLE
[Request/Suggestion] Make the "Last Stand" effect configurable.

### ISSUE THREAD

**Issue by TheUnderTaker11** [brandon3055/Draconic-Evolution#831]
## Description
More specifically, I would like it so that in the config you can disable it all together, or change the amount of RF it needs to save your life. I love the OPness of the mod, but making it so easy to be literally immortal is a bit insane.
All you need is a block that can pull items in/out of your inventory to always keep 2 capacitors on you and boom, no longer can ever die (Assuming you produce enough RF/t).

Right now the only option is to ban draconic armor all together, which I think is a bit extreme.

**Comment by Saklad5** [comment]
I have to agree on this. Endgame content is about becoming insanely powerful through infrastructure, but Last Stand doesn’t even take that much power. It should at least be as power-hungry as a Draconic Bow with Shock Wave.

**Comment by gigabit101** [comment]
There is a config to change the amount of power required to do this, setting it to crazy high number so it will not activate
