### ISSUE TITLE
One Hit by Chaos Guardian

### ISSUE THREAD

**Issue by Kaboose62** [brandon3055/Draconic-Evolution#832]
## Description
I arrived at the chaos island only to be onehit shortly after arriving. I was wearing full charged full draconic armour with a fully charged draconic flux capacitor. Armour was not enchanted.

My character is an android from Matter Overdrive if that has an effect on DE at all.

Mod Version 1.7.10-1.0.2h
## Base information
* Minecraft version:1.7.10
* Mod Pack: Trollcraft from ATLauncher

**Comment by brandon3055** [comment]
The chaos guardian is just that powerful. Try to avoid its attacks. Speed is the key.
