### ISSUE TITLE
Possible error in code with lolnet badge enabling and display

### ISSUE THREAD

**Issue by dupontct** [brandon3055/Draconic-Evolution#835]
In reading the code for draconic-evolution I came across some code that I think is in error.  The result of which impacts the display of lolnet badges.

in src/main/java/com/brandon3055/draconicevolution/client/gui/toolconfig/GuiToolConfig.java line 89 you have 

```java
 contributor.patreonBadgeEnabled = !contributor.patreonBadgeEnabled;
```

From reading the code I think this line should be:

```java
 contributor.lolnetBadgeEnabled = !contributor.lolnetBadgeEnabled;
```

Then in src/main/java/com/brandon3055/draconicevolution/client/render/entity/LayerContributorPerkRenderer.java line 59 you have 

```java
 if (contributor.isLolnetContributor && contributor.patreonBadgeEnabled) {
```

From reading the code I think this line should be:

```java
 if (contributor.isLolnetContributor && contributor.lolnetBadgeEnabled) {
```

I think that the existing code means that if you are a patreon contributor and a lolnet contributor you cannot select to display just the lolnet badge or just the patreon badge.

**Comment by brandon3055** [comment]
Ahh yes thankyou for pointing that out. Will be fixed in the next release.
