### ISSUE TITLE
Grinder/ Stabilized Mob Spawner Chunk Loading: Bug

### ISSUE THREAD

**Issue by Fatthunder** [brandon3055/Draconic-Evolution#84]
I'm currently using forge-10.13.3.1395 with Draconic Evolution 1.7.10-v1.0.1

I believe that there is a problem with the grinder not working right when being chunk loaded and a player is not near by.

I currently have a set up where I have stabilized mob spawners and grinders far out from my base so they are out of my way.  However everytime I go to check on them it seems like the grind is not working until it is loaded by a player. (http://imgur.com/kxUid5R,KMbwqSK#0) - Link to picture while I'm there. And picture of when I go away and only have it chunk loaded for a few minutes.

As you can see in the second picture there has been a massive build up of mobs that seems to all be killed as soon as I load up the area.

I have checked to make sure it wasn't the chunk loader as I tested it with both Railcrafts and ChickenChunks.  Both have the same problem.

The grinder is being powered by a tesseract which is pulling from an energy orb which has 200B RF so its not running out of power.

Bout all I can say about this bug.

**Comment by brandon3055** [comment]
I havent been able to reproduce this error. It seems to be working fine when chunk loaded. To test i recommend sending the drops to an enderchest so you can go out of loaded range and still see if it is getting drops. Im guessing you have it set to not require a player? (nether star upgraid)

**Comment by Fatthunder** [comment]
So I've updated to the most recent version of v1.0.1a using forge 10.13.3.1401.

While I'm still getting the bug ( http://imgur.com/snT3ihN,FOf6wF7#0 ) I've noticed that the fps drop upon loading to the zone is less, but the mobs are still piling up.

The second image is of my setup.  It is a tesseract right next to the grind pumping energy directly in.  Then there is a transfer node with world interaction upgrade (16 of them so it has a 16 block radius, also has a stack upgrade and 64 speed upgrades to prevent item pile up) picking up item drops and putting them into the the ender-chest to be sent into an AE system.  

The floor is made out of Extra Utilities Conveyor belts.  They are put in a direction so that all items and mobs are pushed to the block right in front of the grinder.

The spawner is fully upgrade with the three cores, apple, and nether star.

It doesnt seem to matter which soul is being used since all the ones ive tested have this problem

Thats all the other information I have really without giving you the whole mod list.

**Comment by Fatthunder** [comment]
I have some things to update you on.  I'm using Draconic Evolution v1.0.1b with forge 10.13.3.1401

I have determined that the problem lies with the Stabilized Spawner.  It seems to continue acting as if it is running when chunk loaded but is not spawning the mobs until the area is loaded by a player.  So all the mobs over the period of time the chunks were not loaded by a player spawn at once.

I would also like to mention that this set up is in Aroma1997s Dimensional World using verions 1.1.0.1.

Also during your tests were your spawners up in the air or near level with the ground.  Mine are 9 blocks above the ground.

**Comment by brandon3055** [comment]
Hmm... I wonder if maby the entity AI isnt working in that dimension when chunks are force loaded... (meaning the entities would just sit there in the air when they spawn) Perhaps try moving the spawner or the grinder so when they spawn they are immediately in range without having to fall.

**Comment by Fatthunder** [comment]
Update again.

Just tested moving it down.  Seems to have fixed it for the most part.  Just that some of the mobs spawn outside the 7x7 grinder range (I'll find someway around this)  So it seems its a problem with the AI not working right.

**Comment by brandon3055** [comment]
Well then that is a problem with the chunk loading not the grinder or spawner. As far as i know mobs should be able to move in force loaded chunks. But i have never tested that.
