### ISSUE TITLE
Crash 1.10.2

### ISSUE THREAD

**Issue by Dilise** [brandon3055/Draconic-Evolution#841]
## Description
ExceptionInInitializerError
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: Age of Engeneering 1.0.3 (Twitch Launcher)

## Crash report
```
Crash when rendering some objects. 
[https://pastebin.com/CdwAQ6Uw](url)

```

**Comment by covers1624** [comment]
`Error linking program: Fragment shader(s) failed to link,  vertex shader(s) linked. Fragment Shader not supported.`
Disable DE's shaders in its config. It appears your PC doesn't support them properly.

**Comment by Dilise** [comment]
`
"client settings" {
    # Disabled the 3D tool and armor models. This is required if you want to use a 2D resource pack.)
    B:disable3DModels=false

    # If true the range of the celestial manipulator sound effect will be significantly reduced.
    B:disableLoudCelestialManipulator=false

    # This is where the settings for the in game hud are stores. You should not need to adjust these unless something breaks.
    I:hudSettings <
        996
        825
        69
        907
        90
        100
        3
        0
        1
        1
        1
        1
     >

    # Invert Dislocator Pedestal display name shift behavior.
    B:invertDPDSB=false

    # This allowes you to just disable the energy crystal shader which can be a lot lagier than the reactor since there are usually a lot more of them (The fallback crystal texture is not soooo bad...)
    B:useCrystalShaders=false

    # Set this to false if you prefer the original look of the reactor beams
    B:useReactorBeamShaders=false

    # Set this to false if your system can not handle the awesomeness that is shaders! (Warning will make cool things look like crap)
    B:useShaders=false
}
`
https://pastebin.com/GdVEGrsF

**Comment by brandon3055** [comment]
This seems to be a bit of an edge case issue. Open GL is reporting that your system supports shaders so the shaders are being initialized but as covers said your system does not actually support them properly which results in an initialization crash. I will have a fix for this in the next release.

**Comment by Dilise** [comment]
Don't forget fix it for minecraft 1.10.2, please!

PS: Sorry for my english. I'm not english speaking.

**Comment by Dilise** [comment]
Thanks for version 2.1.3.256. The problem is gone.

PS: Sorry for my english. I'm not english speaking.

**Comment by Piekid34** [comment]
Hey man. any help you can give with 1.10.2? I was playing Sky Factory 3 And moving my stuff around when I broke one of my draconic crystals to move them. the game crashed every time from that point on? any help? Thanks!

**Comment by Tahakk** [comment]
If you have issues on your own open a new one with the link to similar ones, don't resurrect skeletons.

**Comment by FoxMcloud5655** [comment]
Was just about to say that.  Let's leave old issues alone, please.  If you need help, you can always join the DE Discord and ask in there.
