### ISSUE TITLE
Fakeplayers can get Achievements

### ISSUE THREAD

**Issue by tyler489** [brandon3055/Draconic-Evolution#842]
## Base information
* Minecraft version:
* Minecraft Forge version:
* Mod Pack: The New Frontier

https://gyazo.com/c16cc8d6c4cfcb6a434ecfe6e7e7a422

**Comment by brandon3055** [comment]
Hmm... Yea not intended but not really an issue.

**Comment by Morpheus1101** [comment]
Its an UnIntended new Feature ;)
