### ISSUE TITLE
Fusion Crafting Broken 

### ISSUE THREAD

**Issue by Diamondblockmc** [brandon3055/Draconic-Evolution#844]
When I activate fusion crafting, it immediately cancels and does no longer show me the recipe in the GUI.

Mc Version: 1.10.2
Mod Version: 2.1.0.232
Modpack: Direwolf 1.10 v. 1.12.1

**Comment by brandon3055** [comment]
This is fixed in the latest version. A work around is to move the injectors 1 block further away.
