### ISSUE TITLE
[request] few missing things in 1.10.2

### ISSUE THREAD

**Issue by Bass2style** [brandon3055/Draconic-Evolution#845]
## Description
i miss some awesome features from MC 1.7.10 version, but IDK if it's planned to future releases, and if already requested, and possibly not present due to technical limitations :
- that xray thing : that whas pretty cool in 1.7, but isn't present in 1.10.x+ releases.
- blacklist for pickaxes : whas really usefull for me during "hardcore farming" periods.
- enchant book slots : seems obvious, also usefull, to swith from fortune to silk touch for example
- and possibly some other things (but actually nothing more to add.)

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: FTB Beyond (version 1.10.0)

## Crash report
doesn't apply. :D

**Comment by Tahakk** [comment]
Not sure if 1.10 is developed anymore. Most of the mods are working on 1.12 so you will be lucky if it will be added there.

**Comment by Bass2style** [comment]
yeah, i know, i'm actually passed to FTB Unstable 1.12 for more followed mods, but some of them are missing. :p

**Comment by brandon3055** [comment]
The book slots though convenient were actually only added as a work around for the fact that it was not possible to enchant custom tools in 1.7.10. They do not exist in 1.10+ because they are not needed for that reason anymore. Though i may look into a way to toggle active enchants or something.

I dont plan on re adding the distortion flame because i always felt it was a bit hacky/cheaty
 
I have also been meaning to implement a replacement for the tool blacklist but just have not got around to it yet.

**Comment by Bass2style** [comment]
that should be cool to have a "enchantment switch", but idk if it's possible to realy make it for some enchantments like fortune+looting to switch to silk touch for example, because Minecraft block that abilities. but i'm not MC developper or something, just an user. :D (but, in 1.7.10, silk touch + fortune whas possible, but, silk touch whas the main enchant then.)

yeah, a bit true. but it whas funny, but on multiplayer-servers, i think that could be a game-breaker item, but, it whas funny. :D 

Everything in its time, should probably come later then. :p

**Comment by brandon3055** [comment]
![](http://ss.brandon3055.com/6d1th1u.png) 
This will probably only be in 1.12+

**Comment by Bass2style** [comment]
well, i play actually on RagnaMod IV, a 1.12 modpack, and i am verry happy to see that that feature is present, i've seen that yesterday. :D very cool.

is it normal that the Sharpness Enchant should not applied anymore on the staff of power ? intended or a bug ? :p
