### ISSUE TITLE
[REQUEST] ComputerCraft or other "Script-based Management" intergration

### ISSUE THREAD

**Issue by RyuuOujiXS** [brandon3055/Draconic-Evolution#846]
## Description
In previous versions, we were able to use ComputerCraft to pull data from the Draconic Reactor, process it, and instruct said Reactor accordingly. Looking through the source code of the 1.10.2 branch now and I don't see the same references or other related API. Has it just been implemented in a different way? If not, will it be implemented in the future on this branch?

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: Version that's bundled with current stable version of Mod Pack
* Mod Pack: FTB Beyond

**Comment by RyuuOujiXS** [comment]
Sorry, continued search through code and found the aforementioned references at Draconic-Evolution/src/main/java/com/brandon3055/draconicevolution/blocks/reactor/tileentity/TileReactorComponent.java . Have there been any significant changes to the calculations or algorithms since the update from 1.7.10? Just want to be sure that importing a script from a year ago doesn't wipe my work off the map...along with the map itself.

**Comment by brandon3055** [comment]
http://ss.brandon3055.com/517vtke.txt

**Comment by brandon3055** [comment]
Ahh rite... Currently DE 1.10+ only supports Open Computers. Now that there are CC ports i need to re add CC support just have not had the time yet.

**Comment by kain184** [comment]
its just strange that i can read the rf states using plethora such as how much power a gate is storing or the crystals are but not that one. so would be most appreciated if we can get that in. i have a reactor control program that is having to be managed by redstone levels. and it makes micro control very hard. if gates could be toggled for value by the computer as well as the reactor read from it. that would be cool.

**Comment by brandon3055** [comment]
CC support will be in the next release.
Note: I am using the official CC api which probably wont work with computercraft clones like computality. I will not be adding support for CC clones unless CC itself dies with no hope for revival (Which will probably never happen)
