### ISSUE TITLE
Wyvern Fusion crafting for armor not working

### ISSUE THREAD

**Issue by TheDutchMC04** [brandon3055/Draconic-Evolution#847]
## Description
Upgrading the Shield Capacity from Basic to Wyvern in the Wyvern fusion injectors doesn't work. I have Draconic Armor with these upgrades:
- RF Capacity: -
- Shield Capacity: Basic
- Shield Recovery: Basic

In my injectors I have:
- Emerald
- Emerald
- Nether Star
- Nether Star
- Draconic Core
- Draconic Core
- Wyvern Core
- Upgrade Key (Shield Capacity)

The items have no NBT tags
They do have an EMC value (ProjectE) (I added custom EMC Values)

The armor is fully charged

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: forge-12.18.3.2316
* Mod Pack: Galaxy Tales (Curse)

**Comment by brandon3055** [comment]
What exactly is it doing? Is there an error in the gui? Or does it just not show the recipe at all?
Can you post a screenshot of your fusion setup?

**Comment by TheDutchMC04** [comment]
I can' provide a screenshot right now. My setup is simple: air            - wyvern 2 - wyvern 2  - wyvern 2
              wyvern 2 - air            - air                   - air 
              wyvern 2 - air            - crafting core - air
              wyvern 2 - air            - air                   - air

Wyvern 2 = 2 wyvern injectors stacked on each other

If I put one of my Draconic Armor pieces in there, it will go in but not a recipe or a start button. I have all the items for the Wyvern tier correct.

**Comment by brandon3055** [comment]
Based on that description it sounds like you have something like this http://ss.brandon3055.com/u6ruien.png ?
If thats the case then you dont have enough injectors. I suspect you are placing both emeralds and both stars in a single injector. But each ingredient must be in its own injector.
e.g. http://ss.brandon3055.com/6dcrzo6.png

**Comment by TheDutchMC04** [comment]
I have enough injectors for every item (I probably counted wrong). The dual items (Emeralds & Nether Stars) are in a seperate injector. Can it be an issue with other mods?

**Comment by TheDutchMC04** [comment]
Can it be an issue with Spawn Protection? I build the injector setup within 10 blocks of the spawn. As I'm OP on the server I can build there, could that be an issue?

**Comment by brandon3055** [comment]
It may really help if you could post screenshot of your setup. If you have it setup something like this it should work. http://ss.brandon3055.com/reji8tm.png

**Comment by brandon3055** [comment]
If dont have a way to upload a screenshot then just use http://imgur.com/upload

**Comment by TheDutchMC04** [comment]
I am currently on vacation. But the fusion setup in the link is close mine. I have the top layer on another side (say this one is north, i have the top 2 on west). I will be home in c.a 2 weeks.

**Comment by brandon3055** [comment]
Ahh ok. Well i cant find anything wrong with it from my end so will just set this issue aside for a couple weeks... Or until others start having the same issue.

**Comment by TheDutchMC04** [comment]
I think I found the problem, if I have the setup in the spawn chunks and claimed with  FTBUtils, it does not work. If it is not in the spawn chunks but it is claimed, it does work.

**Comment by brandon3055** [comment]
Figures... FTBUtils is a train wreck.
