### ISSUE TITLE
Can't configure crystals with off-hand not empty. [MC 1.10.2, FTB Direwolf20 1.12.1]

### ISSUE THREAD

**Issue by Vahtera** [brandon3055/Draconic-Evolution#849]
## Description

Can't shift-rightclick crystals to configure balanced/in/out modes if shield is equipped.
While it says "shift-rightclick with an empty hand", you really need to remove shield also.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: FTB Direwolf20

**Comment by brandon3055** [comment]
Long story short the main hand/off hand system is written in a very dumb way which causes issues like this. There is no good way to fix this without a bit of hacking.

**Comment by Vahtera** [comment]
I agree with you 100%. I'd advice writing that in the description though. As in instead of "right click with an empty hand", add a "make sure both hands are free" bit somewhere.
