### ISSUE TITLE
Mob Grinder won't kill Carminite Ghastlings

### ISSUE THREAD

**Issue by Yadokingu** [brandon3055/Draconic-Evolution#85]
Carminite Ghastlings from the twilight forest float in front of the grinder without taking any damage.

ftb infinity 1.4.1, draconic evolution 1.0.1 (manually updated), single player

**Comment by brandon3055** [comment]
Seems to kill them just fine for me. Im using snapshot 9 but i dont think i changed anything since then.

**Comment by Yadokingu** [comment]
It also won't kill Whisps. Do mobs have to be on the ground for the grinder to kill them? Is that intended? Seems like a pretty serious limitation.

**Comment by brandon3055** [comment]
Well im not sure what the problem is. It also kills wisps just fine for me. It only checks for entities every few seconds so you need to make sure they dont fly away before it activates. And they dont need to be on the ground just in the 9x9x9 area in front of it. http://puu.sh/hFnjW/d26a414060.jpg
