### ISSUE TITLE
Help with Chaos Crystal

### ISSUE THREAD

**Issue by Rimmer6617** [brandon3055/Draconic-Evolution#852]
I have killed the chaos dragon and made my way to the crystal. When I dig down I get near to the crystal but cant move out of the block i am in. I can mine the blocks around me but cant move. I got round this by teleporting to near the crystal. When I break it I do not get any shards but get a chaos crystal with no texture (pink and black). I can pick this up and in wailia it says it is a chaos crystal 'contents saved'. If I place this crystal down it immediately kills me. A message appears saying player killed by a unrelentable force or something similar. Any ideas?

ps I have done this 3 times at different locations same outcome.

#
* Minecraft version: 1.11.2
* Minecraft Forge version:13.20.1.2414
* Mod Pack: All the mods 2 and a few extras

Thanks

**Comment by brandon3055** [comment]
Hmm.... Yea is an issue.... Will be fixed in the next release. (Which will be within the next few hours)

**Comment by Rimmer6617** [comment]
Thanks it's fixed other than the crystal I already had still kills me!

**Comment by brandon3055** [comment]
yea i would say just delete that and spawn in 5 shards. Its designed to be impossible to move because if people were able to move in it could cause all sorts of very serious issues especially on servers. And as you discovered there is a nasty surprise built in for anyone who somehow manages to get their hands on the item.

**Comment by xenxero1** [comment]
Consider adding some way to (safely) destroy the item, should a player obtain it? Currently it'd make inventory pets and the Actually Additions easter-egg extremely deadly. Or any system that generates random items.
