### ISSUE TITLE
[1.10.2, 1.11.2] ModCompat: Torchmaster

### ISSUE THREAD

**Issue by Xalcon** [brandon3055/Draconic-Evolution#853]
Hi!
I'm the developer of torchmaster. I've got a [bug report](https://github.com/Xalcon/TorchMaster) regarding my mega torch and the DE StabilizedSpawner: My torch blocks the spawn attempts from your StabilizedSpawner, which is not intended. Sadly, there is no way for me to detect if the spawn attempt is done via the WorldSpawner or some artificial mobspawner like your StabilizedSpawner, and I hope we can find a way to work around this issue. For vanilla, I simply patch all mobspawner tile entities to spawn entities with an additional Tag `IsSpawnerMob` in their Tag list. (Not needed in 1.12 thanks to https://github.com/MinecraftForge/MinecraftForge/pull/4075)

I could do something similar with the stabilized spawner but i rather work out something with you so we dont work against each other or cause more issues in the future :)

The easiest way to resolve this would be adding an `IsSpawnerMob` NBTString to the Entities Tag list. This is a single line of code that can be added to the spawning code, something like this would be sufficient: `entity.addTag("IsSpawnerMob");`

I'm considering doing this myself by overriding your `MobSoul` class (replacing the instance in the DEFeatures class) and adding the tag in the `createEntity()` method. But since this is a change that could possibly lead to issues in the future, i'd like to get your consent on this. (It also helps for future issues to know who is messing with your classes :P)

This change will only need to be done to the 1.10.2 and 1.11.2 versions. 1.12 can handle it properly via CheckSpawn#isSpawner() :)

**Comment by brandon3055** [comment]
Too easy! This change will be in the next update.
