### ISSUE TITLE
Advancements Support?

### ISSUE THREAD

**Issue by 1matto** [brandon3055/Draconic-Evolution#854]
Are there any plans for advancement (old achievement system)  in De 1.12?

## Base information
* Minecraft version: 1.12
* Minecraft Forge version :any
* Mod Pack: any

## Crash report: none
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
The advancement system is a complete re write of the old achievement system meaning it will require a complete re write on my end to implement. I will probably get around to it eventually but its not a high priority atm.
