### ISSUE TITLE
Payload error Draconic Chest

### ISSUE THREAD

**Issue by PretoAlbino** [brandon3055/Draconic-Evolution#856]
I'm being kicked when I enter my server: 
![image](https://user-images.githubusercontent.com/20505933/28755760-5507ddac-7538-11e7-9602-48f039a1a881.png)

I think it's the Draconic Chest NBT Data, how I can fix this?
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 2281
* Mod Pack: [here](https://www.technicpack.net/modpack/horizonmc-sky.1057974)

**Comment by brandon3055** [comment]
#850 
you need to delete or edit the or edit the contents of the item using an NBT editor such as 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

As i am assuming you had this in your inventory the item will be stored in your player data. 

btw are you playing singleplayer or on a dedicated server?

**Comment by PretoAlbino** [comment]
Dedicated server ( Sponge )

**Comment by brandon3055** [comment]
Hmm... This probably shouldn't happen on dedicated () servers but Sponge spounge

**Comment by PretoAlbino** [comment]
I updated the sponge to the latest version and it still continues with the same error :/

**Comment by rivoalrivoal** [comment]
Same error for me. On a standard forge server with FTB Beyond pack
