### ISSUE TITLE
Damage Enchantments from Thaumic Tinkerer 2 dont show effect / Forbidden Magic

### ISSUE THREAD

**Issue by tobi971** [brandon3055/Draconic-Evolution#858]
Damage enchantments from Thaumic tinkerer 2 such as final and focused strike, show no effect on the draconic shield, they show affect on mobs though.
The enchantment wrath from forbidden magic doesnt increase dmg of draconic weapons.

Minecraft : 1.7.10
Modpack : Ftb infinity evolved 2.6.0

**Comment by brandon3055** [comment]
This is probably just due to the way the armor blocks damage.
