### ISSUE TITLE
void xp butten

### ISSUE THREAD

**Issue by Goten87** [brandon3055/Draconic-Evolution#86]
hello brandon3055 i have the Draconic staff right now
i have it on 7x7 and i'm furtuning all my certuse quarts
the only stumble now is that i need to stop sometimes becose the XP becomes to mutch
so is there a way where you can add the XP right to the player without a drop
or make a butten for void XP

**Comment by brandon3055** [comment]
Done. XP will now be added directly to the players xp level.
