### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by archmage94** [brandon3055/Draconic-Evolution#868]
## Base information
* Minecraft version: 1.12
* Minecraft Forge version:11.14.4.1577
* Mod Pack:Custom

## Crash report
```It crashes on Startup and i've got "UCE" on the crash log for all 4 mods (Brandons Core, Redstone Flux which Brandon's Core requires for some reason, CodeChickenlib and Draconic Evolution) and I don't know why
CRASH REPORT HERE
```
[crash-2017-08-06_21.42.08-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1204124/crash-2017-08-06_21.42.08-client.txt)

**Comment by covers1624** [comment]
Read the crash report, Solar-Flux-Reborn is being dumb and repacking the old CoFH api. Go yell at them.

**Comment by archmage94** [comment]
Ok, wait what the heck? I swear I typed out a description. Where'd it go?
