### ISSUE TITLE
Ok this is odd

### ISSUE THREAD

**Issue by archmage94** [brandon3055/Draconic-Evolution#869]
## Base information
* Minecraft version:1.12
* Minecraft Forge version:
* Mod Pack:

## Crash report
```
CRASH REPORT HERE
```

**Comment by covers1624** [comment]
Brandons core nor DE require solar flux reborn. That just isn't a thing.

**Comment by archmage94** [comment]
Oh, nevermind, I did something wrong, I got it working, sorry to bother you guys
