### ISSUE TITLE
Multiple hearts from explosions

### ISSUE THREAD

**Issue by BoneCrusherR** [brandon3055/Draconic-Evolution#87]
I was doing my ritual as normaly. When i noticed that i kept getting my hearts back from the awakened draconium ritual. Then i noticed that if you used 2 tnt instead of one you get an extra heart. So i tested it with 4 tnt and with 16 tnt. I managed to get 4 and 14 hearts from 1 heart. This bug makes it able to multiply the hearts without defeating the ender dragon. I think it might be interesting to fix. 
Here are some videos.

https://www.youtube.com/watch?v=nz6ZilPFG4w&feature=youtu.be
https://www.youtube.com/watch?v=rv49th0awbk&feature=youtu.be

**Comment by brandon3055** [comment]
What version are you using? I made a change in RC 5 that hopefully fixes that.

**Comment by BoneCrusherR** [comment]
2 days ago we updated all our mods. We have also updated Draconic Evolution.
We now run the newest version. In this version i did this tests. 
We now run: Draconic-Evolution-1.7.10-v1.0.1
I dont know if the RC 5 is newer then this, my friend said RC 5 was older

**Comment by brandon3055** [comment]
Are you saying it dose it in Draconic-Evolution-1.7.10-v1.0.1? (That is the latest version)

**Comment by BoneCrusherR** [comment]
Yes we did it in Draconic-Evolution-1.7.10-v1.0.1

**Comment by brandon3055** [comment]
Ok i FINALLY found the problem. Because all 4 tnt detonate at the exact same time the damage is processed 4 times before the item entity is deleted.
