### ISSUE TITLE
BrandonsCore-1.10.2-2.1.10.122-universal error at startup

### ISSUE THREAD

**Issue by ktole1999** [brandon3055/Draconic-Evolution#870]
hoping to get some help on this. thanks in advance.

## Description
when core file is added i get this error. still gives error even with 2.1.11.127

This only happens in server environemnt. forge server with core file only, no other mods installed.

## Base information
* Minecraft version: 1.10
* Minecraft Forge version: 12.18.3.2281
* Mod Pack: none

## Crash report
```
https://gist.github.com/ktole1999/41b0c92eea4764355ea82c69415febc6

```

**Comment by covers1624** [comment]
Install ccl, it's listed as a dep on curse for a reason.
