### ISSUE TITLE
Bow Usability Issue

### ISSUE THREAD

**Issue by selonianth** [brandon3055/Draconic-Evolution#871]
## Description
When using the Arrows of Draconic Fire the bow disappears from the screen after firing for a few seconds, and will only properly fire again if you wait for it to return before attempting to draw it again. Testing seems to show that it is tied to the bow recharging as I'm trying to fire, using Flux Networks wireless recharging as the bow disappears, and is unfirable, for the duration of the recharge following the previous shot. Worth noting however, that the effect disappears while auto-fire is on, the bow will fire as fast as it can at full strength.

## Base information
* Minecraft version: 1.10.12
* Minecraft Forge version: 12.1.3.2316
* Mod Pack: Skyfactory 3

**Comment by brandon3055** [comment]
This is related to an issue with vanilla resetting use ticks when an items nbt changes. There isnt really anything i can do about it. One thing i can suggest is you could also carry a DE flux capacitor which will recharge the bow almost instantly with basically no noticeable delay before you can fire again.
