### ISSUE TITLE
Energy Crystal on Fluxduct not transferring energy

### ISSUE THREAD

**Issue by Unicoranium** [brandon3055/Draconic-Evolution#872]
## Description
I have a large line of netherstar generators from XU2 that are connected with cryo-stabilized fluxducts from Thermal Dynamics. I then place Wyvern Energy I/O Crystals on the end of the fluxducts to send it to my storage capacitor but the energy doesn't go into the crystal unless I put something like an Ender IO capacitor bank in between but that limits the rf/t.

Am I doing something wrong, is this a bug or is this intended?

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: forge-12.19.3.2422
* Mod Pack: My own custom modpack

Draconic-Evolution-1.10.2-2.1.2.245-universal

I'm happy to add more information if there is anything else you need.

**Comment by brandon3055** [comment]
Can you check if this still happens with the latest DE and BC 1.10 versions?
