### ISSUE TITLE
Quantum Quarry + Place Item in World = Funny

### ISSUE THREAD

**Issue by SugarDaddii** [brandon3055/Draconic-Evolution#873]
For easy acess i placed Biome Markers on the Quarry (Extra Uti 2) each side!

If you place a Item on the Quarry it thought its and item container like a chest and will place all quarried items next to it! Dont Know if its a Bug or Funny!

## Base information
* Minecraft version:1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: FTB Beyond

![bug glitch](https://user-images.githubusercontent.com/14795020/29256540-76cbae22-80ab-11e7-8acb-2f5638972660.jpg)

**Comment by ktole1999** [comment]
how is this related to Draconic Evolution?

**Comment by covers1624** [comment]
Brandon confirmed this as an issue.

**Comment by GreatOrator** [comment]
oh, the items being placed on the surface?

**Comment by covers1624** [comment]
He had a placed item down and it's a normal tile entity inventory, so things are being inserted.

**Comment by brandon3055** [comment]
This isnt exactly intended... But.... idk maby i will leave it as a feature!
