### ISSUE TITLE
[1.10.2] Redstone signal breaks DE spawners with Torchmaster

### ISSUE THREAD

**Issue by beanzen** [brandon3055/Draconic-Evolution#874]
## Description
This is a followup to the patch made fixing compatibility with Torchmaster (see https://github.com/brandon3055/Draconic-Evolution/issues/853 for that)

Now, when placing a DE spawner in MC 1.10.2 within the range of a torchmaster torch, if you supply a redstone signal to the spawner via redstone torch, or an enderio redstone conduit, particularly on the bottom, the spawner just dies and will never turn back on. I don't know if the soul dies because there is also a visual glitch where I can't see anything inside the spawner ever, but the only way to get the spawner going again is to place another soul, making it impossible to toggle via switch. 

UPDATE: After more testing, it appears placing a redstone torch or conduit on the spawner even OUTSIDE the range of a mega torch causes the spawner to permanently deactivate, so the issue is not confined to just within the range of the torchmaster item

UPDATE UPDATE: After even MORE testing, it appears what kills the spawner are things that attach to the spawner. A redstone torch or cable placed on the side of the spawner kills it... but placing the redstone torch on the block adjacent to the spawner on the sides (or below) does not kill the spawner. This appears to be unrelated to whether or not the spawner is located within the range of a torchmaster torch or not.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2422
* Mod Pack: 1.10.2-2.1.3.256

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
Im so confused.... I setup a 1.10 instance with forge 2422 and the following mods 
![http://ss.brandon3055.com/p27847s.png](http://ss.brandon3055.com/p27847s.png)
And...
![http://ss.brandon3055.com/qq4zodi.png](http://ss.brandon3055.com/qq4zodi.png)
![http://ss.brandon3055.com/8cenfc3.png](http://ss.brandon3055.com/8cenfc3.png)
It works flawlessly.. It even renders the entity in the spawner...
