### ISSUE TITLE
Reactor gui crash

### ISSUE THREAD

**Issue by Aksille** [brandon3055/Draconic-Evolution#875]
Client crash on opening reactor gui

## Base information
* Minecraft version: 1.11.2
* Minecraft Forge version: 13.20.1.2393 or 13.20.1.2454 (both crashing)
* Mod Pack: created my own
It crashing for 1 month Always on new versions, but it is already long enough for me.

https://pastebin.com/cn0xfu4D

There is also no guide for current version, but I built it on server that does not crash, only I crashed.
Maybe i missed something with mods - not ingame setup. Only when i try to open reactor for first time it crash, no other gui doing it.

**Comment by brandon3055** [comment]
This looks like it may be an odd edge case issue with the JEI integration. 
Will be fixed in the next release.
