### ISSUE TITLE
Draconic reactor problems

### ISSUE THREAD

**Issue by phi1ip83** [brandon3055/Draconic-Evolution#877]
## Description
In 1.10.2 the draconic reactor warms up normally but as soon as i activate it, it blows up. at one point i have had 2 energy injectors being fed over 500,000 rf and it still blew up. Would it be possible to tell me what is wrong with it?

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:
* Mod Pack: project ozone light

## Problem
![image](https://user-images.githubusercontent.com/15946818/29488892-26711a30-84e2-11e7-98f0-385a94a6bd4d.png)

Reactor right before it blows up.

**Comment by brandon3055** [comment]
Are you extracting energy from the core? If so how? Can you show me a screenshot of the setup before you hit activate?

**Comment by phi1ip83** [comment]
I figured out why it wasnt working

**Comment by phi1ip83** [comment]
In my setup i was using cryo-stabilized flux ducts from thermal expansion between the reactor stabilizer and the fluxgate. This meant the fluxduct was trying to move an infinite amount of energy at once to the flux gate and caused it to blow up.

**Comment by phi1ip83** [comment]
this setup works far better.
![2017-08-23_17 43 59](https://user-images.githubusercontent.com/15946818/29639952-a81b35ac-882a-11e7-8427-9d819dae69d4.png)

**Comment by phi1ip83** [comment]
i have the fluxgate leading to the injector set to 230,000 and the fluxgate leading out of the stabilizer to 530,000.

**Comment by phi1ip83** [comment]
how the fluxgate is leading out of the stabilizer no more problems!

**Comment by brandon3055** [comment]
Hmm... that shouldn't have been an issue unless the cryo ducts have changed since 1.7.10. The max transfer per tick should still be limited by the devices receiving the energy... @covers1624 Have the cryo ducts changed since 1.7.10?

**Comment by covers1624** [comment]
Nope, should be the same don't think there were any changes to the actual grid logic except the ability to have multiple per duct.

**Comment by jmac460** [comment]
Actually, i am having issues with the fluxduct as well. Everything else seems to work fine, except the flux duct.
