### ISSUE TITLE
Using Shaderpacks messes with effects of Crystals

### ISSUE THREAD

**Issue by Firestar311** [brandon3055/Draconic-Evolution#878]
## Description
I was testing a modpack of mine in a single player world with Shaders and I noticed that using a Shaderspack makes the particle effects (Beams and the like) look really funny and very weird, I tried Disabling the use of internal shaders to see if it would work but still go the same result. Here is a a video of this, it happens at some angles. In this video the Crystal shaders are disabled. 
https://drive.google.com/file/d/0BzDlH7elJh-HTU1YUEtmWFU1TEE/view?usp=sharing
## Base information
* Minecraft version: 1.12.1
* Minecraft Forge version: 14.22.0.2459 (lastest as of this issue)
* Mod Pack: Custom modpack
Optifine Version: 1.12.1_HD_U_C5

## Crash report
NONE
CRASH REPORT HERE
NONE

**Comment by covers1624** [comment]
Hmm, its possible that the shaders DE uses are conflicting with your shader pack, but as you have stated, you tried disabling DE's shaders to no avail, Im not entirely sure whats going on.. Can you link the shader pack and the settings we need to reproduce this please? also can you attempt to strip it down to the minimal mods needed to make this happen.

**Comment by brandon3055** [comment]
@covers1624 Also the beams and particles affected dont use a shader. They use my custom particle system so not sure whats up with this. I suspect the shader is just trying to apply itself to literally all world rendering which is fine for vanilla and basic modded renderers but when you throw in complex renderers like mine... It may just implode. But thats just a theory.

**Comment by Firestar311** [comment]
This happens with just Draconic Evolution, Brandon's core, latest version of Forge and pretty much every shaderpack that I have tried. So I think @brandon3055's theory is correct. Anyways, here is the link to the shaders from the video and I am using the recommended settings, but this also happens on default settings
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293898-chocapic13s-shaders

**Comment by bcrotty** [comment]
This happens for me with Continuum 1.3 and Kuda shaders on 1.10.2 as well.

**Comment by brandon3055** [comment]
I dont think there is anything i can do to fix this on my end. I think its simply the shader system optifine uses does not support the type of custom renderer i use to render my particles. This would probably have to be fixed within optifine.
