### ISSUE TITLE
Mob Grinder does not respect rotation with most wrenches

### ISSUE THREAD

**Issue by Gunsmithy** [brandon3055/Draconic-Evolution#879]
## Description
The Mob Grinder always kills mobs in the orientation it was originally placed. Rotating the block with a wrench changes its appearance as expected, but the kill box remains the same as it was when first placed.Removing the block and placing it again is required for any reorientation. 

This appears to occur with all wrenches in the Direwol20 pack except for those from Applied Energistics 2. This includes but is not necessarily limited to:  
* Ender IO's Yeta Wrench
* Forestry's Wrench
* IndustrialCraft 2's Wrench and Electric Wrench
* Refined Storage's Wrench.

A short video clip of this in action can be seen here: [https://streamable.com/a90rx](https://streamable.com/a90rx)

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: Direwolf20 1.10 v1.12.1

## Crash report
Not a crash bug.

**Comment by brandon3055** [comment]
This will be fixed in the next release.

**Comment by Gunsmithy** [comment]
![My man!](https://res.cloudinary.com/teepublic/image/private/s--zVLVA5Bg--/t_Preview/b_rgb:c8e0ec,c_limit,f_jpg,h_630,q_90,w_630/v1446237990/production/designs/267402_1.jpg)

**Comment by Sorbe1** [comment]
It now appears that the Mob Grinder does not rotate with ANY wrench.  Shift clicking/Shift-Right clicking with Certus Quartz Wrench, Yeta Wrench, Ferricore Wrench, etc. does nothing or opens the UI.

**Comment by FoxMcloud5655** [comment]
1.12.2 and earlier versions are not supported.  If you have an issue with a later version, then feel free to open up a new ticket.
