### ISSUE TITLE
Draconic Chest Deleting items

### ISSUE THREAD

**Issue by ZombieKilla111** [brandon3055/Draconic-Evolution#88]
I seem to be having an issue with the draconic chest deleting its contents when broken and replaced on my personal server. we are currently running sky factory 2.3 and also ive noticed some server lag that seems to correspond with each occurrence but i can't confirm whether or not the two are related or not.

**Comment by brandon3055** [comment]
Need more information.
How are you breaking the chest.
Dose it always loos its inventory?
Are there any errors in ether the client or server log?

**Comment by ZombieKilla111** [comment]
im using a tinkers construct alumite pickaxe it seems to be happening randomly and ther arent any errors in the server console but i cant seem to replicate without using it normally during mining and loosing all my ores to check client side

**Comment by brandon3055** [comment]
Well since your the only person to report this bug (And there are a lot of people using the chest) My guess is it was something to do with the server running low on ram. Let me know if it happens again now that you have increased the ram allocated to the server.

**Comment by ZombieKilla111** [comment]
seems to only happen when the servers ram usage hits 100% of whatever the configured amount is
