### ISSUE TITLE
[1.12] Draconic Evolution gaining achievements. 

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#880]
## Description

So, not the end of the world, doesn't crash the game, at least not yet. Just unusual strange odd behavior. For some reason I am getting messages that say, and I quote, [Draconic-Evolution] has made the advancement [Monster Hunter]

## Base information
* Minecraft version: 1.12
* Minecraft Forge version: 14.21.1.2443
* Mod Pack: Unstable 1.12
* Draconic Evolution version : 2.3.3.261

**Comment by covers1624** [comment]
Duplicate: https://github.com/brandon3055/Draconic-Evolution/issues/842
