### ISSUE TITLE
[1.10.2] Client crash -Description: Rendering Block Entity   java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by ProsperCraft** [brandon3055/Draconic-Evolution#881]
## Description
One player placed extra utils stone barrels with lava on the ground with Draconic place,  one of the two players crashed with this.
## Crash report -  https://pastebin.com/9ecZ7uY8

Some time later, the server crashed with this -https://gist.github.com/ProsperCraft/abacd7ddf5f7f7bd7928832e2dc7c63e
Which then caused the server to roll back 3 hours, even though the save interval is set for 5 minutes.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:forge-1.10.2-12.18.3.2316.jar
* Mod Pack: Age of Progression 2.6
    SpongeAPI: 5.2.0-SNAPSHOT-c675e80
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2597

**Comment by brandon3055** [comment]
How much time passed between the client and the server crashing? The two crashes do not seem related. The client crash seems to be an issue with DE though it may be an edge case issue. The server crash was caused by sponge.
