### ISSUE TITLE
Potentiometer orientation on block place is always "upside down"

### ISSUE THREAD

**Issue by GuntherDW** [brandon3055/Draconic-Evolution#884]
## Description

Note: I haven't tested if this bug occurs with just DE and BC yet.

When I place down a Potentiometer, no matter which side I clicked on it always ends up being placed "upside down".

Like as if I clicked on the bottom side of a block.
This causes it to fall off and break when a block update occurs if it's not actually "on" a block.

http://i.imgur.com/HrsIbwT.png
http://i.imgur.com/EBWF6h8.png

I checked the console output and no exception or any other log message popped up when I placed said blocks.

## Base information
* Minecraft version: 1.12
* Minecraft Forge version: 14.21.1.2443
* Mod Pack: Quickly put together kitchen sink pack
* Brandon Core: 2.3.2.129
* Draconic Evolution: 2.3.3.261

## Crash report
```
No crash report because no crash occured
```

**Comment by brandon3055** [comment]
This will be fixed in the next release.
