### ISSUE TITLE
Can I share this mod with the minecraft forum in China

### ISSUE THREAD

**Issue by 6Bpencle** [brandon3055/Draconic-Evolution#885]
The mod is very interesting ,I very like it.I think you can do it better.So I want to share this mod with the minecraft forum in China.This is website [http://www.mcbbs.net/](url),and let more friends use it.I hope you can agree!

**Comment by brandon3055** [comment]
As always you are allowed to post links to the curse page but like most mods i do not allow reposting of mod files on other sites.
