### ISSUE TITLE
max amount of custom fusion recipes?

### ISSUE THREAD

**Issue by resinate** [brandon3055/Draconic-Evolution#888]
## Description
after 107 recipes in fusion table im not able to add anymore recipes to the list, theyre let me add anymore

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: Latest
* Mod Pack:

## Crash report
```
CRASH REPORT HERE
```

**Comment by brandon3055** [comment]
There should not be a limit. But that must be a massive json file. Perhaps there is a mistake somewhere? if that is the case there should be an error in the log on startup.
