### ISSUE TITLE
[1.10.2] Dragon Heart Dupe

### ISSUE THREAD

**Issue by TheEnding19** [brandon3055/Draconic-Evolution#889]
## Description
If you kill the Ender Dragon and hover by the heart whilst it is preparing to drop, as the heart enters your inventory, if you teleport to another dimension using a dislocator the heart will be in your inventory but if you go back to the end it will still be there but the timer with the white particles will have reset. This process can be repeated multiple times as long as you do the same thing.
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: forge-1.10.2-12.18.3.2316
* Mod Pack: Tested with just Draconic Evolution

## Crash report
```
No crash
```

**Comment by brandon3055** [comment]
This will be fixed in the next release. Thanks for letting me know about this.
