### ISSUE TITLE
1.12 Spawner issues

### ISSUE THREAD

**Issue by mikeroq** [brandon3055/Draconic-Evolution#890]
Running 1.12-2.3.3.261-universal version. 
## Description
Couple issues with spawner:

1)  This might be an issue with something else since Resturbed spawners are also doing it. Spawners won't spawn passive mobs. This was working before but seemed like it stopped when I upgraded to 2.3.3.261 from 2.3.2.258.

2) When looking at a spawner there is no HUD showing information on it like in the past.

3) Right clicking with a nether star or an Enchanted golden apple do nothing. Not sure if this was changed and I just can't find info on it. It seems like the spawners are ignoring players and light level on their own.

## Base information
* Minecraft version: 1.12
* Minecraft Forge version: 14.21.2443
* Mod Pack:

**Comment by mikeroq** [comment]
Never mind I think I figured it out. I couldn't find any information on this but looking through the source code it looks like spawners were changed to have their spawn requirements and player requirements based off the tier.

**Comment by brandon3055** [comment]
There is info about the spawners in the DE ingame info tablet.
