### ISSUE TITLE
[1.10.2] Custom Fusion Recipes Issue

### ISSUE THREAD

**Issue by yepidoodles** [brandon3055/Draconic-Evolution#891]
Hello,

Firstly I'd like to point out I don't actually use Draconic Evolution, this is for a modpack I created. Secondly, this is more of an information gathering issue post (sorry if it's not appropriate).

I'm trying to get custom infusion recipes to work (I did look for existing issues on it but the ones I found seemed to have been resolved). After restarting my game, the infusion does not come up in JEI (I haven't actually tried the infusion - there's no reason it wouldn't come up in JEI first).

I have created the .json as directed; file: https://pastebin.com/VEUGuUBi

I believe I followed the instructions on the text file correctly, however I have been known to be wrong. So any extra information/ insight you can give I would be greatful. Please let me know if you need any extra information.

## Versions
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2422
* Draconic Evolution version: 2.1.5.262
* Mod Pack: [Dragon Industries 3.2 Beta](https://www.technicpack.net/modpack/di-beta.1078730)

- Alice Sellars
DragonTechMC

**Comment by falizure** [comment]
I can confirm this issue in a similar pack.

**Comment by dalgrim** [comment]
I can confirm Custom Fusion Recipes do not work right now on my install either.

**Comment by brandon3055** [comment]
Try this
http://ss.brandon3055.com/ywe5ozr.txt
If it still does not work i will need to see your startup log.

**Comment by yepidoodles** [comment]
It didn't work, I've uploaded the fml log.

[fml-client-latest.txt](https://github.com/brandon3055/Draconic-Evolution/files/1265997/fml-client-latest.txt)

**Comment by brandon3055** [comment]
Oh... the catalyst for the draconic hoe is a diamond hoe not a wyvern hoe. There is no wyvern hoe.
Also according to the log the new recipe is being added. If it does not show up in JEI try crafting it anyway and see if it works.

**Comment by yepidoodles** [comment]
Yeah, that was the issue. Massive derp on my end, the reason I wanted to change it is because I disabled all the vanilla tool recipes, haha. It's been a long week... Changed so many recipes. It shows up correctly in JEI now.

**Comment by brandon3055** [comment]
Nice!
