### ISSUE TITLE
[Bug] Player Step Height incorrectly reset

### ISSUE THREAD

**Issue by BrisingrAerowing** [brandon3055/Draconic-Evolution#892]
## Description
[On this line](https://github.com/brandon3055/Draconic-Evolution/blob/3e293fc16e3a22e10f9fa7486ef791d9fed99a1e/src/main/java/com/brandon3055/draconicevolution/handlers/CustomArmorHandler.java#L343) you set the player step height to 0.5. That is incorrect as 1.8+ use 0.6 for the default player step height. See [the wiki](https://minecraft.gamepedia.com/Block#Block_height) for confirmation.

## Base information
* Minecraft version: 1.12.1
* Minecraft Forge version: 14.22.0.2460
* Mod Pack: Custom

## Crash report
N/A

**Comment by brandon3055** [comment]
Thanks for pointing that out. This will be fixed in the next update.
