### ISSUE TITLE
Issues with Stabilized spawners

### ISSUE THREAD

**Issue by jasperfirecai2** [brandon3055/Draconic-Evolution#893]
## Description
1. Right clicking a spawner with a core does not consume core
2. Right clicking a spawner does not make it retain the mob to spawn (contrary to what the info tablet says)
3. Crafting a core together with an enderIO broken spawner does not retain the mob to spawn (contrary to the info tablet)
4 - Extra (possibly working as intended). Spawner does not show what mob is being spawned visually and has no interface to tell you so.

Other problems:
Mob souls of specific mobs cannot be spawned in, meaning that creative maps are hard to get working and that fixing problems caused by issues 2 or 3 is very difficult.

P.S. You might want to spellcheck the info tablet a couple times. it's terrible atm.
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: Direwolf20 1.10

## Crash report
```
no crash
```

**Comment by brandon3055** [comment]
Im going to have to spend some time looking into this because it seems like its probably another mod causing issues. None of the problems you listed exist in dev or in my test instance.

**Comment by brandon3055** [comment]
Ok so on closer inspection it turns out the core not being consumed is a bug. Everything else needs further investigation.

**Comment by jasperfirecai2** [comment]
Alright. Can i be of any help?

**Comment by brandon3055** [comment]
If you can figure out which mod is causing the issues that would really help.

**Comment by jasperfirecai2** [comment]
alright. i'll get to playtesting

**Comment by Paul17041993** [comment]
You cant use nether stars on them either, or was that changed?

**Comment by InjuredWolf** [comment]
Just to add onto this, one of the mobs that don't work are slimes

**Comment by gigabit101** [comment]
Version no longer supported + issue fixed in 1.12+
