### ISSUE TITLE
[1.10.2][2.1.5.262] Stat Tweaks for Wyvern Sword currently missing in config.

### ISSUE THREAD

**Issue by Compegen** [brandon3055/Draconic-Evolution#894]
## Description
Stat Tweaks config for `wyvernSword` are currently missing.
Adding the assumed appropriate lines to the config does not make them work.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2422
* Mod Pack: Custom
![wyvern](https://user-images.githubusercontent.com/8009507/29947475-76a398ac-8e6f-11e7-8e8c-18aff3783869.PNG)

**Comment by brandon3055** [comment]
This should be fixed in the latest version
