### ISSUE TITLE
[1.12] Draconic Chest doubles TE Iridium Ingots as well

### ISSUE THREAD

**Issue by llloyd4** [brandon3055/Draconic-Evolution#896]
## Description

I put in one stack of Iridum Ore from Thermal Expansion into the Draconic Chest and it fed the ingots back into the smelting slots and resmelting and redoubling them, I wound up with 6 stacks of ingots before I turned *off* the Auto Feed part and cleared the slots otherwise it would have continued until the chest was full of iridium ingots. 

## Base information
* Minecraft version: 1.12
* Minecraft Forge version: 14.21.1.2443
* Mod Pack: FTB Unstable 1.12

**Comment by brandon3055** [comment]
Sounds like another mod is marking the iridium ingot as an ore. Will need to speak to lemming about the best way to handle this. 
Will push a fix as soon as i have a solution.

**Comment by KingLemming** [comment]
We aren't marking the ingots as ores. Ingots are ingots. Ores are ores. No idea who is doing that.
