### ISSUE TITLE
wireless relays not connecting with nothing

### ISSUE THREAD

**Issue by cham326** [brandon3055/Draconic-Evolution#897]
## Description
I'm trying to use Wyvern crystals to connect to injector but it says invalid device. I also try with other machines but it said the same thing
## Base information
* Minecraft version:1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: sky factory 3

## Crash report
```
CRASH REPORT HERE
```
![2017-09-02_09 54 23](https://user-images.githubusercontent.com/24901376/29996485-fbb9153e-8fc4-11e7-8c52-e6440a5901ce.png)

**Comment by covers1624** [comment]
The face you connect to matters, the injectors only accept power from the rear.

**Comment by cham326** [comment]
I tried every side, I just put this screenshot because it showed what I was trying to do

**Comment by cham326** [comment]
![2017-09-03_08 34 29](https://user-images.githubusercontent.com/24901376/30003473-ef7bc6a4-9082-11e7-801a-018b9b9a0a88.png)

**Comment by covers1624** [comment]
Wait, only wireless crystals connect to stuff, are you sure it is a wireless crystal?

**Comment by brandon3055** [comment]
^ That is not a wireless crystal. I can tell because the wireless have a red particle ring.

**Comment by cham326** [comment]
Sorry i just noticed,  i could not read the tablet so i did not know which one did what
