### ISSUE TITLE
[1.12.1] wyvern spawners dont work away from the player

### ISSUE THREAD

**Issue by Paul17041993** [brandon3055/Draconic-Evolution#899]
If a player is a long distance from the spawner, but the chunks are loaded, either the spawner fails to spawn mobs or the mobs are immediately de-spawned (de-spawn flag?)

Mobs tested so far; 
blaze,

- forge-1.12.1-14.22.0.2469
- Draconic-Evolution-1.12-2.3.3.261

**Comment by brandon3055** [comment]
This will be fixed in the next release.
