### ISSUE TITLE
DraconicPick+Golden Kinesis Pipe

### ISSUE THREAD

**Issue by oOAbaddonOo** [brandon3055/Draconic-Evolution#9]
I've got another one :P

I set the Draconic Pickaxe to 3x3-mode. Then i mined some stone directly next to a Golden Kinesis Pipe from Buildcraft and the game crashed
http://pastebin.com/UPMCZtPN

**Comment by brandon3055** [comment]
I just finished re writing the aoe mining code (not yet released) so hopefully that will fix it if not i will look into it.

**Comment by oOAbaddonOo** [comment]
perfekt :)
Then i will close this issue
