### ISSUE TITLE
Enchantment labels in config UI are wrong

### ISSUE THREAD

**Issue by MaienM** [brandon3055/Draconic-Evolution#903]
## Description

The config UI displays a list of all enchantments that can be turned on or off. However, these buttons toggle the wrong enchantments. So for example, toggling Looting might actually toggle Sharpness. This isn't consistent; every time I open the UI the buttons seem to behave slightly differently. So far I have not been able to discern a pattern.

I'm using a Draconic Staff of Power with the following enchantments:

- Sharpness V
- Looting III
- Reaper V
- Life Stealing III (Added by Evilcraft)
- Fortune V
- Silk Touch
- Scorching Heat (Added by Astral Sorcery)

## Base information

* Minecraft version: 1.12.1
* Minecraft Forge version: 14.22.0.2474
* Mod Pack: Custom, [modlist](https://github.com/brandon3055/Draconic-Evolution/files/1290458/modlist.txt)

## Crash report

N/A

**Comment by brandon3055** [comment]
Hmm... I was afraid something like this may happen... The tool config system was never built to be able to toggle enchants so i had to patch on a work around to make it possible. Seems my patch may be a little broken. I will look into it.

**Comment by samsonsin** [comment]
Any news on this?

**Comment by brandon3055** [comment]
tbh im not sure exactly why this is happening. The hack i implemented is ugly yes but it should work. The only thing i can think of is mods giving their enchants invalid names so i have switched to registry names which may fix the issue. Please let me know if it is fixed in the next release.

**Comment by TNTUP** [comment]
It still happens, sadly :( I'm on the FTB Rev 2.2.0

Draconic Evolution 1.12.2-2.3.12.297 w/ Brandon's Core 1.12.2-2.4.3.168 

How I can enable that debugger to see what it outputs like yours?

Same issue as this one which got closed, stating it will be fixed in DE3 -> https://github.com/brandon3055/Draconic-Evolution/issues/1063 Wasn't this PR adress this issue?

**Comment by brandon3055** [comment]
The pr made by T-Fowl should fix this. It will be in  the next release.
