### ISSUE TITLE
[Feature Request] Item that disables item dislocation in its AOE

### ISSUE THREAD

**Issue by Meryl** [brandon3055/Draconic-Evolution#904]
## Description

I love this mods item 'magnet', and I use it all the time. It does, however, force me to move auto crafting for certain other mods that require in-world crafting to places well outside my reach in order for me not to mess that up and/or end up with random items in my inventory that I do not wish to have there.

I know that there is a blacklist configuration option that I can use to prevent the dislocator from dislocating certain items, but that is not really an option because the mod in question (Actually Additions, if you were wondering) uses some very common items (coal, redstone, lapis and diamonds). Obviously, blacklisting those would undermine the usefulness of the item dislocator.

Therefor, I'd like to propose a block that would prevent the dislocator from pulling in items located within its area of effect. By placing one of those near where the in-world crafting occurs, items that are used to craft would no longer disappear into my inventory.

**Comment by covers1624** [comment]
Seems reasonable, "Magnetic normalization field projector."

**Comment by brandon3055** [comment]
I agree... 
Ok here you go. Not my best work but didn't have a lot of time to work on this.
![img](http://ss.brandon3055.com/y4kk42g.png)

**Comment by brandon3055** [comment]
Ok its in and live!
