### ISSUE TITLE
Bug when placing the Potentionmeter

### ISSUE THREAD

**Issue by bu1th4nh** [brandon3055/Draconic-Evolution#905]
## Description
When I placed the Potentionmeter, it would rather place like the Redstone Repeater or the Rain Meter like the picture below, but it was placed upside down. And when I right-clicked in it, it dropped itself. Here is my picture:

![2017-09-13_10 31 31](https://user-images.githubusercontent.com/10758763/30358461-ebd5a486-986e-11e7-9b5e-4c9ad84ee4df.png)

Can you fix the bug? Thank you very much :D.
P/s: Sorry for my bad English

## Base information
* Minecraft version: 1.11.2
* Minecraft Forge version: 1.11.2-13.20.1.2388
* Mod Pack: None

## Crash report: 
None.

**Comment by brandon3055** [comment]
DE version? This should be fixed in the very latest release.
