### ISSUE TITLE
Crash when using Mob Grinder

### ISSUE THREAD

**Issue by cursinorock** [brandon3055/Draconic-Evolution#906]
## Description
The game crash some times when i use the mob grinder, with any mob

## Base information
* Minecraft version: 1.11.2
* Minecraft Forge version:1.11.2-forge1.11.2-13.20.1.2476
* Mod Pack: Cursino Tech (custom but are on curse.com)

## Crash report
```
CRASH REPORT HERE
```
[crash-2017-09-14_03.04.11-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/1301876/crash-2017-09-14_03.04.11-server.txt)

**Comment by covers1624** [comment]
No, this is spectrite mod, they aren't doing things properly in their event handler.
