### ISSUE TITLE
amount of blocks needed for tier 8 in guide

### ISSUE THREAD

**Issue by resinate** [brandon3055/Draconic-Evolution#910]
number of blocks needed to make ball is wrong lol, it takes WAY more than 384 awaken blocks lol

**Comment by brandon3055** [comment]
What mc/mod version are you using? This was changed a while ago and the doc was changed aswell. Its possible you are using a version from before this change.

**Comment by resinate** [comment]
im using newest one for 1.10.2
https://cdn.discordapp.com/attachments/276586040490459145/366056076438929408/unknown.png

lol should be other way around lol

**Comment by cwilson21** [comment]
It is also possible you ran into the same issue I did tonight where the pack I am playing ATM3, has it configured so that you need less Draconium and more Awakened than the book says you need or so it seems. Excerpt from the mods help-desk in their discord when I asked them about it. 

```
[2:01 AM] Shisuka (Xargling): So was the tier 8 draconic power core altered in ATM3 to need more Awakened Draconium than the tablet says it needs? (want to ask here before I report to mod author)(edited)
[2:50 AM] Yoosk: Yes
[2:51 AM] Shisuka (Xargling): Cool so we weren't crazy when we had all the right stuff but not enough

```

**Comment by brandon3055** [comment]
Ahh yes i forgot about that. If hard mode is enabled it does use the old more expensive structure.
