### ISSUE TITLE
Crystal Networks effects

### ISSUE THREAD

**Issue by NopusEngibus** [brandon3055/Draconic-Evolution#911]
So i was setting up a crystal network when i realized that they made lazers that clip through my whole base, i would like to know if there was a way to disable these lasers.

**Comment by ouroborus** [comment]
Turn off particles, maybe. Otherwise, no. Also note that, given that, being graphical, that's a client-side effect, any configuration on your part would only effect you.

**Comment by brandon3055** [comment]
The lasers can not be disabled. If you dont like seeing them go through walls then just dont have them go through walls... In a future version you may not even be able to connect them through walls.
