### ISSUE TITLE
Mod dependencies are not all lowercase

### ISSUE THREAD

**Issue by mezz** [brandon3055/Draconic-Evolution#913]
https://github.com/brandon3055/Draconic-Evolution/blob/f5789462962897ef195147f6a8f53cd46076e099/src/main/java/com/brandon3055/draconicevolution/DraconicEvolution.java#L26

Dependencies with uppercase ModIds will do nothing, since all modIds have to be lowercase.

**Comment by covers1624** [comment]
Rip. :D

**Comment by brandon3055** [comment]
rip.....
