### ISSUE TITLE
Energy Infuser

### ISSUE THREAD

**Issue by BaneOfSerenity** [brandon3055/Draconic-Evolution#914]
Currently it seems like the energy infuser is capped at 128k rf/t when charging, it would be great if this could be increased or make it upgradable via fusion crafting. Right now when charging anything in a higher tier it's just too slow.

**Comment by brandon3055** [comment]
The cap is ether 10MRF/t or the cap imposed by the  item being charged (whichever is lower) in this case it sounds like the item your charging is limiting the charge rate.

**Comment by BaneOfSerenity** [comment]
I'm charging DE items that have cap upgrade. Do the cap upgrade only increase power? If so can they be changed to also increase charging rate? Also to the wireless crystals have any cap imposed?

**Comment by brandon3055** [comment]
The transfer limit on the crystals is a little complicated. The base limit is a little under half the crystals capacity per tick but the more crystals you have in series the slower the energy flow. But even so with the higher tier crystals the energy transfer rate should be higher that you should ever need.

**Comment by brandon3055** [comment]
As for the charge rate of items wyvern items are limited to 500KRf/t and draconic are limited to 8Million RF/t If the energy bar on the left in the energy infuser is empty while charging then you are not supplying the infuser with enough energy to charge at max speed.

**Comment by BaneOfSerenity** [comment]
Sorry for the late response.
So i have a fully depleted Draconic Flux Capacitor that can hold 640MRF http://prntscr.com/h06mx9
That is linked up to a Wyvern Wireless Energy Crystal and that's only outputting 128K RF/t to my Energy Infuser http://prntscr.com/h06nbi
The wireless crystal is linked iinto a Wyvern Energy I/O Crystal which is pushing 150K RF/T to my base http://prntscr.com/h06nry
That crystal is hooked up to my energy pylon to my Tier 5 Energy Core which is at max cap at all times http://prntscr.com/h06oc7

**Comment by brandon3055** [comment]
Oooh... Wireless! Yes the wireless has a cap of 32K for Basic, 128K for Wyvern and 512K for Draconic. This shouldn't be an issue when powering things like machines but for something like the infuser that needs the throughput you should attach an I/O crystal directly to the infuser.  With wyvern crystals this will give you a throughput of around 5 million RF/t when bouncing energy through 3 crystals like this. 
![](http://ss.brandon3055.com/6wbrxh3.png)

**Comment by BaneOfSerenity** [comment]
Little details :P, everything is a lot faster now, thanks!
