### ISSUE TITLE
Bibliocraft Reading Enchantment

### ISSUE THREAD

**Issue by BaneOfSerenity** [brandon3055/Draconic-Evolution#915]
Bibliocraft has a reading enchantment for helmets. It would be nice to have support for both helmets to be enchantable with this.

**Comment by brandon3055** [comment]
The helmets should accept any helmet compatible enchants in the latest versions of de

**Comment by BaneOfSerenity** [comment]
I'm on 2.3.4.265, i'll try it again and take a screenshot. I've also noticed not being able to add silk touch to the staff of power and a couple other things that i don't remember right now.
