### ISSUE TITLE
Retroactively adding ore

### ISSUE THREAD

**Issue by ouroborus** [brandon3055/Draconic-Evolution#916]
[log.txt](https://github.com/brandon3055/Draconic-Evolution/files/1315197/log.txt)

I noticed some unusual log activity on my server recently involving "Retroactivity adding ore ..." messages. I looked at the code and I think I understand why it's a thing. The thing I find unusual is that is seems to be repeatedly adding ore to the same chunks over and over. (Though, because of the way the generation seed is derived from the chunk coordinates, you don't actually get more ore except possibly in specific circumstances.)

In the attached log, it's stuck on repeatedly generating for chunks 51, 106; 51, 108; and 51, 109 in what I think is the Aroma mining dimension.

Minecraft v1.12.1
ATM3 v3.01

**Comment by ouroborus** [comment]
The server has been running this entire time and DE is still trying to populate 108 and 109 with occasionally forays to 106.

**Comment by b0bst3r** [comment]
I have to ask about this 

06.10 05:13:20 [Server] Server thread/INFO [draconicevolution]: Retroactively adding ore to {dim: -6, chunkPos: [33, -13], chunksToGo: 19}

Dim -6 is added to the ban list of ores to generate in 

# Add the dimension id of any mod dimension's you dont want draconium ore generated in
    I:oreGenDimentionBlacklist <
        6
        -6
        50
        51
        52
        53
        100
        101
        102
        103
        104
     >

Is it just server spam or is it actually adding the ores, no one has found any yet.

**Comment by brandon3055** [comment]
Correct the blacklist is working but the blacklist is only checked in the generate method which is fired by the retrogen code so you still get the retrogen spam. Retrogen spam will be disabled in the next release.
