### ISSUE TITLE
Draconic Reactor Explosion does not destroy all blocks in area.

### ISSUE THREAD

**Issue by Platoonsgt1** [brandon3055/Draconic-Evolution#917]
## Description
As far as I can tell, the explosion does not destroy blocks which have air above them. This usually leaves a single block thick layer of surface material, one block thick layers of water where rivers/lakes/oceans used to be and the floors of any caves. (River/Lake/Ocean floors are properly destroyed)

In some instances, blocks with air below them will not be destroyed as well. I had a energy storage multiblock (max size) next to an exploding reactor, and both the top and bottom layers of awakened draconium blocks remained, as well as the top and bottom layers of the energy core stabilizers.

Additional reactor explosions also do not destroy these blocks.

In these screenshots I detonated 2 reactors, the first on the surface and the second at bedrock. There is some debris in the area from me messing with Blood Magic's Meteor Ritual, but the rest of the landscape was BoP's default terrain before the explosions.

![Imgur](https://i.imgur.com/dkvCAG7.png)![Imgur](https://i.imgur.com/Lvilgfh.png)

## Base information
* Minecraft version: 1.10. ?
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: DW20 1.10 (v1.12.1)
* Draconic Evolution version: 1.10.2-2.1.0.232 (2.1.0)

**Comment by brandon3055** [comment]
You are using a very outdated version of DE. This should be fixed in the latest version.

**Comment by Platoonsgt1** [comment]
Fair enough. I thought I'd mention it because the last time I tried it out a few months ago it was also like this, and I couldn't find any mention of it anywhere.
