### ISSUE TITLE
Public Armor's Damage Source

### ISSUE THREAD

**Issue by MasterGeneral156** [brandon3055/Draconic-Evolution#918]
Will preface this with the fact I'm a Java noob. >.>  
Anyway, I wish for the only damage source that can actually ignore Draconic/Wyvern armor to be made Public! I've attempted Reflection, but being a Java noob, I wasn't successful. :T 
Specifically:
https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/handlers/CustomArmorHandler.java#L37

For background, I'm trying to make a mod that should serve as an equalizer against a person in Wyvern/Draconic armor.

**Comment by brandon3055** [comment]
That damage source is not meant to be used on a weapon. It is simply used as a marker for when a player is killed with something like the /kill command. The only reason it even exists is to add a custom death message when that occurs. If you want to create some sort of weapon meant to be super effective against DE armor then  just deal a large amount of damage to players wearing DE armor.

**Comment by MasterGeneral156** [comment]
Actually, that'll work just fine! Thanks for responding :D
