### ISSUE TITLE
dragon respawning

### ISSUE THREAD

**Issue by Wrsaith** [brandon3055/Draconic-Evolution#920]
I dont crash or anything no issues posted to files just can't get the dragon to respawn. i'm using the expensive crystal recipe that uses nether stars to craft but once place nothing happens. no beams of light no sounds nothing. just they sit there. all 4 one on each side. 

 Minecraft 1.12 
DE 1.12-2.3.3.261

**Comment by ouroborus** [comment]
@Wrsaith Screenshot of your placement? Are you using just DE or some other mods or a modpack?

**Comment by Wrsaith** [comment]
I am using several mods but DE is the only one that effects the dragon to my knowledge.  as stated in the wiki i've got one crystal in the middle of each side. on all 4 sides. i have tried the corners, the edges of the sides and every combination of each. I've even turned off the expensive mode for the crystals and tried again with the same outcome.
![2017-09-22_20 53 20](https://user-images.githubusercontent.com/1598821/30768619-2d159756-9fd8-11e7-9939-4734db2d4354.png)


i've checked through all my other mods and the dont have any config concerning the dragon other than like immersive engineering where they have the dragons breath cartridges for the gun.

**Comment by Wrsaith** [comment]
I updated the mod to your latest release for 1.12 but still nothing as well.

**Comment by Wrsaith** [comment]
As an update I deleted the end world and let it respawn killed the dragon again and it worked fine. So maybe something with how it gen'd the first time messed it up. But also even tho DE was changing the recipe one of my friends was still able to make the end crystals the default way, Tho not sure if he was just being delusional xD

**Comment by brandon3055** [comment]
That has nothing todo DE. DE only changes the recipe and does not affect the ritual in any way. I suspect there was some sort of world gen issue or something maby related to transferring a world between versions? No idea but its not DE.
