### ISSUE TITLE
[Feature Request] Config for Disenchanter cost

### ISSUE THREAD

**Issue by oxinabox** [brandon3055/Draconic-Evolution#921]
I suggest that there should be a config setting to scale the disenchanter's extraction cost in XP.
I wish to be able to scale it to match the difficulty etc of my pack.
So in my particular instance,
I've got a pack with Dragonic Evolution and Anvil Enchantments.
Anvil enchantments lets you craft any vanilla enchanted book using an an anvil and some vanilla items.
For example _Repair_ is 3 golden apples and 15XP.
Contrast to draconic evolution's Disenchanter which costs 20XP to extract repair from a breastplate.

So I want to be able to use the config to bring them into parity,
or even make the disenchanter cost less than the anvil, since you need to craft the disenchanter, and you need to find the item.
Though the exact balancing would require some thought, given that mobs often drop bad items with great enchantments.
And because it is a balancing then, that I why I feel it should be a config setting, 
so that mod-pack creators can tweak it to their satisfaction.

**Comment by brandon3055** [comment]
Will be a multiplier to adjust the dissenchant cost in the next release.
