### ISSUE TITLE
[1.12.1] Draconic chest causing game crashes

### ISSUE THREAD

**Issue by jefferyrlc** [brandon3055/Draconic-Evolution#922]
## Base information
* Minecraft version: 1.12.1
* Minecraft Forge version: 1.12.1-14.22.1.2478
* Mod Pack: Custom
[crash-2017-09-24_21.40.40-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1328010/crash-2017-09-24_21.40.40-client.txt)

## Crash report
```
CRASH REPORT HERE
```

**Comment by ruifung** [comment]
For me this is worked around by setting NEI to use the JEI panel instead. Or disabling NEI.
