### ISSUE TITLE
Suggestion to make Capacitors charge Baubles Items in "charge armor" mode

### ISSUE THREAD

**Issue by ben-mkiv** [brandon3055/Draconic-Evolution#923]
## Description
actually Capacitors only charge Items in the Armor Slot, but not in Baubles Slot.

## Base information
* Minecraft version: any
* Minecraft Forge version: any
* Mod Pack: any

Here's an example of how EIO Wireless Charger handles the Baubles Items =>
https://github.com/SleepyTrousers/EnderIO/blob/c09c4efee1d6c14dbfe9058cccc2d8c341e91ec5/src/main/java/crazypants/enderio/machine/wireless/WirelessChargerController.java#L106

This would be low Priority as i dont know of many mods that add BaubleItems that use Energy at all.

Would also write the Patch for 1.10.2 if it would be pulled and no one else is interested in writing it ;)
(if im not wrong this should be upstream compatible to 1.12.x)

**Comment by Saklad5** [comment]
I would like the ability to have Draconic Capacitors charge _all_ items in the inventory, not just held items. It would make using the Refined Storage Addons Network Bag much better, for instance.
