### ISSUE TITLE
Tier 7 Energy Core is not storaging more than 2.147B RF

### ISSUE THREAD

**Issue by tbalthaza** [brandon3055/Draconic-Evolution#924]
## Description
I've just setup a Tier 7 energy core for storing my solar energy, and after reaching 0.01% (2.147B) RF, it stopped charging, even though it's consuming the energy.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2316
* Mod Pack: FTB Beyond

## Crash report
NO CRASH REPORT
![draconic core](https://user-images.githubusercontent.com/32314767/30889192-0385ece4-a2fb-11e7-9e3a-4f7e5fc1ceec.jpg)

**Comment by kdb424** [comment]
Can confirm. In custom modpack on latest. Having this same issue.

**Comment by brandon3055** [comment]
How are you feeding energy into the core?

**Comment by kdb424** [comment]
I was using flux points, though this has been tested time and time again. Latest stable release hits the mack stated, and thinks it's full. The rest works fine except the incorrect limit on a level 7 core. Reverting to last stable on curseforge works great same setup.

**Comment by brandon3055** [comment]
Try a different conduit because there are a lot of issues with flux points ant that entire mod in general.

**Comment by kdb424** [comment]
I had checked even putting a generator next to it. I will test yet again, but as stated reverting just draconian evolution worked fine with Flux points.

**Comment by brandon3055** [comment]
Do you mean a DE generator?

**Comment by kdb424** [comment]
I tried many mods generators, DE generators as well. The T7 energy core does not accept enough power. The value seems to be set to Billion, not trillion as it works up to the point, then caps out.

**Comment by brandon3055** [comment]
And you say just reverting DE fixes this? Or did you revert the entire pack?

**Comment by kdb424** [comment]
In my case it was a custom pack. I reverted DE alone in my pack and it worked. Tested several times, no config files change. Just reverted from latest on curseforge, to previous version for 1.10.2

**Comment by brandon3055** [comment]
I dont see anything in the latest changes that would cause this... Are you also using the latest BCore?

**Comment by kdb424** [comment]
Latest versions of everything on curseforge as of the time of typing thes except DE as this bug affected several of my users.

**Comment by brandon3055** [comment]
The only thing i did in the latest version was add the forge energy capability to the core. The only thing i can think of that cause cause this is if some other mod is overriding that cap and preventing the core from charging over Int max value.

**Comment by Vierbein** [comment]
Sky Factory 3 has exactly the same problem. I've rebuild lower tier Core and still caps at given value(2.147B).

**Comment by covers1624** [comment]
What are you using to feed energy in to the EnergyCore? If you are using FluxPoints/FluxNetworks this is an issue on their end, they are being stupid and checking explicitly if the core has Integer.MAX_VALUE of energy stored and not transfering anymore, when infact that is invalid and they should ask the core to consume the energy first as any other power transfer system does.

**Comment by Vierbein** [comment]
Tested on flux network and EnderIO capacitors directly in and out from pylons.
I'm using twitch installer. Downgrading from DE 263 to 262 fixed the issue.

**Comment by SOL3675** [comment]
I'm using 1.12 version of DE and same issue. It happened in 1.10.2 recently.
I think it caused by change of Forge Energy API.
I noticed the same problem with Zetta Industries mod that has also Multiblock Battery system, and can't storing more than integer maximum value of energy.
It seems to be almost of all generators, cable can't push energy to buffer that has 2.14B Forge Energy.

I'm using Mekanism's Universal Cable that can force to push energy. It works fine with DE and Zetta Industries.

I'm not a modder, but I'm glad if it can help you.
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2316/forge-1.10.2-12.18.3.2316-changelog.txt
Sorry for my poor English.

**Comment by seeeeew** [comment]
@covers1624: Thanks, that solved the problem on my Sky Factory 3 server. :+1: 

The energy in my Tier 6 Energy Core was capped at 2^31-1 while using FluxNetworks. When I connected my Tier 7 Solar Panels (from Solar Flux Reborn) directly to the Energy Pylons, everything worked fine.

**Comment by SubtypeZero** [comment]
This appears to be an issue with Sky Factory 3.0.15 and as a workaround, one of my players has suggested the use of Draconic Energy Relays

![relay](https://user-images.githubusercontent.com/25497312/31854406-146b11f8-b65e-11e7-8cf8-cffc5426076a.png)

**Comment by brandon3055** [comment]
#928

**Comment by TheDeaX-Lab** [comment]
New issue on 1.12.2 https://github.com/brandon3055/Draconic-Evolution/issues/1455
