### ISSUE TITLE
Draconic Energy Ball resets on SMP

### ISSUE THREAD

**Issue by ChetwyndKid** [brandon3055/Draconic-Evolution#925]
## After reaching an amount of power the ball resets and it starts filling up again
The configs where altered, 
    machines {
        I:"Energy Infuser: Energy buffer size (RF)"=10000000
        I:"Energy Infuser: Maximum energy transfer rate (RF/t)"=10000000
        I:"Mob Grinder: Amount of energy required to kill entity (RF)"=1000
        I:"Mob Grinder: Internal energy buffer size (RF)"=20000
        I:"Mob Grinder: Main energy buffer size (RF)"=100000
        I:"Mob Grinder: Maximum energy reception rate (RF/t)"=32000
        D:"Multiblock Energy Storage Tier 1: Energy buffer size (RF)"=4.55E9
        D:"Multiblock Energy Storage Tier 2: Energy buffer size (RF)"=2.73E12
        D:"Multiblock Energy Storage Tier 3: Energy buffer size (RF)"=1.64E16
        D:"Multiblock Energy Storage Tier 4: Energy buffer size (RF)"=9.88E19
        D:"Multiblock Energy Storage Tier 5: Energy buffer size (RF)"=5.93E22
        D:"Multiblock Energy Storage Tier 6: Energy buffer size (RF)"=3.56E23
        D:"Multiblock Energy Storage Tier 7: Energy buffer size (RF)"=2.14E25

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Mod Pack: Galactic Science 2

## Crash report
```
CRASH REPORT HERE
```

**Comment by ChetwyndKid** [comment]
As an update, Resetting the config to the default values still has the reset once it reaches a certain amount.

**Comment by brandon3055** [comment]
Your numbers are to big which results in an overflow. That maximum possible capacity is 9,223,372,036,854,775,806

**Comment by ChetwyndKid** [comment]
Well I reset the config to the default values and was still having the issues as I said in my previous comment, Once it hits a certain % of the ball the power resets.

**Comment by brandon3055** [comment]
No idea... Try completely deleting the config fire (if you did not already do that) and make sure you delete the correct one. Also try breaking and replacing the core. If that does not work then i have no idea...
