### ISSUE TITLE
[1.12.1] Dangerous alternative prefix

### ISSUE THREAD

**Issue by UnPure** [brandon3055/Draconic-Evolution#926]
## Description
While starting a client/server, DE is producing an error/warning in the log file.

    [Server thread/WARN] [FML]: ****************************************
    [Server thread/WARN] [FML]: * Dangerous alternative prefix `minecraft` for name `end_crystal`, expected `draconicevolution` invalid registry invocation/invalid name?
    [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
    [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
    [Server thread/WARN] [FML]: *  at com.brandon3055.draconicevolution.lib.RecipeManager.lambda$registerEvent$0(RecipeManager.java:64)
    [Server thread/WARN] [FML]: *  at com.google.common.collect.ImmutableSet$Indexed.forEach(ImmutableSet.java:392)
    [Server thread/WARN] [FML]: *  at com.brandon3055.draconicevolution.lib.RecipeManager.registerEvent(RecipeManager.java:61)
    [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_424_RecipeManager_registerEvent_Register.invoke(.dynamic)...
    [Server thread/WARN] [FML]: ****************************************

## Base information
* Minecraft version: 1.12.1
* Minecraft Forge version: 14.22.0.2475
* BrandonsCore version: 2.3.3.132
* Draconic Evolution version: 2.3.4.265

**Comment by brandon3055** [comment]
This is just fml complaining that a mod is registering a recipe under a different name. This is required to replace the vanilla ender crystal recipe. I will make a change to prevent this message from showing in future versions but in the mean time its safe to ignore this warning.
