### ISSUE TITLE
[1.11.2]Entity Detector/Advanced Entity Detector options reset

### ISSUE THREAD

**Issue by AndreaS992** [brandon3055/Draconic-Evolution#927]
## Description
![screenshot_8](https://user-images.githubusercontent.com/32372634/30987478-6a756018-a497-11e7-9c60-9dcd7656dd01.png)
I've setted the Filter options of the Advanced Entity Detector as in the first screenshot but as soon as I go away (or disconnect) and the chunk unloads, ALL Filter options turn back to ON.
![screenshot_9](https://user-images.githubusercontent.com/32372634/30987612-eb9e38cc-a497-11e7-9007-96b40ae8af61.png)
Same happens with Entity Detector.
I've tried maintaining the chunk loaded with FTBU chunk loader but nothing changes.
 
## Base information
* Minecraft version: 1.11.2
* Minecraft Forge version: 13.20.1.2476
* BrandonsCore version: 2.2.4.131-universal
* Draconic Evolution version: 2.2.4.264-universal
* Mod Pack: Custom

**Comment by brandon3055** [comment]
This will be fixed in the next release.
