### ISSUE TITLE
[1.7.10] Item Dislocator hangs up the Server by large quantity

### ISSUE THREAD

**Issue by Hodel1** [brandon3055/Draconic-Evolution#929]
## Description
Hi,
we have actually a big problem. We have one or the other player, they farming with a Staff of Power (For Example: 11x11), and activate the Magnet (Item Dislocator) to catch anything.

When anyone done this, the server is hang up so long, until the player disconnects the game / rejoined.
I tested it in Singleplayer too and that seems the same result.
The Server is hang up min. 30secs and don't give any response, in the console. Commands will be there delayed, until the hang is stopped.

This causes only, when your inventory is full and you keep farming.
It will be enough for dig 2-3 chunks with a Staff of Power (11x11), and active item dislocator.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Mod Pack: FTB Infinity Evolved 3.0.2

## Crash report
```
None
```

**Comment by brandon3055** [comment]
This shouldn't be an issue in 1.10+ I suggest you update your pack asap. If you cant then just try to better manage your inventory because 1.7.10 is nolonger being actively maintained.

**Comment by Hodel1** [comment]
Can i decrese the item amount of the Item Dislocator?
Or in best case - deactivate the Item Dislocator, when the inventory is full?

Without codechanges? :)
