### ISSUE TITLE
Pickaxe of the Wyvern is really loud compared to other picks / tinkers tools

### ISSUE THREAD

**Issue by MarkyB283** [brandon3055/Draconic-Evolution#932]
I have just made this pick for the first time and it seems extremely loud compared to all other tools, to the point where I have to turn my sound off to use it

- Edit, It only seems to be when using it in the 3x3 mode, I think it is breaking all 9 blocks and then giving the noise from all of them at once? this might of been fixed in a later patch but unfortunately not in FTB infinity

## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:10.13.4.1614
* Mod Pack: FTB infinity evolved

## Crash report
```
CRASH REPORT HERE
```

**Comment by covers1624** [comment]
Right.. Because you are breaking 9 blocks at a time. It plays the sound over the top of each other. This is an intended feature, just turn down the specific audio channel.
