### ISSUE TITLE
Suggestion: soft dependency on Redstone Flux

### ISSUE THREAD

**Issue by josephcsible** [brandon3055/Draconic-Evolution#933]
Currently, this mod (through Brandon's Core) has a hard dependency on Redstone Flux. Now that it supports Forge Energy, can the dependency on Redstone Flux be changed to a soft dependency, via the `@Optional` annotation?

**Comment by brandon3055** [comment]
Not easily because the entire energy back end is based on RF with FE patched on top as a backup power system. But if i ever need to do a complete re write of the power system i will probably make this change.

**Comment by josephcsible** [comment]
Would you accept a PR for it?

**Comment by brandon3055** [comment]
Its something i would rather do myself as it would require a large re write of the back end code. I am already planning to re write the entire energy system when i do the DE3 re write so i think this can wait till then. And its not really that big of an issue.
