### ISSUE TITLE
Fusion crafting ejectors won’t accept power

### ISSUE THREAD

**Issue by joshuasuperboy** [brandon3055/Draconic-Evolution#934]
I have a bug report.

* Minecraft version:1.12.2
* Minecraft Forge version:14.23.0.2509
* Mod Pack:Draconic evolution

I updated this comment so it will tell more about my issue.
I do not know how to take screen shots. There is a issue with the draconic fusion crafting injectors. They do not accept power for some reason. I have tried to connect the wireless draconic lasers I think that’s what it’s called. When I did that it still did not get RF in the draconic crafting injectors. I have saw it worked with those in other YouTube videos. I have tried everything still did not get RF. I was very sad because when I tryed to fusion craft something in survival mode I could not. So I will just have to wait until you fix the draconic crafting injectors so that they will accept RF again. You can maybe test them yourself in your world in the latest update. Is that enough of info I tryed to give as much info as possible. If you want more info I can do that. I’m very new at this website and Minecraft forge. I know a little of modded Minecraft though. One more thing I also try to connect the creative RF source directly to it and still did not work.

**Comment by brandon3055** [comment]
http://bfy.tw/EM5s
My best guess is that you probably have the fusion setup incorrect. Does the gui show a valid recipe with a start option? If not then the setup or the recipe is incorrect. It  should be setup something like this
![](http://ss.brandon3055.com/k86l2ow.png)
For more information on valid setups check the information tablet.

The other possibility is your power configuration is invalid. But as you tried the creative RF source this is probably less likely. 
Power must be fed into ether the back or the side of an injector. It can not be fed into the front and should not be fed into the core itself.

When using wireless energy crystals to power machines make sure they are actually linked by holding a crystal binder. 
![](http://ss.brandon3055.com/84sio14.png)
If using an IO crystal connected to the injector make sure its in output mode and it is actually getting energy from your power system.
![](http://ss.brandon3055.com/844kuej.png)
 
And if your still having trouble with screenshots. 
http://bfy.tw/EM5v

**Comment by joshuasuperboy** [comment]
Thanks I will try if it dose not work then I’ll let you know with screen shots. Also thanks for that screen shot tutorial on bit.ly

**Comment by joshuasuperboy** [comment]
Thanks for the tutorial on bit.ly. By the way I have tryed to connect up the wireless energy crystals exactly like in picture number 2. When I did that they still did not accept RF. And also all the power transfer crystals have a black texture in 1.12.2. I will try to connect the io crystal to the back of them and set it to output. If that dose not work then I will let you know. Did you know you can just install optifine and set the performance settings in the video settings to a certain way. After you do that then you can turn other video setting to normal instead of it being low graphics. I can get over 100 FPS even with all settings set to max. It will depend on your pc.

**Comment by joshuasuperboy** [comment]
Thanks for the tutorial on bit.ly. By the way I have tryed to connect up the wireless energy crystals exactly like in picture number 2. When I did that they still did not accept RF. And also all the power transfer crystals have a black texture in 1.12.2. I will try to connect the io crystal to the back of them and set it to output. If that dose not work then I will let you know. Did you know you can just install optifine and set the performance settings in the video settings to a certain way. After you do that then you can turn other video setting to normal instead of it being low graphics. I can get over 100 FPS even with all settings set to max. It will depend on your pc. I’m just trying to get this correct that’s why I have been updating these comments a lot and deleting it then making it better.

**Comment by brandon3055** [comment]
You dont need optifine to get good FPS with high settings. Just a descent computer. btw optifine is whats breaking the crystal textures. 
![](http://ss.brandon3055.com/ynn139i.png)
