### ISSUE TITLE
Draconic-Evolution JEI Crash

### ISSUE THREAD

**Issue by ANinjaHope** [brandon3055/Draconic-Evolution#935]
## Description
I would be playing and have to look something up in JEI, so I would look it up and my game would crash before it gets to what I'm looking for. I don't know much about the background of the game so I cant say whats causing it.

## Base information
* Minecraft version:1.10.2
* Minecraft Forge version:
* Mod Pack: DNS

## Crash report
```
CRASH REPORT HERE
[crash-2017-10-08_16.07.31-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1367287/crash-2017-10-08_16.07.31-client.txt)

```

**Comment by brandon3055** [comment]
This should be fixed in the next release.
