### ISSUE TITLE
Help with draconic fusion injectors

### ISSUE THREAD

**Issue by joshuasuperboy** [brandon3055/Draconic-Evolution#936]
I need help with the draconic fusion injectors.

* Minecraft version:1.12.2
* Minecraft Forge version:1.12.2 - 14.23.0.2512
* Mod Pack:draconic evolution

I want to ask you something dose the draconic fusion injectors have to be fusing something in order for the injectors to accept RF. The reason why is cause in another YouTube video I saw it was not accepting RF but when that person started fusing something it started to accept RF.

**Comment by brandon3055** [comment]
Correct they only accept power when crafting.
