### ISSUE TITLE
[1.10.2] Server Crash

### ISSUE THREAD

**Issue by TheVeyra** [brandon3055/Draconic-Evolution#937]
## Description
Our server is crashing every so often (we are using Sponge). I'm not certain on what else I can say here but let me know if you need any more information from me.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2422
* Mod Pack: Skyfactory 3

## Crash report
```
https://pastebin.com/pYV3KHTQ
```

**Comment by brandon3055** [comment]
This has something todo with Flux Network. I will have a safety check on my end in the next release to prevent this crash.
