### ISSUE TITLE
Jump Boost Negates Draconic Energy Shield

### ISSUE THREAD

**Issue by MaxAstro** [brandon3055/Draconic-Evolution#938]
## Description
With jump boost 0, the Draconic Energy Shield absorbs all falling damage.

With jump boost 1+, the shield DOES NOT absorb ANY falling damage, and you can die from falling with a full shield.

Had a nasty surprise when I was trying to compare shield drains on different jump boost levels with a jetpack... came within half a heart of killing myself.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 8.0.99.99
* Mod Pack: FtB Beyond Version 1.11.0

**Comment by brandon3055** [comment]
misplaced a return statement... oops. Will be fixed in the next release.
