### ISSUE TITLE
Help with some textures of draconic evolution

### ISSUE THREAD

**Issue by joshuasuperboy** [brandon3055/Draconic-Evolution#939]
This issue is a thing about the textures of the draconic energy crystals.

* Minecraft version:1.12.2
* Minecraft Forge version:1.12.2 - 14.23.0.2512
* Mod Pack:Draconic Evolution

I need to ask you something about the draconic evolution energy crystals. Why when i am close the energy crystals they look like this.
![2017-10-11_19 48 35](https://user-images.githubusercontent.com/32559193/31474087-7c54bfd4-aead-11e7-8dff-6da3737d68c0.png)

When i am far from them they will render correctly. Like shown below.
![2017-10-11_19 53 30](https://user-images.githubusercontent.com/32559193/31474121-a0aa478c-aead-11e7-9d67-97b3662dcb7f.png)
Can you tell me how to fix this problem? If you can that will be great and thanks for your help.

**Comment by brandon3055** [comment]
Ether your system does not support shaders or you are using optifine and is causing issue's

**Comment by joshuasuperboy** [comment]
thats probaly why anyways thanks for the support optifine keeps down most lag though
