### ISSUE TITLE
Fusion Crafters Not working 

### ISSUE THREAD

**Issue by ResqDiver1317** [brandon3055/Draconic-Evolution#940]
We added DracEv to our modpack but the fusion crafting is not working. It is showing the valid input and has the start button, but does nothing when we press start. I am testing this using creative RF from DE.

This is my setup  https://imgur.com/3DisB1H
Here is the inside showing the start button. https://imgur.com/a/6nbJU

Base Information:
MC Version 1.10.2
Forge 1.10.2-12.18.3.2488
Custom built Modpack on Technic Launcher (AC Special Sauce 1-10-2)
Brandon's Core 1.10.2-2.1.12.130
Drac Ev 1.10.2-2.1.6.263

Not sure if this is related or not, but when we added DE to our modpack, none of the recipes for regular crafting of DE stuff worked either. It would show in the table, but we were unable to remove the items from the table. We used MineTweaker to change the recipe patterns (using same items, just in different order) for all the DE stuff and we can craft them.

**Comment by brandon3055** [comment]
It sounds like you somehow have a recipe mismatch between the client and server. The client thinks the recipes are valid but the server does not. Do you by any chance have hard mode enabled on the client or server? It must be enabled on both.

**Comment by ResqDiver1317** [comment]
Ah, that very well may be the issue. Pretty sure I did enable it on the server and totally did not think about the client side (that'll teach me to work on the pack at 4am)
I'll double check first thing in the morning and report back. If that was the issue, i'll push an update to our pack with the updated config. 
Thanks for the advice. I really hope that is our issue.

**Comment by brandon3055** [comment]
Im sure it is. The issues your seeing are exactly what i would expect to see with a config miss match. 
In fact you were supposed to get a warning when connecting to the server with an option to automatically correct the config mismatch but it seems i durped when setting up that config option so that obviously did not occur.

**Comment by ResqDiver1317** [comment]
Sorry i didn't reply earlier, ended up getting busy IRL. You were absolutely correct about the config miss match (it's like you've see it before or something :)

Thanks for your help!!
