### ISSUE TITLE
Pylon issue

### ISSUE THREAD

**Issue by resinate** [brandon3055/Draconic-Evolution#941]
so i did some testing, i found that INSERTING power has no cap on pylons but exporting from the ball has 2b cap why is this?

**Comment by brandon3055** [comment]
Both input and output are limited to 2billion rf/t this is just due to the fact that the RF api does not actually support numbers large than that. Technically it does not even support storage capacities larger than that but I use some trickery to make it work with the core.

**Comment by brandon3055** [comment]
But keep in mind this limit is only per pylon side

**Comment by resinate** [comment]
ill make a video lol to show u lol ull be shocked when u see this

**Comment by brandon3055** [comment]
Not sure if this is go considered a bug but the issue is with the ducts. If you have say 10 inputs than the outputs are ticked 10 times per tick making it possible to transfer 10 times more energy than would normally be accepted by the receiving device.

**Comment by resinate** [comment]
not a bug it actually sends in above int max lol. i can make it go higher but the particles from u mod cause ALOT of fps drops when using 10+ balls lol

**Comment by brandon3055** [comment]
Yes it is a bug with TD because it allows you to override the input limit of almost any block. I know @covers1624 is aware of this but im not sure if anything is being done to fix it.
