### ISSUE TITLE
[1.10.2] Stabilized Mob Spawner shows up empty, cannot upgrade

### ISSUE THREAD

**Issue by eriongtk** [brandon3055/Draconic-Evolution#944]
**Update: I have tested it more thoroughly, and it seems that JEI (jei_1.10.2-3.14.7.419.jar) is breaking the visuals.**

## Base information
* World type: **Singleplayer world / normal / Biomes o Plenty**
* Game mode: **Survival / Creative**
* Minecraft version: **1.10.2**
* Minecraft Forge version: **forge-1.10.2-12.18.3.2488**
* Liteloader verion: **liteloader-1.10.2**
* DE version:  **Draconic-Evolution-1.10.2-2.1.6.263-universal**
* DE core version: **BrandonsCore-1.10.2-2.1.12.130-universal**
* Mod Pack: **Custom** (Hand picked for my own playstyle, strictly for private use)
* OptiFine version: **OptiFine_1.10.2_HD_U_E3**
* [Full list of installed mods](https://github.com/brandon3055/Draconic-Evolution/files/1398161/mods.txt)

### **Description**

►Installing any mob soul does not show up in the spawner. Spawner starts producing mobs of soul type without any issue.

~~► Unable to right click with nether star - i am assuming it sees the spawner as unconfigured/empty? I am unable to right click with nether star or Gold apples (or otherwise apply any upgrades that is not a Core)~~

► [Spawner shows up unconfigured. It is set to spawn wither skeletons in this particular chamber](https://user-images.githubusercontent.com/32721893/31769132-e430732e-b497-11e7-90fb-913833e29a77.png)

### **Replicating the bug**

Simply place any stabilized  spawner and insert the soul. It will start spawning according to its tier but wont show the soul inside.

* tested with and without optifine? **Yes, bug still persist**
* tested with only DE installed? **Yes, bug still persist**
* tested with re-generating config folder/all default values? **Yes, bug still persists**
*tested with new world? **Yes, bug still persist** (Also, main world was a brand new one, too)

## Base information
* World type: **Singleplayer world / normal / Biomes o Plenty**
* Game mode: **Survival / Creative**
* Minecraft version: **1.10.2**
* Minecraft Forge version: **forge-1.10.2-12.18.3.2488**
* Liteloader verion: **liteloader-1.10.2**
* DE version:  **Draconic-Evolution-1.10.2-2.1.6.263-universal**
* DE core version: **BrandonsCore-1.10.2-2.1.12.130-universal**
* Mod Pack: **Custom** (Hand picked for my own playstyle, strictly for private use)
* OptiFine version: **OptiFine_1.10.2_HD_U_E3**
* [Full list of installed mods](https://github.com/brandon3055/Draconic-Evolution/files/1398161/mods.txt)

### **Description**

►Installing any mob soul does not show up in the spawner. Spawner starts producing mobs of soul type without any issue.

► Unable to right click with nether star - i am assuming it sees the spawner as unconfigured/empty? I am unable to right click with nether star or Gold apples (or otherwise apply any upgrades that is not a Core)

► [Spawner shows up unconfigured. It is set to spawn wither skeletons in this particular chamber](https://user-images.githubusercontent.com/32721893/31769132-e430732e-b497-11e7-90fb-913833e29a77.png)

► Spawner will keep wasting souls (removes them from my inventory) if i keep right clicking on it. I have wasted 4 cow souls before i realized that spawner is actually working (Would a sound cue/Audio feedback be possible or helpful upon inserting a soul?)

### **Replicating the bug**

Simply place any stabilized  spawner and insert the soul. It will start spawning according to its tier but wont show the soul inside.

###  tested with and without optifine?
**Yes, bug still persist**
###  tested with only DE installed?
**Yes, ► WORKS FINE ◄**
### tested with adding mods one by one until error occurs?
Yes...oh god. **Just Enough Items seems to cause the error.**

**Comment by brandon3055** [comment]
The rendering issue is a known issue. Still trying to figure that out. But the upgrade system has changed. Please check the info tablet before reporting on things like this because a lot changed between 1.7 and 1.10. You now upgrade the spanners with the different core tiers. So Wyvern, Draconic and Chaotic cores.

**Comment by eriongtk** [comment]
I apologize about the upgrade part. I've only played 1.10.2, no prior experience. Youtube  pretty much only has 1.7.10 information. My mistake.


To be honest i have no idea why Just Enough Items would breaks it. I was trying it out with CTM and Optifine first, but they worked fine with all combinations.
 only when i ran it with JEI it was bugged. Anyway, it is a minor issue. Would you consider adding a sound cue if a soul is installed? (could play a random sound respective to mob or portal sound or something)

**Comment by brandon3055** [comment]
Probably not a bad idea regardless but the better solution will be to fix the issue... As soon as i track it down.

**Comment by eriongtk** [comment]
Ok, this is weird. I could not reproduce this issue reliably. I have noticed a trend though. I have tried as many combinations...this happens randomly. It must have been a coincidence before :/

![This is something I have found, all mods installed](https://gfycat.com/PopularLawfulBeardedcollie)

**Comment by brandon3055** [comment]
I was thinking it may be an issue with another mod that only shows itself when NEI is installed. Maby when some item from that mod is displayed in NEI or something... Who knows...

**Comment by eriongtk** [comment]
Honestly, at this point i have no idea what is causing it. I have a flying suspicion that it has something to do with a combo of mods - like optifine and jei or something. What is interesting though is the fact that it works, but it stops working as soon i change angle - Maybe it is a clipping/normal issue? 

Based on this, i have tested one more thing:

I went back to main menu, then loaded the map again.

Sure enough, the mob soul was there all the way until i moved -- and i have all the mods installed. Maybe this can help narrowing it down?

**Comment by gigabit101** [comment]
Version no longer supported.
