### ISSUE TITLE
Need help with the chaotic tier of the items.

### ISSUE THREAD

**Issue by joshuasuperboy** [brandon3055/Draconic-Evolution#946]
I want to ask how to get the chaotic tier of the armer and things.

* Minecraft version:1.12.2
* Minecraft Forge version:1.12.2 - 14.23.0.2486
* Mod Pack:Draconic Evolution

When i go into the R tab in the fusion crafting core i then go to the chaotic tier of things it is invisible for the item. Like in this photo below.
![2017-10-20_19 00 01](https://user-images.githubusercontent.com/32559193/31845694-7ce7aba2-b5b8-11e7-9a4e-e902c3d818d9.png)

I do not know why its not showing up. I think its not in the mod if its not in the mod then let me know and thanks.  That is all i needed help with.

**Comment by covers1624** [comment]
If you hover your mouse over the slot is there an item? If so, I'd say it's a dynamic model loading error and we will need your full log file.

**Comment by joshuasuperboy** [comment]
no its not covers1624 i hover over the item thats invis and dose not say a tool tip

**Comment by covers1624** [comment]
Then it's likely not implemented, I'll let Brandon close this out as I'm only 90% sure this is the case.

**Comment by brandon3055** [comment]
What your seeing is a dynamically generated upgrade recipe.  There aren't currently any items that accept chaotic upgrades.  These will be implemented in a future re write of DE
