### ISSUE TITLE
advanced stabilizers ?

### ISSUE THREAD

**Issue by kaceytron** [brandon3055/Draconic-Evolution#948]
i built the tier 8 energy core and put the stabilizers on within 16 blocks it says core is valid but that i need advanced stabilizers but there  is no advanced stabilizer in jei or in guide book 

minecraft 1.12.2 
forge version 14.23.0.2515

**Comment by brandon3055** [comment]
Oh hay! Look what i found in **MY** Guide Book!
![](http://ss.brandon3055.com/813napj.png)

**Comment by kaceytron** [comment]
yes i have built the 9 stabilizers together  i have built there tier 8 before but it still says need advanced
