### ISSUE TITLE
crash de brandonscore 1.12.2 2.3.3.132

### ISSUE THREAD

**Issue by Doniant** [brandon3055/Draconic-Evolution#949]
Hello
When I want to run my minecraft with the version of brandonscore 1.12.2 2.3.3 minecraft crash

I am with the version of forge 1.12.2-14.23.0.2515 and I turn on modpack custom
When I throw it I get it:
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game

Please help me

**Comment by GreatOrator** [comment]
Please provide a link to the full crash log so we can better determine the cause of the crash.

**Comment by Doniant** [comment]
Ok it's good I solved the problem it was chisel who was crashing and not brandons core ^^
Sorry for the inconvenience and thank you anyway
