### ISSUE TITLE
Achievements not unlocking correctly

### ISSUE THREAD

**Issue by darkerfalz** [brandon3055/Draconic-Evolution#952]
## Description
Achievements are not unlocking correctly when I create the item necessary.

I created blocks of awakened draconium and the Advanced Dislocator, and the achievements didn't pop.

I also tried dropping them and picking them back up to see if I had to get them into my inventory like that, and it still didn't work.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2422
* Mod Pack: SkyFactory 3 3.0.14
* Draconic Evolution version: 1.10.2-2.1.5.262 (2.1.5)

**Comment by brandon3055** [comment]
I believe enchantments may be a little broken in 1.10 and they need a complete re write in 1.12 due to the new Advancements system. I will get to them eventually.
