### ISSUE TITLE
Energy Storage Core can only store INT_MAX rf at most.

### ISSUE THREAD

**Issue by xinyuan-liu** [brandon3055/Draconic-Evolution#953]
## Description
![image](https://user-images.githubusercontent.com/17433503/32274286-137fc2de-bf41-11e7-95dd-1932bf59c35e.png)
It refused to receive any more RF.
## Base information
* Minecraft version: 1.12
* Minecraft Forge version: 14.23.0.2517
* Mod Pack: Modern Skyblock 2

**Comment by covers1624** [comment]
Duplicate: https://github.com/brandon3055/Draconic-Evolution/issues/924
