### ISSUE TITLE
Player Heads

### ISSUE THREAD

**Issue by DigitalSketch** [brandon3055/Draconic-Evolution#955]
## Description
I'm not sure where to ask this, and it seems pretty specific so I can't find an answer.  Sorry if this is the wrong place to ask.  I'm attempting to add an end-game craft that gives a certain player head.  I'm testing with it, and can't seem to get it to work.  I've tried a bunch of things such as: "result": "[minecraft:skull]:1,3,{SkullOwner:'\''DigitalSketch'\''}" or "result": "[minecraft:skull]:1,3,{Id:4f6a5821-5583-4d60-b4d7-7c4e8d02e2a3}" and others.  Is there a way to do this?
## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: 14.23.0.2512
* Mod Pack: Testing

## Crash report
```
CRASH REPORT HERE 
NA
```

**Comment by brandon3055** [comment]
If you have the item nbt correct then it would be 
"result": "minecraft:skull,1,3,{SkullOwner:DigitalSketch}" 
Unless the username is actually '''DigitalSketch''' with the apostrophes then it would be 
"result": "minecraft:skull,1,3,{SkullOwner:'''DigitalSketch'''}"
