### ISSUE TITLE
Item Dislocator Picks up XP Infinitely

### ISSUE THREAD

**Issue by KaPowXD** [brandon3055/Draconic-Evolution#956]
## Description
As above both of the draconic magnets pick up xp that no longer exist in the world, Forever.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1614
* Mod Pack: Project Ozone 2 Reloaded 2.3.0

## Crash report
No Crash Report

**Comment by brandon3055** [comment]
If the xp does not exist in world then it would not get picked up.
I suspect you have another issue with client side xp entities that for some reason are not getting removed when they are removed server side.

**Comment by KaPowXD** [comment]
this only happens when magnet is turned on near where I used to kill mobs with diamond spikes.
Vacuum hopper was collecting the xp.
Any place you can point me to fix the client/server issue if that is the case?

**Comment by KaPowXD** [comment]
I am going to close this.
It was client/server inconsistencies.
Turns out the server had stopped auto restarting for some reason.. fixed after a restart =) Thanks!
