### ISSUE TITLE
Energy crystals not showing icons

### ISSUE THREAD

**Issue by ouroborus** [brandon3055/Draconic-Evolution#958]
## Description
Energy crystals are not showing icons in inventories or JEI.

![2017-11-07_17 51 35](https://user-images.githubusercontent.com/392047/32527978-6aaa41d0-c3e5-11e7-8033-46b23ba41c0c.png)

## Base information
* Minecraft version: 1.12.2
* Minecraft Forge version: 12.23.0.2517
* Mod Pack: All the Mods 3 4.4

**Comment by brandon3055** [comment]
Can you post your full log and also check if ender storage items/block have the same issue as they are rendered using the same system.

**Comment by ouroborus** [comment]
The ender chests show up fine.

![2017-11-08_01 37 58](https://user-images.githubusercontent.com/392047/32542247-ce456cf6-c426-11e7-8ecd-b57c91cc2ab0.png)

I'm not sure which log file you want.

**Comment by ouroborus** [comment]
Further testing shows the icons don't show up on drops either. The placed objects are fine.

![2017-11-08_14 36 29](https://user-images.githubusercontent.com/392047/32578547-7cb1f9b0-c492-11e7-9c65-3993d73d4ec4.png)
In this screenshot, there's a dropped crystal next to the placed crystal.

**Comment by brandon3055** [comment]
Rendering is handled client side so will need the client log fml-client-latest.log

**Comment by ouroborus** [comment]
[fml-client-latest.log](https://github.com/brandon3055/Draconic-Evolution/files/1457126/fml-client-latest.log)

**Comment by Ravalli03** [comment]
I'm also having this same issues. items are invisible in JEI and invertory. Once  placed they appear. V. 1.12.2

**Comment by JojotoRudess** [comment]
Hello, I'm also having the same issue.

Minecraft version: 1.12.2
Minecraft Forge version: 14.23.1.2587
Mod Pack: allthemods 3 v.5.7c

I don't know if it's useful but I've recently played with this version of DE in the DW20 1.12.2 pack and didn't have this issue.

Here's my log:

[fml-client-latest.log](https://github.com/brandon3055/Draconic-Evolution/files/1670639/fml-client-latest.log)

Thanks.

**Comment by JojotoRudess** [comment]
Just rechecked with the latest DW20 pack (v1.8) and the problem is not there. I'm no expert, but I'm guessing is a mod compatibility issue with some mod in the ATM pack?

![screenshot_1](https://user-images.githubusercontent.com/35880534/35487063-340d76ae-0456-11e8-8642-a6e5254e0a90.png)

**Comment by ouroborus** [comment]
@JojotoRudess On the other hand, there are ~200 mods in ATM3 and, aside from DE, none of them have this problem.

**Comment by JojotoRudess** [comment]
@ouroborus True, but what's your point? I mean if the crystals render perfectly in modpack A but not on modpack B isn't it logical to think that the problem comes from a compatibility issue in modpack B?

I'm not trying to be snarky, I'm honestly curious on what you're trying to say.

**Comment by ouroborus** [comment]
@JojotoRudess You're right. I was thinking you were saying "not our problem because mod conflict that's not us, we're perfect" (there's a lot of this amoungst the various mod repos) rather than you saying "here's a set of mods that seem to work and so are probably not the issue".

**Comment by ouroborus** [comment]
I've generated a spreadsheet that shows which pack has which mods and allows filtering on those differences. Not sure how useful this is given that ATM3 has quite a few more mods.

https://docs.google.com/spreadsheets/d/1dI2Yy10zgTyRtXTUmwedYQ0bDuU9wS5ix2DzsFiFtL0

**Comment by Ravalli03** [comment]
For me, It ended up being the "connected textures" pack causing it in ATM 1.12.2, on my end

**Comment by ouroborus** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/34

**Comment by JojotoRudess** [comment]
Can confirm that removing the resource pack solved the problem (didn't remove the mod).
