### ISSUE TITLE
"Critical Damage" message causes multiple graves and baubles to drop on server

### ISSUE THREAD

**Issue by Tipsied** [brandon3055/Draconic-Evolution#960]
## Base information
* Minecraft version: 1.10.2
* Mod version: 1.10.2-2.1.0.232
* Minecraft Forge version: 12.18.3.2254
* Mod Pack: (if applicable) SkyFactory2 (SF3) and DireWolf20 (DW20 1.10) (confirmed on these, may be other mod packs as well)
*Multiplayer or single player: Multiplayer 
*Affected features: Baubles and graves while wearing draconic armor 

*Crash report: N/A

Description: 
When fighting the chaos dragon with draconic armor, the message "Critical damage" is received to warn players that their shields are low. Each time a player receives this message, not only does a grave form each time, but if you are wearing baubles, it will drop the baubles as well. Players will then have to break each grave to find their items (if the chaos dragon does not destroy the graves in the meantime as graves are not protected by the destruction like the island is).

**Comment by tyler489** [comment]
Is this on a spongeforge server?

**Comment by brandon3055** [comment]
No reply from OP

**Comment by Tipsied** [comment]
Hi, I thought I replied. Yes, it’s on a spongeforge server. I have not tested it on a server without spongeforge.
