### ISSUE TITLE
I'm getting a crash

### ISSUE THREAD

**Issue by R4ss1n** [brandon3055/Draconic-Evolution#964]
## Base information
* Minecraft version: 1.12.2
* Mod version: 1.12-2.3.5.269-deobf
* Minecraft Forge version: 14.23.0.2517
* Mod Pack: Into the Twilight

## Crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2-deobf.jar)
  BCModPlugin (backpacks 1.12.2 - 3.4.1.jar)
  AstralCore (astralsorcery-1.12.2-1.7.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63-deobf.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 11/13/17 1:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Draconic Evolution (draconicevolution)
Caused by: java.lang.NoSuchFieldError: EMPTY
	at com.brandon3055.draconicevolution.client.creativetab.DETab.<clinit>(DETab.java:16)
	at com.brandon3055.draconicevolution.DraconicEvolution.<clinit>(DraconicEvolution.java:30)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 307372936 bytes (293 MB) / 1397227520 bytes (1332 MB) up to 5965348864 bytes (5689 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6400m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2517 83 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                              | Signature                                |
	|:----- |:------------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                 | 1.12.2                   | minecraft.jar                                       | None                                     |
	| UC    | mcp                       | 9.42                     | minecraft.jar                                       | None                                     |
	| UC    | FML                       | 8.0.99.99                | forge-1.12.2-14.23.0.2517.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                     | 14.23.0.2517             | forge-1.12.2-14.23.0.2517.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | uncraftingtable           | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar                 | None                                     |
	| UC    | actuallyadditions         | 1.12.2-r124              | ActuallyAdditions-1.12.2-r124.jar                   | None                                     |
	| UC    | akashictome               | 1.2-10                   | AkashicTome-1.2-10.jar                              | None                                     |
	| UC    | craftstudioapi            | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar               | None                                     |
	| UC    | animania                  | 1.3.6.1                  | animania-1.12.2-1.3.6.1.jar                         | None                                     |
	| UC    | tammodized                | 0.15.3                   | TamModized-1.12.1-0.15.3.jar                        | None                                     |
	| UC    | aov                       | 0.6.2                    | AoV-1.12.1-0.6.2.jar                                | None                                     |
	| UC    | jei                       | 4.8.0.114                | jei_1.12.2-4.8.0.114.jar                            | None                                     |
	| UC    | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                          | None                                     |
	| UC    | aroma1997core             | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2-deobf.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UC    | aroma1997sdimension       | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar   | None                                     |
	| UC    | astralsorcery             | 1.7.2                    | astralsorcery-1.12.2-1.7.2.jar                      | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UC    | autoreglib                | 1.3-15                   | AutoRegLib-1.3-15-deobf.jar                         | None                                     |
	| UC    | backpacks16840            | 3.4.1                    | backpacks 1.12.2 - 3.4.1.jar                        | None                                     |
	| UC    | badwithernocookiereloaded | 1.12.2-2.12              | badwithernocookiereloaded-1.12.2-2.12.jar           | None                                     |
	| UC    | baubles                   | 1.5.1                    | Baubles-1.12-1.5.1.jar                              | None                                     |
	| UC    | bdlib                     | 1.14.3.10                | bdlib-1.14.3.10-mc1.12.2.jar                        | None                                     |
	| UC    | betterbedrockgen          | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar               | None                                     |
	| UC    | betterbuilderswands       | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70-dev.jar | None                                     |
	| UC    | bibliocraft               | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                   | None                                     |
	| UC    | biomesoplenty             | 7.0.1.2302               | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar       | None                                     |
	| UC    | blockcraftery             | 0.1.3                    | blockcraftery-0.1.3.jar                             | None                                     |
	| UC    | bookshelf                 | 2.2.489                  | Bookshelf-1.12.2-2.2.489.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | botania                   | r1.10-350                | Botania r1.10-350.jar                               | None                                     |
	| UC    | codechickenlib            | 3.1.3.313                | CodeChickenLib-1.12-3.1.3.313-deobf.jar             | None                                     |
	| UC    | redstoneflux              | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar             | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | brandonscore              | 2.3.4                    | BrandonsCore-1.12-2.3.4.134-deobf.jar               | None                                     |
	| UC    | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                            | None                                     |
	| UC    | chesttransporter          | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                     | None                                     |
	| UC    | cofhcore                  | 4.3.6                    | CoFHCore-1.12-4.3.6.14-universal.jar                | None                                     |
	| UC    | cofhworld                 | 1.0.1                    | CoFHWorld-1.12-1.0.1.8-universal.jar                | None                                     |
	| UC    | craftingtweaks            | 8.1.6                    | CraftingTweaks_1.12.1-8.1.6.jar                     | None                                     |
	| UC    | crafttweaker              | 4.0.9                    | CraftTweaker2-1.12-4.0.9.jar                        | None                                     |
	| UC    | ctgui                     | 1.0.0                    | CraftTweaker2-1.12-4.0.9.jar                        | None                                     |
	| UC    | crafttweakerjei           | 2.0.0                    | CraftTweaker2-1.12-4.0.9.jar                        | None                                     |
	| UC    | custommainmenu            | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar                   | None                                     |
	| UC    | thermalfoundation         | 2.3.6                    | ThermalFoundation-1.12-2.3.6.16-universal.jar       | None                                     |
	| UE    | draconicevolution         | 2.3.5                    | Draconic-Evolution-1.12-2.3.5.269-deobf.jar         | None                                     |
	| UC    | enderstorage              | 2.4.0.122                | EnderStorage-1.12-2.4.0.122-deobf.jar               | None                                     |
	| UC    | mantle                    | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                            | None                                     |
	| UC    | tconstruct                | 1.12-2.7.4.34            | TConstruct-1.12-2.7.4.34.jar                        | None                                     |
	| UC    | theoneprobe               | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                         | None                                     |
	| UC    | immersiveengineering      | 0.12-74                  | ImmersiveEngineering-0.12-74.jar                    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UC    | thermalexpansion          | 5.3.6                    | ThermalExpansion-1.12-5.3.6.20-universal.jar        | None                                     |
	| UC    | exchangers                | 1.12-2.5.2               | Exchangers-1.12-2.5.2.jar                           | None                                     |
	| UC    | extrautils2               | 1.0                      | extrautils2-1.12-1.6.5.jar                          | None                                     |
	| UC    | fastleafdecay             | v14                      | FastLeafDecay-v14.jar                               | None                                     |
	| UE    | sonarcore                 | 5.0.2                    | sonarcore-1.12.2-5.0.2-deobf.jar                    | None                                     |
	| UE    | fluxnetworks              | 3.0.1                    | fluxnetworks-1.12.2-3.0.1-deobf.jar                 | None                                     |
	| UC    | forestry                  | 5.7.0.212                | forestry_1.12.2-5.7.0.212.jar                       | None                                     |
	| UC    | ftbl                      | 4.2.3                    | FTBLib-4.2.3.jar                                    | None                                     |
	| UC    | ftbu                      | 4.2.2                    | FTBUtilities-4.2.2.jar                              | None                                     |
	| UC    | ftbg                      | 1.12.1-1.0.06            | ftbg-1.12.1-1.0.6.jar                               | None                                     |
	| UC    | gravestone                | 1.10.0                   | gravestone-1.10.0.jar                               | None                                     |
	| UC    | hardcorequesting          | 1.12                     | HQM-Beyond-1.12.x-5.2.0Alpha1.jar                   | None                                     |
	| UC    | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63-deobf.jar                      | None                                     |
	| UC    | jeiintegration            | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar                  | None                                     |
	| UC    | keywizard                 | 1.10.2-1.5               | keywizard-1.12.2-1.5.2.jar                          | None                                     |
	| UC    | minemenu                  | 1.6.3                    | MineMenu-1.12.2-1.6.3-universal.jar                 | None                                     |
	| UC    | morpheus                  | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                             | None                                     |
	| UC    | neat                      | 1.4-15                   | Neat 1.4-15.jar                                     | None                                     |
	| UC    | radixcore                 | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-deobf.jar                    | None                                     |
	| UC    | reauth                    | 3.5.2                    | ReAuth-3.5.2.jar                                    | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UC    | storagedrawers            | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                     | None                                     |
	| UC    | refinedstorage            | 1.5.22                   | refinedstorage-1.5.22.jar                           | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UC    | rftools                   | 7.13                     | rftools-1.12-7.13.jar                               | None                                     |
	| UC    | rftoolsdim                | 5.05                     | rftoolsdim-1.12-5.05.jar                            | None                                     |
	| UC    | spartanshields            | 1.3a                     | SpartanShields-1.12-1.3a.jar                        | None                                     |
	| UC    | thermaldynamics           | 2.3.6                    | ThermalDynamics-1.12-2.3.6.13-universal.jar         | None                                     |
	| UC    | thutcore                  | 5.11.9                   | thutcore-5.11.9.jar                                 | None                                     |
	| UC    | thutcore_compat           | 1.0                      | thutcore-5.11.9.jar                                 | None                                     |
	| UC    | thuttech                  | 6.0.8                    | thuttech-6.0.8.2.jar                                | None                                     |
	| UC    | torchmaster               | 1.6.1.53                 | torchmaster_1.12.2-1.6.1.53.jar                     | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UC    | twilightforest            | 3.3.202                  | twilightforest-1.12.2-3.3.202-universal.jar         | None                                     |
	| UC    | veinminer                 | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e-dev.jar           | None                                     |
	| UC    | veinminermodsupport       | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e-dev.jar           | None                                     |
	| UC    | waystones                 | 4.0.17                   | Waystones_1.12.1-4.0.17.jar                         | None                                     |
	| UC    | xray                      | 1.3.3                    | xray-1.12.2-1.3.4.jar                               | None                                     |
	| UC    | elulib                    | 0.1.7                    | elulib-0.1.7.jar                                    | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CoreMod (Aroma1997Core-1.12.2-1.3.0.2-deobf.jar)
  
BCModPlugin (backpacks 1.12.2 - 3.4.1.jar)
  brad16840.core.ClassTransformer
AstralCore (astralsorcery-1.12.2-1.7.2.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63-deobf.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13497 Compatibility Profile Context 23.20.788.0' Renderer: 'AMD Radeon R7 200 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

I have know idea what is causing it to crash.

**Comment by covers1624** [comment]
You have the deobfuscated jar installed, this jar is for mod developers, make sure you have the universal jar.

**Comment by Zer0Lyfe** [comment]
the twitch launcher is causing this to happen with certain mods.(DE/Sonar core/Dark utils/Brandon's core just to name a few).

**Comment by brandon3055** [comment]
Not just Brandon's Core.
![](http://ss.brandon3055.com/5q7mmvv.png)

**Comment by Zer0Lyfe** [comment]
yeah it is basically affecting like 70% of my mods so i don't know how they managed to do it this time.
