### ISSUE TITLE
Cannot process Nether or Ender Draconium Ore in any way. I am using 1.10.2, and I mined a whole bunch with my Digital Miner from Mekanism. I silk touch mine to process ores more efficiently, however, I can't even put the Nether or End Draconium ores through a furnace of any kind. I was wondering if it would be possible to get processing support for them similar to the overworld generated Draconium Ore. In addition, the Nether and End Draconium ores do not have an ore ID. What I mean by this is that the Overworld Draconium Ore has the Ore ID oreDraconium however the ones from the Nether and the End have no such ID, therefore it is not possible to mine them with anything that uses ore IDs to find ores, such as the Digital Miner

### ISSUE THREAD

**Issue by araevingaming** [brandon3055/Draconic-Evolution#965]
## Base information
* Minecraft version:
* Mod version:
* Minecraft Forge version:
* Mod Pack: (if applicable)

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by covers1624** [comment]
Please create a new issue with the correct information, the issue title is NOT the place to write an essay.
