### ISSUE TITLE
[1.10.2 Sky Factory 3] Draconic Shield has no Invincibility-frames

### ISSUE THREAD

**Issue by Penquin8** [brandon3055/Draconic-Evolution#966]
## Base information
* Minecraft version: 1.10.2
* Mod version: Draconic-Evolution-1.10.2-2.1.6.263-universal
* Minecraft Forge version: 12.18.3.2477
* Mod Pack: Sky Factory 3 (v1.15)

*Crash report: N/A

My draconic armor's shield has no invincibility-frames, so it takes damage constantly (presumably every tick), this makes any boss fight I intend to melee nearly impossible, as they can often eat through my shields in less than 30 seconds. Even Extra-Utils spikes can destroy my shield in seconds.

Edit: I've done some experimenting, and the issue persists even when the mod is on its own, with no other mods, and no other mod configs.

**Comment by brandon3055** [comment]
This is intended to balance out the overpoweredness of the shield a bit.  But it definitely isn't a perfect solution.
When I get around to re writing the shield I will be making improvements

**Comment by Penquin8** [comment]
Ah, I figured it might have been something like that, thanks for the response.
