### ISSUE TITLE
[Suggestion] Remove client warning on server config change

### ISSUE THREAD

**Issue by Yorkforce** [brandon3055/Draconic-Evolution#968]
It all looks fancy and that but we're entering silly territory here, most people play with modpacks which includes 100's of mods, if they all start adding huge warning notices right in your face when logging into a server thats edited the server configs, players are going to spend 20 mins just getting past it.

Less people are playing minecraft these days, let's not give them more reasons to stop playing please!

At least add a config option to ignore server config change warnings, it makes no real difference ingame and any information about disabled items we can tell them via our own communications or via JEI tooltips.

**Comment by brandon3055** [comment]
Sorry but your argument is kinda pointless. I have had way to many issues reported that were related to config mismatches not to mention the countless players and server owners that have requested this feature be added. In my opinion this should be a part of every mod. Sure that could get a bit messy when you login to a server for the first time but thats only an argument for forge to add something to handle this so mods dont have to.  

Furthermore this gui only shows up for config options that MUST be the same on both the client and server and also require a client restart to change. The type of config options that break the game or damage the user experience if they do not match. If all of the changes can be made run time without a restart they are applied automatically without the user even knowing and then reset to their original settings when the user disconnects from the server. 

But hay if you really hate the popup that much maby i will add an option to disable it and instead let the game crash with a error message that the user wont understand, at which point the user will report the crash to me and i will tell them to go yell at you.

**Comment by Yorkforce** [comment]
We have a few items disabled on our server from Draconic Evolution, none of them cause any major gameplay issues or cause any crashes but I get it, I wish it was default minecraft behaviour to sync config changes automatically on joining a server, it would be an ideal solution.

But this warning message is pretty aggressive imo and forcing a client restart due to some disabled items is pretty extreme. How about a silent option to automatically do it?

I have been running servers for around 6 years now and it's a constant battle to maintain that first login experience a player has when they join our server for the first time, mods have been scrolling off our MOTD, using popups and other methods that just end up spamming the player relentlessly every time they log in.

I understand players come here and complain, believe me we get our fair share of that and we do our best to relay bug reports and issues to mod devs in a mutually beneficial way, but there must be a better way of doing this other than forcing client restarts and putting up a big warning message when a player logs into a server?

**Comment by brandon3055** [comment]
Fair point. Perhaps i will add a less invasive mode that allows the player to join but gives them a chat message informing them that their config does not match the server so thing may be broken. And give them a clickable chat button that will open the original gui.

**Comment by Yorkforce** [comment]
That would be much better I think, it does run the risk of being missed which could cause more issues for you with players complaining but to config mismatch.

Maybe allow that message to show on say the first instance then trigger the full screen warning on a client restart? Not sure if that would be possible, but that way the player can at least jump on and start playing straight away, then be 'encouraged' to sync the config later?
