### ISSUE TITLE
[1.12.2]Energy Core can't go over Max Int

### ISSUE THREAD

**Issue by Niuttuc** [brandon3055/Draconic-Evolution#969]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.5.269
* Minecraft Forge version:2512
* Mod Pack: [Custom Mod pack](https://minecraft.curseforge.com/projects/imperacube-main/files/2501592)

## Issue Description
Recently built a tier 4 energy core in a server, with a 9.88BRF capacity. However, upon charging the core, it stops accepting energy at 2'147'483'619, just shy of the maximum integer value.

**Comment by covers1624** [comment]
Duplicate #928 #924 #953  
Please look at the other issues before opening a new one.
