### ISSUE TITLE
Missing Achievement Title

### ISSUE THREAD

**Issue by shadowfacts** [brandon3055/Draconic-Evolution#97]
The achievement that you get when you craft a Draconic Staff has a [description](https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/resources/assets/draconicevolution/lang/en_US.lang#L453) but no title.

I would PR this myself, but  I have no idea what you want the title to be.

**Comment by brandon3055** [comment]
Hmm... Not how did that happen...
The line above that is supposed to be the description  https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/resources/assets/draconicevolution/lang/en_US.lang#L452
Thanks for pointing that out.
