### ISSUE TITLE
Step Height Incorrect in 1.10.2

### ISSUE THREAD

**Issue by madolinn** [brandon3055/Draconic-Evolution#970]
As per, #892 
The Step Height is 0.6F in 1.10.2 as well and you may have overlooked it.

https://github.com/brandon3055/Draconic-Evolution/blob/1.10.2/src/main/java/com/brandon3055/draconicevolution/handlers/CustomArmorHandler.java#L332

Causing conflicts with Chisels & Bits specifically when making custom blocks like stairs, unable to traverse them.

##

## Base information
* Minecraft version: 1.10.2
* Mod version: Draconic-Evolution-1.10.2-2.1.6.263-universal
* Minecraft Forge version: 1.10.2-2477
* Mod Pack: (if applicable) Age of Engineering

**Comment by brandon3055** [comment]
This is fixed in 1.12. for 1.10 it will be fixed in the next update.
