### ISSUE TITLE
Expensive end crystal. Why?

### ISSUE THREAD

**Issue by PapiDimmi** [brandon3055/Draconic-Evolution#971]
Why does Draconic Evolution make end crystals require a nether star instead of an eye of ender? A lot of mods use end crystals in their recipes, and Draconic Evolution ruins those mods.

**Comment by GreatOrator** [comment]
Well, one, automating nether stars is extremely easy with the draconic grinder, and two, the dragon hearts for the mod need to be tougher to get

**Comment by PapiDimmi** [comment]
A lot of recipes in other mods that are supposed to be cheap now require a Nether star, which is ridiculous. Maybe dragon hearts should be obtained in a different way.

**Comment by GreatOrator** [comment]
That may be, but the reason they are used in this mod are for good reason as a gate to higher tier stuff, maybe talk to the other mod devs and ask them to change their recipe.

**Comment by brandon3055** [comment]
If you dont like it the ether use minetweaker to modify the effected recipes or disable the recipe change in DE's config. Stop Complaining about an issue when you have already been given the tools to resolve said issue.
