### ISSUE TITLE
Missing enchantment descriptions

### ISSUE THREAD

**Issue by darkhax** [brandon3055/Draconic-Evolution#973]
## Base information
* Minecraft version: 1.12.2
* Mod version: N/A
* Minecraft Forge version: N/A
* Mod Pack: (if applicable) N/A

Hello o/

I noticed that your mod adds a new enchantments. I currently maintain several mods (Enchantment Descriptions, Wawla, and Enchanting Plus) which have systems for giving players info about enchantments. This system uses the id of the enchantment to generate a localization key which is then used to get the enchantment description. I would really appreciate it if you could add support for these mods, and other potential mods by adding descriptions for the following localization key in your mod's language file.

```
enchantment.draconicevolution.enchant_reaper.desc
```

**Comment by brandon3055** [comment]
Sure why not! 

``
enchantment.draconicevolution.enchant_reaper.desc=When applied to a weapon this enchant increases that chance that a mob killed by sad weapon will drop their soul. This enchantment is best applied to Draconic Evolution weapons as it stacks with their built in reaper modifier.
``

Sound good?

**Comment by darkhax** [comment]
Hey, sorry for not responding. I checked your comment out on my phone and then lost track of it later. Thanks for adding support, I really appreciate it!
