### ISSUE TITLE
Draconic Armor has Negative RF after adding RF Capacity Upgrades

### ISSUE THREAD

**Issue by araevingaming** [brandon3055/Draconic-Evolution#974]
## Base information
* Minecraft version: 1.10.2
* Mod version: 1.10.2-2.1.6.263-Universal
* Minecraft Forge version: 1.10.2-12.18.3.2281-Universal
* Mod Pack: (if applicable) Custom Modpack partially derived from Resonant Rise 4

It's not crashing my game, but I don't understand why my armor is at -169803776 RF. and it's not just the boots, it's all of the armor, My boots and Helm have Draconic RF Upgrade, the rest has Wyvern RF Upgrade, and they, including my Draconic bow, are at -84901888 RF, and my Staff is at -254705664 RF, also with Wyverm upgrade
![java 2017-11-28 13-32-49-60](https://user-images.githubusercontent.com/28285198/33343053-4974ece2-d441-11e7-814a-926096934a61.jpg)
In addition, the energy shield is not working. The physical armor provided by the Draconic armor works, I only took half a heart of damage from a creeper exploding next to me, but the shield is at 0/2048.  In addition, the Staff of Power is not working either. It can't even one shot a baby zombie, it won't dig more than one block, it's not digging fast at all, and the attack aoe is not working  either. The bow is not working either, but what's really strange is that with the armor on, I still get the night vision, the flight, the speed boosts, and the jump boost. But the actual shield is not working, and I don't know why. I now have all the armor fully upgraded to Draconic Tier Upgrades, everything has -169803776 RF, and the Staff has -509411328 RF. In addition, the Draconic Capacitor has 1.658BRF out of 640MRF. And I can guarantee that it's not an operator error issue with setting up the armor, because I've used this mod since 1.7.10, it's one of my favorite mods ever, and I'm very familiar with how to set it up. Yet it's still not working correctly

**Comment by araevingaming** [comment]
Since posting this, I have closed and reopened my world, and my Capacitor is now at 639.921MRF/640MRF as opposed to the 1.658BRF/640MRF it was before, but nothing else has changed

**Comment by araevingaming** [comment]
Anybody have any idea what might be going on?

**Comment by brandon3055** [comment]
have you modified the tool configs at all?
