### ISSUE TITLE
Cannot Process Nether or End Draconium Ore

### ISSUE THREAD

**Issue by araevingaming** [brandon3055/Draconic-Evolution#975]
## Base information
* Minecraft version: 1.10.2
* Mod version: 1.10.2-2.1.6.263-Universal
* Minecraft Forge version: 1.10.2-12.18.3.2281-Universal
* Mod Pack: (if applicable) Custom Modpack partially derived from Resonant Rise 4

I cannot process Nether or Ender Draconium Ore in any way. I am using 1.10.2, and I mined a large amount with my Digital Miner from Mekanism. I silk touch mine to process ores more efficiently, However, I can't even put the Nether or End Draconium ores through a furnace of any kind. I was wondering if it would be possible to get processing support for them similar to the overworld generated Draconium Ore. In addition, the Nether and End Draconium ores do not have an ore ID. What I mean by this is that the Overworld Draconium Ore has the Ore ID oreDraconium however the ones from the Nether and the End have no such ID, therefore it is not possible to mine them with anything that uses ore IDs to find ores, such as the Digital Miner

**Comment by ruifung** [comment]
Hmm, brandon, I remember reading on another issue previously where you said you omited the oredict entries for nether and end draconium to prevent them being considered equivalent with regular draconium ores right? In that case would you consider adding different oredict names to them? Such as oreNetherDraconium / oreEndDraconium.

And @araevingaming, just use a block breaker / mechanical miner with fortune III instead.

**Comment by brandon3055** [comment]
I think i may just go the vanilla rout. 
![](http://ss.brandon3055.com/13nglr7.png)
It wold be so incredibly inefficient but it people want it...

**Comment by ruifung** [comment]
ayyy lmao. My main gripe was mainly without having oredict names for the 2 variants, you can't use things like Mekanism's digital miner to selectively target them without having at least one on hand.

**Comment by brandon3055** [comment]
Im not really too concerned about that because it is meant to be kinda hard to get after all.
