### ISSUE TITLE
Add invisibility upgrade to armor

### ISSUE THREAD

**Issue by ruifung** [brandon3055/Draconic-Evolution#976]
Maybe with some of these features:
- Make armor invisible (or mostly invisible) so we can gaze upon our glorious skins.
- Invisibility Effect -like the potions-

Although admittedly I'm mainly wanting the first one though, as the tradeoff between looking nice in your skin and defensive power of draconic armor is hard =D.

**Comment by Skaronator** [comment]
Yes! Damn I want this as well! Hope it'll be added one day.

**Comment by brandon3055** [comment]
ok... Your armor will look like mine in the next release.
![](http://ss.brandon3055.com/ey4eg9a.png)
Dont plan on adding player invisibility.
(This will be restricted to draconic)

**Comment by Skaronator** [comment]
fair enough, thanks!
