### ISSUE TITLE
Armor models

### ISSUE THREAD

**Issue by SimasISuppose** [brandon3055/Draconic-Evolution#978]
## Base information
* Minecraft version:1.10.2
* Mod version:
* Minecraft Forge version:
* Mod Pack: Sky factory 3
I remember there used to be a line in config to enable the old 3D models in 1.7 modpacks and now the config file is totaly different and doesnt have this option, i personaly really dislike the newest blocky models and i would like a way to change em back to the classy 3D models wich look less blocky.

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by brandon3055** [comment]
The update to 1.10+ required a complete er write of the armor renderer and the old models were not update. The only other option you have is the 2D models.
