### ISSUE TITLE
Full Tier 8 Energy Core

### ISSUE THREAD

**Issue by araevingaming** [brandon3055/Draconic-Evolution#979]
Wasn't sure where to put this, but I just thought you'd like to see it

![java 2017-11-29 23-09-32-75](https://user-images.githubusercontent.com/28285198/33416591-ae8b3d92-d55a-11e7-9a73-6a474c507fee.jpg)

**Comment by Tahakk** [comment]
Nice, we are proud of you. Since this is not valid issue close the door behind yourself next time.
