### ISSUE TITLE
Minecraft 1.7.10 crash whit Draconoc Evolution

### ISSUE THREAD

**Issue by xXDarkNovaXx** [brandon3055/Draconic-Evolution#980]
Could it be that Draconic Evolution is not compatible with Thaumik Thinkerer?
Because if I have Thaumik Thinkerer in it without Draconic Evolution in it, it works flawlessly only as soon as I insert Draconic Evolution crashes it starts and in the log is Error Thaumik Thinkerer but Thaumik Thinkerer works fine as long as no Draconic Evolution is in it

Sorry for mistakes, I wrote this with Google Translate because my English is not that good

**Comment by covers1624** [comment]
Would you be able to provide a crash report please? As it stands, 1.7 is nolonger supported, and will be added to the list of all the things 1.7.

**Comment by xXDarkNovaXx** [comment]
[crash-2017-11-30_06.57.22-client.txt](https://github.com/brandon3055/Draconic-Evolution/files/1517109/crash-2017-11-30_06.57.22-client.txt)

As I said when I delete Draconic Evolution it starts without problems
This problem is only when I install Draconic Evolution
The funny thing is that in the log at Thaumik Thinkerer the error is even though there are only problems in connection with Draconic Evolution

**Comment by covers1624** [comment]
Ah, Enchantment id's, You will need to edit DraconicEvolutions configuration file and change the id used for the reaper enchantment.
