### ISSUE TITLE
Holding enchantment for draconic orb

### ISSUE THREAD

**Issue by CTH999** [brandon3055/Draconic-Evolution#984]
So, here's an idea, have the ability to enchant the Draconic Orb Part (The thing in the middle) With Thermal Expansions Holding Enchantment. One idea is to use a percentage, Such as Each Level adds in 5%, meaning Level 4 is +20%, These are just Random Values.

Since it's a Percentage, It helps the Tier one a lot, The Tier 2 even more, and so on. Tie eight is extreme.

P.S. A cool feature/ Easter egg would be to include a feature where when a tier eight has Holding 4, It is "Infinite" (IE 64 Bit Integer limit (Even though it's not a Percentage Change), Or it is similar to the Energy Injector for the draconic generator. Where it will just make more room, and store even more.) Just a funny little idea.

P.P.S. It's your Mod, do what you want. This is just a suggestion.

**Comment by brandon3055** [comment]
So hears the thing.... The current limit for the tier 8... Is already a 64bit integer (long) aka 9,223,372,036,854,775,807, aka a shit tone of power, aka this conversation is pointless.

**Comment by Lukas45** [comment]
Time to invent 128bit systems I guess?

**Comment by CTH999** [comment]
Ah, So-That's why. Ok, good to know.

(By the way Lukas45, I would be theoretically possible, but not with our current computers.)
