### ISSUE TITLE
Config feature request

### ISSUE THREAD

**Issue by tyler489** [brandon3055/Draconic-Evolution#986]
Recently players on my server have been using draconic portals to move mobs to other players islands where they shouldny have access. Even more annoying they filled the spawn with gaia guardians. Would it be possible to have a server side config option to blacklist certain mobs traveling through the portal

**Comment by brandon3055** [comment]
Any good permission management mod/plugin should be able to do this. DE isn't the only mod that can do this.

**Comment by tyler489** [comment]
Unfortunitly im stuck using FTB Claims and FTB Claims refuses to support modded servers and wont block interact events in claims.
