### ISSUE TITLE
Rf stuck at 0.01%

### ISSUE THREAD

**Issue by SimasISuppose** [brandon3055/Draconic-Evolution#987]
## Base information
* Minecraft version: 1.10.2
* Mod version:
* Minecraft Forge version:
* Mod Pack: Skyfactory 3

Tier 7 storage core was built on a server, descriprtion said that it holds 2.1 trilion rf, but it got filled up to 2.147.483.647 and it wont go up it just stays at that and doesnt do anything, if i dont put energy into the ball, it will drop but after i charge it again it wont go above the previously mentioned number.

**Comment by covers1624** [comment]
Duplicate, #928 #924 #953 #969
