### ISSUE TITLE
Chaos guardian crystals keep unrendering. 

### ISSUE THREAD

**Issue by Fearmonger185** [brandon3055/Draconic-Evolution#989]
## Base information
While fighting the chaos guardian the crystals (sometimes ones I've destroyed, sometimes ones that are still healing the dragon) keep vanishing. they are still there because the dragon continues to be healed by them, but i cannot see them or destroy them. The only way to see the crystals is to switch game mods because for some reason that rneders them again briefly, then they vanish about 20 seconds later. This issue makes the fight impossible to do, thus making most end tier stuff unobtainable.
* Minecraft version: 1.10.2
* Mod version: 2.1.7.266
* Minecraft Forge version: 12.18.3.2511
* Mod Pack: (if applicable) Project Ozone Lite

**Comment by brandon3055** [comment]
I really dont know what keeps screwing with the crystals. This has never been an issue in any of my testing but seems to happen in some packs. I will have to look into this when i get a chance.
