### ISSUE TITLE
i found a bug with your stabilized spawners on skyfactory (newest version)

### ISSUE THREAD

**Issue by timanttikuutio** [brandon3055/Draconic-Evolution#990]
## Base information
* Minecraft version: 1.10.2
* Mod version: 1.10.2-2.1.6.263 (2.1.6)
* Minecraft Forge version: 12.18.3.2477
* Mod Pack: skyfactory 3

so i was trying to turn of stabilized spawners with lever then they stopped spawning and i flicked the lever off it didnt start spawning then i reapply the soul and it starts again then i tried to place a block and it stopped again

so the problem is that the spawner stops working if it gets any update

video proof: https://www.youtube.com/watch?v=kZikMLL998k&feature=youtu.be

hope you can fix this fast cuz im planning to build a bigger spawn are and more spawners

and hope you will release the fix to skyfactory 3 too

**Comment by brandon3055** [comment]
This is rather odd... Looking at the code i dont see anything that would, cause this and i am unable to reproduce it in dev. I will have to spin up the pack when i get a chance and do some in game testing.
