### ISSUE TITLE
Infinit Power with Draconic Storage Multi Block

### ISSUE THREAD

**Issue by DevilAdvocate02** [brandon3055/Draconic-Evolution#991]
## Base information
* Minecraft version: 1.7.10
* Mod version: 1.0.2h
* Minecraft Forge version: 10.13.4.1614
* Mod Pack: Ozone2 Reloaded 2.4.0 (Single Player)

## Crash report

NOT A CRASH
![2017-12-07_08 20 29](https://user-images.githubusercontent.com/22227958/33692291-8c45498a-db27-11e7-8696-491160e7507f.png)

Power keeps rising past the 2.14Trillion RF and does not seem to stop.

Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by brandon3055** [comment]
Given how long the 1.7.10 version has been stable im going to assume that there is some other factor causing issues with the core. Regardless this should not be a problem in 1.10+

**Comment by DevilAdvocate02** [comment]
It seems to have sorted itself out somehow as it is now behaving normally like it should not sure how or what happened there.
