### ISSUE TITLE
[1.7.10] Image problem while wearing DE Armor and open ChromatiCraft Lexicon

### ISSUE THREAD

**Issue by chaos234** [brandon3055/Draconic-Evolution#992]
Hey Brandon,

I know that you no longer release updates in general for the 1.7.10 Version of DE but would it be possible to take a look into this problem: http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=30134

Like figured out it only occures while the player wears any pice of DE Armor which results in this curios problem that he Lexicon from Chromaticraft misses one image which turns the index page of it white which is a problem.

It happends in v16-19 from DragonAPI + ChromatiCraft and with the latest DE Version which is currently available frome curse.

I hope and please you to finde the problem so that we can use the Lexicon while we are wearing DE Armor.

**Comment by chaos234** [comment]
@brandon3055 anything found related to this reported problem yet?

**Comment by brandon3055** [comment]
I will add this to my todo list if i ever release get around to pushing a new build.

**Comment by chaos234** [comment]
Would be nice if you could find the problem. I don't think that it is the armor itself.
I think it is related to the GUI which is then active when you wear one part. Because
holding e. g. the Staff of Power does not triggers it, also not holding the Enhanced Charm of
Dislocation.
