### ISSUE TITLE
Stabilizers for all Energy Core do not work for me?

### ISSUE THREAD

**Issue by Jac121gw** [brandon3055/Draconic-Evolution#993]
Base information

Minecraft version: 1.12.2
Mod version: 1.12.2.3.5.269
Minecraft Forge version: 1.12.2-forge1.12.2-14.23.1.2558
Mod Pack: no pack
Crash report

NOT A CRASH
![2017-12-10_16 54 14](https://user-images.githubusercontent.com/34426641/33810498-d4a1066a-ddca-11e7-9504-94c7b4884a13.png)

Stabilizers for all Energy Core do not work

**Comment by covers1624** [comment]
Err, how many stabilizers do you have placed, from the angle of your screenshot it seems you only have 1, you need 4..

**Comment by brandon3055** [comment]
No reply from OP.

**Comment by Jac121gw** [comment]
Sorry I am so late but yes I do have 4,I had over 100+ message to go
through and just saw this email.
