### ISSUE TITLE
Tool enchantes

### ISSUE THREAD

**Issue by Goten87** [brandon3055/Draconic-Evolution#997]
## Base information
* Minecraft version: 1.12.2
* Mod version: 3.4.25
* Minecraft Forge version: 14.23.1.2555
* Mod Pack: Direwotlf20 1.12

## Crash report
```
None
```
just have a question dint know where to ask it so sorry to ask it here
i played the mod last in 1.7.2 i think
back then u had the option to put a enchanted book in a tool to get the enchant
i liked that u can take out enchants and chance them as u go
so why in 1.12.2 is that gone :( i miss it so bad already and i dont like to enchant my tools so the books where perfect for that

**Comment by brandon3055** [comment]
Thats system was specifically implemented to work around a limitation which made it impossible to enchant the tools normally. Thats system was very hacky and had some issues so when forge fixed the enchanting issue i chose to remove it. You should be able to disable enchants via the config gui though that can also be a little buggy at the moment.

**Comment by brandon3055** [comment]
oops added that label to the wrong issue xD

**Comment by Mr-Rixa** [comment]
Found toggles for enchants on tools/weapons, but how about toggling armor enchants on/off eg. frost walker?

**Comment by brandon3055** [comment]
The system i wrote for tools has turned out to be rather buggy. I need to find a better way to handle this than i will apply it to both the tools and the armor.
