### ISSUE TITLE
1.10.2 (MINOR BUG) Celestial Manipulator's buttons are a bit mixed up

### ISSUE THREAD

**Issue by 23Link89** [brandon3055/Draconic-Evolution#999]
## Base information
* Minecraft version: 1.10.2
* Mod version: 2.1.7-266
* Minecraft Forge version: 12.18.3.2551
* Mod Pack: (if applicable) Custom

## Crash report
N/A

So in the celestial manipulator if you select the "Start Rain" button, it'll start a storm, if you select the "Start Storm" button it'll create regular rain. It's a really minor bug, though it's just confusing if you don't know about it.

**Comment by brandon3055** [comment]
I looked into this and i think you may have just got unlucky with minecrafts RNG. How much did you test this issue?

**Comment by 23Link89** [comment]
Just fired up my game and test it like 20 times, the buttons 100% of the time create wrong storms. Commands for thunderstorm and rain work fine giving the intended affect.

**Comment by brandon3055** [comment]
I have triple checked the code confirmed in dev. Is it possible one of the other mods you have installed is adjusting weather behavior?

**Comment by 23Link89** [comment]
Shouldn't be, I don't have any custom weather mods. Are there types of mods I should try disabling first?

**Comment by brandon3055** [comment]
No idea may just be some random mod making thunder storms more common or something.
